src/uu/echo/src/echo.rs, tests/by-util/test_echo.rs
Testing with `gecho` on macos outputs a nul character for a `\0` that isn't followed by a valid octal digit
=> echo: Allow echo with escapes to work with `\0`

src/uu/hostid/src/hostid.rs
Addresses https://github.com/uutils/coreutils/issues/2990
Added the description for the **hostid** command. Please let me know if you need me to add anything else apart from the description.
=> hostid: added description in documentation

src/uu/false/src/false.rs, src/uu/true/src/true.rs, tests/by-util/test_false.rs, tests/by-util/test_true.rs
This acknowledges a quirk in GNU `true` and makes `true` and `false` behave consistent to it.
Now treats recognized command line options and ignores unrecognized
command line options instead of returning a special exit status for
them.
`true` may return a non-true exit status (in particular EXIT_FAIL) 
if writing the diagnostics of a GNU specific option fails. For example,
`true --version > /dev/full` would fail and have exit status 1. See commits
for more details.
This now passes `tests/misc/false-status.sh`.
Closes: #3007, #2996, #2989
=> Make true return false less frequently

src/uu/truncate/src/truncate.rs, tests/by-util/test_truncate.rs
Exit with status code 1 for argument parsing errors in `truncate`. When `clap` encounters an error during argument parsing, it exits with status code 2. This causes some GNU tests to fail since they expect status code 1.
Closes #2951
=> truncate: change cli error return code

tests/by-util/test_sort.rs
Currently failing on my Windows machine
```shell
PS C:\Users\Hanif\git\coreutils> cargo t --quiet -- test_sort::test_output_is_input
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 21 filtered out; finished in 0.00s
running 1 test
F
failures:
---- test_sort::test_output_is_input stdout ----
current_directory_resolved:
touch: C:\Users\Hanif\AppData\Local\Temp\.tmpmpU3Qq\file
write(append): C:\Users\Hanif\AppData\Local\Temp\.tmpmpU3Qq\file
run: C:\Users\Hanif\git\coreutils\target\debug\coreutils.exe sort -m -u -o file file file file
thread …
```
=> test_sort: Preserve the environment variable when executing tests

src/uucore/src/lib/mods/backup_control.rs, tests/by-util/test_cp.rs, tests/by-util/test_install.rs, tests/by-util/test_ln.rs, tests/by-util/test_mv.rs
Closes https://github.com/uutils/coreutils/issues/2985
The issue was also present for `ln`, `install` and `mv`, which use the same option.
=> `uucore`: allow backup suffix with hyphen value

.gitattributes, .vscode/.gitattributes, .vscode/cSpell.json, .vscode/extensions.json
Since JSON formally cannot contain comments, GitHub highlights comments in JSON files as errors, but the configuration files for VS Code in this repository contain comments. In this PR, I try to configure GitHub to use a different syntax highlighter for the affected files.
See [documentation of Linguist overrides](https://github.com/github/linguist/blob/master/docs/overrides.md).
Unfortunately, it is not clear to me whether this works or not. I see the `cSpell.json` with properly formatted comments but the `extensions.json` with comments marked as errors. And that is independently of whether I look at a branch with this change in or out.
=> Allow comments in VS Code configuration

src/uu/printf/src/printf.rs
Addresses https://github.com/uutils/coreutils/issues/2993
Hello! First time (attempting to be an) open-source contributor. I've made changes so that the user docs display a version number and a brief description, though I was curious if this would be the best way to do so. 
The existing code was written so that the `--help` and `--version` arguments for printf did not use clap to auto-format, and therefore do not have colorized text and a consistent structure compared to other commands that do. I've currently kept it that way in this PR, overwriting `help` and `version` defaults because I'm unsure how I would prevent clap from creating `-h` and `-V` in the documentation, which seems like it would make things inconsistent with GNU documentation - let me know if I should just default to …
=> printf: add description and version

tests/by-util/test_printf.rs
Using this escaped character will cause `printf` to stop generating characters.
For instance,
```rust
hbina@akarin ~/g/uutils (hbina-add-test-for-additional-escape)> cargo run --quiet -- printf "%s\c%s" a b
a⏎
```
Signed-off-by: Hanif Ariffin <hanif.ariffin.4326@gmail.com>
=> test_printf: add test for additional escape (\c)

src/uu/head/src/parse.rs, src/uu/tail/src/parse.rs, tests/by-util/test_head.rs, tests/by-util/test_stat.rs, tests/by-util/test_tail.rs
Signed-off-by: Hanif Bin Ariffin <hanif.ariffin.43262@gmail.com>
=> tail&head: dont use is_numeric to check for digits

src/uu/base32/src/base32.rs, src/uu/base64/src/base64.rs, src/uu/basenc/src/basenc.rs
=> basenc, base64 and base32 have an ABOUT that's formatted differently than the other utils

src/uucore/src/lib/features/tokenize/sub.rs, tests/by-util/test_printf.rs
Previously, `printf %0n` would pad the output with spaces instead of `0`. This PR updates the behavior to pad with `0` when specified.
=> printf: Support leading zeroes with %0n formatting

.github/workflows/CICD.yml, .github/workflows/GnuTests.yml, util/run-gnu-test.sh
- consolidate configuration
- DRY improvements
- improve flexibility/robustness in the face of missing reference test info
- add reference test info IDs and additional logging to help diagnose testing failures
- includes parallel refactor of 'util/run-gnu-test.sh'
=> maint/CICD ~ implement 'GnuTests' workflow fixes/refactor

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
This addresses the GNU test `cp/dir_vs_file`. Previously, uutils would ignore failures caused by copying directories to files, and return an exit code of 0 even though the copy didn't suceed. GNU expects an exit code of 1.
=> cp: Fail when copying a directory to a file

tests/by-util/test_ls.rs
```shell
---- test_ls::test_ls_order_time stdout ----
current_directory_resolved:
touch: C:\Users\Hanif\AppData\Local\Temp\.tmp2wgS4L\test-1
write(append): C:\Users\Hanif\AppData\Local\Temp\.tmp2wgS4L\test-1
touch: C:\Users\Hanif\AppData\Local\Temp\.tmp2wgS4L\test-2
write(append): C:\Users\Hanif\AppData\Local\Temp\.tmp2wgS4L\test-2
touch: C:\Users\Hanif\AppData\Local\Temp\.tmp2wgS4L\test-3
write(append): C:\Users\Hanif\AppData\Local\Temp\.tmp2wgS4L\test-3
touch: C:\Users\Hanif\AppData\Local\Temp\.tmp2wgS4L\test-4
write(append): C:\Users\Hanif\AppData\Local\Temp\.tmp2wgS4L\test-4
open: C:\Users\Hanif\AppData\Local\Temp\.tmp2wgS4L\test-3
run: C:\Users\Hanif\git\coreutils\target\debug\coreutils.exe ls -al
run: C:\Users\Hanif\git\coreutils\target\debug\coreutils.exe ls -t
run: …
```
=> test_ls: Do not rely on the system time of metadata'access time

src/uu/dd/src/parseargs.rs, tests/by-util/test_dd.rs
This pull request adds support for the suffix 'b' (multiply by 512) and 'x' (multiply by an arbitrary amount) when specifying numeric arguments to dd.
Reference: https://www.gnu.org/software/coreutils/manual/html_node/dd-invocation.html
=> dd: add support for 'b' and 'x' multipliers in numeric arguments

src/uu/dd/src/parseargs.rs, tests/by-util/test_dd.rs
Show a warning when a block size includes "0x" since this is
ambiguous: the user may have meant "multiply the next number by zero"
or they may have meant "the following characters should be interpreted
as a hexadecimal number".
This fixes a test case in the GNU test suite file `tests/dd/misc.sh`.
=> dd: show warning when using 0x size multiplier

src/uu/dd/src/dd.rs, tests/by-util/test_dd.rs
When specifying `seek=N` and *not* specifying `conv=notrunc`, truncate
the output file to `N` blocks instead of truncating it to zero before
starting to write output. For example
$ printf "abc" > outfile
$ printf "123" | dd bs=1 skip=1 seek=1 count=1 status=noxfer of=outfile
1+0 records in
1+0 records out
$ cat outfile
a2
Fixes #3068.
=> dd: truncate to specified seek length

GNUmakefile
Hi,
Don't know if `dd` is deliberately not in `GNUmakefile`, if that is the case feel free to close this PR.
Otherwise, would be nice to have it in.
Dylan
=> Add dd in GNUmakefile

src/uu/dd/src/datastructures.rs, src/uu/dd/src/dd.rs
This pull request adds some helper functions and adjust some error-handling to make the `Output::dd_out()` method, containing the main loop of the `dd` program, more concise. This commit also adds documentation and comments describing the main loop procedure in more detail. I hope this will make future readers of the code better able to understand and contribute.
=> dd: make main loop more concise

src/uu/split/src/split.rs, tests/by-util/test_split.rs
This pull request corrects the error message displayed on an invalid parameter to the `--suffix-length` or `-a` command-line option to match the rest of the error messages and match the behavior of GNU split.
Also, the second commit in this pull request adds some structure to errors that can be created during parsing of settings from command-line options. This commit creates `StrategyError` and `SettingsError` enumerations to represent the various parsing and other errors that can arise when transforming `ArgMatches` into `Settings`.
=> split: correct error message on invalid arg. to -a

src/uu/shuf/BENCHMARKING.md, src/uu/shuf/src/shuf.rs
Fixes https://github.com/uutils/coreutils/issues/3098
Updates `shuf` to use more high-level functions from `rand` instead of having custom implementations.
The result is slightly slower (but hopefully more correct) in the case where no repeats are allowed: (`./shuf` is this branch, `./shuf.old` is the main branch and `shuf` is GNU)
```
❯ hyperfine --warmup 10 "./shuf -i 0-10000000" "./shuf.old -i 0-10000000" "shuf -i 0-10000000"                                                                                               14:32:53
Benchmark 1: ./shuf -i 0-10000000
Time (mean ± σ):      1.521 s ±  0.024 s    [User: 1.327 s, System: 0.190 s]
Range (min … max):    1.485 s …  1.555 s    10 runs
Benchmark 2: ./shuf.old -i 0-10000000
Time (mean ± σ):      1.135 s ±  0.018 s    [User: 0.930 s, …
```
=> `shuf`: remove custom logic for bounded randomization

src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs
This PR addresses #2927 . 
The --classify flag in ls now takes an option when argument that may have the values always, auto and none.
I modified the help text as best as I could but not sure if it is as expected. Also I couldn't find too many tests for the existing indicator flags so modified an existing test. But this doesn't cover all the cases. Let me know if you'd like me to add more tests.
=> ls: add new optional arguments to --classify flag

Cargo.lock, src/uu/join/BENCHMARKING.md, src/uu/join/Cargo.toml, src/uu/join/src/join.rs, tests/by-util/test_join.rs
This adds a series of performance improvements to join:
- Lock and buffer stdout, to save on costs in our single-thread use case and prevent overhead from things like writing single newlines.
- Use faster techniques for finding and keeping track of fields.
- Make an intelligent guess of how many fields there will be, rather than repeatedly growing every single line.
See the following benchmarks (each of the join executables has the cumulative improvements up to that commit, not just the respective one):
```shell
$ hyperfine -w 5 \
"~/Documents/coreutils/join.main -i -t, -j14 kitch_bench.csv wr_bench.csv" \
"~/Documents/coreutils/join.buffered -i -t, -j14 kitch_bench.csv wr_bench.csv" \
"~/Documents/coreutils/join.field_parsing -i -t, -j14 kitch_bench.csv wr_bench.csv" \ …
```
=> join: improve performance

src/uu/split/src/split.rs, tests/by-util/test_split.rs
Make `split` terminate with a usage error when the
`--additional-suffix` argument contains a directory separator
character.
This should cause the GNU test `tests/split/additional-suffix.sh` to pass.
=> split: error when --additional-suffix contains /

tests/by-util/test_cut.rs, tests/by-util/test_head.rs
=> Fix clippy octal-escapes warning

src/uu/touch/src/touch.rs, tests/by-util/test_touch.rs
Show an error message when running `touch -h` on a nonexistent file.
This matches the behavior of GNU touch:
```
$ touch -h not-a-file
touch: setting times of 'not-a-file': No such file or directory
```
=> touch: show error on -h with nonexistent file

src/uu/df/src/df.rs, src/uu/df/src/table.rs, src/uucore/src/lib/features/fsext.rs
This pull request refactors the code for representing the `df` data table into `Header` and `Row` structs. These structs live in a new module `table.rs`. When combined with the `Options` struct, these structs can be `Display`ed. Organizing the code this way makes it possible to test the display settings independently of the machinery for getting the filesystem data. New unit tests have been added to `table.rs` to demonstrate this benefit.
=> df: refactor data table into Row, Header structs

tests/common/util.rs
Fix a bug in `stderr_only_bytes()` where it was unintentionally
checking `no_stderr()` when it should have been checking
`no_stdout()`.
=> tests: fix no_stderr check in stderr_only_bytes()

src/uu/dd/src/dd.rs, tests/by-util/test_dd.rs
Show a warning if the `skip=N` command-line argument would cause `dd`
to skip past the end of the input. For example:
$ printf "abcd" | dd bs=1 skip=5 count=0 status=noxfer
'standard input': cannot skip to specified offset
0+0 records in
This matches the behavior of GNU dd.
=> dd: show warning if skipping past end of input

src/uu/truncate/src/truncate.rs, tests/by-util/test_truncate.rs
Terminate the `truncate` program with an error message when trying to truncate a named pipe (also known as a fifo).
This matches the behavior of GNU truncate and should cause the GNU test `tests/misc/truncate-fifo.sh` to pass.
=> truncate: error when trying to truncate a fifo

src/uu/ls/src/ls.rs
I think its a good candidate to isolate out. I am thinking of refactoring the codebase a bit because I feel like there's a lot of moving parts (passing `&Config` and `&out` everywhere). Trying to put some organization into this instead of everything being free functions.
=> ls: refactor out padding calculations

src/uu/paste/src/paste.rs, tests/by-util/test_paste.rs
* Fix panic when a unicode delimiter is used
* Do not trim extra whitespace after lines
Plus some cleanup to e.g. reuse allocations, write directly to a locked stdout, etc. See commits for more info.
=> paste: Fixes and cleanup

src/uu/head/src/head.rs
=> head: use Self instead of enum name Mode in method

src/uu/df/src/df.rs, tests/by-util/test_df.rs
This pull request changes the `filter_mount_list()` function so that it always produces the same order of `MountInfo` objects. This change ultimately results in `df` printing its table of filesystems in the same order on each execution. Previously, the table was in an arbitrary order because the `MountInfo` objects were read from a `HashMap`.
Fixes #3086.
=> df: always produce the same order in output table

src/uu/dd/src/dd.rs, tests/by-util/test_dd.rs
Correct the accounting for partial records written by `dd` to the
output file. After this commit, if fewer than `obs` bytes are written,
then that is counted as a partial record. For example,
$ printf 'abc' | dd bs=2 status=noxfer > /dev/null
1+1 records in
1+1 records out
That is, one complete record and one partial record are read from the
input, one complete record and one partial record are written to the
output. Previously, `dd` reported two complete records and zero
partial records written to the output in this case.
This fixes the failing test case I reported in a comment https://github.com/uutils/coreutils/issues/3042#issuecomment-1030665705 but the original issue #3042 remains.
=> dd: correctly account for partial record written

.github/workflows/GnuTests.yml
Closes #2754
We are regressing deliberately because they are actual issues.
* `expr` with multibytes: https://github.com/uutils/coreutils/issues/3132
* `sort -k` isn't working well with other locales: https://github.com/uutils/coreutils/issues/3123
=> gnu/test: add the iso en_us locale to help with some tests

src/uu/expr/src/syntax_tree.rs, tests/by-util/test_expr.rs
Partially fixes #3132
Fixes one of the test of tests/misc/expr-multibyte
=> expr: Use chars().count() as we can have some multibytes chars

src/uu/od/src/od.rs
This change is needed to fix missing USAGE section for `od` in user docs.
With reference to this issue
https://github.com/uutils/coreutils/issues/2991, and missing USAGE
section from `od docs` at
https://uutils.github.io/coreutils-docs/user/utils/od.html, it was
found that the USAGE for `od` was starts with an empty line and uudoc
only takes 1st line for using in USAGE section in docs.
This resulted in empty line in usage section for `od`
Fixes #2991
=> od: fix missing usage in user docs

src/uu/split/src/split.rs, tests/by-util/test_split.rs
=> include io-blksize parameter

.github/workflows/GnuTests.yml, docs/src/test_coverage.css, docs/src/test_coverage.js, docs/src/test_coverage.md, src/bin/uudoc.rs, util/gnu-json-result.py
This PR adds a page with the GNU test coverage to the docs. There's two parts to it, the coverage per category (i.e. folder in the GNU tests) and the progress over time. The latter is just the graph we already display in the README.md. The other part uses a python script in the CI to collect the GNU results into a JSON file, which is parsed on the client side. This JSON file needs to be added to `coreutils-tracking` for this to work. The output is a progress bar for each folder with the number of passes, skips and errors/fails. Each category can be expanded and shows a list of tests.
I'm keeping this as a PR to ensure that the Python script output is correct.
=> docs: add page with test coverage

src/bin/uudoc.rs, src/uu/shuf/src/shuf.rs
The first version of `uudoc` could not handle multiline usage strings and only took the first line, which doesn't work for `od`, `shuf`, `test` and some other utils.
**Before**
**After**
I noticed that `shuf` was using the usage string wrong, so I fixed that too.
=> docs: allow for multiline usage

docs/src/test_coverage.js
The test coverage page didn't quite work because I used the wrong URL. This new one should work.
=> docs: fix url for full test report

tests/by-util/test_ls.rs
Hopefully fixes: https://github.com/uutils/coreutils/issues/3002
The test wasn't being triggered on my Linux machine, so I changed some things until it did, so hopefully it now works for both unix and mac. We'll have to see if it also fixes the flakiness.
=> `ls`: fix flaky test `test_ls_io_errors`

src/uu/cat/src/cat.rs
In our code review group we found a few minor simplifications :)
=> cat: minor cleanups

src/uu/dd/src/dd.rs, src/uu/dd/src/parseargs.rs, src/uu/dd/src/parseargs/unit_tests.rs
Correct the behavior of `dd` when multiple arguments are provided.
Before this commit, if the multiple arguments was provided then
the validation error are returned.
For example
```
$ printf '' | ./target/debug/dd status=none status=noxfer
error: The argument '--status=<LEVEL>' was provided more than once, but cannot be used multiple times
USAGE:
dd [OPTIONS]
For more information try --help
```
The unittest was added for this case.
The issue for this PR is https://github.com/uutils/coreutils/issues/3009
=> dd: allow multiple instances of arguments

src/uu/seq/src/extendedbigdecimal.rs, src/uu/seq/src/seq.rs
This PR addresses https://github.com/uutils/coreutils/issues/2870
Removed special format handling around -0.0 in seq
=> seq: Eliminated special handling of -0.0

.github/workflows/GnuTests.yml, util/build-gnu.sh
- surfaces GnuTest test comparison failures more prominently
- removes GNU factor tests for 'debug' builds (which were failing due to "Termination" by timeout when using the debug version of `factor`)
=> CICD fixes/maintainence

src/uu/printf/src/printf.rs, src/uu/seq/src/seq.rs, src/uucore/src/lib/features/memo.rs, src/uucore/src/lib/features/tokenize/sub.rs, src/uucore/src/lib/features/tokenize/token.rs, src/uucore/src/lib/features/tokenize/unescaped_text.rs
This PR addresses https://github.com/uutils/coreutils/issues/2917
Some questions/thoughts:
- Results propagate all the way up to the utility that calls it - to do so, I needed to modify the `Tokenizer` trait to return a result, and consequently also modified `UnescapedText`, though it has nothing to do with `err_conv()`.
- Both `Sub` and `UnescapedText` (which impl `Tokenizer`) can still reach conditions to exit without propagating, but I didn't change them since those exits don't use `err_conv()`.
- I wrote this PR so that `printf` and `seq` should behave similarly to what they do currently.
- I return `UResult`s that err with `UUsageError`s, although I'm wondering if I should use `SimpleError`s or something else entirely.
Let me know what I should change to make this better!
=> uucore(memo): replace err_conv with result

src/uu/dd/src/parseargs.rs, tests/by-util/test_dd.rs
Fix a bug in which `dd` was inappropriately showing a warning about a
"0x" multiplier when there was no "x" character in the argument.
This is a regression I introduced in pull request #3085. I have added a test case to prevent this from happening in the future.
=> dd: remove spurious zero multiplier warning

.vscode/cspell.dictionaries/workspace.wordlist.txt, Cargo.lock, Cargo.toml, docs/.gitignore, docs/Makefile, src/bin/uudoc.rs
Add examples to the documentation, provided by [tldr.sh](https://tldr.sh). Every run, the tldr archive is downloaded and unzipped into the `docs/tldr` folder (which is in `.gitignore`) and then both the `common` and `linux` folders are checked to see if they contain examples for a given util. In the future, we might not want to download the archive every time, for example only when an `--update-examples` flag is passed to `uudoc`, but that doesn't seem super important right now.
If a markdown file is found, some light "parsing" is done to make it fit better with the rest of the page, meaning that:
- The lines that aren't examples are removed.
- The text is not in a list
- Code uses 3 backticks instead of 1.
As far as I can tell, the examples are licensed under CC BY 4.0, which requires …
=> docs: add examples from tldr-pages

src/uu/expr/src/expr.rs
Fixes missing help in user docs. All wording are taken from help output of [`expr.rs`](https://github.com/uutils/coreutils/blob/main/src/uu/expr/src/expr.rs#L81) for consistency.
- Configured clap to take crate version, so version is now visible in docs
- Added ABOUT string, so about section is getting rendered in docs
- Added USAGE section
- Added HELP section for each arg
Fixes #2988
=> `expr`: fix missing help in user docs

src/uu/dd/src/dd.rs, tests/by-util/test_dd.rs
Place the "truncated records" line below the "records out" line in the
status report produced by `dd` and properly handle the singularization
of the word "record" in the case of 1 truncated record. This matches
the behavior of GNU `dd`.
For example
$ printf "ab" | dd cbs=1 conv=block status=noxfer > /dev/null
0+1 records in
0+1 records out
1 truncated record
$ printf "ab\ncd\n" | dd cbs=1 conv=block status=noxfer > /dev/null
0+1 records in
0+1 records out
2 truncated records
=> dd: correct order and phrasing of truncated record

build.rs
Fixes: #3162.
Added "b2sum" and "b3sum" to the phf map. I ran both cargo test and ran the gnu test and didn't see any regressions.
=> Added b2sum and b3sum utility entries

src/uu/dd/src/datastructures.rs, src/uu/dd/src/dd.rs, src/uu/dd/src/parseargs.rs, src/uu/dd/src/progress.rs
This pull request collects structs, implementations, and functions that have to do with reporting number of blocks read and written into their own new module, `progress.rs`. This commit also adds docstrings for everything and unit tests for the significant methods. This commit does not change the behavior of `dd`, just the organization of the code to make it more maintainable and testable.
This is a refactor I'm proposing to facilitate some other improvements to the progress reporting part of `dd`.
=> dd: collect progress reporting into its own module

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
Proposing a solution for #3016 
The infinite recursion can be prevented when running `cp -r <source_dir> <destination_dir> by handling these two cases:
```
cp -r /home/ubuntu/parent   /home/ubuntu/parent 
```
This can also lead to recursion, imagine there is a directory called `child` under `/home/ubuntu/parent` (i.e `/home/ubuntu/parent/child`, then the following example leads to recursion:
```
cp -r /home/ubuntu/parent /home/ubuntu/parent/child
```
The official GNU coreutil's `cp` handles both of these cases.
The above two cases can be solved by simply checking for case 2, i.e don't allow copy if destination has source in it's prefix.
I added a function:
```rust
pub fn path_has_prefix(p1: &Path, p2: &Path) -> io::Result<bool> {
let pathbuf1 = canonicalize(p1, MissingHandling::Normal, …
```
=> Fix: Avoid infinite recursion when source and destinations are same while using `cp -R`

.github/workflows/GnuTests.yml, DEVELOPER_INSTRUCTIONS.md, util/run-gnu-test.sh
- It seems codecov-action can only upload reports to the same project.
- The code runs slower with coverage report enabled, so I extend the timeout limit to four hours. 
- codecov-action@v1 is deprecated, I didn't update the action in CICD.yml in case it breaks something.
- The origin windows coverage report action failed on my forked repo sometimes, but I don't think it's caused by my changes.
- Install valgrind  and libexpect-perl for tests that require it.
Closes #2946.
=> Create coverage report for GNU tests

src/uu/dd/src/blocks.rs, src/uu/dd/src/dd.rs
This pull request creates a new module `blocks.rs` to contain the block-related helper functions. This commit only moves the location of the code and related tests, it does not change the functionality of `dd`.
By providing some light hierarchy in the `dd` crate, I am hoping to make it easier to understand and maintain.
=> dd: move block-related functions into new module

src/uu/dd/src/dd.rs, tests/by-util/test_dd.rs
Prevent `dd` from terminating with an error when given the
command-line argument `of=/dev/null`. This commit allows the call to
`File::set_len()` to result in an error without causing the process to
terminate prematurely.
Before this change:
```
$ : | ./target/debug/dd of=/dev/null
./target/debug/dd: failed to truncate output file: Invalid input
```
After this change:
```
$ : | ./target/debug/dd of=/dev/null
0+0 records in
0 bytes (0 B, 0 B) copied, 0.0 s, 0 B/s
```
This matches the behavior of GNU `dd`.
=> dd: don't error when outfile is /dev/null

src/uu/dd/src/datastructures.rs, src/uu/dd/src/dd.rs, src/uu/dd/src/parseargs.rs, src/uu/du/src/du.rs, src/uu/head/src/head.rs, src/uu/head/src/parse.rs, src/uu/head/src/take.rs, src/uu/od/src/inputoffset.rs, src/uu/od/src/od.rs, src/uu/od/src/parse_inputs.rs, src/uu/od/src/parse_nrofbytes.rs, src/uu/od/src/partialreader.rs, src/uu/sort/src/sort.rs, src/uu/split/src/split.rs, src/uu/stdbuf/src/stdbuf.rs, src/uu/tail/src/tail.rs, src/uu/truncate/src/truncate.rs, src/uucore/src/lib/parser/parse_size.rs, tests/by-util/test_head.rs, tests/by-util/test_split.rs, tests/by-util/test_tail.rs, tests/by-util/test_truncate.rs
Using usize limits 32-bit platforms to operate only on sizes of 4GiB or
less. While 32-bit platforms only have 4GiB of addressable memory, not all
operations require the data to be entirely in memory, so this limitation
can be lifted if we use u64 instead of usize.
The following utilities have been adjusted to use this new type where possible -
- stdbuf
- od 
- tail 
- head 
- du
- dd
- truncate (Thanks @Gilnaa)
- split (Thanks @Gilnaa)
- sort (Thanks @Gilnaa)
The most obvious utility that benefits from this change is `dd`, it's not uncommon
to perform >4GiB `dd` operations on disks/files - and without this PR 32-bit platforms
cannot currently do that with the current state of uutils/coreutils.
Ideally the function would return u128 and the utilities would truncate it
to usize / u64 as …
=> Fix `parse_size` to use u64 rather than usize for better 32-bit support

src/uu/df/src/df.rs, src/uu/df/src/table.rs
Change `df` so that it correctly scales numbers of bytes by the
default block size, 1024, when neither -h nor -H are specified on the
command-line. Previously, it was not scaling the number of bytes in
this case.
Now GNU `df` produces:
```
$ df | sort | head -n1
/dev/loop0                    56832    56832         0 100% /snap/core18/2253
```
and uutils `df` produces:
```
$ ./target/debug/df | sort | head -n1
/dev/loop0              56832        56832            0  100% /snap/core18/2253
```
(The spacing is wrong, but the numbers are right. This pull request is not about the spacing.)
Fixes #3058.
=> df: correctly scale bytes by block size

src/uu/dd/src/parseargs.rs, src/uu/head/src/head.rs, src/uu/split/src/split.rs, src/uu/stdbuf/src/stdbuf.rs, tests/by-util/test_dd.rs, tests/by-util/test_head.rs, tests/by-util/test_split.rs, tests/by-util/test_stdbuf.rs
https://github.com/uutils/coreutils/pull/3084 (2a333ab3919484c5a8cacb294e705dbc2408ce78) had some
missing coverage and was merged before I had a chance to fix it.
This PR adds some coverage / improved error messages that were missing
from that previous PR.
=> Improve coverage / error messages from `parse_size` PR

src/uu/df/src/df.rs
Should have included this with #3182.
=> df: correct links in BlockSize documentation

src/bin/uudoc.rs, tests/by-util/test_ls.rs, tests/by-util/test_relpath.rs
I think this clippy lint was improved with Rust 1.59 and therefore suddenly the CI fails.
=> Rust 1.59 Clippy lints

src/uu/tr/src/operation.rs, tests/by-util/test_tr.rs
Closes #3168 
Fix repeat count processing of `tr` to interpret as octal only if prefixed with `0`.
=> tr: fix octal interpretation of repeat count string

src/uu/install/src/install.rs, tests/by-util/test_install.rs
Addresses  https://github.com/uutils/coreutils/issues/3048 - executing
```
install
``` 
or 
```
install <file>
``` 
no longer panics, and instead returns errors similar to GNU's install when it encounters similar arguments.
=> install: better error messages when handling invalid arguments

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
Closes https://github.com/uutils/coreutils/issues/2984
These arguments should not have been in conflict with each other, but silently override each other.
=> `cp`: override args instead of having them conflict

src/uu/split/src/split.rs, tests/by-util/test_split.rs
This pull request adds support for `split -n l/NUM`. Previously, `split` only supported `-n NUM`, which splits a file into `NUM` chunks by byte. The `-n l/NUM` strategy splits a file into `NUM` chunks without splitting lines across chunks.
=> split: add support for "-n l/NUM" option to split

src/uu/dd/src/blocks.rs, tests/by-util/test_dd.rs
If `conv=block,sync` command-line arguments are given and there is at
least one partial record read from the input (for example, if the
length of the input is not divisible by the value of the `ibs`
argument), then output an extra block of `cbs` spaces.
For example, no extra spaces are printed in this example because the
input is of length 10, a multiple of `ibs`:
$ printf "012\nabcde\n" \
> | dd ibs=5 cbs=5 conv=block,sync status=noxfer \
> && echo $
012  abcde$
2+0 records in
0+1 records out
But in this example, 5 extra spaces are printed because the length of
the input is not a multiple of `ibs`:
$ printf "012\nabcdefg\n" \
> | dd ibs=5 cbs=5 conv=block,sync status=noxfer \
> && echo $
012  abcde     $
2+1 records in
0+1 records out
1 truncated record\n
The number of spaces printed is …
=> dd: pad partial record with spaces in some cases

src/uu/seq/src/seq.rs, tests/by-util/test_seq.rs
This changes the parser to accept arguments to short flags again. The root of the problem is clap's overly restrictive parsing code, specifically this line:
https://github.com/clap-rs/clap/blob/5c3868ea4cb8063731d8526e8e97414942a987ae/src/parse/parser.rs#L994-L995
This means that `-s,` is not accepted when `AllowHyphenValues` is on, as it contains `,` which isn't a short option flag. This is despite the short option taking an argument. As we can see from the surrounding code the treatment is very different if we merely activate `AllowNegativeNumbers`. This, still, isn't _exactly_ the same parser style as GNU `seq`. In particular, that program matches value arguments by the expression: `-[0-9.].*` (regex style) instead. This implies that the _error message_ for negative non-numbers, but …
=> Discuss seq parsing

Cargo.lock, src/uu/pr/Cargo.toml, src/uu/pr/src/pr.rs, tests/by-util/test_pr.rs
Fixes https://github.com/uutils/coreutils/issues/3109
Surprisingly, `pr` didn't use clap yet, so I changed that too. `pr` has a function to that changes the list of arguments into something that clap can parse. The problem was that it was using a regex that matches to many strings. This is the important change for the fix:
```diff
-    let num_regex = Regex::new(r"(.\d+)|(\d+)|^[^-]$").unwrap();
+    let num_regex = Regex::new(r"^.\d*$").unwrap();
```
A couple of subtle issues remain, however. For example `pr -n -5 foo.txt` should use `-` as a separator, but currently `-5` is removed from the list of arguments. It should only remove it if the previous element was not `-n`. The approach to the arguments here might need to be redone eventually.
=> `pr`: Move from getopts to clap and fix heuristic for `-n`

src/uu/df/src/df.rs
Unlike other utilities like `head` or `seq`, the output of the `df` program may be different in each environment in which it is run, and even each time it is run (since filesystem usage may change rapidly). This makes it difficult to produce black box tests, as in the `tests/by-utils/test_*.rs` files. But we can still provide tests for the internal components of `df` using mock data. This pull request starts to address this by adding unit tests in the `df.rs` file for internal helper functions `mount_info_lt()`, `is_best()`, `is_included()`, and `filter_mount_list()`.
=> df: add unit tests for internal helper functions

src/uu/df/src/df.rs, src/uu/df/src/table.rs, tests/by-util/test_df.rs
This pull request adds support for the `--total` option to `df`, which displays the total of each numeric column. For example,
$ df --total
Filesystem            1K-blocks     Used Available Use% Mounted on
udev                    3858016        0   3858016   0% /dev
...
/dev/loop14               63488    63488         0 100% /snap/core20/1361
total                 258775268 98099712 148220200  40% -
=> df: add support for --total option

.github/workflows/GnuTests.yml
GNU coverage job now takes around one hour to finish thanks to contributors' work. Run it on pull requests to compare the GNU coverage report. https://github.com/uutils/coreutils/pull/3045#issuecomment-1058721351
=> Run GNU coverage job on pull requests

Cargo.lock, src/uu/chmod/Cargo.toml, src/uu/chmod/src/chmod.rs, tests/by-util/test_chmod.rs
I guess `filter_map` removes some files even though they can be modified(#3118). `tests/mkdir/p-3.sh` passed after the change.
=> chmod: replace walkdir with std::fs

src/uu/timeout/src/timeout.rs
=> timeout: avoid panicking for empty string

util/build-gnu.sh
I propose removing some of these replacements. Some of these test files seem to work now without replacing program `XYZ` with `/usr/bin/XYZ` on my machine. Let's see if the continuous integration build agrees. If it shows no change in the GNU test suite, then you should consider this change successful.
=> util: remove some workarounds for GNU tests

src/uu/df/src/blocks.rs, src/uu/df/src/df.rs, src/uu/df/src/table.rs, tests/by-util/test_df.rs
This pull request corrects the column header printed by `df` when the `--block-size` argument has a value that is a multiple of 1024. After this commit, the header looks like "1K" or "4M" or "117G", etc., depending on the particular value of the block size. For example:
$ df --block-size=1024 | head -n1
Filesystem                1K-blocks     Used Available Use% Mounted on
$ df --block-size=2048 | head -n1
Filesystem                2K-blocks     Used Available Use% Mounted on
$ df --block-size=3072 | head -n1
Filesystem                3K-blocks     Used Available Use% Mounted on
$ df --block-size=4096 | head -n1
Filesystem                4K-blocks     Used Available Use% Mounted on
This matches the behavior of GNU df.
This pull request does _not_ correct the header when the block size is …
=> df: fix block size header for multiples of 1024

src/uu/df/src/table.rs, tests/by-util/test_df.rs
Always round up the usage percent. For example, `25.1%` is now rounded to `26%,` previously it was rounded to `25%.`
=> df: always round up usage percentage (#3208)

src/uucore/src/lib/features/tokenize/num_format/formatters/float_common.rs, tests/by-util/test_printf.rs
fixes #3088
update `round_terminal_digit`
- Return `bool` (along with pre- and post-decimal formatted strings) indicating if we have rounded in such a way that the decimal place, or mantissa for `%e/%E` format specifiers, should change
update `_round_str_from`
- Accept `before_dec: bool` argument indicating if the numeric string to be rounded is before or after decimal place. This is used to round a `9` to a `1` in the most significant position in a pre-decimal string.
This fixes similar cases for `printf` with `%e`, `%E`, and `%f`:
```shell
$ printf "%e\n" 0.99999999
1.000000e+00  # was 0.000000e-01
$ printf "%f\n" 99999.9999999
100000.000000  # was 00000.000000
```
I also noticed that `%g`/`%G` doesn't perform as expected, but I can open a separate issue for that if needed.
```shell
$ …
```
=> printf: fix printf sci notation round up

util/build-gnu.sh
Similar to #3225; we should be able to use the uutils version of `seq` in the `tests/factor/t*.sh` scripts now. Let's see if the CI build agrees.
=> util: remove replacement of seq in GNU tests

src/uu/df/src/columns.rs, src/uu/df/src/df.rs, src/uu/df/src/table.rs, tests/by-util/test_df.rs
This pull request implements the `--output` command-line argument, which allows specifying an exact sequence of columns to display in the output table. For example,
$ df --output=source,fstype | head -n3
Filesystem       Type
udev             devtmpfs
tmpfs            tmpfs
(The spacing does not exactly match the spacing of GNU `df` yet.)
In order to do this, we replace the `Options.show_fs_type` and `Options.show_inode_instead` fields with the more general `Options.columns`, a `Vec` of `Column` variants representing the exact sequence of columns to display in the output. This makes `Options` able to represent arbitrary output column display configurations.
Fixes #3057.
=> df: implement the --output command-line argument

util/build-gnu.sh
Replace a bash loop for enumerating integers with a more concise use
of `seq` in `util/build-gnu.sh`.
=> util: use seq to enumerate integers

src/uu/df/src/df.rs
Fix unit tests for the `is_included()` and `filter_mount_list()`
internal helper functions. The function signatures changed but the
tests did not get updated to match.
=> df: fix tests of internal helper functions

tests/by-util/test_timeout.rs
To make sure we don't regress on https://github.com/uutils/coreutils/pull/3206
=> timeout: add a test for empty arg

src/uu/split/src/split.rs, tests/by-util/test_split.rs, tests/fixtures/split/letters.txt
Implement the `--line-bytes` option to `split`. In this mode, the
program tries to write as many lines of the input as possible to each
chunk of output without exceeding a specified byte limit. The new
`LineBytesChunkWriter` struct represents this functionality.
=> split: implement --line-bytes option

src/uu/timeout/src/status.rs, src/uu/timeout/src/timeout.rs, tests/by-util/test_timeout.rs
This pull request fixes a bug where `timeout --preserve-status` was not correctly preserving the status code of the child process if it timed out. When that happens, the status code of the child process is considered to be the signal number (in this case, `SIGTERM`). The exit status of `timeout` is then 128 plus the numeric code associated with `SIGTERM`.
Before this pull request:
```
$ ./target/release/timeout --preserve-status .1 sleep 10; echo $?
124
```
After this pull request 
```
$ ./target/release/timeout --preserve-status .1 sleep 10; echo $?
143
```
This now matches the behavior of GNU timeout.
This pull request also includes a commit that adds the `ExitStatus` enumeration in a new module `status.rs` to
contain all the magic numbers in the `timeout` utility.
=> timeout: fix bug in --preserve-status mode

src/uu/df/src/df.rs, src/uu/df/src/filesystem.rs, src/uu/df/src/table.rs
This pull request moves the `Filesystem` struct into a new module `filesystem.rs`. There are on other changes to the code; this move is just in preparation for some further refactors to improve the code readability.
=> df: move Filesystem to filesystem.rs

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
Previously, given 'cp -P a b', where 'a' and 'b' were both symlinks, cp
would end up replacing the target of 'b'.
Signed-off-by: Ryan Gonzalez <ryan.gonzalez@collabora.com>
=> cp: Avoid following a destination symlink with -P

src/uu/fmt/src/linebreak.rs
clippy::suboptimal_flops found a few unnecessary usages of powf (powi is faster).
=> fmt: use powi instead of powf

src/uu/df/src/df.rs, src/uu/df/src/filesystem.rs
This pull request splits the code for getting a list of `Filesystem` objects into two separate functions: one for getting the list of all filesystems (when running `df` with no arguments) and one for getting only named filesystems (when running `df` with one or more arguments). This does not change the behavior of `df` only the organization of the code. If this is not clearer, please let me know.
I recommend reviewing each of the three commits in this pull request separately in order to make the overall diff easier to understand. I can also split this up into multiple pull requests if that is preferable.
=> df: separate functions for two main modes of df

src/uu/split/src/split.rs, tests/by-util/test_split.rs
Implement distributing lines of a file in a round-robin manner to a
specified number of chunks. For example,
$ (seq 1 10 | split -n r/3) && head -v xa[abc]
==> xaa <==
1
4
7
10
==> xab <==
2
5
8
==> xac <==
3
6
9
=> split: implement round-robin arg to --number

.github/workflows/CICD.yml, src/uu/pinky/src/pinky.rs, tests/by-util/test_pinky.rs, tests/by-util/test_users.rs, tests/by-util/test_who.rs
This lets the test pass when running `cargo test --features unix` on my system, a Xubuntu 21.10 install. Without this, the output includes the trailing comma. I am a bit cautious though, since it seems unusual that nobody noticed this in the 6 years since this code was added -- is it possible there's something system-specific going on? Also, all the CI tests pass before and after this change, does the CI not run the Unix-specific tests?
=> pinky: fix off-by-one in GECOS parsing

src/uu/split/src/split.rs, tests/by-util/test_split.rs
Reverts uutils/coreutils#3205
See https://github.com/uutils/coreutils/issues/3268 for the rational
=> Revert "split: implement round-robin arg to --number"

.github/workflows/CICD.yml, CONTRIBUTING.md, Cargo.lock, deny.toml, src/uu/factor/Cargo.toml
This sets up [cargo-deny](https://github.com/EmbarkStudios/cargo-deny/), a cargo tool that allows going through all the transitive dependencies, and check for allowed licenses, security advisories in those, duplicate dependencies, etc.
Full available configuration is documented on https://embarkstudios.github.io/cargo-deny/checks/index.html. I've kept only the bare minimum set of options that make it useful in my opinion:
- set up a list of allowed licenses (that reflect which licenses are currently in use in the project), and deny other licenses
- detect transitive duplicate dependencies, and allow-list all the ones that don't depend on this project but on other dependencies.
- this helped find one duplicate dependency which we controlled, and I could remove it easily (first commit in …
=> Setup `cargo-deny`

src/uu/sleep/src/sleep.rs, src/uucore/src/lib/parser/parse_time.rs, tests/by-util/test_sleep.rs, tests/by-util/test_timeout.rs
This pull request makes two changes. First, we use `Duration::saturating_mul()` in `uucore::parse_time::from_str()` to avoid a panic due to overflow. This change prevents panic on very large arguments to `timeout` and `sleep`. This matches the behavior of GNU `timeout` and `sleep`. Second, we use `Duration::saturating_add()` for the same reason when adding the durations provided as command-line arguments.
=> uucore, sleep: use Duration::saturating_mul and saturating_add to avoid overflow

.github/workflows/GnuTests.yml
Failed with 
```
A 500 status code has been received, will attempt to retry the upload
Exponential backoff for retry #1. Waiting for 5416 milliseconds before continuing the upload at offset 0
An error has been caught http-client index 0, retrying the upload
Error: Client has already been disposed.
at HttpClient.request (/home/runner/work/_actions/actions/upload-artifact/v2/dist/index.js:6081:19)
at HttpClient.sendStream (/home/runner/work/_actions/actions/upload-artifact/v2/dist/index.js:6042:21)
at UploadHttpClient.<anonymous> (/home/runner/work/_actions/actions/upload-artifact/v2/dist/index.js:7208:37)
at Generator.next (<anonymous>)
at /home/runner/work/_actions/actions/upload-artifact/v2/dist/index.js:6923:71
at new Promise (<anonymous>)
at module.exports.608.__awaiter …
```
=> GNU ci: compress logs before upload

src/uu/split/src/split.rs
Catch `BrokenPipe` errors and silently ignore them so that `split`
terminates successfully on a broken pipe. This matches the behavior of
GNU `split`.
This will fix one of the GNU test cases in `tests/split/filter.sh`.
=> split: catch and handle broken pipe errors

src/uu/df/src/df.rs
I noticed there is a "--direct" option in "uutils df" not doing anything and which doesn't seem to exist in "GNU df" (I checked v8.28 and v9.0).
=> df: remove unused "--direct" option

src/uu/df/src/table.rs
Use `FsUsage::bavail` instead of `FsUsage::bfree` for the "Available" column.
There are two potential issues with this PR:
- it might not work on MacOS and/or Windows
- I couldn't figure out how to write a test for this change
=> df: omit reserved filesystem blocks in "Available"

src/uu/split/src/split.rs, tests/by-util/test_split.rs
Fix a bug in the behavior of `split -e -n NUM` when the input file is empty. Previously, it would panic due to overflow when subtracting 1 from 0. After this change, it will terminate successfully and produce no output chunks.
This will fix one of the GNU test cases in `tests/split/filter.sh`.
=> split: elide all chunks when input file is empty

src/uu/split/src/split.rs, tests/by-util/test_split.rs
Fix a panic due to out-of-bounds indexing when using `split
--line-bytes` with an input that had no trailing newline.
=> split: handle no final newline with --line-bytes

src/uu/split/src/split.rs, tests/by-util/test_split.rs
Fix a bug in which a final empty file was written when using `split
--line-bytes` mode.
=> split: avoid writing final empty chunk with -C

src/uu/sleep/src/sleep.rs, tests/by-util/test_sleep.rs
For example,
$ sleep xyz
sleep: invalid time interval 'xyz'
Try 'sleep --help' for more information.
This matches the behavior of GNU sleep.
=> sleep: give usage error on invalid time interval

src/uu/timeout/src/timeout.rs, tests/by-util/test_timeout.rs
For example,
```
$ ./target/debug/timeout xyz sleep 0
./target/debug/timeout: invalid time interval 'xyz'
Try './target/debug/timeout --help' for more information.
```
This matches the behavior of GNU timeout.
Previously, the usage message was not being displayed.
=> timeout: give usage error on invalid time interval

src/uucore/src/lib/features/tokenize/num_format/formatters/decf.rs, tests/by-util/test_printf.rs
Resolves #2775. 
This format is unintuitive. Uutils previously had `%g` return either the standard `%f` output or scientific notation, whichever was shorter. This seems to be a common summary of the format, but it doesn't fully explain its behavior. For example, `printf %g 1.234567` prints `1.23457`, while `%f` prints `1.234567`.  
This PR changes the definition to apply three rules:
1) Choose scientific notation or float notation based on the number's magnitude, not its length.
2) Round to 6 significant figures.
3) Remove trailing zeroes.
I’ve added several tests to validate these rules, and confirmed that GNU gives the same results for each test. 
There are probably better ways to write some of this string parsing. I’m still a bit perplexed by Rust’s complex string rules, so I’d …
=> printf - Update %g formatting to match GNU

src/uucore/src/lib/parser/parse_time.rs, tests/by-util/test_sleep.rs, tests/by-util/test_timeout.rs
Return an error when a negative interval is provided as the argument
to `uucore::parse_time::from_str()`, since a `Duration` should only be
non-negative.
This corrects the behavior of `timeout` and `sleep` to match that of GNU. For example,
```
$ sleep -- -1
sleep: invalid time interval ‘-1’
Try 'sleep --help' for more information.
```
=> uucore: error on negative interval in parse_time::from_str()

src/uu/cp/src/cp.rs, src/uucore/src/lib/mods/error.rs, tests/by-util/test_cp.rs
Add a validator to the `--target-directory` option that only allows directories as the argument value.
Closes #2986
=> cp: only allow directory for -t

src/uu/chcon/src/chcon.rs, src/uu/chroot/src/error.rs, src/uu/cp/src/cp.rs, src/uu/dd/src/parseargs.rs, src/uu/expr/src/tokens.rs, src/uu/groups/src/groups.rs, src/uu/hashsum/src/hashsum.rs, src/uu/nohup/src/nohup.rs, src/uu/numfmt/src/options.rs, src/uu/ptx/src/ptx.rs, src/uu/seq/src/extendedbigdecimal.rs, src/uu/sort/src/sort.rs, src/uu/split/src/filenames.rs, src/uu/tr/src/operation.rs, src/uucore/src/lib/mods/error.rs
This fixes many but not all warnings produced by `cargo +nightly clippy --workspace --all-targets --all-features --` (as appears in `.pre-commit-config.yaml`).
=> clippy fixes from nightly rust

src/uu/timeout/src/timeout.rs, tests/by-util/test_timeout.rs
Produce a usage error on an invalid signal argument. For example,
$ timeout --signal=invalid 1 sleep 0
timeout: 'invalid': invalid signal
Try 'timeout --help' for more information.
=> timeout: produce usage error on invalid signal

.github/workflows/CICD.yml, .github/workflows/GnuTests.yml
Fixes https://github.com/uutils/coreutils/issues/3305
=> CI: Force the rustc nightly version to fix issue 3305

src/uu/dd/src/blocks.rs, src/uu/dd/src/datastructures.rs, src/uu/dd/src/dd.rs, src/uu/dd/src/parseargs.rs, src/uu/dd/src/parseargs/unit_tests.rs
This pull request creates a new enum `ConversionMode` to represent the various conversion, blocking, and unblocking combinations and moves the code for parsing the `ConversionMode` from the command-line arguments up to the `parseargs` module. This location makes more sense for it because the conversion mode can be determined entirely from the command-line arguments at the time of parsing just like the other parameters. Using an enum for this purpose also eliminates the amount of code we need later on. For example, we replace an `if/else if` chain in `conv_block_unblock_helper()` with a `match` statement instead.
You may find it easier to review each commit on its own.
=> dd: create ConversionMode to simplify conversion, blocking, and unblocking

src/uucore/src/lib/parser/parse_time.rs
Disallow uppercase unit suffixes "S", "M", "H", and "D" in
`uucore::parse_time::from_str()` to match the behavior of GNU `sleep`
and `timeout`.
=> uucore: no uppercase suffixes in parse_time

src/uu/mkdir/src/mkdir.rs, tests/by-util/test_mkdir.rs
I agree it is ugly but it is GNU's behavior.
`Warning: Congrats! The gnu test tests/mkdir/p-slashdot is now passing!`
This:
`    std::fs::create_dir("d2/.")?;`
doesn't create d2/
=> mkdir: gnu compat: add support of mkdir -p foo/.

util/build-gnu.sh
Remove the substitution of uutils `timeout` with GNU `timeout` before
running the GNU test suite. Some of these replacements were not
actually operational because the regex was not appropriate (for
example, the test file had `timeout 10` but the regex would only match
`timeout [0-9]`). Others no longer need to be used because the uutils
version of `timeout` works well enough now to terminate a process
within the given period of time.
=> util: use uutils timeout in GNU tests

src/uu/timeout/src/timeout.rs, tests/by-util/test_timeout.rs
Add support for the long form of the `--kill-after`
argument. Previously only the short form `-k` was supported.
=> timeout: support long form of --kill-after arg

src/uu/timeout/src/timeout.rs, tests/by-util/test_timeout.rs
Exit with status 125 (indicating an error in `timeout` itself) when
the timeout duration is invalid or the "kill after" duration is
invalid.
=> timeout: return 125 on invalid time interval args

src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs
Should fix tests/ls/symlink-quote.sh
=> ls: Add proper quotes on symlink with --quoting-style=shell-escape

src/uu/df/src/df.rs, src/uu/df/src/filesystem.rs, src/uu/df/src/table.rs, tests/by-util/test_df.rs
Implement the "File" column in the `df` output table. Before this
commit, a blank entry appeared in the "File" column for each
row. After this commit, a "-" entry appears when `df` is run with no
positional arguments and the filename appears when run with positional
arguments. For example:
$ touch a b c && df --output=target,file a b c
Mounted on File
/          a
/          b
/          c
=> df: implement the File column

src/uu/df/src/df.rs, tests/by-util/test_df.rs
Allow multiple occurrences of the `--output` argument. For example,
$ df --output=source --output=target | head -n1
Filesystem                Mounted on
=> df: allow multiple occurrences of --output arg

src/uu/df/src/df.rs, tests/by-util/test_df.rs
Previously, `df --output .` was treated as `df --output=.` and hence `.` was interpreted as a column name (and caused an error). With this commit, `.` is treated as an argument on its own.
Fixes #3324
=> df: --output w/o "=" doesn't expect further args

src/uu/shuf/src/shuf.rs, tests/by-util/test_shuf.rs
=> shuf: accept multiple occurances of head-count argument

src/uu/df/src/table.rs, tests/by-util/test_df.rs
Change formula from: `Used/Size * 100` to `Used/(Used + Avail) * 100`. This formula also works if "Used" and "Avail" do not add up to "Size", which is the case if there are reserved disk blocks.
=> df: fix calculation of Use% column

src/uu/df/src/columns.rs, src/uu/df/src/df.rs, tests/by-util/test_df.rs
Print a usage error when duplicat column names are specified to the
`--output` command-line argument. For example,
$ df --output=source,source
df: option --output: field ‘source’ used more than once
Try 'df --help' for more information.
=> df: error on duplicate columns in --output arg

util/build-gnu.sh
=> gnu/usage_vs_getopts.sh: make the test FAIL instead of ERROR

src/uu/wc/src/wc.rs, tests/by-util/test_wc.rs
Previously, individual file sizes were used to compute the number width, which
would cause misalignment when the total has a greater number of digits, and is
different from the behavior of GNU wc
```
$ ./target/debug/wc -w -l -m -c -L deny.toml GNUmakefile
95  422 3110 3110   85 deny.toml
349  865 6996 6996  196 GNUmakefile
444 1287 10106 10106  196 total
$ wc -w -l -m -c -L deny.toml GNUmakefile
95   422  3110  3110    85 deny.toml
349   865  6996  6996   196 GNUmakefile
444  1287 10106 10106   196 total
```
=> wc: compute number widths using total file sizes

src/uu/df/src/blocks.rs, src/uu/df/src/df.rs
I don't find the name `OPT_HUMAN_READABLE_2` very meaningful. This PR is an attempt to improve it.
=> df: rename two constants

src/uu/ln/src/ln.rs, tests/by-util/test_ln.rs, util/build-gnu.sh
To make sure that the following works
```
echo "a" > a
echo "b2" > b
ln b b~
ln -f --b=simple a b
```
=> ln: pass tests/ln/backup-1.sh  & improvement in the error messages

src/uu/head/src/head.rs, src/uu/tail/src/tail.rs, tests/by-util/test_head.rs, tests/by-util/test_tail.rs
=> head, tail: include presume-input-pipe parameter

src/uu/df/src/table.rs, tests/by-util/test_df.rs
Change formula from: `Used/Size * 100` to `Used/(Used + Avail) * 100`. This formula also works if `Used` and `Avail` do not add up to `Size`, which is the case if there are reserved disk blocks.
This PR is an addition to #3309 and fixes the same issue for the calculation of the `Use%` value in the `total` row.
=> df: fix calculation of Use% in "total" row

src/uu/env/Cargo.toml, src/uu/env/src/env.rs
Addresses https://github.com/uutils/coreutils/issues/3188.
1. These changes don't print the error output as described in the issue, but they do provide similar information and replicate what I get when encountering a signal termination (x86_64 Fedora 35, GNU coreutils 8.32):
```
$ env ./a.out
Segmentation fault (core dumped)
$ ~/repo/coreutils/target/debug/env ./a.out 
Segmentation fault (core dumped)
```
2. I'm not entirely sure how to test/get code coverage for this; ideas are welcome. For testing my changes, I essentially compared outputs of a c program that an exception, and changed the exception to check for any discrepancies:
```c
#include <signal.h>
int main() {
raise(SIGSEGV);
}
```
3. I use unsafe code and add `libc` as a dependency in order to convert a signal number into a …
=> env: add program signal messages

src/uu/tty/src/tty.rs, tests/by-util/test_tty.rs
This is impacting
gnu/tests/misc/usage_vs_getopt.sh
=> tty: should not return 2 when --help is used

src/uu/df/src/df.rs, tests/by-util/test_df.rs
Any file system type specified to be included and excluded is listed with a separate line in the error message.
=> df: show error if same type is included & excluded

src/uu/hashsum/src/hashsum.rs, tests/by-util/test_hashsum.rs
The official b3sum tool has a --no-names option for only printing the
hashes, omitting the filenames. This is quite handy when used from
scripts because it spares the postprocessing with "cut" or "awk".
Since the installed b3sum symlink would also serve as a drop-in for the
official tool, the --no-names option is expected to exist for
compatibility.
Add a --no-names option not only for b3sum but for hashsum in general
(and maybe GNU coreutils will also feel inspired to add this option).
Closes https://github.com/uutils/coreutils/issues/3360
=> hashsum: add --no-names option from official b3sum tool

docs/theme/head.hbs, src/bin/uudoc.rs
A few examples:
- A util that supports Linux (unix) and Mac:
- A utils that requires SELinux (and thus supports only Linux):
- A util that supports all platforms:
The data is collected by running `./util/show-utils.sh` with different feature sets.
I also refactored the `uudoc` code a bit. I wanted to include FreeBSD as well, but the icon for that was only added in FontAwesome 5, which mdbook does not use yet.
=> docs: show supported platforms for each util

tests/common/util.rs
Fix a bug in which the error message displayed when using
`CmdResult::no_stdout()` was incorrectly showing stderr when it should
have been showing stdout.
=> tests: print stdout in error msg for no_stdout()

src/uu/du/src/du.rs, tests/by-util/test_du.rs
Make the tests/du/no-x.sh & long-sloop.sh pass
=> du: Return non zero error code when dealing with permissions errors

docs/theme/head.hbs, src/bin/uudoc.rs
The `fa` class was missing in the platform icons, which sets the FontAwesome font as the font for the icons. My browser probably had FontAwesome set as a fallback, making it work there. Other browsers don't and hence the icons were not showing up.
The `fa` class also changes the size, so I had to adjust the size and the margin a bit too.
=> Docs: Fix the platform icons not showing up in some browsers

Cargo.lock, src/uu/du/Cargo.toml, src/uu/du/src/du.rs, tests/by-util/test_du.rs
And add an option --verbose (doesn't exist in GNU)
Fixes gnu test tests/du/exclude.sh & tests/du/slash.sh
Leverages glob
=> du: add support for --exclude and --exclude-from

src/uu/factor/src/miller_rabin.rs, src/uu/factor/src/numeric/montgomery.rs, src/uu/factor/src/rho.rs, src/uucore/src/lib/features/tokenize/num_format/formatters/base_conv/mod.rs
This was reported as an error in Clippy 1.60 and makes some PR builds fail. We could also ignore the error if we want to do that instead.
=> Clippy: Don't use `from_*` method names that take `self`

src/uu/df/src/df.rs, tests/by-util/test_df.rs
For example:
$ df not-a-file
df: not-a-file: No such file or directory
Fixes #3373.
=> df: show error when file argument does not exist

src/uu/df/src/table.rs
Instead of using a single `scaled()` function for both inodes and bytes, I introduced two new specialized functions.
Fixes #3349.
=> df: fix too low values in I* columns

src/uu/mv/src/mv.rs, tests/by-util/test_mv.rs
Check OverwriteMode and act depending on its value, specifically in the
the case of overwriting a non-directory with a directory
fixes #3337
=> mv: add OverwriteMode match in specific case

src/uu/df/src/table.rs
Wrapping the return value in a `Result` is unnecessary because there is never an `Err` returned.
=> df: remove unnecessary return of Result

src/uu/mkdir/src/mkdir.rs
```
error: writing `&mut Vec` instead of `&mut [_]` involves a new object where a slice will do
--> src\uu\mkdir\src/mkdir.rs:72:33
|
72 | fn strip_minus_from_mode(_args: &mut Vec<String>) -> bool {
|                                 ^^^^^^^^^^^^^^^^ help: change this to: `&mut [String]`
|
= note: `-D clippy::ptr-arg` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
```
=> mkdir.rs: Fix a clippy warning on clippy::ptr-arg

src/uu/df/src/df.rs, tests/by-util/test_df.rs
Fixes #3252. As a side effect, "df -H -total" will now fail, too, as expected.
The code is adapted from #3254. In addition, I added tests and fixed a todo in the tests.
=> df: show error if specified type doesn't exist

src/uu/df/src/df.rs
The field `show_listed_fs` in the `Options` struct seems to be obsolete as it is always set to `false` (except in a test).
=> df: remove obsolete "show_listed_fs" options field

Cargo.lock, Cargo.toml, docs/.gitignore, src/bin/uudoc.rs
The `ureq` dependency is causing compilation errors on various platforms (see #3184, #3216, #3375). Hence we remove that dependency and do not automatically download the archive anymore. Instead, we ask the user to download it separately when the archive is not found.
I'll post a PR to coreutils-docs to download the archive in the CI there.
This PR supersedes https://github.com/uutils/coreutils/pull/3184.
=> `uudoc`: Don't download the tldr archive automatically

src/uu/df/src/columns.rs, src/uu/df/src/df.rs, src/uu/df/src/table.rs, tests/by-util/test_df.rs
The main idea behind this PR is to introduce a `Table` struct to print a table. The print process now consists of two steps: 1) calculate the widths of the columns and 2) print the data. 
`Header` and `DisplayRow` (which has been renamed to `RowFormatter` (I'm not sure about this name, I struggled to find a name for it)) no longer do any output, they simply prepare the strings used by the table.
Fixes #3194.
=> df: fix incorrect whitespace between columns

src/uu/install/src/install.rs, tests/by-util/test_install.rs
Should fix:
tests/install/strip-program.sh
=> install: When install --strip-program=foor fails, remove the target file

src/uu/install/src/install.rs, tests/by-util/test_install.rs
```
$ install -Dv source_file1 sub3/a/b/c/file
install: creating directory 'sub3'
install: creating directory 'sub3/a'
install: creating directory 'sub3/a/b'
install: creating directory 'sub3/a/b/c'
'source_file1' -> 'sub3/a/b/c/file'
```
Necessary step for tests/install/basic-1.sh
=> install: verbose - list all created directories

Cargo.lock, src/uu/df/Cargo.toml, src/uu/df/src/table.rs, tests/by-util/test_df.rs
Use Unicode-aware function instead of `str::len()` when calculating column widths.
=> df: fix "File" column width for unicode filenames

src/uu/df/src/df.rs, tests/by-util/test_df.rs
`coreutils df -x ext4 -x tmpfs -x devtmpfs -x vfat` will now show an error (this is on my machine, on other machines you might have to specify other types to get the error).
Fixes #3409.
=> df: show error if all types are excluded

src/uu/df/src/df.rs
It's a code snippet that likely sneaked in due to overlapping PRs and doesn't do anything, because the `return` is unreachable.
=> df: remove unreachable code

src/uu/df/src/df.rs, tests/by-util/test_df.rs
`df -t _non_existent_type .` now leads to an error message.
Fixes #3325.
=> df: respect -t arg when specific file is provided

tests/by-util/test_df.rs
Fixes a todo in the `test_block_size_1024()` function.
=> df: simplify get_header() in test_block_size_1024

src/uu/df/src/table.rs, tests/by-util/test_df.rs
Reverts uutils/coreutils#3423
to see if it fixes the GNU tests
=> Revert "df: remove trailing spaces in rightmost column"

Cargo.lock, Cargo.toml, src/uu/cat/Cargo.toml, src/uu/more/Cargo.toml, src/uu/nice/Cargo.toml, src/uu/tail/Cargo.toml, src/uu/timeout/Cargo.toml, src/uu/wc/Cargo.toml, src/uu/yes/Cargo.toml, src/uucore/Cargo.toml, src/uucore/src/lib/features/pipes.rs
Limit nix features, which should help compile times slightly.
Replace usage of deprecated nix functionality with std equivalent.
=> Upgrade nix to 0.24.1, ctrlc to 3.2.2

src/uu/cp/src/cp.rs, src/uu/false/src/false.rs, src/uu/pr/src/pr.rs, src/uu/sort/src/sort.rs, src/uu/true/src/true.rs, src/uu/unexpand/src/unexpand.rs, util/build-gnu.sh
Just a tiny commit that addresses the `-h` and `--help` differences mentioned in https://github.com/uutils/coreutils/issues/3370 - it seems like there are differences when long help is printed, which either occurred when `print_long_help()` was called or `--help` was used on a command that had `long_help()` description in one of its argument.
I removed all calls to long_help since it appears that other commands output their `--help` to be the same as `-h` (argument and description start on the same line). So now the changed commands (like `false`)  look like 
```
...
OPTIONS:
--help       Print help information
--version    Print version information
```
like other commands, as opposed to 
```
...
OPTIONS:
--help
Print help information
--version
Print version information
```
I also moved …
=> fix -h and --help discrepancies

tests/by-util/test_dir.rs, tests/by-util/test_vdir.rs
The Windows tests are currently failing on all new PRs. This is due to an incorrect regex in the tests for `dir` and `vdir`. The regex was:
```regex
[rwx][^some-file1]
```
which was probably supposed to mean: "any of `rxw` but not `some-file1`". This is wrong because it matches any `r`, `w` or `x` that is not followed by the characters in `some-file1`. On my machine, my username is `terts` which then also matches. Secondly, it does not match `-` which is all we output on Windows. 
So what happened is that the Windows tests were only "correct", because the string `April` matched the regex until yesterday, making the Windows tests succeed until `April` was over and `May` began :).
I've change the regex to check both a string of `rwx-` characters and the filename:
```regex …
```
=> `dir`, `vdir`: fix incorrect regex in tests

src/uu/mktemp/src/mktemp.rs, tests/by-util/test_mktemp.rs
Fix a bug in `mktemp` where it was not respecting the path given by
the positional argument. Previously, it would place the temporary file
whose name is induced by a given template in the `/tmp` directory,
like this:
$ mktemp XXX
/tmp/LJr
$ mktemp d/XXX
/tmp/d/IhS
After this commit, it respects the directory given in the template
argument:
$ mktemp XXX
LJr
$ mktemp d/XXX
d/IhS
Fixes #3440.
=> mktemp: respect path given in template argument

util/build-gnu.sh
At least, two use cases:
* when hacking on test update
* when we want to rebuild only Rust coreutils with the right option
Indeed, the GNU code should not cache often in this case
=> GNU testsuite: no need to rerun the GNU build

src/uucore/src/lib/features/tokenize/sub.rs, tests/by-util/test_printf.rs
When using left-justify with integer conversion (like `printf '%-o'`),
default the minimum width to 1.
Closes: https://github.com/uutils/coreutils/issues/3050
Signed-off-by: Hanif Ariffin <hanif.ariffin.4326@gmail.com>
=> printf: Default left-justify integer conversion to 1 width

src/uu/df/src/df.rs, tests/by-util/test_df.rs
Instead of showing an "invalid block-size"-error, a more specific "block-size argument too large"-error is shown if the provided block-size is too large.
=> df: show "block-size argument too large" error

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
Fixes an issue with cp not copying symlinks in spite of the -P  (no dereference option) 
fixes #3364
```console
> ln -s no-such-file dangle
> LANG=C cp dangle d2
cp: cannot stat 'dangle': No such file or directory
[1]> LANG=C cp -P dangle d2
> rm d2
>  ./uu_cp dangle d2
cp: cannot stat 'dangle': No such file or directory
[1]> ./uu_cp -P dangle d2
> rm d2
```
=> cp: Do not dereference symlink even when dangling - fix issue #3364

src/uu/df/src/blocks.rs, tests/by-util/test_df.rs
Implement "Size" column header for block sizes that are not multiples of 1024.
Fixes #3193.
=> df: fix "Size" column header

src/uu/du/src/du.rs, tests/by-util/test_du.rs
Fixes #3389
@tertsdiepraam is this what you meant? I found that `UResult` is meant to be returned at the end, but since we want to display the errors quickly, during the path traversal, we probably want to use `USimpleError`.
=> du: use USimpleError instead of set_exit_code

src/uu/df/src/columns.rs
While creating issue #3479 I noticed that the `Used` column from GNU df is one char wider than the one from uutils df, 5 chars vs. 4 chars. This PR fixes this minor detail.
=> df: set min width of "Used" column to 5

.github/workflows/GnuTests.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

src/uu/base32/src/base_common.rs, src/uu/cat/src/cat.rs, src/uu/cp/src/cp.rs, src/uu/nice/src/nice.rs, src/uucore/src/lib/mods/error.rs, tests/by-util/test_nice.rs
Step towards fixing:
- https://github.com/uutils/coreutils/issues/3331
- https://github.com/uutils/coreutils/issues/3102
To my surprise, `clap::Error` could already be used as a `UResult` due to excellent work by @shoriminimoe, which means that the exit code cal already be set to 1 by making this change in `uumain`:
```rust
let matches = uu_app().get_matches_from(args);
// to
let matches = uu_app().try_get_matches_from(args)?;
```
So, I added one additional bit of functionality to customize the error code:
```rust
use uucore::error::UClapError;
// -- snip --
let matches = uu_app().try_get_matches_from(args).with_exit_code(125)?;
```
With this change we should be able to go through all utils and fix up all the exit codes.
There is just one thing that I'm not sure about. The `UResult` …
=> `clap` exit code

src/uu/df/src/blocks.rs, src/uu/df/src/df.rs, src/uu/df/src/table.rs
This is a refactoring and consists of three parts:
1. Introduction of a `HumanReadable` enum containing the human readable variants from `BlockSize`
2. Addition of a `human_readable` field to the `Options` struct
3. Movement of header logic from `BlockSize` to `Header`
=> df: extract HumanReadable from BlockSize

src/uu/df/src/table.rs
This is a refactoring to remove some "noise" from the unit tests in `table.rs` by implementing `Default` for `Row`.
=> df: implement Default for Row for unit tests

tests/common/util.rs
As far as I can tell the CICD tests do not run as root, however some functionality can only be tested with root permissions.
While tinkering with #2689 it became apparent to me that there's a need for a a convenience wrapper to run a ucmd with root permissions.
Please let me know if there's a better way to do this.
=> tests/util: add a convenience wrapper to run a ucmd with root permissions

src/uu/mktemp/src/mktemp.rs
Change the return type of the `parse_template()` helper function in
the `mktemp` program so that it returns `Result<..., MkTempError>`
instead of `UResult<...>`. This separates the lower level helper
function from the higher level `UResult` abstraction and will make it
easier to refactor this code in future commits.
=> mktemp: return MkTempError from parse_template()

src/uu/df/src/df.rs
This PR fixes some inconsistencies in the help output when using `--help`. For example, it changes `-B, --block-size <blocksize>` to `-B, --block-size <SIZE>`, making it consistent with the corresponding help text which mentions `SIZE`.
=> df: set names for arg values & add missing space

src/uu/df/src/blocks.rs, tests/by-util/test_df.rs
This PR fixes an issue with the "Size" header for block sizes that are multiples of both 1000 and 1024. So far, such block sizes were handled as multiples of 1024 with the corresponding suffixes (e.g. "K", "M", "G"). Now they are handled as multiples of 1000 with suffixes like "kB", "MB", and "GB", in the same way as is done by GNU df.
Example: `128_000` now becomes `128kB` instead of `125K`.
=> df: fix "Size" header for multiples of 1000 & 1024

src/uu/df/src/blocks.rs, src/uu/df/src/df.rs, tests/by-util/test_df.rs
Use a default block size of 512 bytes (instead of 1024 bytes) if the `POSIXLY_CORRECT` environment variable is set.
=> df: use blocksize of 512 if POSIXLY_CORRECT is set

src/uu/df/src/blocks.rs, tests/by-util/test_df.rs
Show an `invalid --block-size argument '0'` error, instead of crashing because of a division by zero, if the user provides `0` as block size argument
=> df: show error if provided block size is zero

src/uu/df/src/blocks.rs, src/uu/df/src/df.rs, src/uu/df/src/table.rs, tests/by-util/test_df.rs
This PR fixes the header part of #3511 to make the header POSIX conform by using `Capacity` instead of `Use%` and using the `u64` value in the size column header (e.g. `1024-blocks` instead of `1K-blocks`).
It also fixes #3195, changing `Available` to `Avail` if the user specified `-h`, `-H`, or `--output`.
=> df: implement POSIX conform header line

src/uu/mktemp/src/mktemp.rs, tests/by-util/test_mktemp.rs
Correct the error that arises from a path separator in the prefix
portion of a template argument provided to `mktemp`. Before this
commit, the error message was incorrect:
$ mktemp -t a/bXXX
mktemp: failed to create file via template 'a/bXXX': No such file or directory (os error 2) at path "/tmp/a/bege"
After this commit, the error message is correct:
$ mktemp -t a/bXXX
mktemp: invalid template, 'a/bXXX', contains directory separator
The code was failing to check for a path separator in the prefix
portion of the template.
=> mktemp: error on path separator in template prefix

src/uu/stat/src/stat.rs, src/uucore/src/lib/features/fsext.rs, tests/by-util/test_stat.rs
* fix https://github.com/uutils/coreutils/issues/3485
* improve the workaround from #3280
* add tests
=> stat: improve handling of stdin/fifo (fix #3485)

tests/by-util/test_df.rs
This PR adds a missing test that checks whether the default block size is correct in the POSIX compatibility mode (`-P`).
=> df: test default blocksize in POSIX mode

src/uu/chown/src/chown.rs, src/uucore/src/lib/features/perms.rs, tests/by-util/test_chown.rs
~Help needed: the test fails because it requires root privileges to change the owner of a file. I couldn't quite follow how the other tests in this file are accomplishing this. The test passes if you run it as root. Any recommendations for what to do about this? Just skip the test if the user is not root?~
-----
This pull request updates `chown` to allow setting the owner of a file to a numeric user ID regardless of whether a corresponding username exists on the system.
For example,
```sh
$ touch f && sudo chown 12345 f
```
succeeds even though there is no named user with ID 12345.
Fixes #3380.
=> chown: allow setting arbitrary numeric user ID

src/uu/dd/src/parseargs.rs, src/uu/df/src/df.rs, src/uu/du/src/du.rs, src/uu/od/src/od.rs, src/uu/sort/src/sort.rs, src/uucore/src/lib/parser/parse_size.rs, tests/by-util/test_df.rs, tests/by-util/test_du.rs, tests/by-util/test_od.rs, tests/by-util/test_sort.rs
This PR adds a `InvalidSuffix` variant to the `ParseSizeError` enum. Right now, `InvalidSuffix` is only used by `df`. I adapted the other tools to make them compile, without changing their behavior.
=> uucore: add InvalidSuffix to ParseSizeError

src/uu/uname/src/uname.rs
fixes #2041
See my comment here: https://github.com/uutils/coreutils/issues/2041#issuecomment-1129324333
I think this is the best solution to the `-p` and `-i` flags in uname, which have been deprecated for a while and aren't supported in most implementations of uname. All other options come from [this](https://www.man7.org/linux/man-pages/man2/uname.2.html) function as part of the kernel.
With this solution these options don't show up in the help page of the program, or the `-a` output.
Some Linux distributions like Debian have already removed these options completely. This is unlikely to break any scripts as discussed [here](https://lists.gnu.org/archive/html/bug-coreutils/2005-09/msg00053.html).
=> uname: hide processor and hwplatform options

src/uu/date/src/date.rs
This PR fixes some inconsistencies in the help output when using `--help`. For example, it changes `-d, --date <date>` to `-d, --date <STRING>`, making it consistent with the corresponding help text which mentions STRING.
=> date: set names for arg values

src/uu/df/src/blocks.rs
This PR fixes some incorrect rounding of the size header. For example, `10_001` was rounded up to `10.1kB` instead of `11kB`.
=> df: fix incorrect rounding of size header

src/uu/mktemp/src/mktemp.rs, tests/by-util/test_mktemp.rs
Correct the error message when the template argument contains a path
separator in its suffix. Before this commit:
$ mktemp aXXX/b
mktemp: too few X's in template 'b'
After this commit:
$ mktemp aXXX/b
mktemp: invalid suffix '/b', contains directory separator
This error message is more appropriate and matches the behavior of GNU
mktemp.
=> mktemp: fix error msg when suffix has path sep.

src/uu/df/src/df.rs, src/uu/uniq/src/uniq.rs
This PR is more of a workaround and suppresses a clippy lint error that was introduced with Rust 1.61.
I don't know how to fix this in a clean way because of some magic behavior of `writeln!` I couldn't figure out (it adds `df: ` to the output when it's called the first time, but not in subsequent calls). This was also the reason I used `eprintln!`...
=> df/uniq: suppress lint errors

src/uu/mv/src/mv.rs, tests/by-util/test_mv.rs
It should be possible to move a single file if `target-directory` is given.
I couldn't find a way to set `min_values` conditionally so I set it to 1 and then manually check that it's not 1 unless `target-directory` is used.
=> mv: allow a single source with --target-directory

src/uu/mktemp/src/mktemp.rs, tests/by-util/test_mktemp.rs
Correct the error message produced by `mktemp` when `--tmpdir` is
given and the template is an absolute path:
$ mktemp --tmpdir=a /XXX
mktemp: invalid template, '/XXX'; with --tmpdir, it may not be absolute
=> mktemp: correct error message on absolute path

src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs
=> ls: implement --group-directories-first

src/uu/mktemp/src/mktemp.rs, tests/by-util/test_mktemp.rs
Include the suffix in the error message produced by `mktemp` when
there are too few Xs in the template. Before this commit,
$ mktemp --suffix=X aXX
mktemp: too few X's in template 'aXX'
$ mktemp --suffix=X aXX
mktemp: too few X's in template 'aXXX'
This matches the behavior of GNU `mktemp`.
=> mktemp: include suffix in error message

Cargo.lock, src/uu/df/Cargo.toml, src/uu/df/src/blocks.rs, src/uu/df/src/df.rs, src/uu/df/src/table.rs
This PR makes the following changes:
- addition of `SuffixType` enum (replaces the suffix constants)
- usage of a single `to_magnitude_and_suffix` function (instead of three)
- removal of `number_prefix` dependency
Fixes #3422.
=> df: fix rounding behavior in humanreadable mode

tests/by-util/test_dircolors.rs
This PR expands an existing test to ensure that a "mutually exclusive" error is shown when using `-bp` or `-cp`.
=> dircolors: test for correct error for -bp and -cp

src/uu/dircolors/src/dircolors.rs, tests/by-util/test_dircolors.rs
This PR makes `-b` and `-c` overridable, i.e. `-bc` is handled as if `-c` was provided, and `-cb` as if `-b` was provided, the latest argument "wins".
=> dircolors: make -b & -c args overridable

src/uu/expand/src/expand.rs
This PR simply removes an unnecessary `\n`.
=> expand: remove empty line from error message

src/uu/mktemp/src/mktemp.rs, tests/by-util/test_mktemp.rs
This matches the exit status used by GNU mktemp on usage errors.
=> mktemp: exit with status 1 on usage errors

src/uu/df/src/table.rs, tests/by-util/test_df.rs
Show the "total" label in the "source" column or in the "target"
column if the "source" column is not visible.
Before this commit,
$ df --total --output=target .
Mounted on
/
-
$ df --total --output=target .
Mounted on
/
total
=> df: show "total" label in correct column

tests/by-util/test_df.rs
Currently there is an implicit assumption in the tests that check the "size" header that there is no file system with more blocks than the width of the "size" header. For example, if the "size" header is "1K-blocks" it is assumed that there are not more than `999_999_999` blocks. Otherwise the header is prefixed with spaces and tests fail that look for a "1K-blocks" header.
This PR fixes this issue by trimming the "size" header in tests.
=> df: trim size header in tests

src/uu/mktemp/src/mktemp.rs, tests/by-util/test_mktemp.rs
Simplify the logic of computing the file path parameters (the
directory, prefix, suffix, and number of random characters) for the
temporary file created by `mktemp`. This commits adds an `Options`
struct as a layer of indirection between the application logic and
`clap`, and a `Params` struct whose associated function is responsible
for determining the file path parameters from the `Options`. This is
an improvement because the previous code had some logic for
determining file path parameters in one place and some in another
place.
This change will help me finish the work started in pull request #3568.
=> mktemp: simplify file path parameter logic

src/uu/split/src/split.rs
This PR fixes some inconsistencies in the help output when using `--help`. For example, it changes `-n, --number <number>` to `-n, --number <CHUNKS>`, making it consistent with the corresponding help text which mentions CHUNKS.
=> split: set names for arg values

src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs
When color was enabled the escape_name function was called twice which led to names like `hello world` being displayed as `"'hello world'"`.
This double quoting also led to an incorrect calculation of the width of the name, which is now also fixed.
Fixes #3584
=> ls: fix double quoting when color is enabled

src/uu/expand/src/expand.rs, tests/by-util/test_expand.rs
So far, providing invalid chars for `--tabs` caused a panic. With this PR, an error message is shown instead. A special error message is shown for `/` and `+` because those chars are allowed at the beginning of a number.
=> expand: show error if --tabs arg has invalid chars

tests/by-util/test_mktemp.rs
Combine the directory given in `--tmpdir` with any subdirectory
structure appearing in the prefix of the template string. For example,
$ mktemp --tmpdir=a b/cXXX
a/b/cNqJ
Previously, this would have incorrectly exited with an error message.
=> mktemp: combine `--tmpdir` and subdirectory info

src/uu/df/src/df.rs, tests/by-util/test_df.rs
This PR reuses the defined --sync flag for df, which was previously a
no-op, assigns its default value and uses the fact that
get_all_filesystems takes CLI options as a parameter to perform a sync
operation before any fs call.
Fixes #3564
Signed-off-by: anastygnome <noreplygitemail@protonmail.com>
=> Implement the --sync flag for df. (fixes #3564)

src/uu/mktemp/src/mktemp.rs, tests/by-util/test_mktemp.rs
Fix a bug in which `mktemp` would replace everything in the template
argument from the first 'X' to the last 'X' with random bytes, instead
of just replacing the last contiguous block of 'X's.
Before this commit,
$ mktemp XXX_XXX
2meCpfM
$ mktemp XXX_XXX
XXX_Rp5
This fixes test cases `suffix2f` and `suffix2d` in
`tests/misc/mktemp.pl` in the GNU coreutils test suite.
=> mktemp: only replace last contiguous block of Xs

src/uu/expand/src/expand.rs, tests/by-util/test_expand.rs
Show a "too large" error instead of an "invalid character" error if the provided `--tabs` argument is too large. Fixes test "e2" in the GNU test suite.
=> expand: handle too large tab size

src/uu/dircolors/src/dircolors.rs
This PR updates the error message that is shown when calling `dircolors -b --print-database` or `dircolors -b --print-database`. Instead of the error message from GNU dircolors 8.x, it is now using the error message from GNU dircolors 9.x.
This change also makes the test `print_clash2` pass in https://github.com/coreutils/coreutils/blob/master/tests/misc/dircolors.pl
=> dircolors: update error message

src/uu/mktemp/src/mktemp.rs, tests/by-util/test_mktemp.rs
Make `mktemp` exit with an error if the `--suffix` option is the empty
string and the template argument does not end in an "X". Previously,
the program succeeded.
Before this commit,
$ mktemp --suffix= aXXXb
apBEb
$ mktemp --suffix= aXXXb
mktemp: with --suffix, template 'aXXXb' must end in X
This causes the test case `suffix7f` to pass in the file `tests/misc/mktemp.pl` in the GNU test suite.
=> mktemp: error on empty --suffix in some situations

src/uu/expand/src/expand.rs, tests/by-util/test_expand.rs
This PR shows an error if a specifier is provided, but not only with the last value. For example, `expand --tabs=/1,2` and `expand --tabs=/1,/2` will now fail. It fixes tests `e5` and `e6` in the GNU test suite.
=> expand: allow specifier only with last value

src/uu/mktemp/src/mktemp.rs, tests/by-util/test_mktemp.rs
Fix issue #3587.
Now the GNU test suite `suffix9f` in `tests/misc/mktemp.pl` can pass.
=> mktemp: respect POSIXLY_CORRECT env var when parsing args

tests/by-util/test_tail.rs
Increase delay for this test to be more resillient against
load-jitter on the CI test VMs.
I hope this helps to solve https://github.com/uutils/coreutils/pull/2695#issuecomment-1150935760
=> test_tail: increase delay for test_follow_name_move_create2

src/uu/cut/src/cut.rs, tests/by-util/test_cut.rs
This fixes the argument parsing for the delimiter for the two special
cases `-d=` and `-d ''`.
This is an addendum to #2428, it fixes the two issues raised here: https://github.com/uutils/coreutils/pull/2428#issuecomment-863944719 and here: https://github.com/uutils/coreutils/pull/2428#issuecomment-1094304470
=> cut: fix argument parsing for the delimiter

src/uu/unexpand/src/unexpand.rs, tests/by-util/test_unexpand.rs
This PR replaces the use of `crash!` with returning a `Result` and adds some missing tests.
It also fixes a small bug: using the same tab position twice, for example `--tabs=1,1`, now results in an error.
=> unexpand: return Result instead of calling crash!

build.rs, src/uu/hashsum/src/hashsum.rs
Several binaries have been added to `hashsum` that have never been part
of GNU Coreutils:
- `sha3*sum` (uutils/coreutils#869)
- `shake*sum` (uutils/coreutils#987)
- `b3sum` (uutils/coreutils#3108 and uutils/coreutils#3164)
In particular, the `--bits` option, and the `--no-names` option added in
uutils/coreutils#3361, are not valid for any GNU Coreutils `*sum` binary
(as of Coreutils 9.0).
This commit refactors the argument parsing so that `--bits` and
`--no-names` become invalid options for the binaries intended to match
the GNU Coreutils API, instead of being ignored options. It also
refactors the custom binary name handling to distinguish between
binaries intended to match the GNU Coreutils API, and binaries that
don't have that constraint.
Part of uutils/coreutils#2930.
=> hashsum: Refactor `uu_app` to isolate non-"GNU Coreutils" options

src/uu/dd/BENCHMARKING.md, src/uu/dd/src/dd.rs
This is purely a performance improvement for the case of large blocksizes in dd. This reuses a single buffer instead of reallocating the buffer for each block.
For the uncommon case of dealing with conversions, this still creates a copy of the buffer and so doesn't confer any benefit. That section of the codebase requires some more complex refactoring that is probably better to change separately. See #3293 by @jfinkels 
Some very rough benchmarks piping from `/dev/zero` to `/dev/null` show an improvement of about 3x with large buffer sizes, and minor speedups with smaller buffers. Real world usage will see less benefit since there will usually be more time spent reading/writing the buffers.
Testing can be done with something like:
```
time ./target/release/dd status=progress bs=1G …
```
=> dd: reuse buffer for the most common cases

src/uu/unexpand/src/unexpand.rs
This PR fixes an inconsistency in the help output when using `--help`. It changes `-t, --tabs <tabs>` to `-t, --tabs <N, LIST>`, making it consistent with the corresponding help text which mentions `N` and `LIST`.
=> unexpand: set value name of arg

src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs
=> Forbid octal numbers for width parameter

src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs
unnecessary trailing space was being added. because we were padding for alignment,
which is not required with -m
fixes #3608
Signed-off-by: anastygnome <noreplygitemail@protonmail.com>
=> ls: Remove unnecessary trailing space when using the comma format (-m)

Cargo.lock, src/uu/cp/Cargo.toml, src/uu/cp/src/cp.rs
because ioctl fails to build on some archs:
https://buildd.debian.org/status/fetch.php?pkg=rust-coreutils&arch=ppc64el&ver=0.0.14-2&stamp=1654852034&raw=0
and it isn't maintained upstream - https://github.com/dcuddeback/ioctl-rs last commit in 2017
=> cp: Replace ioctl-sys by libc for the call to ficlone

src/uu/expand/src/expand.rs, tests/by-util/test_expand.rs
This PR adds support for shortcuts like `-1` and `-1,2` which are translated to `--tabs=1` and `--tabs=1 --tabs=2`.
Fixes #3575 and makes the tests `u1` - `u7` in https://github.com/coreutils/coreutils/blob/master/tests/misc/expand.pl pass.
=> expand: add support for "--tabs" shortcuts

src/uu/expand/src/expand.rs
I noticed that many utils preprocess arguments with:
```Rust
let args = args
.collect_str(InvalidEncodingHandling::Ignore)
.accept_any();
```
and so this PR adds this functionality to `expand`, which allows a much simpler function signature for `expand_shortcuts()`.
=> expand: simplify signature of expand_shortcuts()

src/uucore/src/lib/lib.rs
Replaces the non-existing `InvalidEncodingHandling::Lossy` enum variant in the docstring with the existing `InvalidEncodingHandling::ConvertLossy` enum variant.
=> uucore: fix invalid enum variant in docstring

src/uu/unexpand/src/unexpand.rs, tests/by-util/test_unexpand.rs
This PR adds support for shortcuts like `-1` and `-1,2` which are translated to `--tabs=1 --first-only` and `--tabs=1 --tabs=2 --first-only`, respectively. `--first-only` is omitted if `-a` or `--all` is provided.
It makes the tests `u1` - `u8` in https://github.com/coreutils/coreutils/blob/master/tests/misc/unexpand.pl pass.
=> unexpand: implement "tabs" shortcuts

Cargo.lock, src/uu/shuf/BENCHMARKING.md, src/uu/shuf/Cargo.toml, src/uu/shuf/src/shuf.rs
This PR improves the performance of `shuf` by replacing the current implementation of splitting input by a given separator with a version using the memchr crate. This crate was not used in `shuf` before, but it is already used in e.g. sort. Considering the benchmark results (see below), adding a new dependency to `shuf` is justified.
Generate input data (50,000,000 lines, 3.6 GiB):
```
cat /dev/random | base64 | fold | head -n 50000000 > input.txt
```
Run `shuf` with [hyperfine](https://github.com/sharkdp/hyperfine):
```
hyperfine -w 3 "target/release/coreutils shuf ../testdata/input.txt > /dev/null"
```
The input data was stored in tmpfs to avoid distortions from IO.
| Version  |  Time |
|---|---|
| Old version |  6.982 s ±  0.033 s |
| Improved version |  5.234 s ±  0.046 s |
| GNU shuf …
=> shuf: improve performance

src/uu/install/src/install.rs, tests/by-util/test_install.rs
Issue fix #3649 
Now passes `tests/install/install-C.sh`
- Fixed printing `'removed <file>'` message
- Added permissions comparing on `-C` options
- The test also contains check for inconsistency of `-C` with some other options, added these checks, too
=> Fix install c test

src/uu/paste/src/paste.rs, tests/by-util/test_paste.rs
Implements the `-z`/ `--zero-terminated` flag, which allows to use NUL as a line delimiter instead of newline.
Fixes #3637 and makes the tests `zno-nl-1` - `zno-nl-4` and `zno-nla1` - `zno-nla4` in https://github.com/coreutils/coreutils/blob/master/tests/misc/paste.pl pass
=> paste: implement "-z" flag

src/uu/dd/src/dd.rs, src/uu/dd/src/progress.rs
This change fixes multiple issues with the output of dd, that were easiest to complete in a single PR.
1. Correctly respect SIGUSR1 signals, by marking the setting as 'seen' once we have responded to it.
2. Fix a race condition in the output by moving all output into a single thread.
3. Fixes the bad combination of an existing 'progress' line and final output which can result in printing both on the same line.
4. Moves the check for whether output is needed (only every 1 second) into the main thread to reduce thread-to-thread communication.
The performance uplift of fixing the overzealous thread communication is significant for small blocksizes, and stacks with the buffer changes in #3600.
  | bs=4k count=1000000 | bs=1M count=20000 | bs=1G count=10
-- | -- | -- | --
Coreutils dd | 2.14s …
=> dd: fix output issues

src/uu/rm/src/rm.rs
=> `rm`: fix help text mistakenly being used as the long option

src/uu/realpath/src/realpath.rs, tests/by-util/test_realpath.rs
GNU realpath has a `--no-symlinks` alias for the `-s` and `--strip` arguments. This PR adds it to uutils realpath.
=> realpath: add "--no-symlinks" alias

src/uu/df/src/filesystem.rs
Currently, when providing a device name as a path, you get some output like:
```
$ ./target/debug/coreutils df /dev/sda2 --out=source,target
Filesystem     Mounted on
dev            /dev
```
With this PR, the output is now the same as the output from GNU df:
```
$ ./target/debug/coreutils df /dev/sda2 --out=source,target
Filesystem     Mounted on
/dev/sda2      /boot
```
Fixes #3246
=> df: fix output if input path is device name

src/uu/uniq/src/uniq.rs, tests/by-util/test_uniq.rs
This PR fixes the following clap error that occurs when calling uniq like `uniq --group <(printf "a\na\n")`
```
error: "/dev/fd/63" isn't a valid value for '--group [<group-method>...]'
[possible values: separate, prepend, append, both]
```
It makes the tests `131` and `136` in https://github.com/coreutils/coreutils/blob/master/tests/misc/uniq.pl pass.
I didn't add a test for this change because I couldn't figure out how to test it. The existing test cases `131` and `136` in `test_uniq.rs` already work fine without this change, using `run_piped_stdin`.
=> uniq: set default missing value for "group" and "all-repeated" args

src/uu/cp/src/cp.rs
With the new Rust version there is now a clippy warning:
```
warning: this lifetime isn't used in the impl
--> src/uu/cp/src/cp.rs:61:1
|
61  | / quick_error! {
62  | |     #[derive(Debug)]
63  | |     pub enum Error {
64  | |         /// Simple io::Error wrapper
...   |
105 | |     }
106 | | }
| |_^
```
This PR simply disables the corresponding lint as I don't know how to fix it otherwise.
=> cp: disable "extra_unused_lifetimes" lint

src/uu/numfmt/src/numfmt.rs, tests/by-util/test_numfmt.rs
GNU numfmt shows an "invalid padding error" when using `--padding=0` whereas uutils numfmt doesn't.
This PR adds the same behavior and makes the tests `pad-3` and `pad-3.1` in https://github.com/coreutils/coreutils/blob/master/tests/misc/numfmt.pl pass.
=> numfmt: show error if --padding is zero

src/uu/numfmt/src/numfmt.rs
This PR removes two default hints from the help text because clap automatically generates default hints in those cases.
=> numfmt: remove duplicate default hints from help

src/uu/chmod/src/chmod.rs, src/uu/cp/src/cp.rs, src/uu/ln/src/ln.rs, src/uu/rmdir/src/rmdir.rs, src/uucore/src/lib/features/fs.rs, src/uucore/src/lib/features/perms.rs
Add a `uucore::fs::is_symlink()` function that takes in a
`std::path::Path` and decides whether the given path is a symbolic
link. This is essentially a backport of the `Path::is_symlink()`
function that appears in Rust version 1.58.0. This commit also
replaces some now-duplicate code in `chmod`, `cp`, `ln`, and `rmdir`
that checks whether a path is a symbolic link with a call to
`is_symlink()`.
Technically, this commit slightly changes the behavior of
`cp`. Previously, there was a line of code like this
if fs::symlink_metadata(&source)?.file_type().is_symlink() {
where the `?` operator propagates an error from `symlink_metadata()`
to the caller. Now the line of code is
if is_symlink(source) {
in which any error from `symlink_metadata()` has been converted to
just be a `false` value. I …
=> uucore: add backport for Path::is_symlink()

tests/by-util/test_realpath.rs, tests/common/util.rs
- Fixed test to be the one from #3037 PR
- Added another test that doesn't pass now, but checks #3669 issue: `test_realpath_when_symlink_part_is_missing`
- Made `relative_symlink_file` more alike with other methods
- Added `relative_symlink_dir` that calls `symlink_dir` instead of `symlink_file`
=> test_realpath: fixed test to be the one that was supposed to be

src/uu/cat/src/cat.rs, src/uu/cp/src/cp.rs, src/uucore/src/lib/features/fs.rs, tests/by-util/test_cp.rs, tests/by-util/test_realpath.rs, tests/common/util.rs
Fixes issue #3669 
- Made better component-wise symlink handling, if any part of the path inside symlink is non-existent it fails now
- Fixed test for dangling symlink which was mistakenly changed to failing, try: 
$ ln -s nonexisting link
$ realpath link
It should print path to `nonexisting` as GNU version does
- Fixed test for looping symlink, GNU version does make an error
$ ln -s 1 2
$ ln -s 2 3
$ ln -s 3 1
$ realpath 1
It should fail with Too many levels of symbolic links
=> Realpath symlinks handling, solves issue #3669

src/uu/ls/src/ls.rs, src/uucore/src/lib/features/fs.rs, tests/by-util/test_ls.rs
- When recursively dereferencing (`-RL`) `ls` is called and there is a descendant that links to its parent, the directory is not listed again, and an error message is printed
- for `-L` dereference parameter coloring and name printing is fixed (`->` shouldn't be printed for symlinks)
- Some tests added for `-L` and "already listed"
=> ls: add already listed message

src/uu/numfmt/src/format.rs, src/uu/numfmt/src/numfmt.rs, src/uu/numfmt/src/options.rs, tests/by-util/test_numfmt.rs
This PR implements the `--to-unit` and `--from-unit` options.
It makes the tests `unit-1` - `unit-10` (with the exception of `unit-8`) in https://github.com/coreutils/coreutils/blob/master/tests/misc/numfmt.pl pass.
=> numfmt: implement "--to-unit" & "--from-unit"

src/uu/realpath/src/realpath.rs, tests/by-util/test_realpath.rs
- implement options `--relative-to` and `--relative-base`, probably closes issue #2253
- fixed exit codes for incorrect arguments, fixed issue #3102 for realpath
- added new tests for realpath
=> Realpath relative options

src/uucore/src/lib/features/fs.rs
The reason it wasn't done in #3703 is that `FileInformation` creation for directories failed in Windows, and I didn't know why.
In fac81eecad172633ffc7c71b7291d74b0090bd9a (squashed to da5808d4aca0e8a997048c8b98bea3d968a322f4) this is fixed, so now we can get back to loop looking algorithm in canonicalize.
=> canonicalize: Loop looking in windows

src/uu/numfmt/src/format.rs, tests/by-util/test_numfmt.rs
Show a "reject suffix"-error if the user provides a number with valid suffix but without a unit. For example, `numfmt 12K` and `numfmt 12K --from=none` fail whereas `numfmt 12K --from=si` doesn't.
This PR makes the test `strtod-10` in https://github.com/coreutils/coreutils/blob/master/tests/misc/numfmt.pl pass.
=> numfmt: reject suffix if unit is "none"

src/uu/cp/src/cp.rs, src/uu/ln/src/ln.rs, src/uucore/src/lib/features/fs.rs, tests/by-util/test_ln.rs
- When creating symlink from `src` to `dst`, when `dst` is regular file and `src` is either the same regular file or links to `dst`, raise "same file" error
- Moved `paths_refer_to_same_file` from `cp.rs` to common `fs.rs` to use it in `ln.rs` as well
- Added test
=> ln: symlink --force, src and dst are same file

src/uu/wc/src/wc.rs, tests/by-util/test_wc.rs
The primary computational loop in wc (iterating over all the
characters and computing word lengths, etc) is configured by a
number of boolean options that control the text-scanning behavior.
If we monomorphize the code loop for each possible combination of
scanning configurations, the rustc is able to generate better code
for each instantiation, at the least by removing the conditional
checks on each iteration, and possibly by allowing things like
vectorization.
On my computer (aarch64/macos), I am seeing at least a 5% performance
improvement in release builds on all wc flag configurations
(other than those that were already specialized) against
odyssey1024.txt, with wc -l showing the greatest improvement at 15%.
=> wc: specialize scanning loop on settings.

src/uu/ln/src/ln.rs, src/uu/realpath/src/realpath.rs, src/uucore/src/lib/features/fs.rs, tests/by-util/test_ln.rs, util/build-gnu.sh
- Simplified some code that prints errors
- Made more specific error messages for some IO error cases
- Error messages became more alike to what GNU prints
- Extracted the code for computing relative path from `realpath` and used it in `ln` as well
=> ln: error messages

src/uu/numfmt/src/format.rs, tests/by-util/test_numfmt.rs
So far, all numbers with an invalid suffix cause an "invalid suffix" error. The exception are numbers with an "i" suffix, they cause an "invalid number" error. This PR removes this exception.
This makes the `auto-suf-si-i` test in https://github.com/coreutils/coreutils/blob/master/tests/misc/numfmt.pl pass.
=> numfmt: show "invalid suffix" error for "i" suffix

tests/by-util/test_numfmt.rs
This PR enables the test `test_should_calculate_implicit_padding_per_free_argument()` and removes a line that seems unnecessary.
=> numfmt: enable ignored test

src/uu/nice/src/nice.rs
Minor nitpick (of my own previous patch!), Errno::clear() is a safe
function, it should not be inside of the unsafe block.
=> nice: Move call to Errno::clear() outside of unsafe block

src/uu/basename/src/basename.rs, tests/by-util/test_basename.rs
Closes issue #2535 
Basename has two different formats of arguments, and a simple format `NAME [SUFFIX]` doesn't support any flags, so clap parsing can't be used here, since it parses things starting with double hyphen, like `--`, `--help` and `--suffix` even when `allow_hyphen_values` specified.
- Detected when simple format is used and parsed it manually
- Added tests for that
=> Basename arguments simple format

src/uu/wc/src/count_fast.rs, src/uu/wc/src/wc.rs
When wc is invoked with only the -m flag, we only need to count the
number of Unicode characters in the input. In order to do so, we don't
actually need to decode the input bytes into characters. Rather, we can
simply count the number of non-continuation bytes in the UTF-8 stream,
since every character will contain exactly one non-continuation byte.
On my laptop, this speeds up `wc -m odyssey1024.txt` from 745ms to
109ms.
=> Implement a fast path for character counting in wc.

src/uu/split/src/platform/mod.rs, src/uu/split/src/platform/unix.rs, src/uu/split/src/platform/windows.rs, src/uu/split/src/split.rs, src/uucore/src/lib/features/fs.rs, tests/by-util/test_split.rs
Check that a file exists by calling create_new and changing the
interface of instantiate_current_writer to return a Result rather
than calling unwrap.
=> split: Don't overwrite files

src/uu/numfmt/src/format.rs, src/uu/numfmt/src/units.rs, tests/by-util/test_numfmt.rs
So far uutils numfmt rounds floats up if `--from` is not specified. For example, `numfmt 0.1` returns `1`. GNU numfmt doesn't do any rounding in this case, i.e., it returns `0.1` in the aforementioned example.
This PR fixes this behavior and makes the tests `float-1`, `float-2`, `neg-5`, and `leading-2` in https://github.com/coreutils/coreutils/blob/master/tests/misc/numfmt.pl pass.
=> numfmt: don't round floats if --from is "none"

src/uu/wc/src/count_fast.rs, src/uu/wc/src/wc.rs, tests/by-util/test_wc.rs
Byte, character, and line counting can all be done on the raw bytes
of the incoming stream without decoding the Unicode characters. This
fact was previously exploited in specific fast paths for counting
characters and counting lines. This change unifies those fast paths into
a single shared fast paths, using const generics to specialize the
function for each use case. This has the benefit of making sure that all
combinations of these Unicode-oblivious fast paths benefit from the same
optimization.
On my laptop, this speeds up `wc -clm odyssey1024.txt` from 840ms to
120ms. I experimented with using a filter loop for line counting, but
continuing to use the bytecount crate came out ahead by a significant
margin.
=> Implement wc fast paths that skip Unicode decoding.

src/uu/basenc/src/basenc.rs, util/build-gnu.sh
- Changed error code of `basenc` to 1 on wrong usage
- Fixed usage test to comply with clap output
=> basenc: error code on wrong usage, usage test

src/uu/sum/BENCHMARKING.md, src/uu/sum/src/sum.rs
Use a 4K read buffer for each of the checksum functions, which seems
reasonable. This improves the performance of BSD checksums on
odyssey1024.txt from 399ms to 325ms on my laptop, and of SysV
checksums from 242ms to 67ms.
=> Speed up sum by using reasonable read buffer sizes.

src/uu/numfmt/src/format.rs, src/uu/numfmt/src/numfmt.rs, src/uu/numfmt/src/options.rs, src/uu/numfmt/src/units.rs, tests/by-util/test_numfmt.rs
This PR implements `--format`:
> Use printf-style floating FORMAT string. The format string must contain one ‘%f’ directive, optionally with ‘'’, ‘-’, ‘0’, width or precision modifiers. The ‘'’ modifier will enable --grouping, the ‘-’ modifier will enable left-aligned --padding and the width modifier will enable right-aligned --padding. The ‘0’ width modifier (without the ‘-’ modifier) will generate leading zeros on the number, up to the specified width.
While the parsing of the format string is fully implemented, the handling of the `'` modifier (grouping) is not implemented and hence has no effect on the output.
This PR makes all `precision`, `fmt`, and `fmt-err` (with the exception of `fmt-err-9` and `fmt-err-11`) tests in https://github.com/coreutils/coreutils/blob/master/tests/misc/nu …
=> numfmt: implement --format

src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs
Fixes #2929
(Full disclosure, I am very new to rust, and contributing mainly as a learning exercise. But I hope this change can be useful).
This flag can be used to provide a easy machine parseable output from
ls, as discussed in the GNU bug report
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=49716.
There are some peculiarities with this flag:
- Current implementation of GNU ls of the `--zero` flag implies some
other flags. Those can be overridden by setting those flags after
`--zero` in the command line.
- This flag is not compatible with `--dired`. This patch is not 100%
compliant with GNU ls: GNU ls `--zero` will fail if `--dired` and
`-l` are set, while with this patch only `--dired` is needed for the
command to fail.
We also add `--dired` flag to the parser, with no additional …
=> ls: Implement --zero flag. (#2929)

src/uu/numfmt/src/format.rs, src/uu/numfmt/src/options.rs, tests/by-util/test_numfmt.rs
GNU numfmt preserves trailing zeros if no precision is specified. For example, `numfmt 10.00` returns `10.00`. uutils numfmt doesn't preserve trailing zeros and returns just `10`. This PR fixes this issue.
=> numfmt: preserve trailing zeros

util/build-gnu.sh
Related PR #3618 
Since this test is still not stable, I propose to try to increase the number of attempts from 7 to 9, and total delay will increase from 12.7 seconds to 51.1 seconds.
As I understand tests are being run in parallel, there are three tests with this delay, so this won't result in too much additional running time, 2 minutes tops for this test. And when it succeeds it stops, so it's only slow when it fails. And it sleeps most of the time not using resources.
=> gnu-tests/F-headers: increase number of attempts

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
This is needed in order to allow overriding an existing file. closes #3758 
```
$ truncate -s 512M /tmp/disk.img
$ mkfs.btrfs /tmp/disk.img
[...]
$ mkdir /tmp/disk
$ sudo mount /tmp/disk.img /tmp/disk
$ sudo chown $(id -u):$(id -g) -R /tmp/disk
$ for i in $(seq 0 8192); do echo -ne 'a' >>/tmp/disk/src1; done
$ echo "success" >/tmp/disk/src2
$
$ # GNU ls supports overriding files created with `--reflink`
$ cp --reflink=always /tmp/disk/src1 /tmp/disk/dst1
$ cp --reflink=always /tmp/disk/src2 /tmp/disk/dst1
$ cat /tmp/disk/dst1
success
$
$ # Now testing with uutils
$ cargo run cp --reflink=always /tmp/disk/src1 /tmp/disk/dst2
Finished dev [unoptimized + debuginfo] target(s) in 0.25s
Running `target/debug/coreutils cp --reflink=always /tmp/disk/src1 /tmp/disk/dst2`
$ cargo run cp …
```
=> cp: truncate destination when `--reflink` is set

src/bin/coreutils.rs, src/uu/cp/src/cp.rs, src/uu/df/src/df.rs, src/uu/du/src/du.rs, src/uu/join/src/join.rs, src/uu/ls/src/ls.rs, src/uu/numfmt/src/numfmt.rs, src/uu/od/src/od.rs, src/uu/sort/src/sort.rs, src/uu/tail/src/tail.rs, src/uu/tee/src/tee.rs, src/uu/touch/src/touch.rs, src/uu/uniq/src/uniq.rs
This PR replaces the usage of clap's deprecated `possible_values()` with `value_parser()`.
=> Replace possible_values() with value_parser()

tests/by-util/test_tail.rs, tests/by-util/test_wc.rs
=> tests: fix Freebsd test failures

src/uu/chcon/src/chcon.rs, src/uu/chcon/src/errors.rs
=> Use `u64` instead of `ino_t`/`dev_t` types

tests/by-util/test_cp.rs
The test checked `-p` option that shouldn't change timestamps.
According to coreutils documentation, it shouldn't change `atime` and `mtime`, but changes `ctime`. 
```
‘timestamps’
Preserve the times of last access and last modification, when
possible.
...
Using ‘--preserve’ with no ATTRIBUTE_LIST is equivalent to
‘--preserve=mode,ownership,timestamps’.
```
GNU coreutils `cp` works like it's written in documentation in this case.
The test was passing most of the time, because it was checking the timestamp in seconds, and in a single second both the original link and copied link were created, so their timestamps were equal. Sometimes it was failing, for instance here https://github.com/uutils/coreutils/runs/7711138977?check_suite_focus=true.
- added 5 seconds timeout between file creation …
=> test/cp: fix test_copy_through_dangling_symlink_no_dereference_permissions

tests/by-util/test_dd.rs
Fixes #3581 
I think that happens because `count=0` is stated, `dd` won't read anything from stdin. So the process could finish before we wrote something to stdin pipe, and broken pipe error is raised.
- Add `ignore_stdin_write_error` for this test
=> test/dd: fix broken pipe in test_bytes_oseek_bytes_trunc_oflag

tests/by-util/test_tail.rs
Add `ignore_stdin_write_error` for `tail -n 0` test. 
It doesn't read stdin at all, so process can already finish when trying to write to pipe.
Was failing sometimes with broken pipe, for example here: https://github.com/uutils/coreutils/runs/7723319030?check_suite_focus=true
=> test/tail: ignore broken pipe for tail -n 0

util/build-gnu.sh
Discussion #3772 
Disables three tests mentioned there
=> disable numfmt and printf LONG_MIN and INT_MAX+1 gnu-tests

src/uu/sort/src/sort.rs, src/uu/sort/src/tmp_dir.rs
- I hope it fixes #3623 issue
I think that `test_tmp_files_deleted_on_sigint` was failing, because sometimes the program finished before signal handling was finished, so the directory wasn't removed after all. I tested locally it was failing sometimes, after the fix I didn't see it failing.
- Added wait for lock just before the program finishes if the lock was taken by the signal handler
=> sort: wait when SIGINT was raised for the program to finish properly

Cargo.lock, src/uu/du/src/du.rs, src/uucore/Cargo.toml, src/uucore/src/lib/lib.rs, src/uucore/src/lib/parser.rs, src/uucore/src/lib/parser/parse_glob.rs, tests/by-util/test_du.rs
Fixes https://github.com/uutils/coreutils/issues/3628
The `parse_glob` module uses the same logic implemented in `rust-lang/glob`: https://github.com/rust-lang/glob/blob/master/src/lib.rs#L613 to identify negation in globs. When this pattern is identified, the `^` in the pattern is replaced with `!` and glob's `Pattern` is built from the string.
A disadvantage of this approach is that inconsistencies may result, if this pattern identification method diverges, when rust-lang/glob's parsing of character set negation changes.
However, I think this approach avoids having to maintain or rebuild glob parsing logic, and is the best option I could think of given that `rust-lang/glob`'s implementation is not open to extension to support multiple character set negation markers.
With the …
=> Add `parse_glob` module and update `du` to use `parse_glob`

src/uu/du/src/du.rs, src/uu/numfmt/src/options.rs, src/uu/numfmt/src/units.rs, src/uu/touch/src/touch.rs, src/uucore/src/lib/macros.rs, src/uucore/src/lib/mods/error.rs, tests/by-util/test_pr.rs, tests/common/util.rs
This PR fixes two clippy warnings caused by a new [lint](https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq) added in Rust 1.63.
=> Fix clippy warnings with Rust 1.63

tests/by-util/test_cp.rs, tests/by-util/test_df.rs, tests/by-util/test_ls.rs, tests/by-util/test_stat.rs, tests/by-util/test_tail.rs, tests/by-util/test_test.rs, tests/by-util/test_touch.rs
=> tests: ignore failing tests for FreeBSD (#3778)

src/uu/tail/src/tail.rs, tests/by-util/test_cp.rs, util/build-gnu.sh
fixes #3765
There exists a race condition (RC) that can occur if changes to a path
happen after the initial print loop in `uu_tail()`, but before the
path is added to the notify-Watcher thread in `follow()`.
@niyaznigmatullin found this RC and [identified](https://github.com/uutils/coreutils/issues/3765#issuecomment-1206154992) it as the reason why "gnu/tests/tail-2/F-headers.sh" failed sometimes in the CI and he also came up with a [fix](https://github.com/uutils/coreutils/pull/3786) for it.
The proposed fix manually handles possible events that could have been missed before.
However, this does not reduce the possibility for the RC to occur, and it uses a lot of duplicate code instead of utilizing the functionality of the Watcher thread together with the `handle_event()` function.
To …
=> tail: fix race condition

src/uu/tail/src/platform/mod.rs, src/uu/tail/src/platform/unix.rs, src/uu/tail/src/tail.rs
For the moment, these are just performance improvements (using the right name, not checking if the fd is negative as that can't be in rust, using the libc value)
The goal of this is to tackle #2873 more easily later on.
=> Rework tail plateform module to tackle #2873

src/uu/mv/src/mv.rs, tests/by-util/test_mv.rs
Fixes #3770
Behaviour of the rewritten mv utility was changed to match this in gnu's mv. Moving folder into itself does not stop entire process, but only results in showing appropriate error and changing exit code to 1 (of course moving folder into itself is skipped).
=> mv: fix error when moving directory to itself

src/uu/id/src/id.rs, src/uu/sync/src/sync.rs
I don't have hardware to test this, so I'm just going to trust the CI here. It's a reasonably simple enough change in any case.
=> uutils: Remove use of mem::uninitialized

src/uu/readlink/src/readlink.rs, src/uucore/src/lib/features/fs.rs, tests/by-util/test_readlink.rs, tests/by-util/test_realpath.rs
- Added checking for "Not a directory" error when using `-e` option and the given path is not a directory
- Added checking for "Not a directory" error when using `-f` option and the parent of the given path is not a directory
- Added tests for `readlink` and `realpath` for using trailing slashes
- Fixed behavior when both `--no-newline` and `--zero` were used, it shouldn't print the delimiter even if it's `--zero`.
- Added tests for delimiter options usage
Tests `readlink/can-e.sh`, `readlink/can-f.sh` and `readlink/multi.sh` should pass now
=> readlink: GNU compatibility

src/uu/false/src/false.rs, src/uu/true/src/true.rs
=> Use `clap::ArgAction` in `true` and `false`

src/uu/split/src/split.rs, tests/by-util/test_split.rs
happened to be an exact divisor of the buffer size used to read the
input stream.
The issue here was that file was being split byte-wise in chunks of 1G.
The input stream was being read in chunks of 8KB, which evenly divides
the chunk size. Because the check to allocate the next output chunk was
done at the bottom of the loop previously, it would never occur because
the current input chunk was fully consumed at that point. By moving the
check to the top of the loop (but still late enough that we know we have
bytes to write) we resolve this issue.
This scenario is unfortunately hard to write a test for, since we don't
explicitly control the input chunk size.
Fixes https://github.com/uutils/coreutils/issues/3790
=> Fix a bug in split where chunking would be skipped when the chunk size

src/uu/dd/src/dd.rs, src/uu/dd/src/parseargs.rs, tests/by-util/test_dd.rs
Fixes #3363
Error message of invalid arguments is now matched with GNU. PR also contains tests for this situation.
=> dd: Error message of invalid args is matched with GNU

Cargo.lock, Cargo.toml, deny.toml, src/bin/coreutils.rs, src/uu/cat/Cargo.toml, src/uu/kill/Cargo.toml, src/uu/more/Cargo.toml, src/uu/more/src/more.rs, src/uu/nice/Cargo.toml, src/uu/tail/Cargo.toml, src/uu/timeout/Cargo.toml, src/uu/wc/Cargo.toml, src/uu/yes/Cargo.toml, src/uucore/Cargo.toml, tests/by-util/test_pr.rs
I've seen there were some issues with dependencies update. I tried to run an update and see how it goes. So here it is.
What I did manually after the update:
- `os_str_bytes` updated to version 6.3.0, its MSRV is 1.57, so I downgraded it back to 6.0.1
- `time:0.3` updated to version 0.3.13, its MSRV is 1.57, so I downgraded it back to 0.3.9
- `unicode-ident` updated to 1.0.3, but its license contains [Unicode-DFS-2016](https://spdx.org/licenses/Unicode-DFS-2016.html), so I downgraded it back to 1.0.0
- `gen_completions` failed for some reason, probably because I fixed one deprecated clap function usage, changed `value_of` to `get_one::<Shell>` for clap 3.2
- fixed clippy check fail, seems new `chrono` version supports `AddAssign` trait for `DateTime`
- removed `nix:0.24.2` dependency, …
=> cargo +1.56.1 update

src/uu/dir/src/dir.rs, src/uu/vdir/src/vdir.rs
`uudoc` was getting a dummy `clap` app to generate documentation from. Now the `App` from `ls` is returned instead, so that it actually shows something.
See https://uutils.github.io/coreutils-docs/user/utils/dir.html
We still need to figure out a way to document them separately too, so that we can highlight the difference with `ls`.
**Before**
**After**
=> `dir` & `vdir`: fix docs not showing up on the documentation website

.github/workflows/CICD.yml
They sometimes hang, and when they work they do it in 30 minutes, so 90 minutes would be good timeout I guess
=> CI: add timeout to freebsd and android tests

src/uucore/src/lib/mods/ranges.rs
Another PR that should not change any functionality. I've tried to clean up this module a bit, because I had some ambitious plans for optimizing the `merge` function. The optimization worked, but was probably to complex to actually use, so I stuck with the original.
One tiny change in functionality: the `from_list` function now merges `Range`s that are adjacent, like `1-3,4-6`.
=> `uucore::ranges`: Refactor, document and test

Cargo.lock, src/uu/tty/Cargo.toml, src/uu/tty/src/tty.rs
This moves the responsibility for `unsafe` from us to `nix` and makes the code a bit cleaner as a result.
As an optimization, I moved the `isatty` check to before getting the name if the silent option is passed with an early return. The functionality should stay exactly the same.
Notes:
- I removed the `is_whitespace` check. This check has been in the code since the very first commit (https://github.com/uutils/coreutils/commit/f0be827d6bce653e2d2eacc0d0ea17b1d25ea9ef), but it seems to check for the same thing as the error code. So as far as I can tell, it was not necessary now that we have a nice result type from `nix`.
- I also removed the `collect_lossy` call because there are only flags, so the handling of invalid encoding doesn't matter.
=> `tty`: move from `libc` to `nix`

src/uu/tail/src/tail.rs
Discussed here https://github.com/uutils/coreutils/pull/3798#issuecomment-1212438940
@jhscheer, I'm not sure we need `?`, because it only happens when initially we couldn't open the file, so tail printed `cannot open file for reading` telling about an error to the user. But there can be a case when the file has been renamed twice, for example, in which case we don't print anything now, but later on the next event we will print something.
=> tail: reuse opened file --follow=descriptor and renamed

Cargo.lock, src/uu/arch/Cargo.toml, src/uu/hostname/Cargo.toml, src/uu/sync/Cargo.toml, src/uu/uname/Cargo.toml
- Updated `platform-info` version to `1.0.0` in dependencies
- Made `winapi` dependencies only for Windows target
=> dependencies: make `winapi` dependency only for Windows

examples/busybox-core.rs, examples/uuc.rs
These examples only duplicated the multicall binary via an `include!` and are therefore not necessary.
=> maintenance: remove redundant examples folder

src/uu/chcon/src/chcon.rs, src/uu/dir/src/dir.rs, src/uu/hashsum/src/hashsum.rs, src/uu/link/src/link.rs, src/uu/ls/src/ls.rs, src/uu/mkdir/src/mkdir.rs, src/uu/mv/src/mv.rs, src/uu/rmdir/src/rmdir.rs, src/uu/runcon/src/runcon.rs, src/uu/sort/src/sort.rs, src/uu/stat/src/stat.rs, src/uu/touch/src/touch.rs, src/uu/users/src/users.rs, src/uu/vdir/src/vdir.rs, src/uu/wc/src/wc.rs
This PR replaces the usage of clap's deprecated `values_of_os()` with `get_many().`
=> Replace deprecated values_of_os() with get_many()

src/uu/chcon/src/chcon.rs, src/uu/hostname/src/hostname.rs, src/uu/join/src/join.rs, src/uu/mv/src/mv.rs, src/uu/runcon/src/runcon.rs, src/uu/sort/src/sort.rs, src/uu/touch/src/touch.rs, src/uu/unlink/src/unlink.rs
This PR replaces the usage of clap's deprecated `value_of_os()` with `get_one().`
=> Replace deprecated value_of_os() with get_one()

Cargo.lock, Cargo.toml, deny.toml, src/uu/cat/Cargo.toml, src/uu/cat/src/cat.rs, tests/by-util/test_cat.rs, tests/by-util/test_dir.rs, tests/by-util/test_ls.rs, tests/by-util/test_vdir.rs
The crate became deprecated, since there is `std::os::unix::net` library
- Removed it, and changed to `std::os::unix::net`
=> Remove deprecated `unix_socket` dependency

README.md
This PR removes the build badge as it links to outdated data.
=> README: remove build badge

.github/workflows/CICD.yml
Sometimes Windows jobs hang, decrease timeout from 360 to 90 minutes, jobs should normally finish in 30 minutes maximum.
=> CI: add job timeouts 360 minutes -> 90 minutes

src/uu/mv/src/mv.rs
This PR fixes some wrong indentation that `cargo fmt` seems to ignore.
=> mv: fix indentation within uu_app()

Cargo.lock, deny.toml, src/uu/ls/Cargo.toml, src/uu/ls/src/ls.rs
- `termsize` had no releases since 2017 and it uses old dependencies
- `terminal_size` is used by `clap`, so we depend from it anyway
- Removed `termsize` dependency and added `terminal_size` dependency
- `termsize` was only used in a single place
- This removed several other dependencies as well
=> deps: change `termsize` dependency to `terminal_size`

src/uu/dirname/src/dirname.rs, src/uu/fmt/src/parasplit.rs, src/uu/head/src/head.rs, src/uu/uniq/src/uniq.rs, src/uucore/src/lib/mods/ranges.rs, src/uucore_procs/src/lib.rs, tests/by-util/test_cp.rs, tests/by-util/test_install.rs, tests/by-util/test_mv.rs, tests/by-util/test_split.rs
I don't know how to resolve this one remaining warning:
```
warning: associated function `borrow_buffer` is never used
--> src/uu/sort/src/chunks.rs:26:9
|
26 |     pub buffer: Vec<u8>,
|         ^^^^^^
|
= note: `#[warn(dead_code)]` on by default
warning: `uu_sort` (lib) generated 1 warning
```
=> Clippy fixes in multiple crates

util/android-commands.sh
When the job is stopped on timeout exceeded we don't see what `cargo test` has printed
- added 60 minutes timeout for `cargo test` run, so that it prints what `cargo` printed
=> CI/android: add 60 min timeout for cargo test to see where it's stuck

src/uu/basename/src/basename.rs, src/uu/df/src/columns.rs, src/uu/df/src/df.rs, src/uu/mv/src/mv.rs, src/uu/numfmt/src/numfmt.rs, src/uu/od/src/od.rs, src/uu/split/src/split.rs, src/uu/tail/src/tail.rs
This PR replaces the usage of clap's deprecated `occurrences_of()` with either `value_source()` or `get_many .len()`. The first is used if the number of arguments doesn't matter, and the latter if it does.
=> Replace deprecated occurrences_of()

src/uu/chcon/src/chcon.rs, src/uu/df/src/df.rs, src/uu/hashsum/src/hashsum.rs, src/uu/hostname/src/hostname.rs, src/uu/join/src/join.rs, src/uu/link/src/link.rs, src/uu/ls/src/ls.rs, src/uu/mkdir/src/mkdir.rs, src/uu/mv/src/mv.rs, src/uu/rmdir/src/rmdir.rs, src/uu/runcon/src/runcon.rs, src/uu/sort/src/sort.rs, src/uu/stat/src/stat.rs, src/uu/touch/src/touch.rs, src/uu/unlink/src/unlink.rs, src/uu/wc/src/wc.rs
This PR replaces the usage of clap's deprecated `allow_invalid_utf8()` with `value_parser()`.
=> Replace allow_invalid_utf8() with value_parser()

src/uu/tail/src/tail.rs, tests/by-util/test_tail.rs
Previously `tail -c n file.txt` caused panic if n > sizeof file.txt.
Now it prints out whole file similarly to GNU tail.
Closes https://github.com/uutils/coreutils/issues/3872
=> Fix tail panicing when seeking backwards

src/uu/rm/src/rm.rs, tests/by-util/test_rm.rs
Hi, 
This fixes #3813. also this doesn't check the permission of directories right now.
=> rm: added write-protected check for files

src/uu/ls/src/ls.rs
This PR fixes indentation issues caused by some strings that were too long and hence made `fmt` stop working (https://github.com/rust-lang/rustfmt/issues/3863).
=> ls: fix indentation within uu_app()

src/uu/cp/src/cp.rs
This PR fixes indentation issues caused by some strings that were too long and hence made `fmt` stop working (https://github.com/rust-lang/rustfmt/issues/3863).
=> cp: fix indentation within uu_app()

src/uu/expand/src/expand.rs
This PR fixes a line that's too long and hence made `fmt` stop working (https://github.com/rust-lang/rustfmt/issues/3863).
=> expand: fix line that's too long

src/uu/rm/src/rm.rs
This PR fixes indentation issues caused by some strings that were too long and hence made `fmt` stop working (https://github.com/rust-lang/rustfmt/issues/3863).
=> rm: fix indentation within uu_app()

Cargo.lock, src/uu/tail/Cargo.toml, src/uu/tail/src/chunks.rs, src/uu/tail/src/tail.rs, tests/by-util/test_tail.rs
This fixes a bug where calling `tail - < file.txt` would result
in invoking `unbounded_tail()`.
However, it is a stdin redirect to a seekable regular file and
therefore `bounded_tail` should be invoked as if `tail file.txt` had
been called.
fix #3842
=> tail: fix stdin redirect (#3842)

Cargo.lock, Cargo.toml, deny.toml
It required using `chrono` dependency with features that use old insecure `time` crate version.
Plus this change just makes less dependencies.
=> Disable default features for `procfs`

tests/by-util/test_cp.rs
=> test_cp: comment out `bad syscall` failing piece of code for Android

Cargo.lock, src/uu/pr/Cargo.toml, src/uu/pr/src/pr.rs, tests/by-util/test_pr.rs
It seems that `chrono` is the reason of deadlock or UB in android CI.
=> pr: migrate from `chrono` to `time`

tests/common/util.rs
=> fix broken pipe error in tests/common/util

src/uu/chroot/src/chroot.rs, src/uu/chroot/src/error.rs, tests/by-util/test_chroot.rs
Implements this part of the GNU docs:
```
Exit status:
125 if ‘chroot’ itself fails
126 if COMMAND is found but cannot be invoked
127 if COMMAND cannot be found
the exit status of COMMAND otherwise
```
I think we can only reliably test the the 125 case, and not the 126 and 127 cases, but if someone has ideas about how to do that I'd be happy to add it.
=> `chroot`: set exit codes to 125, 126 or 127 for errors from chroot itself

src/uu/mktemp/src/mktemp.rs, tests/by-util/test_mktemp.rs
Change `mktemp` so that it respects the value of the `TMPDIR`
environment variable, if no directory is otherwise specified in its
arguments. For example, before this commit
$ TMPDIR=. mktemp
/tmp/tmp.WDJ66MaS1T
$ TMPDIR=. mktemp
./tmp.h96VZBhv8P
This matches the behavior of GNU `mktemp`.
=> mktemp: respect TMPDIR environment variable

Cargo.lock, src/uu/stat/src/stat.rs
This closes: #3920 
I'm still fairly new to rust, apologies for any mistakes,  @tertsdiepraam , would be very grateful if you could please review and let me know if I'm heading in the right direction?. :)
=> refactor:  `stat` declarative macros to functions

src/uu/tail/src/args.rs, src/uu/tail/src/chunks.rs, src/uu/tail/src/follow/files.rs, src/uu/tail/src/follow/mod.rs, src/uu/tail/src/follow/watch.rs, src/uu/tail/src/paths.rs, src/uu/tail/src/tail.rs, src/uu/tail/src/text.rs, tests/by-util/test_tail.rs
I feel like the tail.rs file needs some refactoring to make it easier to implement new features. The file grew big over time, so I started with moving functions and structs around and moved them into new modules without changing much of the logic. The tests are all still passing, but there's much more potential for refactorings. Right now, I've spent just a few hours with it. I could dive deeper into the issue, however, I would appreciate to hear some feedback first and maybe you've got some additional ideas, since you've worked on tail much longer than I did.
EDIT:
Here's a quick overview of changes to `tail` in this step:
*  Extraction of smaller specialized modules from `tail.rs`. New modules are
- paths: Containing logic around paths and inputs
- args: Deal with argument parsing
- …
=> Refactor tail

.github/workflows/GnuTests.yml
One of the test is skipped with:
sort-h-thousands-sep.sh: skipped test: The Swedish locale with blank thousands separator is unavailable.
=> GNU test: Generate a few more locales

.github/workflows/GnuTests.yml, DEVELOPER_INSTRUCTIONS.md, README.md, util/analyze-gnu-results.sh, util/run-gnu-test.sh
+ allow the run of multiple tests.
Closes: https://github.com/uutils/coreutils/issues/3884
=> Agregate the root GNU testsuite results

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
uutils `cp` in interactive mode used to write to stdout asking for overwrite. GNU version writes to stderr.
Changed: write to stderr to make compatible with GNU.
=> cp: fix `cp-i` GNU test

src/uu/tail/src/paths.rs, src/uu/tail/src/text.rs
Fix the random errors around piped input, mainly on macos but in theory also possible on other unix systems. When we canonicalize a path to find out if we can treat input from `Stdin` as fifo (we get a resulting path here) or pipe, (we don't) then it may happen sometimes that the canonicalized path points to `/dev/fd/0`. We should treat this result like a pipe.
A different solution also may have been to remove the guards from the is_tailable() method, but I've found putting the solution into the `resolve()` method being more explicit. The `is_tailable()` method should be refactored anyways also because of @niyaznigmatullin comment here https://github.com/uutils/coreutils/pull/3919#discussion_r968150006
=> Fix random errors for piped input on macos

src/uu/factor/Cargo.toml
Done TODO
`union` feature optimizes memory for `smallvec`, from https://docs.rs/smallvec/latest/smallvec/#union:
> When the union feature is enabled smallvec will track its state (inline or spilled) without the use of an enum tag, reducing the size of the smallvec by one machine word. This means that there is potentially no space overhead compared to Vec. Note that smallvec can still be larger than Vec if the inline buffer is larger than two machine words.
=> factor: enable `union` feature for `smallvec`

src/uu/chroot/src/chroot.rs
Closes https://github.com/uutils/coreutils/issues/3783
In the issue the `-c` flag should be passed to `/bin/sh` and not be parsed by `chroot`. This is fixed by simply allowing hyphen values.
@Lunarequest, could you verify that this solves the issue?
=> `chroot`: set trailing var arg

src/uu/chroot/src/chroot.rs, tests/by-util/test_chroot.rs, util/build-gnu.sh
Try to fix the issue `skipped test: user nobody lacks execute permissions` like
https://github.com/coreutils/coreutils/blob/master/tests/cp/special-bits.sh#L45
(but this line fails as it is parsed as `cp -p c c2 ` is part of the chroot args
=> Various improvements to chroot

src/uu/dd/dd.md, src/uu/dd/src/datastructures.rs, src/uu/dd/src/dd.rs, src/uu/dd/src/parseargs.rs, src/uu/dd/src/parseargs/unit_tests.rs, tests/by-util/test_dd.rs, tests/by-util/test_ls.rs
Okay, so this is a super big PR basically all in one commit. I couldn't really split it up because everything I changed is interconnected. Sorry in advance :)
Before this PR, `dd` used clap to handle arguments. Essentially, it would rewrite this:
```
dd if=some_file.txt skip=4 iflag=skip_bytes
```
into this:
```
dd --if=some_file.txt --skip=4 --iflag=skip_bytes
```
and then passed it to clap for parsing. This is clever, but not quite correct.
First, since clap parses everything after `--` as a positional argument, `dd` fails to parse the arguments (hence this PR closes https://github.com/uutils/coreutils/issues/3010).
Second, clap now reports weird errors, which don't match what the user wrote:
```
❯ cargo run --features unix -- dd ofsdf=outfile
error: Found argument '--ofsdf' which …
```
=> `dd`: parse operands manually via positional args

src/uu/mktemp/src/mktemp.rs, tests/by-util/test_mktemp.rs
Update the usage message when too many template arguments are given on the command line to match that of GNU mktemp:
mktemp: too many templates
Try 'mktemp --help' for more information.
This fixes the test case `too-many` in the GNU test suite file `tests/misc/mktemp.pl`.
(With this change and #3940, the GNU test file `tests/misc/mktemp.pl` should now be passing.)
=> mktemp: match GNU error message on too many args

src/uu/mktemp/src/mktemp.rs, tests/by-util/test_mktemp.rs
Add special handling in `mktemp` for when the directory that will
contain the temporary file is not found. This situation now produces
the message
mktemp: failed to create file via template 'XXX': No such file or directory
to match the behavior of GNU mktemp.
This fixes the test case `pipe-bad-tmpdir` in the GNU test suite file `tests/misc/mktemp.pl`.
=> mktemp: add message for directory not found

src/uu/pr/src/pr.rs, tests/by-util/test_pr.rs
This PR let's clap handle help and version, and removes the deprecated `AppSettings::NoAutoHelp` and `AppSettings::NoAutoVersion`.
=> pr: use clap to handle help & version

src/uu/chmod/src/chmod.rs, src/uu/cp/src/cp.rs, src/uu/ln/src/ln.rs, src/uu/rmdir/src/rmdir.rs, src/uu/sort/src/chunks.rs, src/uucore/src/lib/features/fs.rs, src/uucore/src/lib/features/perms.rs, tests/by-util/test_cp.rs, tests/common/util.rs
- Add `-H` option for `cp`
- Got rid of `canonicalize` calls from `cp`, since `canonicalize` is a very general and costly operation `cp` doesn't need it. It was used only to resolve symlinks, but this is done automatically when reading file, or by using `metadata` instead of `symlink_metadata`. The only place where `canonicalize` is still used is when using `hard_link` function. There is no function in Rust library to create hard link that resolves the symlink if the path is the symlink. Probably we need to implement this function in the future.
- Removed `is_symlink` from `uucore/fs`. From Rust 1.58 `Path` has `is_symlink` method.
=> cp: add `-H` option

.github/workflows/CICD.yml, .github/workflows/GnuTests.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

src/uu/tail/src/tail.rs, tests/by-util/test_tail.rs
During #3905, I missed to reactivate the ---presume-input-pipe option. This fix will reactivate it.
=> tail: Reactivate ---presume-input-pipe option

src/uu/df/src/df.rs
This PR replaces the usage of clap's deprecated `values_of_lossy()` with `get_many()`.
=> df: replace deprecated values_of_lossy()

src/uu/du/src/du.rs, src/uu/stty/src/stty.rs
This PR replaces the usage of clap's deprecated `is_present()` with `contains_id()`.
=> du,stty: replace deprecated is_present()

tests/by-util/test_chroot.rs, tests/by-util/test_test.rs, tests/common/util.rs
It is blocking the executions of the tests and I suspect it is breaking android
=> Disable test_when_piped_input_then_no_broken_pipe by default

src/uu/rm/src/rm.rs, tests/by-util/test_rm.rs
Added descend functionality for rm's interactive mode
Setup
```
mkdir -p a/b/
touch a/at.txt a/b/bt.txt
rm -ri a
```
Current
```
rm: remove file 'test/a/b/bt.txt'? y
rm: remove file 'test/a/at.txt'? y
rm: remove directory 'test/a/b'? y
rm: remove directory 'test/a'? y
```
GNU
```
rm: descend into directory 'a'? y
rm: descend into directory 'a/b'? y
rm: remove regular empty file 'a/b/bt.txt'? y
rm: remove directory 'a/b'? y
rm: remove regular empty file 'a/at.txt'? y
rm: remove directory 'a'? y
```
After Commit (Using the same answers as before)
```
rm: descend into directory 'test/a'? y
rm: descend into directory 'test/a/b'? y
rm: remove file 'test/a/b/bt.txt'? y
rm: remove file 'test/a/at.txt'? y
rm: remove directory 'test/a/b'? y
rm: remove directory 'test/a'? y
```
After Commit (Don't …
=> rm: Added descend messages for interactive mode Fixes #3817

src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs
Hello,
This PR addresses issue #3625, which adds support to the `+FORMAT` date in `--time-style`. Given the dynamic argument, I created a custom parsing function to accommodate for the new format. 
I have added the corresponding tests, but probably my code added might not be up to standards, as I am new at it and trying to improve, and basically doing what the borrow checker tells me every time :). I would be more than happy to make changes to improve it. 
I did notice using the +Format on the linked issue, namely `$ TIME_STYLE="+%Y-%m-%d %H:%M:%S.%N %z" ls exe -al` breaks with 
```
thread 'main' panicked at 'a Display implementation returned an error unexpectedly: Error', /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/alloc/src/string.rs:2406:14
note: run with `RUST_BACKTRACE=1` …
```
=> ls: add support for +FORMAT in timestyle

.github/workflows/CICD.yml, build.rs, tests/tests.rs
Generating the tests to run in `build.rs` created problems for tooling. For example, `cargo fmt` was ignoring the `test_*.rs` files and needed to be passed these files manually to be formatted. Now we simply use the feature mechanism to decide which tests to run.
=> tests: do not generate module structure in `build.rs`

tests/by-util/test_tail.rs, tests/common/random.rs
This is a follow up pr to #3905 (refactoring tail), in which the tests for tail are updated to reflect the current state of tail's implementation. 
I removed all cfg attributes from the tests which limited the tests by vendor, os ([ci 8594](https://github.com/uutils/coreutils/actions/runs/3101684375)), then added cfg attributes again for the tests failing in the ci for a specific target os ([ci 8604](https://github.com/uutils/coreutils/actions/runs/3107790421), [ci 8605](https://github.com/uutils/coreutils/actions/runs/3108275942), [ci 8606](https://github.com/uutils/coreutils/actions/runs/3109053464), [ci 8607](https://github.com/uutils/coreutils/actions/runs/3109572586)). This is a quick overview over the outcome and the main differences to before the refactoring:
+ Piped input: works …
=> `tests/tail`: Fix tests to reflect changes from the refactoring #3905

src/uu/cp/src/cp.rs, src/uu/cp/src/platform/linux.rs, src/uu/cp/src/platform/macos.rs, src/uu/cp/src/platform/mod.rs, src/uu/cp/src/platform/other.rs
Move the copy-on-write functions for `cp` to their own module. This provides a layer of indirection so that the `cp.rs` module need only use `platform::copy_on_write()`, and the `platform` module is responsible for providing the appropriate implementation for the current platform. This commit does not change the behavior of the code, just its organization.
=> cp: move copy_on_write funcs to platform module

src/uu/split/src/filenames.rs, src/uu/split/src/number.rs, src/uu/split/src/split.rs, tests/by-util/test_split.rs
This commit now allows split to pass split/numeric.sh
=> Add support for starting suffix numbers

.github/workflows/GnuComment.yml, .github/workflows/GnuTests.yml
My attempt at: https://github.com/uutils/coreutils/pull/4006
Heavily based on: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
It will not entirely work until it's merged, but I'm hoping to at least create the following zip file from the GnuTests workflow:
```
comment.zip
- NR           <- the PR number saved to a file
- result.txt   <- the actual results
```
This artifact can then be used to post the comment in the GnuComment workflow.
=> CI: post gnu comment

src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs
Fixes https://github.com/uutils/coreutils/issues/3753
=> ls: align --ignore behavior with that of GNU ls

.github/workflows/GnuComment.yml
Merging this immediately as it has only to do with the comment workflow
I think we're very close to getting it right: https://github.com/uutils/coreutils/actions/runs/3214546794
=> GnuComment: convert loaded text into string

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
Allow `cp --remove-destination` to remove a symbolic link loop (or a symbolic link that initiates a chain of too many symbolic links). Before this commit, if `loop` were a symbolic link to itself, then
cp --remove-destination file loop
would fail with an error message. After this commit, it succeeds. This matches the behaviotr of GNU cp.
This should make the GNU test suite file `tests/cp/dir-rm-dest.sh` pass.
=> cp: allow removing symbolic link loop destination

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs, tests/common/util.rs
This pull request includes two related fixes to `cp`.
First, we make cp preserve the permissions of a directory when copying it. Before this commit,
cp -pR src/ dest/
failed to copy the permissions of `src/` to `dest/`. After this commit, the permissions are correctly copied.
Second, we make stop `cp` from terminating prematurely if a file in a directory is inaccesible due to insufficient permissions.
These two changes fix on assertion in GNU test suite file `tests/cp/fail-perm.sh` (but it will not be passing yet).
=> cp: preserve permissions when copying directory and don't terminate early on inaccessible file

src/uu/chroot/src/chroot.rs, tests/by-util/test_chroot.rs
Should unbreak tests/misc/chroot-fail.sh
=> chroot: improve support of --skip-chdir

.github/workflows/GnuComment.yml
Reverts uutils/coreutils#4021
Broke the comment https://github.com/uutils/coreutils/pull/4021#issuecomment-1274135706
=> Revert "build(deps): bump actions/github-script from 3.1.0 to 6.3.1"

tests/by-util/test_factor.rs
Factoring 10,000 integers was causing MIRI to not just fail but crash on OSX. This isn't really a unit test anyway. Reduced it to a more sane 1000 integers.
=> fix MIRI crash of long running unit test

src/uu/dircolors/src/dircolors.rs, tests/by-util/test_dircolors.rs
Fixes #3761 by accepting both `^` and `!` for negation.
=> dircolors: align TERM matching behavior with that of GNU dircolors

Cargo.lock, src/uu/env/Cargo.toml, src/uu/env/src/env.rs
Closes https://github.com/uutils/coreutils/issues/3188
This PR reraises any signals from the child process instead of printing them. This is more in line with GNU behaviour. The message that we previously printed was actually not GNU behaviour, but part of the shell.
I'm not sure how to test this in the CI. I need to spawn a child process that raises a signal to respond to. In normal testing I used a custom C program, but I'm not sure how to get that compiled in the CI:
```C
#include <signal.h>
#include <stdlib.h>
int main(int argc, char** argv) {
raise(atoi(argv[1]));
}
```
=> `env`: reraise signal from child process

Cargo.lock, Cargo.toml
This one is not handled correctly by dependabot, because we need to update `phf` and `phf_codegen` at the same time.
=> deps: update phf to 0.11.1

README.md, docs/book.toml, docs/src/build.md, docs/src/installation.md, src/bin/uudoc.rs
Since uutils is now packaged in a few repositories, I think it's about time we start documenting them. Currently, only Nix is mentioned in the `README.md`. Adding all distributions to the `README.md` would be a bit too long though, so I made a page in the documentation instead. I've called this page "Installation" and have renamed the old "Installation" page to "Build from source".
For each distribution/package manager, I have added a badge showing the currently packaged version (via repology.org) and instructions for installation. I also added a little note if uutils is currently only available in an unstable/edge repository.
Note: The table of contents only shows up with `mdbook-toc`. I wish `mdbook` would adopt these kinds of features, but it doesn't yet :) I'll add `mdbook-toc` to the …
=> docs: add installation page with package managers

Cargo.lock, tests/by-util/test_cp.rs, tests/by-util/test_mknod.rs
- updated some dependencies versions
- fixed tests for update to `clap-4.0.15`, it used to use `"` for argument values, now uses `'` on incorrect usage
=> `cargo +1.60.0 update`

src/bin/uudoc.rs
In the current docs, the first line of the usage string is skipped: https://uutils.github.io/user/utils/b2sum.html. This removes the skip and strips the `Usage:` string.
=> docs: fix usage string since clap 4

Cargo.lock, src/uu/cut/Cargo.toml, src/uu/cut/src/cut.rs
Fixed the reason it was failing to update automatically.
- `for_byte_record_with_terminator` method now requires for `BufReader` to be mutable
Also it brought `serde` to `Cargo.lock` because of this: https://github.com/rust-lang/cargo/issues/10801
=> Bump bstr 1.0.1

src/uu/split/src/split.rs
Seems that #4009 was tested for old `clap`.
Fix changes for `clap` version 4
=> split: fix `---io` for clap 4

tests/by-util/test_mkdir.rs, tests/by-util/test_test.rs
Tests used system `touch` and `ls`.
Windows systems usually don't have coreutils installed.
Changed to `AtPath::touch` and `uu_ls` calls.
=> tests: fixed some tests on Windows

src/uu/cp/src/copydir.rs, src/uu/cp/src/cp.rs
This pull request refactors `copy_directory()` and related helper functions into its own new module `copydir.rs`. This commit also adds some additional structs and helper functions to make the code easier to read and maintain. This commit does not change the behavior of the `copy_directory()` function, only the organization of the code.
I am proposing this change because I felt while working on pull request #3894 that it was harder than necessary for me to read and understand the code.
=> cp: move copy_directory() to its own module

Cargo.lock, deny.toml, src/uu/cp/Cargo.toml, src/uu/date/Cargo.toml, src/uu/date/src/date.rs, src/uu/du/Cargo.toml, src/uu/du/src/du.rs, src/uu/hostname/Cargo.toml, src/uu/hostname/src/hostname.rs, src/uu/rm/Cargo.toml, src/uu/rm/src/rm.rs, src/uu/sync/Cargo.toml, src/uu/sync/src/sync.rs, src/uu/tail/Cargo.toml, src/uu/tail/src/platform/windows.rs, src/uu/touch/Cargo.toml, src/uu/touch/src/touch.rs, src/uu/whoami/Cargo.toml, src/uu/whoami/src/platform/windows.rs, src/uucore/Cargo.toml, src/uucore/src/lib/features/fs.rs, src/uucore/src/lib/features/fsext.rs, src/uucore/src/lib/lib.rs
`winapi` is not being maintained, and `windows-sys` is maintained by Microsoft itself, as I understand.
Changed all direct dependencies from `winapi` to `windows-sys`. 
As I understand some other crates we use are also working in this direction.
=> Migrate from `winapi` to `windows-sys`

src/uu/hashsum/src/hashsum.rs, tests/by-util/test_hashsum.rs
Hi
This PR address issue #4042 where checksum would stop on failure, rather than continue processing each file(as does GNU). 
In this way, now it would try to process every file before exiting.
=> hashsum: warn on file not found rather than fail

src/uucore/src/lib/features/fs.rs, tests/by-util/test_ls.rs
Fixes a bit of https://github.com/uutils/coreutils/issues/3544
I kept the format identical to the format and Unix and approximated the permissions for Windows. Here's an example of the output:
```
total 0
drwxrwxrwx 1 somebody somegroup 0 Oct  9 00:36 directory
-rwxrwxrwx 1 somebody somegroup 0 Oct  9 00:30 link
-rwxrwxrwx 1 somebody somegroup 0 Oct  9 00:30 read-and-write
-r-xr-xr-x 1 somebody somegroup 0 Oct  9 00:30 readonly
```
Unfortunately, I can't get the link to work under Wine. I'm not sure if it's an issue with Wine or with the util (it'd be great if someone on Windows could test this. @AndreasBrostrom, maybe?)
=> `ls`, `stat`: Show more info in long format on Windows

Cargo.lock, Cargo.toml, tests/by-util/test_sort.rs
I've seen that test `test_sort:;test_tmp_files_deleted_on_sigint` still sometimes fails, in a line where it checks that `sort` has created the temporary directory and it exists, so the test fails not finding the temporary directory.
- Wait more for the temporary directory to be created by `sort`. Before the change it slept for 0.1 seconds and right after that
asserted if `sort` has created the directory. Sometimes `sort` didn't manage to create the directory in 0.1 seconds. So the change is: now it tries to wait for `timeout` starting with 0.1 seconds, and if directory was not found, it tries 4 more times, each time increasing the time twice. Once the directory is found it breaks.
- Use a new generated file. Before, the sort could work faster and we could be late with sending the signal. …
=> test_sort: Fix timeout issue `test_tmp_files_deleted_on_sigint`

src/uu/hashsum/src/hashsum.rs, tests/by-util/test_hashsum.rs
Resolves #3818 
Signed-off-by: Huijeong Kim <herehuijeong@gmail.com>
=> hashsum: test b3sum::test_nonames for real

src/uu/cp/src/copydir.rs, src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
Fix a bug where `cp` failed to copy ancestor directories when using
the `--parents` option. For example, before this commit:
$ mkdir -p a/b/c d
$ cp -a --parents a/b/c d
$ find d
d
d/c
After this commit
$ mkdir -p a/b/c d
$ cp -a --parents a/b/c d
$ find d
d
d/a
d/a/b
d/a/b/c
Partially resolves issue #3332.
(My first attempt was in #3894.)
=> cp: correctly copy ancestor dirs in --parents mode

src/uu/numfmt/src/format.rs, tests/by-util/test_numfmt.rs
GNU numfmt returns `0` if it is called with a negative zero (`numfmt -- -0`) whereas uutils numfmt returns `-0`. This PR fixes this issue and makes test `neg-6` in https://github.com/coreutils/coreutils/blob/master/tests/misc/numfmt.pl pass.
=> numfmt: handle negative zero values

src/uu/hashsum/src/hashsum.rs, tests/by-util/test_hashsum.rs
Reverts uutils/coreutils#4027
to see if we regressed because of this or not :)
=> Revert "hashsum: test b3sum::test_nonames for real"

src/uu/chown/src/chown.rs, tests/by-util/test_chown.rs
If the arg starts with an id numeric value, the group isn't set but the separator is provided, we should fail with an error
Should fix tests/chown/separator.sh
=> chown: fails when XXXX. or XXXX: is provided (when XXXX is numeric value)

src/uu/hashsum/src/hashsum.rs, tests/by-util/test_hashsum.rs
Let's see if we can enable this again.
I'm still not sure _why_ it failed, but it failed on the `unwrap` so now I'm only using `unwrap_or`. @huijeong-kim I've put you as co-author of this commit :)
=> hashsum: enable testing --no-names

src/uu/numfmt/src/numfmt.rs, tests/by-util/test_numfmt.rs
When specifying `--field -2,4`, GNU numfmt interprets it as the range `1-2` and the field `4` whereas uutils numfmt fails with a clap error because of the `-`. This PR fixes this issue and makes the tests `field-range-14` and `field-range-15` in https://github.com/coreutils/coreutils/blob/master/tests/misc/numfmt.pl pass.
=> numfmt: allow hyphen values for --field option

tests/by-util/test_numfmt.rs
This PR adds a test for `--field -`, which selects all fields, and is currently untested.
=> numfmt: add test for "--field -" (all fields)

src/uu/numfmt/src/numfmt.rs, src/uucore/src/lib/mods/ranges.rs, tests/by-util/test_numfmt.rs
GNU numfmt allows ' ' (space) as a field separator, for example `--field "1,2 4"`, whereas uutils numfmt shows an error. This PR fixes this issue and makes the test `field-range-18` in https://github.com/coreutils/coreutils/blob/master/tests/misc/numfmt.pl pass.
=> numfmt: allow ' ' as field separator

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
Change `cp` to terminate with an error when attempting to copy through a dangling symbolic link with the `--force` option. Before this commit,
touch src
ln -s no-such-file dest
cp -f src dest
would incorrectly replace `dest` with the contents of `src`. After this commit, it correctly fails with the error message
cp: not writing through dangling symlink 'dest'
This appears in the GNU test suite file `tests/cp/thru-dangling.sh`.
=> cp: restrict copy through dangling symlink with -f

src/uu/mktemp/src/mktemp.rs, tests/by-util/test_mktemp.rs
Hello,
This PR closes issue #4075, where `--tmpdir` would not work when no value was set.
=> mktemp: allow default missing value

src/uu/cp/src/cp.rs, src/uu/cp/src/platform/linux.rs, src/uu/cp/src/platform/macos.rs, tests/by-util/test_cp.rs
Implement the `--copy-contents` option when the source is a FIFO, so that the contents of the FIFO are copied (when the bytes become available for reading) instead of the FIFO object itself. For example,
$ mkfifo fifo
$ cp --copy-contents fifo outfile &
[1] 1614080
$ echo foo > fifo
$ cat outfile
foo
[1]+  Done                    cp --copy-contents fifo outfile
=> cp: implement --copy-contents option for fifos

src/uu/printenv/src/printenv.rs, tests/by-util/test_printenv.rs
For example `env a=b=c printenv a=b` should fail
Tested by tests/misc/printenv.sh
=> Weird env variable names should trigger an error.

src/uu/ls/src/ls.rs
At the time of #2145, `major` and `minor` have not been added to libc, so we have to manually calculate the device number.
And those functions have been added ([rust-lang/libc#2937](https://github.com/rust-lang/libc/pull/2937)) so that we can employ them.
BTW, I called `cargo fmt` on this file, but I didn't see `rustfmt.toml` in this project, so if you guys don't like it, feel free to ask to to discard the format changes.
Ref: #2140
=> ls: use libc::{major, minor} to calculate device number

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
Removes the error message on 'no' option in interactive mode for cp for the overwrite prompt.
Relevant link - https://github.com/uutils/coreutils/issues/4000#issuecomment-1287779975
Closes #4023.
=> cp: remove interactive mode message on 'no'

src/uu/cp/src/platform/linux.rs, tests/by-util/test_cp.rs
Correct the behavior of `cp --reflink=never --sparse=always` so that it performs a sparse copy (_Edit:_ on Linux). Before this commit, it was incorrectly performing a dense copy.
This should cause the GNU test suite file `tests/cp/sparse.sh` to pass.
=> cp: use sparse copy on --sparse=always

.vscode/cspell.dictionaries/workspace.wordlist.txt, Cargo.lock, deny.toml, docs/src/extensions.md, src/bin/uudoc.rs, src/uu/cp/Cargo.toml, src/uu/cp/src/copydir.rs, src/uu/cp/src/cp.rs
Closes #1455
Based on the recent discord discussion around https://github.com/uutils/coreutils/issues/1455, I figured I would give it a go to see what the feature would look like. This is mostly meant to spark some discussion about what this should look like and how it should behave.
Details of this implementation:
- `indicatif` is used to draw the progress bar.
- Before copying all the files, we have to recursively read all the files to get the total size (like `du`)
- With very large directories, this means a bit of lag before we can actually show the bar. The entire application is also slowed down noticeably, though I haven't done any benchmarks.
- I ignored the size of the directories themselves as it seems insignificant in most cases.
- We update the progress bar with each copied …
=> `cp`: add progress bar

.github/workflows/GnuTests.yml
Switch back to using `output-type` in GNU tests with coverage. In GNU tests with coverage `grcov` is fetched from `crates.io` unlike in our tests, where we are building the latest repository commit. Fixes issue from run: https://github.com/uutils/coreutils/actions/runs/3467904909/jobs/5793205069
`grcov` supported `output-type` after their "breaking" `output-types`-introduction https://github.com/mozilla/grcov/commit/ee1604c22da3558616c4621235ef7890e668a6b2
=> CI: switch back to use `output-type` in GNU tests with coverage

tests/by-util/test_cp.rs
Disable the test, until the issue resolved.
Related discussions:
- #4079
- #3477
- #4099
=> test_cp: temporarily disable non-working test on Android

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
`cp --preserve` with no arguments doesn't use the default attributes. This PR fixes it.
Tests for various preserve cases will be added here: https://github.com/uutils/coreutils/pull/4099.
Closes #4122.
=> cp: make `--preserve` use the defaults when empty

src/uu/cp/src/cp.rs, src/uu/ln/src/ln.rs, src/uu/mv/src/mv.rs, src/uu/rm/src/rm.rs, src/uucore/src/lib/lib.rs, tests/by-util/test_cp.rs, tests/by-util/test_ln.rs, tests/by-util/test_mv.rs, tests/by-util/test_rm.rs
Several utils (`cp`, `ln`, `rm` and `mv`) have some places where they prompt the user for  `yes` or `no`. Currently, they use custom implementation with slightly different details (different suffix, printing to stdout instead stderr, etc.). Therefore, I wanted to unify them. I've moved `prompt_yes` from `cp` to `uucore` with slight modifications. It supports `format!`-style syntax, puts the util name up from ~and adds `[y/N]:` to the end~.
`cp` had a suffix of `[y/N]:`, but none of the other utils did. GNU also does not have it (not even for `cp`). I removed it because it broke too many GNU tests.
=> `uucore`: add `prompt_yes` macro

src/uu/sort/src/sort.rs, tests/by-util/test_sort.rs
A test case for this is `sort -k 2n,2n` which should be accepted, because `n` is compatible with itself.
I think the only case we were missing was the case where a mode is given twice. All other combinations are probably incompatible.
Resolves #4129.
=> `sort`: allow a sort mode to appear multiple times

.github/workflows/CICD.yml, tests/by-util/test_cp.rs
Closes #3779.
Check that FreeBSD CI failed when the builds or tests failed here: https://github.com/miles170/coreutils/actions/runs/3488640374/jobs/5837818835
=> CI: fix FreeBSD CI passed when tests failed

src/uu/stat/src/stat.rs
Fix "error: unused import: `has`" 
See https://github.com/uutils/coreutils/actions/runs/3502879944/jobs/5867563214
=> stat: remove unused import

src/uu/dd/src/parseargs.rs, src/uucore/src/lib/parser/parse_size.rs, tests/by-util/test_dd.rs
Allow uppercase "B" on its own as a unit specifier for the `count`, `seek`, and `skip` arguments to `dd`.
For example,
$ printf "abcdef" | dd count=3B status=none
abc
This should fix GNU test suite file `tests/dd/bytes.sh`.
=> dd: allow B as a suffix for count, seek, and skip

src/uu/dd/src/dd.rs
This change uses an enum rather than a trait to represent the possible data sources for `dd`. This is a refactor only, it does not change any behavior of `dd`. The purpose of this change is to prepare for a future pull request that will introduce a new enum variant `Dest::Fifo` to represent writing to a named pipe on Unix systems. The way `dd` works for named pipes is different from the way it works for regular files or stdout. For example, since a named pipe is not seekable, a `seek=1` option should actually cause a _read_ of one block, rather than a seek as in a regular file, or a _write_ as in stdout. This is all to try and get `tests/dd/no-allocate.sh` in the GNU test suite passing.
Anyway, you can ignore all of that stuff about named pipes to review this pull request, but it provides …
=> dd: create Dest enum and simpler Output struct

.github/workflows/CICD.yml, .github/workflows/FixPR.yml, .github/workflows/GnuTests.yml
Closes #4154.
1. remove use of `actions-rs/cargo`
> `actions-rs/cargo` is currently inactive and has an issue like https://github.com/actions-rs/cargo/issues/216
2. remove use of `actions-rs/toolchain`
> `actions-rs/toolchain` is currently inactive and has an issue like https://github.com/actions-rs/toolchain/issues/219
3. `Swatinem/rust-cache` should happen after the toolchain. See https://github.com/Swatinem/rust-cache
4. fix `rust-cache` cache conflict. See [Post Run Swatinem/rust-cache@v2](https://github.com/uutils/coreutils/actions/runs/3501453143/jobs/5865167599)
5. replace `actions-rs/install` with cargo install, since with `Swatinem/rust-cache` the binary can be cached
> `actions-rs/install` is currently inactive and has an issue like …
=> CI: update actions to run on Node 16

.github/workflows/CICD.yml
Closes #4163
There are some edge cases where SSH disconnection leads to unexpected issues.
Increase the memory limit to prevent the SSH disconnection.
See https://github.com/uutils/coreutils/issues/4163#issuecomment-1321052947
=> CI: increase the FreeBSD memory limit to 4096

src/uu/cp/src/platform/macos.rs, tests/by-util/test_cp.rs
=> cp: fix `cp --force --backup f f` fails on macOS

.github/workflows/GnuTests.yml
This PR is an attempt to fix the failing CI GNU tests by removing the `python-pyinotify` dependency because the package is no longer in ubuntu.
=> CI: change python-pyinotify to python3-pyinotify

.github/workflows/GnuTests.yml
GNU tests are not working properly after `ubuntu-latest` changed to 22.04. Explicitly specifying Ubuntu version as `ubuntu-20.04` for GNUTests CI, until there is a fix for `ubuntu-latest`.
The issue when using `ubuntu-latest`:
- #4186
=> gnu-tests: rollback to `ubuntu-20.04` for gnu-tests until fixed

src/uu/split/src/filenames.rs, src/uu/split/src/number.rs
This PR fixes some "backticks are unbalanced" warnings when using `clippy::pedantic`.
=> split: fix "backticks are unbalanced" warnings

src/uu/cp/src/cp.rs
closes #4178
This PR suspends the progress bar when printing the copied files with the `--verbose` flag.
=> Suspend the progress bar before printing the copied files.

.github/workflows/CICD.yml, src/uu/basename/src/basename.rs, src/uu/echo/src/echo.rs, src/uu/fmt/src/parasplit.rs, src/uu/ls/src/ls.rs, src/uu/mktemp/src/mktemp.rs, src/uu/numfmt/src/options.rs, src/uu/od/src/inputoffset.rs, src/uu/who/src/who.rs, src/uucore/src/lib/features/fsext.rs, src/uucore/src/lib/features/tokenize/num_format/formatters/decf.rs, tests/by-util/test_ls.rs, tests/by-util/test_pinky.rs, tests/by-util/test_tail.rs, tests/common/random.rs, tests/common/util.rs
This PR fixes "empty String is being created manually" warnings when using `clippy::pedantic`.
=> chore: standardize creation of empty strings

src/bin/uudoc.rs, src/uu/expr/expr.md, src/uu/numfmt/numfmt.md, src/uu/numfmt/src/numfmt.rs, src/uucore_procs/src/lib.rs
A while ago, I posted some plans for better documentation: https://github.com/uutils/coreutils/issues/3181
This PR is a another step towards that plan.
`uudoc` now supports clap's `after_help`, which is useful for a lot of utils. We might need to tweak what it looks like, but we can figure that out later.
In https://github.com/uutils/coreutils/issues/3181, I created a diagram that might be useful in understanding this change. If a file like `numfmt.md` is available, `uudoc` will try to read that instead of getting its information from `clap`. The reason for this is that we don't want to feed `clap` raw markdown. Instead, we want to render the markdown to something that looks nice in the terminal. For now, I only make one simple change before handing the string to `clap`: removing all …
=> Markdown in docs v1

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs, tests/common/util.rs
Prevent a panic in `cp -a` when the target of a hard link already exists in the target directory structure.
For example,
$ mkdir -p src dest/src
$ touch src/f dest/src/f
$ ln src/f src/link
$ cp -a src dest
The `cp` command now succeeds without error.
This should cause the GNU test suite file `tests/cp/preserve-link.sh` to pass.
=> cp: preserve hard links when target already exists

src/uu/timeout/src/timeout.rs, src/uucore/src/lib/features/process.rs
As far as I can tell, all this functionality is covered by `ExitStatusExt` in `std` and it's only used in timeout.
=> `uucore/process`: remove custom `ExitStatus`

src/uu/touch/src/touch.rs, tests/by-util/test_touch.rs, util/build-gnu.sh
For example,
$ touch -d "+1 days" f
It doesn't support all relative times. For example, "+1days" and "11:00 tomorrow" and many more still don't work.
Fixes #3964.
=> touch: add support for some relative times

tests/by-util/test_cat.rs, tests/by-util/test_cp.rs, tests/by-util/test_dd.rs, tests/by-util/test_factor.rs, tests/by-util/test_rm.rs, tests/by-util/test_seq.rs, tests/by-util/test_sort.rs, tests/by-util/test_tac.rs, tests/by-util/test_tail.rs, tests/by-util/test_tee.rs, tests/by-util/test_tty.rs, tests/by-util/test_yes.rs, tests/common/util.rs
UChild provides:
* convenience methods to assert the current or final state of the child process
* other convenience methods for usual actions on the child process
* reduce deadlock situations and provide safer piping into the child process stdin
Changes in UCommand:
* We capture the output of the child process stdout and stderr in a temporary file per default instead of using `Stdio::piped` for stdout and stderr.
* Provide a method `stderr_to_stdout` to redirect stderr to stdout
Note, that some tests needed to be adjusted to the new return value of `UCommand::run_no_wait`.
=> `tests/common/util`: Implement UChild, an abstraction for std::process::Child, to return UChild from run_no_wait instead

src/uu/printf/src/printf.rs, src/uu/seq/src/seq.rs, src/uucore/src/lib/features/memo.rs, src/uucore/src/lib/features/tokenize/sub.rs, src/uucore/src/lib/features/tokenize/token.rs, src/uucore/src/lib/features/tokenize/unescaped_text.rs
Add an `sprintf()` function (and `printf()` function) to `uucore::memo`.  The `sprintf()` function behaves roughly like the standard Rust `format!()`, but follows our implementation of the GNU `printf` formatting logic instead. The `printf()` function is a convenience function that wraps the `Memo::run_all()` function in order to provide a more user-friendly name (or at least more familiar to C programmers).
This pull request was inspired by this comment requesting the use of `%g` to format a number in `dd`: https://github.com/uutils/coreutils/pull/4169#discussion_r1027356289
=> uucore: add sprintf() function

Cargo.lock, src/uu/dd/Cargo.toml, src/uu/dd/src/dd.rs, src/uu/dd/src/numbers.rs, src/uu/dd/src/progress.rs, tests/by-util/test_dd.rs
Adjust the rendering of the concise byte counts in both SI and IEC
units to better match the behavior of GNU dd.
Before this commit,
$ head -c 1024 /dev/zero | dd > /dev/null
2+0 records in
2+0 records out
1024 bytes (1 KB, 1024 B) copied, 0.0 s, 1.0 MB/s
$ head -c 1024 /dev/zero | dd > /dev/null
2+0 records in
2+0 records out
1024 bytes (1.0 kB, 1.0 KiB) copied, 0.0 s, 1.0 MB/s
For comparison, GNU dd produces the following:
$ head -c 1024 /dev/zero | dd > /dev/null
2+0 records in
2+0 records out
1024 bytes (1.0 kB, 1.0 KiB) copied, 0.000332864 s, 3.1 MB/s
=> dd: correct rendering of SI and IEC byte counts

src/uu/cp/src/platform/linux.rs
When copying the contents of a named pipe (also known as a FIFO) via
cp --preserve=ownership --copy-contents fifo fifo-copy
limit the permissions of the destination file while the contents are being copied, and then restore the permissions to match those of the source FIFO when all contents have been copied successfully.
This should cause the GNU test suite file `tests/cp/file-perm-race.sh` to pass.
=> cp: restrict permissions when copying FIFO

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
Allow `cp` to link files that exist. For example,
$ touch src dest
$ cp -f --link src dest
Before this commit, an error was raised.
This should fix GNU test suite file `tests/cp/link.sh`.
=> cp: force link between two files that exist

src/uu/cp/src/copydir.rs, src/uu/cp/src/cp.rs
Improve readability of the `preserve_hardlinks()` helper function by reducing levels of nesting in the body of the function and making it return a Boolean rather than mutating a Boolean argument.
=> cp: improve readability of preserve_hardlinks()

.github/workflows/CICD.yml, GNUmakefile
Results:
`Toybox tests summary = TOTAL: 799 / PASS: 751 / FAIL: 5 / SKIP: 43`
=> Run the toybox testsuite

src/uu/dd/src/progress.rs
Correct the progress report written by `dd` if exactly one byte is written so that it says "1 byte" instead of "1 bytes".
=> dd: correct progress line if 1 byte written

src/uu/cp/src/copydir.rs, src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
This pull request corrects the behavior of `cp --parents --verbose` when the source path is a file and when the source path is a directory so that it prints the copied ancestor directories. For example,
$ mkdir -p a/b d
$ touch a/b/c
$ cp --verbose --parents a/b/c d
a -> d/a
a/b -> d/a/b
'a/b/c' -> 'd/a/b/c'
And
$ mkdir -p a/b/c d
$ cp -r --verbose --parents a/b/c d
a -> d/a
a/b -> d/a/b
'a/b/c' -> 'd/a/b/c'
Fixes #3332.
=> cp: correct --verbose --parents output for both files and directories

src/uu/dircolors/src/dircolors.rs, src/uu/hashsum/src/hashsum.rs, src/uu/shred/src/shred.rs, src/uucore/src/lib/features/fs.rs, src/uucore/src/lib/mods/quoting_style.rs
This PR fixes "wildcard matches only a single variant and will also match any future added variants" warnings from the [match_wildcard_for_single_variant](https://rust-lang.github.io/rust-clippy/master/index.html#match_wildcard_for_single_variants) lint when using `clippy::pedantic`.
=> chore: fix wildcards that match single variant

build.rs
This PR removes two comments which seem to be leftovers from some debugging.
=> build.rs: remove two comments

Cargo.lock, src/uu/tail/Cargo.toml, src/uu/tail/src/args.rs, src/uu/tail/src/chunks.rs, src/uu/tail/src/follow/files.rs, src/uu/tail/src/follow/mod.rs, src/uu/tail/src/follow/watch.rs, src/uu/tail/src/paths.rs, src/uu/tail/src/platform/mod.rs, src/uu/tail/src/platform/unix.rs, src/uu/tail/src/tail.rs, src/uu/tail/src/text.rs, tests/by-util/test_tail.rs
Refactor
* printing of warnings because of problematic configuration by the user on the command line
* handling of early exits. 
This pr also adds the missing warning because of `--follow` being ineffective under some special circumstances.
The warnings and early exits are organized in dedidacted methods within the `Settings` struct providing:
* Clearer, less complex control flow and overall code structure
* `args::Settings::from` has no side effects anymore and the methods sole purpose is parsing and storing the initial configuration provided by the user
* It's simpler now to produce the warnings in the same order as gnu's tail does
* Early exits are organized in a more prominent place in the main module `tail`
* Fixes an issue with a warning which was printed multiple times instead of …
=> `tail`: Refactor handling of warnings and early exits

build.rs, src/bin/coreutils.rs, tests/common/macros.rs, tests/common/util.rs
Found with:
` cargo clippy  --features unix --allow-dirty --fix -- -W clippy::pedantic`
Much more are found
=> fix some clippy warnings

src/uu/cksum/src/cksum.rs, src/uu/csplit/src/csplit.rs, src/uu/dd/src/dd.rs, src/uu/dircolors/src/dircolors.rs, src/uu/du/src/du.rs, src/uu/factor/build.rs, src/uu/fold/src/fold.rs, src/uu/ln/src/ln.rs, src/uu/ls/src/ls.rs, src/uu/mv/src/mv.rs, src/uu/pinky/src/pinky.rs, src/uu/ptx/src/ptx.rs, src/uu/pwd/src/pwd.rs, src/uu/realpath/src/realpath.rs, src/uu/rm/src/rm.rs, src/uu/split/src/split.rs, src/uu/sync/src/sync.rs, src/uu/uptime/src/uptime.rs, src/uu/who/src/who.rs, src/uu/whoami/src/whoami.rs, src/uucore/src/lib/features/fs.rs, src/uucore/src/lib/features/fsext.rs, src/uucore/src/lib/features/mode.rs, src/uucore/src/lib/features/tokenize/num_format/num_format.rs, src/uucore/src/lib/features/tokenize/sub.rs, src/uucore/src/lib/features/tokenize/unescaped_text.rs, src/uucore/src/lib/features/utmpx.rs, src/uucore/src/lib/macros.rs
This'll fix the newly arrived `clippy` warnings and a `doc` warning.
These clippy warnings were mostly related to a needless conversion like `u64 -> u64` on some platforms. I removed these generic conversions, but the conversions could then only be applied specific to the `target_os`, `target_env`, etc. I've applied the `#[cfg(...)]` like they were reported from the ci runs, but there are a systems involved I'm not familiar with, so please double check these newly added `#[cfg(...)]` attributes.
Some of the conversion were realized with a `as TYPE` although the conversions were not safe like `i64` to `u64`, so I've changed them to use `try_into().unwrap()`.
=> cargo: Fix cargo clippy doc warnings

.vscode/cspell.dictionaries/workspace.wordlist.txt, Cargo.lock, Cargo.toml, tests/by-util/test_factor.rs, tests/by-util/test_sort.rs, tests/common/util.rs
This pr adds a builder method `UCommand::timeout` to set a timeout as `Duration` which is applied in `UChild::wait_with_output` and all dependent methods like `UCommand:run`, `UChild::wait` etc. The default timeout in `UChild::kill` can also be overwritten that way.
With `rstest` comes a `timeout` macro which can be used in test functions to complete the needs for setting timeouts in tests. 
Closes #4226
=> `tests/common/util`: Add possibility to set timeout for UCommand and UChild. Add `rstest` with timeout macro to dev dependencies

src/uu/csplit/src/split_name.rs, src/uu/dd/src/parseargs.rs, src/uu/numfmt/src/options.rs, src/uu/od/src/parse_formats.rs, src/uu/od/src/parse_nrofbytes.rs, src/uu/sort/src/sort.rs, src/uu/tee/src/tee.rs, src/uucore/src/lib/features/tokenize/num_format/formatters/float_common.rs
This PR fixes some "unnested or-patterns" warnings from the [unnested_or_patterns](https://rust-lang.github.io/rust-clippy/master/index.html#unnested_or_patterns) lint when using `clippy::pedantic`. I fixed only the warnings where I think the result is an improvement in readability.
=> clippy: fix some "unnested or-patterns" warnings

src/uu/date/src/date.rs, tests/by-util/test_date.rs
Currently if you  pass `date` an invalid format string you will get a panic inside the chrony library. This adds a check to catch this case and return an error message instead.
Once chrony handles this case itself this code can be removed.
=> date: Catch panic from invalid format string

src/uu/dd/src/parseargs.rs, src/uu/sort/src/sort.rs, src/uucore/src/lib/parser/parse_size.rs
#4162
add `allow_list`, `default_unit`, `b_byte_count` options to `parse_size::Parser` to support `parse_byte_count()` in `sort.rs`
=> uucore: add options to parse_size::Parser

src/uu/expr/src/expr.rs, src/uu/expr/src/syntax_tree.rs, tests/by-util/test_expr.rs
I ran into several bugs in `expr` when using it to test some other coreutils implementations (eg, [vlang coreutils](https://github.com/vlang/coreutils)). Here's a commit set that implements tests against those errors and fixes for them.
I've left one test in, but disabled, for a secondary [bug in the oniguruma](https://github.com/kkos/oniguruma/issues/279) regex implementation. I'll re-address when that bug is fixed.
=> Multiple fixes and tests added for `expr`

tests/by-util/test_rm.rs
Closes #4246
As discussed in the linked issue, the behaviour is currently correct, but not tested, so we just add a test to prevent later regression.
=> rm: add test for #4246

docs/src/extensions.md, src/uu/cut/src/cut.rs, src/uu/cut/src/whitespace_searcher.rs, tests/by-util/test_cut.rs, tests/fixtures/cut/whitespace_delimited.expected
**TLDR**: "-w" flag in cut is an extension option implemented in [FreeBSD](https://www.freebsd.org/cgi/man.cgi?cut). This option proves to be useful when cutting fields separated by one or more whitespaces. GNU coreutils does not currently implement this option. This PR implements -w option and adds test cases. The performance difference compared to FreeBSD's cut implementation is about 9x.
**Example use case**: "ls" or "ps" returns columns separated by multiple inconsistent whitespaces. We can use -w option to select columns, e.g. "ps | cut -w -f1" to print only pids.
**Implementation**: For best performance, I created a new function (cut_fields_whitespace) dedicated for -w option. Performance of "cut -f" before and after this PR is essentially the same, as show below:
Before
```
$ …
```
=> cut: add whitespace option for separating fields

tests/by-util/test_cp.rs, tests/by-util/test_dd.rs, tests/by-util/test_expr.rs, tests/by-util/test_mknod.rs, tests/by-util/test_sort.rs, tests/by-util/test_test.rs, tests/by-util/test_timeout.rs, tests/common/util.rs
This gets us better error messages that show the location of where the function was called in the assertions. I also found that `status_code` and `code_is` are basically the same function, so I removed `status_code`.
Related to (but does not close) https://github.com/uutils/coreutils/issues/4250
=> Put `#[track_caller]` on assertion functions in test utils

.github/workflows/CICD.yml, util/android-commands.sh
This pr will enable printing the backtrace in the CI for failing tests when run with `cargo test`
Closes #4250
=> `ci/tests`: Run cargo test with RUST_BACKTRACE=1

src/uu/pr/src/pr.rs
This PR removes a code line that was commented out in relation to a `FIXME` (https://github.com/uutils/coreutils/commit/bc2b385744e045d5f5499e0c8c4c44be0ae649d6#diff-25a81e8809feab14c3f702e683fc8a77ab5a724ecd40842cd79f6ca4c6c8d31fR448). The `FIXME` has been fixed in the meantime, but the commented out line remained.
=> pr: remove commented out code line

src/uu/csplit/src/split_name.rs
This PR is similar to #4263 and #4264: it renames a variable so that many `width = n_digits` can be removed from format strings.
=> csplit: rename var to simplify format strings

src/uu/pr/src/pr.rs, src/uu/seq/src/seq.rs
This PR is similar to #4263 and removes unnecessary `x = x` in format strings.
=> pr,seq: simplify format strings

Cargo.toml
This reorganizes build features, re-ordering with "regular" features toward the top (more discoverable).
Also, added feature "feat_require_hostid" is revised into form ("feat_require_unix_hosted"), location, and documentation matching other internal/plumbing features.
This should be just a refactor not affecting external uses.
=> build: feature cleanup

src/uu/sum/src/sum.rs, src/uu/unexpand/src/unexpand.rs
This PR changes the output of the about string from
```
Checksum and count the blocks in a file.
With no FILE, or when  FILE is -, read standard input.
```
to
```
Checksum and count the blocks in a file.
```
=> sum, unexpand: fix output of about string

tests/by-util/test_rm.rs, tests/by-util/test_tail.rs, tests/by-util/test_tee.rs, tests/common/util.rs
This pr sets the `stdin` of a spawned child process in `UCommand` to `Stdio::null` instead of `Stdio::piped` per default.
Closes #4257
=> `tests/util`: Use `Stdio::null` as default stdin for child processes

src/uu/cat/src/cat.rs, src/uu/cksum/src/cksum.rs, src/uu/cut/src/cut.rs, src/uu/echo/src/echo.rs, src/uu/fold/src/fold.rs, src/uu/mkfifo/src/mkfifo.rs, src/uu/nl/src/nl.rs, src/uu/ptx/src/ptx.rs, src/uu/shuf/src/shuf.rs, src/uu/stty/src/stty.rs, src/uu/sum/src/sum.rs, src/uu/tac/src/tac.rs, src/uu/unexpand/src/unexpand.rs
This PR removes `NAME` constants some utils define to set the program's name used by clap. This seems unnecessary because the name is already set by passing the value of `uucore::util_name()` to clap.
=> remove NAME constants

src/uu/mv/src/mv.rs
This PR removes an unnecessary `!` because it is more consistent to have `if target.is_dir()` and `if source.is_dir()` instead of `if target.is_dir()` and `if !source.is_dir()`.
=> mv: remove unnecessary "!"

src/uu/sleep/src/sleep.rs, tests/by-util/test_sleep.rs
This changes argument parsing and errors to better match GNU practices.
Associated tests are added and updated.
=> Fix `sleep` argument parsing and errors

src/uu/join/src/join.rs
This PR removes the `NAME` constant and uses `uucore::util_name()` when setting the program's name used by clap (I overlooked this case when I created #4277)
=> join: remove NAME constant

src/uu/cp/src/cp.rs
This PR changes the output of `--version` from
```
cp 0.0.16
```
to 
```
cp 0.0.16
```
=> cp: remove empty line from version output

src/uu/dd/src/dd.rs, src/uu/df/src/df.rs, src/uu/head/src/head.rs, src/uu/join/src/join.rs, src/uu/ptx/src/ptx.rs, src/uu/sort/src/sort.rs, src/uu/sort/src/tmp_dir.rs, src/uucore/src/lib/features/tokenize/num_format/formatters/float_common.rs, src/uucore/src/lib/features/tokenize/num_format/formatters/intf.rs, src/uucore/src/lib/features/tokenize/num_format/num_format.rs
This PR fixes warnings caused by the `default_trait_access` lint (https://rust-lang.github.io/rust-clippy/master/index.html#default_trait_access) when running `clippy::pedantic`.
=> clippy: use type name instead of Default::default

src/uu/cp/src/copydir.rs, src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
In GNU cp, there's a lot of special handling of errors based on using `-a`, `-p`, `--preserve=all`, `--preserve=xattr,context` etc. which is not handled properly at the moment. In this PR, an analogous behavior to that of `require_preserve_xattr`, `require_preserve_context`, and `require_preserve` flags in GNU cp code is implemented.
Somethings left todo are testing xattr permission denied case (outside of Android test), and also context permission denied case. One idea is making a simple user-space fuse FS with advanced xattr modification permission controls. This will be implemented in a separate PR here - https://github.com/uutils/coreutils/pull/4100.
Original PR: https://github.com/uutils/coreutils/pull/4095 (started implemeting testfs there, but it's a bit out of scope, so, I'm …
=> cp: require preserve only certain attributes

src/uu/nice/src/nice.rs, tests/by-util/test_nice.rs
This introduces an argument preprocessing step for the nice tool in order to support the legacy nice adjustment syntax (`nice -1 foo`, `nice --1 foo`, `nice -+1 foo` and so forth).
This is a preprocessing step because the interaction between these arguments and the existing `nice -n -1` syntax becomes context dependent, in a way that is currently difficult to capture through clap.
With this patch, the coreutils replacement for nice passes the GNU test suite.
This addresses #2251.
( closes #2251 )
=> Support legacy argument syntax for nice

src/uu/od/src/prn_float.rs
This PR removes unnecessary `width = width` from format strings.
=> od: remove "width = width" from format strings

src/uucore/src/lib/features/fs.rs, src/uucore/src/lib/features/fsext.rs
I ran the builds locally with `cross` without the errors occurring in the failed builds here https://buildd.debian.org/status/logs.php?pkg=rust-coreutils&ver=0.0.17-1
The commands I used were:
```
$ cross build --target s390x-unknown-linux-gnu --features unix
$ cross build --target riscv64gc-unknown-linux-gnu --features unix
```
Closes #4298
=> `uucore`: Fix #4298: Fails to build on s390x (and riscv64)

tests/by-util/test_tail.rs
`test_follow_with_pid` fails intermittently on freebsd
Closes #4306
=> `tests/tail`: Disable `test_follow_with_pid` on freebsd

src/uu/expand/src/expand.rs, tests/by-util/test_expand.rs
This PR fixes a bug when using the plus specifier in the expand tool.
In the existing solution, when using the plus specifier, `next_tabstop` always returns the current step size - 1, which doesn't account for the potentially varying size of columns.
This implementation will instead calculate the number of steps required find the first tabstop after the current column, which should work for longer column values.
It also adds a check that  disengages the plus specifier if only one tabstop is specified, as the plus specifier requires at least one fixed tabstop to work.
By fixing these two issues, expand.pl appears to pass without failures on my machine.
=> expand: improve plus specifier handling

util/gnu-json-result.py
Closes #4276
Use regex to extract the test status from the log. The origin method will fail to extract status from the following:
```
00101201230123401234501234560123456701234567801234567890123456789001012012301234012345012345601234567012345678012345678901234567890010120123012340123450123456012345670123456780123456789012345678900101201230123401234501234560123456701234567801234567890123456789001012012301234012345012345601234567012345678012345678901234567890010120123012340123450123456012345670123456780123456789012345678900101201230123401234501234560123456701234567801234567890123456789001012012301234012345012345601234567012345678012345678901234567890010120123012340123450123456012345670123456780123456789012345678900101201230123401234501234560123456701234567801234567890123456789PASS …
```
=> docs: fix invalid test status in gnu-full-result

src/uu/ptx/src/ptx.rs
This PR fixes a warning from the [unnecessary_join](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_join) lint and replaces `.collect::<Vec<String>>().join("")` with `.collect::<String>()`
=> ptx: fix warning from unnecessary_join lint

src/uu/ln/src/ln.rs
This PR adds some missing `\n\` to the help text.
=> ln: fix format of help text

tests/by-util/test_comm.rs
This PR enables two tests that ensure some missing arguments cause a (clap) error.
=> comm: enable "no_arguments" & "one_argument" tests

Cargo.lock, Cargo.toml, deny.toml, src/uu/cat/Cargo.toml, src/uu/env/Cargo.toml, src/uu/hashsum/Cargo.toml, src/uu/kill/Cargo.toml, src/uu/more/Cargo.toml, src/uu/nice/Cargo.toml, src/uu/stty/Cargo.toml, src/uu/sync/Cargo.toml, src/uu/tail/Cargo.toml, src/uu/timeout/Cargo.toml, src/uu/tty/Cargo.toml, src/uu/wc/Cargo.toml, src/uu/yes/Cargo.toml, src/uucore/Cargo.toml
Updated some dependencies to remove some duplicate transitive dependencies, so we can remove this from `deny.toml`:
```toml
skip = [
...
{ name = "terminal_size", version = "=0.1.17" },
{ name = "memoffset", version = "=0.6.5"},
...
]
```
(I've been reading the [comments at phoronix](https://www.phoronix.com/forums/forum/phoronix/latest-phoronix-articles/1371662-the-rust-implementation-of-gnu-coreutils-is-becoming-remarkably-robust/page8#post1371870) 😄)
=> Fix some double deps

Cargo.lock, deny.toml, src/uu/rm/Cargo.toml, src/uu/rm/src/rm.rs
=> rm: Remove remove_dir_all dependency

src/uu/cp/src/cp.rs
It is implemented, so update the --help text to reflect that
=> Stop saying --sparse is not implemented for cp

docs/src/extensions.md
Found this GNU extension in the code while trying to figure out where the `hashbrown` dependency comes from (it comes from `rust-ini` which is used as a parser for `.env` files).
=> docs: document env -f/--file in GNU extensions

tests/common/util.rs
All tests failed when running the tests in a windows virtualbox with the uutils repo located in a shared folder. The `AtPath::root_dir_resolved` method stripped away the necessary `\\?\` prefix and the `coreutils` test executable couldn't be executed.
Using `env!(CARGO_BIN_EXE_coreutils)` is simpler, platform independent and more reliable in my opinion and I was able to run the test suite in a virtualbox shared folder. Note the `\\?\` prefix would also be necessary if running the tests on a network drive. See also here for a description of the file naming model on windows: https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file
However, I'm not sure if the change that would be introduced by this pr has other implications I'm not aware of.
=> tests/util: Fix path resolution of test executable

Cargo.lock, src/uu/nproc/Cargo.toml, src/uu/nproc/src/nproc.rs
=> nproc: replace num_cpus crate with thread::available_parallelism

src/uu/tr/src/operation.rs, tests/by-util/test_tr.rs
=> tr: Remove the extra newline in stderr

src/uu/chmod/src/chmod.rs, src/uu/dirname/src/dirname.rs, src/uu/mkdir/src/mkdir.rs, src/uu/rm/src/rm.rs, src/uu/stat/src/stat.rs, src/uu/stat/stat.md, src/uu/tr/src/tr.rs, src/uu/truncate/src/truncate.rs, src/uu/uniq/src/uniq.rs
This PR replaces most `get_long_usage()` functions with a constant. In one case, with `stat`, I moved the help text to a markdown file.
=> Replace get_long_usage fns with const

src/uu/cp/cp.md, src/uu/cp/src/cp.rs
#4368 
After this PR,  `cp -h` gives the following output.
```shell
$ ./target/debug/coreutils cp -h
Copy SOURCE to DEST, or multiple SOURCE(s) to DIRECTORY.
Usage: ./target/debug/coreutils cp [OPTION]... [-T] SOURCE DEST
./target/debug/coreutils cp [OPTION]... SOURCE... DIRECTORY
./target/debug/coreutils cp [OPTION]... -t DIRECTORY SOURCE...
Arguments:
[paths]...  
Options:
-t, --target-directory <target-directory>  copy all SOURCE arguments into target-directory
-T, --no-target-directory                  Treat DEST as a regular file and not a directory
-i, --interactive                          ask before overwriting files
-l, --link                                 hard-link files instead of copying
-n, --no-clobber                           don't overwrite a file that already exists …
```
=> cp: move help strings to markdown file

src/uu/cat/cat.md, src/uu/cat/src/cat.rs
#4368 
Now `cat -h` shows the following.
```shell
$ ./target/debug/coreutils cat -h
Concatenate FILE(s), or standard input, to standard output
Usage: ./target/debug/coreutils cat [OPTION]... [FILE]...
Options:
-A, --show-all          equivalent to -vET
-b, --number-nonblank   number nonempty output lines, overrides -n
-e                      equivalent to -vE
-E, --show-ends         display $ at end of each line
-n, --number            number all output lines
-s, --squeeze-blank     suppress repeated empty output lines
-t, --t                 equivalent to -vT
-T, --show-tabs         display TAB characters at ^I
-v, --show-nonprinting  use ^ and M- notation, except for LF (\n) and TAB (\t)
-h, --help              Print help information …
```
=> cat: move help strings to markdown file

src/uu/comm/src/comm.rs, tests/by-util/test_comm.rs, tests/fixtures/comm/ab_total_delimiter_word.expected
This PR makes the `total` line use the delimiter specified with `--output-delimiter` and refactors the delimiter handling.
=> comm: use delimiter on "total" line

Cargo.lock, Cargo.toml, src/uu/tail/Cargo.toml, src/uu/tail/src/args.rs, tests/by-util/test_tail.rs
Like discussed, I've extracted this from the refactoring pr of tail, which fixes the parsing of the sleep interval.
The main intend of this pr is to match the behavior of gnu's tail and properly parse a string in f64 format to a Duration.
Short summary:
* The sleep interval is a `f64` instead of a `f32`
* `Duration::from_secs_f64` panics and `Duration::try_from_secs_f64` is not stable, so we need a separate function to accomplish the conversion from `f64` to a `Duration`.
=> `tail`: fix argument parsing of sleep interval

tests/by-util/test_date.rs, tests/by-util/test_dir.rs, tests/by-util/test_ls.rs, tests/by-util/test_realpath.rs, tests/by-util/test_vdir.rs, tests/common/util.rs
Like discussed in #4261, this pr removes the trimming of the `stdout` in `CmdResult::stdout_matches` and `CmdResult::stdout_does_not_match`. 
The tests using these methdos are adjusted to match the trailing newline instead of ignoring it.
=> `tests/util`: Don't trim output in `CmdResult::stdout_matches` and `stdout_does_not_match`

Cargo.lock, src/uu/tail/Cargo.toml
This pr removes the unused features `ringbuffer` and `lines` of the `uucore` dependency. The `nix` dependency wasn't in use either, so it's removed, too.
=> `tail`: Cargo.toml: Remove unneeded features of uucore and the nix dependency

src/uu/chmod/src/chmod.rs, tests/by-util/test_chmod.rs
Fixes #4355. Basically now it allows to set permissions for files present, and ignoring the missing files by just printing a "warning" that the particular file could not be found.
=> chmod: change permissions for files present even when there is a missing file

src/uu/install/src/install.rs, tests/by-util/test_install.rs
* Correct bug that set the last directory to the mode the file should have been set to.
* Add unit test to verify correct functionality.
* Fixes #4360
=> install: fix bad target directory permissions

src/uu/base32/base32.md, src/uu/base32/src/base32.rs, src/uu/base64/base64.md, src/uu/base64/src/base64.rs, src/uu/cat/cat.md, src/uu/cat/src/cat.rs, src/uu/cp/cp.md, src/uu/cp/src/cp.rs, src/uu/dd/dd.md, src/uu/dd/src/dd.rs, src/uu/expr/expr.md, src/uu/expr/src/expr.rs, src/uu/numfmt/numfmt.md, src/uu/numfmt/src/numfmt.rs, src/uu/stat/src/stat.rs, src/uu/stat/stat.md, src/uucore_procs/src/lib.rs
This PR adds the implementation for the new help structure discussed in https://github.com/uutils/coreutils/issues/4368, which no longer uses `Usage` and `About` headers:
````
```
numfmt [OPTION]... [NUMBER]...
```
Convert numbers from/to human-readable strings
````
The PR 
- adds a new `help_about` macro to get the about text from the help file
- modifies the existing `help_usage` macro accordingly
- updates all help files to the new structure
- replaces the usage of `help_section!("about", "example.md")` with `help_about!("example.md")`
=> uucore_procs: extract "about" and "usage" info from new help structure

src/uu/yes/src/yes.rs, src/uu/yes/yes.md
#4368
`yes -h` outputs the following.
```shell
$ ./target/debug/coreutils yes -h
Repeatedly display a line with STRING (or 'y')
Usage: ./target/debug/coreutils yes [STRING]...
Arguments:
[STRING]...  
Options:
-h, --help  Print help information
```
=> yes: move help strings to markdown file

src/uu/tac/src/tac.rs, src/uu/tac/tac.md
#4368 
`tac -h` outputs the following.
```shell
$ ./target/debug/coreutils tac -h
Write each file to standard output, last line first.
Usage: ./target/debug/coreutils tac [OPTION]... [FILE]...
Options:
-b, --before              attach the separator before instead of after
-r, --regex               interpret the sequence as a regular expression
-s, --separator <STRING>  use STRING as the separator instead of newline
-h, --help                Print help information
-V, --version             Print version information
```
=> tac: move help strings to markdown file

src/uu/kill/kill.md, src/uu/kill/src/kill.rs
#4368 
`kill -h` shows the following.
```shell
$ ./target/debug/coreutils kill -h   
Send signal to processes or list information about signals.
Usage: ./target/debug/coreutils kill [OPTIONS]... PID...
Options:
-l, --list             Lists signals
-t, --table            Lists table of signals
-s, --signal <signal>  Sends given signal instead of SIGTERM
-h, --help             Print help information
-V, --version          Print version information
```
=> kill: move help strings to markdown file

src/uu/chmod/src/chmod.rs, tests/by-util/test_chmod.rs
Closes #4381.  Shows verbose output only when `--verbose` flag is used instead
=> chmod: supress verbose output when not verbose

src/uu/du/du.md, src/uu/du/src/du.rs
#4368
`du --help` outputs the following.
```shell
$ ./target/debug/coreutils du --help
Estimate file space usage
Usage: ./target/debug/coreutils du [OPTION]... [FILE]...
./target/debug/coreutils du [OPTION]... --files0-from=F
Options:
--help                 Print help information.
-a, --all                  write counts for all files, not just directories
--apparent-size        print apparent sizes, rather than disk usage although the apparent size is usually smaller, it may be larger due to holes in
('sparse') files, internal fragmentation, indirect blocks, and the like
-B, --block-size <SIZE>    scale sizes by SIZE before printing them. E.g., '-BM' prints sizes in units of 1,048,576 bytes. See SIZE format below.
-b, --bytes                equivalent to '--apparent-size --block-size=1' …
```
=> du: move help strings to markdown file

Cargo.lock, Cargo.toml, deny.toml, src/uu/cat/Cargo.toml, src/uu/cat/src/cat.rs, src/uu/cut/Cargo.toml, src/uu/cut/src/cut.rs, src/uu/ls/Cargo.toml, src/uu/ls/src/ls.rs, src/uu/more/Cargo.toml, src/uu/more/src/more.rs, src/uu/nohup/Cargo.toml, src/uu/nohup/src/nohup.rs, src/uu/tail/Cargo.toml, src/uu/tail/src/args.rs, src/uu/tty/Cargo.toml, src/uu/tty/src/tty.rs, tests/by-util/test_more.rs
Closes #4377
I did this changes and run the whole test suits, it seems that anything broke.
I would also like to point out that `is_terminal` / `IsTerminal` is currently on rust nigthly [#98070](https://github.com/rust-lang/rust/issues/98070) so maybe in the future would be great to change (again).
=> Migrate from `atty` to `is-terminal`

Cargo.lock, Cargo.toml, tests/by-util/test_cat.rs, tests/by-util/test_chmod.rs, tests/by-util/test_chown.rs, tests/by-util/test_cp.rs, tests/by-util/test_env.rs, tests/by-util/test_mktemp.rs, tests/by-util/test_nproc.rs, tests/by-util/test_printenv.rs, tests/by-util/test_pwd.rs, tests/by-util/test_sort.rs, tests/by-util/test_test.rs, tests/by-util/test_uptime.rs, tests/by-util/test_users.rs, tests/common/util.rs
Like discussed in #4261, this pr restructures `UCommand` to run a command in a shell context (`sh -c` on unix systems and `cmd /C` on windows systems) per default.
A little bit of a refactoring is needed, to not break the other functions in `UCommand` like `arg`, `args` etc. and store the arguments and environment variables in `UCommand` itself instead of delegating them to the underlying `std::process::Command`.
Other fixes/changes in `UCommand`:
* Remove the `raw` field and build the `std::process::Command` in `run_no_wait` or more specifically `UCommand::build` instead.
* Use `OsString`s and `PathBufs` for paths in `UCommand` instead of converting to `str` or `String` back and forth.
* Remove the `comm_string` field and implement `Display` for `UCommand`.
* Add a new public method …
=> `tests/util`: Small Refactor/Fixes of `UCommand` and add method to run a `UCommand` in a shell platform independently

src/uu/mkdir/mkdir.md, src/uu/mkdir/src/mkdir.rs
`mkdir -h` outputs the following.
```
$ ./target/debug/coreutils mkdir -h
Create the given DIRECTORY(ies) if they do not exist
Usage:  ./target/debug/coreutils mkdir [OPTION]... [USER]
Arguments:
[dirs]...  
Options:
-m, --mode <mode>  set file mode (not implemented on windows)
-p, --parents      make parent directories as needed
-v, --verbose      print a message for each printed directory
-h, --help         Print help information
-V, --version      Print version information
Each MODE is of the form '[ugoa]*([-+=]([rwxXst]*|[ugo]))+|[-+=]?[0-7]+'.
```
=> mkdir: move help strings to markdown file

src/uu/sleep/sleep.md, src/uu/sleep/src/sleep.rs
#4368 
`sleep -h` outputs the following.
```
$ ./target/debug/coreutils sleep -h
Pause for NUMBER seconds.
Usage: ./target/debug/coreutils sleep NUMBER[SUFFIX]...
./target/debug/coreutils sleep OPTION
Arguments:
[NUMBER]...  pause for NUMBER seconds
Options:
Pause for NUMBER seconds.  SUFFIX may be 's' for seconds (the default),
'm' for minutes, 'h' for hours or 'd' for days.  Unlike most implementations
that require NUMBER be an integer, here NUMBER may be an arbitrary floating
point number.  Given two or more arguments, pause for the amount of time
specified by the sum of their values.
```
=> sleep: move help strings to markdown file

src/uu/dd/src/dd.rs, tests/by-util/test_dd.rs
First, this pull request creates a `Source` enum and simplifies the `Input` struct in `dd`, mirroring pull request #4134 that introduced the `Dest` enum and a simplified `Output` struct. Second, this pull request adds support seeking in FIFOs given as either input or output (or both). For example, `dd seek=1 of=fifo` and `dd skip=1 if=fifo` will now work.
This should cause GNU test suite file `tests/dd/no-allocate.sh` to change from `ERROR` to `FAIL` status.
Fixes #3321.
=> dd: allow skipping and seeking in FIFOs

src/uu/arch/arch.md, src/uu/arch/src/arch.rs, src/uu/numfmt/numfmt.md
This change moves the `about` and `summary` help strings to `arch.md` in the `arch` directory
=> arch: move help strings to a markdown file

src/uu/rm/rm.md, src/uu/rm/src/rm.rs
#4368 
`rm -h` outputs the following.
```
$ ./target/debug/coreutils rm -h
Remove (unlink) the FILE(s)
Usage: ./target/debug/coreutils rm [OPTION]... FILE...
Arguments:
[files]...  
Options:
-f, --force               ignore nonexistent files and arguments, never prompt
-i                        prompt before every removal
-I                        prompt once before removing more than three files, or when removing recursively. Less      
intrusive than -i, while still giving some protection against most mistakes
--interactive <WHEN>  prompt according to WHEN: never, once (-I), or always (-i). Without WHEN, prompts always   
--one-file-system     when removing a hierarchy recursively, skip any directory that is on a file system
different from that of the corresponding command line argument …
```
=> rm: move help strings to markdown file

src/uu/nohup/nohup.md, src/uu/nohup/src/nohup.rs
#4368 
Now `nohup -h` outputs the following.
```shell
$ ./target/debug/coreutils nohup --h   
Run COMMAND ignoring hangup signals.
Usage: ./target/debug/coreutils nohup COMMAND [ARG]...
./target/debug/coreutils nohup FLAG
Options:
If standard input is terminal, it'll be replaced with /dev/null.
If standard output is terminal, it'll be appended to nohup.out instead,
or $HOME/nohup.out, if nohup.out open failed.
If standard error is terminal, it'll be redirected to stdout.
```
=> nohup: move help strings to markdown file

src/uu/rmdir/rmdir.md, src/uu/rmdir/src/rmdir.rs
#4368 
`rmdir -h` outputs the following.
```
$ ./target/debug/coreutils rmdir -h
Remove the DIRECTORY(ies), if they are empty.
Usage: ./target/debug/coreutils rmdir [OPTION]... DIRECTORY...
Arguments:
[dirs]...  
Options:
--ignore-fail-on-non-empty  ignore each failure that is solely because a directory is non-empty
-p, --parents                   remove DIRECTORY and its ancestors; e.g.,
'rmdir -p a/b/c' is similar to rmdir a/b/c a/b a
-v, --verbose                   output a diagnostic for every directory processed
-h, --help                      Print help information
-V, --version                   Print version information
```
=> rmdir: move help strings to markdown file

src/uucore/src/lib/features/utmpx.rs
=> utmpx: arch/os-independent timeval handling

src/uu/install/src/install.rs, tests/by-util/test_install.rs
* Re-factor the copy function `chown` into a function that can be re-used.
* Fix bug where the group overwrote the user.
* Add `chown` compatibility to follow GNU coreutils.
* Reduce two `chown` calls to a single syscall only when needed.
* Fixes #4361
Not sure how to test this though.  Can the CI/CD server change owners?  I assume this will break most test setups.
Manually tested for now.
=> install: add missing directory chown

src/uu/shuf/shuf.md, src/uu/shuf/src/shuf.rs
#4368 
`shuf -h` outputs the following.
```
$ ./target/debug/coreutils shuf -h
Shuffle the input by outputting a random permutation of input lines.
Each output permutation is equally likely.
Usage: ./target/debug/coreutils shuf [OPTION]... [FILE]
./target/debug/coreutils shuf -e [OPTION]... [ARG]...
./target/debug/coreutils shuf -i LO-HI [OPTION]...;
Arguments:
[file]  
Options:
-e, --echo [<ARG>...]       treat each ARG as an input line
-i, --input-range <LO-HI>   treat each number LO through HI as an input line
-n, --head-count <COUNT>    output at most COUNT lines
-o, --output <FILE>         write result to FILE instead of standard output
--random-source <FILE>  get random bytes from FILE
-r, --repeat                output lines can …
```
=> shuf: move help strings to markdown file

src/uu/link/link.md, src/uu/link/src/link.rs
#4368 
`link -h` outputs the following.
```
$ ./target/debug/coreutils link -h
Call the link function to create a link named FILE2 to an existing FILE1.
Usage: ./target/debug/coreutils link FILE1 FILE2
Options:
```
=> link: move help strings to markdown file

src/uu/ln/ln.md, src/uu/ln/src/ln.rs
#4368 
`ln -h` outputs the following.
```
$ ./target/debug/coreutils ln -h
Change file owner and group
Usage: ./target/debug/coreutils ln [OPTION]... [-T] TARGET LINK_NAME
./target/debug/coreutils ln [OPTION]... TARGET
./target/debug/coreutils ln [OPTION]... TARGET... DIRECTORY
./target/debug/coreutils ln [OPTION]... -t DIRECTORY TARGET...
Arguments:
<files>...  
Options:
--backup[=<CONTROL>]            make a backup of each existing destination file
-b                                  like --backup but does not accept an argument
-f, --force                         remove existing destination files
-i, --interactive                   prompt whether to remove existing destination files
-n, --no-dereference                treat LINK_NAME as a normal file if it is a symbolic link to a …
```
=> ln: move help strings to markdown file

src/uu/tee/src/tee.rs, src/uu/tee/tee.md
#4368 
`tee --help` shows the following
```shell
$ ./target/debug/coreutils tee --help
Copy standard input to each FILE, and also to standard output.
Usage: ./target/debug/coreutils tee [OPTION]... [FILE]...
Arguments:
[file]...
Options:
-a, --append
append to the given FILEs, do not overwrite
-i, --ignore-interrupts
ignore interrupt signals (ignored on non-Unix platforms)
-p
set write error behavior (ignored on non-Unix platforms)
--output-error[=<output-error>]
set write error behavior
Possible values:
- warn:        produce warnings for errors writing to any output
- warn-nopipe: produce warnings for errors that are not pipe errors (ignored on non-unix platforms)
- exit:        exit on write errors to any output
- exit-nopipe: exit on write errors to any output that are not pipe errors …
```
=> tee: move help strings to markdown file

src/uu/tail/src/args.rs, src/uu/tail/tail.md
#4368 
`tail -h` outputs the following
```shell
$ ./target/debug/coreutils tail -h
Print the last 10 lines of each FILE to standard output.
With more than one FILE, precede each with a header giving the file name.
Mandatory arguments to long flags are mandatory for short flags too.
Usage: ./target/debug/coreutils tail [FLAG]... [FILE]...
Arguments:
[files]...  
Options:
-c, --bytes <bytes>            Number of bytes to print
-f, --follow[=<follow>]        Print the file as it grows [default: descriptor] [possible values: descriptor, name]
-n, --lines <lines>            Number of lines to print
--pid <PID>                With -f, terminate after process ID, PID dies
-q, --quiet                    Never output headers giving file names …
```
=> tail: move help strings to markdown file

src/uu/chmod/src/chmod.rs, tests/by-util/test_chmod.rs
Closes #4409.  Based on feedback from PR #4402
=> chmod: allow verbose and quiet flags to be used more than once

src/uu/dd/src/dd.rs
Move the `dd_out()` function out of the `impl Output` and up to the
module level, renaming it to `dd_copy()`. This change aligns it with
the pattern set by `std::io::copy()`, which similarly takes an input
reader and an output writer.
This does not change the behavior of `dd`, just the code organization
to make it more closely match the idioms in the Rust standard library.
=> dd: move dd_out() function up to module level

src/uu/realpath/realpath.md, src/uu/realpath/src/realpath.rs
#4368 
`mkdir -h` outputs the following.
```
$ ./target/debug/coreutils realpath -h
Print the resolved path
Usage: ./target/debug/coreutils realpath [OPTION]... FILE...
Arguments:
<files>...
Options:
-q, --quiet                  Do not print warnings for invalid paths
-s, --strip                  Only strip '.' and '..' components, but don't resolve symbolic links [aliases: no-symlinks]
-z, --zero                   Separate output filenames with \0 rather than newline
-L, --logical                resolve '..' components before symlinks
-P, --physical               resolve symlinks as encountered (default)
-e, --canonicalize-existing  canonicalize by following every symlink in every component of the given name recursively, all components must exist
-m, --canonicalize-missing   canonicalize …
```
=> realpath: move help strings to markdown file

src/uu/fmt/fmt.md, src/uu/fmt/src/fmt.rs
#4368 
`fmt -h` outputs the following.
```
$ ./target/debug/coreutils fmt -h
Reformat paragraphs from input files (or stdin) to stdout.
Usage: ./target/debug/coreutils fmt [OPTION]... [FILE]...
Arguments:
[files]...  
Options:
-c, --crown-margin          First and second line of paragraph may have different indentations, in which case the    
first line's indentation is preserved, and each subsequent line's indentation matches the
second line.
-t, --tagged-paragraph      Like -c, except that the first and second line of a paragraph *must* have different      
indentation or they are treated as separate paragraphs.
-m, --preserve-headers      Attempt to detect and preserve mail headers in the input. Be careful when combining this 
flag with -p.
-s, --split-only            Split lines only, …
```
=> fmt: move help strings to markdown file

docs/src/installation.md
Hi,
just to let you know that uutils-coreutils is available for OpenMandriva to install it.
=> Add OpenMandriva Lx to the documentation

src/uu/stty/src/stty.rs
=> stty: Basic support for --file/-F

src/uu/df/df.md, src/uu/df/src/df.rs
#4368 
`df --help` outputs the following.
```shell
$ ./target/debug/coreutils df --help
Show information about the file system on which each FILE resides,
or all file systems by default.
Usage: ./target/debug/coreutils df [OPTION]... [FILE]...
Arguments:
[paths]...  
Options:
--help                      Print help information.
-a, --all                       include dummy file systems
-B, --block-size <SIZE>         scale sizes by SIZE before printing them; e.g.'-BM' prints sizes in units of 1,048,576 bytes
--total                     produce a grand total
-h, --human-readable            print sizes in human readable format (e.g., 1K 234M 2G)
-H, --si                        likewise, but use powers of 1000 not 1024
-i, --inodes                    list inode information instead of block …
```
=> df: move help strings to markdown file

src/uu/dircolors/dircolors.md, src/uu/dircolors/src/dircolors.rs
#4368 
`dircolors -h ` shows the following.
```shell
$ ./target/debug/coreutils dircolors -h   
Output commands to set the LS_COLORS environment variable.
Usage: ./target/debug/coreutils dircolors [OPTION]... [FILE]
Options:
-b, --sh               output Bourne shell code to set LS_COLORS [aliases: bourne-shell]
-c, --csh              output C shell code to set LS_COLORS [aliases: c-shell]
-p, --print-database   print the byte counts
--print-ls-colors  output fully escaped colors for display
-h, --help             Print help information
-V, --version          Print version information
If FILE is specified, read it to determine which colors to use for which
file types and extensions.  Otherwise, a precompiled database is used.
For details on the format of these files, run 'dircolors …
```
=> dircolors: move help strings to markdown file

src/uu/cp/src/copydir.rs, tests/by-util/test_cp.rs
Hello,
This PR fixes #3886 to handle copying source's directory contents rather than the directory itself. 
Its my first ever Rust PR. Thanks for the helpful responses, and in case something else needs to be added, i can do so np.
Thanks:)
=> cp: modify archive flag to copy dir contents rather than dir

src/uu/uptime/src/uptime.rs
Correctly calculate boot-time on Unix systems that cannot access `/proc/uptime` (eg, macOS).
The number of seconds since boot-time was calculated using the seconds component of OffsetDateTime (eg, boot-time of `2023-02-25 17:46:27` would return `Some(27_i64)`) rather the _total_ number of seconds since the Unix epoch. Meaning `uptime` would believe that the boot-time of the system would always be somewhere between `1970-01-01 00:00:00` and `1970-01-01 00:00:59`.
And I can guarantee that my M1 mac has not been up for 53 years 😉 
Example terminal output: 
```
user@host: uptime
13:23  up 19:37, 2 users, load averages: 1.21 1.82 2.08
user@host: coreutils uptime
13:24:01 up 19414 days, 12:23,  2 users,  load averages: 1.27, 1.83, 2.08
```
This was a very easy bug to miss, since (a) this would …
=> uptime: correctly calculate boot-time

util/size-experiment.py
Inspired by https://github.com/uutils/coreutils/pull/4436, I made a script to analyze the binary size of the multicall binary for different profile options and I thought it might be useful to save for later.
Essentially, it compiles the binary for all combinations of a few flags and then prints the average difference in percentual binary size, so we the effect of the individual flags. I've posted the results here: https://github.com/uutils/coreutils/pull/4436#issuecomment-1445390017
=> utils: create a script to explore binary sizes

src/uu/dirname/dirname.md, src/uu/dirname/src/dirname.rs
#4368 
`dirname -h` outputs the following.
```shell
$ ./target/debug/coreutils dirname -h
Strip last component from file name
Usage: ./target/debug/coreutils dirname [OPTION] NAME...
Options:
-z, --zero     separate output with NUL rather than newline
Output each NAME with its last non-slash component and trailing slashes
removed; if NAME contains no /'s, output '.' (meaning the current directory).
```
=> dirname: move help strings to markdown file

src/uu/comm/comm.md, src/uu/comm/src/comm.rs
#4368 and add an "after help" text.
=> comm: move help strings to markdown file

src/uu/tail/src/args.rs, src/uu/tail/src/parse.rs, src/uu/tail/src/paths.rs, tests/by-util/test_tail.rs
Hi!
This PR targets compatibility to `gnu/tests/misc/tail.pl`.
It's not fully achieved (yet) as some error messages don't fit 1:1 (e.g. a couple of additional `Try 'tail --help' for more information.`). Most of the code is to work around clap, which interprets a couple of arguments as input files.
I imported most of the perl tests to the code base.
Please feel free to respond if I should handle something differently (add tests/comments, split commit, ...) or if this is not needed at all :smile: 
Best regards
bb
=> tail: fix GNU test 'misc/tail'

src/uu/comm/src/comm.rs, tests/by-util/test_comm.rs
This PR allows multiple occurrences of the `-z`/ `--zero-terminated` argument. It makes the test `zdelim-empty` in https://github.com/coreutils/coreutils/blob/master/tests/misc/comm.pl pass.
=> comm: allow multiple occurrence of --zero-terminated

tests/by-util/test_du.rs
Hi,
When running tests locally, I noticed that [`test_du_time`](https://github.com/uutils/coreutils/blob/f6b646e4e5aebb89defc24f8202ee41b947199ad/tests/by-util/test_du.rs#L391) fails because it expects the output to be 1h offset from what the tool produces:
```
$ cargo test --features "du touch" --no-default-features
...
---- test_du::test_du_time stdout ----
run: /Users/guilherme/src/coreutils/target/debug/coreutils touch -a -t 201505150000 date_test
run: /Users/guilherme/src/coreutils/target/debug/coreutils touch -m -t 201606160000 date_test
run: /Users/guilherme/src/coreutils/target/debug/coreutils du --time date_test
thread 'test_du::test_du_time' panicked at 'assertion failed: `(left == right)`
Diff < left / right > :
<0	2016-06-16 01:00	date_test
>0	2016-06-16 00:00	date_test
', …
```
=>  tests/du: run test_du_time with TZ=UTC. 

src/uu/truncate/src/truncate.rs, src/uu/truncate/truncate.md
#4368 
`truncate --help` now outputs the following:
```sh
./target/debug/truncate --help
Shrink or extend the size of each file to the specified size.
Usage: ./target/debug/truncate [OPTION]... [FILE]...
Arguments:
<FILE>...
Options:
-o, --io-blocks          treat SIZE as the number of I/O blocks of the file rather than bytes (NOT IMPLEMENTED)
-c, --no-create          do not create files that do not exist
-r, --reference <RFILE>  base the size of each file on the size of RFILE
-s, --size <SIZE>        set or adjust the size of each file according to SIZE, which is in bytes unless --io-blocks is specified
-h, --help               Print help information
-V, --version            Print version information
SIZE is an integer with an optional prefix and optional unit.
The available units (K, M, …
```
=> truncate: move help strings to markdown file

src/uu/wc/src/wc.rs, src/uu/wc/wc.md
#4368 
`wc --help` now outputs the following:
```
./target/debug/coreutils wc --help
Display newline, word, and byte counts for each FILE, and a total line if
more than one FILE is specified. With no FILE, or when FILE is -, read standard input.
Usage: ./target/debug/coreutils wc [OPTION]... [FILE]...
Arguments:
[files]...
Options:
-c, --bytes            print the byte counts
-m, --chars            print the character counts
--files0-from <F>  read input from the files specified by
NUL-terminated names in file F;
If F is - then read names from standard input
-l, --lines            print the newline counts
-L, --max-line-length  print the length of the longest line
-w, --words            print the word counts
-h, --help             Print help information
-V, --version          Print …
```
=> wc: move help strings to markdown file

src/uu/basename/basename.md, src/uu/basename/src/basename.rs
#4368 
Now `basename -h` shows the following:
```
$ ./target/debug/coreutils basename -h
Print NAME with any leading directory components removed
If specified, also remove a trailing SUFFIX
Usage: ./target/debug/coreutils basename NAME [SUFFIX]
./target/debug/coreutils basename OPTION... NAME...
Options:
-a, --multiple         support multiple arguments and treat each as a NAME
-s, --suffix <SUFFIX>  remove a trailing SUFFIX; implies -a
-z, --zero             end each output line with NUL, not newline
-h, --help             Print help information
-V, --version          Print version information
```
=> basename: move help strings to markdown file

src/uu/chown/chown.md, src/uu/chown/src/chown.rs
#4368 
Now `chown --help` outputs the following.
```shell
$ ./target/debug/coreutils chown --help
Change file owner and group
Usage: ./target/debug/coreutils chown [OPTION]... [OWNER][:[GROUP]] FILE...
./target/debug/coreutils chown [OPTION]... --reference=RFILE FILE...
Arguments:
<OWNER>    
<FILE>...  
Options:
--help                                Print help information.
-c, --changes                             like verbose but report only when a change is made
--dereference                         affect the referent of each symbolic link (this is the default), rather than the symbolic link itself
-h, --no-dereference                      affect symbolic links instead of any referenced file (useful only on systems that can change the ownership of a symlink)
--from …
```
=> chown: move help strings to markdown file

src/uu/ls/ls.md, src/uu/ls/src/ls.rs
#4368 
`vdir` is a wrapper for `ls` and does not have it's own help text. It will output what `ls` has configured.
`ls --help` and `vdir --help` now output the following:
```
target/debug/vdir --help
List directory contents.
Ignore files and directories starting with a '.' by default
Usage: target/debug/vdir [OPTION]... [FILE]...
Arguments:
[paths]...
Options:
--help                                     Print help information.
--format=<format>                          Set the display format.
-C                                             Display the files in columns.
-l, --long                                     Display detailed information.
-x                                             List entries in rows instead of in columns.
-T, --tabsize <COLS>                           Assume tab …
```
=> ls + vdir: move help strings to markdown file

src/uu/pwd/pwd.md, src/uu/pwd/src/pwd.rs
#4368 
`pwd --help` now outputs the following:
```
./target/debug/coreutils pwd --help
Display the full filename of the current working directory.
Usage: ./target/debug/coreutils pwd [OPTION]... [FILE]...
Options:
-L, --logical   use PWD from environment, even if it contains symlinks
-P, --physical  avoid all symlinks
-h, --help      Print help information
-V, --version   Print version information```
=> pwd: move help strings to markdown file

src/uu/chgrp/chgrp.md, src/uu/chgrp/src/chgrp.rs
#4368 
Move help strings from `chgrp` to `chgrp.md` file
=> chgrp: move help strings to markdown file

src/uu/date/date.md, src/uu/date/src/date.rs
Existing tests still pass
```bash
cargo test
...
test result: ok. 2139 passed; 0 failed; 25 ignored; 0 measured; 0 filtered out; finished in 23.66s
```
Manual debug build shows same as `main` branch
```bash
@ coreutils [stevenchu]$ ./target/debug/coreutils date -h
Print or set the system date and time
Usage: ./target/debug/coreutils date [OPTION]... [+FORMAT]...
./target/debug/coreutils date [OPTION]... [MMDDhhmm[[CC]YY][.ss]]
Arguments:
[format]
Options:
-d, --date <STRING>     display time described by STRING, not 'now'
-f, --file <DATEFILE>   like --date; once for each line of DATEFILE
-I, --iso-8601 <FMT>    output date/time in ISO 8601 format.
FMT='date' for date only (the default),
'hours', 'minutes', 'seconds', or 'ns'
for date and …
```
=> For `date`, move help strings to `.md` file

src/uu/chmod/chmod.md, src/uu/chmod/src/chmod.rs
#4368 
Now `chmod -h` shows the following:
```
$ ./target/debug/coreutils chmod -h
Change the mode of each FILE to MODE.
With --reference, change the mode of each FILE to that of RFILE.
Usage: ./target/debug/coreutils chmod [OPTION]... MODE[,MODE]... FILE...
./target/debug/coreutils chmod [OPTION]... OCTAL-MODE FILE...
./target/debug/coreutils chmod [OPTION]... --reference=RFILE FILE...
Arguments:
[MODE]     
[FILE]...  
Options:
-c, --changes            like verbose but report only when a change is made
-f, --quiet              suppress most error messages [aliases: silent]
-v, --verbose            output a diagnostic for every file processed
--no-preserve-root   do not treat '/' specially (the default)
--preserve-root      fail to operate recursively on '/'
-R, --recursive …
```
=> chmod: move help strings to markdown file

src/uu/chcon/src/chcon.rs, src/uu/chgrp/src/chgrp.rs, src/uu/runcon/src/runcon.rs
replace VERSION string with clap::crate_version in chcon, chgrp and runcon utilities
Ref: https://github.com/uutils/coreutils/pull/4461#discussion_r1125632433
=> replace VERSION string with clap::crate_version

src/uu/ptx/ptx.md, src/uu/ptx/src/ptx.rs
#4368 
`ptx -h` outputs the following.
```
$ ./target/debug/coreutils ptx -h
Output a permuted index, including context, of the words in the input files.
Mandatory arguments to long options are mandatory for short options too.
With no FILE, or when FILE is -, read standard input. Default is '-F /'.
Usage: ./target/debug/coreutils ptx [OPTION]... [INPUT]...  
./target/debug/coreutils ptx -G [OPTION]... [INPUT [OUTPUT]]
Options:
-A, --auto-reference            output automatically generated references
-G, --traditional               behave more like System V 'ptx'
-F, --flag-truncation <STRING>  use STRING for flagging line truncations
-M, --macro-name <STRING>       macro name to use instead of 'xx'
-O, --format=roff               generate output as roff directives
-R, --right-side-refs …
```
=> ptx: move help strings to markdown file

docs/src/installation.md
https://cgit.FreeBSD.org/ports/commit/?id=8014b050aa2f5d3e016d48c98865eabb0e6b12fe
=> Freebsd pkg has been remamed to rust-coreutils

src/uu/chroot/chroot.md, src/uu/chroot/src/chroot.rs
#4368 
`chroot -h` outputs the following.
```shell
$ ./target/debug/coreutils chroot -h
Run COMMAND with root directory set to NEWROOT.
Usage: ./target/debug/coreutils chroot [OPTION]... NEWROOT [COMMAND [ARG]...]
Options:
-u, --user <USER>                User (ID or name) to switch before running the program
-g, --group <GROUP>              Group (ID or name) to switch to
-G, --groups <GROUP1,GROUP2...>  Comma-separated list of groups to switch to
--userspec <USER:GROUP>      Colon-separated user and group to switch to. Same as -u USER -g GROUP. Userspec has higher preference than -u and/or -g
--skip-chdir                 Use this option to not change the working directory to / after changing the root directory to newroot, i.e., inside the chroot.
-h, --help                       Print …
```
=> chroot: move help strings to markdown file

src/uu/install/install.md, src/uu/install/src/install.rs
#4368 
`install -h` now outputs the following.
```shell
$ ./target/debug/coreutils install -h
Copy SOURCE to DEST or multiple SOURCE(s) to the existing
DIRECTORY, while setting permission modes and owner/group
Usage: ./target/debug/coreutils install [OPTION]... [FILE]...
Arguments:
[files]...  
Options:
--backup[=<CONTROL>]            make a backup of each existing destination file
-b                                  like --backup but does not accept an argument
-c                                  ignored
-C, --compare                       compare each pair of source and destination files, and in some cases, do not modify the destination at all
-d, --directory                     treat all arguments as directory names. create all components of the specified directories
-D …
```
=> install: move help strings to markdown file

src/uu/echo/echo.md, src/uu/echo/src/echo.rs
#4368
`echo -h` now outputs the following:
```
./target/debug/coreutils echo --help
Display a line of text
Usage: ./target/debug/coreutils echo [OPTIONS]... [STRING]...
Arguments:
[STRING]...
Options:
-n             do not output the trailing newline
-e             enable interpretation of backslash escapes
-E             disable interpretation of backslash escapes (default)
Echo the STRING(s) to standard output.
If -e is in effect, the following sequences are recognized:
\\\\      backslash
\\a      alert (BEL)
\\b      backspace
\\c      produce no further output
\\e      escape
\\f      form feed
\\n      new line
\\r      carriage return
\\t      horizontal tab
\\v      vertical tab
\\0NNN   byte with octal …
```
=> echo: move help strings to markdown file

src/uu/hostname/hostname.md, src/uu/hostname/src/hostname.rs
#4368 
Now `hostname -h` displays the following.
```shell
$ ./target/debug/coreutils hostname -h
Display or set the system's host name.
Usage: ./target/debug/coreutils hostname [OPTION]... [HOSTNAME]
Arguments:
[host]  
Options:
-d, --domain      Display the name of the DNS domain if possible
-i, --ip-address  Display the network address(es) of the host
-f, --fqdn        Display the FQDN (Fully Qualified Domain Name) (default)
-s, --short       Display the short hostname (the portion before the first dot) if possible
-h, --help        Print help information
-V, --version     Print version information
```
=> hostname: move help strings to markdown file

src/uu/csplit/csplit.md, src/uu/csplit/src/csplit.rs
#4368 
`csplit -h` outputs the following.
```shell
$ ./target/debug/coreutils csplit -h
Split a file into sections determined by context lines
Usage: ./target/debug/coreutils csplit [OPTION]... FILE PATTERN...
Options:
-b, --suffix-format <FORMAT>  use sprintf FORMAT instead of %02d
-f, --prefix <PREFIX>         use PREFIX instead of 'xx'
-k, --keep-files              do not remove output files on errors
--suppress-matched        suppress the lines matching PATTERN
-n, --digits <DIGITS>         use specified number of digits instead of 2
-s, --quiet                   do not print counts of output file sizes [aliases: silent]
-z, --elide-empty-files       remove empty output files
-h, --help                    Print help information
-V, --version                 Print version information …
```
=> csplit: move help strings to markdown file

src/uu/env/env.md, src/uu/env/src/env.rs
#4368
After this PR, env -h gives the following output.
~~~
Set each NAME to VALUE in the environment and run COMMAND
Usage: ./target/debug/coreutils env [OPTION]... [-] [NAME=VALUE]... [COMMAND [ARG]...]
Arguments:
[vars]...
Options:
-i, --ignore-environment  start with an empty environment
-C, --chdir <DIR>         change working directory to DIR
-0, --null                end each output line with a 0 byte rather than a newline (only valid when printing the environment)
-f, --file <PATH>         read and set variables from a ".env"-style configuration file (prior to any unset and/or set)
-u, --unset <NAME>        remove variable from the environment
-h, --help                Print help information
-V, --version             Print version information
A mere - implies -i. If no COMMAND, …
=> env: move help strings to a markdown file

src/uu/nl/nl.md, src/uu/nl/src/nl.rs
#4368
After this PR, nl --help gives the following output.
~~~
Number lines of files
Usage: ./target/debug/coreutils nl [OPTION]... [FILE]...
Options:
--help                           Print help information.
-b, --body-numbering <SYNTAX>        use STYLE for numbering body lines
-d, --section-delimiter <CC>         use CC for separating logical pages
-f, --footer-numbering <STYLE>       use STYLE for numbering footer lines
-h, --header-numbering <STYLE>       use STYLE for numbering header lines
-i, --line-increment <NUMBER>        line number increment at each line
-l, --join-blank-lines <NUMBER>      group of NUMBER empty lines counted as one
-n, --number-format <FORMAT>         insert line numbers according to FORMAT
-p, --no-renumber <no-renumber>      do not reset line numbers at …
=> nl: move help strings to a markdown file

Cargo.lock, Cargo.toml
This PR bumps `tempfile` to `3.4.0`. This version no longer has a dependency on `remove_dir_all` and hence resolves https://github.com/advisories/GHSA-mc8h-8q98-g5hr.
=> Bump tempfile from 3.3.0 to 3.4.0

src/uu/shred/src/shred.rs
=> shred: fix `permissions_set_readonly_false` clippy error

Cargo.lock, Cargo.toml
This PR replaces outdated https://github.com/uutils/coreutils/pull/4173.
=> Bump rayon from 1.6.0 to 1.7.0

fuzz/Cargo.toml, src/uucore/src/lib/parser/parse_glob.rs
Fixes #4479 
This PR fixes index out of bounds in `parse_glob::fix_negation`.
=> parser: fix index out of bounds error

Cargo.lock, Cargo.toml, tests/by-util/test_base32.rs, tests/by-util/test_base64.rs, tests/by-util/test_chgrp.rs, tests/by-util/test_chroot.rs, tests/by-util/test_cp.rs, tests/by-util/test_link.rs, tests/by-util/test_mknod.rs, tests/by-util/test_seq.rs, tests/by-util/test_sort.rs, tests/by-util/test_stdbuf.rs, tests/by-util/test_truncate.rs, tests/by-util/test_tsort.rs, tests/by-util/test_who.rs
This PR bumps clap to `4.1.8` and fixes some broken tests caused by changes in clap's error messages.
=> Bump clap from 4.0.26 to 4.1.8 & fix broken tests

src/uu/relpath/relpath.md, src/uu/relpath/src/relpath.rs
Now relpath -h shows the following:
```
$ ./target/debug/coreutils relpath -h
Convert TO destination to the relative path from the FROM dir.
If FROM path is omitted, current working dir will be used.
Usage: ./target/debug/coreutils relpath [-d DIR] TO [FROM]
Arguments:
[TO]    
[FROM]  
Options:
-d <DIR>       If any of FROM and TO is not subpath of DIR, output absolute path instead of relative
```
=> relpath: move help strings to markdown file

Cargo.lock, Cargo.toml
This PR replaces the outdated https://github.com/uutils/coreutils/pull/4310
=> Bump procfs from 0.14.1 to 0.15.1

Cargo.lock, Cargo.toml
This PR replaces the outdated https://github.com/uutils/coreutils/pull/4203
=> Bump terminal_size from 0.2.2 to 0.2.5

.github/workflows/CICD.yml
instead of Swatinem/rust-cache@v2
After that PR, GNU's jobs are next
=> Use sccache to cache build results

README.md
`cargo install --path . --locked` will honor the existing `Cargo.lock`. This will use version `0.3.17` of the time crate instead of the non-compatible `0.3.18`.
=> readme: advise using --locked with cargo install

util/gnu-json-result.py
Closes #4341 
Ignore decoding error with the `open()` function in `gnu-json-result.py`
```bash
$ python3 /coreutils/util/gnu-json-result.py /gnu/tests
/gnu/tests/test-suite.log 'utf-8' codec can't decode byte 0xc0 in position 940: invalid start byte
/gnu/tests/misc/stat-printf.log 'utf-8' codec can't decode byte 0xff in position 297: invalid start byte                                                           
/gnu/tests/misc/tr.log 'utf-8' codec can't decode byte 0xc0 in position 627: invalid start byte
```
=> docs: fix tr.pl and stat-printf.pl don't show up in gnu-full-result

src/uu/mkfifo/mkfifo.md, src/uu/mkfifo/src/mkfifo.rs
#4368 
`mkfifo -h` outputs the following.
```shell
$ ./target/debug/coreutils mkfifo -h
Create a FIFO with the given name.
Usage: ./target/debug/coreutils mkfifo [OPTION]... NAME...
Options:
-m, --mode <MODE>    file permissions for the fifo [default: 0666]
-Z                   set the SELinux security context to default type
--context <CTX>  like -Z, or if CTX is specified then set the SELinux or SMACK security context to CTX
-h, --help           Print help
-V, --version        Print version
```
=> mkfifo: move help strings to markdown file

Cargo.lock
This PR bumps `fts-sys` from `0.2.3` to `0.2.4` and `selinux-sys` from `0.6.1` to `0.6.2`. It replaces https://github.com/uutils/coreutils/pull/4177 and should fix the error `found 2 duplicate entries for crate 'bindgen'` from `CICD / Style/cargo-deny`
=> Bump fts-sys to 0.2.4 & selinux-sys to 0.6.2

src/uu/timeout/src/timeout.rs, src/uucore/src/lib/features/process.rs, tests/by-util/test_timeout.rs
Closes #4176.
This should also fix #4073.
Follow GNU's timeout behavior, send a signal to the process group to make sure subprocesses are cleaned up, and also send SIGCONT to the child and the whole process group after that.
=> timeout: fix subprocess is never terminated

CONTRIBUTING.md
This PR changes a link to https and fixes the quoted text in the `Commit messages` section to match the original (https://git-scm.com/book/ch5-2.html).
=> Use https in link & fix quote in CONTRIBUTING.md

src/uu/whoami/src/whoami.rs, src/uu/whoami/whoami.md
#4368 
```bash
$ cargo run --features 'whoami' -- whoami -h
Finished dev [unoptimized + debuginfo] target(s) in 0.12s
Running `target/debug/coreutils whoami -h`
Print the current username.
Usage: whoami
Options:
```
=> whoami: move help strings to markdown file

src/uu/uptime/src/uptime.rs, src/uu/uptime/uptime.md
#4368 
```bash
$ cargo run --features 'uptime' -- uptime -h
Finished dev [unoptimized + debuginfo] target(s) in 0.13s
Running `target/debug/coreutils uptime -h`
Display the current time, the length of time the system has been up,
the number of users on the system, and the average number of jobs
in the run queue over the last 1, 5 and 15 minutes.
Usage: target/debug/coreutils uptime [OPTION]...
Options:
-s, --since    system up since
```
=> uptime: move help strings to markdown file

src/uu/date/src/date.rs, tests/by-util/test_date.rs
=> fix: match date -I error messages with GNU date

src/uu/date/src/date.rs, tests/by-util/test_date.rs
`default_missing_value` set to `OPT_DATE` (`"date"`) `num_args(0..=1)` required for `default_missing_value`.
Using function name `test_date_rfc_8601_default`.
The function name `test_date_rfc_8601` is left intact for compatibility.
Fixes: #4521
=> date: Added default value for `date --i`.

tests/by-util/test_shred.rs
Closes #2061.
The `test-shred-force` has currently passed on FreeBSD, but I'm not sure which commit made it start working properly.
=> shred: enable `test_shred_force` on FreeBSD

src/uu/chmod/src/chmod.rs, src/uucore/src/lib/features/mode.rs, tests/by-util/test_chmod.rs
fixes chmod/usage.
The description of the test says:
> These test cases assume GNU behavior for "options" like -w. 
The tests are (basically) combinations (and re-occurrences) of options, like (`f` considered as valid file):
`chmod -- -w -- f`, `chmod -- -- -- f`, `chmod -w -w -- f`
I then tried (testwise): 
```
$ chmod -gw -w f -w
chmod: invalid mode: ‘-gw,-w,-w’
```
which seems to me like the options (like `-w`) are splitted from the files.
So my idea was to split the options from the files, keep order, and then "uniq" them before giving them to clap.
However, target is to find the not-working test cases, port them to the Rust unit tests, fix them, check for regression :)
=> chmod: fix GNU test 'chmod/usage'

src/uu/dd/src/dd.rs, tests/by-util/test_dd.rs
~This is a draft pull request because it includes the changes from pull request #4164. Review and merge that one first.~
This pull request causes `dd` to open stdin using its file descriptor so that a `dd skip=N` command in a subshell does not consume all bytes from stdin.
For example, before this commit, multiple instances of `dd` reading from stdin and appearing in a single command line would incorrectly result in an empty stdin for each instance of `dd` after the first:
$ printf "abcdef\n" | (dd bs=1 skip=3 count=0 && dd)  2> /dev/null
After this commit, the `dd skip=3` process reads three bytes from the file descriptor referring to stdin without draining the remaining three bytes when it terminates:
$ printf "abcdef\n" | (dd bs=1 skip=3 count=0 && dd)  2> /dev/null
def
This …
=> dd: open stdin from file descriptor when possible

src/uu/date/src/date.rs, tests/by-util/test_date.rs
Fixes https://github.com/uutils/coreutils/issues/4525
=> `date`: make sure 'invalid date' message also returns exit code 1

src/uu/date/src/date.rs, tests/by-util/test_date.rs
./target/release/coreutils date -f aze doesn't result in panic anymore, instead gives Error: File not found at path <PATH>. Fixes https://github.com/uutils/coreutils/issues/4480
=> A better handler for `./coreutils date -f aze`

tests/by-util/test_shuf.rs, tests/common/util.rs
With:
`cargo +nightly clippy --features unix --allow-dirty --fix -- -W clippy::pedantic`
=> Fix some simple clippy warnings

src/uu/mktemp/mktemp.md, src/uu/mktemp/src/mktemp.rs
#4368 
`mktemp -h` shows the following.
```shell
$ ./target/debug/coreutils mktemp -h
Create a temporary file or directory.
Usage: ./target/debug/coreutils mktemp [OPTION]... [TEMPLATE]
Arguments:
[template]  
Options:
-d, --directory        Make a directory instead of a file
-u, --dry-run          do not create anything; merely print a name (unsafe)
-q, --quiet            Fail silently if an error occurs.
--suffix <SUFFIX>  append SUFFIX to TEMPLATE; SUFFIX must not contain a path separator. This option is implied if TEMPLATE does not end with X.
-p, --tmpdir [<DIR>]   interpret TEMPLATE relative to DIR; if DIR is not specified, use $TMPDIR ($TMP on windows) if set, else /tmp. With this option, TEMPLATE
must not be an absolute name; unlike with -t, TEMPLATE may contain slashes, but …
```
=> mktemp: move help strings to markdown file

src/uu/mknod/mknod.md, src/uu/mknod/src/mknod.rs
#4368 
`mknod -h` outputs the following.
```shell
$ ./target/debug/coreutils mknod -h
Create the special file NAME of the given TYPE.
Usage: ./target/debug/coreutils mknod [OPTION]... NAME TYPE [MAJOR MINOR]
Arguments:
<NAME>   name of the new file
<TYPE>   type of the new file (b, c, u or p)
[MAJOR]  major file type
[MINOR]  minor file type
Options:
-m, --mode <MODE>  set file permission bits to MODE, not a=rw - umask
-h, --help         Print help
-V, --version      Print version
Mandatory arguments to long options are mandatory for short options too.
-m, --mode=MODE    set file permission bits to MODE, not a=rw - umask
--help     display this help and exit
--version  output version information and exit
Both MAJOR and MINOR must be specified when TYPE is b, c, or u, and they
must be …
```
=> mknod: move help strings to markdown file

src/uu/who/src/who.rs, src/uu/who/who.md
#4368
`who -h` outputs the following:
```
./target/debug/who -h
Print information about users who are currently logged in.
Usage: ./target/debug/who [OPTION]... [ FILE | ARG1 ARG2 ]
Arguments:
[FILE]...  
Options:
-a, --all       same as -b -d --login -p -r -t -T -u
-b, --boot      time of last system boot
-d, --dead      print dead processes
-H, --heading   print line of column headings
-l, --login     print system login processes
--lookup    attempt to canonicalize hostnames via DNS
-m              only hostname and user associated with stdin
-p, --process   print active processes spawned by init
-q, --count     all login names and number of users logged on
-r, --runlevel  print current runlevel
-s, --short     print only name, line, and time (default)
-t, --time      print last system …
```
=> who: move help strings to markdown file

src/uu/fold/fold.md, src/uu/fold/src/fold.rs
`fold -h` outputs the following:
```
./target/debug/fold -h
Writes each file (or standard input if no files are given)
to standard output whilst breaking long lines
Usage: ./target/debug/fold [OPTION]... [FILE]...
Options:
-b, --bytes          count using bytes rather than columns (meaning control characters such as newline are not treated specially)
-s, --spaces         break lines at word boundaries rather than a hard cut-off
-w, --width <WIDTH>  set WIDTH as the maximum line width rather than 80
-h, --help           Print help
-V, --version        Print version
```
=> fold: move move help strings to markdown file

tests/by-util/test_chmod.rs, tests/by-util/test_sort.rs, tests/by-util/test_tee.rs, tests/by-util/test_touch.rs
Hey im just taking some easy issues since i have free time right now: https://github.com/uutils/coreutils/issues/4533
=> fix: clippy long literal lacking separators

src/uu/groups/groups.md, src/uu/groups/src/groups.rs
`groups --help` outputs the following:
```
./target/debug/groups --help
Print group memberships for each `USERNAME` or, if no `USERNAME` is specified, for
the current process (which may differ if the groups data‐base has changed).
Usage: ./target/debug/groups [OPTION]... [USERNAME]...
Arguments:
[USERNAME]...  
Options:
```
=> groups: move help strings to markdown file

src/uu/false/false.md, src/uu/false/src/false.rs
`false --help` outputs the following:
```
./target/debug/false --help
Returns false, an unsuccessful exit status.
Immediately returns with the exit status `1`. When invoked with one of the recognized options it
will try to write the help or version text. Any IO error during this operation is diagnosed, yet
the program will also return `1`.
Usage: false
Options:
--help     Print help information
--version  Print version information
```
=> false: move help strings to markdown file

src/uu/expand/expand.md, src/uu/expand/src/expand.rs
`expand -h` outputs the following:
```
./target/debug/expand -h
Convert tabs in each FILE to spaces, writing to standard output.
Usage: ./target/debug/expand [OPTION]... [FILE]...
Options:
-i, --initial         do not convert tabs after non blanks
-t, --tabs <N, LIST>  have tabs N characters apart, not 8 or use comma separated list of explicit tab positions
-U, --no-utf8         interpret input file as 8-bit ASCII rather than UTF-8
-h, --help            Print help
-V, --version         Print version
```
=> expand: move help strings to markdown file

README.md
This PR removes the LOC (lines of code) badge because it shows `0`. A corresponding [ticket](https://github.com/XAMPPRocky/tokei/issues/881) has been open for more than a year.
=> readme: remove LOC badge

src/uu/factor/factor.md, src/uu/factor/src/cli.rs
#4368 
```sh
$ cargo run -puu_factor -- factor -h
Finished dev [unoptimized + debuginfo] target(s) in 0.56s
Running `target/debug/factor factor -h`
Print the prime factors of the given NUMBER(s).
If none are specified, read from standard input.
Usage: target/debug/factor [NUMBER]...
Arguments:
[NUMBER]...
Options:
```
=> factor: move help strings to markdown file

src/uu/head/head.md, src/uu/head/src/head.rs
#4368 
```sh
$ cargo run -puu_head -- head -h
Finished dev [unoptimized + debuginfo] target(s) in 0.59s
Running `target/debug/head head -h`
Print the first 10 lines of each FILE to standard output.
With more than one FILE, precede each with a header giving the file name.
Mandatory arguments to long flags are mandatory for short flags too.
Usage: target/debug/head [FLAG]... [FILE]...
Arguments:
[FILE]...
Options:
-c, --bytes <[-]NUM>   print the first NUM bytes of each file;
with the leading '-', print all but the last
NUM bytes of each file
-n, --lines <[-]NUM>   print the first NUM lines instead of the first 10;
with the leading '-', print all but the last
NUM lines of each file
-q, --quiet            never print headers giving file …
```
=> head: move help strings to markdown file

src/uu/hashsum/hashsum.md, src/uu/hashsum/src/hashsum.rs
#4368 
```sh
$ cargo run -- hashsum -h
Finished dev [unoptimized + debuginfo] target(s) in 2.82s
Running `target/debug/coreutils hashsum -h`
Compute and check message digests.
Usage: target/debug/coreutils hashsum [OPTIONS] [FILE]...
Arguments:
[FILE]...
Options:
-b, --binary       read in binary mode
-c, --check        read hashsums from the FILEs and check them
--tag          create a BSD-style checksum
-t, --text         read in text mode (default)
-q, --quiet        don't print OK for each successfully verified file
-s, --status       don't output anything, status code shows success
--strict       exit non-zero for improperly formatted checksum lines
-w, --warn         warn about improperly formatted checksum lines
--bits <BITS>  set the size of the output (only for SHAKE)
--no-names …
```
=> hashsum: move help strings to markdown file

src/uu/users/src/users.rs, src/uu/users/users.md
#4368 
```sh
$ cargo run -puu_users -- users -h
Finished dev [unoptimized + debuginfo] target(s) in 0.51s
Running `target/debug/users users -h`
Print the user names of users currently logged in to the current host.
Usage: target/debug/users [FILE]
Arguments:
[files]
Options:
Output who is currently logged in according to FILE.
If FILE is not specified, use /var/run/utmp.  /var/log/wtmp as FILE is common.
```
=> users: move help strings to markdown file

tests/by-util/test_chroot.rs
See https://github.com/uutils/coreutils/actions/runs/4486101640/jobs/7888344087
```
warning: unused import: `is_ci`
--> tests/by-util/test_chroot.rs:3:27
|
3 | use crate::common::util::{is_ci, run_ucmd_as_root, TestScenario};
|                           ^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: `coreutils` (test "tests") generated 1 warning
Finished test [unoptimized + debuginfo] target(s) in 5m 12s
Running unittests src/bin/coreutils.rs (target/debug/deps/coreutils-c1c95fca0b7a1e35)
```
=> chroot: fix unused import on Android

src/uu/hostid/hostid.md, src/uu/hostid/src/hostid.rs
`hostid --help` outputs the following:
```
target/debug/hostid --help
Print the numeric identifier (in hexadecimal) for the current host
Usage: target/debug/hostid [options]
Options:
```
=> hostid: move help strings to markdown file

tests/by-util/test_touch.rs
This PR adds underscores to a long number in a test. The number was overlooked in https://github.com/uutils/coreutils/pull/4546
=> touch: add underscores to long number in test

src/uu/cut/cut.md, src/uu/cut/src/cut.rs
Replacement for https://github.com/uutils/coreutils/pull/4550
`cut -h` outputs the following after the change with markdown:
```
Prints specified byte or field columns from each line of stdin or the input files
Usage: target/debug/cut [-d|-w] [-s] [-z] [--output-delimiter] ((-f|-b|-c) {{sequence}}) {{sourcefile}}+
Options:
-b, --bytes <LIST>                  filter byte columns from the input source
-c, --characters <LIST>             alias for character mode
-d, --delimiter <DELIM>             specify the delimiter character that separates fields in the input source. Defaults to Tab.
-w                                  Use any number of whitespace (Space, Tab) to separate fields in the input source (FreeBSD extension).
-f, --fields <LIST> …
```
=> cut: move help strings to markdown file

src/uucore_procs/src/lib.rs
While working on help for cut I've noticed that headers for levels below 2 are not rendered.
This is due to the fact that every they start with `##`.
To reproduce check current help for `dd` command before and after the fix.
I'm not sure if it's the best solution.
=> uucore: fix help section doesn't render 3+ level headers
