src/uu/nproc/nproc.md
src/uu/nproc/src/nproc.rs

`nproc` --help outputs the following:
```
target/debug/nproc --help
Print the number of cores available to the current process.
If the `OMP_NUM_THREADS` or `OMP_THREAD_LIMIT` environment variables are set, then
they will determine the minimum and maximum returned value respectively.
Usage: ./target/debug/nproc [OPTIONS]...
Options:
--all         print the number of cores available to the system
--ignore <N>  ignore up to N cores
-h, --help        Print help
-V, --version     Print version
```

nproc: move help strings to markdown file

---

src/uu/touch/src/touch.rs
src/uu/touch/touch.md

`touch --help` outputs the following:
```
target/debug/touch --help
Update the access and modification times of each `FILE` to the current time.
Usage: target/debug/touch [OPTION]... [USER]
Arguments:
[files]...  
Options:
--help              Print help information.
-a                      change only the access time
-t <STAMP>              use [[CC]YY]MMDDhhmm[.ss] instead of the current time
-d, --date <STRING>     parse argument and use it instead of current time
-m                      change only the modification time
-c, --no-create         do not create any files
-h, --no-dereference    affect each symbolic link instead of any referenced file (only for systems that can change the timestamps of a symlink)
-r, --reference <FILE>  use …
```

touch: move help strings to markdown file

---

src/uu/logname/logname.md
src/uu/logname/src/logname.rs

`logname --help` outputs the following:
```
target/debug/logname --help
Print user's login name
Usage: target/debug/logname
Options:
```

logname: move help strings to markdown file

---

src/uu/id/id.md
src/uu/id/src/id.rs

#4368
`id --help` outputs the following:
```
target/debug/id --help
Print user and group information for each specified `USER`,
or (when `USER` omitted) for the current user.
Usage: target/debug/id [OPTION]... [USER]...
Arguments:
[USER]...  
Options:
-A             Display the process audit user ID and other process audit properties,
which requires privilege (not available on Linux).
-u, --user     Display only the effective user ID as a number.
-g, --group    Display only the effective group ID as a number
-G, --groups   Display only the different group IDs as white-space separated numbers, in no particular order.
-p             Make the output human-readable. Each display is on a separate line.
-n, --name     Display the name of the user or group ID for the -G, -g and -u options …
```

id: move help strings to a markdown file

---

src/uu/join/join.md
src/uu/join/src/join.rs

`join --help` outputs the following:
```
target/debug/join --help
For each pair of input lines with identical join fields, write a line to
standard output. The default join field is the first, delimited by blanks.
When `FILE1` or `FILE2` (not both) is `-`, read standard input.
Usage: target/debug/join <FILE1> <FILE2>
Options:
-a <FILENUM>           also print unpairable lines from file FILENUM, where
FILENUM is 1 or 2, corresponding to FILE1 or FILE2 [possible values: 1, 2]
-v <FILENUM>           like -a FILENUM, but suppress joined output lines [possible values: 1, 2]
-e <EMPTY>             replace missing input fields with EMPTY
-i, --ignore-case      ignore differences in case when comparing fields
-j <FIELD>             equivalent to '-1 …
```

join: move help strings to markdown file

---

src/uu/nice/nice.md
src/uu/nice/src/nice.rs

`nice --help` outputs the following:
```
target/debug/nice --help
Run `COMMAND` with an adjusted niceness, which affects process scheduling.
With no `COMMAND`, print the current niceness.  Niceness values range from at
least -20 (most favorable to the process) to 19 (least favorable to the
process).
Usage: target/debug/nice [OPTIONS] [COMMAND [ARGS]]
Arguments:
[COMMAND]...  
Options:
-n, --adjustment <adjustment>  add N to the niceness (default is 10)
-h, --help                     Print help
-V, --version                  Print version
```

nice: move help strings to markdown file

---

src/uu/more/more.md
src/uu/more/src/more.rs

`more --help` outputs the following:
```
target/debug/more --help
A file perusal filter for CRT viewing.
Usage: target/debug/more [OPTIONS] <FILE>...
Arguments:
[files]...  Path to the files to be read
Options:
-d, --silent   Display help instead of ringing bell
```

more: move help strings to markdown file

---

src/uucore/src/lib/lib.rs

Closes https://github.com/uutils/coreutils/issues/4543
I noticed it just got the name from command line. I added a condition to get the next argument instead when you use man.
There may be a better solution than this.

fix: to show the name of utility instead of 'manpages'

---

Cargo.toml
docs/src/packaging.md
src/uu/stdbuf/build.rs

Inspired by https://github.com/uutils/coreutils/pull/4436 and https://github.com/uutils/coreutils/issues/747.
In the comments of #4436, I did an exploration of the binary size by trying different settings in cargo. The conclusion was that we can get the binary size down by a lot (even smaller than GNU), but that this will make bug reports less useful. Therefore, we should leave the exact configuration up to package maintainers. To document that, I've written a page on packaging this project in the docs. This page explains the best practices for the package name (since we had some issues there) and how to configure the package.
Additionally, to quickly see what our best performance and smallest binary size is, I've created the `release-fast` and `release-small` profiles in addition to the …

`release-fast` and `release-small` profiles and a page on packaging in the docs.

---

src/uucore/src/lib/lib.rs

This PR indents multiline usage info to align them because clap adds `Usage: ` to the first line. This changes the help output from
```
Usage: target/debug/coreutils expr [EXPRESSION]
target/debug/coreutils expr [OPTIONS]
```
to 
```
Usage: target/debug/coreutils expr [EXPRESSION]
target/debug/coreutils expr [OPTIONS]
```

uucore: indent multiline usage info

---

Cargo.lock
src/uu/factor/Cargo.toml
src/uu/factor/src/miller_rabin.rs
src/uu/factor/src/numeric/modular_inverse.rs
src/uu/factor/src/numeric/montgomery.rs

Another macro that's not really pulling its weight. I think being explicit here is easier to understand anyway.

`factor`: remove `paste` dev dependency

---

Cargo.lock
Cargo.toml
src/uu/uniq/Cargo.toml
src/uu/uniq/src/uniq.rs

The `strum` dependency was only used here and it wasn't doing a lot. It also pulled in two transitive dependencies.

`uniq`: remove `strum` dependency

---

src/uu/test/src/error.rs
src/uu/test/src/parser.rs
src/uu/test/src/test.rs
tests/by-util/test_test.rs

Closes https://github.com/uutils/coreutils/issues/4556 
Closes https://github.com/uutils/coreutils/issues/4555

test: replace panic in favor of ParseError

---

src/uu/cp/src/cp.rs
src/uu/ln/src/ln.rs
src/uu/mv/src/mv.rs
tests/by-util/test_cp.rs
tests/by-util/test_ln.rs
tests/by-util/test_mv.rs

Mentioned in issue #4627
touch a b && echo "n"|./target/debug/coreutils ln -i a b; echo $?
was 0, it is now 1
See: 
https://github.com/coreutils/coreutils/commit/7a69df88999bedd8e9fccf9f3dfa9ac6907fab66
(no problem reading the code here as there isn't much)

Adjust -i behavior for ln, cp & mv 

---

Cargo.lock
src/uu/tee/src/tee.rs
src/uu/timeout/src/timeout.rs
src/uu/yes/Cargo.toml
src/uu/yes/src/yes.rs
src/uucore/Cargo.toml
src/uucore/src/lib/features/signals.rs
src/uucore/src/lib/mods/error.rs

Edit : Original title was "yes: remove redundant dependency"
Yes, using libc while using nix was a bit redundant.

Refactor signal handling in yes, tee, and timeout

---

src/uu/stdbuf/build.rs

The path is not always `/target/{PROFILE}`, because cross uses `/target/{TARGET_TRIPLE}/{PROFILE}`, so we have to get the name of the profile in another way. StackOverflow recommended the getting the third component from the back of the path.
Closes https://github.com/uutils/coreutils/issues/4634 (hopefully)
Maybe some time soon https://github.com/rust-lang/cargo/issues/11054 will get fixed and we can remove this again.

`stdbuf`: get profile from the end of the path

---

.cargo/config
.github/workflows/CICD.yml
Cargo.lock
tests/by-util/test_cp.rs
tests/by-util/test_mv.rs
tests/by-util/test_touch.rs

Should fix the issues in https://github.com/uutils/coreutils/pull/4639
With https://github.com/uutils/coreutils/pull/4593, we no longer run `now_local` in a multithreaded environment, so we don't need to opt in to the unsound behaviour anymore. If we ever do need to do that, we should probably use `chrono` instead.

deps: bump `time` from 0.3.17 to 0.3.20

---

.github/workflows/CICD.yml

It's already defined on line 613 and is running twice, for example:
- https://github.com/uutils/coreutils/actions/runs/4518817884/jobs/7959076091
- https://github.com/uutils/coreutils/actions/runs/4518817884/jobs/7959076264

CI: Remove duplicated x86_64-unknown-linux-gnu target from build job

---

.github/workflows/CICD.yml

While reviewing https://github.com/uutils/coreutils/pull/4648 I noticed some comments related to `ubuntu-18.04`. Its standard support ends in a month and so I guess we don't need those comments anymore.

CICD: remove outdated comments

---

src/uu/du/src/du.rs
tests/by-util/test_du.rs

This pull requests adds an error message to the `--threshold` option inline with the GNU version of du.
Previous behavior:
```sh
$ du --threshold -0 file
0	file
```
Current behavior:
```sh
$ du --threshold -0 file
du: invalid --threshold argument '-0'
```

du: threshold error message fix

---

src/uu/pathchk/pathchk.md
src/uu/pathchk/src/pathchk.rs

`pathchk` --help outputs the following:
```
target/debug/pathchk --help
Check whether file names are valid or portable
Usage: target/debug/pathchk [OPTION]... NAME...
Options:
-p                 check for most POSIX systems
-P                 check for empty names and leading "-"
--portability  check for all POSIX systems (equivalent to -p -P)
-h, --help         Print help
-V, --version      Print version
```

pathchk: move help strings to markdown file

---

tests/by-util/test_mktemp.rs

Uncomment a test case fixed by commit
53c4b0b81e528adc340dd803bf597fa3fad1bb4c (pull request https://github.com/uutils/coreutils/pull/4091).

mktemp: uncomment fixed test case

---

src/uu/paste/paste.md
src/uu/paste/src/paste.rs

`paste --help` outputs the following:
```
target/debug/paste --help
Write lines consisting of the sequentially corresponding lines from each
`FILE`, separated by `TABs`, to standard output.
Usage: ./target/debug/paste [OPTIONS] [FILE]...
Arguments:
[FILE]...  [default: -]
Options:
-s, --serial             paste one file at a time instead of in parallel
-d, --delimiters <LIST>  reuse characters from LIST instead of TABs
-z, --zero-terminated    line delimiter is NUL, not newline
-h, --help               Print help
-V, --version            Print version
```

paste: move help strings to markdown file

---

src/uu/date/src/date.rs
tests/by-util/test_date.rs

Fixes #4539 
GNU `date` runs `fopen` on input path ("/"). Later, we are at https://github.com/coreutils/coreutils/blob/master/src/date.c#L372 where `getline` fails and the `while(true)` loop breaks.
This error message gets returned as result for `batch_convert` which in the end calls `main_exit` where the process finally exits with error code 1.
If a directory path is provided as argument for `-f`, we show the following error:
```sh
$ target/debug/coreutils date -f /
date: expected file, got directory
```

date: show error when reading dirs for -f arg

---

.github/workflows/CICD.yml

This PR removes the `continue-on-error: true` setting in the `fuzz_date` step because the issue mentioned in the todo has been fixed in https://github.com/uutils/coreutils/pull/4499.

CICD: remove "continue on error" in fuzz_date step

---

src/uu/unlink/src/unlink.rs
src/uu/unlink/unlink.md

#4368
```sh
$ cargo run -- unlink --help
Finished dev [unoptimized + debuginfo] target(s) in 0.11s
Running `target/debug/coreutils unlink --help`
Unlink the file at FILE.
Usage: target/debug/coreutils unlink [FILE]
Options:
```

unlink: move help strings to markdown file

---

src/uu/uniq/src/uniq.rs
src/uu/uniq/uniq.md

#4368 
```sh
$ cargo run -- uniq --help
Finished dev [unoptimized + debuginfo] target(s) in 0.14s
Running `target/debug/coreutils uniq --help`
Report or omit repeated lines.
Usage: target/debug/coreutils uniq [OPTION]... [INPUT [OUTPUT]]...
Arguments:
[files]...
Options:
-D, --all-repeated[=<delimit-method>]  print all duplicate lines. Delimiting is done with blank lines. [default: none] [possible values: none, prepend, separate]
--group[=<group-method>]           show all items, separating groups with an empty line. [default: separate] [possible values: separate, prepend, append, both]
-w, --check-chars <N>                  compare no more than N characters in lines
-c, --count                            prefix lines by the number of occurrences
-i, --ignore-case …
```

uniq: move help strings to markdown file

---

src/uu/pr/pr.md
src/uu/pr/src/pr.rs

`pr --help` outputs the following:
```
target/debug/pr --help
Write content of given file or standard input to standard output with pagination filter
Usage: target/debug/pr [OPTIONS] [files]...
Arguments:
[files]...  
Options:
--pages <FIRST_PAGE[:LAST_PAGE]>
Begin and stop printing with page FIRST_PAGE[:LAST_PAGE]
-h, --header <STRING>
Use the string header to replace the file name in the header line.
-d, --double-space
Produce output that is double spaced. An extra <newline> character is output
following every <newline> found in the input.
-n, --number-lines <[char][width]>
Provide width digit line numbering.  The default for width, if not specified, is
5.  The number occupies the first width column positions of each text column or
each …
```

pr: move help strings to markdown file

---

src/uu/wc/src/wc.rs
tests/by-util/test_wc.rs

This PR implements `wc --total` which allows you to define whether the "total" row should be shown. It makes all tests in https://github.com/coreutils/coreutils/blob/master/tests/misc/wc-total.sh pass.

wc: implement --total

---

src/uu/pinky/pinky.md
src/uu/pinky/src/pinky.rs

issue: #4368 
`pinky --help` outputs the following.
```
./target/debug/pinky --help
Lightweight finger
Usage: ./target/debug/pinky [OPTION]... [USER]...
Arguments:
[user]...  
Options:
-l             produce long format output for the specified USERs
-b             omit the user's home directory and shell in long format
-h             omit the user's project file in long format
-p             omit the user's plan file in long format
-s             do short format output, this is the default
-f             omit the line of column headings in short format
-w             omit the user's full name in short format
-i             omit the user's full name and remote host in short format
-q             omit the user's full name, remote host and idle time in short format
--help     Print help …
```

pinky: move help strings to markdown file

---

src/uu/true/src/true.rs
src/uu/true/true.md

`true --help` outputs the following:
```
target/debug/true --help
Returns true, a successful exit status.
Immediately returns with the exit status `0`, except when invoked with one of the
recognized
options. In those cases it will try to write the help or version text. Any IO error during
this
operation causes the program to return `1` instead.
Usage: true
Options:
--help     Print help information
--version  Print version information
```

true: move help strings to markdown file

---

src/uu/unexpand/src/unexpand.rs
src/uu/unexpand/unexpand.md

`unexpand --help` outputs the following:
```
target/debug/unexpand --help
Convert blanks in each `FILE` to tabs, writing to standard output.
With no `FILE`, or when `FILE` is `-`, read standard input.
Usage: target/debug/unexpand [OPTION]... [FILE]...
Options:
-a, --all             convert all blanks, instead of just initial blanks
--first-only      convert only leading sequences of blanks (overrides -a)
-t, --tabs <N, LIST>  use comma separated LIST of tab positions or have tabs N characters
apart instead of 8 (enables -a)
-U, --no-utf8         interpret input file as 8-bit ASCII rather than UTF-8
-h, --help            Print help
-V, --version         Print version
```

unexpand: move help strings to markdown file

---

tests/by-util/test_wc.rs

This PR uses `concat!` to improve the readability of the tests from https://github.com/uutils/coreutils/pull/4695. Inspired by the tests in https://github.com/uutils/coreutils/pull/4696.

wc: use concat! to improve readability of tests

---

src/uu/touch/src/touch.rs
tests/by-util/test_touch.rs

This commit resolves issue #4608.
To make it relatively straightforward to implement I have taken some
code from parse_date and put it inside a function parse_relative_time.
This commit changes and adds some test as well to work with the new
functionality.

touch: add support for --ref and --date together

---

src/uu/touch/src/touch.rs
tests/by-util/test_touch.rs

This PR removes a few "extern crate"s and expands a glob import.

touch: remove unnecessary "extern crate"s

---

src/uu/sync/src/sync.rs
src/uucore/src/lib/features/fsext.rs
src/uucore/src/lib/features/utmpx.rs
src/uucore/src/lib/mods/backup_control.rs
src/uucore_procs/src/lib.rs

This PR removes some more unnecessary "extern crate" statements.

Remove some unnecessary "extern crate" statements

---

tests/by-util/test_chmod.rs
tests/by-util/test_chown.rs
tests/by-util/test_date.rs
tests/by-util/test_dir.rs
tests/by-util/test_dircolors.rs
tests/by-util/test_hostid.rs
tests/by-util/test_ls.rs
tests/by-util/test_mkdir.rs
tests/by-util/test_mv.rs
tests/by-util/test_od.rs
tests/by-util/test_pinky.rs
tests/by-util/test_pr.rs
tests/by-util/test_split.rs
tests/by-util/test_stat.rs
tests/by-util/test_sync.rs
tests/by-util/test_tail.rs
tests/by-util/test_uptime.rs
tests/by-util/test_vdir.rs
tests/tests.rs

The final PR to clean up unnecessary "extern crate" statements.

tests: remove all "extern crate" statements

---

src/uu/hashsum/src/hashsum.rs
src/uucore/src/lib/features/sum.rs
tests/by-util/test_hashsum.rs

This pull request adds support for the -l/--length option to b2sum (hashsum).
B2sum supports variable output size if 
- length is a multiple of 8 bits
- length is less or equal than 512
#4610 
This is my first attempt to contribute to this project, so I may have missed something. (same goes for naming conventions) !
I added a new function to allow creating a Blake2d instance with custom output size (`with_output_bytes`). I updated the reset function to use this new function instead of calling ::new().
Eventually, the Blake2d tuple has now a new parameter to keep track of the custom size. 
I had to create a new parsing step `uu_app_opt_length` that behaves more or less like `uu_app_opt_bits` but cannot share the same code due to different text / names.
I added a simple test with the …

B2sum: add -l/--length option

---

src/uu/du/src/du.rs
tests/by-util/test_du.rs

Should make tests/du/deref.sh pass

du: add support of --dereference-args & minor changes

---

util/build-gnu.sh
util/run-gnu-test.sh

This PR fixes a comment where I think the comment is incorrect (and not the corresponding code). And it removes a comment about `UU_MAKE_PROFILE` because this variable doesn't appear in the file.

Fix incorrect comment & remove irrelevant comment

---

Cargo.lock
Cargo.toml
src/uu/factor/factor.md
src/uu/factor/src/cli.rs
src/uu/factor/src/factor.rs
tests/benches/factor/Cargo.toml
tests/benches/factor/benches/gcd.rs
tests/benches/factor/benches/table.rs
tests/by-util/test_factor.rs

This pull request adds support for the -h/--exponents option to the factor function, which was recently introduced in GNU coreutils 9.2. 
With this option, the factors are printed in the form p^e, rather than repeating the prime p, e times.
For example : 
```
$ ./factor -h 3000
3000: 2^3 3 5^3
```
This is implemented with a new module that sets a mutable global variable when the option is provided. The Display implementation for Factors has been updated to use this global variable when printing factors. Tests have been added to cover the new option.
This pull request Fixes #4682

factor: add -h/--exponents option

---

.github/workflows/CICD.yml

We need this PR to be merged before checking the binary size. See #4693

CI: compute individual binary sizes

---

.github/workflows/CICD.yml
.github/workflows/GnuTests.yml

This fix places steps which influence the cache key of `Swatinem/rust-cache` before this `Swatinem/rust-cache` step to produce more cache hits and eventually speed up ci runs.
Note this pr also adds the `Swatinem/rust-cache` step to some jobs which haven't used caching, yet.
Closes #4741

ci: Fix usages of rust-cache to produce more cache hits

---

.config/nextest.toml
.github/workflows/CICD.yml
.github/workflows/android.yml
.github/workflows/freebsd.yml
CONTRIBUTING.md
GNUmakefile
util/android-commands.sh

This pr installs `cargo-nextest` as test runner in ci workflows and jobs previously running tests with `cargo test`.
[nextest](https://nexte.st/index.html) comes with a better execution model making it less error prone, so that test binaries exiting with error still report the test which caused the error. It also comes with other features like 
* test retries and marking intermittently failing tests as flaky
* showing per test execution times and particularly slow tests
* ... see the docs
Note there's no performance improvement in the ci because of the lack of a multi-core test environment. Together with the installation step of `nextest` the test jobs even take around 5-10 seconds longer. 
In case of the `android` workflow, the `nextest` binary has to be built from source because none of …

`ci`: Run tests with nextest

---

Cargo.lock
Cargo.toml
src/bin/uudoc.rs
src/help_parser/Cargo.toml
src/help_parser/src/lib.rs
src/uucore_procs/Cargo.toml
src/uucore_procs/src/lib.rs

This PR is related to https://github.com/uutils/coreutils/pull/4393#issuecomment-1436617819 and removes the check for the `about` section. It also removes the check for the `long_about` value because no tool sets this value.

uudoc, uucore_procs: move markdown parsing to HelpParser

---

tests/by-util/test_fmt.rs

This PR cleans up the `fmt` tests. It 
- renames test functions
- deletes commented out code
- uses short and long versions of params
- replaces `assert_eq!` with either `stdout_is` or `stderr_is`

fmt: cleanup tests

---

.github/workflows/android.yml
util/android-commands.sh

This pr fixes and improves caching of the rust directories `$HOME/.cargo` and `$PROJECT_ROOT/target` to speed up the build and test steps. Due to the need for better debugging output during the development of this pr, the `android-commands.sh` script was enhanced in many ways, too.
Summary of changes in the `android.yml` workflow:
* Remove the unnecessary `Swatinem/rust-cache` and `mozilla-actions/sccache-action` actions including some enviroment variables.
* Increase the disk size of the emulator image.
* For better error handling move the creation of the emulator snapshot into the `android-command.sh` script which can be run with the `init` function
* Store a hash of the rustc version of the rust version installed in the emulator image along with the rest of the avd directories during …

ci/android: speed up build and test

---

src/uu/test/src/error.rs
src/uu/wc/src/utf8/read.rs

This PR fixes warnings from the [uninlined_format_args](https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args) lint (clippy::pedantic).

test,wc: use vars directly in format! strings

---

tests/by-util/test_du.rs

This PR fixes the clippy warning I mentioned in https://github.com/uutils/coreutils/pull/4759#issuecomment-1517476090

du: fix clippy warning in test

---

src/uu/readlink/readlink.md
src/uu/readlink/src/readlink.rs

issue: #4368 
This PR contains bellow contents.
- Move help strings to markdown file e82ba6e7073fa1ff0cd3c42005cb4cecf70f075b
- Use override_usage method instead of override_help method b84a94b8895137819f5eda95db74dc16febba69c
`readlink --help` outputs follow.
**before**
```
$ ./target/debug/readlink --help
./target/debug/readlink [OPTION]... [FILE]...
```
**after**
```
$ ./target/debugreadlink --help
Print value of a symbolic link or canonical file name.
Usage: ./target/debug/readlink [OPTION]... [FILE]...
Arguments:
[files]...
Options:
-f, --canonicalize           canonicalize by following every symlink in every component of the given name recursively; all but the last component must exist
-e, --canonicalize-existing  canonicalize by following every symlink in every component of the …
```

readlink: move help strings to markdown file

---

src/uu/runcon/runcon.md
src/uu/runcon/src/runcon.rs

`runcon --help` outputs follow.
```
$ ./target/debug/runcon --help
Run command with specified security context.
Usage: ./target/debug/runcon [CONTEXT COMMAND [ARG...]]
./target/debug/runcon [-c] [-u USER] [-r ROLE] [-t TYPE] [-l RANGE] COMMAND [ARG...]";
Arguments:
[ARG]...  
Options:
-c, --compute        Compute process transition context before modifying.
-u, --user <USER>    Set user USER in the target security context.
-r, --role <ROLE>    Set role ROLE in the target security context.
-t, --type <TYPE>    Set type TYPE in the target security context.
-l, --range <RANGE>  Set range RANGE in the target security context.
-h, --help           Print help
-V, --version        Print version
Run COMMAND with completely-specified CONTEXT, or with current or transitioned security context …
```

runcon: move help strings to markdown file

---

src/uu/factor/src/cli.rs

When running factor without an argument, results are never printed. In that case, the stdout writer is never flushed since it's flushed at the end of the handling. I added a flush after a write to the buffer, and now it works as expected.

Add flush after calculating factor

---

src/uu/mv/src/mv.rs
tests/by-util/test_mv.rs

This PR fixes #4724 . 
`mv -i a.txt target/` no longer shows an error message if `target` contains an `a.txt` file and the overwriting is declined. It just returns an exit code of `1`.

mv: show no error if overwriting is declined in interactive mode

---

src/uu/seq/seq.md
src/uu/seq/src/seq.rs

`seq --help` outputs follow.
```
$ ./target/debug/seq --help
Usage: ./target/debug/seq [OPTION]... LAST
./target/debug/seq [OPTION]... FIRST LAST
./target/debug/seq [OPTION]... FIRST INCREMENT LAST";
Arguments:
[numbers]...
Options:
-s, --separator <separator>    Separator character (defaults to \n)
-t, --terminator <terminator>  Terminator character (defaults to \n)
-w, --widths                   Equalize widths of all numbers by padding with zeros
-f, --format <format>          use printf style floating-point FORMAT
-h, --help                     Print help
-V, --version                  Print version
```

seq: move help strings to markdown file

---

src/uucore/src/lib/features/entries.rs

Rust nightly recently [started] issuing the following warning when compiling coreutils:
[started]: https://github.com/rust-lang/rust/pull/109944
```
warning: getting the inner pointer of a temporary `CString`
--> src/uucore/src/lib/features/entries.rs:324:67
|
324 |                         let data = $fnam(CString::new(k).unwrap().as_ptr());
|                                          ------------------------ ^^^^^^ this pointer will be invalid
|                                          |
|                                          this `CString` is deallocated at the end of the statement, bind it to a variable to extend its lifetime
...
340 | f!(getpwnam, getpwuid, uid_t, Passwd);
| ------------------------------------- in this macro invocation
|
= note: pointers do not have a lifetime; …
```

Fix a warning in upstream code on Rust nightly.

---

src/uu/touch/src/touch.rs
tests/by-util/test_touch.rs
util/build-gnu.sh

Basically fixing:
```
ln -s nowhere dangling
touch -h -r dangling file
touch -h dangling
touch -h -
```
For:
tests/touch/no-dereference.sh

touch: improve support for dangling link

---

src/uu/split/split.md
src/uu/split/src/split.rs

issue: #4368 
`split --help` outputs follow.
```
$ ./target/debug/split --help
Create output files containing consecutive or interleaved sections of input
Usage: ./target/debug/split [OPTION]... [INPUT [PREFIX]]
Arguments:
[input]   [default: -]
[prefix]  [default: x]
Options:
-b, --bytes <SIZE>
put SIZE bytes per output file
-C, --line-bytes <SIZE>
put at most SIZE bytes of lines per output file [default: 2]
-l, --lines <NUMBER>
put NUMBER lines/records per output file [default: 1000]
-n, --number <CHUNKS>
generate CHUNKS output files; see explanation below
--additional-suffix <SUFFIX>
additional SUFFIX to append to output file names [default: ]
--filter <COMMAND>
write to shell COMMAND; file name is $FILE (Currently not implemented for Windows)
-e, --elide-empty-files
do not generate …
```

split: move help strings to markdown file

---

tests/by-util/test_ls.rs

As the existing comment says, the expected output here is dependent on the platform, so use the `expected_result` utility to avoid hard-coding specific results for each platform.
This fixes spurious failures on my machine.

Use `expected_result` in test_ls to avoid spurious failures

---

tests/by-util/test_nice.rs

Make `test_get_current_niceness` query the libc nice value instead of hard-coding a value of zero. This avoids a spurious failure on systems which have a non-zero default nice value.
This fixes spurious failures on my machine.

Avoid spurious failures in the presence of non-zero default nice

---

src/uu/mv/src/mv.rs
tests/by-util/test_mv.rs

This PR adapts the behavior of `-n/--no-clobber` to the new behavior of GNU mv 9.3: it returns an exit code of `1` and shows a "not replacing" message if the target already exists.

mv: adapt -n behavior to GNU mv 9.3

---

src/uu/stty/src/stty.rs
src/uu/stty/stty.md

issue: #4368 
`stty --help` outputs follow.
```
./target/debug/stty
Print or change terminal characteristics.
Usage: ../../../target/debug/stty [-F DEVICE | --file=DEVICE] [SETTING]...
../../../target/debug/stty [-F DEVICE | --file=DEVICE] [-a|--all]
../../../target/debug/stty [-F DEVICE | --file=DEVICE] [-g|--save]
Arguments:
[settings]...  settings to change
Options:
-a, --all            print all current settings in human-readable form
-g, --save           print all current settings in a stty-readable form
-F, --file <DEVICE>  open and use the specified DEVICE instead of stdin
-h, --help           Print help
-V, --version        Print version
```

stty: move help strings to markdown file

---

tests/by-util/test_ls.rs

I tested on my laptop, the username has `.` characters, so `ls -l` tests fail, because they weren't allowing `.` characters in usernames
- Fix regular expressions that test `ls -l` calls

[tests/ls] Support user names containing dots

---

src/bin/coreutils.rs

The multi-call `coreutils` binary starts by trying to convert its invocation path into a UTF-8 string, panicking if this doesn't work.
This patch makes `coreutils` exit gracefully in this case.

coreutils: fixed panic when multi-call binary has funny name

---

src/uu/sum/src/sum.rs
src/uu/sum/sum.md

issue: #4368 
`sum --help` outputs follow.
```
$ ./target/debug/sum --help
Checksum and count the blocks in a file.
Usage: ./target/debug/sum [OPTION]... [FILE]..."
Options:
-r             use the BSD sum algorithm, use 1K blocks (default)
-s, --sysv     use System V sum algorithm, use 512 bytes blocks
```

sum: move help strings to markdown file

---

src/uu/paste/src/paste.rs
tests/by-util/test_paste.rs

Show an error if the user provides a delimiter list ending with an unescaped backslash. For example, `paste -d'\'` will now show an error whereas `paste -d'\\'` will work fine.
This makes the tests `delim-bs1` and `delim-bs2` in https://github.com/coreutils/coreutils/blob/master/tests/misc/paste.pl pass.

paste: handle list ending with unescaped backslash

---

src/uu/sync/src/sync.rs
src/uu/sync/sync.md

issue #4368 
`sync --help` outputs follow.
```
$ ./target/debug/sync --help
Synchronize cached writes to persistent storage
Usage: ./target/debug/sync [OPTION]... FILE...
Arguments:
[files]...
Options:
-f, --file-system  sync the file systems that contain the files (Linux and Windows only)
-d, --data         sync only file data, no unneeded metadata (Linux only)
-h, --help         Print help
-V, --version      Print version
```

sync: move help strings to markdown file

---

src/uu/mv/src/mv.rs

This PR fixes the hack I mentioned in https://github.com/uutils/coreutils/pull/4794#discussion_r1179288936 and reverts the change made to `mv.rs` in https://github.com/uutils/coreutils/pull/4794.
Now, the check whether `--target` is a directory is done when processing the args, thus ensuring the `target_dir` property in the `Behavior` struct is a directory.

mv: validate --target arg

---

src/uu/timeout/src/timeout.rs
src/uu/timeout/timeout.md

issue: #4368 
`timeout --help` outputs follow.
```
$ ./target/debug/timeout --help
Start COMMAND, and kill it if still running after DURATION.
Usage: ./target/debug/timeout [OPTION] DURATION COMMAND...
Arguments:
<duration>
<command>...
Options:
--foreground               when not running timeout directly from a shell prompt, allow COMMAND to read from the TTY and get TTY signals; in this mode, children of COMMAND will not be timed out
-k, --kill-after <kill-after>  also send a KILL signal if COMMAND is still running this long after the initial signal was sent
--preserve-status          exit with the same status as COMMAND, even when the command times out
-s, --signal <SIGNAL>          specify the signal to be sent on timeout; SIGNAL may be a name like 'HUP' or a number; see 'kill -l' for …
```

timeout: move help strings to markdown file

---

src/uu/sort/sort.md
src/uu/sort/src/sort.rs

Move help strings for `sort` to its own markdown file.

sort: Move help strings to markdown file

---

src/uu/cp/src/cp.rs
tests/by-util/test_cp.rs

Partially fix GNU: tests/cp/thru-dangling.sh

cp: add support POSIXLY_CORRECT=1 when dealing with dangling links

---

src/uu/test/src/test.rs
src/uu/test/test.md

issue: #4368
This PR contains bellow contents.
- Remove duplicated expressions 22d1880e715ce6e224c19c2cc3e3c2aeaea92822
- Move help strings to markdown file d6366c41eda316cad6b1c1047d97bed9e2b4b078
This command has two util names ( `test` or `[` ). And, the format_usage method replaces {} with a util name. So, we changed `USAGE` as strings that do not contain `{}`.
If there are better ideas, please tell me.
```
$ cargo run -- [ --help
Check file types and compare values.
Usage: target/debug/coreutils [ EXPRESSION
target/debug/coreutils [
[ EXPRESSION ]
[ ]
[ OPTION
Options:
Exit with the status determined by EXPRESSION.
An omitted EXPRESSION defaults to false.  Otherwise,
EXPRESSION is true or false and sets exit status.  It is one …
```

test: move help strings to markdown file

---

src/uu/tail/src/args.rs
src/uu/tail/src/text.rs
tests/by-util/test_tail.rs

Like discussed in #4756 this pr changes usages of `static` global variables to `const` in `tail` and `test_tail`.

'tail': Change static global variables to const

---

Cargo.lock
src/uu/cp/src/cp.rs
src/uucore/Cargo.toml
src/uucore/src/lib/features/fs.rs
src/uucore/src/lib/features/mode.rs
tests/by-util/test_cp.rs
tests/by-util/test_mv.rs

Fix: tests/cp/thru-dangling.sh

cp: fix cp -f f loop when loop is a symlink loop

---

src/uu/mv/src/mv.rs
tests/by-util/test_mv.rs

fix tests/mv/i-5.sh

---

src/uu/cp/src/cp.rs

This PR fixes the issue that when running `cp --help` the "after help" content in `cp.md` is not shown.

cp: fix "after help" output

---

src/uu/mv/mv.md
src/uu/mv/src/mv.rs
tests/by-util/test_mv.rs

This PR ensures that when using `-i -n` and `-n -i` the last argument wins, thus leading to different behavior. A message is shown in the first case, and a prompt in the second case.
Closes #4795

mv: if more than one of -i, -f, -n is specified, only the final one takes effect

---

src/uu/tty/src/tty.rs
src/uu/tty/tty.md

issue: #4368 
`tty --help` outputs following.
```
$ ./target/debug/tty --help
Print the file name of the terminal connected to standard input.
Usage: ./target/debug/tty [OPTION]...
Options:
-s, --silent   print nothing, only return an exit status [aliases: quiet]
```

tty: move help strings to markdown file

---

tests/by-util/test_dd.rs

When running `cargo test --features "dd" --no-default-features`, a `unused imports: 'TESTS_BINARY', 'UCommand'` warning is shown because of a mismatch between the `cfg`-attributes of those imports and the function where they are used. This PR fixes this issue.

dd: fix "unused imports" warning in tests

---

src/uu/mv/Cargo.toml
src/uu/mv/src/mv.rs
src/uucore/src/lib/features/fs.rs
tests/by-util/test_mv.rs

mv: 'mv source hardlink' should fail

---

src/uu/basenc/src/basenc.rs

This PR adds some missing help texts.
Before:
```
Options:
-d, --decode          decode data
-i, --ignore-garbage  when decoding, ignore non-alphabetic characters
-w, --wrap <COLS>     wrap encoded lines after COLS character (default 76, 0 to disable wrapping)
--base64          
--base64url       
--base32          
--base32hex       
--base16          
--base2lsbf       
--base2msbf       
--z85             
-h, --help            Print help
-V, --version         Print version
```
After:
```
Options:
-d, --decode          decode data
-i, --ignore-garbage  when decoding, ignore non-alphabetic characters
-w, --wrap <COLS>     wrap encoded lines after COLS character (default 76, 0 to disable wrapping)
--base64          same as 'base64' program
--base64url       file- and url-safe base64 …
```

basenc: add help texts for options

---

docs/src/extensions.md

This PR describes the use of `=` as a key/value separator in short options with arguments (e.g. `ls -w=80`) as an extension.
Closes #4846

docs: add extension (short options with args)

---

src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

With [libc#2999](https://github.com/rust-lang/libc/pull/2999) merged, we can finally add device numbers support to other platforms:)
1. Add `ls -l` device number support for BSDs and SolarishOS
1. FreeBSD
2. DragonFlyBSD
3. NetBSD
4. OpenBSD
5. Illumos
6. Solaris
For the list in this [comment](https://github.com/uutils/coreutils/issues/2140#issuecomment-1312494378), `Redox` does not have these `major/minor` things(yet, I guess), other platforms are all supported, so we can close #2140.

ls: device number for BSDs and solarishOS

---

src/uu/cp/src/copydir.rs
src/uu/cp/src/cp.rs
tests/by-util/test_cp.rs

cp: preserve permission on -p --parents

---

src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

Before, it failed with
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "-\xE0-foo"', src/uu/ls/src/ls.rs:1932:53
```

ls: when facing an invalid utf-8, don't panic

---

.github/workflows/GnuTests.yml

This pr fixes the location of the coreutils workspace in the `Swatinem/rust-cache` action, so it can cache the correct target directoy in all jobs of the gnu tests workflow.

`ci/gnu tests`: fix Swatinem/rust-cache to use correct workspace

---

.github/workflows/CICD.yml
.github/workflows/FixPR.yml
.github/workflows/GnuTests.yml

This pr speeds up installation of cargo tools in the ci by installing pre-built binaries with `taiki-e/install-action` where possible instead of building them from source with `cargo install`.
Setting up the rust toolchain with `dtolnay/rust-toolchain` simplifies and shortens the installation of the rust toolchain. This action is just used to outsource this setup step, so we don't have to care about it.
Some explicitly set environment variables which are already set by github actions are removed.

`ci`: Improve and speed up setup steps using github actions

---

Cargo.lock
src/uu/yes/Cargo.toml
src/uu/yes/src/yes.rs
tests/by-util/test_yes.rs

Also, tighten the creation of the output buffer.  Rather than copy `"y\n"` 8192 times, or any other input some number of times, it can be doubled in place using `Vec::extend_from_within`.

yes: support non-UTF-8 args

---

src/uu/mktemp/src/mktemp.rs
tests/by-util/test_mktemp.rs

mktemp -t foo.XXXX should create in TMPDIR

---

src/uu/chgrp/src/chgrp.rs
src/uu/chown/src/chown.rs
src/uucore/src/lib/features/perms.rs
tests/by-util/test_chown.rs

This PR modify `chown` to print a message to stdout when the file doesn't exist.
It's a fix for #4767 .
The following cases are implemented:
```
chown -v 0 nf 2> /dev/null
failed to change ownership of 'nf' to 0
$ chown -v user nf
failed to change ownership of 'nf' to user
$ chown -v user:group nf
failed to change ownership of 'nf' to user:group
$ touch f
$ chown -v --reference=f nf
failed to change ownership of 'nf' to user:group
```
To access the owner as specified by the user in the command, I had to modify the signature of the tuple returns by `parse_gid_uid_and_filter` and add a field in the struct `ChownExecutor`.
Note: the first part of the GNU tests/chown/basic is expected to fail (_ownership of 'f' retained as root_) but the rest is not.

fix #4767: `chown -v 0 nf` isn't showing a message 

---

src/uu/mkdir/src/mkdir.rs
tests/by-util/test_mkdir.rs

should fix mkdir/perm.sh
1. default permission created by mkdir is `a=rwx` (0o0777)
2. permission of parent dirs created by -p argument is `=rwx,u+wx`, which is umask modified by `u+wx`

mkdir: set correct permissions on dirs created by -p

---

src/uu/mktemp/src/mktemp.rs
tests/by-util/test_mktemp.rs

This PR ensures that the `TMPDIR` env variable has a higher priority than `-p` when using `-t`.
```
$ TMPDIR=dir_a cargo run mktemp -t -p dir_b foo.XXXX
dir_a/foo.DAXt
```
Closes #4874

mktemp: prioritize TMPDIR over -p when using -t

---

tests/by-util/test_mv.rs

This PR fixes some "consider adding a `;` to the last statement for consistent formatting" clippy warnings.

mv: add missing semicolons to tests

---

src/uu/rm/src/rm.rs
tests/by-util/test_rm.rs

1. allow empty `interactive` arg
2. fix prompt when removing multiple files

fix rm/interactive-always.sh

---

Cargo.lock

This PR bumps the following `crossbeam`-related crates to avoid "yanked crate" warnings from `cargo deny`:
```
crossbeam-channel from 0.5.6 to 0.5.8
crossbeam-epoch from 0.9.12 to 0.9.14
crossbeam-utils from 0.8.13 to 0.8.15
```

Bump crossbeam(-channel, -epoch, -utils) crates

---

tests/by-util/test_mkdir.rs

1. explicitly set umask when testing file mode (https://github.com/uutils/coreutils/pull/4876#issuecomment-1560070035)
2. run tests sequentially since tests that do set umask cause other tests to fail

Mkdir: explicit umask and sequential tests

---

Cargo.lock
deny.toml

This PR bumps the two `rustix` crates we use from `0.36.8` to `0.36.14` and from `0.37.3` to `0.37.7`, and removes an older version of `errno`.

Bump rustix crates

---

Cargo.lock
Cargo.toml
tests/by-util/test_tail.rs

This PR bumps `notify` from `5.1.0` to `5.2.0`, and disables some failing tests on Android.

Bump notify to 5.2.0 and disable tests on android

---

Cargo.lock
deny.toml

This PR bumps the crates `console`, `ctrlc`, `filetime`, `mio`, `parking_lot_core`, and `tempfile` to newer versions to get rid of `windows-sys 0.42.0`. This allows us to introduce `windows-sys 0.48.0`, without having three versions of one crate. Because `tempfile` requires a newer version of `redox_syscall`, I added an exception for it to `deny.toml`.

Bump crates to phase out windows-sys 0.42.0

---

src/uu/uniq/src/uniq.rs

uniq ought to be able to work with files whose names are not UTF-8.
I've also taken the chance to remove some unnecessary `String` allocations.
Additionally, both `open_input_file` and `open_output_file` were returning items with two implie levels of `Box<dyn ...>` that were not necessary.
In the case of `stdin` as input, it was not necessary to wrap `stdin` with a `BufReader`, `StdinLock` implements `BufRead` itself.

uniq: non-UTF-8 file names and fewer copies

---

src/uu/cp/src/cp.rs

Used for example in:
tests/mv/hard-3.sh

cp: Accept --preserve=link

---

Cargo.lock
deny.toml

This PR bumps `windows-targets` from `0.42.1` to `0.42.2` and adds it with its dependencies to `deny.toml`.
The addition to `deny.toml` is done so we can start merging the renovate-PRs that rely on `windows-sys` `0.48.0` (and thus on `windows-targets` `0.48.0`).

Bump windows-targets to 0.42.2 and add it with its dependencies to deny.toml

---

src/uu/mv/src/mv.rs
tests/by-util/test_mv.rs

mv: Show 'skipped' when a file isn't overwriten

---

src/uu/head/src/head.rs

This no longer triggers the `invalid_from_utf8_unchecked` lint. It is also a bit cleaner and no longer requires `unsafe` because `OsString` is not guaranteed to be valid UTF-8.
I noticed the lint here: https://github.com/uutils/coreutils/actions/runs/5134271496/jobs/9238032149?pr=4747
cc @cakebaker

`head`: use `OsStringExt::from_vec` instead of `std::from_utf8_unchecked`

---

Cargo.lock
deny.toml

This PR bumps `io-lifetimes` from `1.0.5` to `1.0.11` and removes it from the skip list in `deny.toml`. It also fixes some outdated comments in that file.

Bump io-lifetimes and remove it from the skip list in deny.toml

---

tests/by-util/test_cp.rs

This PR fixes the warnings from the [assertions_on_constants](https://rust-lang.github.io/rust-clippy/master/index.html#assertions_on_constants) lint and replaces all `assert!(false)` with `panic!`

cp: replace assert!(false) with panic!()

---

src/uu/more/src/more.rs
tests/by-util/test_more.rs

Related to #2320 
The [match option](https://github.com/uutils/coreutils/pull/4914/files#diff-bf8028446467cb967cdae6a73043d11dba3b1f97663ccf53f6e0c7a3eda2f474R65) assigns a value to the `lines` variable based on the provided options.
It prioritizes the value obtained from the `--lines` option over the `--number` option.
If a value of 0 is given for `lines`, it will fallback to using the terminal size.

more: implement arguments -n/--lines and --number

---

src/uu/cp/src/cp.rs
tests/by-util/test_cp.rs

prevents --preserve to eat the next argument when no value is passed.
default value for --preserve is set to mode,ownership,timestamps
before the patch:
cp --preserve foo bar
error: invalid value 'foo' for '--preserve [<ATTR_LIST>...]'
[possible values: mode, ownership, timestamps, context, link, links, xattr, all]

cp: makes --preserve requires =

---

.github/workflows/CICD.yml
.github/workflows/freebsd.yml

Reverts uutils/coreutils#4939
Release of sccache 0.5.3 probably fixed the issue

Revert "specify the sccache version "

---

src/uu/pwd/src/pwd.rs
tests/by-util/test_pwd.rs

pwd: Fix #4855
Based on testing with GNU's pwd, it seems like the -P flag should take precedence over the use of the POSIXLY_CORRECT flag.

pwd: Allow -P flag precedence over POSIXLY_CORRECT

---

Cargo.lock
Cargo.toml
tests/by-util/test_chgrp.rs
tests/by-util/test_chown.rs
tests/by-util/test_date.rs
tests/by-util/test_install.rs

This PR removes the unmaintained `users` crate and uses the same functionality from `uucore::process` instead.
Closes #4941

Remove users crate

---

src/uu/tsort/src/tsort.rs
tests/by-util/test_tsort.rs

Using HashMap and HashSet give a valid topological sort, but the output will change randomly at each run.
BTree based structures will guarantee that the output is always ordered in the same way.
This also makes the ouptut similar to the output of the C version of the tools, on which some applications rely.
An example of application that rely on this is the `initramfs-update` program on Debian that uses `tsort` to create the order of hooks execution. The floating nodes still need to be executed alphabetically to avoid having the `busybox` version of some tools in `initramfs` instead of the full versions. See [this issue](https://gitlab.apertis.org/infrastructure/apertis-issues/-/issues/334#note_100371) on Apertis.
Although the issue could be fixed in `initramfs-update`, other …

tsort: Switch to BTreeMap and BTreeSet

---

src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

This option was introduced in some more recent versions of GNU coreutils (around 2021-4-11) which lets you sort by filename widths .
One oddity of this particular option in GNU coreutils is that unlike other sort options, this one does not have a shorthand form flag so I have implemented it similarly as such here.

ls: Implement new sort option --sort=width 

---

tests/by-util/test_mkdir.rs

This PR removes all `TEST_DIR<x>` consts to improve the readability of the tests.

mkdir: remove TEST_DIR<x> consts in tests

---

Cargo.lock

This PR bumps `getrandom` from `0.2.8` to `0.2.9` to hopefully fix the compilation error in https://github.com/uutils/coreutils/pull/4945

Bump getrandom from 0.2.8 to 0.2.9

---

Cargo.lock
Cargo.toml
deny.toml
src/uu/date/Cargo.toml
src/uu/date/src/date.rs

This PR replaces `humantime_to_duration` with its successor `parse_datetime`. It also removes `humantime_to_duration` from the skip list in `deny.toml` because with this update we no longer use two versions of `humantime_to_duration`.

date: switch to parse_datetime

---

src/uu/mv/src/mv.rs
src/uucore/src/lib/features/fs.rs
tests/by-util/test_mv.rs

In normal GNU mv behaviour, moving a symlink to a file with target as file should fail which this one does currently, but vice versa must actually succeed. I have slightly changed the approach of mv so that when checking for same link, only the source path's symbolic link is resolved fully while target is taken as is which seems to fix some edge cases.
I am a bit unsure of how to handle this on Windows however.

mv: fix into-self-2.sh test

---

.github/FUNDING.yml

The sponsor will be used for improving the CI machines on github
Doc:
https://docs.github.com/fr/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

Create a FUNDING.yml file

---

src/uu/mv/src/mv.rs
src/uucore/src/lib/features/fs.rs
tests/by-util/test_mv.rs

My previous PR missed an extremely special case of moving onto a hardlink to symbolic link. So, the correct way is to first check immediate metadata for hard link before checking for symbolic link. In short, the previous PR I put may have caused this test to regress silently, which was already not passing
Previously, the only reason this test was failing was due to the --backup option part of the test not passing, which I have fixed as well. 
This PR should fix tests/mv/symlink-onto-hardlink-to-self.sh keeping all else intact.

mv: Fix for tests/mv/symlink-onto-hardlink-to-self.sh

---

src/uu/sync/src/sync.rs
tests/by-util/test_sync.rs

sync: fix error msg

---

deny.toml

This PR adds `hashbrown` to the skip list in `deny.toml`. This is done to unblock https://github.com/uutils/coreutils/pull/4825, where `cargo-deny` currently fails with a "found 2 duplicate entries for crate 'hashbrown'" error.

deny.toml: add hashbrown to skip list

---

src/uu/od/src/parse_nrofbytes.rs
tests/by-util/test_od.rs

This should fix #4981.
This is my first contribution in Rust and I just started learning it today, so pardon me if I missed something, do let me know and I will fix it promptly!
Special thanks to @tertsdiepraam for finding the bug before I even started learning Rust, thus saving me a bunch of time :smile:

od: fix parsing of hex input ending with `E`

---

src/uu/nl/src/nl.rs

This PR implements `Default` for `Settings`. It also replaces `static` with `const`, and removes the unnecessary `spell-checker:ignore` line.

nl: implement Default for Settings

---

src/uu/touch/src/touch.rs

This PR renames `CURRENT` to `TIMESTAMP` because `CURRENT` is the wrong name for the `-t` argument:
```
-t <STAMP>              use [[CC]YY]MMDDhhmm[.ss] instead of the current time
```
The PR also removes some unused words from the `spell-checker:ignore` line.

touch: rename CURRENT to TIMESTAMP

---

docs/src/extensions.md

This PR documents `-t`/`--terminator` from `seq` as an extension.

docs: add seq to extensions; add some backticks

---

tests/by-util/test_cp.rs

This PR fixes an "unused variable" warning on Windows I introduced with my previous PR https://github.com/uutils/coreutils/pull/5014 (I was too slow to fix it there)

cp: fix "unused variable" warning on Windows

---

src/uu/seq/src/seq.rs
tests/by-util/test_seq.rs

This PR renames the long version of the `-w` argument from `--widths` to `--equal-width` to be compatible with GNU seq.

seq: rename "--widths" to "--equal-width"

---

src/uu/hashsum/src/hashsum.rs

This program matches the binary name to determine which algorithm to use. On Windows, `file_name()` was matching against a string with `.exe`, causing binaries like `sha256sum.exe` to not properly detect the algorithm.
By using `file_stem()`, we exclude the `.exe` from matching, achieving similar and correct behavior on Windows.

hashsum: use file_stem() instead of file_name()

---

util/build-gnu.sh

For a new contributor, the message given by `utils/build-gnu.sh` is
fairly confusing - it starts with several lines of noise (showing
variables that are set in the script) followed by an error about missing
"GNU" and a `git` command string.
This PR changes the script to explicitly instruct the user to run
the `git clone` command. Since the GNU coreutils repository is probably
missing for new developers, this error is shown if the repository is
missing without including any VARIABLE=value lines that are not actionable
yet.

util/build-gnu.sh: Improve error message when missing GNU Coreutils repository

---

src/uu/more/src/more.rs
tests/by-util/test_more.rs

Related to #2320 
This implements the arguments `plain` and `from-line`.
The `plain` option does nothing because, according to the man page of `more`, it is written that this option is silently ignored as backwards compatibility.
This also fixes two bugs. 
The first one occurs when multiple files are given, and a file takes one display to output its content. Now, it displays the next file message if there is another file and only stops if there is none other.
The second one happens with the `squeeze` option. When multiple files are given and the end of the file takes less than a full terminal size to display, it should not start printing the next file.

More implement arguments plain and from line

---

src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

The metadata are not used but it permits to use the same path as the long format to ensure we return 1 on invalid symlinks when ls is invoked with ls -L -Z
should solve https://github.com/uutils/coreutils/issues/2928

ls: force fetching metadata when called with -L -Z

---

src/uu/tail/src/args.rs
src/uu/tail/src/follow/watch.rs
src/uu/tail/src/paths.rs
tests/by-util/test_tail.rs

This pr refactors mainly the `Input::from` method and changes inputs in `Settings` from a `VecDeque` to a `Vec`.
There is no need for `Settings::inputs` being a `VecDeque` anymore and `Vec` is a little bit more efficient. In `Input::from`, unpacking `AsRef<OsString>` with `.as_ref()` just once is also a bit more efficient. Same with the comparison of `OsStr` with another `OsStr` instead of `Path`. Parsing the input arguments to a `String` and then back to an `OsStr` is unnecessary, since we can get the inputs raw as `OsStr` from clap to pass them to `Input::from`.
Note this pr also includes a small fix. When file headers are printed in verbose mode, the output for stdin should be equal on all platforms: `==> standard input <==`. Before this change the output for non unix systems was `==> …

`tail`: Refactor `paths::Input::from` and `Settings::inputs`

---

Cargo.lock
Cargo.toml
src/uu/touch/Cargo.toml
src/uu/touch/src/touch.rs

This PR cherry-picks the necessary commits from https://github.com/uutils/coreutils/pull/4974 to switch from `humantime_to_duration` to `parse_datetime`. This should fix the "dependencies: 1 of 14 outdated" badge.

touch: use parse_datetime instead of humantime_to_duration

---

tests/by-util/test_df.rs

This PR disables the four tests mentioned in https://github.com/uutils/coreutils/issues/5015 on Windows.

df: disable failing tests on Windows

---

src/uu/numfmt/src/numfmt.rs

`clap` automatically shows a list of possible values for an option in the help output, so it is unnecessary that we list the same values again. This PR removes this duplicate information.
```
// before the change
--round <METHOD>     use METHOD for rounding when scaling; METHOD can be: up,down, from-zero, towards-zero, nearest [default: from-zero] [possible values:
up, down, from-zero, towards-zero, nearest]
// after the change
--round <METHOD>     use METHOD for rounding when scaling [default: from-zero] [possible values: up, down, from-zero, towards-zero, nearest]
```

numfmt: remove duplicate info from help output

---

src/uu/nl/src/helper.rs
src/uu/nl/src/nl.rs
tests/by-util/test_nl.rs

This PR turns `-p`/`--no-renumber` into a flag to be compatible with GNU `nl`.

nl: make -p/--no-renumber a flag

---

Cargo.lock
deny.toml

This PR bumps `hermit-abi` from `0.3.1` to `0.3.2` because `0.3.1` got yanked. And by bumping `num_cpus` from `1.14.0` to `1.16.0` I was able to get rid of an old version of `hermit-abi` and thus I could remove it from `deny.toml`.

Bump hermit-abi and num_cpus

---

src/uu/date/src/date.rs
src/uucore/src/lib/lib.rs
src/uucore/src/lib/parser.rs
src/uucore/src/lib/parser/shortcut_value_parser.rs

This PR introduces `ShortcutValueParser`, a custom value parser for clap that not only recognizes the exact values from a list of allowed values but also shortcuts of them (for example, `h`, `ho`, `hou`, are recognized as `hour`).
Closes #4744

date: use custom value parser

---

src/uu/split/src/split.rs
tests/by-util/test_split.rs

Matches what is done in tests/split/fail.sh
(still doesn't work)

split: reject some invalid values

---

Cargo.lock

This PR bumps `iana-time-zone-haiku` from `0.1.1` to `0.1.2` which allows us to get rid of eight dependencies.

Bump iana-time-zone-haiku from 0.1.1 to 0.1.2

---

Cargo.lock
Cargo.toml
deny.toml

This PR bumps `syn` from `1.0.103` to `1.0.109` and adds it to the skip list in `deny.toml` to resolve the `cargo-deny` error in https://github.com/uutils/coreutils/pull/5039. And while looking at that PR, I noticed we can use `{ workspace = true }` for `rstest` in `Cargo.toml`.

Bump syn and add it to skip list

---

.gitignore
README.md
docs/src/oranda.css
oranda.json

[oranda](https://opensource.axo.dev/oranda/) is a new tool by [axo](https://axo.dev/), which can generate pretty websites for projects, based on info from `Cargo.toml` and GitHub. Here is the blog post where they explain it: https://blog.axo.dev/2023/06/oranda.
I think it would be nice to replace [this page](https://uutils.github.io/) with the generated website. It contains a link to the docs, funding and changelog. It also renders the mdbook documentation with the same style as the rest of the website. It can also show installation options, but currently, that feature is not yet flexible enough for us. We could open some issues on their repo to discuss what we would need (they're really friendly).
We might need to either clean up the README or make a separate markdown document as landing …

Initial oranda setup

---

src/uu/stty/src/stty.rs

Argument parsing for this exists, but the option doesn't change output in any way. Finish the support.
Closes #3862.
I haven't found any documentation on the format of this or looked at any code, but it would appear to be simple hex printing of some (not all) struct termios fields:
````
$ cat termiostest.c
#include <stdio.h>
#include <termios.h>
int main() {
struct termios t;
tcgetattr(0, &t);
while (1)
;
}
$ gcc -g termiostest.c
$ gdb ./a.out
(gdb) run
(gdb) p/x t
$1 = {c_iflag = 0x100, c_oflag = 0x5, c_cflag = 0xbf, c_lflag = 0x8a3b, c_line = 0x0, c_cc = {0x3, 0x1c, 0x7f, 0x15, 0x4, 0x0, 0x1, 0x0, 0x11, 0x13, 0x1a, 0x0, 0x12, 0xf, 0x17, 0x16, 0x0 <repeats 16 times>},
c_ispeed = 0xf, c_ospeed = 0xf}
$ stty --save
100:5:bf:8a3b:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0 …
```

stty: Finish '--save' support

---

src/uu/stty/src/stty.rs

stty: Support setting baud rate

---

src/uu/touch/src/touch.rs
tests/by-util/test_touch.rs

This PR adds `modify` and `mtime` to the list of possible values for `--time`.

touch: accept "modify" & "mtime" for --time arg

---

.github/workflows/FixPR.yml

Let see if it helps.
Based on https://github.com/dtolnay/rust-toolchain#toolchain-expressions
Attempts to fix https://github.com/uutils/coreutils/issues/5003
Tested on my fork: https://github.com/piotrkwiecinski/coreutils/actions/runs/5494245033

fix: fixpr.yml unrecognized named-value: 'steps'

---

src/uucore/src/lib/mods/version_cmp.rs
tests/by-util/test_ls.rs
tests/by-util/test_sort.rs

should fix `tests/misc/sort-version.sh`

uucore: leading zeros are ignored in version compare

---

src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

#5025
I've fixed `--l` option to be a short cut for `--literal`.

ls: --l should output the same as --literal

---

src/uu/seq/src/error.rs
src/uu/seq/src/seq.rs
tests/by-util/test_seq.rs

This is in reference to issue #4749, where just running `seq` ends up panicking. I have added a new `NoArguments` error, and refactored the display formatting, in order to match GNU messages.

fix: seq panic on no arguments #4749

---

src/uu/nl/src/helper.rs
src/uu/nl/src/nl.rs
tests/by-util/test_nl.rs

This PR uses `clap`'s value parser to handle `-n`/`--number-format`.

nl: use value parser for "--number-format"

---

src/uu/nl/src/helper.rs
src/uu/nl/src/nl.rs
tests/by-util/test_nl.rs

GNU `nl` shows an "invalid line number field width" error if `-w`/`--number-width` is `0` whereas uutils `nl` doesn't fail. This PR fixes this issue.

nl: show error if --number-width is zero

---

src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

This change will clamp --width value to u16::MAX if the number passed is too large. The present behaviour results in invalid line width error. This lets gnu/tests/ls/w-option.sh progress a bit further till the last test.
The actual correct behaviour would have been to set the limit to u64::MAX as per the GNU test but all the logic related to formatting seems to be heavily reliant on u16 values, including one crate terminal_size and that would probably take a while for me to sift through. In all practical cases, this should be indistinguishable unless you are printing on a billboard maybe.

ls: Limit value of --width to maximum value if overflowing

---

src/uu/nl/src/helper.rs
tests/by-util/test_nl.rs

This PR adds a test for `-s`/`--number-separator` and replaces the `match` to handle the value of this argument with an `if let` for better readability.

nl: add test for "--number-separator"

---

Cargo.lock

This PR bumps `pretty_assertions` from `1.3.0` to `1.4.0` which removes two dependencies.

Bump pretty_assertions from 1.3.0 to 1.4.0

---

deny.toml

This PR removes the MPL license from the allow list in `deny.toml`. The change comes from https://github.com/uutils/coreutils/pull/4974 (which is unlikely to be merged in its current form), and I set that PR's author as the author.

deny.toml: remove MPL license from allow list

---

docs/book.toml

There is a GitHub icon in the top right of the [documentation page](https://uutils.github.io/user).
This links to Cargo repository, which make it weird for contributors to the `uutils/coreutils` documentation, so this PR updates this link to point to this repository instead.

docs: github repo link related to uutils/coreutils

---

.github/workflows/CICD.yml
src/uu/dd/src/progress.rs
src/uu/df/src/df.rs
src/uu/df/src/filesystem.rs
src/uu/df/src/table.rs
src/uu/head/src/head.rs
src/uu/sort/src/numeric_str_cmp.rs
src/uu/tail/src/args.rs

This PR adds the pedantic [default_trait_access](https://rust-lang.github.io/rust-clippy/master/index.html#/default_trait_access) lint to the CICD and fixes its warnings.

ci: add default_trait_access lint and fix its warnings

---

docs/src/installation.md

This PR updates the Arch Package link in the documentation, because it is currently pointing to a 404 page. :smile:

docs: fix broken Arch package link

---

src/uu/nl/src/helper.rs
src/uu/nl/src/nl.rs
tests/by-util/test_nl.rs

This PR allows negative values for `-i`/`--line-increment` and `-v`/`--starting-line-number` to be compatible with GNU `nl`.
To keep the PR focused on the input I didn't address any indentation issues in the output. This will be addressed in a future PR.

nl: allow negative values for --line-increment and --starting-line-number

---

tests/by-util/test_factor.rs

small improvements when creating vectors

uucore: provide capacity for vectors

---

.github/workflows/CheckScripts.yml

Hi,
I've added a new GitHub action workflow to resolve https://github.com/uutils/coreutils/issues/4752. It utilizes `shellcheck` and `shfmt` tools to perform checks and formatting on our shell scripts during a push to the main branch or the creation of a PR.
As it stands, I would appreciate some input on the following aspects that may require further discussion or decision: 
1. Unification of Shell Interpreters: It appears that some of our scripts utilize #!/bin/sh shebang, yet contain certain statements that do not adhere to the POSIX sh standard, as pointed out by shellcheck. I have attached an example of such an occurrence in the CI output from my forked repo here:  [ShellScript/Check](https://github.com/starccy/coreutils/actions/runs/5539084094/jobs/10109672892). As a temporary …

ci: Add a new workflow to check and format shell scripts in `util` dir

---

util/analyze-gnu-results.sh
util/build-gnu.sh
util/run-gnu-test.sh
util/update-version.sh

Some discussion is already in this thread: https://github.com/uutils/coreutils/pull/5077

"style(util): fix/format scripts to meet the `shellcheck`/`shfmt` rules"

---

src/uu/stty/src/flags.rs
src/uu/stty/src/stty.rs

stty: Implement printing assignment of control chars

---

src/uu/cat/src/cat.rs

This PR removes `--t`, the long version of `-t`, because GNU `cat` doesn't have a long version of `-t`.

cat: remove --t

---

src/uu/nl/src/nl.rs
tests/by-util/test_nl.rs

This PR fixes the indentation of line numbers by adapting the calculation of the line number lengths to work with negative line numbers (introduced in https://github.com/uutils/coreutils/pull/5078).
```
// before change
$ printf "a\nb\nc" | cargo run nl -i10 -v-19
-19  a
-9   b
1    c
// after change
$ printf "a\nb\nc" | cargo run nl -i10 -v-19
-19  a
-9  b
1  c
```

nl: fix calculation of line number lengths

---

.github/workflows/CICD.yml
GNUmakefile

make: uninstall man pages

---

src/uu/nl/src/nl.rs
tests/by-util/test_nl.rs

This PR fixes the zero padding of negative line numbers when using `-nrz`/`--number-format=rz`. It also moves the logic for formatting line numbers to its own function.
```
// before change
$ echo "test" | cargo run nl -v-10 --number-format=rz
000-10  test
// after change
$ echo "test" | cargo run nl -v-10 --number-format=rz
-00010  test
```
This PR probably conflicts with #5091.

nl: fix zero padding of negative line numbers

---

src/uu/csplit/src/csplit.rs

This PR fixes a warning from the pedantic [explicit_into_iter_loop](https://rust-lang.github.io/rust-clippy/master/index.html#/explicit_into_iter_loop) lint.

csplit: remove explicit "into_iter()"

---

src/uu/mktemp/src/mktemp.rs
tests/by-util/test_mktemp.rs

Fixes #3454
This implementation more closely matches the behavior of GNU mktemp. Specifically, if using the short-form `-p`, then DIR is required, and if using the long form `--tmpdir` then DIR is optional, but if provided, must use the `--tmpdir=DIR` form (not `--tempdir DIR`), so that there is no ambiguity with also passing a TEMPLATE.
The downside to this implementation is we are now introducing a new workaround for https://github.com/clap-rs/clap/issues/4702 where we use separate calls to `.arg()` for the short `-p` and the long `--tmpdir`, which results in a less than ideal output for `--help`.

Require = for --tmpdir in mktemp

---

Cargo.lock
deny.toml

This PR bumps `unicode-linebreak` from `0.1.4` to `0.1.5` to remove two dependencies. This makes it possible to remove `hashbrown` from the skip list in `deny.toml`.

Bump unicode-linebreak from 0.1.4 to 0.1.5

---

util/build-gnu.sh

Fails on Mac otherwise with:
```
Compiling crossterm v0.25.0
error: couldn't read /Users/sylvestre/dev/debian/coreutils/target/release/build/fts-sys-5da7dc1e06092d06/out/fts-sys.rs: No such file or directory (os error 2)
--> /Users/sylvestre/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fts-sys-0.2.2/src/lib.rs:30:1
|
30 | include!(concat!(env!("OUT_DIR"), "/fts-sys.rs"));
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: this error originates in the macro `include` (in Nightly builds, run with -Z macro-backtrace for more info)
error: could not compile `fts-sys` (lib) due to previous error
```

only set SELINUX_ENABLED=1 on Linux

---

src/uu/nl/src/helper.rs
src/uu/nl/src/nl.rs
tests/by-util/test_nl.rs

GNU `nl` shows an "invalid line number of blank lines" error if `-l`/`--join-blank-lines` is `0` whereas uutils `nl` doesn't fail. This PR fixes this issue. Plus adds a test for when an invalid value is specified for `-l`/`--join-blank-lines`.

nl: show error if --join-blank-lines is zero

---

src/uu/nl/src/helper.rs
src/uu/nl/src/nl.rs

This PR shortens the variants of the `NumberingStyle` enum by removing the `NumberFor` prefix and replacing `RegularExpression` with `Regex`.

nl: shorten variants of NumberingStyle enum

---

src/uu/mv/src/mv.rs
src/uu/rmdir/src/rmdir.rs

not sure why clippy isn't showing any warnings for [comparison_to_empty](https://rust-lang.github.io/rust-clippy/master/index.html#/comparison_to_empty)

use is_empty()

---

src/uucore/src/lib/features/fs.rs
src/uucore/src/lib/lib.rs

This PR adds documentation for the following macros -
- `bin` in src/uucore/src/lib/lib.rs
- `has` in src/uucore/src/lib/features/fs.rs
Fixes #5067

docs(bin,has): add docstrings for macros bin and has

---

deny.toml

This PR adds `bitflags` to the skip list in `deny.toml`. It's necessary for https://github.com/uutils/coreutils/pull/5133

deny.toml: add bitflags to skip list

---

Cargo.lock
deny.toml

This PR bumps `filetime` from `0.2.20` to `0.2.22` and `parking_lot_core` from `0.9.7` to `0.9.8` in order to remove `redox_syscall` from the skip list in `deny.toml`.

deny.toml: remove redox_syscall from skip list

---

src/uu/seq/src/seq.rs

While reviewing https://github.com/uutils/coreutils/pull/5136 I noticed the unused `_is_first_iteration` param in `write_value_float()`. This PR removes it.

seq: remove unused param from write_value_float()

---

Cargo.lock
deny.toml

This PR bumps `aho-corasick` from `0.7.19` to `0.7.20` and from `1.0.1` to `1.0.2`.

Bump aho-corasick crates

---

src/uu/stat/src/stat.rs
tests/by-util/test_stat.rs

Currently, stat does not complain about it but GNU stat does not allow this.
This PR also fixes the test case tests/misc/stat-hyphen.sh which tests exactly this usage.

stat: Output error when - and -f are used together.

---

src/uu/mv/src/mv.rs

This PR removes an unnecessary OR in a condition. It can be removed because the removed condition appears again a few lines below as a condition on its own, with the same return value.

mv: remove unnecessary OR in condition

---

src/uu/nl/src/nl.rs
tests/by-util/test_nl.rs

This PR fixes the output of `-b`/`--body-numbering`, `-f`/`--footer-numbering`, and `-h`/`--header-numbering`. It also adds support for `-b`/`--body-numbering` if there is no body delimiter.

nl: fix output of numbering styles

---

src/uu/rm/src/rm.rs

This PR applies two refactorings to `prompt_file()` to simplify the function:
- extract a `prompt_dir()` function
- replace an `if` with a `match`

rm: refactor prompt_file()

---

src/uucore/src/lib/parser/shortcut_value_parser.rs

This PR fixes a bug in `ShortcutValueParser`. Currently, if a provided value is ambiguous but a direct match of a possible value, an error is shown. With the fix, the matched value is returned.

uucore: don't show error for ambiguous value

---

src/uu/nl/src/nl.rs
tests/by-util/test_nl.rs

This PR re-adds the functionality of `-p`/`--no-renumber` I forgot to add in https://github.com/uutils/coreutils/pull/5131

nl: re-add handling for -p/--no-renumber

---

src/uu/fmt/src/fmt.rs
tests/by-util/test_fmt.rs

fix #5150 
Changed the confirmation method from get_flag to contains_id. And added several tests.

fmt: fix panic on width argument

---

Cargo.lock

This PR undoes #5161 and downgrades `windows-targets` from `0.48.2` to `0.48.0` because it seems to be the cause for the failing "CICD / Code Coverage" test on Windows.

Downgrade windows-targets from 0.48.2 to 0.48.0

---

Cargo.lock
deny.toml

This PR bumps `cpp` from `0.5.8` to `0.5.9` which allows us to remove `aho-corasick` from the skip list in `deny.toml`. It also bumps `aho-corasick` from `1.0.2` to `1.0.4`.

Bump cpp to remove aho-corasick from skip list in deny.toml

---

src/uu/nl/src/helper.rs
src/uu/nl/src/nl.rs
tests/by-util/test_nl.rs

This PR implements `TryFrom<String>` for `NumberingStyle` to replace the `parse_style` function.

nl: implement TryFrom<&str> for NumberingStyle

---

src/uu/cp/src/copydir.rs
src/uu/cp/src/cp.rs

Part of https://github.com/uutils/coreutils/issues/5088.
I've removed the `Source`, `SourceSlice`, `Target` and `TargetSlice` type aliases, because I think those obfuscate the public API. I want to make it as easy as possible for the nushell people to understand how to use our types and functions, without having to dive into the source code. For the same reason, I've documented every field of the `Options` struct with the arguments that change the behavior. Various other docstrings are added or improved too.
~While the `Attributes` struct is `pub`, nu won't be able to construct it yet. We'll have to discuss whether they want to do their own parsing there or that we should do it (i.e. should we make all the fields `pub` or should we provide some functions to set the values).~
`Attributes` …

`cp`: make more types public and add more documentation (for nushell)

---

src/uu/nl/src/nl.rs
tests/by-util/test_nl.rs

This PR shows an error message if the line number gets too high or too low.

nl: handle line number overflow

---

Cargo.toml

I noticed in https://uutils.github.io/coreutils/book/platforms.html that `hostid` was not included in `unix` by default. Therefore, many people will probably have coreutils installed without `hostid`. Since, `hostid` is at least supported on Linux, Mac and FreeBSD, I think it makes sense to include it by default.

`Cargo.toml`: add `feat_require_unix_hostid` to `feat_os_unix`

---

.github/workflows/CICD.yml
fuzz/Cargo.toml
fuzz/fuzz_targets/fuzz_test.rs

Not ideal as it is generating a lot of incorrect code but a start

Fuzz the test command

---

tests/by-util/test_chown.rs

This PR removes some duplication by turning nine functions into three functions.

chown: remove some duplication in tests

---

docs/src/installation.md

I don't quite understand why people would want to install uutils with conda, but apparently it's possible 😄
See: https://anaconda.org/conda-forge/uutils-coreutils
I can't add a badge for it, because conda is not supported by repology, so I just added a simple link.

docs: add conda installer

---

src/uucore/src/lib/lib.rs
src/uucore_procs/src/lib.rs

This PR removes the author copyright notices from two files missed by https://github.com/uutils/coreutils/pull/5184 and https://github.com/uutils/coreutils/pull/5197

Remove the author copyright notices

---

.vscode/cspell.dictionaries/shell.wordlist.txt
src/uu/rm/BENCHMARKING.md
src/uu/rm/benchmark.sh

Add benchmarking script and guide for `rm`, mostly copied from `ls` benchmarking guide. Tested `rm` using `jwalk` instead of `walkdir`, and saw a slight performance regression, if any change.

Add benchmarking for `rm`

---

src/uu/comm/src/comm.rs
src/uucore/src/lib/lib.rs

This PR fixes some warnings from the pedantic [bool_to_int_with_if](https://rust-lang.github.io/rust-clippy/master/index.html#/bool_to_int_with_if) lint.

uucore,comm: fix warnings from bool_to_int_with_if

---

src/uu/dd/src/parseargs.rs
src/uucore/src/lib/parser/parse_size.rs

This PR fixes warnings from the pedantic [unused_self](https://rust-lang.github.io/rust-clippy/master/index.html#/unused_self) lint by turning some instance functions into associated functions.

parse_size,dd: turn instance fns to associated fns

---

src/uu/cp/src/cp.rs

This allows other projects to construct values for these types which in turn allows them to construct `Options` and call `copy`.
This is implemented at the request of nushell.
Sidenote: we should set up tests for the API as well. This would've been caught if I had made a test trying to call the `copy` function.

`cp`: re-export `uucore::{BackupMode, UpdateMode}`

---

src/uu/split/src/split.rs
tests/by-util/test_split.rs

Short variants of numeric and hex suffixes now act as flags with value forced to 0
Long variants work without value (default 0) as well as with value (equal sign is enforced)
Any combination of numeric and/or hex suffixes in any order is allowed with last one winning
Short variants can be combined together like `split -dxen 4 file`
Tests added to cover changes and verified against GNU `split` to match behavior
Fixes #5171

split: better handle numeric and hex suffixes, short and long, with and without values

---

oranda.json

Our website doesn't have a changelog due to a misconfiguration in oranda. See https://github.com/axodotdev/oranda/issues/611
This fixes the config and brings back our beautiful and extensive changelog :)

website: fix changelog config

---

src/uucore/Cargo.toml

This PR makes the `dunce` dependency optional.

uucore: make "dunce" optional

---

src/uu/factor/src/cli.rs
tests/by-util/test_factor.rs

Should fix this line in the GNU tests:
```
yes 1 | factor > /dev/full
```
which prints a **lot** of lines in the logs right now. (To be exact, 617,310 lines)
I've also removed `factors_buffer`, which was originally added to ensure only full lines are being written. However, in my testing, the tests for that did not break (on my machine), so I figured all was good.

`factor`: short circuit on write error, but not on parse error

---

src/uu/cp/src/cp.rs

Small break from my break to fix an issue for nushell :)
The progress bar sometimes does not show up if the `cp` itself is too fast for it to draw, or something like that. The `finish` method draws the progress bar one last time before exiting, so we get a full error bar at the end.
Context: https://github.com/nushell/nushell/pull/10097#issuecomment-1703865381

`cp`: finish progress bar to make it always show up

---

.clippy.toml
.github/workflows/CICD.yml
Cargo.toml
README.md
tests/by-util/test_split.rs

This PR bumps the MSRV to `1.70` and fixes a Clippy warning in a test.

Bump MSRV to 1.70

---

src/uu/wc/src/wc.rs

This PR fixes a todo by using Rust's `ilog10` function and removing our custom `ilog10` implementation.

wc: use Rust's ilog10(), remove custom ilog10 fn

---

src/uu/yes/src/yes.rs

This PR fixes a todo by using `let`/`else` to simplify an expression.

yes: use let/else to fix todo

---

src/uu/cp/src/cp.rs
tests/by-util/test_cp.rs

Hi
Currently,
GNU :
```
>cp a:
`missing destination file operand after a
>cp a
#nothing
```
With this fix, we match the  behavior
```
>cp a
missing destination file operand after a

cp: Error out if cp only contains source

---

deny.toml

This PR adds `redox_syscall` to the skip list in `deny.toml` in order to be able to merge https://github.com/uutils/coreutils/pull/5262

deny.toml: add redox_syscall to skip list

---

Cargo.lock
Cargo.toml
src/uu/stty/src/stty.rs

This PR bumps `nix` from `0.26.2` to `0.27.1` and `ctrlc` from `3.4.0` to `3.4.1`. And it fixes two compilation errors in `stty` because `nix` changed the function signatures of `tcgetattr` and `tcsetattr`.

Bump nix & ctrlc, adapt stty to nix API changes

---

deny.toml

This PR removes `constant_time_eq` from the skip list in `deny.toml` because of https://github.com/uutils/coreutils/pull/5266

deny.toml: remove constant_time_eq from skip list

---

src/uu/ls/src/ls.rs

This PR uses `std::cell::OnceCell` instead of `once_cell::unsync::OnceCell`.

ls: use OnceCell from std instead of once_cell

---

.github/workflows/CICD.yml

`markdownlint-cli2-action` deprecated the `command` input and so this PR replaces it with the `fix` input. See also https://github.com/marketplace/actions/markdownlint-cli2-action#command-optional

ci: replace deprecated "command" with "fix"

---

Cargo.lock
Cargo.toml
src/uu/touch/src/touch.rs
tests/by-util/test_touch.rs

This PR bumps `chrono` from `0.4.28` to `0.4.30` and fixes in `touch` the warnings caused by the deprecation of `chrono::TimeZone::datetime_from_str`.

Bump chrono and fix deprecation warnings in touch

---

src/uu/split/src/split.rs
tests/by-util/test_split.rs

The broken pipe error is not handled in the case of the round robin strategy (typically used with --filter).
Align to the other strategies to silence that error in that use case too.
fixes #5191

split: catch broken pipe error for round robin strategy

---

.github/workflows/CICD.yml
.github/workflows/GnuTests.yml

Reverts uutils/coreutils#5273 because they tagged the version prematurely, see https://github.com/codecov/codecov-action/issues/1089

Revert "chore(deps): update codecov/codecov-action action to v4"

---

src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

switching to match and handle the error
Will help with tests/ls/stat-failed.sh

ls -l: show an error when symlink not readable

---

deny.toml

This PR adds `terminal_size` to the skip list in `deny.toml` to be able to merge https://github.com/uutils/coreutils/pull/5275

deny.toml: add terminal_size to skip list

---

src/uu/ls/src/ls.rs

This hopefully will make this cade a little les cryptic
reponding to issue #5282

ls.rs: changed variable name dfn to display_file_content responding to #5282

---

tests/by-util/test_ls.rs

This PR fixes a test that fails if `/tmp` uses `tmpfs`. The test fails because it assumes a size of 4096 bytes for a newly created directory and this is not the case when using `tmpfs`.

ls: fix test which fails if /tmp uses tmpfs

---

src/uu/relpath/src/relpath.rs
tests/by-util/test_relpath.rs

This PR shows a (clap) error message if no argument is provided.
Fixes #5300

relpath: show error if no argument provided

---

src/uu/nl/src/nl.rs
tests/by-util/test_nl.rs

So far the line number and `consecutive_empty_lines` (used for `--join-blank-lines`) got reset for each file. This PR removes this reset and makes them work over multiple files.

nl: make line number and --join-blank-lines work over multiple files

---

.vscode/cspell.dictionaries/acronyms+names.wordlist.txt
src/uu/rm/src/rm.rs

Made `Options`, `InteractiveMode`, and the `remove` function public and added documentation for them. This is an attempt at implementing #5294.
`rm` options are much simpler compared to `cp`, so I just made them public.  I am unsure if `OPT_*` constants should be made public too.
Additionally, I couldn't figure out what `InteractiveMode::PromptProtected` does, as it doesn't seem to be used anywhere.  So the documentation is a TODO for now.
P.S. the commit also includes a minor typo fix: `eay -> way`.

`rm`: make the utility public

---

src/uu/nl/src/nl.rs
tests/by-util/test_nl.rs

This PR changes the output order from "files first, stdin last" to "input order = output order" to match the behavior of GNU nl.

nl: fix output order if stdin and files are mixed

---

src/uu/dd/src/dd.rs
tests/by-util/test_dd.rs
tests/common/util.rs

The GNU test suggests that GNU's variant is trying to seek stdin/stdout s.t. it can abort early if the respective fd is seekable and does not have enough length to do the requested skip/seek.
Draft for now to signalize that I am working on it.
There are some small open points, e.g. recognize this better:
```
dd: 'standard input': cannot skip: Invalid argument
0+0 records in
1
```
vs
```
0+0 records in
0
```
and obviously add tests :)

dd: fix GNU test 'dd/skip-seek-past-dev'

---

src/uu/tail/src/follow/watch.rs

This PR removes the `_event_counter` var. This variable is increased but never read. It also renames the `_timeout_counter` var to `timeout_counter`, because the `_` at the beginning indicates the var will not be used which is not the case.

tail: remove unused "_event_counter"; rename "_timeout_counter" to "timeout_counter"

---

util/run-gnu-test.sh

This PR fixes a "file not found" error if `run-root` is passed to `run-gnu-test.sh`.

run-gnu-test.sh: accept "run-root" as first param

---

.github/workflows/CICD.yml
fuzz/Cargo.toml
fuzz/fuzz_targets/fuzz_common.rs
fuzz/fuzz_targets/fuzz_expr.rs

Based on:
https://github.com/uutils/coreutils/pull/4641

Fuzz the expr command

---

src/uucore/src/lib/features/ranges.rs
tests/by-util/test_cut.rs

GNU fails with
$ cut -b18446744073709551615 /dev/null
but we are able to support this value
we both fail with
$ cut -b18446744073709551616 /dev/null

cut-huge-range.sh: make cut fails on usize::MAX

---

src/uu/expr/src/syntax_tree.rs
tests/by-util/test_expr.rs

So far when using `|` or `&` numbers were only interpreted as `true` if they were `1`. This PR changes this behavior, now any number != 0 is interpreted as `true`.
Fixes https://github.com/uutils/coreutils/issues/5315 and https://github.com/uutils/coreutils/issues/5316

expr: interpret numbers != 0 as true for | and &

---

src/uu/fmt/src/fmt.rs
tests/by-util/test_fmt.rs

This PR uses clap's `usize` value parser for the `goal` and `width` options.

fmt: use clap's value parser for goal & width

---

src/uu/nl/src/helper.rs
src/uu/nl/src/nl.rs
tests/by-util/test_nl.rs

This PR implements `-d`/`--section-delimiter` that allows you to define a section delimiter other than the default `\:`. If the specified delimiter is a single character, `:` is added to the delimiter.

nl: implement -d/--section-delimiter

---

src/uu/nl/src/nl.rs
tests/by-util/test_nl.rs

Currently, a "line number overflow" error is shown when calculating the next line number. With this PR, the output of the error is deferred to when the next line number should be shown.

nl: defer showing "line number overflow" error

---

Cargo.lock
Cargo.toml
src/uu/date/src/date.rs
src/uu/touch/src/touch.rs
tests/by-util/test_touch.rs

Update parse_datetime to 0.5.0

---

src/uu/cp/src/platform/macos.rs
tests/by-util/test_cp.rs

Fixes issue #5257 by first checking if file is read only or not before removing file and trying clonefile again

cp: fail when trying to copy to read only file on mac

---

src/uu/mv/src/mv.rs
tests/by-util/test_mv.rs

This PR no longer shows a "skipped" message with `-vi`/`-vin` and makes https://github.com/coreutils/coreutils/blob/master/tests/mv/mv-n.sh pass.

mv: show no "skipped" msg with -vi/-vin

---

src/uu/cp/src/cp.rs
tests/by-util/test_cp.rs

Similar to https://github.com/uutils/coreutils/pull/5347 but for `cp`. Makes https://github.com/coreutils/coreutils/blob/master/tests/cp/cp-i.sh pass.

cp: show no "skipped" msg with -vi/-vin

---

src/uu/echo/src/echo.rs
tests/by-util/test_echo.rs

Funny behaviour in GNU:
```
$ echo -e "\0501"
A
```
Even though the octal code for `A` is `\0101`. The reason that happens is because 3 octal digits is equivalent to a _9_ bit integer.
This is possibly a bug in GNU that nobody has fixed in 31 years or they just chose to ignore it since it is fairly minor. I was investigating this with @jdonszelmann and we found that GNU and the built-in `echo` for zsh and fish both also have this wrapping behaviour. Though it's not really a problem because it is all done using `unsigned` integers. In this PR, I've made sure to use the `wrapping_*` methods for arithmetic to further avoid any problems.
Some other utilities might need to be checked too. For instance `printf`:
```
$ env printf "\501"
A
```
I noticed this while I was refactoring …

`echo`: fix wrapping behavior of octal sequences

---

tests/by-util/test_cp.rs
tests/by-util/test_split.rs
tests/by-util/test_tee.rs

This PR fixes clippy warnings in tests introduced by Rust 1.73, among them warnings from the [format_collect](https://rust-lang.github.io/rust-clippy/master/index.html#/format_collect) and [octal_escapes](https://rust-lang.github.io/rust-clippy/master/index.html#/octal_escapes) lints.

clippy: fix warnings in tests

---

src/uu/mv/src/mv.rs

References #5293 
@tertsdiepraam I did try to base if off the PR you mentioned in the issue.
The reason for the change of variable names (`b` -> `opts`) in non-public functions, is simply to match the new naming. If this is something that isn't desired, let me know.
Let me know of any additional changes you are looking for. 
Also, everything did end up working out in our CI (eza), as well as further testing for uutils-term-grid. Was removing the Alignment field all that you were waiting on to publish? Although now that we know it will be a drop-in replacement, there certainly isn't a rush. Thanks, we definitely appreciate it.
EDIT: Had to fix clippy warning for failed CI anyway so those `;`'s are just other random warnings I saw.

 mv: expose main functionality for nushell 

---

src/uu/ls/src/ls.rs

ls: fix panic when file removed too quickly

---

src/uu/expr/src/syntax_tree.rs
tests/by-util/test_expr.rs

fix #5326 
Implement short-circuit evaluation for `|`. And add the corresponding test.

`expr`: short-circuit evaluation for `|`

---

Cargo.lock

This PR bumps `errno` from `0.3.1` to `0.3.5` which removes the `errno-dragonfly` dependency.

Bump errno from 0.3.1 to 0.3.5

---

src/uu/mkdir/src/mkdir.rs

- Made the `mkdir` function public.  Added documentation, describing the behavior and parameters
- Moved the GNU dot-stripping behavior from `exec` to `mkdir`.

`mkdir`: make `mkdir` public and document it

---

Cargo.lock
Cargo.toml

This PR bumps `bstr` from `1.6` to `1.7` and `regex` from `1.9.6` to `1.10.0`.

Bump bstr and regex

---

src/uu/df/src/table.rs

Hit crash like this:
```
thread 'main' panicked at src/uu/df/src/table.rs:156:21:
attempt to subtract with overflow
stack backtrace:
0: rust_begin_unwind
at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
1: core::panicking::panic_fmt
at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
2: core::panicking::panic
at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
3: <uu_df::table::Row as core::convert::From<uu_df::filesystem::Filesystem>>::from
at ./src/uu/df/src/table.rs:156:21
4: uu_df::table::Table::new
at ./src/uu/df/src/table.rs:392:27
5: uu_df::uumain::uumain
at ./src/uu/df/src/df.rs:470:20
6: uu_df::uumain
at ./src/uu/df/src/df.rs:430:1
7: coreutils::main
at …
```

Fix overflow error on WSL. Default to 0 when the values are non-sense.

---

src/uu/split/src/split.rs
tests/by-util/test_split.rs

Implements undocumented `--numeric` and `--hex` aliases of the `--numeric-suffixes` and `--hex-suffixes` long options. At least one of them (`--numeric`) is used in GNU tests for `split`.
Minor fix for `--help` output.

`split`: undocumented options aliases + help fix

---

src/uu/who/src/who.rs

This PR suppresses the `cognitive_complexity` lint for the `exec` function. Discovered thanks to https://github.com/uutils/coreutils/pull/5399

who: suppress cognitive_complexity lint

---

.github/workflows/code-quality.yml

ci: code-quality workflow doesn't fail on clippy errors

---

src/uu/expr/src/syntax_tree.rs
tests/by-util/test_expr.rs

`&` can be short-circuit evaluated just like `|`. And add the corresponding test.

`expr`: short-circuit evaluation for `&`

---

tests/by-util/test_expr.rs

This PR adds a test to ensure a "syntax error" message is shown for some invalid syntaxes.

expr: test some invalid syntaxes

---

src/uu/expr/src/tokens.rs
tests/by-util/test_expr.rs

fix #5377 
`+` may escape such as `expr + 1` and `expr 1 + + 1`, and the cause of syntex error of `expr 12 \| 9a + 1` is the `+` escaped incorrectly.
Now the condition for escape is `!(pre_prev.1.is_a_value() || pre_prev.1.is_a_close_paren())`, but I'm not sure if the condition is identical to GNU.
I have add the test set for escape, and it would be better to have more test cases.

`expr`: fix expr syntax error

---

src/uu/rm/src/rm.rs
tests/by-util/test_rm.rs

use it when remove_dir_all failed
GNU compatibility (rm/empty-inacc.sh)

rm: In some cases, remove_dir is doing a better job than remove_dir_all

---

src/uu/rm/src/rm.rs

Refactor ```prompt_file```, add helper function.

`rm`: refactor `prompt_file`, issue #5345

---

fuzz/fuzz_targets/fuzz_expr.rs

This PR sets `LC_COLLATE=C` when fuzzing `expr` to avoid false positives.
A big thank you to @Luv-Ray for figuring out this issue in https://github.com/uutils/coreutils/issues/5378#issuecomment-1766134312

fuzz: set LC_COLLATE=C for expr

---

src/uu/dd/src/parseargs.rs
src/uu/df/src/blocks.rs
src/uu/du/src/du.rs
src/uu/head/src/parse.rs
src/uu/ls/src/ls.rs
src/uu/od/src/parse_nrofbytes.rs
src/uu/shred/src/shred.rs
src/uu/split/src/split.rs
src/uu/stdbuf/src/stdbuf.rs
src/uu/tail/src/args.rs
src/uu/truncate/src/truncate.rs
src/uucore/src/lib/parser/parse_size.rs
tests/by-util/test_head.rs
tests/by-util/test_split.rs
tests/by-util/test_stdbuf.rs
tests/by-util/test_truncate.rs

Implementing support for Ronna (R) and Quetta (Q) SI prefixes
Fixes #5334

Implement SI prefixes R and Q

---

src/uu/pathchk/src/pathchk.rs
tests/by-util/test_pathchk.rs

fix #5314 
comment in GNU pathchk:
> Check whether a file name component is in a directory that is not searchable, or has some other serious problem. POSIX does not allow "" as a file name, but some non-POSIX hosts do (as an alias for "."), so allow "" if lstat does.
I use `std::fs::symlink_metadata`, which currently corresponds to the `lstat` function on Unix and the `GetFileInformationByHandle` function on Windows instead.
It looks good in my local, but I don't have a non-POSIX environment, so it may need some more tests.
In my local:
```
$ ./target/debug/pathchk ""         
pathchk: '': No such file or directory
```
```
$ ./target/debug/pathchk "" ""      
pathchk: '': No such file or directory
pathchk: '': No such file or directory
```

`pathchk`: check empty path by default

---

src/uu/mv/src/mv.rs

mv: make UpdateMode public

---

src/uu/split/src/split.rs
tests/by-util/test_split.rs

Refactor handling of `--filter` option, specifically BrokenPipe error handling - for "endless" and finite inputs.
Better handling of stdin input errors for `--number` option.
Following GNU `split` behavior for above.
GNU test tests/split/filter.sh should stop failing

`split` : `--filter` and stdin updates

---

src/uu/cp/src/cp.rs
tests/by-util/test_cp.rs

With this PR, `cp --remove-destination` no longer shows an error if the destination is a symlink to the source and the destination is removed instead.
Fixes https://github.com/uutils/coreutils/issues/5420

cp --remove-destination: don't fail if destination is symlink to source

---

src/uu/runcon/src/errors.rs

tested in tests/runcon/runcon-no-reorder.sh

runcon: generate the same error as GNUs

---

src/uu/test/src/test.rs
tests/by-util/test_test.rs

- Use the file modification time instead of the creation time (matches GNU coreutils documentation)
- Fix direction of comparison (a < b instead of a > b)
- Extend test case to cover both the 0 and 1 exit code cases

test: use mtime for -ot and fix direction of comparison

---

Cargo.lock

This PR bumps `const-random` from `0.1.15` to `0.1.16` and thus removes `proc-macro-hack`.

Bump const-random from 0.1.15 to 0.1.16

---

src/uu/mv/src/error.rs
src/uu/mv/src/mv.rs
tests/by-util/test_mv.rs

Fixes #5426, where moving a directory into itself would remove the source directory and not fail
Previously:
`mkdir mydir/mydir_2`
```
uutils mv mydir mydir/mydir_2
```
And it would make `mydir` disappear. 
Now:
`mkdir mydir/mydir_2`
```
uutils mv mydir mydir/mydir_2
mv: cannot move 'mydir' to a subdirectory of itself, 'mydir/mydir_2/mydir'
```
which matches the GNU behavior

mv: moving directory itself should fail

---

src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

This PR returns an exit code `2` if the value for `--time-style` is invalid. It makes https://github.com/coreutils/coreutils/blob/master/tests/ls/time-style-diag.sh pass.

ls: return exit code 2 for invalid time-style

---

util/build-gnu.sh

Failed with:
```
-df: options OPT and --output are mutually exclusive 
-Try 'df --help' for more information.
+error: the argument '--inodes' cannot be used with '--output[=<FIELD_LIST>...]' 
+
+Usage: df [OPTION]... [FILE]...
```

df: Replace the error message by the one generated by clap

---

tests/by-util/test_dd.rs

On *BSD and macOS, the system provided dd utility opens up the output file for both reading and writing. This means that the open/write to the FIFO does not block, and almost instantly completes. The system dd then exits, leaving nothing left to be read by the time the coreutils-rs dd tries to open/read the FIFO.
Avoid this problem by just writing to the FIFO from the test case itself, rather than relying on the system provide dd.

tests/dd: Do not use the OS provided dd utility on FIFOs

---

src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

This PR replaces `get_matches_from` with `try_get_matches_from` to adapt clap's exit code. It makes https://github.com/coreutils/coreutils/blob/master/tests/ls/classify.sh pass and replaces https://github.com/uutils/coreutils/pull/5437

ls: use try_get_matches_from instead of get_matches_from

---

tests/by-util/test_cp.rs

This PR adds a test for the existing functionality of `--attributes-only`.

cp: add test for --attributes-only

---

src/uu/mv/src/error.rs
src/uu/mv/src/mv.rs
tests/by-util/test_mv.rs

Fixes #5463
The implementation of mv seems a bit messy, at least to a first time reader. My changes also feel a bit "band-aided" in. Glad we have a bunch of tests but the many repeated calls to `is_dir` and `symlink_metadata` and hard to understand flow may need to be addressed.

Fix stderr output mv file into dir and dir into file where both are files

---

src/uu/cat/src/cat.rs
tests/by-util/test_cat.rs

Should fix tests/du/long-sloop.sh because it is using cat as a ref for error messages

cat: return the same error message as GNU with loop symlink

---

fuzz/fuzz_targets/fuzz_parse_size.rs

fuzz: use parse_size_u64

---

src/uucore/src/lib/features/fsext.rs

df, and perhaps other commands, get the list of the mounted filesystems
with the call to getmntinfo(3).  Since Rust still use FreeBSD 11.x ABI
for filesystem metadata call, it should use matching versioned symbol for
getmntinfo from libc.

freebsd: fix the 'df' command

---

src/uu/cat/src/cat.rs

The error code for `ELOOP` (Too many levels of symbolic links) is `62`, and not `40`, on FreeBSD according to https://man.freebsd.org/cgi/man.cgi?query=errno&apropos=0&sektion=2&manpath=FreeBSD+15.0-CURRENT&arch=default&format=html

cat: use error code 62 for ELOOP on FreeBSD

---

src/uu/cp/src/copydir.rs
tests/by-util/test_cp.rs

fix #5457
by letting the cp respect the -T option

cp: fix cp -rT dir dir2 leads to different result than with GNU cp

---

tests/by-util/test_cp.rs

This PR restricts two test functions to avoid the following "unused variable" warnings on FreeBSD:
```
warning: unused variable: `stdout_str`
--> tests/by-util/test_cp.rs:3225:9
|
3225 |     let stdout_str = result.stdout_str();
|         ^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_stdout_str`
|
= note: `#[warn(unused_variables)]` on by default
warning: unused variable: `stdout_str`
--> tests/by-util/test_cp.rs:3261:9
|
3261 |     let stdout_str = result.stdout_str();
|         ^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_stdout_str`
```

cp: restrict two test functions to linux/mac/win

---

src/uu/cp/src/cp.rs

It seems to be unnecessary since we have already made the path relative using `construct_dest_path`.
Oh and I made `TargetType` copy, which simplifies some things a bit.
I want to see if this impacts GNU tests before merging, I might have missed something.

`cp`: remove `crash!` call

---

src/uu/split/src/filenames.rs
src/uu/split/src/number.rs
src/uu/split/src/split.rs
src/uu/split/src/strategy.rs
tests/by-util/test_split.rs

Refactoring suffix length processing, distinguishing between dynamic auto-widening vs. pre-calculated auto-width and addressing an edge case of passing `0` as a value for suffix length in command line option, 
i.e. `split -a0 file` 
or `split --suffix-length=0 file`

split: suffix length refactor

---

deny.toml

This PR removes entries for `rustix` and `linux-raw-sys` from the skip list in `deny.toml`. They are no longer needed due to https://github.com/uutils/coreutils/pull/5474

deny.toml: remove two entries from skip list

---

src/uu/du/src/du.rs
tests/by-util/test_du.rs

This PR adds `-P`/`--no-dereference`.

du: add --no-dereference

---

tests/by-util/test_cp.rs
tests/by-util/test_tail.rs

This PR fixes some "unused import" and "unused variable" warnings in tests on Android as shown in https://github.com/uutils/coreutils/actions/runs/6756912757/job/18366894422?pr=5494#step:8:2114:
```
warning: unused import: `rlimit::Resource`
--> tests/by-util/test_cp.rs:28:5
|
28 | use rlimit::Resource;
|     ^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: unused import: `std::path::Path`
--> tests/by-util/test_tail.rs:29:5
|
29 | use std::path::Path;
|     ^^^^^^^^^^^^^^^
warning: unused import: `tail::text`
--> tests/by-util/test_tail.rs:37:5
|
37 | use tail::text;
|     ^^^^^^^^^^
warning: unused import: `std::fmt::Write`
--> tests/by-util/test_tee.rs:6:5
|
6 | use std::fmt::Write;
|     ^^^^^^^^^^^^^^^
Waiting for /sdcard/tests.probe: /sdcard/tests.log: 1 …
```

cp,tail: fix warnings in tests on Android

---

src/uu/mktemp/src/mktemp.rs

Tried to follow @tertsdiepraam guidance [here](https://github.com/uutils/coreutils/issues/5465#issuecomment-1783830036)
Link to https://github.com/uutils/coreutils/issues/5465

mktemp: add func to expose functionality (for use in nushell)

---

src/uu/du/src/du.rs
tests/by-util/test_du.rs

This PR adds `-H`, an alias for `-D`/`--dereference-args`.

du: add -H (alias for --dereference-args)

---

.vscode/cspell.dictionaries/workspace.wordlist.txt
CONTRIBUTING.md

This is a step towards https://github.com/uutils/coreutils/issues/5195
~The sections "Design Goals" and "Git Etiquette" are still left empty. We can discuss what we what to put there.~

Expand CONTRIBUTING.md (WIP)

---

src/uu/printf/printf.md
src/uucore/src/lib/features/tokenize/sub.rs
tests/by-util/test_printf.rs

fix #5468 
The previous [PR](https://github.com/uutils/coreutils/pull/5472) was quite messy, so I open a new PR with clean commits.

`printf`: support %q

---

tests/by-util/test_cp.rs

This PR makes `test_closes_file_descriptors` Linux-only as my solution in https://github.com/uutils/coreutils/pull/5496 makes the test fail on Android.

cp: make test_closes_file_descriptors Linux-only

---

src/uu/du/src/du.rs

This PR is related to #5487.
It removes the crash! macro from `du`.

du: remove crash! macro

---

src/uu/expand/src/expand.rs

Related issue: #5487 
Removes use of `crash!` macro in `expand`

expand: remove crash! macro

---

fuzz/fuzz_targets/fuzz_common.rs
fuzz/fuzz_targets/fuzz_expr.rs
fuzz/fuzz_targets/fuzz_test.rs

* compares exit code, stdout & stderr (the later can be disabled)
* add checks on pipe operations
* flush before getting the results for stdout & stderr

fuzzing: Refactor the error management

---

.github/workflows/CICD.yml

Github claims they have arm64 runners but doesn't seem like they enabled them for free plans. So for now, we cross-compile from intel and skip tests. I verified that some basic smoketests passed on my M1.

Add darwin arm64 builds

---

src/uu/du/src/du.rs
tests/by-util/test_du.rs

So far, `-l`/`--count-links` were accepted as options and then ignored. This PR makes them work.

du: make -l/--count-links work

---

src/uu/split/src/platform/unix.rs

This is related to issue: https://github.com/uutils/coreutils/issues/5487
This removes the `crash` macro from split.

split: remove crash macro

---

src/uucore/src/lib/features/tokenize/num_format/formatters/intf.rs
tests/by-util/test_printf.rs

Fixes #5536 by changing the warning called from the `intf` module and adding an appropriate exit code.
Created a test to confirm the behavior.
Before:
```
./target/debug/coreutils printf %x %194 > /dev/null
echo $? 
```
returns:
```
printf: '%194': value not completely converted
0
```
After:
```
printf: %194: expected a numeric value
1
```

printf: Fixing incorrect exit code when passing invalid value to %x

---

docs/src/installation.md

`/build.md` is absolute, so the link in https://uutils.github.io/coreutils/book/installation.html turns out to be https://uutils.github.io/build.html instead of https://uutils.github.io/coreutils/book/build.html.
Reference: [Links · Markdown - mdBook Documentation](https://rust-lang.github.io/mdBook/format/markdown.html#links)

doc: Fix a broken link

---

src/uu/join/src/join.rs

This is related to issue https://github.com/uutils/coreutils/issues/5487. Removes the `crash!` macro from join.

join: remove crash! macro

---

util/publish.sh

This can happen when a publishing step failed

publishing: check if the current version is already there or not

---

src/uu/stdbuf/src/stdbuf.rs
tests/by-util/test_stdbuf.rs

This is related to issue: https://github.com/uutils/coreutils/issues/5487
Removes the `crash!` macro from `stdbuf`.

stdbuf: remove crash macro

---

src/uu/expr/src/syntax_tree.rs
tests/by-util/test_expr.rs

As addressed in https://github.com/uutils/coreutils/issues/5558 , this PR aligns the error messages from this implementation of `expr` with the GNU one.
If there are no arguments, it returns `expr: missing operand`.
If one of the arguments introduced arity, but there are not enough arguments, it returns `expr: syntax error: unexpected argument 'substr'` with the name of that argument, like `substr`.
Added tests.

expr: different stderr with `expr "56" "substr"`

---

src/uu/expr/src/expr.rs
src/uu/expr/src/syntax_tree.rs
tests/by-util/test_expr.rs

This PR is an alternative to #5575. It reverts most of #5559 and adapts the error messages to match those of GNU `expr`. It also fails fast if `expr` is called without any arguments.

expr: adapt error messages, revert most of #5559

---

src/uu/expr/src/syntax_tree.rs
tests/by-util/test_expr.rs

Fixes uutils/coreutils#5576
Issue 5576 reported a bug in expr, found by the fuzzer. The problem
turns out to be with the regex match operator `:`, which is defined in
POSIX and the GNU manual to match the pattern only when it occurs at
the beginning of the string, i.e., the regex has an implicit `^`
prepended to it. We hadn't been doing that.
References:
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/expr.html
https://www.gnu.org/software/coreutils/manual/html_node/String-expressions.html

Fix issue 5576 (regex matching bug in expr)

---

src/uu/split/src/split.rs
src/uu/split/src/strategy.rs
tests/by-util/test_split.rs

Pass GNU tests/split/l-chunk.sh test
Cleaning up tests

split: pass GNU test l-chunk

---

src/uu/cp/src/copydir.rs
tests/by-util/test_cp.rs

This PR improves the error message when trying to call `cp source_dir target_dir` from `omitting directory 'source_dir'` to `-r not specified; omitting directory 'source_dir'` (the same message shown by GNU `cp`).

cp: improve error msg if -r is not specified

---

src/uu/du/src/du.rs

This PR updates `du` so that it continuously prints output as it is running, as opposed to waiting until all of the data has been collected before printing anything. A separate thread has been added which handles printing data (and errors) as they are produced by the main thread.
Fixes #5516

du: start printing output immediately

---

src/uu/hashsum/src/hashsum.rs

Remove usage of the `crash!` macro for error handling and instead return a `UResult` from `detect_algo`.
Part of #5487

hashsum: Remove usage of crash! macro

---

src/uu/wc/src/wc.rs
tests/by-util/test_wc.rs

Pass the GNU tests/wc/wc-files0-from.pl test

wc: pass GNU test wc-files0-from.pl

---

src/uu/dd/src/bufferedoutput.rs
src/uu/dd/src/dd.rs
src/uu/dd/src/parseargs.rs
src/uu/dd/src/parseargs/unit_tests.rs
src/uu/dd/src/progress.rs
tests/by-util/test_dd.rs

This pull request adds buffering of partial blocks in the output block writer until they are completed.
The test case that demonstrates this buffering behavior is
```
mkfifo fifo
dd ibs=3 obs=3 if=fifo &
(printf 'ab'; sleep 1; printf 'cd') > dd.fifo
```
The "ab" forms a partial block, which is buffered and not written immediately. Then when the "cd" comes in, the complete block "abc" is written, followed by the partial block "d".
To override the behavior set `bs=N`, like this:
```
dd bs=3 ibs=1 obs=1 if=fifo
```
Fixes GNU test case `tests/dd/reblock.sh`.

dd: buffer partial blocks in the output writer

---

src/uu/split/src/platform/unix.rs
src/uu/split/src/platform/windows.rs
src/uu/split/src/split.rs
tests/by-util/test_split.rs

Pass GNU test tests/split/r-chunk.sh
Implement handling system limit on open files (`ulimit -n`) following the same approach as in GNU split, i.e. running up to the limit, catch an error on instantiating next writer to a file, closing one of the existing writers to free up resources and re-trying to instantiate a writer again, including tracking new vs. append to previously created and closed writers.
Tests.

split: passing GNU test r-chunk.sh

---

src/uu/fmt/src/parasplit.rs

While reviewing https://github.com/uutils/coreutils/pull/5592 I noticed the inconsistent naming of `pfxind_end` compared to names like `indent_end` and `prefix_len`. For consistency reasons, this PR changes `pfxind_end` to `prefix_indent_end`.

fmt: rename `pfxind_end` -> `prefix_indent_end`

---

src/uu/cut/src/cut.rs
tests/by-util/test_cut.rs

This PR adds a test and improves the error message if the provided delimiter is longer than one char. Now it is the same message as GNU `cut` shows.

cut: add test & improve error message if the delimiter is too long

---

.github/workflows/freebsd.yml
tests/by-util/test_cp.rs

Based on https://github.com/uutils/coreutils/pull/5511
Updated workspace path to match linux workers.
Tested on my fork: https://github.com/piotrkwiecinski/coreutils/actions/runs/7049864926/job/19189301324?pr=3

Bump freebsd-vm action to v1.0.2 & use ubuntu

---

.github/workflows/CICD.yml
.github/workflows/GnuTests.yml
.github/workflows/android.yml
.github/workflows/code-quality.yml
.github/workflows/freebsd.yml
.github/workflows/fuzzing.yml

While testing FreeBSD job I noticed that each push to a feature branch creates 2 separate events - push and pull request.
This should reduce consecutive commits from running the same job twice and free a lot of CI resources.

prevent CI creating 2 events on each pull request push

---

src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

This PR fixes an issue with the padding of the size column when using `-l` and the folder contains more than one file. The output of `ls -l` before the change:
```
total 0
-rw-r--r-- 1 dho dho    0 Nov 30 15:29 c.txt
-rw-r--r-- 1 dho dho    0 Nov 30 15:51 d.txt
```
And after the change:
```
total 0
-rw-r--r-- 1 dho dho 0 Nov 30 15:29 c.txt
-rw-r--r-- 1 dho dho 0 Nov 30 15:51 d.txt
```
This is the same output as GNU `ls` produces.

ls: fix padding of size column when using `-l`

---

src/uucore/src/lib/features/fs.rs
src/uucore/src/lib/features/fsext.rs

- uucore/src/lib/features/fs.rs: add target_os = OpenBSD when needed
- uucore/src/lib/features/fsext.rs: implement FsUsage::new for OpenBSD
- fixes uutils/coreutils#5448
- initial code by n1000 https://github.com/n1000/coreutils/tree/openbsd_compile_fixes
---
Build OK with `cargo build --release` on OpenBSD-current/amd64 and Rust 1.74.0
```
$ target/release/coreutils
coreutils 0.0.23 (multi-call binary)
Usage: coreutils [function [arguments...]]
Currently defined functions:
[, b2sum, b3sum, base32, base64, basename, basenc, cat, cksum, comm, cp, csplit, cut, date,
dd, df, dir, dircolors, dirname, du, echo, env, expand, expr, factor, false, fmt, fold,
hashsum, head, join, link, ln, ls, md5sum, mkdir, mktemp, more, mv, nl, numfmt, od, paste,
pr, printenv, printf, ptx, pwd, readlink, …
```

Add support in uucore for OpenBSD

---

tests/by-util/test_cp.rs
tests/by-util/test_test.rs

Avoid trying to set the file sticky bit on FreeBSD, since only the superuser has permissions to set the file sticky bit.

tests/cp, tests/test: Don't attempt to set sticky file bit on FreeBSD

---

tests/by-util/test_du.rs

This PR disables `test_du_inodes_with_count_links` on Android because its file system doesn't seem to support hard links.

du: disable test on Android

---

src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

This PR ignores the value of `POSIXLY_CORRECT` to match the behavior of GNU `ls`. It also renames some vars related to block sizes for better readability and consistency.

ls: ignore value of `POSIXLY_CORRECT`

---

src/uu/mv/src/mv.rs
tests/by-util/test_mv.rs

When using `mv -T source_dir dest_dir/` (note the trailing slash, it works fine without it), and `dest_dir` doesn't exist, uutils `mv` shows an error message whereas GNU `mv` renames `source_dir` to `dest_dir`. This PR fixes this issue.

mv: fix issue with -T and destination ending with "/"

---

src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

If you provide an invalid block size with `ls --block-size=invalid`, GNU `ls` shows an error message and exits with a status code of `2`. uutils `ls`, on the other hand, shows the same error message but also lists the content of the current folder. And the status code is `1`. This PR adapts the handling of an invalid block size to match GNU's handling.

ls: handle invalid block size as GNU does

---

.github/workflows/fuzzing.yml
src/uu/echo/src/echo.rs
tests/by-util/test_echo.rs

Closes https://github.com/uutils/coreutils/issues/5619
I know it was a good-first-issue, but I was convinced that `-e` and `-E` would override so I wanted to note that in the issue and then it turned out that I was already halfway into solving the issue 😄

`echo`: make `-e` and `-E` override each other

---

src/uu/ls/src/ls.rs

This PR uses the `show_dir_name` function to output the directory name instead of using `writeln!`. It's done for consistency reasons because a few lines below the same function is used.

ls: use show_dir_name to output dir name

---

src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

This PR makes `--block-size` and `--human-readable`/`--si` override each other to match the behavior of GNU `ls`.

ls: make --block-size and --human-readable/--si override each other

---

docs/src/installation.md

This PR removes the broken "scoop" badge and adapts some links to point to the corresponding repos instead of repology.org.

docs: remove scoop badge, adapt links to repos

---

.github/workflows/CICD.yml

This PR is an attempt to fix the failing `Tests/Toybox test suite`, probably caused by https://github.com/uutils/coreutils/pull/5646 and its breaking change:
> Uploading to the same named Artifact multiple times.
>
> Due to how Artifacts are created in this new version, it is no longer possible to upload to the same named Artifact multiple times. You must either split the uploads into multiple Artifacts with different names, or only upload once. Otherwise you will encounter an error.

ci: rename test summary names for busybox & toybox

---

.github/workflows/CICD.yml

This adds Redox OS builds to CI. Tests are skipped at the moment.
Part of https://github.com/uutils/coreutils/issues/5210

Add Redox OS CI

---

tests/by-util/test_hostname.rs

On OpenBSD, test_hostname::test_hostname_ip fails with "failed to lookup address information: Name does not resolve" error

tests/hostname: disable failing test_hostname::test_hostname_ip on OpenBSD

---

Cargo.lock
Cargo.toml
deny.toml

This PR bumps `xattr` from `1.1.1` to <del>`1.1.2`</del>`1.1.3` and adapts `deny.toml` to allow three versions of `windows-sys` and its related crates.

Bump xattr from 1.1.1 to 1.1.3 & adapt deny.toml

---

src/uu/unexpand/src/unexpand.rs

This PR is related to https://github.com/uutils/coreutils/issues/5487.
It removes the `crash!` macro from `unexpand`.

 unexpand: remove crash! macro

---

src/uu/ls/Cargo.toml
src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

Should fix GNU tests/ls/color-term.sh

ls: manages the COLOR and COLORTERM variables

---

.github/workflows/CICD.yml
.github/workflows/FixPR.yml

This PR fixes three warnings shown by `cargo tree` (for example in https://github.com/uutils/coreutils/actions/runs/7244626153/job/19733242456?pr=5668, in the "Info" section):
```
warning: the --no-indent flag has been changed to --prefix=none
warning: The `cargo tree` --all flag has been changed to --no-dedupe, and may be removed in a future version.
If you are looking to display all workspace members, use the --workspace flag.
warning: the --no-dev-dependencies flag has changed to -e=no-dev
```

ci: fix warnings from "cargo tree"

---

src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

This PR encodes special characters in a path when using `--hyperlink`.

ls: encode path when using --hyperlink

---

src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

This PR adds `--hyperlink` support for dir names and makes the [hyperlink.sh GNU test](https://github.com/coreutils/coreutils/blob/master/tests/ls/hyperlink.sh) pass.

ls: support hyperlinks for dir names

---

src/uu/expr/src/syntax_tree.rs
tests/by-util/test_expr.rs

Closes https://github.com/uutils/coreutils/issues/5647

`expr`: coerce to string before comparing values

---

src/uu/ls/src/ls.rs

This PR renames the function `display_file_name` to `display_item_name` because the function is not limited to file names.

ls: rename `display_file_name` to `display_item_name`

---

src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

If the block size value specified by an env variable (e.g. `LS_BLOCK_SIZE`) is invalid, GNU `ls` "ignores" the value (it changes a block size value we currently don't have) whereas uutils `ls` panics while creating an error. This PR fixes this issue.

ls: ignore invalid block size from env vars

---

fuzz/fuzz_targets/fuzz_expr.rs

https://storage.googleapis.com/oss-fuzz-coverage/rust-coreutils/reports/20231118/linux/src/rust-coreutils/src/uu/expr/src/syntax_tree.rs.html

expr fuzz: add missing ops. found thanks to oss fuzz coverage

---

src/uucore/src/lib/features/fs.rs

- src/uucore/src/lib/features/fs.rs: in inode function, remove useless conversion for target_OS = OpenBSD
Build and tests OK on OpenBSD/amd64 and Linux
Tests with inodes (via `ls`) on OpenBSD => same results with Rust and system coreutils
```
$ target/release/coreutils ls -li
total 192
363028 -rw-r--r-- 1 fox fox  5227 Nov 28 11:22 CODE_OF_CONDUCT.md
363029 -rw-r--r-- 1 fox fox 13320 Nov 28 11:22 CONTRIBUTING.md
362949 -rw-r--r-- 1 fox fox 77830 Dec 16 18:38 Cargo.lock
362956 -rw-r--r-- 1 fox fox 20970 Dec 16 18:38 Cargo.toml
363032 -rw-r--r-- 1 fox fox 10965 Dec 16 18:40 DEVELOPMENT.md
363033 -rw-r--r-- 1 fox fox  8667 Nov 28 11:22 GNUmakefile
363034 -rw-r--r-- 1 fox fox  1056 Nov 28 11:22 LICENSE
363035 -rw-r--r-- 1 fox fox    55 Nov 28 11:22 Makefile
363037 -rw-r--r-- 1 fox fox 10264 …
```

uucore: remove useless conversion for features/fs on OpenBSD

---

src/uu/sort/src/sort.rs
tests/by-util/test_sort.rs

Hello :wave: 
This small PR try to fix #5667.
I'm pretty new to rust, so if there's a better way to allow a flag to be pass multiple time, let me know.  :smile: 
```
echo "foo" | target/debug/sort -f -f
foo
```

sort: allow `-f` to be pass multiple time

---

src/uu/ls/src/ls.rs

This PR removes a `cfg!(unix)` condition with an unreachable `else` block. It is unreachable because the enclosing code is already in a `#[cfg(unix)]` block.

ls: remove condition with unreachable "else" block

---

src/uu/expand/src/expand.rs
tests/by-util/test_expand.rs
tests/fixtures/expand/alice_in_wonderland.txt

Fixed `expand` failed when executing multiple args. See [#5671](https://github.com/uutils/coreutils/pull/5671)
**GNU:**
```
$ echo -e "foo\tbar" | expand -i -i
foo	bar
```
**Current uutils/coreutils:**
```
$ echo -e "foo\tbar" | uuu expand -i -i
error: the argument '--initial' cannot be used multiple times
Usage: /home/nemesis/Documents/Github/Focus/util/coreutils/target/debug/coreutils expand [OPTION]... [FILE]...
For more information, try '--help'.
```
**Expected behavior for uutils/coreutils:**
```
$ echo -e "foo\tbar" | uuu expand -i -i
foo	bar
```

expand: fix duplicate flags

---

.github/workflows/CICD.yml

Fixes #5690.
I tested the workflow on my fork:
- [CI run](https://github.com/malt3/coreutils/actions/runs/7298905395/job/19890810745)
- [test release](https://github.com/malt3/coreutils/releases/tag/0.0.24-malt3-rc1)
The resulting artifact works as expected:
```shell-session
$ file coreutils
coreutils: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, with debug_info, not stripped
$ ./coreutils
coreutils 0.0.23 (multi-call binary)
Usage: coreutils [function [arguments...]]
Currently defined functions:
[, arch, b2sum, b3sum, base32, base64, basename, basenc, cat, chgrp, chmod, chown, chroot,
cksum, comm, cp, csplit, cut, date, dd, df, dir, dircolors, dirname, du, echo, env, expand,
expr, factor, false, fmt, fold, groups, hashsum, head, hostid, hostname, id, …
```

ci: add aarch64-unknown-linux-musl release artifact

---

src/uu/mv/src/mv.rs
tests/by-util/test_mv.rs

With GNU `mv`, `mv --update source/ dest/` renames `source` to `dest`. uutils `mv`, on the other hand, shows a "Not a directory" error message. This PR fixes this issue.

mv: allow destination with slash when using --update

---

src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

This PR introduces a second, internal blocksize and fixes all todos in the tests related to this missing blocksize.
Some more work is needed to make `tests/ls/block-size.sh` pass.

ls: introduce 2nd blocksize & fix todos in tests

---

src/uu/install/src/install.rs
tests/by-util/test_install.rs

Should fix: tests/install/strip-program.sh

install: support when a hyphen is passed

---

src/uu/install/src/install.rs
tests/by-util/test_install.rs

Should pass tests/install/basic-1

install: with -t, check if we aren't passed a file

---

src/uu/runcon/src/errors.rs

Upstream doesn't have in:
https://github.com/coreutils/coreutils/blob/master/tests/runcon/runcon-no-reorder.sh#L22

runcon: remove trailing '.'

---

tests/by-util/test_wc.rs

This PR disables a part of `test_files_from_pseudo_filesystems` on Android because it fails with a "Permission denied" error when accessing `/sys/kernel/profiling`. I noticed this issue in https://github.com/uutils/coreutils/actions/runs/7309434867/job/19917041320?pr=5701

wc: disable part of test on Android

---

Cargo.lock

This PR bumps 
- `crossbeam-channel` from `0.5.8` to `0.5.10`
- `crossbeam-deque` from `0.8.2` to `0.8.4`
- `crossbeam-epoch` from `0.9.14` to `0.9.17`
- `crossbeam-utils` from `0.8.15` to `0.8.18`
and thus removes the `memoffset` dependency.

Bump crossbeam crates

---

src/uu/ls/src/ls.rs
util/build-gnu.sh

Should fix tests/ls/stat-free-color.sh

ls: Improve the access to metadata of the files

---

src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

This PR sets the correct block sizes when `-k` is provided. It makes https://github.com/coreutils/coreutils/blob/master/tests/ls/block-size.sh pass

ls: set correct block size when -k is provided

---

tests/by-util/test_df.rs

This PR fixes a rounding issue in `test_use_percentage`. Because the test used the default block size of `1024`, the returned values for the columns `Used` and `Avail` were rounded. However, the test used them to calculate the percentage values to compare them with the values returned in the `Use%` column. In some cases, the rounding led to a mismatch between those values and that caused the test to fail. By setting the block size to `1`, the returned values for `Used` and `Avail` are no longer rounded.
Fixes https://github.com/uutils/coreutils/issues/5531

df: fix rounding issue in test

---

tests/by-util/test_tee.rs

warning: unused import: `std::fmt::Write`

tee test: fix a warning on not(linux)

---

util/deps.nu

I was playing around with nushell and made a script to analyze our dependencies. I keep trying to get a better overview of all the dependencies that we have and it's a bit of a struggle, because we have so many. I'm planning on writing a little blog post analyzing all our dependencies with this script.
The reason to add this in addition to `cargo tree`, `cargo deny`, etc. is that this gives us a table to analyze in any way we want and extend. See the list of ideas in the comments of the script. We could also, for example, figure out dependants of crates to check they are popular or that we are the only users.
Ultimately, it might be a good idea to go through the entire list of dependencies to figure out whether they are necessary. Or to figure out whether there are multiple crates doing …

Add nushell dependency analysis script

---

src/uu/cp/src/cp.rs
tests/by-util/test_cp.rs

With this PR, cp --remove-destination no longer shows an error on Unix platforms if the destination is a hardlink to the source and the destination is removed instead.
<del>This PR probably conflicts with https://github.com/uutils/coreutils/pull/5430</del>

cp --remove-destination: don't fail if destination is hardlink to source

---

src/uu/cp/src/cp.rs
src/uu/ln/src/ln.rs
src/uu/mv/src/mv.rs
tests/by-util/test_cp.rs
tests/by-util/test_ln.rs
tests/by-util/test_mv.rs

Should fix: tests/mv/childproof.sh

cp/mv/ln: add support for the "will not overwrite just-created"

---

src/uu/mv/src/mv.rs
tests/by-util/test_mv.rs

This PR fixes the subdirectory detection so that `test` is not incorrectly recognized as a subdirectory of `test2` when calling `mv test test2`.
Fixes https://github.com/uutils/coreutils/issues/5481

mv: fix subdir detection

---

tests/by-util/test_test.rs

On some platforms (mostly the BSDs) the test fixture files copied to the /tmp directory will have a different gid than the current egid (due to the sticky bit set on the /tmp directory). Fix this before running the "test" command.

tests/test: Ensure the test fixture files have the expected gid

---

tests/by-util/test_du.rs

While looking at the `du` tests I noticed that the `_du_basics` functions are never called. Assuming they were intended to be called from `test_du_basics`, I adapted this function accordingly.

du: call unused _du_basics() in test_du_basics()

---

src/uu/du/src/du.rs
tests/by-util/test_du.rs
util/build-gnu.sh

Should make tests/du/files0-from-dir pass

du: implement files0-from

---

src/uu/cp/src/cp.rs
tests/by-util/test_cp.rs

With this PR, `cp --link` no longer shows a "same file" error if the destination is a hardlink to the source.

cp --link: don't fail if destination is hardlink to source

---

tests/by-util/test_du.rs

This PR simplifies the creation of files in tests, using a single line instead of two. It also improves the readability by using `concat!`.

du: simplify file creation in tests

---

src/uu/install/src/install.rs
tests/by-util/test_install.rs

#5720 fix.
I figured paths ending in "/" make .exists() not work properly so I added a check as to remove the / if there is one.

install: remove / from end of path if it exists so as not to mess with .exists()

---

src/uu/cp/src/cp.rs
tests/by-util/test_cp.rs

When using `cp -b a symlink`, GNU `cp` backups `symlink` as `symlink~` and then overwrites `symlink` with `a` (and thus `symlink` is no longer a symlink). uutils `cp`, on the other hand, backups the target of the symlink as `symlink~` and then overwrites the target of the symlink with `a` (and thus `symlink` remains a symlink). This PR fixes this behavior.

cp: fix backup of destination symlink

---

src/uu/install/src/install.rs
tests/by-util/test_install.rs

Should make tests/install/install-C-root.sh  pass

install: Manages permissions when run as root

---

src/uu/basenc/basenc.md
src/uu/cut/cut.md
src/uu/join/join.md
src/uu/mkdir/mkdir.md
src/uu/nohup/nohup.md
src/uu/pr/pr.md
src/uu/printenv/printenv.md
src/uu/printf/printf.md
src/uu/runcon/runcon.md
src/uu/shuf/shuf.md
src/uu/sum/sum.md
src/uu/uniq/uniq.md
src/uu/unlink/unlink.md

join: fixed parameter
basenc: fixed parameter
cut: fixed parameter
mkdir: fixed parameter
nohup: fixed parameter
pr: fixed parameter
printenv: fixed parameter
printf: added parameters
runcon: fixed typo
shuf: fixed typo
sum: fixed typo
uniq: fixed parameter
unlink: fixed parameter
issue #5692

src: Fixing typos in signatures for the argument parser

---

src/uu/cp/src/cp.rs
tests/by-util/test_cp.rs

This PR adapts the warning shown when using `cp a a b/` to match the one shown by GNU `cp`.

cp: adapt warning if source is used more than once

---

src/uu/ls/src/ls.rs

Issue #5632 fix.
In short, I added a boolean variable `quoted` which is true if at least one file name is displayed between quotes. If so, all unquoted filenames are formatted so that they have an extra leading space, as GNU's ls does.
Unfortunately I couldn't find a way to write unit tests for this functionality because ls formats output differently when it's not stdout. I tried using different flags ("-C", "--quoting-style", "-T") but couldn't find a way to make ls format properly.

ls: unquoted names should be indented with a space if there is a quoted name

---

src/uu/cp/src/cp.rs
tests/by-util/test_cp.rs

When using `cp a a`, GNU `cp` shows a "same file" error whereas uutils `cp` doesn't fail. This PR fixes this issue.

cp: show error if source and destination are same file

---

docs/src/installation.md

FreeBSD port name is `rust-coreutils`, fix URL for repology.org

docs: fix URL for FreeBSD port

---

tests/common/util.rs

`bool::is_ok_and()` is available in Rust 1.70.0 and above, which is compatible with the current MSRV.

test: use clearer expression for CI testing

---

src/uucore/src/lib/lib.rs

Avoid panic when using
seq 1 >/dev/full
Should move tests/csplit/csplit-io-err.sh from ERROR to SKIP

handle the error when stdout is full

---

src/uu/du/src/du.rs
tests/by-util/test_du.rs

This PR shows an "invalid zero-length file name" error when using `printf "\0" | du --files0-from=-`. The same error is shown if such a name is listed in the file specified with `--files0-from=some-file`.
It makes the tests `nul-1` and `nul-2` in https://github.com/coreutils/coreutils/blob/master/tests/du/files0-from.pl pass.

du: show error for nul names with `--files0-from`

---

src/uu/du/src/du.rs
tests/by-util/test_du.rs

This PR ignores duplicate file names, whether they are piped in or read from a file specified with `--files0-from=some-file`. It makes the [files0-from.pl](https://github.com/coreutils/coreutils/blob/master/tests/du/files0-from.pl) GNU test pass.

du: ignore duplicate names with `--files0-from`

---

.github/workflows/fuzzing.yml
fuzz/Cargo.toml
fuzz/fuzz_targets/fuzz_common.rs
fuzz/fuzz_targets/fuzz_cut.rs
fuzz/fuzz_targets/fuzz_sort.rs
fuzz/fuzz_targets/fuzz_split.rs
fuzz/fuzz_targets/fuzz_wc.rs

to merge after
https://github.com/uutils/coreutils/pull/5758

Add new fuzzers: cut, sort, split and wc 

---

fuzz/fuzz_targets/fuzz_common.rs

fuzz: reset the exit code global variable after every test

---

src/uucore/src/lib/features/backup_control.rs
src/uucore/src/lib/features/fs.rs
src/uucore/src/lib/parser/parse_size.rs
src/uucore/src/lib/parser/shortcut_value_parser.rs

- `Path::new()` returns a `&Path` and does not need to be dereferenced
- Some types can be deduced from the context and are well visible already (`parse_size_u128()` or `from_bytes()`)

uucore: fix style in tests

---

src/uu/cp/src/copydir.rs
src/uu/cp/src/cp.rs
src/uu/mv/src/mv.rs
src/uucore/src/lib/features/fs.rs
tests/by-util/test_cp.rs
tests/by-util/test_mv.rs
util/build-gnu.sh

should fix tests/mv/trailing-slash.sh

cp/mv: manage with trailing slash in target

---

src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

This PR aims to support the QUOTING_STYLE environment variable as proposed [here](https://github.com/uutils/coreutils/pull/5553#pullrequestreview-1761217383).

ls: Support QUOTING_STYLE environment variable

---

src/uuhelp_parser/Cargo.toml

When viewing the crate right now, apart from via looking at the dependencies it's hard to find the associated project and repository.
Add the missing info.

uuhelp_parser: add links to homepage and repo

---

src/uucore/src/lib/features/fs.rs

Add support for sparc64 in uucore to avoid the following build failure with nushell:
```
error[E0308]: mismatched types
--> /home/autobuild/autobuild/instance-7/output-1/build/nushell-0.85.0/VENDOR/uucore/src/lib/features/fs.rs:121:16
|
111 |     pub fn number_of_links(&self) -> u64 {
|                                      --- expected `u64` because of return type
...
121 |         return self.0.st_nlink;
|                ^^^^^^^^^^^^^^^ expected `u64`, found `u32`
|
help: you can convert a `u32` to a `u64`
|
121 |         return self.0.st_nlink.into();
|                               +++++++
For more information about this error, try `rustc --explain E0308`. error: could not compile `uucore` (lib) due to previous error
```
Fixes:
- …

uucore: add support for sparc64

---

src/uucore/src/lib/features/format/num_format.rs
tests/by-util/test_seq.rs

The output of `seq` had two issues:
- The default precision for `%g` was set to 0 instead of 6
- Numbers whose integer part was larger than the precision and ended with zeroes (such as 10) where erroneously truncated by removing the trailing significant `0`.
Fix #5766

Fix seq output

---

src/uu/cksum/src/cksum.rs
tests/by-util/test_cksum.rs

This PR should fix https://github.com/uutils/coreutils/issues/5792. Now an error is generated if the blake2b algorithm is used on a directory.

Made cksum return an error if the algorithm blake2b is used on a directory.

---

tests/by-util/test_head.rs

This PR disables some tests on Android that fail with "Permission denied" errors while trying to access `/sys/kernel/profiling` and files in `/proc`.

head: disable some tests on Android

---

.github/workflows/android.yml

This PR runs Android with `-no-window` and is an attempt to get rid of the Javascript-related errors like 
```
INFO    | Critical: Uncaught TypeError: Cannot read property 'update' of undefined (qrc:/html/js/location-mock-web-channel.js:130, (null))
INFO    | Critical: Failed to load https://maps.googleapis.com/maps/api/mapsjs/gen_204?csp_test=true: The 'Access-Control-Allow-Origin' header has a value 'qrc://' that is not equal to the supplied origin. Origin 'qrc://' is therefore not allowed access. (qrc:/html/js/location-mock-web-channel.js:0, (null))
INFO    | Critical: Failed to load https://maps.googleapis.com/maps/api/mapsjs/gen_204?csp_test=true: The 'Access-Control-Allow-Origin' header has a value 'qrc://' that is not equal to the supplied origin. Origin 'qrc://' is therefore not …
```

ci: set -no-window in Android workflow

---

src/uucore/src/lib/features/format/argument.rs
src/uucore/src/lib/features/format/mod.rs
src/uucore/src/lib/features/format/num_parser.rs
tests/by-util/test_printf.rs

This makes printf more compatible with its GNU coreutils counterpart.
- format: %c prints the first character of a string
- format: parse as many characters as possible in numbers and make the error messages more compatible with GNU coreutils

printf compatibility

---

src/uucore/src/lib/features/format/escape.rs
tests/by-util/test_printf.rs

``` bash
$ printf '\#\"\$'
\#"\$
```

printf: output of double-quote should not be escaped

---

src/uucore/src/lib/features/format/argument.rs
tests/by-util/test_printf.rs

printf: %c prints the first byte of its argument

---

src/uu/printf/src/printf.rs
tests/by-util/test_printf.rs

Fixes #5815
```bash
$ printf a b
a
```
This PR adds a test for this behaviour. at this moment - the iter from `parse_spec_and_escape` function won't consume `args` if no format string is present and goes to an infinite loop.
https://github.com/uutils/coreutils/blob/edb77b8d591a1f0653a35f462923aaa7fb61b574/src/uu/printf/src/printf.rs#L49-L54

printf : no infinite loop

---

.github/workflows/CICD.yml
Cargo.lock
deny.toml

This PR bumps `console` from `0.15.7` to `0.15.8` and `mio` from `0.8.6` to `0.8.10` in order to reduce the number of crates that depend on `windows-sys 0.45.0` to one (`notify`).

Bump console and mio

---

src/uu/cut/src/cut.rs
tests/by-util/test_cut.rs

cut: allow the same option to be passed multiple times

---

tests/by-util/test_head.rs

This PR fixes some clippy warnings from the [len_zero](https://rust-lang.github.io/rust-clippy/master/index.html#/len_zero) lint in the tests.

head: fix clippy warnings in tests

---

tests/by-util/test_pathchk.rs

This PR renames `test_args_parsing` to `test_no_args` and simplifies the test. And it removes some useless comments.

pathchk: simplify and rename test

---

src/uu/nl/src/nl.rs
tests/by-util/test_nl.rs

When specifying a directory instead of a file, GNU `nl` shows an error but keeps printing the output of the next file(s):
```
$ nl dir file
nl: dir: Is a directory
1  content
```
uutils `nl`, on the other hand, shows an error and exits:
```
$ cargo run nl dir file
nl: could not read line: Is a directory
```
This PR makes uutils `nl` skip directories and show the same error as GNU `nl`.

nl: don't exit if input is directory

---

src/uu/cp/src/cp.rs
tests/by-util/test_cp.rs

When running `cp --link a a`, GNU `cp` doesn't do anything whereas uutils `cp` shows a "same file" error. This PR adapts the behavior of uutils `cp` to match the one of GNU `cp`.

cp: show no "same file" error for `--link a a`

---

src/uu/cp/src/cp.rs
tests/by-util/test_cp.rs

This PR covers a special case of https://github.com/uutils/coreutils/pull/5731, with the destination being a symlink to the source. So far this caused a "same file" error whereas it works fine with GNU `cp`.

cp: backup dest symlink linking to source

---

Cargo.lock
deny.toml

This PR bumps `redox_syscall` from `0.3.5` & `0.4.0` to `0.4.1`, `filetime` from `0.2.22` to `0.2.23`, and 
`parking_lot_core` from `0.9.8` to `0.9.9`.

Bump redox_syscall to 0.4.1

---

src/uucore/src/lib/features/format/num_format.rs

uucore: fix clippy warning from if_not_else lint

---

Cargo.lock
Cargo.toml
src/uu/cp/src/cp.rs
tests/by-util/test_cp.rs

Should help with tests/cp/acl.sh

cp: --preserve should keep xattr

---

src/uu/base32/src/base_common.rs
src/uu/expand/src/expand.rs
src/uu/factor/src/cli.rs
src/uucore/src/lib/features/encoding.rs
tests/by-util/test_basenc.rs
tests/by-util/test_expand.rs
tests/by-util/test_factor.rs

for these two fixes, it was breaking some Rust errors
tested in tests/misc/read-errors.sh

Handle better some errors

---

src/uu/install/Cargo.toml
src/uu/install/src/install.rs
tests/by-util/test_install.rs

adresses issue #5718
there where two issues:
1. stdout from strip program wasn't forwarded
2. "./" was applied redundantly (`././-dest`) as the check was on the filename (without path)
Tests are extented accordingly

install: fix strip program stdout and destination hyphen handling #5718

---

.github/workflows/CICD.yml
src/uucore/src/lib/features/sum.rs

I think this should fix https://github.com/uutils/coreutils/pull/5783/files#r1447343162
The problem is that we were testing uucore without any features enabled, which led to a lot of tests being ignored.
In general it might be time to refactor our workflows a bit and make them a bit more uniform. The MSRV, codecov and regular builds all seem to be doing slightly different things.

CI: test `uucore` with `coreutils` in codecov to run it with the proper features

---

src/uu/tsort/src/tsort.rs
tests/by-util/test_tsort.rs

tsort: returns error when input is dir - same as GNU tsort

---

tests/by-util/test_pinky.rs
tests/by-util/test_uptime.rs
tests/by-util/test_who.rs

pinky, uptime and who are not supported on OpenBSD (no support of utmpx feature, see PR uutils/coreutils#5620) => disable tests for these tools on OpenBSD with conditional compilation
No need to disable tests for users (tool not supported on OpenBSD)

tests: disable tests for tools unsupported on OpenBSD

---

src/uu/hashsum/src/hashsum.rs
tests/by-util/test_hashsum.rs

Should fix tests/cksum/md5sum-newline.pl

hashsum: when the filename contains some special chars, escape them

---

src/uu/expand/src/expand.rs
tests/by-util/test_expand.rs

Should fix https://github.com/uutils/coreutils/issues/5872
I also added the unit test.

expand: Continue work when one of given files doesn't exist

---

tests/by-util/test_expand.rs

This PR replaces an invisible trailing tab in a test with `\t`.

expand: make tab explicit in test

---

src/uu/factor/build.rs
src/uu/factor/src/factor.rs
src/uu/factor/src/miller_rabin.rs
tests/by-util/test_factor.rs

Closes: #5884
first dabbling with uutils. Trying to be helpful.

factor: remove clippy exceptions by reformatting "unreadable literals"

---

src/uu/cp/src/cp.rs

Could not even reproduce what they would complain for. Closes: #5885
I went back to the commit introducing these, but with today's carg/clippy, warning did not show up

cp: remove lint exceptions

---

fuzz/fuzz_targets/fuzz_sort.rs

The output of GNU `sort` in https://github.com/uutils/coreutils/issues/5849 doesn't seem to use the C locale, even though `LC_COLLATE=C` is set before running GNU `sort`. The help says to set `LC_ALL=C`:
```
The locale specified by the environment affects sort order.
Set LC_ALL=C to get the traditional sort order that uses
native byte values.
```
On my machine I don't see a difference, both `LC_COLLATE=C` and `LC_ALL=C` lead to the same `sort` output. So I'm not sure whether this PR will fix the issue.

fuzzing: use LC_ALL instead of LC_COLLATE

---

src/uu/factor/src/rho.rs

Closes: #5883
Clippy warns if there are more than 4 single-character local variables.
I looked up the original papers for that algorithm and I don't see any sense renaming `x,y or d`.
I see the best solution in renaming the input parameter.

factor: rename input parameter

---

tests/by-util/test_cp.rs
util/android-commands.sh

this is what {termux}/scripts/termux-change-repo.in does at the end
this is an attemp at fixing #5893 which tries an unreachable mirror

util: android disable mirror selection

---

.github/workflows/code-quality.yml
src/uu/cp/src/cp.rs
src/uu/nl/src/helper.rs
src/uu/numfmt/src/format.rs
src/uu/sort/src/numeric_str_cmp.rs
src/uu/sort/src/sort.rs
src/uu/split/src/split.rs
src/uu/uniq/src/uniq.rs
src/uu/wc/src/wc.rs
src/uucore/src/lib/parser/parse_size.rs

ran clippy with clippy::range-plus-one, clippy::redundant-closure-for-method-calls and fix those where I was confident this is
a) improvement to the reader
b) does not make lines longer, no additional imports

Clippy suggestions

---

Cargo.lock
tests/by-util/test_rm.rs

This PR bumps `wild` from `2.2.0` to `2.2.1` which fixes https://github.com/uutils/coreutils/issues/3200

Bump wild from 2.2.0 to 2.2.1

---

src/uu/dd/src/parseargs.rs
src/uu/dd/src/parseargs/unit_tests.rs

Change the behavior of `dd` so that it parses numbers that would be too big and instead treats them as `u64::MAX`. This allows `dd` to run without error on
dd count=00x9999999999999999999999999999999999999999999999999999999999999
This matches the behavior of GNU `dd`. This test case appears in GNU test suite `tests/dd/misc.sh`.

dd: parse big numbers and return u64::MAX

---

src/uu/wc/src/wc.rs

refactor wc.rs to remove clippy's cognitive complexity lint.
closes: [uutils#5882](https://github.com/uutils/coreutils/issues/5882)

refactor wc.rs to remove clippy's cognitive complexity lint

---

src/uu/echo/src/echo.rs
tests/by-util/test_echo.rs

Closes https://github.com/uutils/coreutils/issues/5910

`echo`: do not infer long args

---

.github/workflows/android.yml

working against 
```
/bin/sh -c \/Users/runner/Library/Android/sdk/emulator/emulator -avd test -no-window -no-snapshot-save -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -snapshot 28-x86+termux-v0.118.0 &
INFO    | Android emulator version 33.1.24.0 (build_id 11237101) (CL:N/A)
INFO    | Found systemPath /Users/runner/Library/Android/sdk/system-images/android-28/default/x86/
ERROR   | Running multiple emulators with the same AVD 
ERROR   | is an experimental feature.
ERROR   | Please use -read-only flag to enable this feature.
INFO    | Storing crashdata in: , detection is enabled for process: 1367
INFO    | Duplicate loglines will be removed, if you wish to see each individual line launch with the -log-nofilter flag.
INFO    | Increasing RAM size to 1536MB
```

ci: android delete AVD lockfile when running from cached image

---

src/uu/dd/src/parseargs.rs
src/uucore/src/lib/parser/parse_size.rs
tests/by-util/test_dd.rs

Simple fix that adds a flag for dd when empty string is not allowed for units of count in dd

dd: fail on missing number in count, fix #5904

---

src/uu/du/src/du.rs
tests/by-util/test_du.rs

This PR adapts the error message shown if a specified doesn't exist to match GNU's message. It also modifies the corresponding test to ensure multiple errors are shown if there are multiple non-existing files specified.

du: adapt error message to match GNU's

---

.github/workflows/android.yml

This PR enables Android x86_64 in the CI/CD as suggested in https://github.com/uutils/coreutils/pull/5821 and should be merged after it.

ci: add Android x86_64

---

.github/workflows/CICD.yml

https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

github action: run on native m1 - and execute the tests

---

src/uu/stat/src/stat.rs
tests/by-util/test_stat.rs

fix the issue
now it give same output as GNU

 stat: should fail without arguments #5928

---

.github/workflows/android.yml
src/uucore/src/lib/features/fsext.rs
util/android-commands.sh
util/android-scripts/collect-info.sh
util/android-scripts/run-tests.sh

I did the following changes which make the build significantly more robust:
- increase RAM and disk size (from original 1.5GB to: 4GB ram -> x86, 8GB ram -> x86_46, disk: 12GB)
- use own pre-defined mirror list for termux package manager to be able to disable brocken mirrors
- install (install sshd and a public key from runner) and use ssh connection to termux for less error prone scripting on android with more reliable progress and error reporting
- periodically print disk- and ram-usage during test execution to see if we run into ressource issues
- limit available memory for test execution to 3GB (ulimit) to avoid that the OS kills the sshd server process
- when using "adb shell input text" split the transmition into chunks to support longer commands.
- take and upload screenshots …

`ci:android` stabilize and improve android github actions

---

.github/workflows/code-quality.yml
docs/compiles_table.py
src/uu/factor/src/numeric/montgomery.rs
src/uucore/src/lib/parser/shortcut_value_parser.rs
tests/by-util/test_ls.rs
tests/by-util/test_nl.rs
util/size-experiment.py

This PR uses the latest version of `cspell` in the `code-quality` workflow and fixes the spelling errors shown by it.

ci: use latest version of `cspell`

---

src/uu/tr/src/tr.rs
tests/by-util/test_tr.rs

fixes the issue #5944 where tr -d flag should not take more than one operand
so its like this now
```
❯ echo "acsd5c"| ./target/debug/tr -d "c"
asd5
~/sad/coreutils main
❯ echo "acsd5c"| ./target/debug/tr -d "c" "p"
./target/debug/tr: extra operand 'p'
Only one string may be given when deleting without squeezing repeats.
Try './target/debug/tr --help' for more information.
```
problem tho is that adding more arguments errors out tr when it should just display the same massage
where gnu tr
```
❯ echo "acsd5c"| tr -d "c" "p" "m"
tr: extra operand ‘p’
Try 'tr --help' for more information.
```
coreutils one 
```
❯ echo "acsd5c"| ./target/debug/tr -d "c" "p" "m"
error: unexpected value 'm' for '[sets]...' found; no more were expected
Usage: ./target/debug/tr [OPTION]... SET1 [SET2]
For more …
```

fix tr with delete flag if more than 1 operand given 

---

Cargo.lock

This PR bumps `smallvec` from `1.13.0` to `1.13.1` to fix a "yanked crate" warning from `cargo deny`.

Bump smallvec from 1.13.0 to 1.13.1

---

src/uu/nohup/src/nohup.rs
src/uu/od/src/mockstream.rs
src/uu/pr/src/pr.rs
tests/by-util/test_cat.rs
tests/common/util.rs

This PR fixes clippy warnings from the [blocks_in_conditions](https://rust-lang.github.io/rust-clippy/master/index.html#/blocks_in_conditions), [ineffective_open_options](https://rust-lang.github.io/rust-clippy/master/index.html#ineffective_open_options) and [test_attr_in_doctest](https://rust-lang.github.io/rust-clippy/master/index.html#/test_attr_in_doctest) lints.

clippy: fix warnings introduced by Rust 1.76

---

src/uucore/src/lib/features/format/num_format.rs
tests/by-util/test_printf.rs

See https://github.com/uutils/coreutils/pull/5794#issuecomment-1931824910
```
printf 'before %#15.6o after' 42
```
Expected (and this PR):
```
before          000052 after
```
Current main branch:
```
before          052    after
```
Note: this PR has expanded in scope a bit. It turned out that the padding logic was faulty for unsigned numbers, so I fixed that, which fixes the problem with `0` as well.

`printf`: pad unsigned numbers properly

---

src/uu/tsort/src/tsort.rs

To reduce the copying happening in `tsort`, we can load the entire input in memory and only refer to slices within that input instead of allocating a `String` for each occurrence of a node.
cc @anastygnome 
On my input generated with:
```python
import random
random.seed(0)
N = 10000
for i in range(100*N):
a = random.randint(0,N)
b = random.randint(0,N)
if a != b:
print(f"{min(a, b)} {max(a, b)}")
```
The time measured with hyperfine drops from ~2.3 seconds to ~1.6 seconds.

`tsort`: drastically reduce memory copies

---

src/uu/date/src/date.rs
src/uu/ls/src/ls.rs

This PR renames `chrono::Duration` to `chrono::TimeDelta` because in the latest [chrono release](https://github.com/uutils/coreutils/pull/5967) they did the same. While `chrono::Duration` still works for the time being, I think it makes sense to use the "official" name.

ls,date: rename `chrono::Duration` to `chrono::TimeDelta`

---

.github/workflows/CICD.yml

Fixes 4d2bdf4. For a release to be triggered, the workflow has to run with GITHUB_REF=refs/tags/X.Y.Z, which was disabled by limiting the push trigger to a branch.
Please note that the tag filter `v*.*.*` does not work since releases are tagged like `0.0.24`.
<strike>This will create extra runs in case branches are created in the uutls/coreutils repo.
I think this is an acceptable tradeoff.</strike>
See also: 
- https://github.com/uutils/coreutils/issues/5929
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-branches-and-tags
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#create

ci: run CICD workflow on tag creation

---

src/uu/head/src/head.rs
src/uu/split/src/split.rs
src/uucore/src/lib/features/fs.rs

`split` allocates quite some memory when reading from "files" with no real end like `/dev/zero`.
On x86 its ~ 1GB and on x86_x64 its 2GB. This was cause frequent stability issues on android CI.
This change limits the initially read memory heavily to the `blksize` of the filesystem or 500MB at max if no blksize is specified. This is aligned with a solution used in `head`

`split` fix android memory kill in split

---

src/uu/tr/src/tr.rs
tests/by-util/test_tr.rs

turns out all tr flags should fail with the same massage not just delete flag if the number of operands is more than 2 so i rewrote the part i did write so all the flags fails with more than 2 operand 
so now 
```
gnu tr:
>tr -s a b c
tr: extra operand ‘c’
Try 'tr --help' for more information.
[ble: exit 1]
~
>tr -d a b c
tr: extra operand ‘b’
Try 'tr --help' for more information.
[ble: exit 1]
and uutils tr 
>cargo run tr -s a b c
Compiling coreutils v0.0.24 (/home/broly/sad/coreutils)
Finished dev [unoptimized + debuginfo] target(s) in 2.68s
Running `target/debug/coreutils tr -s a b c`
tr: extra operand 'c'
Try 'target/debug/coreutils tr --help' for more information.
[ble: exit 1]
>cargo run tr -d a b c
Finished dev [unoptimized + debuginfo] target(s) in 0.10s
Running …
```

fix tr with any flag with more than 2 operands 

---

src/uu/cut/src/cut.rs
tests/by-util/test_cut.rs

`uutils-cut` runs without an error when there are multiple cutting mode arguments of one type, i.e. more than one `--bytes`, or `--characters`, or `--fields`, while GNU cut shows an error as described in GNU cut manual - _`"Use one, and only one of -b, -c or -f."`_
For example:
```bash
$ echo "12345" | cargo run cut -c1 -c5
5
$ echo "12345" | cut -c1 -c5
cut: only one list may be specified
Try 'cut --help' for more information.
```
Duplicated arguments were overriding the previous ones, therefore only the last cutting mode argument (`-b`, `-c`, `-f`) was handled, as you can see on the example above.
Disable overriding of cutting mode arguments (`-b`, `-c`, `-f`) using `ArgAction::APPEND`. Count the number of the cutting mode arguments and show an error when there are more than one `-b`, …

cut: show error for multiple mode args (`-b`, `-c`, `-f`)

---

tests/by-util/test_pr.rs

Replaced `time` with `crono` for pr test

 pr: use chrono instead of time in tests #5972

---

src/uu/shuf/src/shuf.rs
tests/by-util/test_shuf.rs

This PR makes shuf behave more like GNU shuf in the case of empty files (e.g. null stdin).
Old behavior:
```console
$ true | cargo run -- shuf | hd
00000000  0a                                                |.|
00000001
$
```
GNU behavior:
```console
$ true | shuf | hd
$
```
New behavior:
```console
$ true | cargo run -- shuf | hd
$
```
Note that this also makes `shuf-reservoir.sh` in the GNU shuf tests happy.
I'm [mostly](https://github.com/uutils/coreutils/pull/5978) new to uutils, so please do point out any resources that might help me. (I've already read {DEVELOPMENT,CONTRIBUTING,CODE_OF_CONDUCT}.md.)

shuf: Treat empty file as zero elements instead of one emptystring

---

src/uu/shuf/src/shuf.rs
tests/by-util/test_shuf.rs

This PR fixes all `shuf` bugs around repeated arguments:
- GNU shuf considers all arguments to `--echo`.  uutils `shuf` currently only considers the very last `--echo`, and ignores all the others.
- GNU shuf accepts multiple head-counts (`-n`), effectively only considering the *lowest*. uutils `shuf` currently only considers the very last `--head-count`, and ignores all the others.
- GNU shuf rejects repeated input ranges and output files with a clear error message. uutils `shuf` currently only considers the very last element each, silently ignoring all the others.
This is clearly buggy, since command-line arguments should be ignored only in exceptional cases. This appears to be a regression after #3329.
In this PR I'm fixing these and adopt the behavior of GNU, which is in my eyes the …

shuf: include all echo args, not just the last

---

tests/by-util/test_od.rs

As discussed and agreed in #5941, the test gets disabled for android CI.
I disabled it for android on x86 and x86_64.

disable failing test_od::test_f16() for android CI

---

src/uu/numfmt/src/numfmt.rs

I'm on a quest to delete some uses of `collect_{lossy,ignore}` 😄

`numfmt`: remove clap workaround

---

src/uu/cp/src/cp.rs
src/uu/env/src/env.rs
src/uu/join/src/join.rs
src/uu/od/src/multifilereader.rs
src/uu/pr/src/pr.rs
src/uu/ptx/src/ptx.rs
src/uu/sleep/src/sleep.rs
src/uu/stat/src/stat.rs
src/uu/timeout/src/status.rs
src/uu/wc/src/utf8/read.rs
src/uucore/src/lib/features/backup_control.rs
src/uucore/src/lib/features/encoding.rs
src/uucore/src/lib/features/fsext.rs
src/uucore/src/lib/features/perms.rs
src/uucore/src/lib/features/utmpx.rs
src/uucore/src/lib/mods/error.rs
tests/by-util/test_touch.rs

This PR fixes the "item x imported redundantly" warnings that show up in the CI using the nightly builds (see, for example, https://github.com/uutils/coreutils/actions/runs/7957254785/job/21719731331, "Test" step).

Fix "item x imported redundantly" warnings

---

src/uu/shuf/src/shuf.rs
tests/by-util/test_shuf.rs

This PR implements and tests support for the weird permitted argument order of `shuf`, especially for invocations like `shuf -ez firstarg secondarg`, where the `z` shall not be interpreted as a value to `-e`.
This moves us closer to passing the GNU testsuite.
Related:
- Discussed in https://github.com/uutils/coreutils/issues/4254#issuecomment-1953201152 (turns out, I was wrong, it *is* possible)
- Relates to https://github.com/uutils/uutils-args/pull/104 (which is kinda the same patch, but using the new `uutils-arg`).
This PR sadly slightly degrades the quality of the error message in one case:
Before:
```console
$ cargo run -- a b
error: unexpected argument 'b' found
Usage: /path/to/target/debug/shuf [OPTION]... [FILE]
/path/to/target/debug/shuf -e [OPTION]... [ARG]... …
```

shuf: treat -e as a flag, not as a multi-value arg

---

src/uu/tr/src/tr.rs
tests/by-util/test_tr.rs

Found while playing around with multiple arguments, and comparing with GNU `tr` output:
- We used to accept invocations with only one string; note that this never makes sense with `tr -ds`, for example.
- We used to complement the second set in `tr -cds`, even though our `--help` text already correctly points out that `-c` only complements `SET1`, not `SET2`.

tr: Properly handle deleting and squeezing

---

tests/by-util/test_dd.rs

If the first four decimal digits are zero, GNU dd elides them altogether. Here's an execution on my PC:
```console
$ for i in $(seq 20000); do LC_ALL=C gnu_dd if=/dev/null of=/dev/null \
2>&1; done | grep copied | grep -E ' [0-9]e'
0 bytes copied, 1e-05 s, 0 B/s
0 bytes copied, 9e-06 s, 0.0 kB/s
```
Our implementation conforms to this, resulting in the following CI flake:
```
---- test_dd::test_final_stats_unspec stdout ----
run: D:\a\coreutils\coreutils\target\x86_64-pc-windows-gnu\debug\coreutils.exe dd
thread 'test_dd::test_final_stats_unspec' panicked at 'Stderr does not match regex:
0+0 records in
0 bytes copied, 8e-05 s, 0.0 B/s
', tests\by-util\test_dd.rs:280:10
stack backtrace:
0: rust_begin_unwind
at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library\std\src/p …
```

dd: fix flaky test_final_stats_unspec

---

tests/by-util/test_head.rs
tests/by-util/test_touch.rs

This PR un-ignores two tests:
- `test_head::test_spams_newline` set a wrong expectation. A simple comparison with GNU head and busybox head reveals that the test was flawed, and plugging in the correct output passes the test.
- `test_touch::test_touch_invalid_date_format` had a simple typo: Apparently someone accidentally copy-pasted typographic quotation marks instead of the usual "ASCII" quotation marks. Changing this passes the test.

Un-Ignore two tests that fail for nonsense reasons

---

src/uu/shuf/src/shuf.rs
tests/by-util/test_shuf.rs

This is explicitly tested by some suites, including the GNU test suite.
Together with #5980 and #5989, this should make uutils pass the GNU test suite for shuf. Yay! :D

shuf: Do not read input when -n0 is given

---

src/uu/shuf/BENCHMARKING.md
src/uu/shuf/src/shuf.rs
tests/by-util/test_shuf.rs

`gnu_shuf -n10 -r -i0-4294967295` will run perfectly fine on virtually all platforms, and allocates only 2 MiB.
`uushuf -n10 -r -i0-4294967295` immediately OOMs with `memory allocation of 103079215104 bytes failed`, and probably needs at least 137 GiB of RAM and several hours if not weeks to actually work.
> Differences with GNU are treated as bugs.
This PR fixes this crash bug, by treating number ranges specially:
- The first commit extracts a common interface between `Vec<&[u8]>` and the "number range" concepts.
- The second commit implements and tests a special implementation for the number range case.
- The third commit adds some documentation.
The "special implementation" is a really stupid approach. I'm sure this can be optimized further (e.g. bitsets?), but first let's get this …

shuf: Fix OOM crash for huge number ranges

---

src/uu/tr/src/tr.rs
tests/by-util/test_tr.rs

Before:
```console
$ echo abbbcddd | tr -tt abc x  # GNU
xbbbcddd
$ echo abbbcddd | cargo run tr -tt abc x
error: the argument '--truncate-set1' cannot be used multiple times
Usage: target/debug/coreutils tr [OPTION]... SET1 [SET2]
For more information, try '--help'.
[$? = 1]
$
```
After:
```
$ echo abbbcddd | cargo run tr -tt abc x
xbbbcddd
```
This fixes #5998 for the special case of `tr`.

tr: Correctly handle multiple appearances of flag-args

---

tests/by-util/test_pr.rs

The test `test_pr::test_with_pr_core_utils_tests` is flaky, and causes [real problems](https://github.com/uutils/coreutils/pull/5980#issuecomment-1962726133).
Here's a branch that makes the bug 100% reproducible, by injecting "lag" at critical moments: https://github.com/BenWiederhake/coreutils-rs/tree/historic/demo-pr-test-race
The bug is best explained by the fix:
```diff
let input_file_path = input_file.first().unwrap();
let test_file_path = expected_file.first().unwrap();
-    let value = file_last_modified_time(&scenario, test_file_path);
+    let value = file_last_modified_time(&scenario, input_file_path);
let mut arguments: Vec<&str> = …;
arguments.extend(input_file.clone());
// "value" is then used to construct the expected output.
```
In other words: `value` is the last modified …

pr: Check the correct timestamp in test_with_pr_core_utils_tests

---

src/uu/chmod/src/chmod.rs
tests/by-util/test_chmod.rs

Fix for issue #6009.
I changed the code so that the old permission octal is retrieved in "full form" (6 octal digits). It is afterwards set to 4 digits when displayed.
Beforehand, 2 identical permissions were marked as different because of the different formats, resulting in incorrect displays for `-c`.

chmod: Fix chmod -c --reference reporting when no change is made

---

src/uu/basename/basename.md
src/uu/basename/src/basename.rs
tests/by-util/test_basename.rs

This fixes several GNU behavior bugs around repeated arguments. In my eyes, the parsing code is now simpler, too.
Note in particular that `args_override_self` would *NOT* work here, since it would in all cases cause `options::NAME` to override itself, or interfere with `trailing_var_arg`.
This fixes #5998 for the special case of basename.
<details><summary>Notes on the GNU documentation bug</summary>
The GNU basename help suggests that `-z` immediately implies "multi-name mode", because it cannot appear in the first pattern:
```console
$ basename --help
Usage: basename NAME [SUFFIX]
or:  basename OPTION... NAME...
```
However, that is evidently wrong:
```console
$ basename -z tool l  | hd
00000000  74 6f 6f 00                                       |too.|
00000004
```
If `-z` would imply …

basename: Fix handling of repeated flags/arguments

---

src/uu/base32/src/base_common.rs
src/uu/basenc/src/basenc.rs
tests/by-util/test_base32.rs
tests/by-util/test_base64.rs
tests/by-util/test_basenc.rs

This PR fixes several issues:
- Basic functionality of `basenc` was not tested – it already works, yes, but let's make sure it doesn't regress.
- `basenc` should not decide according to some arbitrary built-in priority list (`ENCODINGS`), but rather let the last encoding on the command-line override any earlier ones. (This fixes a GNU behavior bug.)
- Permit repeated flags on the command-line; i.e. the flags `-d`, `-i`, and `-w`. (This fixes a GNU behavior bug.)
This fixes #5998 for the special case of `base32`, `base64`, and `basenc`.

base32/base64/basenc: implement and test proper flag parsing

---

src/uu/shuf/src/shuf.rs
tests/by-util/test_shuf.rs

This was a GNU behavior bug:
```console
$ LC_ALL=C shuf -er
shuf: no lines to repeat
[$? = 1]
$ cargo run shuf -er  # old, bad (unexpected success)
$ cargo run shuf -er  # new
shuf: no lines to repeat
[$? = 1]
```
Note that this bug already existed *before* #5980 and my other shuf-related PRs.
This should also fix the last testcase of the GNU shuf test.

shuf: Refuse repeating zero lines

---

tests/by-util/test_cat.rs
tests/by-util/test_numfmt.rs
tests/by-util/test_sort.rs
tests/by-util/test_split.rs
tests/by-util/test_tee.rs

This PR improves the tests:
- Two tests were unnecessarily lax (`test_tee_no_more_writeable_1` ignored memory problems, the new `test_check_unique_combined` exercises an input that wasn't possible before clap#2624)
- Four tests had the potential to flake: They were writing to the stdin of a process that might have already terminated.
My goal was to find any flaky tests like 9995c637aa5de190ddce0abc4be36d773797f1bc: When we write a large buffer to the stdin of a process that will fail at some point, then a race happens:
- Perhaps the write happens first, and the kernel buffer is large enough to accept it entirely. In that case, the write is successful, and the writer thread terminates normally. This is likely to happen on a developer machine.
- Perhaps the write happens later, and the …

tests: Harden two tests, prevent 4 flaky tests (cat, numfmt, sort, split, tee)

---

util/android-commands.sh
util/android-scripts/run-tests.sh

tries to address #5992 
UDPATE: It really helps. See comments.

Android CI: workaround: run builds with retry

---

.cargo/config.toml

https://blog.rust-lang.org/2024/02/28/Clippy-deprecating-feature-cargo-clippy.html

cargo: fix feature = "cargo-clippy" deprecation

---

src/uucore/src/lib/features/format/argument.rs
src/uucore/src/lib/features/format/spec.rs
tests/by-util/test_printf.rs

Fixes #5826
```
❯ /bin/printf %c 🙃 | hexdump          
0000000 00f0                                   
0000001
```
```
❯ ./target/debug/printf %c 🙃 | hexdump
0000000 b0c3                                   
0000002
```
```
❯ ./target/debug/printf %c 🙃 | hexdump 
0000000 00f0                                   
0000001
```

printf: Make printf operate on bytes instead of strings 

---

src/uucore/src/lib/features/format/spec.rs
tests/by-util/test_printf.rs

Fix #6030 
For now I just added tests to check that the error is raised, I will provide implementation later on

printf: '%0c' and '%0s' should fail

---

tests/by-util/test_cp.rs

Fixes #4725
This fixes a flaky test that causes [real problems](https://github.com/uutils/coreutils/pull/6018#issuecomment-1963035379).
As the test already documents, `-u -i` won't show a prompt, so trying to pipe some stdin into it is pointless, and also causes a race.

cp: fix flaky test test_cp_arg_interactive_update, document adjacent bug

---

Cargo.toml
tests/by-util/test_nohup.rs
tests/common/util.rs
tests/fixtures/nohup/is_atty.sh
tests/fixtures/util/is_atty.sh

addresses #5785
and addresses #1857
replaces if accepted PR #5858
let me know what you think. It's very easy to use. Just do a `.simulate_terminal(true)` and thats it.
I implemented in such a way that also stdin piping still works and also the capturing of stdout and stderr works as usual.
EDIT: For cases where the terminal size matters, there is no an additional function available:
```
.terminal_size(libc::winsize {
ws_col: 40,
ws_row: 10,
ws_xpixel: 40 * 8,
ws_ypixel: 10 * 10,
})
```
Example:
```rust
#[test]
fn test_simulation_of_terminal_true() {
let scene = TestScenario::new(util_name!());
let out = scene
.ucmd()
.arg("sh")
.arg("is_atty.sh")
.terminal_simulation(true)
.succeeds();
assert_eq!(
String::from_utf8_lossy(out.stdout()),
"stdin is atty\r\nstdout is atty\r\nstderr is …
```

test utilities: easy way to simulate terminal context

---

.github/workflows/CICD.yml
.github/workflows/GnuTests.yml

Since the recent update of the `codecov` GH action, the "Run GNU tests with coverage" job in `GnuTests.yml` (for example, https://github.com/uutils/coreutils/actions/runs/7766050082/job/21181432457, "Upload coverage results") shows the following error:
```
Error: Codecov token not found. Please provide Codecov token with -t flag.
Warning: Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1
```
This PR sets the required codecov token.

ci: use codecov token in CICD/GnuTests workflows

---

tests/common/util.rs

The recent merge of https://github.com/uutils/coreutils/pull/5869 has an unwanted side effect: running the tests for a single tool shows some failures unrelated to the tool:
```
$ cargo test --features "nl" --no-default-features
[snipped]
failures:
---- common::util::tests::test_simulation_of_terminal_false stdout ----
run: /home/dho/projects/coreutils/target/debug/coreutils env sh is_atty.sh
thread 'common::util::tests::test_simulation_of_terminal_false' panicked at tests/common/util.rs:3590:65:
Command was expected to succeed. Exit code: 1.
stdout = env: function/utility not found
stderr = 
[snipped]
failures:
common::util::tests::test_simulation_of_terminal_false
common::util::tests::test_simulation_of_terminal_pty_pipes_into_data_and_sends_eot_automatically …
```

tests/common/util.rs: add `cfg(feature = "env")`

---

Cargo.lock

This PR bumps `mio` from `0.8.10` to `0.8.11` because of https://github.com/advisories/GHSA-r8w9-5wcg-vfj7

Bump mio from 0.8.10 to 0.8.11

---

Cargo.toml
src/uu/split/src/split.rs
tests/common/util.rs

Addresses #6031
- refactoring: split large function `get_writer` into two parts
- robutify closing of fds by retry until it works or no fds to close left. Previous implemenation did only one try and failed then.
- robustify test setup: add `sleep 0.5 &&` to ensure that the limits are applied before `split` application starts.
_update: I implemented the idea with pre_exec from @tertsdiepraam as replacement for the `sleep 0.5` test-setup fix.
the results of 15*2*54 (1620) runs can be seen here: https://github.com/cre4ture/coreutils/actions/runs/8155517787/job/22291219367?pr=10
There was no single case where the original implementation of split failed._
I proved that both changes on its own fix the flakiness of the test by running all tests on 22 runners, each ~50times:
Evaluation:
the …

Fix/flaky `split` round robin limited fds

---

src/uu/chmod/src/chmod.rs
src/uucore/src/lib/features/fs.rs
src/uucore/src/lib/features/perms.rs
tests/by-util/test_chgrp.rs

This makes the GNU `preserve-root.log` test green.
In particular:
- We used to have the wrong logic to detect whether or not to issue a warning. The root (punt not intended) cause was that `Path::is_dir()` completely ignores whether a given argument has a trailing slash or not, but that is *the* criterion that GNU (and many other tools) apparently uses to decide whether the path points "at" or "into" a directory. (See below for demonstration.)
- chown and chgrp also didn't correctly output an indication why the warning was being given
- And finally, `chmod` simply forgot to output its own name in one place.
Additional notes:
- This makes the uucore function `resolve_relative_path` superfluous. This function is by necessity ill-defined: Depending on the context, `..` is either the logical …

chown+chgrp+chmod: Fix handling of preserve root flag and error messages

---

Cargo.lock
Cargo.toml
src/uu/ls/src/ls.rs
src/uu/touch/src/touch.rs
tests/by-util/test_touch.rs

This PR bumps `chrono` from `0.4.34` to `0.4.35` and replaces the usage of deprecated functions.

Bump chrono to 0.4.35 & replace usage of deprecated functions

---

src/uu/dd/src/parseargs.rs
tests/by-util/test_dd.rs

this fixes `bytes.log` test case of dd  in gnu test coverage #5903.

dd : treat arg as bytes if it contains a 'B'

---

tests/by-util/test_chgrp.rs
tests/by-util/test_pr.rs

This PR fixes three warnings in tests I noticed while reviewing https://github.com/uutils/coreutils/pull/6052 and removes a commented out constant.

pr/chgrp: fix warnings

---

src/uu/chcon/src/chcon.rs
tests/by-util/test_chcon.rs

This PR changes and tests three things:
- Accept `--no-dereference` and `--dereference` in any order, use the last occurrence.
- Accept `--no-preserve-root` and `--preserve-root` in any order, use the last occurrence.
- Accept repetitions of everything, flags and arguments like `--user`.
All three of these are GNU behavior bugs, i.e. GNU does it differently, and uutils wants to handle it like GNU does.
This is work towards #5998.

chcon: Handle repeated flags and overrides between --no-XXX and --XXX

---

src/uu/tr/src/operation.rs
src/uu/tr/src/tr.rs

This should lower memory consumption, and fixes OOM in some scenarios.
Before, buggy behavior:
```console
$ yes | tr -ds a b | head -n5  # GNU
y
y
y
y
y
$ yes | cargo run -- -ds a b | head -n5  # WARNING: THIS CAUSES OOM!
^C
[$? = 130]
$ yes yes | tr -s ye s | head -n5  # GNU
s
s
s
s
s
$ yes yes | cargo run -- -s ye s | head -n5  # WARNING: THIS CAUSES OOM!
^C
[$? = 130]
```
After:
```console
$ yes | cargo run -- -ds a b | head -n5
y
y
y
y
y
$ yes yes | cargo run -- -s ye s | head -n5
s
s
s
s
s
$
```
It might be tempting to factor out the common line `translate_input(&mut locked_stdin, &mut buffered_stdout, op);` from all if-branches. However, note that `op` has distinct types in each case, and virtualizing it (e.g. `let op: Box<dyn SymbolTranslator>`) would incur additional runtime …

tr: Stream output instead of buffering

---

src/uu/shuf/src/shuf.rs
tests/by-util/test_shuf.rs

It seems that I accidentally introduced an off-by-one error in #5980. My bad!
This PR:
- Fixes the off-by-one error by using the standard type `RangeInclusive<usize>`, instead of passing `(usize, usize)` around and hoping that we don't forget whether the range is inclusive or exclusive. (That was the bug.)
- Adds a bunch of tests to make sure this cannot regress. (This is very relevant: `shuf` is somewhat inefficient, especially when permuting a reasonably-large number range.)
- Requires #6011, hence this PR is a draft until #6011 lands
- Adds an intentional GNU behavior bug, see below.
- Does not touch the existing implicit bug around `-n`: `fn parse_head_count` defaults to `std::usize::MAX`, which is technically a bug, but has no practical impact.
Sadly, it seems that GNU shuf is buggy: …

shuf: Fix off-by-one errors in range handling

---

src/uu/cp/src/cp.rs
tests/by-util/test_cp.rs

Should fix tests/cp/attr-existing.sh

cp: improve the support of --attributes-only

---

src/uucore/src/lib/parser/parse_glob.rs

This solves #5584, where the fuzzing would take hours without this.

parser: if closing square bracket not found, stop looking for it again

---

src/uu/hashsum/src/hashsum.rs
tests/by-util/test_hashsum.rs
util/build-gnu.sh

Should fix tests/cksum/md5sum-bsd.sh

 hashsum: also escape/unescape files with checks

---

tests/by-util/test_sort.rs

sort: fix incorrectly placed "}" in test

---

Cargo.lock
Cargo.toml

This PR updates `bstr` crate version from 1.9 to 1.9.1 to fix an issue with handling `stdin` when it is a terminal, i.e. in `cut` it would not exit on Ctrl-D (EOF) input. This check is used in `tty-eof.pl` GNU test.
Reference: https://github.com/BurntSushi/bstr/issues/180

tty: fix for Ctrl-D when stdin is a terminal

---

deny.toml

I noticed that `cargo-deny` shows several "deprecated" warnings (see, for example:  https://github.com/uutils/coreutils/actions/runs/8260400412/job/22595846683). This PR removes the deprecated keys and  opts-in to the new behavior (see also https://github.com/EmbarkStudios/cargo-deny/pull/611).

deny.toml: remove deprecated keys, opt-in to v2

---

src/uu/split/src/split.rs
tests/by-util/test_split.rs

Currently, uutils `split` shows "No such file or directory" twice if the specified file doesn't exist. This PR fixes the issue.

split: fix error message shown if file doesn't exist

---

src/uucore/src/lib/features/perms.rs
tests/by-util/test_touch.rs

This PR fixes two "item x is imported redundantly" warnings I noticed in the CI output (see, for example: https://github.com/uutils/coreutils/actions/runs/8268396799/job/22621166258#step:11:55 and https://github.com/uutils/coreutils/actions/runs/8268396799/job/22621166258#step:11:178)

Fix two "item x is imported redundantly" warnings

---

src/uu/cut/src/cut.rs

Small refactoring of how OsString values are handled for delimiters following feedback from PR #6037 
- returning delimiter values early
- do not create and pass around temporary OsString values
- comments

cut: refactor delimiters OsString handling

---

src/uu/csplit/src/csplit.rs

While reviewing https://github.com/uutils/coreutils/pull/6090 I noticed a `crate_name` attribute I think is unnecessary as no other util uses it. According to https://doc.rust-lang.org/rust-by-example/attribute/crate.html:
> it is important to note that both the `crate_type` and `crate_name` attributes have **no** effect whatsoever when using Cargo, the Rust package manager.

csplit: remove `crate_name` attribute

---

src/uu/tr/src/operation.rs

I found a TODO that I think I can help with, I tried to complete this TODO in a very simple way, but I'm not sure if I can achieve the right result.
In my CI, GNU Tests instead has an extra failure, which as I understand should not be a problem, this just initializes the value when needed, could this value be modified? But I didn't find any other modifications.

tr: lazily generate the character mapping as necessary

---

src/uu/df/src/table.rs

addresses #6070
changes:
- use `u128` for accumulating inodes
- ~~use `Option<>` additionally to handle overflows correctly~~
- add unittests accordingly
I know that u128 is slower than u64 as its probably not natively supported, but we are not accumulating millions of numbers such that it should not be significant.
ADDITION:
- I also fixed the issue that the total row was not considered when computation of column widths is done

df: switch from u64 to u128 to handle fs with large inodes nr

---

src/uu/cksum/src/cksum.rs
src/uucore/src/lib/features/encoding.rs
tests/by-util/test_cksum.rs
tests/fixtures/cksum/base64/blake2b_single_file.expected
tests/fixtures/cksum/base64/bsd_single_file.expected
tests/fixtures/cksum/base64/crc_single_file.expected
tests/fixtures/cksum/base64/md5_multiple_files.expected
tests/fixtures/cksum/base64/md5_single_file.expected
tests/fixtures/cksum/base64/sha1_single_file.expected
tests/fixtures/cksum/base64/sha224_single_file.expected
tests/fixtures/cksum/base64/sha256_single_file.expected
tests/fixtures/cksum/base64/sha384_single_file.expected
tests/fixtures/cksum/base64/sha512_single_file.expected
tests/fixtures/cksum/base64/sm3_single_file.expected
tests/fixtures/cksum/base64/sysv_single_file.expected

This PR changes and tests three things:
- Accept `--tag` and `--untagged` in any order, use the last occurrence.
- Accept repetitions of everything, flags and arguments like `--algorithm`.
- Accept and correctly handle `--base64` flag.
All three of these are GNU behavior bugs, i.e. GNU does it differently, and uutils wants to handle it like GNU does.
This is work towards #5998.
Note that `cksum` is still woefully incomplete; most prominently, the `-c` option is missing.

cksum: permit repeated flags, handle overrides correctly, implement base64 output

---

src/uu/fmt/src/fmt.rs
src/uu/fmt/src/linebreak.rs
tests/by-util/test_fmt.rs

Currently, the `fmt` utility will panic with an integer overflow when given a small enough width:
```shell
$ cargo run -q -- fmt -w3 Cargo.toml
thread 'main' panicked at src/uu/fmt/src/linebreak.rs:242:21:
attempt to subtract with overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#%
```
GNU coreutil's fmt doesn't have a problem with this:
```shell
$ fmt -w3 Cargo.toml|head -n 3
#
coreutils
(uutils)
```
This PR adds a test to tests/by-util/test_fmt.rs reproducing this panic. The root cause is this calculation:
```
let g = (w * DEFAULT_GOAL_TO_WIDTH_RATIO / 100).min(w - 3);
```
This sets the goal `g` to be zero when the width `w` is three, or negative for smaller widths. This also contradicts the behavior in the argument help and in the GNU fmt info …

fmt: Make sure goal is always positive

---

.vscode/cspell.dictionaries/shell.wordlist.txt
Cargo.lock
src/uu/env/src/env.rs
src/uu/env/src/native_int_str.rs
src/uu/env/src/parse_error.rs
src/uu/env/src/split_iterator.rs
src/uu/env/src/string_expander.rs
src/uu/env/src/string_parser.rs
src/uu/env/src/variable_parser.rs
tests/by-util/test_env.rs
tests/common/util.rs
tests/fixtures/env/runBat.bat
util/build-gnu.sh
util/gnu-patches/tests_env_env-S.pl.patch

addresses  #5710
This implements all the functionality tested by gnu/tests/env/env-S.pl.
I had to patch the test due to more powerfull implementation and differencences in how parser errors are reported.
I Introduced a mechanism to patch the test with patch-files as the sed-stuff I could not make run for me.
The feature is quite complex, as the tool needs do parsing and evaluation (quoting, escape sequences, environmental variables) of the string on a similar level as a shell:
`env -S<single full featured shell command>`
I used "shell-words" create (MIT license) as a basis. I did heavy modifications, such that I directly commit the sources to this repo. EDIT: Additionally I extended shell-words with a variable expanstion functionality as needed by env.
The idea to use subst was rejected …

env: support string args by "-S", "-vS" or "--split-strings"

---

src/uu/dd/src/dd.rs
tests/by-util/test_dd.rs

this fixes the `misc` test case in dd, it was failing because there was this check in misc where dd should error when given the input via stdin is not a folder and `iflag=directory` is set.

dd: misc gnu test 

---

src/uu/fmt/src/fmt.rs
tests/by-util/test_fmt.rs

GNU `fmt` fails when using `fmt --goal=76 example.txt` because the provided goal value is bigger than `75`, the default width. uutils `fmt`, on the other hand, doesn't fail.
This PR fixes this issue and also replaces two magic numbers with constants.

fmt: fail if goal is bigger than default width

---

src/uu/cksum/Cargo.toml

Running `cargo test --features "cksum" --no-default-features` currently leads to the following error:
```
error[E0432]: unresolved import `uucore::encoding`
--> src/uu/cksum/src/cksum.rs:18:5
|
18 |     encoding,
|     ^^^^^^^^ no `encoding` in the root
|
note: found an item that was configured out
--> /home/dho/projects/coreutils/src/uucore/src/lib/lib.rs:43:26
|
43 | pub use crate::features::encoding;
|                          ^^^^^^^^
= note: the item is gated behind the `encoding` feature
```
This PR fixes the issue by enabling the `encoding` feature.

cksum: enable encoding feature

---

.github/workflows/android.yml
tests/by-util/test_od.rs

fixes issue  #5941
how?
- using the system image "google_apis_playstore" instead of "default" results in slightly newer OS version (2019 instead of 2018) that apparently fixed the issue with `f16c` instruction set
found by chance when investigateting different issue. Sadly the different issue (PR #6080) is not yet fixed by this version.
This brings me to the general question: Why are we using the old API level 28? Is there any specific reason why not switching to a even newer one?

test_od - re-enable f16 test with newer AVD system image

---

src/uu/more/src/more.rs
tests/by-util/test_more.rs

This implements the Pattern option to `more`.
I put this as a draft for now, because the implementation is not as the one from gnu more. The implementation was discussed on the [discord](https://discord.com/channels/563860080668442635/566539469038288910/1125513321504845876) server, but it has been 6 months since then I don't know if anything has changed.
Currently `more` does this:
Before displaying each file, `more` searches for the pattern. If the pattern is not found, it displays the message "Pattern not found." Otherwise, it displays the file starting from the pattern match.

More implement argument pattern

---

src/uu/more/src/more.rs
tests/by-util/test_more.rs

This PR fixes two tests I think are incorrect. It's possible I'm missing something as I don't understand why they test a different code branch than is used when running `more` manually. For example, running `cargo run more` fails as expected. However, the corresponding test, `test_more_no_arg`, ensures it doesn't fail with no arguments. For the fix, I merged the two code branches.

more: fix two incorrect tests

---

.clippy.toml
src/uu/dd/src/parseargs/unit_tests.rs
src/uu/sort/src/sort.rs
src/uucore/src/lib/features/perms.rs
src/uucore/src/lib/parser/parse_glob.rs
tests/by-util/test_cksum.rs
tests/by-util/test_cp.rs
tests/by-util/test_dd.rs
tests/by-util/test_env.rs
tests/by-util/test_touch.rs
tests/common/random.rs
tests/common/util.rs

lint: fix lints of new Rust version

---

.github/workflows/android.yml
tests/by-util/test_ls.rs
util/android-commands.sh
util/android-scripts/collect-info.sh

addresses #6075 
changes:
- improve logging in CI
- detect filesystem type at runtime during test
- apply different set of reference values for case `f2fs`

fix `ls`:  test_ls_allocation_size fails on filesystem `f2fs` (android)

---

src/uu/truncate/src/truncate.rs
tests/by-util/test_truncate.rs

This PR fixes three issues:
- The tests `test_reference` and `test_truncate_bytes_size` had dead code with comments "Uncomment when XYZ is implemented", but XYZ was already implemented two years ago. So I uncommented it.
- The implementations for "reference-only" and "reference-and-size" lacked the logic that "file not truncated because it's missing" is not an error when `--no-create`. So I moved the code from the "size-only" implementation to the common function.
- The fifo-check was copy-pasted in all three implementations, and contained a bug where a missing file would error out. This is fixed here.
Note that `truncate` still has a TOCTOU bug: The fifo check is done on the path, not on the file(descriptor), which leaves a (very short) window of time where a regular file could be …

truncate: correctly handle file (non-)creation

---

src/uu/csplit/src/csplit.rs
tests/by-util/test_csplit.rs

This PR tackles to things with `csplit`:
- Support (and test) passing repeated arguments; this was pleasantly simple, but discovered what seems to be a bug in GNU
- Fix a bug in uutils csplit, because I found/solved it while investigating the "GNU bug". Specifically, we used to unconditionally emit all the remainder of the input, even though GNU does no such thing. (This is especially silly if `-sk` is given.)
The GNU bug seems to be that an empty output file *sometimes* consumes a line:
```console
$ rm xx*; cargo run csplit 50.txt /13/ 9 -k --suppress-matched; echo "= $?"; head -n2 xx02
27
0
111
= 0
14
15
$ rm xx*; csplit 50.txt /13/ 9 -k --suppress-matched; echo "= $?"; head -n2 xx02
27
0
108
= 0
15
16
$
```
As you can see, GNU `csplit` consumed the line containing `13`, even though …

csplit: Handle repeated args, fix remainder after error

---

src/uu/fmt/fmt.md
src/uu/fmt/src/fmt.rs
tests/by-util/test_fmt.rs

The `fmt` command has an interesting syntax where the first argument can be the width (as a dash), with options and/or files after that.
This PR enables that way of calling `fmt` by allowing the positional argument in clap to be a negative number, and parse that as a width if it is the first argument.
This error handling in this PR should fix `tests/fmt/base.pl`.

fmt: allow negative widths as first argument

---

src/uu/tr/src/unicode_table.rs
tests/by-util/test_tr.rs

This addresses a stand-alone issue originally documented in #6133, but can be solved independently: Our `space` class was wrong. As a drive-by, I also wrote a test to make sure our `space` class never gets messed up.

tr: fix "space" class, test "blank" class for order

---

tests/by-util/test_touch.rs

When building coreutils I got the following deprecation warning:
```
warning: use of deprecated method `chrono::NaiveDateTime::timestamp_subsec_nanos`: use `.and_utc().timestamp_subsec_nanos()` instead
--> tests/by-util/test_touch.rs:37:59
|
37 | ..._utc().timestamp(), tm.timestamp_subsec_nanos())
|                           ^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(deprecated)]` on by default
warning: `coreutils` (test "tests") generated 1 warning
```
This commit fixes it.

tests: fix deprecation warning `timestamp_subsec_nanos()`

---

src/uu/date/src/date.rs
tests/by-util/test_date.rs

This commit is a trivial followup for:
https://github.com/uutils/coreutils/pull/4917
and
https://github.com/uutils/parse_datetime/pull/12
The functionality to parse the datetime was moved into the parse_datetime crate and the only (tiny) piece left is to call it from `date`.
It also adds the test-case from the original issue. I did not include the two tests from PR#4917 because they appear to work even without this change. I am happy to include them of course if prefered.
Closes: #4657
Thanks to Ben Schofield

date: fix `date -f dates.txt is failing`

---

.github/workflows/CICD.yml

fixes issue #6033 (failing windows builds)

don't upgrade packages - msys2-runtime upgrade fails in CI

---

src/uu/dd/src/dd.rs
src/uu/dd/src/progress.rs

addresses issue #5902.
The relevant gnu test `tests/dd/stats.sh` is now green.
Changes:
- extend the Alarm-flag with a manual trigger that gets triggered by each received SIGUSR1 signal
- fix block writing to also consider `fullblock` cmd line arg. It retries partial writes when this is set.

dd: handle SIGUSR1 directly. not just every 1sec

---

src/uu/dircolors/src/dircolors.rs
tests/by-util/test_dircolors.rs

This is work towards #5998. Turns out, it's pleasantly simple to fix `dircolors`.

dircolors: accept repeated flags

---

src/uu/date/src/date.rs
tests/by-util/test_date.rs

So far `date -f -` was not reading from stdin. This commit fixes this.
Closes: #6058

date: support `-f -` to read from stdin

---

Cargo.lock
Cargo.toml
tests/by-util/test_factor.rs

Drops the `conv` dependency, which hasn't been updated in the last 8 years and was used in just one place.

chore(deps): drop conv dev-dependency

---

src/uu/tee/src/tee.rs
tests/by-util/test_tee.rs

This PR mainly fixes the handling of writing to existing read-only files, and adds `test_readonly()`.
As a drive-by improvement, this PR also removes some weird wrapping that seems to be unintentional leftovers from history. In short, we used to have a NamedWriter that contained a NamedWriter that contained a NamedWriter that contained the actual file. The run-time impact should be negligible, but removing it makes the code a bit easier to read and edit.
The inspiration for this PR was working towards fixing the GNU test `misc/tee.log`. Note that we still don't fully pass this test because we don't implement "iopoll-powered early exit for closed pipes".

tee: Correctly handle read-only files, avoid unnecessary wrapping

---

src/uu/du/src/du.rs
tests/by-util/test_du.rs
tests/by-util/test_env.rs

Closes #6169 
This is the output as expected
```
└─$ target/debug/coreutils du -s --time-style=banana
2449284 .
```
```
└─$ target/debug/coreutils du -s --time --time-style=banana
du: invalid argument 'banana' for 'time style'
Valid arguments are:
- 'full-iso'
- 'long-iso'
- 'iso'
Try 'target/debug/coreutils du --help' for more information.
```
```
└─$ target/debug/coreutils du -s --time --time-style=iso   
2449476 2024-04-01      .
```

Use time-style only if time is provided

---

fuzz/fuzz_targets/fuzz_common.rs

Inspired by #6167: #6175 is a bug in uutils, caused by an unexpectedly empty string.
Note that the empty string regularly causes interesting behavior:
```
$ echo hello world | hd
00000000  68 65 6c 6c 6f 20 77 6f  72 6c 64 0a              |hello world.|
0000000c
$ echo hello "" world | hd # Additional space!
00000000  68 65 6c 6c 6f 20 20 77  6f 72 6c 64 0a           |hello  world.|
0000000d
```
(uutils already behaves correctly here.)
However, uutils sometimes doesn't behave correctly. To prove my point, I just found this bug merely by inserting the empty string in various places:
```console
$ rm -rf target/test/; mkdir target/test/; cp LICENSE "" README.md target/test/; echo "EXITCODE GNU: $?"; ls -l target/test/; echo "(end)"      
cp: cannot stat '': No such file or directory
EXITCODE …
```

fuzz: also generate the empty string sometimes

---

src/uu/ls/src/ls.rs
tests/by-util/test_ls.rs

Turns out, `ls`'s exit code is actually quite complex, and convincing clap to do what we need is not trivial.
#6162 grew too much, and in particular `ls` is a big hassle. So let's deal with `ls` in isolation first, and I'll rebase #6162 once this PR is merged.

ls: compute the correct exit code

---

.github/workflows/CICD.yml

Hopefully, this fixes our release artifact problems.
Based on: https://github.com/marketplace/actions/gh-release#-limit-releases-to-pushes-to-tags

CI: change publish step condition

---

src/uu/cksum/src/cksum.rs
tests/by-util/test_cksum.rs

The base64 coding was present & only lacked the short option form (-b). Added.
closes #5706

cksum: adding -b as the short form of --base64

---

tests/by-util/test_cut.rs

Two new tests added for `cut`. 
- `test_delimiter_with_byte_and_char`
- `test_no_argument`
increases the `cut.rs` coverage to 95%

cut: two new tests; -d conflict & no arg

---

GNUmakefile
src/uu/env/src/env.rs
tests/by-util/test_env.rs

as discussed with @sylvestre here: #5801 
this makes the gnu-test `tests/env/env.sh` green again.
changes explained:
- accept new parameter and provide it at program start
- adapt debug logmessages to fit to gnu ones
- introduce a second debug-level (-vv) that allowes more detailed, non-gnu conform logs.
- add own test that uses --argv0 argument to `coreutils` executable to execute specific tools without placing seperate argument for tool-name
- UPDATE: patch gnu test to seperately test "-a" and "--argv0"

`env` argv0 overwrite possibility (unix only) - fixes new gnu test version

---

src/uu/wc/src/wc.rs
tests/by-util/test_wc.rs

This PR fixes an issue that caused us to fail the GNU test `wc/wc.log`, specifically not counting ASCII control characters. This is a recent change in GNU coreutils, and 9.4 has a different behavior than 9.5.

wc: count ASCII control characters as word characters

---

src/uu/kill/src/kill.rs

> Environment: Ubuntu 20.04, uutils main branch (git commit https://github.com/uutils/coreutils/commit/415de28fedcd66ae3482f22d4ba274fe77c9d3d8), GNU coreutils version 9.5.3-8f39 (from git commit https://github.com/coreutils/coreutils/commit/8f3989d586a88d182700050b435d2f6c393ec27b).
See #6197 for more details.

kill: print signals vertically when using --list flag

---

src/uu/seq/src/numberparse.rs

This relates to #6182, but does not close the issue.
I looked into how seq parsed the width and found that we were padding the string with zeroes based on the exponent. This would mean that numbers with large exponents would generate a string with the same number of characters.
This PR removes the generation of the string.
Instead, the num_integral_digits is calculated directly. No new strings are generated now when parsing an exponent without decimals.

seq: Removed zero-padding of string when parsing with parse_exponent_no_decimal

---

tests/by-util/test_dd.rs

If the first four decimal digits are zero, GNU dd elides them altogether. Therefore, this test just contained an overly-strict regex.
See also ede944e1f856cc0011852a25d6826b9eac6f2f11.
This flake causes [real problems](https://github.com/uutils/coreutils/pull/6201#issuecomment-2041559555).

dd: fix flaky test_null_stats

---

src/uu/cp/src/cp.rs
tests/by-util/test_cp.rs

This is #6069.
To recap what this PR does: If `-u` is given, don't consider overwriting. If not considering overwriting, don't ask even if `-i` is given.
Reason: While trying to rebase and push his PR, I accidentally overwrite Vikrant's `main` branch, which caused his original PR to be closed, which caused me no longer having implicit write permission to his branch. I guess I'll just never use that GitHub feature again.
@Vikrant2691 Please sanity-check whether this looks correct. `git diff` says there is no difference in content between c94809b490d5ae83b4c69e9b97bb8e52d249bc1a (your original final commit) and 9b9c0cc237e3eb6f9855cab3a40b0f6bf6a0b456 (this commit).

cp: handle update prompt with and without interactive mode enabled

---

src/uu/mv/src/mv.rs

Redox OS doesn't support extended attributes yet, so [this commit](https://github.com/uutils/coreutils/commit/2ec4e9f78490f5cd8d4ccff4ac87a442da5461b2) breaks `mv` there for the "fallback" case of `rename_with_fallback()`.
This PR addresses the issue through a few simple `cfg` conditional changes. Tested manually on Linux and Redox.

mv: Fix bug on Redox OS introduced by xattr handling

---

src/uu/kill/src/kill.rs
tests/by-util/test_kill.rs

> ### Broken support for querying multiple signal names
> 
> ```
> $ ../gnu/src/kill --version | head -n1
> kill (GNU coreutils) 9.5
> $ ../gnu/src/kill -l SIGUSR1 SIGUSR2
> 10
> 12
> $ cargo run --all-features kill -l SIGUSR1 SIGUSR2
> 10
> $
> ```
Multiple signal input support for --list command
```
$ cargo run --all-features kill -l SIGUSR1 SIGUSR2
10
12
```
Don't terminate and display error inline when signal is not recognized
```
$ cargo run --all-features kill -l SIGUSR3 SIGUSR2
kill: unknown signal name 'SIGUSR3'
12
```

kill: support multiple signals for --list

---

src/uu/kill/src/kill.rs
tests/by-util/test_kill.rs

GNU `kill` doesn't list the `EXIT` signal when using `--list` whereas uutils `kill` does. This PR removes `EXIT` from the output of `--list`.

kill: don't show `EXIT` with `--list`

---

src/uu/kill/src/kill.rs
tests/by-util/test_kill.rs

including a new test for "no pid provided" use case.
closes #6221

kill: return 1 and gnu style stderr in case of no pid

---

src/uu/kill/src/kill.rs
tests/by-util/test_kill.rs

> ### Table (-L) format is wrong
> 
> Should be an actual table, not a grid
> 
> ```
> --- STDOUT_GNU	2024-04-07 19:12:25.820911283 +0200
> +++ STDOUT_UUTILS	2024-04-07 19:12:25.824911280 +0200
> @@ -1,62 +1,5 @@
> - 1 HUP      Hangup
> - 2 INT      Interrupt
> - 3 QUIT     Quit
> - 4 ILL      Illegal instruction
> - 5 TRAP     Trace/breakpoint trap
> - 6 ABRT     Aborted
> - 7 BUS      Bus error
> - 8 FPE      Floating point exception
> - 9 KILL     Killed
> -10 USR1     User defined signal 1
> -11 SEGV     Segmentation fault
> -12 USR2     User defined signal 2
> -13 PIPE     Broken pipe
> -14 ALRM     Alarm clock
> -15 TERM     Terminated
> -16 STKFLT   Stack fault
> -17 CHLD     Child exited
> -18 CONT     Continued
> -19 STOP     Stopped (signal)
> -20 TSTP     Stopped
> -21 TTIN …
```

kill: print --table as vertical

---

docs/src/extensions.md
src/uu/cp/src/cp.rs
src/uu/du/src/du.rs
src/uu/ls/src/ls.rs
src/uu/numfmt/src/numfmt.rs
src/uu/od/src/od.rs
src/uu/shred/src/shred.rs
src/uu/sort/src/sort.rs
src/uu/tail/src/args.rs
src/uu/tee/src/tee.rs
src/uu/touch/src/touch.rs
src/uu/uniq/src/uniq.rs
src/uu/wc/src/wc.rs
src/uucore/src/lib/features/update_control.rs
src/uucore/src/lib/parser/shortcut_value_parser.rs
tests/by-util/test_cp.rs
tests/by-util/test_du.rs
tests/by-util/test_ls.rs
tests/by-util/test_numfmt.rs
tests/by-util/test_od.rs
tests/by-util/test_shred.rs
tests/by-util/test_sort.rs
tests/by-util/test_tail.rs
tests/by-util/test_tee.rs
tests/by-util/test_touch.rs
tests/by-util/test_uniq.rs
tests/by-util/test_wc.rs

We already infer long arguments, like `wc --tot` being equivalent to `wc --total`. This PR introduces the same functionality for *values*, just like the GNU tools. In particular, this means the following calls are equivalent:
```
ls -l --time=a
ls -l --time=atime
ls -l --time=access
```
This example also demonstrates that alias resolution does not interfere with value inference: "a" is lexically ambiguous (it might mean "atime" or "access"), but has only one meaning (because "atime" and "access" are the same thing).
The implementation to do that was already there, but was only used in `date(1)` for some reason.
This PR is completely different from the following PRs:
- This PR changes **how** a value is parsed. #6170 changes **if** a value is parsed **at all**.
- This PR **adds** a few …

all: Accept shortcuts for stringly-enum options

---

src/uu/cp/src/cp.rs

Replace `-r` with POSIX’s `-R` and vice versa in `cp`’s manpage to begin to fix  the only reparable part of [#6223](https://github.com/uutils/coreutils/issues/6223) pending changes to `clap` or to the adoption of `uutils-args`.

swap `cp`’s short `-r` and alias `-R` recursive options

---

src/uu/kill/src/kill.rs
tests/by-util/test_kill.rs

This PR updates the signal name comparison to work with all cases. The changes are effective on `--list` and `--signal` commands.
```
$ cargo run --features kill kill -l sIgUsR2
12
[$? = 1]
$ kill -l sIgUsR2 # bash built-in
12
$ /usr/bin/kill -l sIgUsR2 # Debian procps-ng 4.0.4
12
```
Fixes #6217

kill: accept all cases for signal names

---

.github/workflows/CICD.yml

I stumbled across the issue that the nightly and stable builds in CICD.yml where not properly providing the "--features" arg. I think it was probably an issue with copy-paste, as the code on a different place in the yml works.
After change:

CI fix: use features arg for stable and nightly build

---

src/uu/od/src/output_info.rs

This PR removes the `print_width_block` field of the `OutputInfo` struct and fixes the corresponding "field is never read" warning in the nightly builds (see, for example, https://github.com/uutils/coreutils/actions/runs/8688432442/job/23824154227#step:7:91)

od: remove `print_width_block` field of `OutputInfo`

---

src/uu/factor/src/numeric/montgomery.rs

This PR removes the unused method `zero` from the `Arithmetic` trait and thus fixes the "method is never used" warning in the nightly builds (see, for example, https://github.com/uutils/coreutils/actions/runs/8688432442/job/23824154227#step:7:111)

factor: remove unused method `zero`

---

tests/by-util/test_chmod.rs
tests/by-util/test_kill.rs

Fix warning when executing Clippy

Fix warning when executing Clippy

---

src/uu/hashsum/src/hashsum.rs
tests/by-util/test_hashsum.rs

Tested by gnu/tests/cksum/md5sum.pl

hashsum: implement the ignore-missing option

---

.github/workflows/CICD.yml

This adds a rudimentary CI job for building the different programs individually by basically looping over a subset of the `cargo feature` output.
Would look like this: https://github.com/gierens/coreutils/actions/runs/8638198438/job/23682121436
Not sure if this is what you're looking for or rather some static list, I just stumbled across this issue and did something similar before. A future alternative could be cargo-all-features (https://github.com/frewsxcv/cargo-all-features) but unfortunately this is more for feature combinations and still lacks a few features thus would require a fork at the moment.
Resolves: #6097

feat(github): add CICD job build_programs_individually

---

.github/workflows/code-quality.yml
src/uu/env/src/env.rs
tests/by-util/test_chown.rs
tests/by-util/test_chroot.rs
tests/by-util/test_env.rs
tests/by-util/test_install.rs

While looking at https://github.com/uutils/coreutils/pull/6246 I wondered why those clippy warnings were not caught by our CI. <del>The reason is probably that `${{ matrix.job.cargo-options }}` is never defined and so I replaced it with `${{ steps.vars.outputs.CARGO_FEATURES_OPTION }}`.</del> <del>I couldn't figure out the reason and my two attempts to make the CI fail on those warnings failed. And so this PR is just about removing the undefined `${{ matrix.job.cargo-options }}`.</del> It looks like the reason is that we select the utils for the specific platform and then run clippy on those  packages (which don't contain the tests). By running clippy on the `coreutils` package with the `--features` flag, the tests are also checked by clippy.

ci: use `-pcoreutils` when running clippy

---

src/uu/cp/src/cp.rs
src/uucore/src/lib/features/backup_control.rs
src/uucore/src/lib/features/fs.rs
tests/by-util/test_cp.rs

This pr tries to fix #6158 
- changed the behavior of how `-b` worked. Now, `VERSION_CONTROL` env is considered before resorting to  `--backup=existing`
- added more checks to `is_forbidden_to_copy_to_same_file` 
- added some more cases in `copy_file` so that it's okay to return without an error in some cases
- fixes the issue of cp not dereferencing the destination symlink when -d is given without -b, by only removing destination files that are only part of a hard link
- fixed the error caused by trying to remove a file that's already been removed

cp: gnu "same-file" test case compatibility

---

src/uu/hashsum/src/hashsum.rs
src/uucore/src/lib/macros.rs
tests/by-util/test_hashsum.rs
util/build-gnu.sh

Should make tests/cksum/md5sum.pl pass

hashsum: improve the error management to match GNU

---

tests/by-util/test_cp.rs

This PR removes calls of `touch()` that are followed by `write()` or `append_bytes()`. In case of the latter, `append_bytes()` is replaced with `write_bytes()`.

cp: remove unnecessary calls of `touch()` in tests

---

Cargo.lock
Cargo.toml
src/uu/more/Cargo.toml

more: use dev tty instead of mio to avoid panics

---

Cargo.lock
src/uu/du/Cargo.toml
src/uu/du/src/du.rs
src/uu/ls/Cargo.toml
src/uu/ls/src/ls.rs
src/uucore/Cargo.toml
src/uucore/src/lib/features/format/human.rs
src/uucore/src/lib/features/format/mod.rs
tests/by-util/test_du.rs

When printing the `du -h` output GNU coreutils does autoscale
the size, e.g.
```
$ truncate -s12M a
$ truncate -s8500 b
$ truncate -s133456345 c
$ truncate -s56990456345 d
$ du -h --apparent-size a b c d
12M     a
8,4K    b
128M    c
54G     d
```
Align our version to do the same by sharing the code with `ls`.
Closes: #6159
---
ls,uucore: extract display `human_readable()` helper from ls
This commit extract the `display_size()` helper from `ls` into
`uucore` as `human_readable` to be similar to the gnulib helper
so that the human readable display of sizes can be shared between
ls, du, df.

du: give `-h` output the same precision as GNU coreutils

---

src/uucore/src/lib/features/fsext.rs

The NetBSD was missing from target-os checks on fsext.rs
Fixed #6261
tested and works on NetBSD 10.0

Fixing the build issue on NetBSD

---

.github/workflows/CICD.yml

This is a simple one-line fix of *CICD.yaml* to re-enable artifact creation for version tagged commits.
It does include a revert of https://github.com/uutils/coreutils/issues/6181 so that only version-type tags trigger deployment.
I've done testing on [a repo clone](https://github.com/rivy-t/rs.coreutils), so I'm 90% confident. 😄
If it doesn't work on the next release, ping me and I'll further debug it.
@sylvestre , the deployment does always create a release even if there's a draft release with the same title/version, so you'll have to copy any draft release text over to the actual release. Has that been your release practice in the past?
Fixes https://github.com/uutils/coreutils/issues/5929.

fix/CI ~ re-enable artifact deployment for version tagged commits

---

tests/test_util_name.rs

I noticed that [`src/bin/coreutils.rs`](https://app.codecov.io/gh/uutils/coreutils/blob/main/src%2Fbin%2Fcoreutils.rs?flags%5B0%5D=ubuntu_latest) had abysmal coverage. Turns out, we don't have any tests for most features of our "multi-call binary" logic!
This PR fixes that by adding a few tests, namely:
- Calling with an unusual name
- Calling with a non-UTF8-name
- Calling with invalid arguments (thus exercising the top-level argument error handling)
- Generating a manpage
- Generating a completion
Thankfully, this revealed no bugs. Let's prevent regressions!
EDIT: From 19% to 68%: https://app.codecov.io/gh/uutils/coreutils/blob/BenWiederhake%2Fcoreutils-rs%3Adev-better-test-coverage/src%2Fbin%2Fcoreutils.rs

tests: test multi-call logic

---

src/uu/hostid/src/hostid.rs
src/uu/pr/src/pr.rs
src/uu/tee/src/tee.rs
tests/by-util/test_hostid.rs
tests/by-util/test_pr.rs
tests/by-util/test_tee.rs
util/build-gnu.sh

This PR:
- fixes the exit codes for three utils; the bulk of utils was already fixed back in #3922
- fixes a weird difference in behavior of `tee -h` and `tee --help`
- reduces our customization of the GNU test `misc/usage_vs_getopt`
All in all, we should now pass `misc/usage_vs_getopt`. Let's see whether CI agrees!
Ping @tertsdiepraam, you touched on this topic a long time ago. What do you think? :)

all: Undo custom exit codes

---

util/android-commands.sh

I stumbled accross this by chance. When the install step was retried, it started from scratch again.
This PR enables the reuse of build artefacts from previous try.
This done by explicitly setting CARGO_TARGET_DIR env variable as otherwise a random generated tmp directory is used,
which prevents incremental build for the retries.

android CI: incremental install when retry

---

src/uu/kill/src/kill.rs
tests/by-util/test_kill.rs

Adding support for handling `SIGEXIT` as mentioned in [Issue-6628](https://github.com/uutils/coreutils/issues/6228).
Before this change the nix library would return an `EINVAL` when passing `SIGEXIT` / `EXIT` to uutils/coretutils kill.
After this change nix passes `0` to libc kill as shown [here](https://github.com/nix-rust/nix/blob/master/src/sys/signal.rs#L1068-L1073).

kill: adding support for handling SIGEXIT

---

Cargo.lock

This PR bumps `bigdecimal` from `0.4.0` to `0.4.2` as a (partial?) solution for https://github.com/uutils/coreutils/issues/6281. I didn't upgrade to `0.4.3` because it breaks a lot of `seq` tests and according to https://github.com/akubera/bigdecimal-rs/issues/127#issuecomment-2053739584 they will revert some of its changes in `0.4.4`:
> Version 0.4.3 changed the formatting in a way many people didn't like, so I'm changing formatting again for 0.4.4.

Bump bigdecimal from 0.4.0 to 0.4.2

---

src/uu/id/src/id.rs
tests/by-util/test_id.rs

This PR fixes argument-parsing for `id`, in particular:
- All arguments can now be repeated (this makes sense for all of them; I checked.)
- `-p` and `-P` both take control of the output format, so it does not make sense to specify both of them.
This is work toward #5998.

id: Handle repeated flags, recognize conflict between pretty-print and passwd file-entry

---

tests/by-util/test_od.rs

Discovered when looking at `/tmp/` after I killed `cargo test`, and apparently hit the 0.1 second window where these tests are executed.

od+tests: use TestScenario, avoid spamming /tmp on failure

---

src/uu/sort/src/sort.rs

- Avoid error on OpenBSD stable/7.5 with clippy (lint)
- suspicious_open_options added in Rust 1.77.0 (1.76 used on OpenBSD 7.5) https://rust-lang.github.io/rust-clippy/master/index.html#/suspicious_open_options
Fix uutils/coreutils#6290
Lint with `clippy` and build OK on OpenBSD stable/7.5 and FreeBSD 14.0 (Rust version 1.77).

sort: disable clippy::suspicious_open_options on OpenBSD

---

src/uu/tail/src/parse.rs
src/uucore/src/lib/features/fsext.rs
tests/by-util/test_basename.rs
tests/by-util/test_basenc.rs
tests/by-util/test_cat.rs
tests/by-util/test_kill.rs
tests/by-util/test_ls.rs
tests/by-util/test_mktemp.rs
tests/by-util/test_numfmt.rs
tests/by-util/test_od.rs
tests/by-util/test_printf.rs
tests/by-util/test_realpath.rs
tests/by-util/test_sort.rs
tests/by-util/test_tr.rs

We have lots of unnecessary `spell-checker:disable-THING` all over the place, 44 in fact. That means we wouldn't notice typos in those lines, so let's remove unnecessary stuff like that.
I found this when watching @jadijadi's video about #6225, because he copy-pastes a non-sensical `spell-checker:disable-line` on an empty line.
Code to find the unnecessary spellcheck-statements: https://gist.github.com/BenWiederhake/f43c386c957825b6109325c39a351cac
In the process, I also found that `tests/by-util/test_cat.rs` could be simplified a little bit. Not sure if it's worth it, but now it's done.

everywhere: cleanup unused/unnecessary spellcheck-disabling

---

Cargo.lock
Cargo.toml
src/uu/ls/Cargo.toml
src/uu/ls/src/ls.rs

Draft PR for now, because we need to release a new version of term-grid first, but I wanted to show how the new API changes in https://github.com/uutils/uutils-term-grid/pull/27 are affecting `ls`.

`ls`: upgrade uutils-term-grid to 0.5

---

src/bin/coreutils.rs

Closes https://github.com/uutils/coreutils/issues/6250
I've implemented it more or less like the busybox version now, by just matching on the string `--list`. Ultimately, we might want to go for more sophisticated argument parsing in the multicall binary.
It is a bit strange though, because all the other things that the multicall binary can do are implemented as subcommands. In other words, one of these is not like the others:
```
coreutils completion
coreutils manpage
coreutils --list
```
I think using `--` makes sense to clearly separate it from the utils. Maybe `completion` and `manpage` should be prefixed with `--` too?

multicall: add --list to list all utils

---

src/uu/cp/src/cp.rs
src/uu/csplit/src/csplit.rs
src/uu/csplit/src/patterns.rs
src/uu/df/src/filesystem.rs
src/uu/env/src/env.rs
src/uu/factor/src/factor.rs
src/uu/hashsum/src/hashsum.rs
src/uu/kill/src/kill.rs
src/uu/nl/src/helper.rs
src/uu/ptx/src/ptx.rs
src/uu/tail/src/follow/watch.rs

This PR fixes the clippy warnings introduced with Rust 1.78. In two cases I used `#[allow(clippy::assigning_clones)]` because the suggested changes didn't work.

clippy: fix warnings introduced with Rust 1.78

---

.github/workflows/CICD.yml

On windows path to grcov is:
```
info: grcov installed at /c/Users/runneradmin/.install-action/bin/grcov.exe
+ grcov --version
grcov 0.8.19
```
On unix:
```
info: grcov installed at /home/runner/.cargo/bin/grcov
+ grcov --version
grcov 0.8.19
```
In both cases they should be available in `$PATH`
Tested on my fork: https://github.com/piotrkwiecinski/coreutils/actions/runs/8926781245/job/24518622684?pr=7
Fixes https://github.com/uutils/coreutils/issues/6331

fix code coverage windows

---

util/show-utils.sh

In jq query, the correct regex to select .id is ".*coreutils[ |@]\\d+\\.\\d+\\.\\d+"
- with cargo v1.76.0, id = `"coreutils 0.0.26 (path+file://<coreutils local directory>)"`
- with cargo v1.77.0, id = `"path+file://<coreutils local directory>#coreutils@0.0.26"`
Fix uutils/coreutils#6242
---
Tests OK on OpenBSD with cargo v1.76 and FreeBSD with cargo v1.77
```
$ ./util/show-utils.sh
base32 base64 basename basenc cat cksum comm cp csplit cut date dd df dir dircolors dirname du echo env expand expr factor false fmt fold hashsum head join link ln ls mkdir mktemp more mv nl numfmt od paste pr printenv printf ptx pwd readlink realpath rm rmdir seq shred shuf sleep sort split sum tac tail tee test touch tr true truncate tsort unexpand uniq unlink vdir wc yes
$ ./util/show-utils.sh …
```

show-utils.sh: fix jq query to get coreutils deps

---

src/uu/tr/src/operation.rs
src/uu/tr/src/tr.rs
tests/by-util/test_tr.rs

Fixes #6163 and adds a test to verify that a regression is not caused.
Instead of inverting the conditions to check (e.g. delete characters **not** present in set1) invert set1 when passed the complement flag (`-c`, `-C`, `--complement`). This is done by calculating set1 then "inverting" it by subtracting from the "full" (universe) set (0..=u8::MAX).
This fixes issue 6163 because it was caused by a combination of the `-c` and `-t` flag. `-c` is the abovementioned complement flag and `-t`/`--truncate-set1` truncates set1 to the length of set2. What happened in issue 6163 is that `set1={b'Y'}` and `set2={b'Z'}`, when truncated set1 stays the same and we proceed. The problem is GNU utils does not consider set1 to be `{b'Y'}`, but the complement of `{b'Y'}`, that is `U \ {b'Y'}={0, 1, ..., …

tr: calculate complement set early

---

src/uu/cp/src/cp.rs
src/uu/df/src/filesystem.rs
src/uu/tail/src/follow/watch.rs

- Avoid error on OpenBSD stable/7.5 with clippy (lint), Rust version 1.76 used on OpenBSD 7.5 and will be not updated before the next stable version 7.6, release ~October 2024
- assigning_clones added in Rust 1.78.0 https://rust-lang.github.io/rust-clippy/master/index.html#/assigning_clones
- disable clippy::assigning_clones via `cfg_attr` for cp, df and tail utils

Disable clippy::assigning_clones on OpenBSD

---

src/uu/fmt/src/fmt.rs
tests/by-util/test_fmt.rs
tests/fixtures/fmt/prefixed-one-word-per-line.txt
tests/fixtures/fmt/prefixed-one-word-per-line_p-.txt
tests/fixtures/fmt/prefixed-one-word-per-line_p=.txt
tests/fixtures/fmt/prefixed-one-word-per-line_p=_P=2.txt

Turns out, just a simple `args_override_self(true)` is precisely the correct behavior.
This is also correct with regard to `-p`, `-w`, `-g`; I checked (and found #6352, #6353, #6354 in the process of doing so).
This is work towards #5998.
Note that even though I added some basic tests, a huge chunk of the functionality is still untested, especially `-c`, `-x`/`-X`, `-t`, `-m`, `-q`, `-T`, and of course `-g`, which is broken (known issue).

fmt: accept repeated arguments

---

src/uu/fmt/src/linebreak.rs
tests/by-util/test_fmt.rs

fmt: value of minlength should not be negative

---

tests/common/util.rs

The test_compare_xattrs test fails on OpenBSD because OpenBSD does not support xattrs. Disabling this test for `target_os = openbsd` resolved the issue.
Fixes #6348

Disabling xattrs tests on OpenBSD

---

src/uu/fmt/src/fmt.rs
tests/by-util/test_fmt.rs

Fixes #6352.
In particular, this changes a deviation from GNU to a more helpful deviation from GNU:
```console
$ ../gnu/src/fmt -g apple
../gnu/src/fmt: invalid width: 'apple'
[$? = 1]
$ cargo run -q fmt -g apple # Before this PR
fmt: invalid value 'apple'
[$? = 1]
$ cargo run -q fmt -g apple # After this PR
fmt: invalid goal: 'apple'
[$? = 1]
```

fmt: fix error priority, make goal-errors more helpful

---

deny.toml

This PR removes `hashbrown` from the skip list because we no longer use two versions of this crate. It also updates a comment.

deny.toml: remove hashbrown, update comment

---

src/uu/fmt/src/fmt.rs

While reviewing https://github.com/uutils/coreutils/pull/6362 I noticed that we use `try_get_matches_from()` in the tests. We pass only valid values to this function, and so it's simpler to use `get_matches_from()`.

fmt: use `get_matches_from()` instead of `try_get_matches_from()` in tests
