uutils/coreutils

- src/base64/base64.rs
- src/basename/basename.rs
- src/common/c_types.rs
- src/common/time.rs
- src/kill/kill.rs
- src/nice/nice.rs
- src/tty/tty.rs
- src/uptime/uptime.rs
- from_str() -> parse()
- into_string() -> to_owned()
> Fix deprecation warnings with latest rust nightly

- src/logname/logname.rs
getlogin can return NULL pointer. Patch fixes this and makes logname work fine even with NULL.
> NULL-pointer check in logname

- Makefile
Some tests (e.g. cp) assume a empty directory.
> make: wipe $(TEMPDIR) before running tests

- src/uname/uname.rs
Otherwise all options have a space at the end, causing a warning in grml zsh config, and who knows what else.
> uname: change trim_left() to trim()

- Makefile
- src/stdbuf/libstdbuf.c
- src/stdbuf/libstdbuf.h
- src/stdbuf/libstdbuf.rs
- src/stdbuf/prepare_libs.sh
- src/stdbuf/stdbuf.rs
My first attempt to solve issue #434
This is very first and basic version of stdbuf working on Linux 86_x64. It assumes that user has GNU coreutils installed (and so libstdbuf.so from GNU in /lib/coreutils). It also works for the same programs GNU stdbuf works, that is programs written in C/C++ using default stdin/stdout/stderr objects from stdio.h library. 
To be honest, I don't know how to implement it for programms written in rust.
GNU uses LD_PRELOAD to link dynamically a shared library, which changes stdio.h objects before running the program itself, so buffors are being set properly. I know that rust allows to modify object returned by stdout() in current task by function set_stdout() (http://doc.rust-lang.org/nightly/std/io/stdio/fn.set_stdout.html), but I'm not sure if there is …
> stdbuf - basic version 

- README.md
As stdbuf is finally merged, let's remove stdbuf and libstdbuf from TODO list in README
> remove stdbuf and libstdbuf from TODO list

- src/od/od.rs
The initial draft written by @benhirsch24 misinterpreted the -A/--address-radix flag. This flag should control the printing of the file offsets (the leftmost field of the output), not the printing of the values in the output bytes. See the POSIX spec for od:
http://pubs.opengroup.org/onlinepubs/9699919799/utilities/od.html
You can also verify this by running any standard od on any input whatsoever.
This PR implements an initial fix for this defect. A few preparatory cleanups I made related to fixing this bug are rolled into this PR as well.
> od: fix --address-radix interpretation and minor cleanups

- Makefile
After building the serialize crate, the rlib was copied to the build
directory using a hyphen in the library name ('librustc-serialize').
It seems that Rust expects an underscore instead.
> Fix broken build for serialize crate.

- .gitignore
- .gitmodules
- Makefile
- deps/Cargo.toml
- mkmain.rs
- mkuutils.rs
- src/base64/base64.rs
- src/base64/deps.mk
- src/chmod/deps.mk
- src/cksum/gen_table.rs
- src/du/deps.mk
- src/fmt/deps.mk
- src/fmt/fmt.rs
- src/fmt/linebreak.rs
- src/fmt/parasplit.rs
- src/hashsum/deps.mk
- src/nl/deps.mk
- src/seq/seq.rs
- src/touch/deps.mk
- src/uptime/deps.mk
- src/uptime/uptime.rs
This PR includes two things. First, it fixes the utility `seq`.
Second, it does some relatively major surgery on the way the build works, with the goal of
1. allowing us to more easily add dependencies in the future, and
2. allowing us to specify on a per-utility basis what the dependencies are.
This is how it works:
* The `DEPLIBS` and `DEPPLUGS` variables in the Makefile determines which Cargo crates are built. By default, `DEPLIBS := libc` (needed for `common`) and `DEPPLUGS` is empty.
* `DEPLIBS` are rlibs, `DEPPLUGS` are compiler plugins (and thus dynamic libs) like `regex_macros`.
To use it:
* In each utility's directory, one can add a `deps.mk` file that modifies the values of `DEPLIBS` and `DEPPLUGS`. This causes additional targets to be generated which build the appropriate …
> refactor Makefile to use Cargo to build all dependencies ; make seq build

- Makefile
- src/chmod/chmod.rs
- src/chroot/chroot.rs
- src/common/c_types.rs
Three commits:
1. Tweak Makefile so that when the make goal is `test` it only considers the `TESTS` variable when building dependencies.
2. Updates in chmod. Works, but I suspect it will have issues with non-UTF-8 filenames. This was probably always the case, though.
3. Updates in chroot (and in `src/common/c_types.rs`). Two things here:
* For now, one of the fixes in c_types is slightly hacky (specifically: I commented out the `Copy` impls for several of the structs), but this will get fixed as necessary for other utils.
* The call to the chroot function seems to fail in some cases. I am still investigating this, but I ran out of time for now.
> quick Makefile tweak ; update chmod ; update chroot

- Makefile
- README.md
This rule will build each program, ignore all output, and return pass or fail depending on whether the build has errors. This is helpful for finding out which programs need to be fixed when a new Rust nightly build inevitably breaks everything.
This would be deprecated by changing the Makefile to not exit on the first program that doesn't build properly, but this seemed useful enough for inclusion.
> Add a new makefile rule to check for build errors.

- src/base64/base64.rs
- src/cat/cat.rs
- src/expand/deps.mk
- src/expand/expand.rs
- src/fmt/fmt.rs
- src/tr/expand.rs
- src/tr/tr.rs
- src/unexpand/deps.mk
- src/unexpand/unexpand.rs
- src/unlink/unlink.rs
- test/tr.rs
- test/unexpand.rs
This PR does the following:
1. Removes unnecessary use of `box_syntax` feature gate in `fmt`, `base64`, and `cat`
2. Fixes `unlink`
3. Fixes and substantially reworks `unexpand` and `expand`
* In both cases, the goals were
1. Fix slightly broken behavior in weird cases,
2. make the utilities able to handle both UTF-8 and non-UTF-8 inputs, and
3. add a `-U` switch that explicitly prevents the command from interpreting input as UTF-8.
4. Fixes `tr`, and substantially reduces the number of allocations it does at startup.
> more feature cleanup ; fix more utils

- src/sort/sort.rs
- test/sort.rs
The sorted values were not outputted using a newline.
> Fix failing test for sort.

- Makefile
- README.md
This rule will test each program, ignore all output, and return pass or fail depending on whether the test has errors. This is the equivalent of `make build-check`, but for tests.
> Add a new makefile rule to check for test errors.

- src/rm/rm.rs
- src/rmdir/rmdir.rs
This PR fixes `rm` and `rmdir`.
The behavior of `rm` when recursively deleting with interactive mode enabled better matches the behavior of GNU Coreutils `rm`. Specifically, the user is asked before recursing into a subdirectory. The order in which files and directories are deleted is different from GNU Coreutils, however.
> fix `rm` and `rmdir`

- src/fold/fold.rs
The syntax for concatenating a vector and a slice use the '+' operator was removed from Rust.
> Update fold to replace vector concatenation.

- Makefile
- src/factor/gen_table.rs
- src/factor/sieve.rs
- test/factor.rs
This commit adds `cargo update` to the distclean target in the
makefile. This updates the Cargo.lock file when clearing the
deps directory.
In addition, it adds a faster implementation of the Sieve of
Eratosthenes for use by `src/factor/gen_table.rs` and `test/factor.rs`.
> improved Sieve implementation ; add `cargo update`

- src/mkfifo/mkfifo.rs
The build failed because of type mismatch errors for the mode permission.
> Fix mkfifo on Linux.

- mkmain.rs
- mkuutils.rs
- src/uutils/uutils.rs
With the 1.0 release, unstable features are causing build errors. I replaced references to std::env::set_exit_status() with std::process::exit().
> Replace unstable set_exit_status() with exit().

- src/split/split.rs
- src/sum/sum.rs
- src/sync/sync.rs
- src/tac/tac.rs
- src/tee/tee.rs
- src/truncate/truncate.rs
- src/tty/tty.rs
- src/uname/uname.rs
- src/uniq/uniq.rs
- src/unlink/unlink.rs
- src/uptime/uptime.rs
- src/users/users.rs
- src/whoami/whoami.rs
- src/yes/yes.rs
I switched over to the getopts crate on crates.io, instead of Rust's private implementation. This will allow coreutils to build for Rust 1.0.
I'm splitting the updates into several commits for easier reviewing.
> Switch to external getopts cargo (part 2).

- src/cp/cp.rs
- src/cut/cut.rs
- src/du/du.rs
- src/expand/expand.rs
- src/fmt/fmt.rs
- src/fold/fold.rs
- src/head/head.rs
- src/mkdir/mkdir.rs
- src/mv/mv.rs
- src/nl/nl.rs
- src/readlink/readlink.rs
- src/realpath/realpath.rs
- src/relpath/relpath.rs
- src/rm/rm.rs
- src/seq/seq.rs
- src/stdbuf/stdbuf.rs
- src/tail/tail.rs
- src/touch/touch.rs
- src/tr/tr.rs
- src/tsort/tsort.rs
- src/unexpand/unexpand.rs
- src/wc/wc.rs
I switched over to the getopts crate on crates.io, instead of Rust's private implementation. This will allow coreutils to build for Rust 1.0.
I'm splitting the updates into several commits for easier reviewing.
> Switch to external getopts cargo (part 3).

- src/echo/echo.rs
Upon program termination, pending stdout writes were not automatically flushed. When newlines are disabled, I force a flush to stdout.
> Fix failure to print stdout for echo.

- src/chroot/chroot.rs
- src/realpath/realpath.rs
The help documentation for the other utilities use periods instead.
> Replace UTF-8 ellipsis character w/ ASCII periods.

- src/common/util.rs
- src/echo/echo.rs
- src/env/env.rs
- src/seq/seq.rs
I built upon the pipe_* macros, adding pipe_flush!() to flush an optional writer (default to stdout if no writer is given).
It turns out standard output is buffered by default, so non-newline-terminated strings are not printed when a program terminates.
> Add macro to manually flush a writer.

- src/chmod/chmod.rs
- src/chroot/chroot.rs
- src/du/du.rs
- src/env/env.rs
- src/expand/expand.rs
- src/fmt/fmt.rs
- src/fold/fold.rs
- src/groups/groups.rs
- src/hashsum/hashsum.rs
- src/head/head.rs
- src/mkdir/mkdir.rs
- src/mv/mv.rs
- src/nice/nice.rs
- src/nl/nl.rs
- src/nohup/nohup.rs
- src/pwd/pwd.rs
- src/readlink/readlink.rs
- src/realpath/realpath.rs
- src/relpath/relpath.rs
- src/shuf/shuf.rs
- src/split/split.rs
- src/stdbuf/stdbuf.rs
- src/tail/tail.rs
- src/timeout/timeout.rs
- src/tsort/tsort.rs
- src/unexpand/unexpand.rs
All utilities should now use the format "{name} {version}" when the version is printed.
> Standardize display of utility name and version.

- src/cat/cat.rs
- src/readlink/readlink.rs
- src/tr/tr.rs
- src/unexpand/unexpand.rs
This was needed to ensure all writes to stdout were printed. Several tests failed because this wasn't happening.
> Flush pending stdout writes.

- Makefile
- src/ptx/deps.mk
- src/ptx/ptx.rs
- test/fixtures/ptx/ignore
- test/fixtures/ptx/input
- test/fixtures/ptx/only
- test/ptx.rs
#516 
This is intial commit of ptx. It's based on www.gnu.org/software/coreutils/manual/html_node/ptx-invocation.html#ptx-invocation. Unfortunatelly, original implementation works slightly different than explained in aforementioned documantation. Additionally, in GNU sources you can find comments like the following one: "I never figured out exactly how UNIX' ptx plans the output width of its various fields.  If GNU extensions are disabled, do not  try computing the field widths correctly(...)". As my implementation works with GNU extensions disabled (but it shouldn't take long to add them though), it sometimes produces slightly different chunks than the GNU one. But in my opinion they make sense and whole functionality is preserved. I know that there is a lot of code but I'm looking …
> initial ptx commit

- test/common/util.rs
- test/hashsum.rs
- test/unexpand.rs
When creating tests, we could pass a String, &str, or [u8] to the standard input. Previously, all arguments had to be manually converted to a reference to a [u8]. This update makes it more ergonomic.
> Refactor method to auto-convert into byte array.

- mkmain.rs
Since stdout is line-buffered by default, we need to ensure any pending writes are flushed before exiting. Ideally, this should be enforced by each utility. Since all utilities are wrapped by mkmain, this was a
convenient location to enforce this behavior. I previously was handling this on a case-by-case basis.
See: https://github.com/rust-lang/rust/issues/23818
> Ensure any pending stdout writes are flushed.

- .travis.yml
It looks like the Travis build has been broken for a long time, that's a shame.
I have a PR (#641) fixing timeout.rs, so that the Travis build on nightly succeeds; this PR makes it so that the build isn't red because of the failure on 1.0.0.
> Allow failure on Rust 1.0.0 (broken right now)

- src/mv/mv.rs
- test/mv.rs
Following discussion on `mv`: https://github.com/uutils/coreutils/commit/beba02757ee2d2341dd7412273c1fe358edd9559#commitcomment-11934351
I'm new to Rust, review carefully. I avoided copying the paths (single copy from &String to PathBuf).
The option might also be useful to `cp`.
Probably warrants a test, but the expected behavior (without --strip-trailing-slashes) differs depending on rename(2) behavior.
> Implement mv's --strip-trailing-slashes

- src/mv/mv.rs
The program name was incorrectly printed, and the alignment of the help message was off.
> Fix alignment of mv help.

- Makefile
- README.md
- src/ln/ln.rs
- test/common/util.rs
- test/ln.rs
Fixes #267.
There are several areas needing improvement:
1) add tests for hard links
2) add implementation for uncommon flags (-d, -L, -n, -P, -r)
3) align error messages more closely with GNU implementation
Any updates, comments, or suggestions are welcome.
> Add initial implementation for ln.

- Makefile
- src/stdbuf/stdbuf.rs
- test/stdbuf.rs
When replacing range_inclusive(), I introduced a bug when parsing arguments. I added a smoke test to prevent basic regressions in the future.
> Fix stdbuf regression.

- Makefile
- src/stdbuf/libstdbuf.rs
- src/stdbuf/stdbuf.rs
I removed several unused linker flags and replaced extern C reference to standard I/O with Rust's libc constants. I also removed an unused variable mutation.
> Fix OS X build errors for stdbuf.

- Makefile
This is needed for dynamic libraries on OS X. This was supposed to be part of #647, but it was left out.
> Delay resolution of library symbols until runtime.

- README.md
- appveyor.yml
Given the recent focus on the Windows build, I added CI support using AppVeyor. I installed MSYS2 and Rust in the Windows VM, and the initial build is functional but still fails.
Could someone review this? I'm a new to AppVeyor and building Rust programs on Windows so any help would be appreciated.
Here is the build for my coreutils fork: https://ci.appveyor.com/project/jbcrail/coreutils
/cc @retep998 @Arcterus
> Add Windows CI support using AppVeyor.

- src/echo/echo.rs
- src/users/users.rs
- src/yes/yes.rs
We are using connect() instead of join() until Rust 1.3 is stable. Currently, connect() is just a thin wrapper over join(). Keeping the deprecated method allows us to build on all releases.
Fixes concerns about #676.
> Add comments for deprecated connect().

- src/du/du.rs
Use channels and push them into a vector instead. Code remains largely the same.
Addresses #681 with a simple solution.
> Fix build by making du not use futures

- src/whoami/platform/unix.rs
- src/whoami/platform/windows.rs
- src/whoami/whoami.rs
This PR does the following:
- Return status `libc::EXIT_FAILURE` instead of `1` on failures. This mimicks the GNU whoami implementation. Not sure what you think of it, if you want me to use `1` instead, let me know.
- The `getusername` functions now return a `Result<String, String>` instead of crashing directly
- Handle null pointer return value for `getpwuid()` on Linux
I don't have much experience doing systems stuff, so please check this PR carefully :) Also, I didn't try to compile it on Windows.
The error condition can be tested by doing this change (under the condition that a user with uid 1337 does not exist, of course):
```diff
diff --git a/src/whoami/platform/unix.rs b/src/whoami/platform/unix.rs
index d24d02e..e9c56a2 100644
--- a/src/whoami/platform/unix.rs
+++ …
```
> whoami fixes

- test/factor.rs
The current test runs for ~1min on a fast machine which seems to be a bit
excessive. (Or maybe there is a performance problem?)
> factor: reduce number of random tests

- src/factor/factor.rs
No further calculations required in case 'num' is already 1.
> factor: panic running againts power of two. (issue #702)

- Cargo.toml
- Makefile
- src/expr/Cargo.toml
- src/expr/expr.rs
- src/expr/syntax_tree.rs
- src/expr/tokens.rs
Implemented as follows:
Usage: expr EXPRESSION
or:  expr OPTION
--help     display this help and exit
--version  output version information and exit
Print the value of EXPRESSION to standard output.  A blank line below
separates increasing precedence groups.  EXPRESSION may be:
ARG1 | ARG2       ARG1 if it is neither null nor 0, otherwise ARG2
ARG1 & ARG2       ARG1 if neither argument is null or 0, otherwise 0
ARG1 < ARG2       ARG1 is less than ARG2
ARG1 <= ARG2      ARG1 is less than or equal to ARG2
ARG1 = ARG2       ARG1 is equal to ARG2
ARG1 != ARG2      ARG1 is unequal to ARG2
ARG1 >= ARG2      ARG1 is greater than or equal to ARG2
ARG1 > ARG2       ARG1 is greater than ARG2
ARG1 + ARG2       arithmetic sum of ARG1 and ARG2
ARG1 - ARG2       arithmetic difference of ARG1 and ARG2 …
> Implement expr.

- Makefile
The `make test` command failed to run the integration and unit tests.
> Fix test scaffolding after Cargo updates.

- Cargo.toml
- Makefile
- build.rs
- src/test/Cargo.toml
- src/test/test.rs
- src/uutils/uutils.rs
To avoid linking issues with Rust's libtest, the crate for the test utility was changed to `uutest`. However, the user doesn't need to see this so a few hoops were jumped through to make this transparent.
I also updated the make rules to build the individual features first and then uutils. This makes `make && make test` look more organized.
> Fix namespace collision for test.

- build.rs
- src/test/Cargo.toml
- src/test/main.rs
- src/test/test.rs
I separated test's main() into a separate file to override Cargo's
requirement for matching crate names. I had to update the build command
to use a special extern reference for test.
Current broken tests: cut readlink realpath relpath pwd
Fixes issues caused by #728.
> test: fix namespace and broken test

- .travis.yml
`make test` used to run all tests but exited with 0 unless the last test
failed. So failures where hidden from travis. 
With 2d41e664 `make test` fails with an error exit code on the first test
failure. This is better than before, but it hides newly introduced failures.
`cargo test --no-fail-fast` runs all tests and if any of the tests fails exits
with an error. So if travis reports a failed check, we at least can skim the
travis log to ensure no new failures are introduced.
> travis: switch to cargo build/test

- src/cut/ranges.rs
When determining the range from which to select portions of a line, the
upper limit of the range is a usize. The maximum upper value is
usize::MAX, but at one point this value is incremented, causing an
overflow. By setting the maximum upper value to usize::MAX-1, the bug is
averted. Since the upper limit of the range is an index (thus, ranging
from 0 to 2^64-1 for 64-bit platforms), the maximum usize should not be
reached.
> cut: fix off-by-one error for range calculation

- src/cat/cat.rs
- src/nohup/nohup.rs
- src/sort/sort.rs
- src/tty/tty.rs
- src/uucore/fs.rs
Since several utilities check if the standard streams are interactive, I
moved this into the uucore::fs library as is_std*_interactive(). I also
added Windows support for these methods, which only return false (or at
least until someone finds a way to support this).
> Refactor check for standard stream interactivity.

- Cargo.toml
- Makefile
- src/mv/Cargo.toml
- src/sync/Cargo.toml
- src/uucore/Cargo.toml
- src/uucore/fs.rs
- src/uucore/lib.rs
- src/whoami/Cargo.toml
- src/whoami/platform/windows.rs
The build now works on the following targets (tests still fail):
* x86_64-pc-windows-msvc
* i686-pc-windows-msvc
> Fix build errors on Windows.

- CONTRIBUTING.md
- README.md
GitHub uses CONTRIBUTING.md as the basis for a message to someone
creating a new issue. I made a few changes to modernize the contribution
section, but there's still room for updates.
> Move contributing section into separate file

- src/chmod/chmod.rs
- src/chroot/chroot.rs
- src/cp/cp.rs
- src/cut/cut.rs
- src/ln/ln.rs
- src/mkdir/mkdir.rs
- src/mv/mv.rs
- src/rm/rm.rs
- src/stdbuf/stdbuf.rs
- src/touch/touch.rs
- src/uucore/fs.rs
- src/wc/wc.rs
Now that Path has stabilized in Rust 1.5, I removed the UUPathExt trait
needed to support stable, beta, and nightly.
> Remove trait shim needed before Path stabilized

- Makefile
- src/tail/tail.rs
- tests/fixtures/tail/foobar.txt
- tests/fixtures/tail/foobar_single_default.expected
- tests/fixtures/tail/foobar_stdin_default.expected
- tests/tail.rs
I added a few simple tests. I also simplified `tail`'s settings in the same manner as `head`.
After adding the tests, I uncovered a bug that caused all input lines to be stripped of the end-of-line delimiters. The previous behavior of `lines()` kept those characters. I will create an issue to track this bug.
> tail: add tests and refactor

- Makefile
- README.md
- src/uutils/uutils.rs
A make task to run busybox tests for utiltiies has been added back, with some changes.
Changes:
1. the busybox tests are now run from busybox source that is automatically downloaded and unpacked into a subdir of the repo's ```tmp``` folder
2. utilities to run busybox tests for is now determined by the ```BUSYTEST``` make variable (analogous to ```BUILD``` and ```TEST```) - the RUNTEST_ARG make variable still exists.
3. Busybox tests now run against a bash shim, instead of the ```uutils``` binary
* Because of this, running ```make busytest``` will, like running ```make test```, not create or clobber the ```uutils``` binary
fixes #742
> Add busybox test functionality

- Makefile
The generated script fails to execute due to escaped newlines.
/src/uutils/tmp/busybox-1.24.1/testsuite/basename/basename-works: /src/uutils/target/debug/busybox: /bin/bash\n/src/uutils/target/debug//deps/./$1: bad interpreter: No such file or directory
> make: fix busybox script

- src/id/id.rs
Some cases printed gid instead of uid.
> id: fix '-u'

- src/hostname/hostname.rs
hostname -i always failed with:
$ uutils hostname -i
hostname: error: invalid socket address
> hostname: fix '-i'

- Makefile
Some busybox tests failed because passing of empty ("") argument to the util didn't work.
> make: fix passing empty arguments to busybox tests

- Makefile
- README.md
- appveyor.yml
- src/uutils/uutils.rs
- tests/common/util.rs
Key changes
1. Appveyor script now creates downloadable artifacts (zip of single call binaries, and multicall binary) on test success
2. Installed multicall utilities can now be prefixed using PROG_PREFIX make param
3. Utilities are only built during install if they are going to be installed
Additional minor changes described in commit notes for "fixes for linux install" commit (d99d5c1)
> *nix install script and appveyor script

- Makefile
- README.md
changes as suggested for #766 by @ebfe 
remove split of destdir into two params
use ```ln -f``` option to clobber old binaries rather than unnecessary rm
> Changes as suggested for #766

- Makefile
- src/uutils/uutils.rs
@ebfe suggested in #769 to make use of the previous infrastructure (of careful ux specification for the multicall binary) to support newer busybox tests rather than adding complexity to the makefile. This PR uses that approach.
> resolve bug where newer busybox tests would not run, multicall method as suggested in #769

- .travis.yml
* Run CI on OS X
* Cache .cargo to make CI faster
I anticipate test under OS X will fail because OS X support of current coreutils is broken
> CI on OS X too. And cache .cargo

- Makefile
As raised by @ebfe in #773 
currently, on call of the install target, INSTALL is expected to override BUILD (and same for DONT_INSTALL), and to default to all packages.
The former behavior recently had its implementation corrected (#770). This commit implements the latter behavior, which was missing.
> default INSTALL to list of progs

- src/seq/seq.rs
I simplified formatting code for seq a bit and fixed a mismatch in busybox test that occurred due to default float formatting. I.e.
```
echo -ne '' | seq .7 -.9 -2.2
FAIL: seq count by -.9
--- expected	2015-12-26 15:58:44.242175239 +0300
+++ actual	2015-12-26 15:58:44.244175239 +0300
@@ -1,4 +1,4 @@
0.7
--0.2
+-0.20000000000000007
-1.1
-2.0
```
> Fix busybox seq formatting test

- tests/common/util.rs
Allows setting environment variables in the test process.
> tests: add UCommand::env()

- Cargo.lock
- src/chmod/chmod.rs
- tests/chmod.rs
I rewrote the monstrosity that was the former mode parser.  At the moment, I have fixed `+octal`, but `-octal` is still not working because of getopts (see #788).  I have also re-enabled the tests that now pass.
> chmod: rewrite mode parser

- .travis.yml
- .travis_fixup.sh
- Cargo.toml
Kind of hacky but makes the stable/beta builds less useless.
Also useful to detect newly introduced reliance on the nightly.
Skipped utils: expand fmt tr unexpand
> travis: skip unsupported utils on stable/beta builds

- src/uucore/fs.rs
We were apparently resolving symlinks when examining metadata, so files were never considered to be symlinks.
> uucore: don't follow symlinks when examining them (fixes #799)

- Makefile
Basically busytest would stop testing whenever a utility failed to pass a test, and I wanted to see which utils actually passed all the tests.
> Allow selection of tests to not pass to BusyBox

- Makefile
Reverts uutils/coreutils#805
I somehow did not notice that `DONT_BUSYTEST` and `BUSYTEST` exist, so I added redundant functionality.
It probably won't make much of a difference if we decide to keep the redundancy, though.
> Revert "Allow selection of tests to not pass to BusyBox"

- Cargo.lock
- src/tr/tr.rs
The `bit_set` cargo changed `contains()` to only accept the parameter by value instead of reference.
> Fix type mismatch error.

- tests/fixtures/.gitattributes
This prevents line ending conversion to CRLF by git under Windows.
Without this patch tests on cat (or anything using tests/fixtures) are failing on Windows machine and git with default settings. AppVeyor seems to be ok (probably core.autocrlf is not set to 'true' there)
> .gitattributes: treat tests/fixtures/** as binary data

- Cargo.toml
- Makefile
- README.md
- build.rs
- tests/printf.rs
Allows use of integration tests feature gated by the "unimplemented" feature e. g.
```
#[cfg(feature="unimplemented")]
#[test]
fn sub_num_hex_float_lower() {
expect_stdout(vec!["%a", ".875"], "0xep-4");
}
```
Also adds make ```SPEC=y``` option (e.g. ```make UTILS='...' SPEC=y test```) that will include these tests and include the ```--no-fail-fast``` option.
Writing tests for implemented functionality only requires knowing which features are implemented which usually entails an intimate knowledge of the implementation
Because good practice is to write integration tests for each feature implemented anyway, if we allow writing the tests before implementation, this allows us to express (through code and automatically through a nice-looking CI results page if desired) what features are and …
> allow feature-gated integration tests for unimplemented functionality

- src/cat/cat.rs
minor fix, matches the behavior of GNU ```cat --squeeze-blank``` to keep up to 1 blank line in a row for all groups of blank lines
```printf "a\n\n\nb\n" | cat -s```
now results in:
```
a
b
```
> cat: --squeeze-blank keeps up to one blank line

- tests/common/util.rs
- tests/ln.rs
- tests/mv.rs
- tests/rm.rs
- tests/tr.rs
A set of additional convenience functions, and one breaking change, to the testing utility module to make testing more ergonomic, and more consistent across tests (e.g. avoiding the possibility of each test class developing their own convenience functions that does basically the same things but may have minor differences).
The ergonomic jumps here are made from the repetition that we know we will generally be making assertions on the result of this command we are running, rather than another variable. And because this command helper is only being run in a test context, we know already when using it that we will be making assertions.
In the general use case, there are benefits in the sense that most of what we are asserting is very standardized, so if we can standardize around particular …
> more ergonomic testing

- src/link/link.rs
As can be seen from this [this appveyor console](https://ci.appveyor.com/project/nathanross/coreutils/build/1.0.3) another reason the appveyor tests are currently failing is because ```link``` returns two different error messages for the same error scenario.
This is because link directs to the stderr the string value of ```std::fs::hard_link``` whose returned error message varies by platform for the same scenario, because these are the os error messages retrieved from the respective libc calls.
This commit changes the implementation to return the error message specified in the test for that error scenario on all platforms. That this resolves the issue on windows is demonstrated in [this appveyor console](https://ci.appveyor.com/project/nathanross/coreutils) of a separate branch that …
> link: normalize file-not-found error message across platforms

- src/dirname/dirname.rs
> Dirname: fix windows' failing test for absolute-path behavior (approach 2/2: platform-independent behavior)

- src/chmod/chmod.rs
- tests/chmod.rs
Change the reference option so that the file path is mandatory
Fix C interface using CString.
Better error message if the file doesn't exist.
I'm not sure if there's a better way to create a reference file for tests, right now I'm creating it for every test.
> chmod: fix reference option

- README.md
- src/fmt/fmt.rs
- src/fmt/parasplit.rs
- src/tr/tr.rs
Hi,
this patch fixes coreutils to compile on stable Rust by mostly following the recommendations given when removing the feature flags. In detail, that is:
* remove `fmt`s dependency on `rustc_unicode`. It wasn't using it anyways.
* Remove `CharRange` usage from `fmt` and use the recommended handling methods (`char_indices` and `chars`). These methods recently got deprecated, see https://github.com/rust-lang/rust/issues/27754, the struct is not committed to.
* Remove usage of io::Read::chars() in `tr`. The method is still under debate (https://github.com/rust-lang/rust/issues/27802). As a buffered reader is used anyways, I concluded that we could just read into a buffer and work on that. I'm rather unsure if this patch is super-clean, it's a bit late. All tests pass and I think logically, …
> Move to stable

- src/sleep/sleep.rs
Durations longer than ~4s were overflowing u32 and just.. not working.
> Fix sleep duration calculations.

- src/uucore/Cargo.toml
Fix build on Linux
Built with `rustc 1.7.0`
Fix  #838
> Add missing lib.name for uucore

- src/sort/sort.rs
- tests/fixtures/sort/month1.ans
- tests/fixtures/sort/month1.txt
- tests/sort.rs
In addition to sorting by month, I moved the options into a dedicated settings struct for future enhancements. I also updated the flag for human-numeric sort to be in sync with GNU coreutils.
> sort: refactor and add month sort

- tests/fixtures/tail/foobar_bytes_single.expected
- tests/fixtures/tail/foobar_bytes_stdin.expected
- tests/tail.rs
I noticed that there weren't any tests for tailing bytes rather than lines, so I whipped up some simple sanity tests.
> Tests for `tail -c <bytes>`

- tests/common/util.rs
Due to canonicalize()'s use of GetFinalPathNameByHandleW() on Windows, the resolved path starts with '\\?\' to extend the limit of a given path to 32,767 wide characters.
To address this issue, we remove this prepended string if available.
Source: http://stackoverflow.com/questions/31439011/getfinalpathnamebyhandle-without-prepended
ping @nathanross
> tests/pwd: fix broken Windows test

- src/tail/tail.rs
- tests/common/util.rs
- tests/tail.rs
* Test when `-n` is larger than the number of lines in the file
* Rename `INPUT` to `FOOBAR_TXT` as there are more than one inputs
* Add a test for tail'ing large files in bytes mode
* Refactor the `test_single_big_args` test to use `ScopedFile`
* Create the `ScopedFile` type for temporary files in tests
* When tailing a file in bytes mode, seek directly to the specified byte
* Pre-fill the buffer with zeroes
See each commit and commit message for more details.
> Miscellaneous `tail` related commits

- tests/common/util.rs
- tests/readlink.rs
- tests/realpath.rs
Both tests for `readlink` and `realpath` assumed that paths used a forward slash to separate directories. This caused errors for Windows.
> Fix readlink/realpath tests on Windows

- Cargo.lock
- build.rs
- src/hashsum/hashsum.rs
Only the fixed output-size functions are supported, SHAKE128 and
SHAKE256 are not included for now.
> hashsum: add support for SHA-3 functions

- Makefile
- src/od/od.rs
- tests/od.rs
Adds features, all from origial `od` that were missing: 
- add extra spaces to output to match format of origial `od`
- accept multiple files as input, concatenating
- accept stdin as, either when no args or as arg '--' 
- create first tests for these features
There are still missing flags, but if no missing flags are given, output should match origial `od` exactly if no error, or very close if error. (For instance rust's file not found error is a little longer)
> add functionality to od

- Cargo.lock
- Cargo.toml
- Makefile
- src/ls/Cargo.toml
- src/ls/ls.rs
- src/ls/main.rs
- tests/ls.rs
This is a basic implementation of `ls` that produces output roughly analogous to `ls -l`. The `-h`/`--human-readable` option is also implemented.
See #126 for outstanding items.
> Basic implementation of ls

- appveyor.yml
The Windows build no longer relies on make. This allowed me to remove the msys2 installation and greatly simplified the build. We now build on three Windows targets instead of one.
Fixes #804
> Update Appveyor build

- src/od/od.rs
- tests/test_od.rs
Adds most of the single letter format flags and outputs their lines in the order that the options were given on the cmd line. Still no: floating point, '-t ...' options, multi-char.
> od: take more format options, respect their order.

- Cargo.lock
On a hunch after noticing the link errors with the rust-crypto crate, I ran `cargo update` to update all dependencies. The `i686-pc-windows-msvc` build finally passed. This is probably related to improved Rust support on Windows, as noted here:  https://github.com/DaGenix/rust-crypto/pull/360.
> Fix Windows build on all supported targets

- src/tail/tail.rs
- tests/fixtures/tail/follow_stdin.expected
- tests/test_tail.rs
Brings back the `follow()` call when reading from stdin. (issue #891)
> Follow stdin

- src/fmt/fmt.rs
- src/fmt/parasplit.rs
Current behavior of `fmt` is broken when processing empty, prefixed lines with the -p option. This change fixes that.
Here's an example of what was wrong before:
```
[user@host]$ fmt -w 80 -p\>
>
>  asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf
^D
>  >  asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf
```
Correct output is:
```
>
>  asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf
```
`fmt` needs some tests. I thought I'd written some once, but either I have a bad memory or they've disappeared. I'll try to find some time to write new ones, but it probably won't be any time soon, so it's probably not worthwhile to put them in the same PR as the above fix.
> fix fmt's behavior for blank prefixed lines

- Cargo.lock
- Cargo.toml
- Makefile
- README.md
- src/install/Cargo.toml
- src/install/install.rs
- src/install/main.rs
- src/install/mode.rs
- tests/test_install.rs
- tests/tests.rs
This pull request implements install, with basic functionality.
**Included:**
- _install_ is now built as a utility
- `install file1 file2 directory/` works
- `install -d comp1 comp2` works
- `install --mode=345 file directory/` works
- all command line options from GNU are displayed in help
- all unimplemented options are marked in help
- all unimplemented options give nice error
**Testing:**
- all implemented functions have extensive integration tests
- we test that all unimplemented features are reported
- we test obvious failure cases
- [tested with Travis](https://travis-ci.org/beneills/coreutils)
- [tested with Appveyor](https://ci.appveyor.com/project/beneills/coreutils)
**Notes:**
- all functions are documented for rustdoc
- we based the skeleton off _mv_
- a minimum _libc_ …
> Implement install

- src/cp/cp.rs
- tests/fixtures/cp/hello_dir_with_file/hello_world.txt
- tests/test_cp.rs
I added the following flags to cp:  
* -v/--verbose  
* -t/--target-directory  
* -T/--no-target-directory  
And created two tests to verify that files are copied into and out of folders correctly.  
These tests helped find a bug, which I fixed (when copying files from a directory other than cwd, the destination files would be named after the entire path given, and not the file name itself)  
I'm not sure whether to "adopt" cd, because I'm just a beginner and someone more experienced might be a better fit for this, and get things done more quickly, but I'll work on this as much as I can.
> Added some functionality and tests to cp

- Makefile
Currently the README.md advises users to continue to use the makefile for running tests. 
This commit makes running tests via make faster by removing an extraneous binary build that previously occurred prior to each test.
> Tests run using makefile skip separately building binaries

- tests/test_cat.rs
With these additions, the tests should now cover at least one example case of every flag of ```cat```, including the status code result and an empty stderr.
> tests: feature-complete cat integration tests

- tests/common/util.rs
This changes, where applicable, the ```assert!``` macros called by util.rs to the more idiomatic ```assert_eq!``` macro, with this change users will always be able to compare the results of a failed string equality test.
> tests/common: use more idiomatic asserts

- tests/test_base64.rs
- tests/test_cat.rs
- remove extraneous uses of ```run``` or ```run_piped_stdin```
- remove extraneous uses of ```vec!```
- remove extraneous uses of ```as_bytes``` (```run_piped_stdin``` and ```pipe_in``` both now use ```Into<Vec<u8>>```)
- remove an extraneous use of >2 ```arg``` calls for the same command instead of ```args```
> Tests: minor refactor for dryness of base64 and cat tests

- Cargo.toml
- Makefile
- README.md
- src/pinky/Cargo.toml
- src/pinky/main.rs
- src/pinky/pinky.rs
- src/pinky/utmp.rs
- src/uucore/c_types.rs
- src/uucore/utmpx.rs
- tests/test_pinky.rs
- tests/test_stat.rs
- tests/tests.rs
TODO:
--------
Unsolved problem:
------------------------
Pinky needs to read `struct utmp`s from `/var/run/utmp`, but the definition of `struct utmp` on Linux goes like this:
```C
struct utmp {
...
...
/* The ut_session and ut_tv fields must be the same size when
compiled 32- and 64-bit.  This allows data files and shared
memory to be shared between 32- and 64-bit applications. */
#if __WORDSIZE == 64 && defined __WORDSIZE_COMPAT32
int32_t ut_session;           /* Session ID (getsid(2)),
used for windowing */
struct {
int32_t tv_sec;           /* Seconds */
int32_t tv_usec;          /* Microseconds */
} ut_tv;                      /* Time entry was made */
#else
long   ut_session;           /* Session ID */
struct timeval ut_tv;        /* Time entry was made */
#endif
...
...
}
```
which …
> Implement pinky

- Makefile
- README.md
The previous runs of `make UTILS='stat dircolors ...etc.' test` would compile multiple times, which is somewhat inefficient.
In addition, I updated the TODO list on README according to the [online manual](https://www.gnu.org/software/coreutils/manual/coreutils.html). BTW, are we going to implement chcon/runcon which are related to SELinux context?
> Minor changes

- appveyor.yml
If you're testing multiple features with cargo and do not wrap them in quotes, no tests are run
> ci: fix appveyor cargo test call

- Makefile
This permits the use of, *e.g.*, `ginstall` or `uu-install`.
> Allow choice of `install` program

- src/arch/Cargo.toml
- src/arch/arch.rs
- src/cut/Cargo.toml
- src/cut/cut.rs
- src/uucore/Cargo.toml
- src/uucore/coreopts.rs
- src/uucore/lib.rs
- src/uucore/macros.rs
This PR's first commit adds a group of Macros in ```uucore/macros.rs``` which we could call "Message Templates"
The second commit adds ```uucore::coreopts::CoreOptions```, a facet for ```getopts::Options``` that handles error output uniformly for option parsing failure cases. The reason it is a facet and not a function is to enable eventual uniformity in how option flags are displayed in error messages (for example, if we want to, for options with a shortform and longform, always display both forms when referencing a problem with an option, that is not possible with using just a function)
The third commit demonstrates CoreOption and Message Templates usage by making use of them in the ```cut``` implementation. I've added this and the following sample commit so that this PR does not add a …
> Add Message templates

- tests/common/util.rs
often when stdout is wrong, differences in stderr are more useful for determining the cause
> tests/common: more communicative assertion failure messages

- src/arch/arch.rs
- src/cut/cut.rs
- src/uucore/coreopts.rs
- src/uucore/macros.rs
Using uucore::coreopts, `<prog> --version` will print out:
```
uucore::coreopts 0.0.1
```
because of the `executable!()` macro.
I decided to pass the program name to `CoreOptions` to fix this problem.
> coreopts: display package name instead of module path

- tests/test_echo.rs
I don't know of any failure cases for echo, so I think with this commit, echo is tested as feature complete, except for the question of whether --help and --version should print a help and version message.
One stylistic choice of this commit is to break up escape tests into separate tests to explicitly document which character is being tested so that readers of the test can understand without cross-referencing another document. 
This choice is not very dry, however, so I could be easily convinced to keep it in the old format of all one test, possibly with using comments.
> tests/echo: complete tests except for --help and --version

- src/arch/arch.rs
- src/cut/cut.rs
- src/pinky/pinky.rs
- src/uucore/coreopts.rs
- src/uucore/lib.rs
- src/uucore/macros.rs
- src/who/who.rs
This PR builds on knight42's bugfix of passing in package name in the constructor to also pass in version. The result of this is that the version is that of the utility itself rather than the version uucore.
Additionally, syntax, summary, and long help are now passed in as separate strings. In this way each uumain() function need not repeat their relative position. These changes offer the following the benefits:
- keeps code dry, as utilities no longer have to individually create a format string for utility name, version, syntax, usage summary, and long help
- better reflects the actual semantics of coreopts than the previous approach where the long help was required to use coreopts parse but this was not enforced at compile-time.
> Coreopts further refinement

- src/cut/cut.rs
- tests/test_cut.rs
This is the same behavior that GNU coreutils currently has for cut: it is not UTF-8 aware, the use of the ```--characters/-c``` option is essentially an alias for the ```--bytes``` option. If it does change in the future to become UTF-8 aware we can go back through version control and revive this code.
> cut: make chars mode use byte mode behavior

- src/tail/tail.rs
- tests/test_tail.rs
main panics when following /dev/stdin since /dev/stdin is not seekable.
Check to see if file is seekable and use unbounded_seek if not.
Also tail should ignore `-f` if no files are passed.
> tail: fix bug when following /dev/stdin

- README.md
- src/mv/Cargo.toml
- src/mv/mv.rs
- tests/test_mv.rs
The unimplemented option of `mv` is `-Z/--context` which is a Linux-specific option and I *guess* it can be ignored for the time being.
> mv: cleanup the code

- appveyor.yml
As per discussion in #943
What appveyor now does in regard to installing mingw.
* if in 386 GNU, checks if the mingw version specified in the environment var exists at the cached location
* if it is not, it wipes the cached location if it exists, makes a new directory there and any necessary parent directories, and downloads the specified version of mingw
* then the the extraction of binaries continues as normal, only referencing the archive in a different location now.
It is probably possible to extract, and then remove the archive, and just have the extracted directory be cached instead of the installer. That could be a possible future upgrade, but I'm not sure it would be worth the complexity cost.
> appveyor: add cache of mingw download

- src/who/who.rs
`who` fails to compile on a raspberry pi 2. This commit fixed that.
`idle_string` was using `time_t`. But it is called with the result of [`meta.atime()`](https://doc.rust-lang.org/std/os/unix/fs/trait.MetadataExt.html#tymethod.atime), which returns an `i64`. And it is compared with [`n.to_timespec().sec`](https://doc.rust-lang.org/time/time/struct.Timespec.html), which is also an `i64`. So it seems appropriate to use `i64` instead of `time_t`.
> who: fix build on raspberry pi 2

- src/more/Cargo.toml
- src/more/more.rs
see also #990; the build of more fails on windows. [nix](https://crates.io/crates/nix) is the reason. As it does not contain any windows specific code, I moved all related code to two functions and added dummy functions to call on windows.
error message on my test system:
```
w@w7 ~/coreutils/src/more
$ rustup show
Default host: x86_64-pc-windows-gnu
stable-x86_64-pc-windows-gnu (default)
rustc 1.12.0 (3191fbae9 2016-09-23)
w@w7 ~/coreutils/src/more
$ cargo build
Compiling more v0.0.1 (file:///C:/cygwin/home/w/coreutils/src/more)
error[E0432]: unresolved import `nix::sys::termios`. Could not find `sys` in `nix`
--> more.rs:22:5
|
22 | use nix::sys::termios;
|     ^^^^^^^^^^^^^^^^^
error: aborting due to previous error
error: Could not compile `more`.
To learn more, run the command again …
```
> more: fix build on windows

- src/ln/ln.rs
- src/ls/ls.rs
ln: allow linking directories via symlinks on Windows
ls: more POSIX compliant symlink behavior
ls: fix -aR recursion
Attempting to use this (day to day) as a replacement for msys2 
revealed these issues quickly. ln -s would create a file no matter what
and ls wouldn't deal with symlinks the same as GNU ls or FreeBSD ls.
Probably more comprehensive unit tests are warranted, but these build,
pass the existing tests, and appear to work as-expected and are
modeled the same way as existing code.
Fairly certain there's a better way to fix the recursion than cloning,
but I'm still admittedly getting used to Rust. I didn't notice any problems
on excessively long paths (on Windows), though.
Symlink code also doesn't try to figure out a trailing slash yet with -l, but neither did the original.
> trivial windows fixes

- tests/test_stat.rs
See also #996 for diagnostics.
The travis builds on linux run inside a docker container. It looks like travis has changed the containers some time ago. Now all builds on linux fail because gnu stat does not detect the bind-mount of /dev/zero. This causes the output to be different, and the test to fail.
I assume `test_char` is meant to test a character special file in `/dev`. This PR uses `/dev/pts/ptmx` instead, both stat versions agree about it's output.
See https://travis-ci.org/wimh/coreutils/builds/177738828 where I added some additional logging.
> stat: fix test on travis

- Cargo.lock
- src/printf/memo.rs
- src/printf/tokenize/num_format/formatter.rs
- src/printf/tokenize/sub.rs
The purpose is to update the dependency of `num_cpus` for `nproc`. `num_cpus` v1.2 [has Fuchsia support](https://github.com/seanmonstar/num_cpus/pull/28) now.
ref #999.
cc @raphlinus.
> Update dependencies and solve deprecated warnings.

- src/cat/Cargo.toml
- src/cat/cat.rs
- Less if branches: declare variables _tab_ and _end_of_line_ in the beginning of the functions and use them instead of **if-s**
- Unnecessary range variable deleted: use simple _i32_ instead
- Optional fail-assertion commented: it is local for cat utility and is always true. At the same time it is in the bottleneck function and increases the run time significantly
- Use rustfmt to structure code
> cat utility refactoring

- src/od/od.rs
I noticed `od --help` was not working any more. 
`-h` is used for hexadecimal 2-byte units output, not for help....
> od: fix od --help

- build.rs
- tests/common/util.rs
The errors were caused by the missing env $OUT_DIR which should be set by
cargo. 
[Related issue](https://github.com/rust-lang/cargo/issues/3368)
> Temporary fix for errors in testing

- Cargo.lock
- Cargo.toml
- tests/test_chmod.rs
- tests/tests.rs
`test_chmod_many_options` relied on user's umask not denying read access for anyone. 022, which is the default umask for many, indeed allows read access for everyone. I'm using 027, which disallows read for everyone but owner and group. This made tests fail.
Now tests set and reset umask, ensuring checks are run in a reliable, predictable environment.
`test_chmod_ugoa` already tests chmod's behaviour with different umasks, so it's sufficient to run this test with one particular umask.
> tests/chmod: don't make assumptions about umask

- Cargo.lock
- src/tail/Cargo.toml
- src/tail/README.md
- src/tail/platform/mod.rs
- src/tail/platform/unix.rs
- src/tail/platform/windows.rs
- src/tail/tail.rs
- tests/test_tail.rs
GNU coreutils have one more use-case for `--pid`, actually, but it doesn't apply to us because we don't support inotify:
```
-s, --sleep-interval=N   with -f, sleep for approximately N seconds
(default 1.0) between iterations;
with inotify and --pid=P, check process P at
least once every N seconds
```
> tail: implement --pid

- src/mkdir/mkdir.rs
- tests/test_mkdir.rs
Fixes #1017.
test_mkdir_dup_dir asserted that creating an existing directory is an
error, but that's not how GNU coreutils behaves. This has been reported
in #121, but wasn't fixed (only the `-p` case was).
> mkdir: trying to create existing dir is fine

- Cargo.lock
- Cargo.toml
- src/cat/Cargo.toml
- src/cat/cat.rs
- tests/test_cat.rs
BSD cat supports output from unix domain sockets.
This PR adds unix socket domain support for the `cat` utility.
For ease of future extensibility:
- moved params into `OutputOptions` struct for configuration
extensibility
- introduced Results to functions, removing unwraps
- uutils `cat` used to panic on broken stdout pipes (e.g. `cat
/dev/zero | head -c1`).  this is fixed in this PR
- updated to exit 0 on success, and 1 if an error occurs.
Differentiates file types:
- logs an error on printing a directory
- implements cat from domain sockets
- categorizes other filetypes for extensible differentiation of behaviors
todo:
closes #1023
> add cat support for unix domain sockets

- src/ls/ls.rs
- tests/test_ls.rs
This fixes #1019 .
In my understanding, windows don't have the notion of inode, so I'm implementing this option only on unix-like OSes.
I'm sorry that the tests aren't enough. This is because inodes may vary over each environments.
> ls: implement -i option

- src/cat/cat.rs
- tests/fixtures/cat/nonewline.txt
- tests/test_cat.rs
Make `at_line_start` persist between printing each file. This fixes an
issue when numbering lines in the output and one of the input files
does not have a trailing newline.
```
❯ cat -n tests/fixtures/cat/nonewline.txt tests/fixtures/cat/alpha.txt
1	text without a trailing newline     2	abcde
3	fghij
4	klmno
5	pqrst
6	uvwxyz
```
```
❯ cat -n tests/fixtures/cat/nonewline.txt tests/fixtures/cat/alpha.txt
1	text without a trailing newlineabcde
2	fghij
3	klmno
4	pqrst
5	uvwxyz
```
> cat: fix for numbered lines w/ no trailing newline

- Cargo.lock
- Cargo.toml
- src/date/Cargo.toml
- src/date/date.rs
- src/date/main.rs
- src/date/usage.txt
Here's a partial implementation of `date`.
Things that work:
- Printing the current date/time in UTC or local time
- Command line arguments
- Printing in various formats (standard formats and user supplied format string)
- Reading from a file
Things that don't work:
- Handling the variety of ways in which the GNU `date` program parses string input ("next week", "yesterday", etc)
- Setting the system clock (need to be able to parse the time first)
- Printing the name of the time zone
I don't have any tests yet. I'm not quite sure how to approach them, since most of the things this program does depend on the system clock.
> Partial implemantion of date.

- src/ln/ln.rs
- tests/test_ln.rs
The following should work, but without this patch, it tries
to create the link as x/y and it fails with EEXIST.
$ mkdir -p x/y
$ ln -s -t . x/y
> ln: Use basename when target directory is specfied

- src/mkdir/mkdir.rs
- tests/test_mkdir.rs
Currently, mkdir always succeeds for existing files and it
even modifies their mode. With this change, only mkdir -p for
existing directories will be allowed.
> mkdir: Fix the behavior for existing files

- src/rm/rm.rs
- tests/test_rm.rs
Path::is_dir follows symlinks so it returns true for symlinks
to directories. Use symlink_metadata instead so you can remove
symlinks to directories without -r flag.
> rm: Remove symlinks to directories without -r

- src/rm/rm.rs
- tests/test_rm.rs
Checking with file.exists() was not good for this purpose as
Path::exists() returns false for invalid symlinks.
> rm: Remove invalid symlinks

- src/id/id.rs
#[cfg(not(target_os = "linux"))] spelling mistake
> Ensure "linux" not targeted instead of "linu" =D

- Cargo.lock
- src/nproc/Cargo.toml
- src/nproc/nproc.rs
* Upgrade num_cpus crate to 1.5.0.
* Use sysconf(_SC_NPROCESSORS_CONF) when `--all` query given.
> nproc: counts CPU cores via affinity mask if available on Linux

- src/tr/Cargo.toml
- src/tr/tr.rs
FnvHashMap is much faster for small inputs like intergers, and we literally have a hashmap with chars as keys in tr. This reduces runtime for tr in substitution mode from 40 seconds to 30 seconds on my 1.7Gb unicode test file.
Using FnvHashSet instead of BitSet in tr delete mode did not measuarably impact performance, so I did not convert it. I have also grepped for "Hash" and checked if using FnvHash made sense in other places; it did conceptually, but did not result in measurable performance improvements, so I did not convert those.
This adds dependency on the `fnv` crate, but it's quite mature and even used inside `rustc` itself, so that should not be a problem.
> tr: use FnvHashMap instead of default HashMap backed by SipHasher

- src/ln/ln.rs
- tests/test_ln.rs
ln had a bunch of problems:
1. `ln -s target` didn't work (2nd form in help).
2. `ln -t tmp` wasn't an error. We should check if files are
empty first.
3. `ln -s file dir` didn't create dir/file.
4. `ln -s -T file dir` was removing `dir`.
5. Test cases for 4 say this is for compatibility with GNU
coreutils but I couldn't find this feature.
> ln: Fix how it selects the form

- Cargo.lock
- src/cp/Cargo.toml
- src/cp/README.md
- src/cp/cp.rs
- tests/fixtures/cp/existing_file.txt
- tests/fixtures/cp/how_are_you.txt
- tests/test_cp.rs
I know there are at least two other open PRs for `cp` so I figured I throw this one up that I started some time ago in case it's useful.
I'd like to finish this up, but just haven't gotten around to it.
cc @Matt8898 @jerenept  @Arcterus
> implement many copy flags

- README.md
'date' has been partially implemented into the coreutils. According to
[this](https://github.com/uutils/coreutils/pull/1029) I decided to move 'date' into the 'Semi-Done' section from the
readme utilities chart.
> README: Moved 'date' into the 'Semi-Done' section.

- src/cp/cp.rs
- tests/test_cp.rs
Fixes https://github.com/uutils/coreutils/issues/1067.
> Correct behavior of cp -r with non-existent dest

- src/cp/Cargo.toml
- src/cp/cp.rs
> cp: add support for --attributes-only and setting timestamps, links and xattrs

- src/tail/tail.rs
- tests/fixtures/tail/foobar_multiple_quiet.expected
- tests/test_tail.rs
A first stab at adding the `--quiet` flag to `tail`.
As mentioned in the TODOs the `--silent` alias is missing so far. Not sure how (and if) this is possible with getopts. If clap can do this it might be a good reason to move forward with #1006?
Another open point is taking the position of `-q` and `-v` into account. Again, not sure if this is even possible with getopts...
> tail: suppress headers when --quiet flag is used

- src/basename/basename.rs
- tests/test_basename.rs
I noticed that some utilities are also using getopts or clap. Stuck with coreopts in this case to keep changes to a minimum. Appreciate any feedback.
> basename: add -a, -s and -z flags

- src/cp/cp.rs
Noticed that `cp` displays usage twice. Possibly because clap did not support custom usage at the time.
Custom usage looks like this:
```
cp [OPTION]... [-T] SOURCE DEST
cp [OPTION]... SOURCE... DIRECTORY
cp [OPTION]... -t DIRECTORY SOURCE...
```
versus autogenerated
```
cp [FLAGS] [OPTIONS] [--] [paths]...
```
> make cp print usage correctly

- src/chmod/chmod.rs
Moved all functions for the actual chmod operation into a struct; I'd like to do some further refactoring there in the future...
> chmod: avoid passing all args through function hierarchy

- Cargo.lock
- Makefile
- src/pinky/pinky.rs
- src/stdbuf/Cargo.toml
- src/stdbuf/Makefile
- src/stdbuf/build.rs
- src/stdbuf/libstdbuf/Cargo.toml
- src/stdbuf/libstdbuf/libstdbuf.rs
- src/who/who.rs
- tests/test_base32.rs
- tests/test_base64.rs
- tests/test_uniq.rs
Hopefully this should solve issues #1072, #1064, and #1040.  It's a little fragile as it depends on the structure of stuff that `cargo` generates.  I also have not tested the build for Macs as I do not have one accessible at the moment.
> Fix Makefile and stdbuf

- .travis.yml
- README.md
> Document supported versions and test minimum

- .cargo/config
- .travis.yml
- .travis/redox-toolchain.sh
- src/cp/cp.rs
It is helpful to make sure things are building on Redox, though It's understandable if you don't want Redox breaking CI.
I ran `cargo update` since Redox required newer versions of a dependency or two.
>  Add cross build targeting Redox to Travis CI

- src/du/du.rs
The old implementation spawned a thread for every subdirectory found.  This change gets us closer to the speed of GNU's implementation (and prevents us from exhausting resources so easily).
> du: remove inefficient multi-threading

- src/install/install.rs
Do the same as GNU coreutils do.
> install: ignore -c option for compatibility

- src/uname/Cargo.toml
- src/uname/uname.rs
The --sysname flag in GNU uname was deprecated in 2002 and replaced by --kernel-name.
> uname: change sysname flag to kernel-name

- .travis.yml
- README.md
The coverage is generated using Tarpaulin (which seems somewhat inaccurate but is a lot easier to set up than kcov).
> Start using Codecov

- src/yes/yes.rs
See #1085.
On my computer, it makes coreutils' yes go from 3MB/s to 4GB/s. As a comparison, GNU yes is at 5GB/s.
> Make 'yes' 1000 times faster.

- src/tail/README.md
- src/tail/tail.rs
Add spaces after title hashes to correct formatting.
> tail: add spaces after hashes

- src/hashsum/hashsum.rs
- src/pinky/pinky.rs
- src/truncate/truncate.rs
- src/wc/wc.rs
Since 1.23 stable no need to import AsciiExt explicitly.
> refactor: remove import of AsciiExt

- src/stat/stat.rs
* Avoid parsing the `MOUNT_INFO` file when showing filesystem information
* Replace hard-coded /etc/mtab in error string with formatting
> stat: Minor improvements

- src/realpath/realpath.rs
- src/relpath/relpath.rs
Apparently the fix for nightly broke stable and beta (which I was not aware of because the only build that actually started was the nightly one).  This should work for everything.
> realpath, relpath: fix on stable and beta (whoops)

- src/join/join.rs
- tests/test_join.rs
Enables line order checks by default, with options to either completely turn them off, or turn them on, making the program fail upon the first unsuccessful check.
> join: check line order

- README.md
The package set `nixpkgs`, NixOS relies on provides `uutils-coreutils`
out of the box since 18.03/unstable.
See https://github.com/NixOS/nixpkgs/pull/34840
> Add installation instructions for NixOS

- codecov.yml
This can be merged after ensuring that the build in fact does not fail.
> Add configuration for Codecov to prevent it from failing builds

- src/du/du.rs
When du encounters a file that cannot be read it logs an error and
continues to analysise the rest of the directory. This behaviour brings
it inline with the original du.
fixes #1155
> Fix edge case for du on mac

- Cargo.toml
- src/tail/Cargo.toml
- src/tail/platform/mod.rs
- src/tail/platform/redox.rs
This requires https://github.com/redox-os/kernel/pull/86 to work correctly (it builds and runs fine without that, but the `--pid` feature won't work without that kernel change).
> Port 'tail' to Redox

- Cargo.lock
- src/yes/Cargo.toml
- src/yes/yes.rs
This bumped the speed past GNU `yes` on my Mac.  I now get something like 4.30 GiB/s for ours compared to around 1 GiB/s for the GNU version.
> yes: use 16 KiB rather than 8 KiB for the buffer

- .travis.yml
- appveyor.yml
This should allow the build to pass (as it is always a linking error when using `x86_64-unknown-redox-gcc` on Travis).  Also, this will hopefully help fix spurious errors on Appveyor when trying to download the Rust compiler.
~If the Appveyor build doesn't start at some point, don't merge this.  I will have to see what is wrong if so.  It seems to work if I start the build manually, so I am pretty sure the issue is unrelated to my changes.~
> Allow build to fail on Redox

- src/hostname/hostname.rs
- tests/test_hostname.rs
- tests/tests.rs
Cstr::from_bytes_with_nul needs input bytes null terminated. Current
version does not include the last null byte, hence
Cstr::from_bytes_with_nul will panic with error 'FromBytesWithNulError {
kind: NotNulTerminated }'
> hostname: bug fix for non-windows xgethostname

- README.md
- codecov.yml
Also this adds a small bit describing how to build on Windows using Cargo (requested in #1174).
> Remove Codecov from and add dependency tracking to the README

- Cargo.lock
- src/uptime/Cargo.toml
- src/uptime/uptime.rs
I believe this fixes #1195.  `uptime` will also now compile on Windows, although it doesn't work correctly (missing load averages and the number of users is always 0).
> uptime: error when uptime cannot be found

- src/uutils/uutils.rs
This can get confused on Windows with powershell, where it passes .exe
for symlinks.
closes #1241
> uutils: Replace file_name with file_stem in symlink applet detection.

- src/hostid/hostid.rs
Remove old arg parsing enum. Fixes #1286
> hostid: remove old enum

- src/sort/sort.rs
Taking a look at issue #1282 the problem appears to be that the empty line is failing the numeric comparison. This change ensures that if we are not passed any value it will still properly return the expected result.
> Fix comparison of empty string to numeric f64 sort

- src/numfmt/numfmt.rs
- tests/test_numfmt.rs
This is consistent with GNU behaviour, and allows for uses like normalizing SI units:
```
$ numfmt --from=si --to=si
-> 10000000K
<- 10.0G
-> 0.001K
<- 1
```
> numfmt: support neither or both of --to and --from

- src/du/du.rs
Fixes #1295 , making -b act like `du --block-size=1 --apparent-size`, the reason it uses `stat.size` instead of `stat.nlink * stat.size` is explained in #1292 and the fix for that issue #1294 is mirrored by the use of `stat.size` here.
> Fix -b flag

- src/du/du.rs
All credit goes to @JJJollyjim in this PR https://github.com/uutils/coreutils/pull/1294, but that PR needs to be rebased over master to be mergeable and hasn't been after multiple weeks.
> Fix du --apparent-size on ext4 and MacOS

- src/cp/cp.rs
- src/factor/factor.rs
- src/ln/ln.rs
- src/mv/mv.rs
This fixes, in part only, #1103.
I’m willing to remove the other useless `BufReader` wrappers, but I am too much of a Rust newbie to know how to do that properly. I need some help.
In, for instance, `base32.rs`, it’d be easy to do:
```rust
let input = if matches.free.is_empty() || &matches.free[0][..] == "-" {
-        BufReader::new(Box::new(stdin()) as Box<Read>)
+        Box::new(stdin()) as Box<Read>
} else {
let path = Path::new(matches.free[0].as_str());
let file_buf = safe_unwrap!(File::open(&path));
-        BufReader::new(Box::new(file_buf) as Box<Read>)
+        Box::new(BufReader::new(file_buf))
};
```
This compiles. But then some repetitive hence excessive mutex locking/unlocking is going to take place.
`base32.rs` delegates to `decode()/encode()` in `encoding.rs`. There, …
> Remove some useless BufReader wrappers around stdin

- src/mv/mv.rs
- tests/test_mv.rs
- tests/tests.rs
* includes test which demonstrates the problem 
Note that this is on top of the improved testing introduced in [PR#1281](https://github.com/uutils/coreutils/pull/1281).
> fix "`mv` fails transfers between dirs"

- src/cp/cp.rs
- tests/test_cp.rs
* includes test which demonstrates the problem 
Note that this is on top of the improved testing introduced in [PR#1281](https://github.com/uutils/coreutils/pull/1281).
> fix "`cp` always creates backup"

- src/rm/rm.rs
- tests/common/util.rs
- tests/test_chgrp.rs
- tests/test_ln.rs
- tests/test_rm.rs
- tests/test_touch.rs
* includes test which demonstrates the problem
Note that this is on top of the improved testing introduced in PR#1281.
> fix ~ rm: fix dir-type symlink removal on windows

- Cargo.toml
- src/touch/touch.rs
- tests/tests.rs
- fix windows compilation
- enable testing windows
- re-categorize as "generic"
> fix ~ touch: fix and test for windows

- src/env/env.rs
@Arcterus , I just noticed that I apparently left out the final polish commit when I squashed the `fix.env` branch a couple of weeks ago.
This commit repairs that omission, fixing a couple of minor typos and adding the code commentary that I promised to add after our discussion about the INI-parser.
> env: minor fixes and commentary polish

- Cargo.lock
- src/env/Cargo.toml
- src/env/env.rs
- tests/test_env.rs
One small step towards #1358.  Apparently we were boxing `Options`, which I assume was leftover from when `Box` was `~`, so this code was very much in need of an update.
> env: refactor and move away from pre-1.0 Rust conventions

- Cargo.lock
- Cargo.toml
Redox needs libc 0.2.62 to compile currently and the latest release of atty. Update the dependencies to fix this.
cc @jackpot51
> Update the dependencies for redox compilation

- src/uptime/uptime.rs
This version:
` 22:59:49 up 10 days, 11:38, 1 user, load average: 4.07, 2.95, 2.40`
GNU:
` 23:00:05 up 10 days, 11:38,  1 user,  load average: 4.18, 3.03, 2.44`
https://github.com/coreutils/coreutils/blob/master/src/uptime.c#L149
https://github.com/coreutils/coreutils/blob/master/src/uptime.c#L161
This patch provides the same output
> uptime: match the gnu version output

- src/ls/Cargo.toml
- src/ls/ls.rs
- tests/test_ls.rs
Hi,
The --color flag did not accept argument like it should have.
I've split this into two commits because I use an additional crate: isatty
Depending on whether you want it, feel free to discard that part, or merge the two commits.
Best regards,
> ls: fix --color flag

- Cargo.toml
- build.rs
- src/cp/cp.rs
Allows older windows versions to build, using feature="windows_legacy".
- use `CreateFileW` instead of `CreateFile2`
- disable `hostname` build (current implementation isn't compatible with older Windows version)
> Fix for legacy Windows versions

- .cirrus.yml
- update FreeBSD image used to 'freebsd-12-1-release-amd64'
.# [why]
FreeBSD 12.0-RELEASE became designated as end-of-life on February 29, 2020 (removing
access to any packages for installation [eg, `curl` and `gmake`, required here], and
causing setup errors for the Cirrus CI build).
ref: <https://www.freebsd.org/security/unsupported.html>
ref: <https://www.ixsystems.com/community/threads/pkg-problem-cant-install-or-update-packages-in-11-2-u7.82368> @@ <https://web.archive.org/web/20200407230115/https://www.ixsystems.com/community/threads/pkg-problem-cant-install-or-update-packages-in-11-2-u7.82368>
> maint/CICD ~ fix FreeBSD build on Cirrus CI

- .appveyor.yml
- .codecov.yml
- .github/workflows/CICD.yml
- .travis.yml
adds work-around for bugs caused by absorption of `cargo tree` into `cargo`
ref: [GH:rust-lang/cargo#8062](https://github.com/rust-lang/cargo/pull/8062)
Fixes: #1478
> Fix `cargo tree` bug + CICD issues

- Cargo.toml
Makes the life of packagers easier
Cargo will use the most recent version when building locally anyway
> Relax the dependencies

- .github/workflows/CICD.yml
- Cargo.toml
Reorganizing and minor renaming of features within *Cargo.toml* will hopefully help to place new utilities into the best feature set, encouraging the "universal" / cross-platform aspect of the project.
"feat_require_..." sets are used to segregate utilities with restrictions limiting cross-platform availability and are annotated with the reasons for the limitations.
> feature reorganization and polish

- GNUmakefile
This ensures that docs Makefile is processed using the same binary as main one. See https://www.gnu.org/software/make/manual/html_node/Recursion.html#Recursion
> Use `$(MAKE)` variable for recursive invocations

- .codecov.yml
- .github/workflows/CICD.yml
- maint/CICD ~ change 'Style' job to a more robust, "allow-failure"-type, state
> #### [why]
>
> Compiler and clippy warnings will change over time. To avoid build failures due to some updated allow/warn categories for more future rust versions, the tests using the toolchain utilities are converted to a form which will always "pass" but will push any errors/warnings to the GHA UI as annotations.
>
> Additional build-breaking tests utilizing more stable tools (or local scripts) can be added at a later date if/when desired.
>
> This should prevent CI failures for already known-working builds.
- maint/CICD ~ fix coverage build failures by pinning to known-working nightly toolchain
> #### [why]
>
> Code coverage must currently use some unstable features in nightly rust builds. The nightly …
> Fix CI coverage

- Makefile.toml
This PR includes some additional tasks for `cargo make` and some polish on some existing tasks, especially `cargo make help`. 
- `cargo make help` output ...
```shell
[cargo-make] INFO - cargo make 0.30.6
[cargo-make] INFO - Project: uutils
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: help
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: _init_task
[cargo-make] INFO - Running Task: _init-vars
[cargo-make] INFO - Running Task: _init
[cargo-make] INFO - Running Task: action-display-help
usage: `cargo make TARGET [ARGS...]`
TARGETs:
build              Build project
build-features     Build (with features); usage: `cargo make (build-features | features) FEATURE...`
default            *DEFAULT* Build and test project
features           Build …
```
> Add/polish `cargo make` tasks

- src/uu/wc/src/wc.rs
When counting lines (`wc -l`) it is not necessary to run the expensive unicode decoding
> wc: Do not decode UTF8 when only counting bytes/newlines

- src/uu/more/src/more.rs
- tests/test_more.rs
- tests/tests.rs
> fix(more) Return a proper error message when no argument is provided

- Cargo.lock
- src/uu/mv/Cargo.toml
- src/uu/mv/src/mv.rs
Closes: #1411
I can confirm that it fixes the problem for me.
```
$ touch 1413.patch
$ ./target/debug/uutils mv 1413.patch /external
mv: error: mv: cannot move ‘1413.patch’ to ‘/external/1413.patch’: Invalid cross-device link (os error 18)
```
With the patch:
```
$ ./target/debug/uutils mv 1413.patch /external 
$ ls -al /external/1413.patch
-rw-r--r-- 1 sylvestre sylvestre 1419 mai   24 12:25 /external/1413.patch
```
> fix(mv): Allow move across file systems

- src/uu/factor/build.rs
- src/uu/factor/src/factor.rs
- src/uu/factor/src/miller_rabin.rs
- src/uu/factor/src/numeric.rs
- src/uu/factor/src/rho.rs
- src/uu/factor/src/table.rs
First pass at fixing #1456: after those changes, `factor` is 4× faster, and
“only” 48× slower than the GNU implementation (when factoring all numbers from 2
to 10⁶).
- Replaced the `Vec` of factors with a datatype that only stores each prime once
- Moved each algorithm (table-based, Pollard's rho, and Miller-Rabin) to its own module, and decoupled them.
- Removed unecessary calls to `is_prime` (~50% of the perf. gain)
- Replaced iterated division by 2 with `u64::trailing_zeros`
- Refactored and optimized the Miller-Rabin primality test, extracted dividers from the result (the other half of the performance gain)
> Performance improvements for factor

- .github/workflows/CICD.yml
- code coverage upload failure becomes a warning instead of error
> maint/build ~ allow code coverage upload failures without breaking build

- tests/by-util/test_factor.rs
- tests/by-util/test_hostname.rs
- tests/by-util/test_logname.rs
- tests/common/util.rs
- `test_factor::test_random_big` has been failing intermittently since inception
* the commit disables it and adds an investigative ToDO referring to the issue #1531
- disables failing `logname` test on WSL (has always failed) with an investigative ToDO
- MacOS `hostname` test is newly failing after wild + other dep update even though the linux version is unaffected
* disabled with a FixME until someone with a Mac PC or VM can investigate further
* increased detail failure output is ...
```text
---- test_hostname::test_hostname_ip stdout ----
current_directory_resolved: 
run: /Users/runner/runners/2.263.0/work/coreutils/coreutils/target/x86_64-apple-darwin/debug/coreutils hostname -i
CmdResult {
tmpd: Some(
TempDir {
path: "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/.tmpw8rmnN",
}, …
```
> Fix ~ disable failing tests

- src/uu/factor/build.rs
- src/uu/factor/src/factor.rs
- src/uu/factor/src/miller_rabin.rs
- src/uu/factor/src/numeric.rs
- src/uu/factor/src/rho.rs
This can probably be optimised further, but as of commit 4851619d this is already ~2.43 times faster as previously, taking ~3.55s for all integers from 2 to 10⁶.
A further optimisation would be to make the `Montgomery` implementation generic, and add a 32b variant. Moreover, a 32b variant could use a shorter basis in the Miller-Rabin primality test (either [3 witnesses], or a [single witness depending on n]).
[3 witnesses]: https://miller-rabin.appspot.com/#records
[single witness depending on n]: http://ceur-ws.org/Vol-1326/020-Forisek.pdf
This seems however out-of-scope for this PR. Moreover, such an optimisation would be currently premature, and its impact hard to measure: after this change, `factor` only spends ~10% of its time in the Miller-Rabin primality test, and another ~10% in …
> factor: Faster modular arithmetic with the Montgomery transform

- src/uu/factor/src/factor.rs
- src/uu/factor/src/numeric.rs
- src/uu/factor/src/rho.rs
- src/uu/factor/src/table.rs
I discovered yesterday that I accidentally failed to update/preserve those when
moving code around (#1525), deleting code (#1529), or adding my own
contributions.
This rectifies it, also adding years (based on git history) for all copyright
lines; I took the liberty not to track the individual changes for which
copyright is claimed, since that information is in git and tacking it by hand
would get out-of-hand very quickly.
> factor: Add/update copyright notices as necessary

- src/uu/factor/src/factor.rs
- src/uu/factor/src/numeric.rs
- src/uu/factor/src/rho.rs
I introduced the problematic codepath in commit 82410376 (#1525)
> factor: Fix very-rare bug in ρ

- tests/by-util/test_factor.rs
- includes additional RNG seed detail for any failures (for reproducibility) 
- probably fixes #1531 (via #1529) per @nbraud
> tests/factor ~ re-enable factor tests

- src/uu/factor/src/miller_rabin.rs
> factor::miller_rabin: Fix bug #1556

- src/uu/factor/src/miller_rabin.rs
computation is performed.
Will conflict with #1554, but the merge should be pretty trivial.
> factor::miller_rabin: Minor improvements

- Cargo.lock
- src/uu/factor/Cargo.toml
- src/uu/factor/benches/gcd.rs
- src/uu/factor/src/cli.rs
- src/uu/factor/src/numeric.rs
~50-65% faster (on the GCD computations themselves)
[criterion]: https://bheisler.github.io/criterion.rs/
> Speed up factor::numeric::gcd

- src/uu/factor/src/miller_rabin.rs
I just noticed it was missing  >_>'
> factor::miller_rabin: Add missing copyright header in source file

- tests/by-util/test_head.rs
This caused tests to fail on all unrelated work.
In particular, CI went red for all pull requests.
> head: Ignore known-failing tests introduced in #1579

- .github/workflows/CICD.yml
- src/uu/factor/src/numeric/mod.rs
- src/uu/factor/src/numeric/montgomery.rs
(See previous conversation, gives erroneous warnings due to rustc bugs)
> CI: Improve annotations

- src/uu/ls/src/ls.rs
This is trivial refactor.
```usize``` can call max method, so deleting user defined max function.
> ls: deleting user defined max function

- src/uu/stat/src/stat.rs
`cargo clippy` is complaining about using `Vec::sort_by(|a,b| b.cmp(a))` as a complicated closure (see [unnecessary_close_by](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_sort_by)). I'm not sure I agree, but this should be an equivalent construction which avoids the issue. [Benchmark comparison on StackOverflow](https://stackoverflow.com/a/60916195) shows no real difference in performance.
Alternatively, I can add a clippy allow exception for the offending line, but, of the two options, I'm inclined to this repair.
Thoughts/concerns?
> stat: fix `cargo clippy` complaint (unnecessary_sort_by)

- src/uu/factor/src/factor.rs
This set of changes is extracted from #1571.  Approx. 12% faster than `master`.
> factor: Refactor and optimise the `Factors` datastructure

- src/bin/coreutils.rs
- src/uu/expand/src/expand.rs
- src/uu/expr/src/tokens.rs
- src/uu/fmt/src/parasplit.rs
- src/uu/hashsum/src/hashsum.rs
- src/uu/od/src/parse_formats.rs
- src/uu/printf/src/tokenize/sub.rs
- src/uu/rm/src/rm.rs
- src/uu/shred/src/shred.rs
- src/uu/unexpand/src/unexpand.rs
This PR fixes new warnings due to updated rust/clippy version(s).
> Fix `cargo clippy` warnings

- tests/by-util/test_cp.rs
- track repair progress at uutils/coreutils#1590
> tests/cp ~ disable intermittent failures on MacOS (includes FixME comments)

- src/uu/sort/src/sort.rs
- tests/by-util/test_sort.rs
If the output of sort is piped to another program that closes the file
descriptor, sort currently panics. The GNU coreutils is able to handle
this case.
Replacing panic with crash_if_err reports the closed pipe and exits
with a return code, which seems like the correct behavior. Tested on
my Mac and the panic disappears.
> sort: fix panic on write to closed pipe

- .github/workflows/CICD.yml
I don't see any way around requiring that *Cargo.lock* be in a format that MinSRV can decipher.
This adds a step to the MinSRV build which specifically checks for *Cargo.lock* compatibility. If/when an incompatible *Cargo.lock* file is found, an error message is generated which suggests the correct fix for the problem (for example, see [build run #324516614](https://github.com/rivy/rs.coreutils/actions/runs/324516614)).
> maint/CICD ~ add 'Cargo.lock' format testing and protection

- src/uu/install/src/install.rs
- tests/by-util/test_install.rs
GNU:
```
$ install -d foo
$ install -d foo
```
Rust:
```
$ install -d foo
$ install -d foo
install: cannot create directory 'foo': File exists
install: foo: File exists (os error 17)
```
> bug(install) - install -d can be run on an existing directory

- src/uu/cp/src/cp.rs
- tests/by-util/test_cp.rs
Real life test case:
```
set -e
rm -rf dir dir-copy-archive-rust
mkdir dir
echo "a" > dir/1
echo "b" > dir/2
touch -d "2 hours ago" dir/1
chmod 705 dir/*
cd dir
ln -s 1 1.link
ln -s 2 2.link
cd -
cp --archive dir dir-copy-archive
ls -al dir-copy-archive|grep "rwx---r-x"
ls -al dir-copy-archive|grep "1.link -> 1"
./target/debug/coreutils cp --archive -v dir dir-copy-archive-rust
ls -al dir-copy-archive-rust|grep "rwx---r-x"
ls -al dir-copy-archive-rust|grep "1.link -> 1"
ls -al dir-copy-archive-rust|grep "2.link -> 2"
```
> feature(cp): implement archive & -L

- src/uu/ls/src/ls.rs
- tests/by-util/test_ls.rs
When a file doesn't exist, exit early and fails ls
Currently, running
```
$ ls doesntexist
```
will return 0
while it should return 1
Ditto for
```
$ ls doesntexist a
```
> ls - improve the error management + add tests

- src/uu/base32/src/base_common.rs
- src/uu/base64/src/base_common.rs
For inputs that are valid base64 but that encode non-utf8 strings (like
garbage), base64 panicks when trying to unwrap the result from
String::from_utf8().
Instead of interpreting the byte stream as utf8, simply dump the raw
bytes to stdout.
Since the test assert that all io is valid utf8, this does not come with
a unit test. See run() in tests/common/utils.rs.
Eg.
"gD63hSj3ScS+wuOeGrubXlq35N1c5Lby/S+T7MNTjxo=" -> ">(Iľ^Z\/S"
> base32/base64: tolerate non-utf8 encoded inputs

- src/uu/cp/src/cp.rs
- src/uu/tee/src/tee.rs
- tests/by-util/test_cp.rs
- tests/by-util/test_ls.rs
Simple example:
```
touch bar
rm -rf /tmp/foo
mkdir -p /tmp/foo
cp -pnL -v bar /tmp/foo
echo $?
cp -pnL -v bar /tmp/foo
echo $?
rm -rf /tmp/foo
mkdir -p /tmp/foo
./target/debug/coreutils cp -pnL -v bar /tmp/foo
echo $?
./target/debug/coreutils cp -pnL bar /tmp/foo
echo $?
```
> bug(cp): like gnu/cp, don't show any message when --no-clobber is used

- src/uu/install/src/install.rs
- src/uucore/src/lib/features/mode.rs
- tests/by-util/test_install.rs
The parse_numeric was getting ' 0333' as input
and showing 'mode is too large ( 0333 > 7777)' as error
Syntax used: https://sources.debian.org/src/firebird3.0/3.0.7.33374.ds4-1/debian/functions.sh/?hl=145#L145
> fix(install) - Install was failing with '-m 0333'

- src/uu/seq/src/seq.rs
- tests/by-util/test_seq.rs
Was failing with
```
Found argument '-1' which wasn't expected, or isn't valid in this context
```
otherwise
> bug(seq) - Allow 'seq 6 -1 0'

- src/uu/ls/src/ls.rs
- tests/by-util/test_ls.rs
This little check, allows us to hide the files that
shouldn't be shown on the listing on Windows operating
systems.
Just like the "dot" in UNIX based operating systems
Windows uses its own file attributes to determine if a file
is hidden or not.
The lack of support for this option is normally an annoyance
for many users, this commit adds full support for this feature.
Here is a little example of this issue:
Before the patch: 
As you may see, there are some files named: 
`NTUSER.DAT{fa492542-3fc7-11eb-9272-e44a63569703}.TM.blf`, etc
That are supposed to be hidden under the NTFS filesystem, after the patch:
As you can see, the files are now properly hidden, allowing for a much cleaner user experience, that fits right into the operating system.
This annoyance is pretty normal, among Windows …
> ls: On Windows don't display files hidden by NTFS

- src/uu/rm/src/rm.rs
This matches the behavior of GNU rm.
Fixes #1663.
> rm: allow "-f" to be specified multiple times

- Cargo.lock
- src/uu/csplit/Cargo.toml
- src/uu/csplit/src/csplit.rs
- src/uu/csplit/src/csplit_error.rs
- src/uucore/Cargo.toml
- src/uucore/src/lib/features/encoding.rs
- src/uucore/src/lib/lib.rs
Failure isn't maintained anymore:
https://github.com/rust-lang-nursery/failure/pull/347
https://rustsec.org/advisories/RUSTSEC-2020-0036.html
> Replaces "failure" by "thiserror"

- src/uu/factor/src/numeric/gcd.rs
Should be clearer; does not handle the `gcd(0, 0)` case, which is already covered by the `zero` test.
> factor::numeric::gcd: Refactor `divisor` test

- .github/workflows/GNU.yml
This fixes the last review comments from #1699
> Cleanup gnu test script

- README.md
There's a duplicate 'stty' in the progress table in the README.
> Delete duplicate stty from README table

- src/uu/wc/src/wc.rs
- tests/by-util/test_wc.rs
uu_wc -L (count the number of characters in a line) is a GNU extension. I fixed the failing test case from the GNU test suite where the last line of the file does not end in a LF.
> Fixed wc -L no end of line LF bug

- src/uu/mktemp/src/mktemp.rs
- tests/by-util/test_mktemp.rs
Used by apt-key https://sources.debian.org/src/apt/2.1.20/cmdline/apt-key.in/?hl=76#L76
> fix(mktemp) - Make mktemp --tempdir foo.XXXXXX works

- src/uu/numfmt/Cargo.toml
- src/uu/numfmt/src/numfmt.rs
Hi! This small contribution converts argument parsing in the numfmt utility from getopts to clap.
The test suite passes and clippy and rustfmt are happy.
Please let me know if I can improve this PR.
Thanks!
> numfmt: replace getopts with clap

- src/uu/ls/src/ls.rs
Previously if no --color argument was input, we would always print
colors in the output. This breaks `configure` scripts which run `ls`
and then compare the output against what they expect to see, since the
left side has ANSI escape sequences and the right side doesn't.
Instead, only print escape sequences if a TTY is present, or if
`--color=always` is specified.
Fixes #1638.
> ls: only print colors if stdout is a tty

- .github/workflows/GNU.yml
Not really interesting for us and logs are too big
> GNU testsuite: Remove tests checking for --version & --help

- src/uu/numfmt/src/numfmt.rs
- tests/by-util/test_numfmt.rs
Align with GNU numfmt by trimming leading whitespace from supplied values.
If the user did not specify a padding, calculate an implied padding from
the leading whitespace and the value.
Also track closer to GNU numfmt’s error message format.
> numfmt: handle leading whitespace & implied padding

- src/uu/numfmt/src/numfmt.rs
- tests/by-util/test_numfmt.rs
Adjust header option handling to prohibit passing a value of 0 to align
with GNU numfmt. Also report header option parse errors as GNU does.
closes #1708
> numfmt: prohibit --header=0 to align with GNU

- src/uu/yes/src/yes.rs
Improve readability by fixing an inadvertent rename during a performance
enhancement (b46e228).
> yes: correct a typo

- src/uu/od/src/partialreader.rs
This should fix the issue for the specific case of unsoundness mentioned in #1729.  Note that there are still uses of `Vec::set_len()` elsewhere (including another in `od`), but I am not planning to remove them until I get an answer to my question in that issue, as removing `Vec::set_len()` in those places will require somewhat more intense refactoring (unless we decide to eat the hit of pointlessly initializing the `Vec`s combined with allocation).
> od: remove potential unsoundness and an allocation in PartialReader

- src/uucore/src/lib/features/utmpx.rs
From what I can tell (the man page is not very useful here), `utmpxname()` uses `strdup()` to copy the string, so it's fine that it is freed afterwards.
> uucore: fix potential use-after-free in utmpx iterator

- Cargo.lock
- src/uu/factor/Cargo.toml
- src/uu/stdbuf/src/libstdbuf/Cargo.toml
- src/uu/timeout/Cargo.toml
- src/uu/uname/Cargo.toml
- src/uu/uptime/Cargo.toml
- src/uu/uptime/src/uptime.rs
I have begun to update our dependencies,  The most important update is probably `factor`, since there was a security issue in versions of `smallvec` before 0.6.14 (although I'm not sure it actually affects our code).
You can merge this now (in which case I'll submit more PRs like this) or just wait a few days for me to update everything.
> factor, stdbuf, timeout, uname, uptime: update dependencies

- src/uucore/src/lib/features/process.rs
- tests/by-util/test_timeout.rs
- tests/common/util.rs
This should resolve #1742.  I've basically switched from using `libc` to Rust's standard library, which dramatically simplifies the code and makes it more portable at the expense of potentially waiting longer for a program to exit before returning its exit status.
> uucore: process: fix exit status processing

- src/uu/shred/src/shred.rs
This PR removes usage of `Vec::set_len()` (#1729).  It also avoids allocating a new `Vec` every time `BytesGenerator` iterates, so it is most likely actually faster than before.  Note that there is still quite a bit of room for improvement in terms of performance ~(_e.g._ copying entire patterns rather than pushing them to the `Vec` one byte at a time)~ and readability.
There is at least one more instance of `Vec::set_len()` that needs to be fixed (it's in `od` again).  We may want to simply review our usage of `unsafe` in general, as I imagine some of the cruft that's built up over the years can be removed.
> shred: remove usage of Vec::set_len()

- src/uu/od/src/inputdecoder.rs
This removes the last usage of `Vec::set_len()` with undefined behavior (AFAIK).  Zero-initializing the `Vec` isn't much of an issue here as it is only created once (over the course of the entire program) and the actual amount of allocated memory should be rather small (usually at least).
See #1729 for more info on the undefined behavior.
> od: remove Vec::set_len() usage in InputDecoder

- src/uu/mktemp/src/mktemp.rs
- tests/by-util/test_ls.rs
Fixed the first failure in https://github.com/uutils/coreutils/issues/1747 is due to the truncate command not existing in powershell.
Also changed the default 'mktemp' template to the windows filename convention of XXXXXXX.tmp.
> muted test not for windows and added windows temp file convention

- src/uu/cut/src/cut.rs
- src/uu/numfmt/src/numfmt.rs
- src/uucore/src/lib/lib.rs
- src/uucore/src/lib/mods.rs
- src/uucore/src/lib/mods/ranges.rs
- tests/by-util/test_numfmt.rs
- tests/fixtures/numfmt/df_expected.txt
- tests/fixtures/numfmt/df_input.txt
Add field selection to `numfmt`, allowing the user to select an alternate field to format, a list of alternate fields, a range of fields, or any combination of individual fields and ranges.
This PR takes a different approach from the earlier PR (#1454): the range support in `cut` was already nicely factored out of the main implementation, so this PR relocates `cut`'s range handling to `uucore` and reuses it for `numfmt`.
> numfmt: implement --field

- src/uu/cp/src/cp.rs
- tests/by-util/test_cp.rs
Adds support for the `--strip-trailing-slashes` flag for `cp` (#1761).
I've based the implementation on the `--strip-trailing-slashes` flag for `mv`, which [uses `.components().as_path()`](https://github.com/uutils/coreutils/blob/2dcc60d624b672c6100e28808fb6ac20e391a0b7/src/uu/mv/src/mv.rs#L200) to perform the normalization.
> cp: implement --strip-trailing-slashes

- src/uu/chown/src/chown.rs
- src/uu/stat/src/stat.rs
- src/uu/sync/src/sync.rs
- src/uu/tail/src/tail.rs
- src/uu/touch/src/touch.rs
- src/uu/truncate/src/truncate.rs
- src/uu/uname/src/uname.rs
- src/uu/uniq/src/uniq.rs
- src/uu/uptime/src/uptime.rs
- src/uu/wc/src/wc.rs
Group `OPT_SOME_CLI_OPTION` into `options::SOME_CLI_OPTION`
This pull request does not intend to end all re-ordering of options, but rather establish a norm to follow in all tools/commands.
I'm grouping several related options into sub-mods. They can be improved by pointing them out here, in this PR, or later in the future
> Group OPT_ARGUMENTS into mods

- src/uu/uniq/src/uniq.rs
Resolved #550 
Replaced the basic, ascii-only uppercase implementation with the inbuilt `to_uppercase`.
The PR is minimal, all tests pass, and no warnings were added.
> uniq: fixed #550

- src/uu/paste/src/paste.rs
- tests/by-util/test_paste.rs
- added `-` as the default input, since `paste` reads stdin if no file
is provided
- `paste` also supports providing `-` multiple times
- added a test for it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uutils/coreutils/1791)
> paste: support multi-stdin

- src/uu/ptx/src/ptx.rs
- tests/by-util/test_ptx.rs
- tests/fixtures/ptx/gnu_ext_disabled_roff_no_ref_word_regexp_exc_space.expected
GNU manpages for the `-W` option say. "An empty regexp is equivalent to not using this option."
Here's a patch that implements that. If somebody does #1753 they will likely need to know about this PR.
> ptx: ignore empty regex

- src/uu/touch/src/touch.rs
- tests/by-util/test_touch.rs
There are three mutually exclusive arguments in `touch` to specify the time that should be set: `time`, `date` and `current`. This PR removes the manual check that ensures that only one of these is present in favor of using a `clap::ArgGroup`. I have also added tests for the cases where multiple of these arguments are passed.
Finally, there were the macros `to_local!` and `local_tm_to_filetime` that I turned into functions.
> touch: use an ArgGroup for sources and turn macros into functions

- src/uu/sleep/Cargo.toml
- src/uu/sleep/src/sleep.rs
- tests/by-util/test_sleep.rs
Fixes #1735.
This request replaces getopts with clap for the sleep binary.
It does not introduce tests.
> sleep: move from getopts to clap #1735

- .github/workflows/CICD.yml
- GNUmakefile
- src/bin/coreutils.rs
The binary was rename from uutils to coreutils in that commit
52ae491fcdd2cd9bd56fb56fae8270c399654dcd
but the makefile to run the busybox test wasn't updated
This commit update the makefile to use the correct binary name.
It also updates the busybox to the 1.32.1 version and fix the makefile
to run all the busybox tests instead of stopping after the first failed exe
This also change the main binary usage to match busybox. This allow to run the new busybox tests.
New busybox tests use an exact match on the usage string to find the list of defined functions. So without that change we had a `SKIPPED: cp (not built)` issue
> Fix `make busytest`

- .travis.yml
Follow-up to #1724 where the minimum Rust version was bumped to v1.33.0
I'm not too sure this is wanted, but I'll leave it here
> travis: bump rust to 1.33.0

- src/uu/uniq/src/uniq.rs
- tests/by-util/test_uniq.rs
- tests/fixtures/uniq/not-utf8-sequence.txt
- tests/fixtures/uniq/skip-2-fields.expected
- tests/fixtures/uniq/skip-fields.txt
This fixes 2 issues I found with handling of utf-8 input in `uniq`:
- Invalid utf-8 sequence in input was causing panics
- Multi-byte code points were handled incorrectly in `skip_fields` causing incorrect results or panics in some cases.
> uniq: utf-8 issues

- src/uu/factor/src/factor.rs
> factor::tests: Check that powers of known-factorization numbers are factored correctly

- src/uu/numfmt/src/format.rs
- src/uu/numfmt/src/numfmt.rs
- src/uu/numfmt/src/options.rs
- src/uu/numfmt/src/units.rs
- tests/by-util/test_numfmt.rs
Split the implementation of `numfmt` into separate modules holding the defined options, unit constants and types, formatting implementation, and program entry and argument parsing.
Add the `--delimiter` option allowing the user to choose a delimiter character to override the default behavior of splitting input lines on whitespace.
closes #1454
> numfmt: implement --delimiter

- src/uu/rm/src/rm.rs
- tests/by-util/test_rm.rs
make clap support -R in addition to -r
> rm: add an additional flag -R for --recursive 

- src/uu/expand/Cargo.toml
- src/uu/expand/src/expand.rs
- tests/by-util/test_expand.rs
expand has one odd behavior that allows two format for tabstop
From expand --help
```
-t, --tabs=N     have tabs N characters apart, not 8
-t, --tabs=LIST  use comma separated list of tab positions
```
This patch use one `value_name("N, LIST")` for tabstop and
deal with above behavior in `parse_tabstop`.
Close #1795
> expand: replace getopts with clap

- Cargo.lock
- src/uu/more/Cargo.toml
- src/uu/more/src/more.rs
Needed for iOS compatibility, as newer `nix` versions are fully iOS-compatible.
Goes with https://github.com/uutils/coreutils/pull/1836 for iOS support
> Update nix to 0.13 in uu_more

- src/uu/ls/src/ls.rs
- tests/by-util/test_ls.rs
There was a mistake that `--human-readable` and `-h` used decimal prefixes (kilo, mega, etc.) instead of binary prefixes (kibi, mebi, etc.). So `--si` was added for decimal prefixes.
Second, there are a few peculiarities with how GNU `ls` formats the sizes:
1. They only show a single decimal place if the size is less than 10. Previous behaviour was to always include two decimal places.
2. Sizes are always rounded up. Previous behaviour was to do normal rounding.
3. They never show the "B" for bytes, e.g. they show `K` instead of `KB`.
3. There is no `i` for prefixes such as  `Ki` and `Mi`.
4. The prefix for kibi is `K`, while the prefix for kilo is `k`.
Below are some examples of this behaviour (from GNU ls) with some annotations. I've used the same file sizes for the tests.
```
$ ls -lh …
```
> ls: --si flag and more compatible size formatting

- tests/by-util/test_date.rs
Follow on from PR #1798 to put in tests for different date formats that are not handled yet.
> date: add more tests for setting (alt. formats)

- src/uu/factor/src/factor.rs
- src/uu/factor/src/table.rs
It was a draft PR, not ready for merging, and its premature inclusion caused repeated issues, see 368f47381b7441ddb23bb7460417e0d1ce33e330 & friends.
This reverts commits 3743a3e1e7a87bdd0ea7b923dc42386bfc14ccd5, ce218e01b6fcfadf4a9e55348d98f36dafff6c6b, and b7b0c76b8ea60297b43777d17d7322d1d45a9e91.
Close #1841.
> Revert #1571 “perf/factor ~ deduplicate divisors”

- src/uu/install/src/install.rs
- tests/by-util/test_install.rs
TIL path manipulation in rust is intentionally basic due to [security concerns](https://github.com/rust-lang/rust/issues/16507#issuecomment-73804876).
fixes #1823
> install: fix bug #1823

- src/uu/ls/src/ls.rs
- tests/by-util/test_ls.rs
This PR adds the options to customize what information is shown in long format regarding author, group & owner. Specifically it adds:
- `--author`: shows the author, which is always the same as the owner. GNU has this feature because GNU/Hurd supports a difference between author and owner, but I don't think Rust supports GNU/Hurd, so I just used the owner.
- `-G` & `--no-group`: hide the group information.
- `-o`: hide the group and use long format (equivalent to `-lG`).
- `-g`: hide the owner and use long format.
The `-o` and `-g` options have some interesting behaviour that I had to account for. Some examples:
- `-og` hides both group and owner.
- `-ol` still hides the group. Same behaviour with variations such as `-o --format=long`, `-gl`, `-g --format=long` and `-ogl`.
- They even …
> ls: long format author, group and owner

- src/uucore/src/lib/macros.rs
- tests/by-util/test_pathchk.rs
- tests/common/macros.rs
- tests/common/util.rs
resolves #1132 
- removed repeat_str helper as it's now part of std
- added docstrings for usual macros and test utils
- added `allow(dead_code)` in tests/utils.rs to reduce warnings when testing individual utilities
I've stated repeatedly that some macros/methods treat paths as relative to a unique test directory, since some tests seem to have been written with the assumption that the test directory was shared across tests.
> documentation for usual macros

- src/uu/expr/src/syntax_tree.rs
fix several clippy warnings on `expr/syntax_tree.rs` (fixes: https://github.com/uutils/coreutils/issues/1868)
Clippy was complaining about `Result<String, String>` which is pretty understandable because they were only returning `Ok(String)`, this changes updates them and uses `Ok(fn() ->String)` instead.
> fix(expr): fix clippy warnings

- src/uu/nohup/Cargo.toml
- src/uu/nohup/src/nohup.rs
- tests/by-util/test_nohup.rs
resolves #1856
- changed error return codes from 2 to 125
- changed warning/error messages to match GNU nohup
- replaced getopts dependency with clap
- added a test
> nohup: move from getopts to clap

- src/uu/echo/src/echo.rs
- tests/by-util/test_echo.rs
This is a two line change, but it fixes: https://github.com/uutils/coreutils/issues/1873 by allowing the leading hyphens and trailing var arg.
> echo: allow leading hyphens  

- src/uu/mv/src/mv.rs
Previously this used `print` instead of `println`, and as a result the
prompt would never appear and the command would hang. The Rust docs
note this about print:
> Note that stdout is frequently line-buffered by default so it may be
> necessary to use io::stdout().flush() to ensure the output is emitted
> immediately.
Changing to `println` fixes the issue.
Fixes #1889.
> mv: ensure line prints

- tests/by-util/test_date.rs
Fixes issue #1882 .
Although these tests contain valid dates, the parsing logic is not implemented yet. It should be changed to expect success when the parsing logic is done.
> date: change tests to expect failure

- src/uu/ptx/Cargo.toml
- src/uu/ptx/src/ptx.rs
resolves: https://github.com/uutils/coreutils/issues/1753
While porting to clap, i found some flags like `-S --sentence-regexp``-b --break-file` - (https://github.com/uutils/coreutils/issues/1763), and GNU extensions are not implemented yet, maybe we can create issue for them :)
This PR is also going to require some rebasing for https://github.com/uutils/coreutils/pull/1602
> ptx: move from getopts to clap

- src/uu/cp/src/cp.rs
Replaced "they if" with "if they" in the comments above the "prompt_yes" macro.
> Cleanup: Fix grammar in "cp" macro comments.

- src/uu/ls/src/ls.rs
- src/uu/ls/src/version_cmp.rs
- tests/by-util/test_ls.rs
Implements version sort (`-v` and `--sort=version`) for `ls`. My approach is different from the one used in `sort`, because that one did not seem entirely consistent with what the GNU docs say. The approach here is two compare the characters one by one, but when two numeric characters are found, to collect the rest of the number and compare the parsed strings. There is also some additional complexity due to the fact that GNU ls sorts identical numbers based on the first differing number of leading zeros.
> ls: version sort

- src/uu/tail/src/tail.rs
- src/uucore_procs/src/lib.rs
New in Rust 1.51.
Closes #1914
> Fix "panic message is not a string literal" warnings

- tests/by-util/test_tee.rs
These tests are ported from `https://github.com/coreutils/coreutils/tests/misc/tee.sh`.
Issue #1793 asked to add tests for tee.
There are tests in `tee.sh` that I could not port over because I don't know how to handle `timeouts` and `dd` in tests.
These are the tests I managed to port over:
- processing_multiple_operands
- treat_minus_as_filename
- append
- no_more_writeable_stdout
- no_more_writeable_stdin
The last two tests fail because rust's tee stdout/stderr differ from GNU's tee stdout/stderr if either of them is `/dev/full`.
I will open an issue for this at #1805
> tests/tee: implemented tests for tee

- Cargo.lock
- Cargo.toml
- src/uu/install/Cargo.toml
- src/uu/install/src/install.rs
- tests/by-util/test_install.rs
GNU coreutils [1] checks the following: whether
- either file is nonexistent,
- there's a sticky bit or set[ug]id bit in play,
- either file isn't a regular file,
- the sizes of both files mismatch,
- the destination file's owner differs from intended, or
- the contents of both files mismatch.
[1] https://git.savannah.gnu.org/cgit/coreutils.git/tree/src/install.c?h=v8.32#n174
----
This is the first non-exercise thing I've written in Rust, so don't hesitate to point out anything unidiomatic.
Closes #1756.
> install: implement `-C` / `--compare`

- Cargo.lock
```
Updating memoffset v0.6.1 -> v0.6.2
Updating syn v1.0.64 -> v1.0.65
```
> refresh cargo.lock with recent updates

- Cargo.lock
- src/uu/ptx/Cargo.toml
I forgot to delete it in https://github.com/uutils/coreutils/pull/1893, thanks for the reminder @sylvestre .)
> ptx: delete getopts dependency

- src/uu/cksum/Cargo.toml
- src/uu/cksum/src/cksum.rs
While adding tests to cksum, i found cksum wasn't using clap, there is a very small need for clap in cksum (it is very small) but it is great for general consistency.
> cksum: use clap for argument management

- Cargo.lock
- src/uu/mkfifo/Cargo.toml
- src/uu/mkfifo/src/mkfifo.rs
- tests/by-util/test_mkfifo.rs
This PR includes these changes for mkfifo (resolves https://github.com/uutils/coreutils/issues/1928) : 
* Made a general refactor
* Moved from getopts to clap
* Added tests
> mkfifo: general refactor, move to clap, add tests

- src/uu/tee/Cargo.toml
- src/uu/tee/src/tee.rs
- tests/by-util/test_tee.rs
+ aligned 'tee' output with GNU tee when one of the files is '/dev/full'
+ don't stop tee when one of the outputs fails; just continue and return
error status from tee in the end
Testing:
```
tee: 'standard output': No space left on device (os error 28)
1
```
```
1
2
3
tee: /dev/full: No space left on device (os error 28)
```
> tee: should match GNU's output if used with /dev/full

- tests/by-util/test_install.rs
To ensure timestamps don't match. Fixes #1927.
> test_install: Add sleeps

- src/uu/tty/Cargo.toml
- src/uu/tty/src/tty.rs
- tests/by-util/test_tty.rs
I replaced getopts with clap for tty.
I also added some tests, but I wasn't able to write a succeeding one.
I'm not sure, if all tests run on all operating systems. Maybe some `#[cfg(not(windows))]` have to be added.
Fixes #1935.
> tty: Move from getopts to clap

- Cargo.lock
- src/uu/sum/Cargo.toml
- src/uu/sum/src/sum.rs
- tests/by-util/test_sum.rs
This PR includes these changes for sum:
* Fixed unnecesarry crashes for invalid inputs
* When an error occurs GNU sum writes the error on stderr and moves on, our existing implementation was crashing the whole app. 
* Moved to clap from getopts
* Added tests for invalid inputs
Resolves: https://github.com/uutils/coreutils/issues/1932
> sum: fix crash on invalid inputs, move to clap, add tests

- src/uu/cksum/src/cksum.rs
addition to: https://github.com/uutils/coreutils/pull/1923 
https://github.com/uutils/coreutils/pull/1923 kept failing for freebsd, there was no precheck for file metadata before  this pr addresses that.
> fix(cksum): check metadata of the path 

- tests/by-util/test_wc.rs
- tests/common/util.rs
This PR adds a bunch of useful functions & byte/string getters for the CmdResult struct.
It also adds methods to rw+ items in an `AtPath`.
Now, we need to refactor tests to use this API (together with `stdout_is` for example instead of manual asserts, and `succeeds` instead of `assert!(result.success)`. Once that is done, we can 
1. Change the type of `stderr`/`stdout` in `CmdResult` to `Vec<u8>` 
2. Make the fields private (to avoid this whole mess in the future)
3. Finally be able to test our utils for non-utf8 reliance! Will close #1916
> Expand `CmdResult`'s API 

- src/uu/echo/src/echo.rs
Changed from static to const.
Added alternative usage, see GNU echo.
Do not allow short options for --version and --help, compare also to GNU echo.
Added tests for the above.
> echo: Some minor changes to options

- tests/by-util/test_od.rs
part of the ongoing effort in #1982
The tests are still the same but don't access the fields of `CmdResult`
> od: refactor tests for #1982

- src/uu/du/src/du.rs
- tests/by-util/test_du.rs
> Consistency with GNU version of `du` when doing `du -h` on an empty file

- src/uu/fold/src/fold.rs
- tests/by-util/test_fold.rs
Update `fold` to preserve blank lines in the input stream as GNU does:
```
$ echo -ne '0\n1\n\n2\n\n\n-----' | fold
0
1
2
-----
```
> fold: preserve blank lines

- src/uu/install/src/install.rs
- tests/by-util/test_install.rs
The '-d' flag should create all ancestors (or components) of a directory regardless of the presence of the "-D" flag.
From the man page:
```
-d, --directory
treat all arguments as directory names; create **all components** of the specified directories
```
With GNU:
```
$ install -v -d dir1/di2
install: creating directory 'dir1'
install: creating directory 'dir1/di2'
```
With this version:
```
$ ./target/release/install -v -d dir3/di4
install: dir3/di4: No such file or directory (os error 2)
install: dir3/di4: chmod failed with error No such file or directory (os error 2)
install: created directory 'dir3/di4'
```
This PR also adds a few more fixes:
- Uses the correct wording for the log message to match GNU install.
- Don't display success message when a directory was not actually created. …
> install: Fix behaviour of the '-d' flag

- src/uu/csplit/Cargo.toml
- src/uu/csplit/src/csplit.rs
**with clap**
```bash
csplit 0.0.4
split a file into sections determined by context lines
USAGE:
[OPTION]... FILE PATTERN...
FLAGS:
-z, --elide-empty-files    remove empty output files
-h, --help                 Prints help information
-k, --keep-files           do not remove output files on errors
--quiet                same as --silent
-s, --silent               do not print counts of output file sizes
--suppress-matched     suppress the lines matching PATTERN
-V, --version              Prints version information
OPTIONS:
-n, --digits <DIGITS>           use specified number of digits instead of 2
-f, --prefix <PREFIX>           use PREFIX instead of 'xx'
-b, --suffix-format <FORMAT>    use sprintf FORMAT instead of %02d
Output pieces of FILE separated by PATTERN(s) to files 'xx00', …
```
> csplit: move from getopts to clap

- GNUmakefile
I noticed while debugging the nix package that the makefile is out of date.
> makefile: replace all uutils with coreutils

- Cargo.lock
- src/uu/dirname/Cargo.toml
- src/uu/dirname/src/dirname.rs
This PR includes these changes for dirname: 
* moved to clap
* fixed writing to stdout instead of stderr in missing operand
> dirname: move to clap, write to stderr on errors 

- Cargo.lock
- src/uu/cut/Cargo.toml
- src/uu/cut/src/cut.rs
- src/uu/stdbuf/src/stdbuf.rs
- tests/by-util/test_cut.rs
This PR includes these changes for cut:
* Moved to clap
* Added GNU coreutils compatible error messages.
> cut: move to clap, add gnu like error messages + tests

- src/uu/ls/src/ls.rs
- src/uu/ls/src/quoting_style.rs
- tests/by-util/test_ls.rs
Implements the flags:
- `-q` & `--hide-control-chars`
- `--show-control-chars`
The former is now the default and replaces any control character with a `?`, the second just shows them as is.
One thing I couldn't figure out was this line from the GNU docs for the `-q` flag:
> This is the default if the output is a terminal and the program is `ls`.
In what circumstances would the program not be `ls` and how could we perform the same check? If anyone knows how to do this, please let me know and I'll update the PR, otherwise I'll make an issue about this.
> ls: show/hide control chars

- .cirrus.yml
- .github/workflows/CICD.yml
- .travis.yml
- README.md
Before this change we never ran tests on uucore itself
meaning that is was not possible to test
functions of the shared core, only their usage
in the different binaries
This change adds running uucore to our ci, which will increase coverage for the few doctests that exist
and is extracted from #1988 where first tests for uucore will be introduced
> uucore: Start testing uucore

- Cargo.lock
- src/uu/ls/Cargo.toml
- src/uu/ls/src/ls.rs
- tests/by-util/test_ls.rs
Implements `--ignore` and `--hide`, which both hide files matching a shell paths, except that `--hide` does not work when `-A` or `-a` is used. The options can also be used multiple times to specifiy multiple patterns. I've also refactored the `--ignore-backups` options  to be essentially a shorthand for `--ignore='*~' --ignore='.*~'`.
GNU does not show any errors or warnings for invalid patterns, but I thought it might be nice to at least show a warning.
> ls: --hide and --ignore

- tests/by-util/test_realpath.rs
- tests/by-util/test_rm.rs
- tests/by-util/test_tee.rs
part of the ongoing effort in #1982
The tests are still the same but don't access the fields of CmdResult
* I omitted extra `println` since it's [planned](https://github.com/uutils/coreutils/issues/1982#issuecomment-811808890) to do these automatically.
* I renamed some tests to be coherent with the naming scheme.
* I changed `run` to `succeeds` since that's [recommended](https://github.com/uutils/coreutils/blob/9bb588d69ad8a230cfcbd267e8a276ca88e442f2/tests/common/util.rs#L741)
> Some more test refactors for #1982

- src/uu/ls/src/ls.rs
Small correction to my previous PR (https://github.com/uutils/coreutils/pull/2026), where I missed the short option `-I` for `--ignore`.
> ls: add short option for ignore

- src/uu/od/src/inputdecoder.rs
- src/uucore/src/lib/macros.rs
`macros.rs` used a `String` where in the future a string literal will be expected.
`inputdecoder.rs`'s tests matched on a `Result` and asserted `false` on error.
iirc the second argument also needs to be a string, but I've just turned the whole thing into an unwrap.
> Fixed panic!/assert! used with improper format strings

- tests/by-util/test_relpath.rs
part of the ongoing effort in #1982
The tests are still the same but don't access the fields of CmdResult
> relpath: refactor tests for #1982

- src/uu/fold/src/fold.rs
- tests/by-util/test_fold.rs
GNU `fold` does not remove characters from the input stream:
```
$ echo -ne 'x\b' | fold | xxd
00000000: 7808                                     x.
$ echo -ne 'x\ry' | fold | xxd
00000000: 780d 79                                  x.y
```
Backspaces and carriage returns are preserved, but simply change the column counters for folding. Here is an example where a backspace decreases the column count by 1
```
$ echo -ne 'foobar\b6789abcdef' | fold -w10 -s
fooba6789a
bcdef
```
so the input for folding purposes is `fooba6789abcdef` and `fold` inserts a newline after the character `a` in the tenth column; the `r\b` pair still appear in the output:
```
$ echo -ne 'foobar\b6789abcdef' | fold -w10 -s | xxd
00000000: 666f 6f62 6172 0836 3738 3961 0a62 6364  foobar.6789a.bcd
00000010: 6566 …
```
> Fold backspace and carriage return

- Cargo.lock
- src/uu/du/Cargo.toml
- src/uu/du/src/du.rs
- tests/by-util/test_du.rs
I also noticed that times are being miscalculated on linux, so I fixed that.
Fixes #2042 and fixes #2043.
> Replace outdated time 0.1 dependancy with latest version of chrono

- tests/by-util/test_ls.rs
- tests/common/util.rs
Part of https://github.com/uutils/coreutils/issues/1982
I've refactored the tests to no longer use the `stdout`, `stderr` and `success` fields on `CmdResult`. Additionally, I've improved the formatting of some docstrings in `tests/common/util.rs` and fixed a docstring that claimed that the function trimmed trailing whitespace, but it didn't.
> ls: refactor tests

- Cargo.lock
- src/uu/fold/src/fold.rs
- src/uu/stdbuf/src/stdbuf.rs
- src/uu/timeout/Cargo.toml
- src/uu/timeout/src/timeout.rs
Changed from optparse to clap.
None of the logic within timeout has been changed, which could use some
refactoring,
Closes Issue: https://github.com/uutils/coreutils/issues/1934
> timeout: Moved argument parsing to clap

- Cargo.lock
- src/uu/stdbuf/Cargo.toml
- src/uu/stdbuf/src/stdbuf.rs
- tests/by-util/test_stdbuf.rs
I'm unsure about how closely the behavior of the GNU original should be mimicked when checking options:
* is it okay to just use claps default message in case no MODE option is set?
* when attempting line buffering stdin, stdbuf prints `Try 'stdbuf --help' for more information.` but not when an invalid mode is set. The current uutils implementations prints it in any case. Should this behavior be kept or should it behave like the GNU implementation?
And lastly, should I add integration tests or should this be done in a seperate issue?
closes #1930
> stdbuf: move from getopts to clap

- tests/by-util/test_cksum.rs
- tests/common/util.rs
* if we want to test an irregular scenario, ignoring errors caused by
writing to stdin of the command can be uselful.
* for example, when writing some text to stdin of cksum in a scenario
where it doesn't consume this input, the child process might have
exited before the text was written. therefore, this test sometimes
fails with a 'Broken pipe'.
> allow ignoring stdin write errors in tests & fix flaky test

- src/uu/du/src/du.rs
- src/uucore/src/lib/macros.rs
- tests/by-util/test_du.rs
Fixes #1770
* Created a new error macro which allows the customization of the
"error:" string part
* Match the du output based on the type of error encountered. Can extend
to handling other errors I guess.
I'm pretty new to rust, so interested in feedback on this. I did contemplate changing the signature of the `show_error` macro, but it seemed less complex to create a new macro allowing the customization of the `error:` string part. Also, I'm not wild about hardcoding the `Permission denied` string, but it seemed the simplest thing to do.
> du error output should match GNU

- tests/by-util/test_cksum.rs
- tests/by-util/test_cp.rs
- tests/by-util/test_install.rs
- tests/by-util/test_mktemp.rs
- tests/by-util/test_pinky.rs
- tests/by-util/test_shred.rs
- tests/by-util/test_stat.rs
- tests/by-util/test_tail.rs
- tests/common/util.rs
Note that previously `test_empty` didn't really check the stdout contents
Added `normalized_newlines_stdout_is` since it looks like something the tests avoid checking in all kind of creative ways.
Also made `code` a private field since it wasn't used anywhere
> Remove direct usage of CmdResult fields in tests (cksum, pinky, mktemp, shred, stat, tail)

- tests/by-util/test_cksum.rs
- tests/by-util/test_hostid.rs
- tests/by-util/test_hostname.rs
- tests/by-util/test_mktemp.rs
- tests/by-util/test_nproc.rs
- tests/by-util/test_pinky.rs
- tests/by-util/test_printenv.rs
- tests/by-util/test_readlink.rs
- tests/by-util/test_sort.rs
- tests/by-util/test_sync.rs
- tests/by-util/test_tsort.rs
- tests/by-util/test_uname.rs
- tests/by-util/test_uptime.rs
- tests/by-util/test_users.rs
After this, we have 83 more occurrences of usage of `.success`,  18 of `.stdout`, and 64 of `.stderr` (measured by removing `pub` from the fields).
This is excluding @jhscheer 's open PR which removes yet more.
Also ran cargo fmt and made sure to install it onto my local hooks.
Not sure why but it looks like cargo-fmt selectively formats or doesn't format certain files with different invocations.
Maybe due to feature flags.
> Refactored tests for more utilities

- tests/by-util/test_id.rs
- tests/by-util/test_whoami.rs
part of the ongoing effort in #1982
The tests are still the same but don't access the fields of CmdResult
* there were a lot of calls to `is_ci()` which I put in an extra function `skipping_test_is_okay()`
* cleaned up and updated exception handling for the `whoami`, `id` calls
* removed unnecessary calls to `println`
* removed unnecessary `String` conversions
> whoami/id: refactor tests for #1982

- src/uu/du/src/du.rs
- tests/by-util/test_du.rs
This closes #2066
* Fixed failing tests on some linux hosts by dynamically taking reference values from the system `du`.
If system `du` is not available, or host is not linux, this falls back to the existing hard coded reference values.
* Refactored tests to not access the fields of CmdResult #1982
> du: fix tests on linux (#2066)

- src/uu/cat/src/cat.rs
- src/uu/cat/src/splice.rs
- tests/by-util/test_cat.rs
- tests/common/util.rs
Currently, if the second call to splice fails, or if pipe creation fails, cat will not attempt to fall back to normal read/write. This was an oversight on my part. This PR fixes that.
> cat: Put splice code in separate file, handle more failures

- .github/workflows/GNU.yml
Remove the `printf` test that causes make to fail generating the test run statistics.
Fixes #1941
> Remove broken GNU test for printf

- src/uu/truncate/src/truncate.rs
- tests/by-util/test_truncate.rs
The GNU `truncate` allows spaces in the size argument, so you can have calls like
```
truncate --size '< 10'
```
> Allow space in truncate --size

- Cargo.lock
- src/uu/ls/Cargo.toml
- src/uu/ls/src/ls.rs
- tests/by-util/test_ls.rs
Previously, the colors in `ls` were restricted to Unix. This PR removes that restriction and uses the [`lscolors`](https://github.com/sharkdp/lscolors) crate instead of a custom implementation.
> ls: cross-platform colors

- src/uu/tac/src/tac.rs
- tests/by-util/test_chmod.rs
- tests/by-util/test_chroot.rs
- tests/by-util/test_cp.rs
- tests/by-util/test_date.rs
- tests/by-util/test_df.rs
- tests/by-util/test_du.rs
- tests/by-util/test_env.rs
- tests/by-util/test_fmt.rs
- tests/by-util/test_groups.rs
- tests/by-util/test_head.rs
- tests/by-util/test_install.rs
- tests/by-util/test_ln.rs
- tests/by-util/test_ls.rs
- tests/by-util/test_mkfifo.rs
- tests/by-util/test_more.rs
- tests/by-util/test_mv.rs
- tests/by-util/test_nice.rs
- tests/by-util/test_shuf.rs
- tests/by-util/test_stat.rs
- tests/by-util/test_tac.rs
- tests/by-util/test_tr.rs
- tests/by-util/test_tsort.rs
- tests/by-util/test_who.rs
- tests/common/util.rs
This closes #1982
* refactor last remaining tests to not access the fields of `CmdResult`
* set the remaining fields of `CmdResult` to private
* use of new test utils from #2011 where applicable, e.g. `stdout_matches` etc.
Some minor things
* replace some `at_and_ucmd` with `new_ucmd` if "at" is not needed
* fix a return value in `tac`
> refactor tests (#1982)

- src/uu/tail/src/tail.rs
- tests/by-util/test_tail.rs
Currently if you try to use the `--sleep-interval` option it will fail as the number is not taken as a value for the option. 
The test will ensure this issue doesn't regress, I wasn't sure about how to create a more detailed test to confirm the option is having the expected effect.
> tail --sleep-interval takes a value

- src/uu/sort/src/sort.rs
- tests/by-util/test_sort.rs
Trailing separators were included at the end of the last token, but they
should not be.
> sort: fix tokenization for trailing separators

- src/uu/cp/src/cp.rs
- tests/by-util/test_cp.rs
- Passing `never` to `--reflink` does not raise an error anymore.
- Remove `Options::reflink` flag as it was redundant with
`reflink_mode`.
- Add basic tests for this option.  Does not check that a copy-on-write
rather than a regular copy was made.
> cp: add support for --reflink=never

- src/uu/sort/src/sort.rs
- tests/by-util/test_sort.rs
GNU sort disallows these combinations, presumably because they are
likely not what the user really wants.
Ignoring characters would cause things to be put together that aren't
together in the input. For example, -dn would cause "0.12" or "0,12" to
be parsed as "12" which is highly unexpected and confusing.
> sort: disallow certain flags with -d and -i

- Cargo.lock
- Cargo.toml
- tests/common/util.rs
- All assert_eq in tests/common/util.rs now print a pretty diff on test
failures.
- {stdout, stderr}_is_fixture now compare the expected output and the
fixture as Strings, which leads to more usable diffs.
If we had flipped the order of two lines in `sort`, the assertion failure would have printed something like this:
After this change it displays like this:
This makes it much easier to spot the difference.
Added dev dependency: pretty_assertions
> tests: show pretty diffs for assertion failures

- src/uu/ls/src/ls.rs
For sorting by name, the key computation was becoming a non-trivial operation. Use sort_by_cached_key so gave a performance boost.
(tree is a linux kernel source tree)
**Before:**
```
Summary
'ls -R tree > /dev/null' ran
3.82 ± 0.61 times faster than 'target/release/ls -R tree > /dev/null'
Summary
'ls -al -R tree > /dev/null' ran
1.34 ± 0.11 times faster than 'target/release/ls -al -R tree > /dev/null'
```
**After:**
```
Summary
'ls -R tree > /dev/null' ran
2.32 ± 0.30 times faster than 'target/release/ls -R tree > /dev/null'
Summary
'ls -al -R tree > /dev/null' ran
1.14 ± 0.09 times faster than 'target/release/ls -al -R tree > /dev/null'
```
> ls: Use sort_by_cached_key

- src/uu/ls/src/ls.rs
Instead of writing directly to `stdout`, with `print!` and `println!`, we can write to a `BufWriter` to reduce `write` syscalls. Doing so leads to the following improvements:
* GNU is now 4.06 times faster instead of 4.31.
* Our time spent on syscalls is now on par with GNU instead of 60% longer.
* Number of `write` calls goes from 344064 to 1090 when running `ls -R` on the Firefox source code.
The full benchmarks are in the `details` tag below. Because `print!` doesn't return a `Result` and `write!` does, I simply discarded the return values of `write!`.
Because this was a simple change I figured I could sneak in a few other changes to clean up the code some more. I hope that's okay. These changes are:
* Merging some imports
* Use `Entry` API with the cache `HashMap`s.
* Remove some …
> `ls`: reduce write syscalls & cleanup

- tests/by-util/test_truncate.rs
* Adds some more tests to improve coverage on truncate.
* Make assert error messages provide useful info for debuging test failures
> Expand truncate tests

- src/uu/ls/src/ls.rs
- tests/by-util/test_ls.rs
Added implementation (and small test) for extension sorting with ls.
Fixes #1880 
There is some difference to the behavior of my ls on ubuntu, especially when it comes to the behavior of hidden directories and files, this implementation does not treat hidden files (with a leading .) as extensions, whereas my system's /usr/bin/ls does. 
Not sure on the pro's and con's about that and would like to discuss.
> ls: Implements extension sorting

- src/uu/ls/BENCHMARKING.md
- src/uu/ls/src/ls.rs
- src/uu/ls/src/quoting_style.rs
I did some more performance improvements based on flamegraph data. I documented the method for this in `BENCHMARKING.md`. The changes I made are mostly reducing some allocations and reducing the times that `OsStrs` are converted to `Strings`.
**Before**
```
Benchmark #1: ls ../firefox-source/ -R
Time (mean ± σ):     741.3 ms ±  26.7 ms    [User: 521.4 ms, System: 216.2 ms]
Range (min … max):   708.8 ms … 766.3 ms    10 runs
Benchmark #2: target/release/coreutils ls ../firefox-source/ -R
Time (mean ± σ):      1.049 s ±  0.031 s    [User: 831.8 ms, System: 212.2 ms]
Range (min … max):    1.005 s …  1.090 s    10 runs
Summary
'ls ../firefox-source/ -R' ran
1.41 ± 0.07 times faster than 'target/release/coreutils ls ../firefox-source/ -R'
```
**After**
```
Benchmark #1: ls ../firefox-source/ …
```
> `ls`: file name handling performance improvements

- Cargo.lock
- src/uu/ls/Cargo.toml
- src/uu/ls/src/ls.rs
- tests/by-util/test_ls.rs
Fixes https://github.com/uutils/coreutils/issues/2132
**Before** (in the terminal this is colored, of course)
```
❯ target/release/coreutils ls --color
benches  CODE_OF_CONDUCT.md         examples          LICENSE           'one\ntwo'     README.md             tests
build.rs          CONTRIBUTING.md            flamegraph.svg    Makefile          'one\two'      src          util
Cargo.lock        DEVELOPER_INSTRUCTIONS.md  flamegraph_ls.sh  Makefile.toml     perf.data      target       
Cargo.toml        docs              GNUmakefile                'one'$'\n''&two'  perf.data.old  test_folder
```
**After**
```
❯ target/release/coreutils ls --color
benches     Cargo.toml          DEVELOPER_INSTRUCTIONS.md  flamegraph.svg    LICENSE        'one'$'\n''&two'  perf.data      src          tests …
```
> `ls`: fix grid alignment with `--color`

- src/uu/truncate/src/truncate.rs
- tests/by-util/test_truncate.rs
The GNU truncate allows you to use `--reference` when giving an increase or decrease by size.
> Allow truncate to take --size and --reference

- Cargo.lock
- src/uu/factor/Cargo.toml
- src/uu/factor/src/factor.rs
- src/uu/factor/src/table.rs
`coz` is a profiling utility that's helpful in figuring out which parts of the
code would yield the greatest performance improvement when optimized (as opposed
to which take the longest).
The dependency on it is [optional], and when the corresponding feature is not
enabled there is no functional or performance change.
[optional]: https://doc.rust-lang.org/cargo/reference/features.html#optional-dependencies
> factor: Add annotations for coz, the causal profiler

- src/uu/ls/src/ls.rs
- tests/by-util/test_ls.rs
This is an attempt to make the tests for `ls -t --time=birth` a little bit more stable and also enable the test for Windows. ~Keeping this as a draft for now to see whether it works out.~
Tests are green, the failures are unrelated, so this seems to fix it. `AtPath::touch` seemed to be the issue for windows because it uses `File::create`, which sets the creation time on Windows. I'm not sure whether this fixes the stability of the other tests, but the best we can do is wait and see.
> `ls`: add birth time for windows and attempt to fix tests

- src/uu/dirname/src/dirname.rs
- src/uu/tr/src/tr.rs
- tests/by-util/test_dirname.rs
- tests/by-util/test_tr.rs
I noticed there were two (tr and dirname) getopts to clap ports which called `short()` within `App::arg` more than once. However, this does not create an alias for the short flag because the last call to `short()` takes precedence over previous calls.
Since `Arg::visible_short_alias()` is only available in clap >3.0, aliases for short flags can only be created with a work around, i.e. an additional call to `App::arg()`.
* implements `-C` as an alias for `-c` for `tr` and adds tests
* fix `--zero` flag for `dirname` and adds tests
* refactor `dirname` and `tr` to be more consistent with other clap ports, e.g. use of `get_usage()` and `get_long_usage()`
> tr/dirname: fix clap short_alias

- src/uu/tr/src/tr.rs
- tests/by-util/test_tr.rs
Add translate and squeeze mode to the `tr` program. For example:
$ printf xx | tr -s x y
y
Fixes #2141.
> tr: implement translate and squeeze (-s) mode

- src/uu/test/src/parser.rs
- src/uu/test/src/test.rs
- tests/by-util/test_test.rs
- tests/fixtures/test/non_empty_file
* Replace the parser with a recursive descent implementation that handles parentheses and produces a stack of operations in postfix order. Parsing now operates directly on OsStrings passed by the uucore framework.
* Replace the dispatch mechanism with a stack machine operating on the symbol stack produced by the parser.
* Add many tests, including tests for parenthesized expressions.
> test: implement parenthesized expressions, additional tests

- src/uu/ls/BENCHMARKING.md
- src/uu/ls/src/ls.rs
- tests/by-util/test_ls.rs
Fixes https://github.com/uutils/coreutils/issues/2149
- The sort order is reverted to a simple string compare without any preprocessing (lowercasing & ignoring leading periods) to match the C locale. This makes the uutils `ls` faster than GNU on my machine, but this is misleading because GNU does localization by default. The `BENCHMARKING.md` therefore includes a note stating that comparisons should be done with `LC_ALL=C`.
- The name of the `.` folder is fixed and tests are added for this case.
**Before**
```
❯ target/release/coreutils ls -al test_folder/
drwxr-xr-x  3 terts terts 4096 May  1 09:16 test_folder
drwxr-xr-x 15 terts terts 4096 May  2 10:15 ..
-rw-r--r--  1 terts terts    0 Apr 30 21:23 Formula
-rw-r--r--  1 terts terts    0 May  1 09:16 formula
drwxr-xr-x  2 terts terts …
```
> `ls`: C sort order and fix subdirectory listing

- src/uu/sort/src/custom_str_cmp.rs
- src/uu/sort/src/sort.rs
This removes the need to allocate a new string for each line when used
with -f, -d or -i. Instead, a custom string comparison algorithm takes
care of these cases.
The resulting performance improvement is about 20% per flag (i.e. there
is a 60% improvement when combining all three flags)
As a side-effect, the size of the Line struct was reduced from 96 to 80
bytes, reducing the overhead for each line.
> sort: add some custom string comparisons

- Cargo.lock
- src/uu/kill/Cargo.toml
- src/uu/kill/src/kill.rs
- tests/by-util/test_kill.rs
- Migrate to clap.
- Change default signal to SIGTERM.
- Add integration tests.
Fixes #2122.
> kill: migrate to clap

- src/uu/who/Cargo.toml
- src/uu/who/src/who.rs
- tests/by-util/test_who.rs
* move from getopts to clap (closes #2124)
* add more tests
Clap `v3.0.0-beta.2` was needed instead of the latest stable `2.33.3` in order to be able to use `Arg::visible_short_alias`.
Otherwise the use of multiple short flags for the same option would have required an ugly work around with an additional `App::arg` for every short flag alias.
Since all other ports use clap `2.33`, I'm unsure if it's okay to use a non stable Clap?
There are other uutils that would benefit from `Arg::visible_short_alias`, e.g. `rm -r` / `rm -R` (#1834), etc.
> who: move from getopts to clap (#2124)

- src/uu/basename/Cargo.toml
- src/uu/basename/src/basename.rs
- tests/by-util/test_basename.rs
This PR contains the following changes  
- moved from getopts to clap (resolves #2117)    
- add tests
> basename: move from getopts to clap

- tests/by-util/test_stat.rs
On Fedora Linux `test_terse_normal_format` fails because uu_stat doesn't print `SELinux security context string` if invoked with `-t`.
```
run: stat -t /                                                                                                                                     
actual: "/ 4096 8 416d 0 0 fd01 2 18 0 0 1619888495 1605377538 1605377538 1576062995 4096\n"                                                       
expect: "/ 4096 8 416d 0 0 fd01 2 18 0 0 1619888495 1605377538 1605377538 1576062995 4096 system_u:object_r:root_t:s0\n"
```
> stat: fix test to ignore selinux related output

- Cargo.lock
- src/uu/ls/src/ls.rs
- tests/by-util/test_ls.rs
Total size for directories in long format is implemented with this PR for unix. For non-unix environments, there is no exact equivalent for what GNU displays so I've left it unimplemented at the moment instead of printing some other value.
Partially fixes #1872
> Implement Total size feature

- src/uu/fmt/src/linebreak.rs
- tests/by-util/test_fmt.rs
Fixes #1501. The `tlen` variable will sometimes exceed the size of the `goal` option, causing the overflow as they are both unsigned ints. We can cast to signed before the subtraction without worrying about loss of range as the maximum width and therefore the maximum that `goal` and `tlen` is 2500.
> Fix fmt crashing on subtracting unsigned numbers

- src/uu/wc/src/wc.rs
- tests/by-util/test_wc.rs
Remove the leading space from the output of `wc` when printing two or
more types of counts.
Fixes #2173.
> wc: remove leading space when printing multiple counts

- src/uu/wc/src/wc.rs
- src/uu/wc/src/wordcount.rs
This pull request moves the `WordCount` struct and its implementations into a new module, `wordcount.rs`, but more importantly, this pull request refactors the counting code from the inner loop of the `wc` program into the `WordCount::from_line()` associated function. It also splits that function up into other helper functions that encapsulate decoding characters and finding word boundaries from raw bytes. Finally, this commit also implements the `Sum` trait for the `WordCount` struct, so that we can simply call `sum()` on an iterator that yields `WordCount` instances. (The `Add` trait was already implemented.)
This change allows us to express the main loop concisely as
```rust
reader.lines().map(|line| WordCount::from_line(line)).sum()
```
although you can see in the actual diff that in …
> wc: move counting code into WordCount::from_line() for easier iteration

- src/uu/split/src/split.rs
- tests/by-util/test_split.rs
Things done:
* Simplified the parsing that `ByteSplitter` does quite a bit, and brings it in line with GNU coreutils split behavior.
* Refactored the internals of split to be clearer.
* Updated and extended the test suite to test a few more cases, including testing that it works on non-UTF-8 files, testing that the resulting files are the correct size, and little bits for testing corner cases with the buffering logic.
Tests are passing on my machine, and I've confirmed that this solves my original problem in #2174.
As a result of working on this, I discovered that `Settings.verbose` is unused, but I refrained from removing it in this PR so as to keep the changes small. Happy to remove in a separate PR. Also the `OPT_LINE_BYTES` options is redundant and behaves exactly like `OPT_BYTES` …
> Fix split's handling of non-UTF-8 encoded input files

- Cargo.lock
- src/uu/sort/Cargo.toml
- src/uu/sort/src/external_sort/mod.rs
- src/uu/sort/src/sort.rs
(Based on #2156 for convenience, the actual change is in the latest commit)
Related to #2134.
I still need to kick this around a bit, these are IMHO the low hanging fruits when it comes to memory usage reduction.
> sort: optimize the line struct

- src/uu/test/src/parser.rs
- src/uu/test/src/test.rs
- tests/by-util/test_test.rs
- add `==` as undocumented alias of `=`
- handle negated comparison of `=` as literal
- negation generally applies to only the first expression of a Boolean chain,
except when combining evaluation of two literal strings
This version passes 12 more tests from the GNU suite (50 failing in this PR vs. 62 from master):
```
$ make TESTS=tests/misc/test.pl SUBDIRS=. check
...
$ rg failed tests/misc/test.log | wc -l
50
```
> test: improve handling of inverted Boolean expressions

- src/uu/tail/src/ringbuffer.rs
- src/uu/tail/src/tail.rs
This pull request refactors common code out of two branches of the `unbounded_tail()` function into a new `unbounded_tail_collect()` helper function, that collects from an iterator into a `VecDeque` and keeps either the last `n` elements or all but the first `n` elements.
This commit also adds a new struct, `RingBuffer`, in a new module, `ringbuffer.rs`, to be responsible for keeping the last `n` elements of an iterator.
These changes use some iterators in the standard library, like `BufRead::lines()` and `Iterator::skip()`, to make the code more succinct.
> tail: simplify unbounded_tail() function

- src/uu/wc/src/wc.rs
- src/uu/wc/src/wordcount.rs
- tests/by-util/test_wc.rs
When stdin is explicitly specified on the command-line with '-', emit it
in the output stats to match GNU wc output.
Fixes #2188.
> wc: emit '-' in ouput when set on command-line

- src/uu/date/src/date.rs
- tests/by-util/test_date.rs
This is a fix for #2205 that also considers format literals as pointed out by @jfinkels https://github.com/uutils/coreutils/pull/2205#discussion_r630583042
> date: fix format literal for nanoseconds

- src/uu/tail/src/chunks.rs
- src/uu/tail/src/tail.rs
This pull request refactors code from the `backwards_thru_file()` function into a new `ReverseChunks` iterator, and use that iterator to simplify the implementation of the `backwards_thru_file()` function. The `ReverseChunks` iterator yields `Vec<u8>` objects, each of which references bytes of a given file.
This has the benefit of providing and using an abstraction similar to one in the standard library, https://doc.rust-lang.org/std/slice/struct.RChunks.html. However, it creates a new `Vec<u8>` for each chunk, whereas the previous code was re-using the same `Vec<u8>` to read each chunk into. Perhaps someone more familar with Rust could propose an improvement to this part of the code.
> tail: refactor code into ReverseChunks iterator

- src/uu/wc/src/wc.rs
- tests/by-util/test_wc.rs
This pull request changes the error messages that get printed to `stderr` for compatibility with GNU `wc` when an input is a directory and when an input does not exist. The messages are now
```
$ ./target/debug/coreutils wc /tmp
wc: /tmp: Is a directory
0 0 0 /tmp
$ ./target/debug/coreutils wc blah
wc: blah: No such file or directory
0 0 0 blah
```
Fixes #2211.
> wc: correct some error messages for invalid inputs

- Cargo.lock
- src/uu/pinky/src/pinky.rs
- src/uu/who/src/who.rs
- src/uucore/Cargo.toml
- src/uucore/src/lib/features/utmpx.rs
- tests/by-util/test_pinky.rs
- tests/by-util/test_who.rs
This closes #2181.
`who --lookup` is failing with a runtime panic (double free).
Since `crate::dns-lookup` already includes a safe wrapper for `getaddrinfo`
I used this crate instead of further debugging the existing code in
utmpx::canon_host().
> who: fix `--lookup`

- src/uu/head/src/head.rs
- tests/by-util/test_head.rs
This pull request fixes a bug in which `head` failed to print headings for `stdin` inputs when reading from multiple files, and fix another bug in which `head` failed to print a blank line between the contents of a file and the heading for the next file when reading multiple files. The output now matches that of GNU `head`.
A future pull request can refactor the common code for printing the heading above the contents of each file.
> head: print headings when reading multiple files

- tests/by-util/test_ls.rs
Fixed https://github.com/uutils/coreutils/issues/2215 . It was not taking negative timezone offsets.
> fixing regex to take negative time offsets

- src/uu/truncate/src/truncate.rs
- tests/by-util/test_truncate.rs
This pull request changes the interface provided by the `parse_size()` function to reduce its responsibilities to just a single task: parsing a number of bytes from a string of the form '123KB', etc. Previously, the function was also responsible for deciding which mode truncate would operate in. Furthermore, this commit simplifies the code for parsing the number and unit to be less verbose and use less mutable state. Finally, this commit adds some unit tests for the `parse_size()` function itself, as well as a test for invalid size arguments for the command-line itself.
(There may be other coreutils programs that require parsing a size from a string with units, they could use this function.)
> truncate: simplify parse_size() function and correct error message

- .github/workflows/GNU.yml
The “GNU tests” task is routinely broken on `master`.
Broken CI is worse than no CI, as it teaches people to ignore errors.
This PR pins the versions of the GNU testsuite (and GNUlib) used,
to current stable versions, so this task stops breaking unexpectedly.
This is a proposed alternative to #2225.
Presumably, someone will update `GNU.yml` when a new stable version
of the GNU coreutils is released, but I'm not volunteering.
> CI: Stabilise the version of GNU tests used in CI

- src/uu/head/src/head.rs
- tests/by-util/test_head.rs
- tests/common/util.rs
This pull request changes the behavior of `head` to display an error for each problematic file, instead of displaying an error message for the first problematic file and terminating immediately at that point. This change now matches the behavior of GNU `head`.
Before this commit, the first error caused the program to terminate immediately:
$ head a b c
head: error: head: cannot open 'a' for reading: No such file or directory
After this commit:
$ head a b c
head: cannot open 'a' for reading: No such file or directory
head: cannot open 'b' for reading: No such file or directory
head: cannot open 'c' for reading: No such file or directory
> head: display errors for each input file instead of terminating at the first error

- tests/by-util/test_cat.rs
/dev/random blocks on Linux, you have to use /dev/urandom. This fixes https://github.com/uutils/coreutils/issues/2214.
> dev random blocks on linux

- src/uu/truncate/src/truncate.rs
- tests/by-util/test_truncate.rs
This pull request changes the error message for when the reference file (the `-r` argument) is not found to match GNU coreutils. This commit also eliminates a redundant call to `File::open`; the file need not be opened because the size in bytes can be read from the result of `std::fs::metadata()`. (The error message suggests that implementation as well: it states `"cannot stat '{}'"`.)
> truncate: fix error message for file not found

- .cirrus.yml
It is failing currently on:
```
info: installing component 'cargo'
error: error: 'sysinfo not supported on this platform'
```
with 1.52.1
> freebsd/circus: workaround the timeout

- src/uu/ls/src/ls.rs
- tests/by-util/test_ls.rs
For any commandline arguments, ls should print the argument as is (and not truncate to just the file name)
For any other files it reaches (say through recursive exploration), ls should print just the filename (as path is printed once when we enter the directory)
This PR implements above behavior and also fixes corresponding test and fixes #2223
> Fix ls path printing

- src/uu/wc/src/wc.rs
- tests/by-util/test_wc.rs
This pull request fixes two issues with the string formatting width for counts displayed by `wc`.
First, the output was previously not using the default minimum width (seven characters) when reading from `stdin`. This commit corrects this behavior to match GNU `wc`. For example,
$ cat alice_in_wonderland.txt | wc
5      57     302
Second, if at least 10^7 bytes were read from `stdin` *after* reading from a smaller regular file, then every output row would have width 8. This disagrees with GNU `wc`, in which only the `stdin` row and the total row would have width 8. This commit corrects this behavior to match GNU `wc`. For example,
$ printf "%.0s0" {1..10000000} | wc emptyfile.txt -
0       0       0 emptyfile.txt
0       1 10000000
0       1 10000000 total
(I did not add a test for this …
> wc: compute minimum width to format counts up front

- .github/workflows/CICD.yml
- src/uu/stat/src/stat.rs
- src/uu/who/src/who.rs
- src/uucore/src/lib/features/utmpx.rs
- tests/by-util/test_pinky.rs
- tests/by-util/test_stat.rs
- tests/by-util/test_who.rs
A lot of tests depend on GNU's coreutils to be installed in order
to obtain reference values during testing.
In these cases testing is limited to `target_os = linux`.
This PR installs GNU's coreutils on "github actions" and adjusts the
tests for `who`, `stat` and `pinky` in order to be compatible with macOS.
* `brew install coreutils` (prefix is 'g', e.g. `gwho`, `gstat`, etc.
* switch paths for testing to something that's available on both OSs,
e.g. `/boot` -> `/bin`, etc.
* switch paths for testing to the macOS equivalent,
e.g. `/dev/pts/ptmx` -> `/dev/ptmx`, etc.
* exclude paths when no equivalent is available,
e.g. `/proc`, `/etc/fstab`, etc.
* refactor tests to make better use of the testing API
* fix a warning in utmpx.rs to print to stderr instead of stdout
* fix long_usage text in …
> who/stat/pinky: adjust tests to be compatible with running on macOS 

- src/uu/truncate/src/truncate.rs
- tests/by-util/test_truncate.rs
This pull request fixes a bug in which the incorrect character was being used to indicate "round up to the nearest multiple" mode in `truncate`. The character was "*" but it should be "%". This commit corrects that. Here is the corresponding section of the GNU man page for `truncate` in GNU coreutils v8.28:
```
SIZE may also be prefixed by one of the following modifying characters:
'+' extend by, '-' reduce by, '<' at most, '>' at least, '/' round down
to multiple of, '%' round up to multiple of.
```
(As far as I can this is just a typo that was never noticed. It seems that `truncate` was introduced in https://github.com/uutils/coreutils/commit/968483bdf6332b382dfc673e6e9545dabf68e765, where you can already see the discrepancy between the implementation, which has `'*'` and the help text, …
> truncate: fix character used to indicate round up

- src/uu/tail/src/tail.rs
- tests/by-util/test_tail.rs
Fix an off-by-one issue for `tail -c +NUM` and `tail -n +NUM` command line options. This is for compatibility with GNU `tail`, which treats the bytes and lines as if they were 1-indexed, not 0-indexed. (So `tail -c +0` and `tail -c +1` seem to do the same thing.)
> tail: fix off-by-one issue for +NUM args

- src/uu/sort/BENCHMARKING.md
- src/uu/sort/src/check.rs
- src/uu/sort/src/chunks.rs
- src/uu/sort/src/ext_sort.rs
- src/uu/sort/src/merge.rs
- src/uu/sort/src/sort.rs
- tests/by-util/test_sort.rs
To make this work we make default sort a special case of external sort.
External sorting uses auxiliary files for intermediate chunks. However,
when we can keep our intermediate chunks in memory, we don't write them
to the file system at all. Only when we notice that we can't keep them
in memory they are written to the disk.
Additionally, we don't allocate buffers with the capacity of their
maximum size anymore. Instead, they start with a capacity of 8kb and are
grown only when needed.
This makes sorting smaller files about as fast as it was before
(I'm seeing a regression of ~3%), and allows us to seamlessly continue
with auxiliary files when needed.
Command for the benchmark mentioned above: `hyperfine "./coreutils-before-patch sort shuffled_wordlist.txt" "target/release/coreutils sort …
> sort: automatically fall back to extsort

- src/uu/sort/src/sort.rs
- tests/by-util/test_sort.rs
`sort` supports three ways to specify the sort mode: a long option
(e.g. --numeric-sort), a short option (e.g. -n) and the sort flag
(e.g. --sort=numeric).
This adds support for the sort flag.
Additionally, sort modes now conflict, which means that an error is
shown when multiple modes are passed, instead of silently picking a mode.
For consistency, I added the `random` sort mode to the `SortMode` enum,
instead of it being a bool flag.
> sort: support --sort flag and check for conflicts

- .github/workflows/CICD.yml
Fails trom time to time with:
```
info: installing component 'rustc'
memory allocation of 16777216 bytes failed
Error: The process 'C:\Rust\.cargo\bin\rustup.exe' failed with exit code 3221226505
```
on  Build (windows-latest, i686-pc-windows-gnu, feat_os_windows)
> Workaround the Windows CI install issue.

- src/uu/expr/src/syntax_tree.rs
- tests/by-util/test_expr.rs
Instead of returning an Err it should return the "null string"
(in our case that's the empty string) when the offset or length
is invalid.
> expr: make substr infallible

- src/uu/wc/src/wc.rs
This pull request changes the behavior of `wc` to print the counts for a file as soon as it is computed, instead of waiting to compute the counts for all files before writing any output to `stdout`. The new behavior matches the behavior of GNU `wc`.
The old behavior looked like this (the word "hello" is entered on `stdin`):
$ wc emptyfile.txt -
hello
0       0       0 emptyfile.txt
1       1       6 -
1       1       6 total
The new behavior looks like this:
$ wc emptyfile.txt -
0       0       0 emptyfile.txt
hello
1       1       6 -
1       1       6 total
> wc: print counts for each file as soon as computed

- src/uucore/src/lib/macros.rs
After moving all(literally) the argument parsing stuff to clap, there is need to keep these macros.
> uucore: delete unused macros

- src/uu/cp/src/cp.rs
- src/uucore/src/lib/lib.rs
- src/uucore/src/lib/mods.rs
- src/uucore/src/lib/mods/backup_control.rs
- tests/by-util/test_cp.rs
This PR also includes a `uucore` implementation of backup control where it can live to be shared among the utilities needing backup control.
The backup control in `uucore` was sourced from `mv`'s existing backup control. In a follow-up PR (or this one on request) I can make changes to `mv` and other utilities so that they all use the `backup_control.rs` functionality in `uucore`.
fixes #2231
> cp: implement backup support

- src/uu/mv/src/mv.rs
- tests/by-util/test_mv.rs
This PR is a follow-up to #2275 refactoring the backup logic in `mv` to use the shared `backup_control` in `uucore`. I added comprehensive tests too.
This also fixes #2278 (issue with existing `mv` backup logic).
In my last PR (#2275) I merged the two args `--backup` and `-b` using `.short("b")` for the `--backup` arg. I realized when implementing this PR that this fails when using the short arg in a group of other short args.
For example, this would fail:
```sh
$ mv -vbT [file] [file]
error: The argument '--backup=<CONTROL>' requires a value but none was supplied
USAGE:
mv [OPTION]... [-T] SOURCE DEST
mv [OPTION]... SOURCE... DIRECTORY
mv [OPTION]... -t DIRECTORY SOURCE...
For more information try --help
```
but it would succeed if the `-b` arg was listed last in the group or on it's …
> mv: refactor backup logic to use shared uucore backup control

- .github/workflows/CICD.yml
- Cargo.lock
- Cargo.toml
- README.md
Closes https://github.com/uutils/coreutils/issues/2282
I hope I did not miss any important steps but based on the previous version bump and checking where 1.40 was mentioned, I think this is all that needs to change.
> Bump MSRV to 1.43.1

- src/uu/cp/src/cp.rs
- tests/by-util/test_cp.rs
This PR also adds a test for the regressed issue.
See the note about `--backup` and `-b` in #2284 for more info.
> cp: fix regressed issue with `--backup` and `-b`

- src/uu/csplit/src/csplit.rs
- src/uu/expr/src/tokens.rs
- src/uu/fmt/src/parasplit.rs
- src/uu/hashsum/src/hashsum.rs
- src/uu/mktemp/src/mktemp.rs
- src/uu/od/src/parse_formats.rs
- src/uu/rm/src/rm.rs
- src/uu/sort/src/ext_sort.rs
- src/uu/sort/src/numeric_str_cmp.rs
- src/uu/sort/src/sort.rs
- src/uu/stdbuf/src/stdbuf.rs
- src/uu/test/src/parser.rs
- src/uucore_procs/src/lib.rs
We can now use the `matches!` macro, which means we don't have to `#[allow(clippy::match_like_matches_macro)]` anymore.
There were also a few attributes that could be removed since rust 1.38.
I also formatted all recent changes.
> maint: adapt code to new MinRustV

- tests/common/util.rs
This is (hopefully) the last PR in the 'enable-arbitrary-binary-stdout' refactor saga.
It just changes `CmdResult`s inner representation to `Vec<u8>`, and then adjusts where necessary.
Possible future consideration:
Caching the `&str` and `String` representations after they're used at least once, could help performance. (Not in this PR)
> Closing #1916 - Concluding the test refactor

- Cargo.lock
- src/uu/factor/Cargo.toml
- src/uu/factor/src/cli.rs
- tests/by-util/test_factor.rs
Issue: https://github.com/uutils/coreutils/issues/2121
Help looks like:
```
factor 0.0.6
Print the prime factors of the given NUMBER(s).
If none are specified, read from standard input.
USAGE:
factor [NUMBER]...
FLAGS:
-h, --help       Prints help information
-V, --version    Prints version information
ARGS:
<NUMBER>...
```
> Moved factor to use clap

- src/uu/truncate/src/truncate.rs
- tests/by-util/test_truncate.rs
This pull request reorganizes the code in `truncate.rs` into three distinct functions representing the three modes of operation of the `truncate` program. The three modes are
- `truncate -r RFILE FILE`, which sets the length of `FILE` to match the length of `RFILE`,
- `truncate -r RFILE -s NUM FILE`, which sets the length of `FILE` relative to the given `RFILE`,
- `truncate -s NUM FILE`, which sets the length of `FILE` either absolutely or relative to its current length.
This organization of the code makes it more concise and easier to follow.
> truncate: re-organize truncate() into one function for each mode of operation

- .github/workflows/CICD.yml
This adds annotations like
```
cspell: Unknown word (socio)
```
to .rs and .md files if there's an unknown word.
This is the first time I've touched Github Actions, sed and cspell, so please check if this is the correct way of doing this :smiley: 
cc @rivy
> maint: add spell checker to CICD

- src/uu/rmdir/src/rmdir.rs
- tests/by-util/test_rmdir.rs
Reverts uutils/coreutils#2305
Fails on Windows with:
```
---- test_rmdir::test_rmdir_remove_symlink_match_gnu_error stdout ----
current_directory_resolved: 
touch: C:\Users\RUNNER~1\AppData\Local\Temp\.tmpboJOXp\file
symlink: C:\Users\RUNNER~1\AppData\Local\Temp\.tmpboJOXp\file,C:\Users\RUNNER~1\AppData\Local\Temp\.tmpboJOXp\fl
run: D:\a\coreutils\coreutils\target\i686-pc-windows-gnu\debug\coreutils.exe rmdir fl/
thread 'test_rmdir::test_rmdir_remove_symlink_match_gnu_error' panicked at 'assertion failed: `(left == right)`
Diff < left / right > :
<"rmdir: reading directory \'fl/\': The directory name is invalid. (os error 267)"
>"rmdir: failed to remove \'fl/\': Not a directory"
', tests\common\util.rs:229:9
```
> Revert "rmdir: match GNU error output"

- src/uu/ls/src/ls.rs
- tests/by-util/test_ls.rs
When a single directory is passed to ls in recursive mode, uutils ls
won't print the directory name
GNU ls:
z:
uutils ls:
This commit fixes this minor inconsistency and adds corresponding test.
> ls: Fix minor output mismatch

- tests/by-util/test_du.rs
WARNING: `cargo clippy`: single-character string constant used as pattern
> Fix a clippy warning

- Cargo.lock
- src/uu/touch/src/touch.rs
- tests/by-util/test_touch.rs
Now it can parse `touch -d 2000-01-23 file`
Related to #2311
> Fix touch parse date error

- Cargo.lock
- src/uu/seq/Cargo.toml
- src/uu/seq/src/seq.rs
- tests/by-util/test_seq.rs
- Implements a BigInt based code path for integer sequences when all arguments are integers.
- Change the default value for the -t flag to GNU's implicit default.
- Remove support for escape sequences: Do not interpret "\n" / "\t" as a newline/tab. Only actual tab/newline characters should be treated as tab/newline.
- Small bug fix: Already make clap show an error if no arguments are supplied instead of panicking on an unwrap.
> seq: improve compatibility

- .github/workflows/CICD.yml
- src/uu/pr/src/pr.rs
- src/uu/rmdir/src/rmdir.rs
- tests/by-util/test_pr.rs
`**/*` must be quoted, otherwise it is expanded by the shell and not
literally passed to cspell.
I tried to fix the errors that came up.
Fyi @rivy
> maint: actually run spellcheck on all files

- src/uu/sum/src/sum.rs
The help text for the `--sysv` argument was incorrectly copied from the `-r` argument.
> `sum`: fix help text for System V argument

- tests/by-util/test_pr.rs
Closes https://github.com/uutils/coreutils/issues/2329
I went for the simplest fix I could think of, which is to get the time right before the command starts running, instead of after. It doesn't make the failure impossible, but it does make it less likely. I could take another look at this if problems still turn up too often.
> `pr`: fix usage of current time in tests

- src/uu/du/src/du.rs
- tests/by-util/test_du.rs
Closes #2279 
I also added `birth` and `creation` feature like `--time` behavior in `ls` command.
> du: fix `--time` behavior

- README.md
In PR #2300 an old commit got merged putting back utilities that were
already implemented into "To Do". This commit reverts this. In addition
it moves `numfmt` to Semi-Done and sorts the Semi-Done column
alphabetically.
This should now be the up-to-date list of utilities. There are 96
utilities in Done or Semi-Done and `ls -1 src/uu | wc -l` also outputs
96.
> README: Cleanup utility list

- Cargo.lock
- src/uu/dircolors/Cargo.toml
- src/uu/dircolors/src/dircolors.rs
Closes #2119.
This ports dircolors from `getopts` to `clap`.
A couple of things I was uncertain about:
- Should I add myself to the copyright header or not?
- I left in a few verbose comments justifying doing some things in a non-clap-standard way - are those OK?
- Most of the commands in here get the version using a snippet like `static VERSION: &str = env!("CARGO_PKG_VERSION");`, but clap provides the `crate_version!()` macro for this.  Is it OK to use the macro, or should I do it manually?
- `echo`, `env`, `hashsum`, and `tail` are using `crate_version!()`.  Would it be good to standardize on one or the other?
The dircolors tests are all still passing, at least on Debian.
The only difference I have observed is that clap auto-generates `-h` and `-V` short options for help and version, …
> dircolors: replace getopts with clap

- Cargo.toml
- src/uu/groups/src/groups.rs
- src/uu/id/src/id.rs
- src/uucore/src/lib/features/entries.rs
- tests/by-util/test_groups.rs
- tests/by-util/test_id.rs
As discussed here: #2361
the group IDs returned for GNU's 'group' and GNU's 'id --groups'
starts with the effective group ID.
This implements a wrapper for `entris::get_groups()` which mimics
GNU's behaviour.
* add tests for `id`
* add tests for `groups`
* fix `id --groups --real` to no longer ignore `--real`
> uucore: fix order of group IDs return from entries::get_groups()

- Cargo.lock
- Cargo.toml
- src/uu/cat/Cargo.toml
- src/uu/cat/src/cat.rs
- src/uu/cut/Cargo.toml
- src/uu/cut/src/cut.rs
- src/uu/more/Cargo.toml
- src/uu/nohup/Cargo.toml
- src/uu/nohup/src/nohup.rs
- src/uu/tty/Cargo.toml
- src/uu/tty/src/tty.rs
- src/uucore/src/lib/features/fs.rs
Closes https://github.com/uutils/coreutils/issues/1162
> `cat`/`cut`/`tty`/`nohup`: replace `is_std{in, out, err}_interactive` with atty

- tests/by-util/test_groups.rs
On Arch-based systems (at least mine, which is Manjaro), the `groups` command comes from shadow utils instead of GNU coreutils. We can check against `id -Gn` instead, which should be identical according to the docs.
cc @jhscheer
> `groups`: fix test for Arch-based systems

- Cargo.lock
- src/uu/whoami/Cargo.toml
- src/uu/whoami/src/platform/windows.rs
Closes https://github.com/uutils/coreutils/issues/1564
> `whoami`: remove `advapi32-sys` dependency and use `winapi`

- src/uu/ln/src/ln.rs
Closes https://github.com/uutils/coreutils/issues/2359
I've taken the opportunity to also refactor the arguments a bit.
`--symbolic` is now special-cased to fix the issue, which might be a little bit weird. Maybe we should encourage that (almost) all flags override themselves? I did not use `multiple` because we don't need the number of times this flag is used.
> `ln`: refactor argument handling and fix #2359

- src/uu/du/src/du.rs
- tests/by-util/test_du.rs
From original GNU `du`:
```
-x, --one-file-system    skip directories on different file systems
```
Two directories are considered in the same file system if they have the same device id.
> du: add `--one-file-system`

- src/uu/more/src/more.rs
Should do the same as https://github.com/uutils/coreutils/pull/2380 and I restructured the code to have a `Pager` struct. I used some of the changes from #2380, but as I was already writing this, merging that first would not make sense.
Fixes/changes:
- do not accidentally skip the first line (or hide the first line)
- going to the end, back up and down again no longer skips past the last page
- state is stored in the `Pager` struct, cleaning up the main loop
- drawing the prompt and flushing are separated
- use `usize` everywhere instead of `u16`
cc @miDeb
> `more`: rewrite drawing logic

- Cargo.lock
- src/uu/chgrp/Cargo.toml
- src/uu/chgrp/src/chgrp.rs
- src/uucore/src/lib/features/perms.rs
- tests/by-util/test_chgrp.rs
- tests/fixtures/chgrp/file1
- tests/fixtures/chgrp/file2
- tests/fixtures/chgrp/file3
- tests/fixtures/chgrp/ref_file
Hey, I'm trying to learn rust and this looked like something straightforward to do, especially since the `chown` command is so similar.
I'm not 100% certain that the I have the best way to handle the `--reference` flag, but I couldn't come up with any options that left the `files` Vec immutable.
> chgrp: replace getopts with clap (#2118)

- tests/by-util/test_pr.rs
- tests/common/util.rs
I hope this prevents the occasional test failures on CI from timing issues in pr tests.
Instead of only checking if stdout contains the timestamp from the start of the command,
check for any timestamp from the start to the end of the command.
Closes #2329.
> tests/pr: prevent races

- src/uu/touch/src/touch.rs
- tests/by-util/test_touch.rs
I'm in the process of adding a test as well but I'm having problems running it. I've asked for help in the discord channel so as soon as I make it work, I'll also commit it.
> touch: change the error message to match the GNU error message #2346

- src/uu/tty/src/tty.rs
- tests/by-util/test_tty.rs
There probably was a misunderstanding of what `pipe_in("</dev/null")` does. It pipes in the raw string `"</dev/null"`, not the `/dev/null` _file_. Piping in the string could cause a "Broken pipe" error because `tty` never reads anything from stdin.
I also fixed the exit codes for wrong arguments and write errors.
> tty: fix tests and exit codes

- src/uu/sort/src/check.rs
- src/uu/sort/src/chunks.rs
- src/uu/sort/src/ext_sort.rs
- src/uu/sort/src/merge.rs
- src/uu/sort/src/sort.rs
- tests/by-util/test_sort.rs
- When we have finished reading from a temproary file, we can immediately
delete it.
- Use one single directory for all temporary files.
- Only create the temporary directory when needed.
- Also compress temporary files created by the merge step, not only the initial
ext-sort step (if compression was requested).
> sort: delete temporary files as soon as possible

- src/uucore/src/lib/features/entries.rs
- src/uucore/src/lib/features/process.rs
While testing my PR for `id` (#2361) I noticed that (although coreutils Testsuite passes for `id`) my tests on macOS return less groups than both GNU's coreutils `id` and Darwin's `id`:
```bash
run: gid runner
run: /Users/runner/work/coreutils/coreutils/target/x86_64-apple-darwin/debug/coreutils id runner
thread 'test_id::test_id_single_user' panicked at 'assertion failed: `(left == right)`
```
```diff
Diff < left / right > :
-"uid=501(runner) gid=20(staff) groups=20(staff),0(wheel),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin)\n"
+"uid=501(runner) gid=20(staff) groups=20(staff),0(wheel),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),264(_webdeveloper),399(com.apple.access_ssh),701(com.apple.sharepoint.g …
```
> uucore/entries: fix `getgrouplist` wrapper to handle a bug in macOS's `getgrouplist` implementation

- src/uu/sort/src/ext_sort.rs
- src/uu/sort/src/sort.rs
- src/uucore/src/lib/mods/panic.rs
- tests/by-util/test_sort.rs
By calling `unwrap` we get a panic instead of an abort, and since we
mute sigpipe panics for all utilites, no error message will be printed.
> sort: avoid sigpipe errors 

- src/uu/touch/src/touch.rs
- tests/by-util/test_touch.rs
parse `@<seconds since epoch>` as a valid date.
In the long term we should move the date parsing logic to `core`, because there's something similar in `date`. `date` however uses the `chrono` crate, while `touch` uses `time 0.1`, so unifying that would probably require more work.
GNU also supports all kinds of date inputs, `last year tomorrow yesterday yesterday 10 seconds ago now today this friday this day` is perfectly valid for example. (See also [GNU's documentation](https://www.gnu.org/software/coreutils/manual/html_node/Date-input-formats.html#Date-input-formats))
> touch: support @<timestamp> date format

- src/uu/cp/src/cp.rs
- tests/by-util/test_cp.rs
Closes #2423.
When we try to copy a symlink, don't dereference it (unless dereference is enabled). When recursively copying, dereference is disabled by default.
> cp: improve symlink handling

- src/uu/ls/src/ls.rs
Related to #1872 
> * [ ]  Control characters
>   * [ ]  Set default to `-q` if the output is a terminal.
> ls: set show-control-char if stdout is terminal

- src/uu/cut/src/cut.rs
- tests/by-util/test_cut.rs
fix for #2424
GNU's `cut` supports `-d=` to set the delimiter to `=`.
Clap parsing is limited in this situation, [see](https://github.com/uutils/coreutils/issues/2424#issuecomment-863825242
).
Since clap parsing handles `-d=` as delimiter explicitly set to `""` we can use this as basis for a simple workaround. 
The downside is that `uu_cut` loses the ability to handle empty delimiters.
I don't know how often this is used, or if it is useful at all, but I consider this an acceptable tradeoff.
GNU's behaviour for an empty delimiter is to echo the input.
Other alternatives for a workaround to fix #2424 could be:
1. parse/regex `args` before calling `App::get_matches()`
2. set `Arg::with_name(options::DELIMITER).empty_values(false)` use `App::get_matches_safe()`, handle the error manually and …
> cut: fix `-d=` (#2424)

- src/uu/ln/src/ln.rs
- tests/by-util/test_ln.rs
Instead of returning an empty `Path` we should return a path to the current directory (`.`)
> ln: don't return an empty path in `relative_path`

- src/uu/du/src/du.rs
- tests/by-util/test_du.rs
- tests/fixtures/du/subdir/deeper/deeper_dir/deeper_words.txt
From gnu:
```
-L, --dereference
dereference all symbolic links
```
To test it we have fixture file `subdir/deeper/deeper_dir/deeper_words.txt`.
Then symlink the directory `subdir/deeper/deeper_dir` into `subdir/links/deeper_dir`.
Test the `du` against directory `subdir/links` and make sure that it returns the size of the symlinked dir.
Note: I don't have WSL to test manually.
> du: add `--dereference`

- build.rs
- src/uu/test/src/test.rs
- tests/by-util/test_test.rs
When invoked via '[' name, last argument must be ']' or we bail out with
syntax error. Then the trailing ']' is simply disregarded and processing
happens like usual.
> test: Implement [ expr ] syntax

- .github/workflows/CICD.yml
- .github/workflows/FixPR.yml
- .github/workflows/GNU.yml
- .github/workflows/GnuTests.yml
- .vscode/cspell.dictionaries/acronyms+names.wordlist.txt
- .vscode/cspell.dictionaries/jargon.wordlist.txt
- .vscode/cspell.dictionaries/workspace.wordlist.txt
- src/uucore/src/lib/lib.rs
- tests/by-util/test_cut.rs
- util/GHA-delete-GNU-workflow-logs.sh
This is a continuation of #2368.
Style warnings have been converted to errors (with instructions for repair in the error messages; see <https://github.com/rivy-t/rs.coreutils/actions/runs/953446073>). This should push contributors to fix issues earlier and rely less on maintainers to ask for changes.
BusyBox and GNU tests still produce soft warnings when any test fails (with test summaries of failed tests; see <https://github.com/rivy-t/rs.coreutils/actions/runs/953373363> for a fully successful run with only a BusyBox test failure summary).
We should ask for "no-error/no-red PRs" from contributors.
A new 'FixPR' workflow runs on any PR merge to 'master' which auto-fixes 'Cargo.lock' and code formatting, when necessary.
Suggestions for changes?
> CICD ~ refactor + add PR auto-fixes

- src/uu/more/src/more.rs
1. Fixed display when terminal resizing.
2. Now displays the unknown command entered. This also actually fixes the match. It previously matched on _everything_ even terminal resizing.
3. Some minor improvement where we initialize vector with _at least_ the minimum required size (which is the common case).
4. Fixed the choice of integer type here. Casting `u16` to `usize` is always safe. But the other way round is not. Prefer `u16` whenever possible to express the limit of terminals. AFAIK, we are always casting up in this commit.
5. Prefer using `saturating_` functions instead just `+` operator to avoid underflow and overflow.
6. When scrolling down, the scrolling should first stop at the end of the file. Scroll down again to exit the file or visit the next file.
Thanks!
Pinging …
> Improvements to `more`.

- src/uu/ls/src/ls.rs
- tests/by-util/test_ls.rs
- For dangling symlinks, errors should only be reported if
dereferencing options were passed and dereferencing was applicable to
the particular symlink
- With -i parameter, report '?' as the inode number for dangling
symlinks
- Add tests similar to dangle tests from GNU test suite
This is first step to fixing issues with dangle related tests from GNU test suite
> ls: Fix problems dealing with dangling symlinks

- src/uu/cp/src/cp.rs
- tests/by-util/test_cp.rs
Closes #2433.
Changing the default revealed some bugs, which I fixed.
> cp: default to --reflink=auto on linux and macos

- src/uu/id/src/id.rs
- tests/by-util/test_id.rs
* change of identifier names and spelling according to the suggestions in the review of #2446
> id: refactor identifiers

- .github/workflows/CICD.yml
- .github/workflows/FixPR.yml
- .vscode/cspell.dictionaries/people.wordlist.txt
This makes the dependency display more lax about network access and should stop the errors seen in the CICD/MinRustV step.
Plus, some minor housekeeping.
> Fix CICD dependency display errors

- src/uu/groups/Cargo.toml
- src/uu/groups/src/groups.rs
- tests/by-util/test_groups.rs
This passes the relevant tests for `groups` from GNU's Testsuite that currently fail on master branch.
```
============================================================================
Testsuite summary for GNU coreutils 8.32.162-4eda
============================================================================
PASS: tests/misc/groups-dash.sh
PASS: tests/misc/groups-process-all.sh
```
* add new feature to support multiple users (introduced in coreutils 8.31)
* sync help text with GNU's `groups` manpage
* add tests for everything
> groups: fixes to pass GNU's Testsuite

- .vscode/cspell.dictionaries/people.wordlist.txt
Unfortunately, `cspell` and the internal speller for VSCode have slightly different semantics for the exception word lists.
This should actually fix the spelling error; local `cspell` says all is well.
> docs ~ fix addition of 'jhscheer' to spell-checker exceptions word list

- docs/uutils.rst
This is a minor typo fix that removes a duplicated word.
> Fix typo: duplicated word

- src/uu/sort/src/check.rs
- src/uu/sort/src/chunks.rs
- src/uu/sort/src/ext_sort.rs
- src/uu/sort/src/merge.rs
- src/uu/sort/src/sort.rs
Data that was previously boxed inside the Line struct was moved to
separate vectors. Inside of each Line remains only an index that
allows to access that data.
This helps with keeping the Line struct small and therefore reduces
memory usage in most cases.
Additionally, this improves performance because one big allocation (the
vectors) are faster than many small ones (many boxes inside of each
Line). Those vectors can be reused as well, reducing the amount of
(de-)allocations.
<details>
<summary>
Some benchmarks showing improvements
</summary>
```plaintext
Benchmark #1: target/release/sort shuffled_wordlist.txt
Time (mean ± σ):      14.1 ms ±   0.4 ms    [User: 66.6 ms, System: 5.1 ms]
Range (min … max):    13.5 ms …  15.9 ms    170 runs
Benchmark #2: ./oldsort shuffled_wordlist.txt
Time …
```
> sort: separate additional data from the Line struct

- src/uu/ls/src/ls.rs
- src/uu/mkdir/src/mkdir.rs
- src/uu/mktemp/src/mktemp.rs
- src/uu/touch/src/touch.rs
- src/uucore/src/lib/lib.rs
- src/uucore/src/lib/macros.rs
- src/uucore/src/lib/mods.rs
- src/uucore/src/lib/mods/error.rs
- src/uucore_procs/src/lib.rs
- tests/by-util/test_mktemp.rs
Closes https://github.com/uutils/coreutils/issues/2336.
The full rationale behind this PR is explained in that issue.
With this PR, a typical `uumain` signature would become something like:
```rust
#[uucore_procs::gen_uumain]
fn uumain(args: impl uucore::Args) -> UResult<()>
```
Where `UResult` is roughly:
```rust
pub type UResult<T> = Result<T, UError>;
enum UError {
Common(UCommonError),
Custom(Box<dyn UCustomError),
}
```
`UCommonError` is an enum containing errors that appear across multiple utils and provides default messages and exit codes. `UCustomError` is a trait that extends `Error` and requires a `code` method that returns the exit code for the error. The `Display` trait (required by `Error`) is used for printing the error message.
Additionally, `UResult` implements 2 methods: …
> Improve error handling with `UResult`

- src/uu/install/src/install.rs
- src/uucore/src/lib/mods/backup_control.rs
- tests/by-util/test_install.rs
Implements the `-b`, `--backup` and `-S` options for the `install` utility to perform backups of existing files before overwriting. Modify the `--backup` argument to take an optional argument only if the argument is separated by an equals sign ("=") from the command-line option (in compliance with the GNU utils).
Make use of `print!` rather than `print_error!` for verbose outputs.
Add tests to verify that the command line options work as expected.
> install: implement --backup, -b and -S

- src/uu/du/src/du.rs
- tests/by-util/test_du.rs
From gnu help:
```
--inodes          list inode usage information instead of block usage
```
> du: add `--inodes`

- src/uucore/src/lib/macros.rs
- src/uucore/src/lib/mods/error.rs
- src/uucore_procs/src/lib.rs
Adds support for the `"Try {utilname} --help for more information string."` to `UError` through a `usage` method. I also added `UUsageError`, which is identical to `USimpleError` but shows the usage string.
> uucore: add usage errors

- src/uu/ls/src/ls.rs
Only refactors the `options` module and a bunch of long strings as opposed to full refactor here https://github.com/uutils/coreutils/pull/2434
Signed-off-by: Hanif Bin Ariffin <hanif.ariffin.4326@gmail.com>
> ls: Refactored options and other long constants to fix formatting

- src/uu/arch/src/arch.rs
- src/uu/cat/src/cat.rs
- src/uu/csplit/src/csplit_error.rs
- src/uu/ls/src/ls.rs
- src/uu/mkdir/src/mkdir.rs
- src/uu/mktemp/src/mktemp.rs
- src/uu/touch/src/touch.rs
- src/uu/wc/src/wc.rs
- src/uucore/src/lib/features/encoding.rs
Fails with:
```
error: use of irregular braces for `write!` macro
--> src/uucore/src/lib/features/encoding.rs:19:17
|
19 | #[derive(Debug, Error)]
|                 ^^^^^
|
= note: `-D clippy::nonstandard-macro-braces` implied by `-D warnings`
help: consider writing `Error`
--> src/uucore/src/lib/features/encoding.rs:19:17
|
19 | #[derive(Debug, Error)]
|                 ^^^^^
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#nonstandard_macro_braces
= note: this error originates in the derive macro `Error` (in Nightly builds, run with -Z macro-backtrace for more info)
```
> silent buggy clippy warning

- src/uu/sort/src/sort.rs
- tests/by-util/test_sort.rs
This makes it so that `sort -k 1 file` treats `file` as the input file
and not the second key.
> sort: make -k only take one argument per flag

- GNUmakefile
- src/uu/test/src/test.rs
- tests/by-util/test_test.rs
Closes #2420.
This installs `test` as `[` as well. When `test` is called with a binary name that ends with `[`, it changes its behavior a bit.
I would rather add `[` as its own utility instead of changing the behavior of `test` based on its binary name,
but I ran into problems trying to do that because `[` is not a valid crate/feature name. Working around it in build.rs and in GNUmakefile adds complexity and feels easy to get wrong... In any case we can't convince cargo to create a binary called `[`, which we can't work around if `uutils` is installed via `cargo install`.
There are plans for cargo to [support creating arbitrarily named binaries](https://github.com/rust-lang/cargo/issues/1706), which would mean we'd only have to work around the restriction for the feature name.
Maybe we …
> [: install test as [ as well

- tests/by-util/test_du.rs
- tests/by-util/test_groups.rs
- tests/by-util/test_id.rs
- tests/by-util/test_pinky.rs
- tests/by-util/test_stat.rs
- tests/by-util/test_who.rs
- tests/by-util/test_whoami.rs
- tests/common/macros.rs
- tests/common/util.rs
* move fn expected_result to common/util.rs
* move fn check_coreutil_version to common/util.rs
* move fn whoami to common/util.rs
* move macro unwrap_or_return to common/macros.rs
* add documentation
* add tests
> tests/common: refactor to reduce duplicate code

- tests/by-util/test_du.rs
The `test_du_bytes` testcase for the `du --bytes` command is written to perform
a dynamic comparison on linux hosts, i.e. it compares the output of the command
to that of the hosts `du` from the GNU coreutils.
Previously the test was written such that it would *first* perform the dynamic
comparison, and *after that* continue to a static comparison which may fail for
specific hosts that have a filesystem different from what the test expects.
This patch excludes linux hosts from the static comparison to ensure the test
performs only the dynamic comparison.
> test: du: Skip nondynamic comparison on linux for test_du_bytes

- src/uucore_procs/Cargo.toml
Fixes
```
cargo build
Compiling uucore_procs v0.0.5 (/home/terts/Programming/coreutils/src/uucore_procs)
error[E0432]: unresolved import `syn::ItemFn`
--> src/uucore_procs/src/lib.rs:7:36
|
7 | use syn::{self, parse_macro_input, ItemFn};
|                                    ^^^^^^ no `ItemFn` in the root
error: aborting due to previous error
For more information about this error, try `rustc --explain E0432`.
error: could not compile `uucore_procs`
To learn more, run the command again with --verbose.
```
when building for example `ls` individually.
> uucore_procs: add full feature flag to syn

- src/uu/tr/src/tr.rs
- tests/by-util/test_tr.rs
```shell
coreutils on  master [$?] is 📦 v0.0.6 via 🦀 v1.53.0 
❯ echo "test" | ./target/debug/coreutils tr 'f' 'f' 'f'
test
coreutils on  master [$?] is 📦 v0.0.6 via 🦀 v1.53.0 
❯ echo "hello" | tr 'f' 'f' 'f'
tr: extra operand ‘f’
Try 'tr --help' for more information.
```
Signed-off-by: Hanif Bin Ariffin <hanif.ariffin.4326@gmail.com>
> `tr` should error out when if user provides more than 2 sets

- CONTRIBUTING.md
Document existing practices around licensing, including making it clear
not to copy/reference GPL code.
Intended to resolve #1994.
> CONTRIBUTING: Add licensing details (#1994)

- tests/by-util/test_du.rs
> test_du: ignore unsupported --time=birth

- CONTRIBUTING.md
Add a note the licensing section, stating that references using the
Apache License are acceptable on a case-by-case basis when there is no
MIT-licensed alternative.
* Follow-up to #1994 / https://github.com/uutils/coreutils/pull/2493
* Intended to resolve issue #2086
> CONTRIBUTING: Add Apache License note (#2086)

- src/uu/arch/src/arch.rs
- src/uu/cat/src/cat.rs
- src/uu/cp/src/cp.rs
- src/uu/csplit/src/csplit_error.rs
- src/uu/dirname/src/dirname.rs
- src/uu/du/src/du.rs
- src/uu/echo/src/echo.rs
- src/uu/false/src/false.rs
- src/uu/hostid/src/hostid.rs
- src/uu/hostname/src/hostname.rs
- src/uu/kill/src/kill.rs
- src/uu/ls/src/ls.rs
- src/uu/mkdir/src/mkdir.rs
- src/uu/mktemp/src/mktemp.rs
- src/uu/pwd/src/pwd.rs
- src/uu/sleep/src/sleep.rs
- src/uu/touch/src/touch.rs
- src/uu/true/src/true.rs
- src/uu/wc/src/wc.rs
- src/uucore/src/lib/features/encoding.rs
Reverts uutils/coreutils#2475 as https://github.com/rust-lang/rust-clippy/issues/7422 is fixed.
> Revert "silent buggy clippy warning"

- src/uu/sort/src/sort.rs
The custom usage string does not have to include the "sort\nUsage:" part,
because this part is already printed by clap.
It prevents the following duplication:
USAGE:
sort
Usage:
sort [OPTION]... [FILE]..
Now, only the following is printed:
USAGE:
sort [OPTION]... [FILE]...
> sort: remove duplication from usage string

- src/uu/sort/src/sort.rs
- tests/by-util/test_sort.rs
You can't actually pass a null byte as an argument to a program, instead we interpret `\0` as a null byte.
This is also for compatibility with gnu (gnu sort has this feature since version 5.0.91)
> sort: allow null bytes for -t

- src/uu/tac/src/tac.rs
- tests/by-util/test_tac.rs
Change the behavior of `tac` when there are no line separators in the
input. Previously, it was appending an extra line separator; this commit
prevents that from happening. The input is now writted directly to
stdout.
> tac: handle no line separators in file

- src/uu/tac/src/tac.rs
- tests/by-util/test_tac.rs
Correct the error message produced by `tac` when trying to read from a
directory. Previously if the path 'a' referred to a directory, then
running `tac a` would produce the error message
dir: read error: Invalid argument
after this commit it produces
a: read error: Invalid argument
which matches GNU `tac`.
> tac: correct error message when reading from directory

- src/uu/expand/src/expand.rs
- tests/by-util/test_expand.rs
Add support for
* space-separated list of tab stops, like `--tabs="2 4 6"`,
* mixed comma- and space-separated lists, like `--tabs="2,4 6"`,
* the slash specifier in the last tab stop, like `--tabs=1,/5`,
* the plus specifier in the last tab stop, like `--tabs=1,+5`.
> expand: expand support for --tabs arguments

- src/uu/sort/src/check.rs
- src/uu/sort/src/ext_sort.rs
- src/uu/sort/src/merge.rs
- src/uu/sort/src/sort.rs
- tests/by-util/test_sort.rs
In such cases we have to create a temporary copy of the input file to prevent
overwriting the input with the output. This only affects merge sort, because it
is the only mode where we start writing to the output before having read all inputs.
I also included fixes for other bugs I encountered.
> sort: handle cases where the output file is also an input file

- tests/common/util.rs
Change the argument names in
* `AtPath::hard_link()`,
* `AtPath::symlink_file()`, and
* `AtPath::symlink_dir()`,
from `src` and `dest` to `original` and `link` to match the arguments of
the corresponding functions from the Rust standard library. For example,
see `std::os::unix::fs::symlink()`.
This is an improvement because (1) it matches the corresponding standard library convention and (2) `src` and `dest` were the reverse of what I would expect.
> tests: better arg names in link helper functions

- src/uu/tac/src/tac.rs
- tests/by-util/test_tac.rs
Support the null character `\0` as a line separator to match the behavior of GNU tac.
> tac: support null separator (-s "")

- util/build-gnu.sh
Gnu checks before testing a utility whether that utility was actually built.
It thinks `arch` was not built, even though it was.
This patch does not convince gnu that `arch` was built (I wasn't able to figure that out),
but instead comments out the check in `init.cfg` when running `build-gnu.sh`.
> maint: enable gnu test for arch

- src/uu/chown/src/chown.rs
For some reasons this test is not run on CI, so nobody noticed it was broken.
> chown: fix unit test

- .vscode/cspell.dictionaries/shell.wordlist.txt
- .vscode/cspell.dictionaries/workspace.wordlist.txt
- Cargo.lock
- Cargo.toml
- GNUmakefile
- README.md
- src/uu/chcon/Cargo.toml
- src/uu/chcon/src/chcon.rs
- src/uu/chcon/src/main.rs
- tests/by-util/test_chcon.rs
The ToDo list was updated to mark `chcon` as done.
Building and testing `chcon` requires enabling the `feat_selinux` feature. If `make` is used for building, then please specify `SELINUX_ENABLED=1` if building and testing on a system where SELinux is not enabled.
Closes #1041
> chcon: added implementation and integration tests

- Cargo.lock
- src/uu/sort/Cargo.toml
- src/uu/sort/src/ext_sort.rs
- src/uu/sort/src/merge.rs
- src/uu/sort/src/sort.rs
- src/uu/sort/src/tmp_dir.rs
- tests/by-util/test_sort.rs
When hitting Ctrl+C sort now deletes any temporary files. To make this easier I
created a new struct `TmpDirWrapper` that handles the creation of new temporary
files and the registration of the signal handler.
I did not add tests because I don't think the way we currently run tests allows to send signals to a running test, but I'll try to look at this again.
Closes #2294.
> sort: delete temporary files when sort is terminated

- src/uu/cat/src/cat.rs
- tests/by-util/test_cat.rs
This functionality was recently added to GNU cat, but had a bug.
This implementation will be compatible with gnu once the bug in gnu is fixed.
> cat: show `\r\n` as `^M$` when `-E` is enabled

- src/uu/od/src/od.rs
- tests/by-util/test_od.rs
The following test case read stdin instead of file:
```
echo abcdefg > file
cargo run -- od --format x1 file
```
This is because the -t/--format argument was able to absorb multiple
arguments after it. This has now been fixed, and a test case is added
to ensure it will not happen again.
> od: fix reading from file while supplying a format argument

- src/uu/factor/src/cli.rs
- tests/by-util/test_factor.rs
This makes it possible to execute multiple `factor` instances that write
to the same output in parallel, without having them interfere.
> factor: prevent writing incomplete lines

- .github/workflows/GnuTests.yml
- util/compare_gnu_result.py
Add a script to compare the results from a current run against the last result from the `master` branch.
If the results change then an annotation will be added showing the change in pass, fail, error and skip numbers.
If the number of passing tests goes down then the run will be failed.
This PR shows a reduction of 2 passing tests because it is based on `54f4c8ff` and 2 new tests have started passing in newer commits.
Fixes #2287
> Add step to GnuTest workflow to compare results against master

- tests/by-util/test_pr.rs
Since some tests run multiple commands, we have to re-calculate the
expected result for every run.
This is because the expected results depend on file timestamps, but the
files are re-created for every new TestScenario.
> pr: reduce test flakiness

- Cargo.lock
- Cargo.toml
- src/uu/chcon/Cargo.toml
- src/uu/chcon/src/chcon.rs
- src/uu/chcon/src/errors.rs
- src/uu/chcon/src/fts.rs
- src/uu/id/Cargo.toml
- src/uu/id/src/id.rs
This refactors the code of `chcon` in order to reduce the number of `unsafe` blocks and keep them isolated.
After this refactoring, `chcon` no longer depends directly on the `selinux-sys` crate.
Most remaining `unsafe` blocks relate to direct usage of `fts-sys` APIs. This usage is currently necessary in order to keep the behavior of our `chcon` similar to its GNU implementation.
> chcon: reduce the number of unsafe blocks.

- src/uu/chown/src/chown.rs
- src/uu/df/src/df.rs
- src/uu/dirname/src/dirname.rs
- src/uu/du/src/du.rs
- src/uu/false/src/false.rs
- src/uu/id/src/id.rs
- src/uu/install/src/install.rs
- src/uu/ln/src/ln.rs
- src/uu/ls/src/ls.rs
- src/uu/mktemp/src/mktemp.rs
- src/uu/sort/src/sort.rs
- src/uu/touch/src/touch.rs
- src/uucore/src/lib/mods/error.rs
On the current master branch, there is a distinction between `UCommonError` and `UCustomError`. The reason for this was to allow convenient conversion from common to custom errors. However, this makes the implementation quite complicated. This PR therefore removes that distinction with the following changes:
- The `UError` and `UCommonError` enums are removed.
- The `UCustomError` trait is renamed to `UError`.
- `UResult<T>` is now defined as `Result<T, Box<dyn UError>>`.
Additionally, the `new` methods for `USimpleError` and `UUsageError` also take `Into<String>` (thanks for the suggestion @miDeb) for the message, which allows `&str`s to be passed to them.
This PR also fixes the issue in https://github.com/uutils/coreutils/pull/2561
> `uucore`: simpler `UResult` and `UError`

- src/uu/cp/src/cp.rs
- src/uu/ln/src/ln.rs
- src/uu/readlink/src/readlink.rs
- src/uu/realpath/src/realpath.rs
- src/uu/relpath/src/relpath.rs
- src/uucore/src/lib/features/fs.rs
- tests/by-util/test_readlink.rs
- tests/by-util/test_realpath.rs
This adds the 'Physical Mode' and 'Logical Mode' switches to realpath, which control when symlinks are resolved.
For other utilities that use the `canonicalize` function I have preserved the current behaviour.
> Add Physical mode to realpath

- src/uu/wc/src/wc.rs
This fixes a lint error in the CI builds.
> wc: fix collapsible match clippy warning

- .vscode/cspell.dictionaries/shell.wordlist.txt
- .vscode/cspell.dictionaries/workspace.wordlist.txt
- Cargo.lock
- Cargo.toml
- GNUmakefile
- README.md
- src/uu/runcon/Cargo.toml
- src/uu/runcon/src/errors.rs
- src/uu/runcon/src/main.rs
- src/uu/runcon/src/runcon.rs
- tests/by-util/test_runcon.rs
Added implementation and tests for the `runcon` command.
For reference: [Supporting-SELinux-in-the-coreutils](https://github.com/uutils/coreutils/wiki/Supporting-SELinux-in-the-coreutils).
The following testing tasks are still pending for this command:
I checked this manually by comparing the operation of the GNU implementation with our implementation through strace. I hope we can find a way to check this automatically instead.
All `runcon` tests succeed on a virtual machine with SELinux enabled:
```
$ cargo test --features=feat_selinux -- test_runcon::
Finished test [unoptimized + debuginfo] target(s) in 0.31s
Running unittests (target/debug/deps/coreutils-2df32bef2901c472)
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s …
```
> runcon: added implementation and tests.

- src/uu/basename/src/basename.rs
- tests/by-util/test_basename.rs
Fix an issue where `basename` would print the empty path when provided
an input comprising only slashes (for example, "/" or "//" or
"///"). Now it correctly prints the path "/".
> basename: handle paths comprising only slashes

- src/uu/sort/src/ext_sort.rs
- src/uu/sort/src/merge.rs
- src/uu/sort/src/tmp_dir.rs
Move the creation of temporary files into next_file so that it happens
while the lock is taken.
Previously, only the computation of the new file path happened while
the lock was taken, while the creation happened later.
I saw this test failing _sometimes_ in Ci, but I was only able to reproduce _a_ race by inserting `sleep`s in the right places, so I'm not _entirely_ sure this is why CI was failing. Maybe there's another problem too.
> sort: prevent race when deleting files

- src/uu/cat/src/splice.rs
- src/uu/wc/src/count_bytes.rs
- tests/by-util/test_cat.rs
[`nix::unistd::pipe`](https://docs.rs/nix/0.22.1/nix/unistd/fn.pipe.html) returns `RawFd`s which have to be closed at some point, otherwise they are leaked. Wrapping them in `File`s does the trick.
The leaked file descriptors can be observed by running `uucat /dev/null /dev/null /dev/null -` in one terminal (the `-` ensures it doesn't exit immediately) and then running `lsof -p $(pidof uucat)` in another.
It's possible to implement this without the `unsafe` keyword by writing a wrapper that calls [`nix::unistd::close`](https://docs.rs/nix/0.22.1/nix/unistd/fn.close.html) when it's dropped, but that function is technically also unsafe and probably will be marked as such in the future, so it's better to be upfront. See nix-rust/nix#1421.
> Close file descriptors of pipes after use

- Cargo.lock
- src/uu/tac/Cargo.toml
- src/uu/tac/src/tac.rs
- tests/by-util/test_tac.rs
Fix a bug in `tac` where multi-character line separators would cause
incorrect behavior when there was overlap between candidate matches in
the input string. This commit adds a dependency on `memchr` in order to
use the `memchr::memmem::rfind_iter()` function to scan for
non-overlapping instances of the specified line separator characters,
scanning from right to left.
Fixes #2580.
> tac: support multi-character line separator with possible overlaps

- .github/workflows/CICD.yml
- .pre-commit-config.yaml
- src/uu/csplit/src/csplit.rs
- src/uu/dd/src/parseargs/unit_tests.rs
- src/uu/factor/src/table.rs
- src/uu/head/src/head.rs
- src/uu/od/src/inputdecoder.rs
- src/uu/od/src/mockstream.rs
- src/uu/od/src/multifilereader.rs
- src/uu/od/src/parse_formats.rs
- src/uu/od/src/prn_float.rs
- src/uu/split/src/split.rs
- src/uucore/src/lib/features/ringbuffer.rs
These lints were cluttering up the "problems" tab in my VS Code. `--workspace` fixes the disparity.
I'm not sure why only tests were affected.
> Run clippy on the full workspace

- Cargo.lock
- src/uu/chgrp/Cargo.toml
- src/uu/chgrp/src/chgrp.rs
- src/uu/chown/Cargo.toml
- src/uu/chown/src/chown.rs
- src/uu/install/src/install.rs
- src/uucore/Cargo.toml
- src/uucore/src/lib/features/perms.rs
- tests/by-util/test_chgrp.rs
chgrp does mostly the same as chown.
By making chown a bit more configurable we can reuse its code for chgrp.
Closes #2565.
Depends on #2471 for correct error messages.
> chgrp/chown: move common code to `uucore`

- Cargo.lock
- src/uu/hashsum/Cargo.toml
- src/uu/hashsum/src/hashsum.rs
Remove a copy operation of the input buffer being read for digest when
reading in text mode on Windows. Previously, the code was copying the
buffer to a completely new `Vec`, replacing "\r\n" with "\n". Instead,
the code now scans for the indices at which each "\r\n" occurs in the
input buffer and inputs into the digest only the characters before the
"\r" and after it.
This issue was referenced in https://github.com/uutils/coreutils/issues/2295#issuecomment-850627402 :
> If we try to parse in windows text mode (whatever that is - there are no tests for it and I have no idea why we want to modify the input file before hashing), there is a second vector used. That allocation is not used in other cases, we should make sure it's only allocated when actually used.
> hashsum: don't copy input buffer on Windows

- src/uu/base32/src/base_common.rs
- src/uu/csplit/src/csplit.rs
- src/uu/expand/src/expand.rs
- src/uu/fold/src/fold.rs
- src/uu/hashsum/src/hashsum.rs
- src/uu/ls/src/ls.rs
- src/uu/pinky/src/pinky.rs
- src/uu/seq/src/seq.rs
- src/uu/stdbuf/src/stdbuf.rs
- src/uu/timeout/src/timeout.rs
- src/uu/uname/src/uname.rs
- src/uu/unexpand/src/unexpand.rs
- src/uu/who/src/who.rs
- src/uucore/src/lib/macros.rs
Related to #2585. This PR removes the `return_if_err` and `safe_unwrap` macros and replaces them with `crash_if_err` instead.
> Unify error macros

- src/uu/cp/src/cp.rs
- src/uu/install/src/install.rs
- src/uu/ln/src/ln.rs
- src/uu/mv/src/mv.rs
- src/uucore/Cargo.toml
- src/uucore/src/lib/mods/backup_control.rs
Hello again,
this is my follow-up from #2467 (@miDeb). This PR adds:
- an `arguments` module that contains ready-to-use `clap::Arg`s for the backup-related CLI options
- A `UCustomError`-based `BackupError` enum
- A more intuitive signature to `determine_backup_mode/suffix`, which now both take a `clap::ArgMatches` and parse the options from there themselves (using what's defined in the `arguments` module)
- Updated tests (Which imo are much nicer to read)
- A **lot** of new docs so hopefully people understand what I tried to accomplish
Waiting for your feedback!
> backup_control: Streamline CLI arguments, use UError

- src/uucore/src/lib/features/fs.rs
- tests/by-util/test_realpath.rs
When we ignore failures resolving symbolic links we should keep the
latest resolution that did not fail, not the original path.
> uucore/fs: use the latest resolution that did not fail

- src/uu/seq/src/seq.rs
- tests/by-util/test_seq.rs
This change adds support to match the GNU `seq` output:
```
$ seq -0 1
-0
1
```
> seq: print negative zero at start of integer sequence

- Cargo.toml
Found out that touch wasn't compiled in what I assume in ordinary Ubuntu
Linux setup.
```
./+o+-       hbina@komputa
yyyyy- -yyyyyy+      OS: Ubuntu 20.04 focal
://+//////-yyyyyyo      Kernel: x86_64 Linux 5.12.9-051209-generic
.++ .:/++++++/-.+sss/`      Uptime: 1h 5m
.:++o:  /++++++++/:--:/-      Packages: 2241
o:+o+:++.`..```.-/oo+++++/     Shell: bash 5.0.17
.:+o:+o/.          `+sssoo+/    Resolution: 1920x1080
.++/+:+oo+o:`             /sssooo.   DE: GNOME 3.36.5
/+++//+:`oo+o               /::--:.   WM: Mutter
\+/+o+++`o++o               ++////.   WM Theme: Adwaita
.++.o+++oo+:`             /dddhhh.   GTK Theme: Yaru [GTK2/3]
.+.o+oo:.          `oddhhhh+    Icon Theme: ubuntu-mono-dark
\+.++o+o``-````.:ohdhhhhh+     Font: Cantarell 11
`:o+++ `ohhhhhhhhyo++os:      Disk: 142G / 475G …
```
> Add touch as a common core utility

- .vscode/cspell.dictionaries/jargon.wordlist.txt
- .vscode/cspell.dictionaries/workspace.wordlist.txt
- src/uu/pwd/src/pwd.rs
- tests/by-util/test_pwd.rs
- tests/common/macros.rs
`std::env::current_dir()` doesn't actually return the logical path (i.e. without resolving symlinks) on Unix, that takes extra work.
> pwd: Properly resolve logical working directory

- src/uu/seq/src/seq.rs
- tests/by-util/test_seq.rs
Fix a bug in `seq` where the number of characters needed to print the
number was computed incorrectly in some cases. This commit changes the
computation of the width to be after parsing the number instead of
before, in order to accommodate inputs like `1e3`, which requires four
digits when printing the number, not three.
> seq: compute width of numbers after parsing

- src/uu/ls/src/ls.rs
- tests/by-util/test_ls.rs
Implemented column-formating to mimic the behavior of GNU coreutils's ls 
Previously, columns from users with names / uids of different lengths would not render in a column when invoking `ls -l` causing a very disorganized and hard to read output:
```
total 8455364
drwxr-xr-x  25 root root       4096 Apr 29 14:06 .
drwxr-xr-x  25 root root       4096 Apr 29 14:06 ..
lrwxrwxrwx   1 root root          7 Sep 21  2019 bin -> usr/bin
drwxr-xr-x   4 root root       4096 Aug 21 06:47 boot
drwxr-xr-x   2 root root       4096 Sep 21  2019 cdrom
drwxr-xr-x  22 root root       5000 Aug 27 05:16 dev
drwxr-xr-x 165 root root      12288 Aug 28 12:11 etc
drwxr-xr-x   3 root root       4096 Sep 21  2019 home
d-wxrwx--t   3 root aa          0 Aug 30 02:32 hugepages
lrwxrwxrwx   1 root root         32 Oct …
```
> Proper columns for `ls -l`

- .github/workflows/CICD.yml
- src/uucore/src/lib/mods/error.rs
By always using the latest nightly rust version for code coverage we can avoid having to increment the rust version every time compilation breaks.
This has the additional effect that tests are now run against nightly rust as well, and has already revealed an issue that would have hit stable in about a week.
> CICD: use nightly rust for code coverage

- src/uu/join/src/join.rs
- tests/by-util/test_join.rs
Makes the `-o auto` option construct a format at initialization, rather
than try to handle it as a special case when printing lines. Fixes bugs
when combined with `-e`, especially when combined with `-a`.
Basic `-e` usage can be fixed by just changing https://github.com/uutils/coreutils/blob/2bd556e252fd562777cabe052a2eb811d44c3167/src/uu/join/src/join.rs#L113 to include `empty`, but once you start including unmatched lines, that's also insufficient. The new test effectively checks both of these. Also makes more of the GNU join tests pass.
> join: make autoformat actually construct a format

- .vscode/cspell.dictionaries/jargon.wordlist.txt
- .vscode/cspell.dictionaries/workspace.wordlist.txt
- Cargo.lock
- Cargo.toml
- src/uu/cp/Cargo.toml
- src/uu/cp/src/cp.rs
- src/uucore/Cargo.toml
- tests/by-util/test_cp.rs
Fix a mix-up between ownership and mode. The latter (mode / file permissions)
can also be set on windows (which however only affects the read-only flag),
while there doesn't seem to be a straight-forward way to change file ownership
on windows.
Copy the acl as well when copying the mode. This is a non-default feature and can be
enabled with `--features feat_acl`, because it doesn't seem to work on CI.
It is only available for unix so far.
Copy the SELinux context if possible.
> cp: correctly copy mode, ownership, acl and context

- src/uu/realpath/src/realpath.rs
- tests/by-util/test_realpath.rs
Adds the `-e` and `-m` options to real path.
Renames the variants of `uucore::fs::MissingHandling` to more clearly indicate their effects. This does move away from the naming scheme used for the long options exposed for tools, which can't be changed for compatibility, but is more descriptive for the developers working on the code.
> Add -e and -m to realpath

- src/uu/test/src/parser.rs
- src/uu/test/src/test.rs
- tests/by-util/test_test.rs
Handle additional edge cases arising from test(1)’s lack of reserved words.
For example, left parenthesis followed by an operator could indicate
either
* string comparison of a literal left parenthesis, e.g. `( = foo`
* parenthesized expression using an operator as a literal, e.g. `( = != foo )`
> test: handle additional parentheses edge cases

- src/uucore/src/lib/mods/error.rs
These errors still have a unique message even if the `ErrorKind` enum doesn't classify them.
Solves part of #2639. The message is now "Is a directory" instead of "No such file or directory", but that actually seems to be incorrect behavior rather than a bad error message.
> Preserve error message for "other" I/O errors

- src/uu/chown/src/chown.rs
- tests/by-util/test_chown.rs
Should fix:
gnu/tests/chown/separator.sh
> chown: support '.' as 'user.group' separator (like ':')

- src/uu/printf/src/tokenize/num_format/formatter.rs
- src/uu/sort/src/sort.rs
- tests/by-util/test_tty.rs
This one fails pretty commonly locally, though not in the CI for some reason.
(Includes ~~#2649~~ #2652, merge that one first)
> tty: Make test_stdout_fail() less flaky

- Cargo.lock
- src/uu/cat/Cargo.toml
- src/uu/cat/src/cat.rs
- src/uu/cat/src/splice.rs
- src/uu/wc/Cargo.toml
- src/uu/wc/src/count_fast.rs
- src/uu/yes/Cargo.toml
- src/uu/yes/src/splice.rs
- src/uucore/Cargo.toml
- src/uucore/src/lib/features.rs
- src/uucore/src/lib/features/pipes.rs
- src/uucore/src/lib/lib.rs
`wc`, `cat` and `yes` do similar things with splicing and pipes. This unifies them somewhat and makes it easier to extend to other tools in the future.
> Move common pipe and splice functions into uucore

- src/uu/wc/src/wc.rs
This pull request removes mutability from the `min_width` parameter to the `print_stats()` function in `wc`.
> wc: remove mutable min_width parameter

- tests/common/util.rs
This fixes an issue on macOS/bsd where multiple calls
to `host_name_for` each added a prefix 'g'.
The issue led to some tests being skipped because `util_name` was
renamed to e.g. "ggid" instead of "gid".
> tests/common: make call to `host_name_for` idempotent

- tests/by-util/test_cp.rs
warning: unused import: `std::os::unix::fs::PermissionsExt`
> Fixed a warning on freebdsd

- Cargo.lock
- src/uu/tac/Cargo.toml
- src/uu/tac/src/tac.rs
- tests/by-util/test_tac.rs
Add support for `tac --regex`, where the line separator is interpreted
as a regular expression.
> tac: add support for --regex option to tac

- src/uu/seq/src/seq.rs
- tests/by-util/test_seq.rs
Change from using `print!()` to using `stdout.write_all()` in order to allow the main function to handle broken pipe errors gracefully.
I've duplicated a helper function from `test_yes.rs` in order to write the two unit tests. A future change can refactor them.
One feature our version of `seq` does not yet support is `seq 0 inf 1`: we output `NaN` while GNU outputs `0`. I'll create a new issue for that.
> seq: use stdout.write_all() instead of print!()

- src/uu/seq/src/seq.rs
- tests/by-util/test_seq.rs
Before this change:
```
$ ./target/debug/coreutils seq " 1"
seq: invalid floating point argument: ' 1'
Try './target/debug/coreutils seq --help' for more information.
$ ./target/debug/coreutils seq "1 "
seq: invalid floating point argument: '1 '
Try './target/debug/coreutils seq --help' for more information.
```
After this change:
```
$ ./target/debug/coreutils seq " 1"
1
$ ./target/debug/coreutils seq "1 "
seq: invalid floating point argument: '1 '
Try './target/debug/coreutils seq --help' for more information.
```
GNU `seq`:
```
$ seq " 1"
1
$ seq "1 "
seq: invalid floating point argument: ‘1 ’
Try 'seq --help' for more information.
```
> seq: trim leading whitespace from inputs

- .vscode/cspell.dictionaries/workspace.wordlist.txt
- src/uu/hostname/src/hostname.rs
- Attach context to I/O errors
- Make flags override each other
- Support invalid unicode as argument
- Call `WsaCleanup()` even on panic
- Do not use deprecated `std::mem::uninitialized()`
> hostname: Cleanup

- src/uucore/src/lib/mods/panic.rs
Add "Broken pipe" to the set of panic messages used to determine whether
a panic is caused by a broken pipe error.
> uucore(panic): guard against "Broken pipe" panics

- src/uu/seq/src/seq.rs
Add the `is_first_iteration` Boolean variable to the `print_seq()`
function in order to avoid unnecessary comparisons. Specifically, before
this change, the `done_printing()` function was called twice on each
iteration of the main loop. After this change, it is only called once
per iteration.
Furthermore, this change makes the `print_seq()` function similar in
structure to the `print_seq_integers()` function.
This change was suggested in https://github.com/uutils/coreutils/pull/2615/files#r706598679
> seq: add is_first_iteration to avoid comparisons

- src/uu/seq/src/digits.rs
- src/uu/seq/src/seq.rs
- tests/by-util/test_seq.rs
This pull request fixes a bug in the behavior of `seq` with the `-w` option when printing floating point numbers with digits after the decimal point. Previously, the code assumed that the string provided on the command-line was a floating point number in decimal format, like 12.34. But the command-line argument might be a floating point number in scientific notation, like 1e-2. This commit changes the code to compute the number of required decimal places to display in fixed-width mode after converting the command-line argument to `f64`. For example:
$ seq -w .1 1e-2 .11
0.10
0.11
> seq: correctly compute width due to decimal places

- tests/by-util/test_hashsum.rs
I extracted this from pull request #2663, since it would be nice to know whether the feature is working and whether the test is correctly implemented before trying to debug the build issues in #2663. I don't have a Windows machine so I'm relying on GitHub Actions to tell me whether this is passing.
> hashsum: add tests for Windows text mode

- src/uu/seq/src/seq.rs
- tests/by-util/test_seq.rs
Replace two loops that print leading and trailing 0s when printing a
number in fixed-width mode with a single call to `write!()` with the
appropriate formatting parameters.
Came from https://github.com/uutils/coreutils/pull/2615/files#r706599625
> seq: replace loops with a single format string

- src/uu/hashsum/src/digest.rs
- src/uu/hashsum/src/hashsum.rs
This pull request creates a `DigestWriter` struct that implements `Write` by passing bytes directly to `Digest::input()`, so that `hashsum` can use `std::io::copy()`. Using `std::io::copy()` eliminates some boilerplate code around reading and writing bytes. And defining `DigestWriter` makes it easier to add a `#[cfg(windows)]` guard around the Windows-specific replacement of "\r\n" with "\n".
> hashsum: use std::io::copy() to simplify digest

- Cargo.lock
- src/uu/whoami/Cargo.toml
- src/uu/whoami/src/platform/unix.rs
- src/uu/whoami/src/platform/windows.rs
- src/uu/whoami/src/whoami.rs
- tests/by-util/test_whoami.rs
- tests/common/util.rs
- Use modern conventions
- Restrict the scope of unsafe
- Do not use deprecated `std::mem::unitialized()`
- Do not bake unicode into design
> whoami: Cleanup

- src/uu/kill/src/kill.rs
- tests/by-util/test_kill.rs
Fixes #2645.
The origin of the problem was that `handle_obsolete` was not looking for named signals but only for numbers preceded by '-'.
- Change `handle_obsolete` to use `signal_by_name_or_value` to parse the possible signal.
- Since now the signal is already parsed return an `Option<usize>` instead of `Option<&str>` to parse later.
- Change the way to decide the pid to use from a `match` to a `if` because the tested element are actually not the same for each branch.
- Parse the signal from the `-s` argument outside of `kill` function for consistency with the "obsolete" signal case.
- Again for consistency, parse the pids outside the `kill` function.
Add two tests of the old form signal arg using the signal name instead of the number.
Bonus: add a test for the new form but with the …
> Kill with signal name

- Cargo.lock
- src/uu/hashsum/Cargo.toml
> Use non-yanked version of digest crate in hashsum

- src/uucore/src/lib/features.rs
- src/uucore/src/lib/features/fsext.rs
- src/uucore/src/lib/features/mode.rs
- src/uucore/src/lib/features/process.rs
- src/uucore/src/lib/lib.rs
- Replace some unsafe code in `fsext`
- Avoid some unnecessary copies
- Add notes about safety considerations and platform support
> uucore: Minor cleanup

- tests/common/util.rs
For the CICD on macOS, this fixes:
```
---- common::util::tests::test_check_coreutil_version stdout ----
---- common::util::tests::test_expected_result stdout ----
thread 'common::util::tests::test_expected_result' panicked at
'byte index 4 is out of bounds of `9.0`', tests/common/util.rs:1172:41
```
> common/util: fix parsing of coreutil version

- Cargo.lock
- Cargo.toml
- src/uu/ls/Cargo.toml
- src/uu/ls/src/ls.rs
- tests/by-util/test_ls.rs
This adds SELinux security context (--context/-Z) support to `uu_ls`.
Since the SELinux specific parts are  gated behind `--featues feat_selinux`, the tests don't run in the CICD and I appreciate a volunteer to run:
`cargo test test_ls_context --features feat_selinux`
on an SELinux enabled Linux distribution with libselinux headers installed (e.g. on fedora dnf install libselinux-devel).
(With this the "gnu/tests/id/no-context.sh" test now passes because it depends on `uu_ls -Z` being implemented.)
> `ls`: add support for showing SELinux context (--context/-Z)

- src/uu/basename/src/basename.rs
- src/uu/ls/src/ls.rs
- src/uu/sort/src/chunks.rs
- src/uucore/src/lib/features/mode.rs
- tests/common/util.rs
This closes #2719
I opened this as a draft because of this:
https://github.com/uutils/coreutils/blob/d72a135b42b3c6eec2de587dd80a97f681cedd2f/src/uucore/src/lib/features/mode.rs#L167-L173
I don't really see the benefit of using strip_prefix here since the prefix is already known to be there. IMO it would just add more complexity.
Once someone responds to this I will either remove the comment or implement it using strip_prefix
> uu+tests: use strip_prefix and strip_suffix

- Cargo.lock
- src/uu/factor/Cargo.toml
smallvec 1.0 and later wasn't compatible with Rust 1.33 but the minimum supported Rust version for coreutils moved on.
> factor: Update to current versions of `smallvec`

- tests/by-util/test_base32.rs
- tests/by-util/test_base64.rs
- tests/by-util/test_basename.rs
- tests/by-util/test_cp.rs
- tests/by-util/test_more.rs
- tests/by-util/test_mv.rs
- tests/by-util/test_nice.rs
- tests/by-util/test_seq.rs
- tests/by-util/test_stdbuf.rs
- tests/common/util.rs
This also opens up the possibility to implement something like `CmdResult::simple_error`, where `util_name` is implied.
Just got tired of having the duplicate "{0}: {2} Try '{1} {0} --help' for more information" everywhere so implemented this. Also didn't know whether or not to call `.fails()` inside `CmdResult::usage_error` so I didn't, since it would change less code. Maybe it should do it, not sure.
> Add CmdResult::usage_error

- src/uu/seq/src/seq.rs
- tests/by-util/test_seq.rs
Pad infinity and negative infinity values with spaces when using the
`-w` option to `seq`. This corrects the behavior of `seq` to match that
of the GNU version:
$ seq -w 1.000 inf inf | head -n 4
1.000
inf
inf
inf
Previously, it incorrectly padded with 0s instead of spaces.
> seq: correct fixed-width spacing for inf sequences

- src/uu/factor/BENCHMARKING.md
- src/uu/factor/src/numeric/gcd.rs
- minor fix for the newlines in BENCHMARKING.md
- minor test refactor to more a more common/idiomatic use of `quickcheck`
Replaces #2739.
> fix/factor ~ minor repairs to docs and tests

- src/uu/tail/src/parse.rs
- src/uu/tail/src/tail.rs
- tests/by-util/test_tail.rs
echo "a\nb" | ./target/debug/tail -1 
```
b
```
> Fix tail -<number> does not work

- src/uu/env/src/env.rs
- src/uu/printenv/src/printenv.rs
- tests/by-util/test_env.rs
env now passes all GNU tests except for `tests/misc/env-S.pl` and `tests/misc/env-signal-handler.sh`
Also related to #2464
> env+printenv: use UResult + improve compatibility

- src/uucore/src/lib/macros.rs
Documents the `macros` module with most relevant parts of the contents. "most", because:
- Some macros are used **only** by `cut` (See #2584)
- Some macros replicate almost identical functionality (See #2585)
- Other macros are used only by 2 or more utils and may thus be eliminated if the utils are adapted accordingly
I'm marking this as WIP so we can discuss it, but I'd like to have an opinion about the matters above. If all/most of these macros are eliminated, I don't need to document them. If they stay, it'd be tedious to have multiple PRs that all document different parts of the macros...
Most of the macros that I think could be eliminated have comments in this PR. I'm curious to hear what you think.
> WIP: macros: Add documentation with examples to macros

- .vscode/cspell.dictionaries/workspace.wordlist.txt
- src/uu/chown/src/chown.rs
- src/uu/id/src/id.rs
- src/uu/pinky/src/pinky.rs
- src/uucore/src/lib/features/entries.rs
- tests/by-util/test_pinky.rs
- Protect `getpwnam()` and friends with a lock. This makes the wrappers safe, they were occasionally causing segfaults before (in tests).
- Do not use unsafe `Vec` operations unnecessarily.
> uucore::entries: Fix safety issues

- util/build-gnu.sh
The URL of the GNU coreutils repo contained a typo.
> Fix typo in `utils/build-gnu.sh`

- tests/by-util/test_sort.rs
For some reasons, on windows, test_compress_fail is failing with a different
error. So, don't check the output on windows
> Try to unbreak the code coverage CI.

- src/uu/more/src/more.rs
- Add next and previous line with 'j' and 'k' keys, respectively.
- Fixed small bug where a page down near the end of an open file causes over pagination.
> more: add next-line and prev-line command.

- src/uu/more/src/more.rs
> more: use UResult

- util/build-gnu.sh
Fixes #2733
This is a minimal patch to restore idempotence of `utils/build-gnu.sh`.
* Fix regular expressions to only match when run the first time.
* Enhance the regular expression which removes duplicated "/usr/bin/" to allow a space between them (+ also considers `init.cfg`).
> Fix idempotence of `utils/build-gnu.sh`

- src/uu/seq/src/numberparse.rs
- tests/by-util/test_seq.rs
Fix a bug in which a negative decimal input would not be displayed with
the correct width in the output. Before this commit, the output was
incorrectly
$ seq -w -.1 .1 .11
-0.1
0.0
0.1
After this commit, the output is correctly
$ seq -w -.1 .1 .11
-0.1
00.0
00.1
The code was failing to take into account that the input decimal "-.1"
needs to be displayed with a leading zero, like "-0.1".
> seq: correct width for certain negative decimals

- src/uu/readlink/src/readlink.rs
See #2464.
This pull request also makes a minor change to the code: it eliminates duplicate code by moving a `match` statement up.
> readlink: return UResult from uumain() function

- src/uu/split/src/split.rs
Previously, the code was checking strings to decide which chunking strategy to use. This pull request creates a `Strategy` enum and moves all the responsibility of parsing the `Strategy` to the same time as all the other `Settings` fields are parsed.
> split: replace string checking with Strategy enum

- .github/workflows/CICD.yml
I just noticed the drop in code coverage due to mistakenly including (non-)coverage of the vendored 'nix' crate.
This fixes that oversight.
> maint/CICD ~ ignore 'vendor' for CodeCov

- src/uu/ls/src/ls.rs
- tests/by-util/test_ls.rs
Referenced as an issue as well: https://github.com/uutils/coreutils/issues/2785
- print error in the correct order by flushing the stdout buffer before printing an error
- print correct GNU error codes
- correct formatting for config.inode, and for dangling links
- correct padding for  Format::Long
- remove colors after the -> link symbol as this doesn't match GNU
- correct the major, minor #s for char devices, and correct padding
- improve speed for all metadata intensive ops by not allocating metadata unless in a Sort mode
- new tests, have struggled with how to deal with stderr, stdout ordering in a test though
- tried to implement UIoError, but am still having issues matching the formatting of GNU
> ls: Improve error handling and other improvements

- src/uu/cksum/src/cksum.rs
- src/uucore/src/lib/mods/error.rs
- tests/by-util/test_cksum.rs
Builds on the work in #2789.
This PR removes the custom error messages in `cksum` in favour of `UIoError`. It also makes it possible to create an `UIoError` from an `std::io::Error` without a `context`, which in turn makes it possible to use `?` on a function returning `io::Result` in a function returning `UResult`.
Another detail is that this would exit with code `1`, instead of `2`, since I that was the exit code that GNU seemed to give on my machine.
> `cksum`: use `UIoError`

- src/uu/ls/src/ls.rs
- tests/by-util/test_ls.rs
Fix: Don't print an initial newline when no files in base directory, with test
> ls: Fix newline when only dirs in base directory

- src/uu/ls/src/ls.rs
- tests/by-util/test_ls.rs
This PR will make `is_hidden` to use the `Metadata` that `DirEntry` has instead of retrieved with `std::fs::metadata` and `std::fs::symlink_metadata`.
With this change, the `Application Data` folder, that is symlink to hidden folder, will be hidden, that will same as `dir` behavior in cmd.
Also, `coreutils ls C:\` will not panic. (it is probably issue in `std::fs`, but I came up with this PR when I was reproducing it.)
The test from #1662 and #2441 should pass.
> ls: On Windows use metadata owned by DirEntry instead of retrieved one additionaly

- src/uu/ls/src/ls.rs
- tests/by-util/test_ls.rs
ErrorKind::PermissionDenied can occur for two error codes, errno 13 and 1.  Here, we handle the Errno 1 case which on MacOS at least occurs when we stat SIP protected files/dirs.  I'd love to know how to create such a file for a test, if anyone has any ideas.    
We also move the error printing into the md function.  This has the benefit of making sure we only print an error once, but we must pass the stdout bufwriter to the function, so it may be flushed before the error to preserve error order.
Very interested: Is there any way to 'pipe' stderr to stdout in a test so we can test the order of errors and regular output? 
Thanks.
> ls: Fix Errno 1, print errors at the md call point

- .vscode/cspell.dictionaries/jargon.wordlist.txt
- Cargo.lock
- src/uu/cat/src/cat.rs
- src/uu/cp/src/cp.rs
- src/uucore/Cargo.toml
- src/uucore/src/lib/features/fs.rs
- tests/by-util/test_cp.rs
- Refactor identical file detection into `uucore`
- Use refactored file identity detection in `cat` (fixes #2601)
- Fix edge cases in `cp` when the destination is a symlink.
I also added some `FIXME` comments to `cp` about issues I found but didn't fix in this PR.
> cp: handle edge cases when dest is a symlink 

- build.rs
- src/uu/ls/src/ls.rs
- tests/by-util/test_tee.rs
- tests/common/util.rs
Since we decided on holding off on merging https://github.com/uutils/coreutils/pull/2869, I pulled the clippy lint fixes into this PR, so they can be merged.
> Fix Rust 1.58 clippy lints

- Cargo.toml
- src/uu/stdbuf/build.rs
It turns out that `cargo publish` doesn't just create a file called `liblibstdbuf.so`, but instead something like `liblibstdbuf-1285737e7e670288.so`. With this PR, we loop through the directory until we find a file which starts with `liblibstdbuf` and ends with `.so` (or another dylib extension). This fixed https://github.com/uutils/coreutils/issues/2876 for me locally.
> `stdbuf`: fix `cargo publish` problem

- src/uu/tail/src/lines.rs
- src/uu/tail/src/tail.rs
- tests/by-util/test_tail.rs
Fix a bug where `tail` would inappropriately add a newline to the last
line of output even though the input did not end with one.
> tail: don't add trailing \n if input doesn't end with one

- tests/by-util/test_tr.rs
The test `test_tr::test_more_than_2_sets` sometimes fails randomly. For example here: https://github.com/uutils/coreutils/runs/4845185000?check_suite_focus=true
Here's my guess to why this was happening: the command exits immediately because the arguments are wrong. Therefore, there might sometimes be no time to pipe the input into the command, which results in the broken pipe error. The fix is simple: remove the pipe. I also re-enabled this test for FreeBSD.
> `tr`: fix flaky test

- src/uu/join/src/join.rs
- tests/by-util/test_join.rs
This expands the error message that is printed if either input file has
an unsorted line. Both the program name (join) and the offending line
are printed out with the message to match the behaviour of the GNU
utility.
Note: while copying the input string with `clone` may look bad, this makes the `Sep::Line` arm have the same performance as the rest of the match arms (which clone the input line in their calls to `Vec::from`).
> join: print unsorted line in error message

- src/uu/expr/src/syntax_tree.rs
```
warning: this URL is not a hyperlink
```
> expr: Fix a warning in the doc generation

- src/uu/tail/src/tail.rs
- tests/by-util/test_tail.rs
This pull request fixes a bug when getting all but the first NUM lines or bytes of a file via `tail -n +NUM <file>` or `tail -c +NUM <file>`. The bug only existed when a file is given as an argument; it did not exist when the input data came from stdin. I added tests to cover this use case as well.
> tail: fix a bug in tail [ -n | -c ] +NUM <file>

- util/build-gnu.sh
Add the `g` flag to one of the regular expression substitutions in
`util/build-gnu.sh` so that all instances of `printf` are replaced
with `/usr/bin/printf` in `tests/dd/ascii.sh` instead of just one
instance per line.
> util: replace all instances of printf in tests/dd/ascii.sh

- src/uu/tail/src/tail.rs
- tests/by-util/test_tail.rs
- tests/common/util.rs
Fix a bug where `tail -f` would terminate with an error due to failing
to parse a UTF-8 string from a sequence of bytes read from the
followed file. This commit replaces the call to `BufRead::read_line()`
with a call to `BufRead::read_until()` so that any sequence of bytes
regardless of encoding can be read.
Fixes #1050.
> tail: don't error when following non-UTF-8 data

- .github/workflows/FixPR.yml
- .github/workflows/GnuTests.yml
- util/compare_gnu_result.py
This is just a shot in the dark...does this have anything to do with the strange GNU test comparison results recently? I notice that the default branch name has changed to "main" somewhat recently.
> ci: update default branch to "main" in workflows

- src/uu/dd/src/parseargs.rs
- src/uu/dd/src/parseargs/unit_tests.rs
- tests/by-util/test_dd.rs
Update `dd` so that the conversion `conv=ascii` implies `conv=unblock`
and, symmetrically, the conversion `conv=ebcdic` implies `conv=block`.
> dd: block/unblock on ebcdic/ascii conversions

- src/uu/dd/src/dd.rs
- tests/by-util/test_dd.rs
Correct the behavior of `dd` with the `status=noxfer` option. Before
this commit, the status output was entirely suppressed (as happens
with `status=none`). This was incorrect behavior. After this commit,
the input/output counts are printed to stderr as expected.
For example,
$ printf "" | dd status=noxfer
0+0 records in
This commit also updates a unit test that was enforcing the wrong
behavior.
> dd: correct behavior when status=noxfer

- src/uu/seq/Cargo.toml
- src/uu/seq/src/seq.rs
- tests/by-util/test_seq.rs
Add support for the `-f FORMAT` option to `seq`. This option instructs
the program to render each value in the generated sequence using a
given `printf`-style floating point format. For example,
$ seq -f %.2f 0.0 0.1 0.5
0.00
0.10
0.20
0.30
0.40
0.50
Fixes issue #2616.
This will cause GNU tests `fmt-1` through `fmt-5` in `tests/misc/seq.pl`.
> seq: implement -f FORMAT option

- GNUmakefile
There is an issue with the `make clean` command that it only removes the artifacts generated with the profile that it's been passed, i.e. by default only removes `target/debug`. This leads to confusion if someone uses `make install` (which implies building with release) and then tries to clean the directory. So I changed it to use `cargo clean`, which is probably closer to the expected behaviour.
This issue came up here: https://github.com/uutils/coreutils/issues/2920#issuecomment-1022478326
> make: use "cargo clean" instead of removing the target/$profile folder

- .github/workflows/GnuTests.yml
Updates it to the next and latest release. This is necessary to pull the [fixed invalid-j test](https://github.com/coreutils/coreutils/commit/1d5dbb82030a2ca7aef606d36a9d04863240c7a8) that will, once all the outstanding join PRs get merged, allow join to pass all its GNU tests (#2634). Seems to make some other tests fail, so those might require more investigation, but presumably aren't because of bugs introduced in the GNU repo.
> update GNU coreutils version in GnuTests workflow

- src/uu/truncate/src/truncate.rs
- tests/by-util/test_truncate.rs
Fix the behavior of truncate when given a non-existent file so that it
correctly creates the file before truncating it (unless the
`--no-create` option is also given).
This should make one of the GNU tests pass (`tests/misc/truncate-no-create-missing.sh`).
> truncate: create non-existent file by default

- .vscode/cspell.dictionaries/jargon.wordlist.txt
- src/uu/wc/src/count_fast.rs
- tests/by-util/test_wc.rs
Fixes https://github.com/uutils/coreutils/issues/2933
For these files from pseudo-filesystems, the size was reported as 0, even though it wasn't. So with this PR we just do a normal count if the size is 0. This is a negligible performance hit, because files that are actually empty are, well, empty, so reading them won't take long.
> wc: fix counting files from pseudo-filesystem

- src/uu/truncate/src/truncate.rs
- tests/by-util/test_truncate.rs
This pull request adds an error for division by zero. Previously, running `truncate -s /0 file` or `-s %0` would panic due to division by zero. After this change, it writes an error message "division by zero" to stderr and terminates with an error code.
The first commit in this pull request is a refactor to allow us to return the division by zero `USimpleError` in the right place. It was not possible before due to the containing function returning `std::io::Result` instead `UResult`.
This should cause the GNU test `tests/misc/truncate-relative/sh` to pass.
> truncate: add a division by zero error

- src/uu/seq/src/error.rs
- tests/by-util/test_seq.rs
Change a word in the error message displayed when an increment value
of 0 is provided to `seq`. This commit changes the message from "Zero
increment argument" to "Zero increment value" to match the GNU `seq`
error message.
This fixes the GNU tests `inc-zero-1` through `inc-zero-4` in the `tests/misc/seq.pl` file. After this change, the only remaining test failures in that file have to do with format strings provided to `-f`.
> seq: correct error message for zero increment

- README.md
This PR updates the README a little bit.
- I added a section on documentation linking to both user and developer documentation
- I rewrote the "why?" section.
- I felt that it was focused too much on *other* projects than uutils. So I removed the references to those.
- I also removed the reference to C because we don't have to bash C to like Rust.
- Finally, I removed the "and this is as good a way as any to try and learn it.", because I think we all know Rust by now (even though there's always more to learn 😄 )
- However, I don't think what I wrote now is perfect, so feedback is welcome.
- I also restructured a bit and changed some headings, but I could revert this change if you prefer.
Ultimately, I'd like the README to be much shorter and focused on users instead of developers. For …
> README: reference the docs & rewrite why section

- src/uu/truncate/src/truncate.rs
- tests/by-util/test_truncate.rs
Prevent usize underflow when reducing the size of a file by more than
its current size. For example, if `f` is a file with 3 bytes, then
truncate -s-5 f
will now set the size of the file to 0 instead of causing a panic.
This change should cause the GNU test `tests/misc/truncate-overflow.sh` to pass.
> truncate: prevent underflow when reducing size

- src/uu/dd/src/dd.rs
- tests/by-util/test_dd.rs
Add support for the `seek=N` argument when the destination is stdout
and not a file. Previously, the argument was ignored when writing to
stdout.
> dd: support seek=N when destination is stdout

- src/uu/head/src/head.rs
Use `show!()` and `USimpleError` to handle I/O errors instead of using
custom code.
> head: use uucore error handling instead of custom

- src/uu/truncate/src/truncate.rs
- tests/by-util/test_truncate.rs
Improve the error message that gets printed when a directory does not
exist. After this commit, the error message is
truncate: cannot open '{file}' for writing: No such file or directory
where `{file}` is the name of a file in a directory that does not
exist.
> truncate: better error msg when dir does not exist

- README.md
Resolves #2955. The previous Developer Documentation link led to a 404 page. I've updated it to point to https://uutils.github.io/coreutils-docs/dev/coreutils/.
> README: Update link for Developer Documentation

- src/uu/tail/src/lines.rs
- src/uu/tail/src/tail.rs
- tests/by-util/test_tail.rs
Support `-z` option when the input is not a seekable file. Previously,
the option was accepted by the argument parser, but it was being
ignored by the application logic.
> tail: support zero-terminated lines in streams

- src/uu/cp/src/cp.rs
- tests/by-util/test_cp.rs
Fixes #2959 by propagating errors from `preserve_hardlinks()` instead of unwrapping them. On Unix platforms, `preserve_hardlinks()` returns an Error if the file specified by `source` does not exist. This was previously causing `cp -a abc xyz` to panic on Unix if there was no file called `abc`. This problem did not occur on Windows.
This PR also slightly changes the formatting of the original error to match GNU's output.
> Don't panic when calling cp -a with a nonexistent file

- src/uu/split/src/split.rs
Create a `Settings::from` method that converts a `clap::ArgMatches`
instance into a `Settings` instance. This eliminates the unnecessary
use of a mutable variable when initializing the settings.
This does not change the behavior of `split`, is just a re-organization of the code.
> split: add a method to convert ArgMatches to Settings

- GNUmakefile
Creating this directory is no longer necessary and resulted in an error on my machine.
> make: no longer create INSTALLDIR_MAN

- .github/workflows/CICD.yml
The goal is to use https://github.com/uutils/coreutils-tracking to graph the evolution
> Run the release builds and store the size

- src/uu/split/src/filenames.rs
- src/uu/split/src/number.rs
- src/uu/split/src/split.rs
This pull request replaces the `FilenameFactory` introduced in pull request #2859 with `FilenameIterator` and calls to `FilenameFactory::make()` with calls to `FilenameIterator::next()`. We did not need the fully generality of being able to produce the filename for an arbitrary chunk index. Instead we need only iterate over filenames one after another. This allows for a less mathematically dense algorithm that is easier to understand and maintain. Furthermore, it can be connected to some familiar concepts from the representation of numbers as a sequence of digits.
The most important part of this code is in the `FixedWidthNumber::increment()` and `DynamicWidthNumber::increment()` methods, and in the `Display` implementation for each of those structs.
This does not change the behavior of …
> split: use iterator to produce filenames

- Cargo.lock
- src/uu/hashsum/Cargo.toml
- src/uu/hashsum/src/digest.rs
This gives a speedup of ~5x for some algorithms:
Old version:
```bash
$ time target/release/coreutils sha256sum ~/Downloads/ideaIC-2021.3.tar.gz 
de44097f00f4f9c48cf5abc2fab58c6436a4345f00f83ae7a75734af177e3077  /home/master/Downloads/ideaIC-2021.3.tar.gz
real	0m2,669s
user	0m2,576s
sys	0m0,092s
```
New version:
```bash
$ time target/release/coreutils sha256sum ~/Downloads/ideaIC-2021.3.tar.gz
de44097f00f4f9c48cf5abc2fab58c6436a4345f00f83ae7a75734af177e3077  /home/master/Downloads/ideaIC-2021.3.tar.gz
real	0m0,420s
user	0m0,348s
sys	0m0,072s
```
> Updated sha libraries

- .vscode/extensions.json
As discussed in uutils/coreutils#3017, only `rust-analyzer` should be recommended. Fixes uutils/coreutils#3017.
> Only recommend rust-analyzer
