uutils/coreutils

src/split/README.md, src/split/split.rs
Added -C flag and printing of created file names when --verbose flag is given.
Also, multiplier suffixes work now.
=> Split additional flags

src/chroot/chroot.rs, src/comm/comm.rs, src/common/c_types.rs, src/hashsum/hashsum.rs, src/hostname/hostname.rs, src/logname/logname.rs, src/paste/paste.rs, src/shuf/shuf.rs, src/split/split.rs, src/sum/sum.rs, src/sync/sync.rs, src/tee/tee.rs, src/tty/tty.rs, src/uname/uname.rs, src/users/users.rs
This fixes some more utils.
Still broken:
base64 chmod chroot cut du fmt ~~hashsum~~ id mkfifo nice nl nohup realpath relpath sort split tee test touch tr tsort unexpand uptime users whoami
=> Partially fix build with rust master

Makefile, README.md, src/readlink/readlink.rs
=> Implement readlink

src/yes/yes.rs
Mostly avoid copying where not needed. In general, would you like cleanups like this?
=> Cleanup `yes`

src/sync/sync.rs
* Use slicing syntax.
* Don't unnecessarily use the match binding syntax.
=> Cleanup sync.

src/wc/wc.rs
This is actually a bug fix and a cleanup. I can break it into two PRs if you want. `wc` could still use some functional style love but this helps a little.
=> Cleanup wc

src/stdbuf/stdbuf.rs
This is fix for issue #512 . Thanks for pointing this out!
=> stdbuf - fix issue 512

Makefile, src/fmt/parasplit.rs, src/hashsum/hashsum.rs
=> Fix build with rust nightly

src/chmod/chmod.rs, src/nl/nl.rs
=> Fix build with rust master

src/chroot/chroot.rs, src/common/c_types.rs, src/echo/echo.rs, src/split/split.rs, src/tail/tail.rs, src/tr/tr.rs
=> Fix build with alpha 2

.gitmodules, Cargo.toml, Makefile, mkmain.rs, mkuutils.rs, src/common/util.rs, src/fmt/fmt.rs, src/fmt/linebreak.rs, src/fmt/parasplit.rs, src/uutils/uutils.rs
This patch begins the work of modernizing uutils to work with 1.0-ish
Rust. In particular, it
1. Updates to the latest submodules.
2. Convert mkmain.rs, mkuutils.rs, and src/uutils/uutils.rs
to new slice syntax and use of new io, fs, and path APIs.
3. Convert src/common/util.rs to new io, fs, and path APIs.
4. Convert fmt to use new APIs.
The plan is to propagate fixes to all other submodules and thereby end up with something that builds against nightly. After that, it'd be ideal to make something that will build against beta and/or stable (i.e., not requiring anything behind feature gates).
=> fix build infrastructure ; modernize library use

src/base64/base64.rs
I updated the base64 utility to use the new I/O library and string slicing.
=> Upgrade base64 to use recent Rust nightly build.

src/echo/echo.rs
I removed unused features, switched to the new range syntax, and other
minor updates.
=> Upgrade echo to use recent Rust nightly build.

src/cat/cat.rs, test/cat.rs
This commit updates the `cat` utility as well as its testbench
to work with the latest APIs.
=> update cat, cat tests to new API

src/chmod/chmod.rs, src/chroot/chroot.rs
I've got an issue with src/common/c_types.rs.
As `os::errno` is no longer in the std lib, the project may needs to rely on something like https://github.com/carllerche/nix-rust
Otherwise I've no idea where I can get a equivalent.
(Disclaimer I'm not a C programmer)
=> chmod + chroot new io

src/chroot/chroot.rs
Fixed the `chroot` brokenness. My tests show it working correctly now.
=> working chroot implementation

src/base64/base64.rs, src/basename/basename.rs, src/cat/cat.rs, src/chroot/chroot.rs, src/echo/echo.rs, src/fmt/fmt.rs, src/fmt/parasplit.rs, src/sync/sync.rs, src/uniq/uniq.rs, src/yes/yes.rs
1. I'm trying to remove as many feature gates as possible, with the goal of eventually allowing us to build against stable rather than nightly Rust. To that end, I went through the working utils and removed whatever features were quick and easy.
2. `yes` updated
3. `uniq` updated
=> remove `#![feature()]` where possible in working utils ; fix `yes` and `uniq`

src/uname/uname.rs, src/uptime/uptime.rs, src/users/users.rs, src/wc/wc.rs, src/whoami/platform/mod.rs, src/whoami/platform/unix.rs, src/whoami/platform/windows.rs, src/whoami/whoami.rs
=> fix `whoami`, `users`, `wc`, `uptime`, `uname`

src/tsort/tsort.rs
I upgraded to the recent Rust release. I also fixed the behavior to conform to GNU `tsort`:
1. Any non-zero amount of whitespace is allowed between nodes
2. Any non-zero pair of nodes is allowed per line
=> Fix tsort.

src/head/head.rs, src/tail/tail.rs
I upgraded to the recent Rust release. The only major change was the reduction of the sleep millisecond resolution from u64 to u32 (this matches the thread::sleep_ms() method).
=> Fix head and tail.

src/dirname/dirname.rs
=> Fix dirname.

src/truncate/truncate.rs, test/truncate.rs
Just minor corrections to align with Rust's nightly build.
=> Fix truncate and related tests.

src/groups/groups.rs, src/logname/logname.rs
Minor upgrades and whitespace corrections.
=> Fix groups and logname.

src/hostid/hostid.rs, src/pwd/pwd.rs
Minor library upgrades and whitespace corrections.
=> Fix hostid and pwd.

src/printenv/printenv.rs
Minor corrections and upgrade to new env variable module.
=> Fix printenv.

.gitignore, src/tty/tty.rs
I updated tty's command-line options to conform to the GNU version. I also ignored several build directories.
=> Update tty and ignore build directories.

src/tee/tee.rs
The utility needed a substantial rewrite due to library changes and lifetime issues. I also needed to implement the MultiWriter struct since it was no longer available.
=> Rewrite tee to conform to nightly build.

src/realpath/realpath.rs, src/relpath/relpath.rs
I used the new Path/PathBuf/PathExt libraries.
=> Fix realpath and relpath.

src/link/link.rs, src/sum/sum.rs
I only updated the code to use the nightly build. No features or other major updates were made.
=> Fix link and sum.

Makefile, src/env/env.rs, test/env.rs
I updated env to use the nightly build. I also added several tests.
=> Fix env and add tests.

src/cat/cat.rs
I removed the obsolete `unsafe_destructor` feature.
=> Remove unused feature from cat.

test/seq.rs
Upgrading the code to the nightly build fixed the tests.
=> Fix broken seq tests.

src/split/split.rs
I upgraded to the nightly build.
=> Fix split.

src/basename/basename.rs
The GNU implementation first strips all trailing slashes before deleting the directory portion. This case wasn't handled.
I also rewrote the method that strips the directory to use the PathBuf methods for improved platform-independence.
=> Fix basename when trailing slashes are present.

Makefile, test/dirname.rs, test/echo.rs, test/false.rs, test/pwd.rs, test/true.rs
I added tests for dirname, echo, false, pwd, and true.
=> Add more tests.

src/pwd/pwd.rs
I removed an unused argument from the usage documentation. I also removed the redundant return calls.
=> Cleanup pwd.

deps/Cargo.toml, src/nproc/deps.mk, src/nproc/nproc.rs
Since std::os::num_cpus() was removed from the library, I added the num_cpus crate to the dependencies.
=> Fix nproc.

src/stdbuf/libstdbuf.rs, src/stdbuf/stdbuf.rs
The utility only works on Linux at the moment. Linking errors are preventing a successful build on OS X.
=> Fix stdbuf.

src/nohup/nohup.rs
I upgraded to the nightly build.
=> Fix nohup.

.travis.yml
I updated the Travis configuration so that we can see build results against 1.0 and nightly.
=> Add separate builds for stable and nightly.

test/base64.rs, test/common/util.rs, test/cp.rs, test/hashsum.rs, test/mkdir.rs, test/mv.rs, test/nl.rs, test/rm.rs, test/split.rs, test/test.rs, test/tr.rs, test/truncate.rs, test/tsort.rs, test/unexpand.rs, test/unlink.rs
Following the pattern used for the utilities, I moved helper methods and macros to a separate module.
=> Move helper methods for tests to separate module.

Makefile, src/wc/wc.rs, test/fixtures/wc/alice_in_wonderland.txt, test/fixtures/wc/lorem_ipsum.txt, test/fixtures/wc/moby_dick.txt, test/wc.rs
I refactored the settings into a dedicated struct, aligned the formatting of the counts, and added tests.
=> Refactor wc.

src/split/deps.mk, test/split.rs
I added an additional regex dependency and converted strings to Vec<u8>'s for the assertions.
=> Fix split tests.

test/split.rs
I added a prefix to each test to isolate working files.
=> Fix broken split tests.

deps/Cargo.toml, src/tr/deps.mk, src/tr/tr.rs
I switched over to the bit-vec/bit-set cargos.
=> Fix deprecation warnings for tr.

src/sync/sync.rs
=> Fix build on non-windows

src/cut/buffer.rs, src/cut/cut.rs, src/fold/fold.rs, src/hostname/hostname.rs, src/ptx/ptx.rs
I replaced position_elem() and slice_chars(). I also removed an unused feature attribute.
=> Replace deprecated methods.

src/uniq/uniq.rs
Added -f flag for uniq.
```
-f, --skip-fields=N
avoid comparing the first N fields
```
=> -f flag for uniq

README.md
Small update to reflect the nightly build requirement
=> Updated README to reflect nightly build dependency

src/echo/echo.rs, src/ln/ln.rs, src/mv/mv.rs, src/nl/helper.rs, src/nl/nl.rs, src/users/users.rs, src/yes/yes.rs
I removed the unstable slice_patterns and str_char features. I also used the deprecated connect() method, instead of join().
=> Backport and/or replace unstable features.

src/ptx/ptx.rs
I cleaned up string references, whitespace, and use of unstable features. I also added a comment about reverting to connect, making others aware that the method should be replaced by join after 1.3.
=> Remove unstable features from ptx.

Makefile, src/echo/echo.rs, src/fold/fold.rs, src/ptx/ptx.rs, src/stdbuf/libstdbuf.rs, src/stdbuf/stdbuf.rs, src/timeout/timeout.rs, src/users/users.rs, src/yes/yes.rs
Nightly is already a dependency.  This reduces lots of warnings on Nightly, and makes it ALMOST compile on Beta.
=> Moved code officially to run on nightly since it's a dependency

src/expand/expand.rs, src/unexpand/unexpand.rs
Revert the breaking changes to expand/unexpand introduced by #691
=> Fix nightly build

Makefile, src/rmdir/rmdir.rs, test/common/util.rs, test/rmdir.rs
I also adjusted error message to conform to GNU implementation.
=> Add tests for rmdir.

Makefile
Allow to pass additional flags to cargo.
See #746.
=> make: add CARGOFLAGS

src/tail/tail.rs
In order to work around lines() removing the newline byte and CRLF, I
switched from the iterator methods (lines/bytes) to the direct methods
(read_line/read). I also manually skipped lines/bytes.
Fixes #744.
=> tail: use read_line/read instead of lines/bytes

src/chmod/chmod.rs, src/id/id.rs, src/uname/uname.rs, src/uucore/c_types.rs
=> Fix arm build

src/du/du.rs
=> du: fix default symlink handling

Cargo.toml, Makefile, README.md, src/shred/Cargo.toml, src/shred/main.rs, src/shred/shred.rs
This is my attempt at implementing shred.  It's partially based on some earlier implementation I saw in the issues section that someone else had worked on.  Feedback appreciated
=> Implement shred

.travis.yml, Cargo.lock
=> cache .cargo. TODO: decide `fetch` each time or commit `Cargo.lock`

tests/touch.rs
=> tests/touch: fix tests

Cargo.lock, src/chmod/chmod.rs
You might want to check to see if I've missed something, though.
=> Should fix chmod (#784)

tests/chmod.rs
=> tests/chmod: disable failing tests

.travis.yml, src/chmod/chmod.rs, tests/common/util.rs, tests/pwd.rs, tests/readlink.rs, tests/realpath.rs
Also drop OS X from allowed failures in Travis and very slightly change the output formatting for chmod.
=> tests: fix tests that were failing on OS X

CONTRIBUTING.md, README.md
I'm not really sure why AppVeyor wasn't working before, but whatever.
=> Fix AppVeyor (hopefully) and change targeted Rust version

Makefile, README.md
Replace {,DONT_}{BUILD,INSTALL,TEST,BUSYTEST} with UTILS and SKIP_UTILS.
This probably breakes something.
=> make: simplify make variables

tests/common/util.rs
fixes " thread 'xxx' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 87, message: "The parameter is incorrect." } }', ../src/libcore\result.rs:746" in tests under Windows
=> Fix tests startup under Windows

tests/base64.rs, tests/basename.rs
complete behavior covered afaik
=> Base64, Basename: additional tests

src/sort/sort.rs
This adds the -o switch to specify an output file for 'sort'.
While I've used it for toy projects, this is the first time I've submitted Rust code for review by others, so please give it a careful review.
=> sort: Implement -o switch

src/uutils/uutils.rs
=> fix two clippy warnings

CONTRIBUTING.md
To help contributors, I added guidelines and examples for commit messages. This came from the discussion in #844.
I welcome any comments or suggestions.
ping @ebfe @Heather @Arcterus
=> CONTRIBUTING: add guidelines for commit msgs

src/tail/tail.rs, tests/tail.rs
Makes `parse_size` return a `Result` where the `Err` part indicates whether
there was a parsing error, or the parse size is too big to store. Also makes the
value parsed a `u64` rather than a `usize`.
Adds unit tests for `parse_size` and integration tests using the suffix
multiplier in a number passed with the `-n` flag.
Fixes #850.
=> tail: Clean up and test suffix multiplier

Makefile
introduced in 8ff308740c33479019e137fe2ece5bb5372c9ecb
=> Revert unwanted change

src/od/od.rs
Fixes #866 
Error handling/reporting still could be improved.
=> od: fix infinite loop at EOF

Cargo.lock, src/tr/Cargo.toml, src/tr/tr.rs
=> tr: update vec_map to 0.6.0

src/cksum/cksum.rs
Fixes #886 
Thanks, @nathanross!
=> cksum: resolve msvc unsafe issue

Cargo.toml, Makefile, src/stat/Cargo.toml, src/stat/fsext.rs, src/stat/main.rs, src/stat/stat.rs, src/stat/test_stat.rs, tests/test_stat.rs, tests/tests.rs
Finally made it! Many times of refactoring... Orz. There is some remaining work though.
TODO:
@Heather Maybe a code review? I am inexperienced in Rust. Any suggestion would be appreciated :-D
=> Implement stat

README.md, src/mktemp/mktemp.rs, src/mktemp/tempdir.rs, tests/test_mktemp.rs
Add two options: `-d` and `-q`
=> Improve mktemp

src/chmod/chmod.rs, tests/test_chmod.rs
=> chmod: check umask if ugoa is not present

Cargo.lock, Cargo.toml, Makefile, src/arch/Cargo.toml, src/arch/arch.rs, src/arch/main.rs
=> arch: add new utility

Cargo.toml, Makefile, src/chown/Cargo.toml, src/chown/chown.rs, src/chown/main.rs, src/chown/passwd.rs, tests/test_chown.rs, tests/tests.rs
#698 It has been 3 months, so...
TODO:
=> Implement chown

tests/test_base64.rs
This rewrites the base64 tests's assertions to use the [ergonomic testing](https://github.com/uutils/coreutils/pull/822) feature, making the tests more terse and readable.
=> base64: refactor tests to be more terse

tests/common/util.rs
As a beginning to resolving #859 , this commit adds some basic documentation to several functions and structs in util.rs, the utility module used by integration tests
=> tests/common: document more structs and functions of util.rs

src/ls/ls.rs
This commit computes the largest values of `symlink_count` and `file_size` before printing such that it can pad these columns if needed.
The functionality copies `ls -l`, which also pads (ls (GNU coreutils) 8.21)
Before:
```
drwxr-xr-x 125 kefin kefin      4096 .fingerprint
-rw-r--r-- 1 kefin kefin         0 .cargo-lock
drwxr-xr-x 2 kefin kefin      4096 examples
drwxr-xr-x 2 kefin kefin     12288 deps
drwxr-xr-x 7 kefin kefin      4096 build
-rwxr-xr-x 1 kefin kefin  38444424 uutils
drwxr-xr-x 2 kefin kefin      4096 native
```
After:
```
drwxr-xr-x 125 kefin kefin     4096 .fingerprint
-rw-r--r--   1 kefin kefin        0 .cargo-lock
drwxr-xr-x   2 kefin kefin     4096 examples
drwxr-xr-x   2 kefin kefin    12288 deps
drwxr-xr-x   7 kefin kefin     4096 build
-rwxr-xr-x   1 kefin kefin …
```
=> ls: Show columns correctly padded according to the largest file and the largest symlink count

src/ls/ls.rs
The flag was unimplemented, so here it is. One concern is the `unwrap()` inside the `should_cull_dot` function: is it possible for the string to be of size 0? After some googling, I suspect this is not the case, so I left it in.
The reason for implementing this is due to the help message:
```
By default, ls will list the files and contents of any directories on the 
command line, expect that it will ignore files and directories whose 
names start with '.'.                                                                        
```
=> ls: ls: Implement the '-a' (all) flag

.travis.yml, Cargo.toml, appveyor.yml, build.rs, tests/test_stat.rs
Fix windows build and  pass `--features=nightly` to cargo when using nightly rustc
=> Improve CI

Cargo.lock, src/ls/Cargo.toml, src/ls/ls.rs
As a project to learn Rust, I've been working on making some improvements to ls. This adds a bunch of options such as color and sorting, improves the output, and cleans up a few other things.
Apologies for the mega-commit; since this was a learning effort, the full commit history was sort of a mess.
=> ls improvments

Cargo.lock, src/sleep/sleep.rs, src/timeout/timeout.rs, src/uucore/Cargo.toml, src/uucore/lib.rs, src/uucore/parse_time.rs, src/uucore/process.rs
Also refactored out usage of the `time` crate in `uucore`.
=> Prefer handling `Duration` over `f32` when dealing with times.

src/cut/cut.rs
Changed towards resolving #818
=> cut: provide original-work help message and option descriptions

src/cut/buffer.rs, src/cut/cut.rs, tests/test_cut.rs
implement  --zero-terminated (-z) option
no changes to char mode because removal of specialized char mode behavior is pending
=> cut: implement zero-terminated option

Makefile
This fixes a few problems I was having with installing on Mac.
=> Make installation more robust

Cargo.toml, Makefile, README.md, src/pinky/pinky.rs, src/users/users.rs, src/uucore/utmpx.rs, src/who/Cargo.toml, src/who/main.rs, src/who/who.rs, tests/test_who.rs, tests/tests.rs
=> Implement who

README.md, src/uniq/Cargo.toml, src/uucore/Cargo.toml, src/uucore/lib.rs, tests/test_uniq.rs
...and make the TODO list more encouraing(maybe?)
=> Uniq: add tests

src/tr/Cargo.toml, src/tr/tr.rs
Fix building error e.g. https://travis-ci.org/uutils/coreutils/jobs/153635233#L213
=> tr: use HashMap in stdlib instead of vec_map

src/pinky/pinky.rs, src/who/who.rs, tests/test_pinky.rs
=> Fix bugs of `pinky` and `who`

Cargo.toml, Makefile, README.md, src/chgrp/Cargo.toml, src/chgrp/chgrp.rs, src/chgrp/main.rs, tests/test_chgrp.rs, tests/tests.rs
=> Implement chgrp

src/chgrp/Cargo.toml, src/chgrp/chgrp.rs, src/chown/Cargo.toml, src/chown/chown.rs, src/uucore/fs.rs
=> Updated chgrp & chown

src/touch/Cargo.toml, src/touch/touch.rs, tests/common/util.rs, tests/test_touch.rs
=> touch: respect -h option

src/chgrp/chgrp.rs, src/chown/chown.rs, src/uucore/fs.rs, tests/test_chgrp.rs
=> chgrp: fix bug in option --preserve-root

src/chgrp/chgrp.rs, src/uucore/fs.rs
Is there a bind mount equivalent on Windows?
=> chgrp: fix more --preserve-root problems

Cargo.lock, Cargo.toml, src/ls/Cargo.toml, src/more/Cargo.toml, src/more/more.rs
ref #999.
All generic utilities can compile on Fuchsia thus far!
cc @raphlinus
=> Enable compilation of more and ls on Fuchisa.

Cargo.toml, build.rs
only features that crosscompile for redox are included
=> create redox feature as subset of generic

src/sort/sort.rs, tests/fixtures/sort/ignore_case.expected, tests/fixtures/sort/ignore_case.txt, tests/test_sort.rs
=> sort: Implement ignore-case

tests/test_pinky.rs
At the moment pinky tests try to match /etc/passwd contents to pinky output. Unfortunately, on MacOS /etc/password is only used in single-user mode, normally it uses MacOS specific configuration. This leads to test failure when root user configuration in /etc/passwd does not match MacOS configuration. In my case it was failing because I had zsh installed.
This PR changes broken tests to use getpwnam from libc instead.
=> pinky: fix tests on MacOS

src/uucore/coreopts.rs
This adds support for options and flags that can appear multiple times.
=> uucore: add support for optflagmulti and optmulti.

src/tr/tr.rs
Current implementation of `tr` buffers the entire input file _and_ the entire transformed output. This results in extremely high memory usage.
This pull request makes `tr` not buffer output (aside of BufWriter) and only buffers a single line of input, which is the next best thing until the [chars() iterator](https://doc.rust-lang.org/std/io/struct.Chars.html) is stabilized.
These changes do not degrade performance.
=> Make tr streaming

src/cp/Cargo.toml, src/cp/cp.rs, tests/test_cp.rs
I added support and tests for -r/--recursive to cp.
=> cp: Add -r flag

src/cp/cp.rs
Added support for updating files using cp.
=> cp: added --update flag.

README.md
=> Add LOC counter to README

Cargo.lock, src/rm/Cargo.toml, src/rm/rm.rs
I also switched to `walkdir` from our custom directory walking code, so someone might want to check to make sure I didn't overlook something.
=> rm: massive refactor

README.md
This makes it easier to see which utils still need to be implemented.  I'm not sure about the wording for the headers though, so if anyone has any suggestions I'd be glad to hear them.
=> Format list of complete and incomplete utils as a table

src/cp/Cargo.toml, src/cp/cp.rs
Add support for cp --reflink using the FICLONE ioctl.
=> cp: add support for --reflink.

src/install/install.rs
- Do not mark as unimplemented
- Use ascii quotes
- Print newline
=> install: Fix verbose mode

src/tr/tr.rs, tests/test_tr.rs
Hi! Just practicing with Rust.
* Added squeeze option
* Improved performance a little
=> Improve tr

src/mv/mv.rs
Thought I'd split up uumain as it seemed a bit long. Not sure if you want those kind of refactorings. Feel free to close this if not.
=> mv: split up uumain

src/comm/comm.rs, src/cp/cp.rs, src/printf/tokenize/unescaped_text.rs, src/unexpand/unexpand.rs
=> cp: fix compiler warnings

Cargo.toml, Makefile, src/numfmt/Cargo.toml, src/numfmt/main.rs, src/numfmt/numfmt.rs, tests/test_numfmt.rs, tests/tests.rs
Not all options are included, but this implementation can be base for future improvements
#911
=> Add numfmt

src/env/env.rs, tests/test_env.rs
`--help` and `--version` not working for `env`
=> fix --help and --version

src/mknod/parsemode.rs, src/stdbuf/build.rs
This should stop all the build failures.  Fixes #1109.
=> mknod, stdbuf: fix build

src/echo/echo.rs
Removed duplicate code by merging some common cases into one, variable names refactoring.
=> Slight improvements to echo

Cargo.lock, Cargo.toml, src/stdbuf/build.rs, src/who/who.rs, tests/test_chgrp.rs, tests/tests.rs
Resolves #1138, although we need to find a good (_i.e._ safe) way to test as root.
=> Fix tests when using containers

src/du/du.rs
Allow -h (human readable form) to show GB (mimics original du behaviour)
=> du -h: support GB

src/ls/ls.rs
If you're accepting PRs for the `-1` flag, here it is.
- Adds the `-1` flag so that results can be printed in a single column
- Removes the pointless `Vec` allocation when gathering names.
=> [ls] Add "-1" Flag & Fix Needless Vec

src/join/join.rs, tests/fixtures/join/header.expected, tests/fixtures/join/header_1.txt, tests/fixtures/join/header_2.txt, tests/fixtures/join/header_autoformat.expected, tests/test_join.rs
The changes to support the --header option for join.
=> join: support headers

src/du/du.rs
This is basically the quick rewrite from the comment I wrote on #1176.  I also ran `du` through `rustfmt` again.
=> du: clean up block size parsing code

src/du/du.rs
`convert_size()` would check the options passed on the command-line every time it was called before.  Now the options are only checked once.  This also fixes a bug I inadvertently created in the last commit (due to reversing `UNITS`).
=> du: pick format for convert_size() once and reverse UNITS (again)

src/chmod/chmod.rs
=> chmod: Remove '(unimplemented)' from the opt help.

src/chmod/chmod.rs, src/ls/Cargo.toml, src/ls/ls.rs, src/uucore/fs.rs
when --changes or --verbose is given, like GNU chmod. Using on `ls`' code, which I moved to uucore.
=> chmod, ls, uucore: Make chmod display human-friendly permissions

src/mkdir/mkdir.rs, tests/test_mkdir.rs
=> mkdir: Silently fail in recursive mode if unable to create directories.

.travis.yml, Cargo.lock, Makefile, src/uucore/Cargo.toml, src/uucore/encoding.rs, src/uucore/lib.rs
For the time being, I am planning on restructuring various things to support arbitrary writers/readers rather than relying on stdio/stdin/stderr.  I am also planning on preventing arbitrary panics (which could have occurred in the previous implementation).
=> uucore: update data_encoding and add wrap_write()

src/uniq/uniq.rs
The biggest speedups comes from not allocating Strings at every cmp_key
=> Improve uniq performance

src/numfmt/numfmt.rs, tests/test_numfmt.rs
=> numfmt: add suffixes and fix negative numbers

Cargo.lock, src/ls/Cargo.toml, src/ls/ls.rs
**Before:**
```
-rw-r--r--  1 arni arni  2.02 kB 2018-09-14 21:07 CONTRIBUTING.md
-rw-r--r--  1 arni arni 78.75 kB 2018-09-14 23:41 Cargo.lock
-rw-r--r--  1 arni arni  6.92 kB 2018-09-14 21:07 Cargo.toml
-rw-r--r--  1 arni arni  1.05 kB 2018-09-14 21:07 LICENSE
-rw-r--r--  1 arni arni  5.98 kB 2018-09-14 21:07 Makefile
-rw-r--r--  1 arni arni 10.68 kB 2018-09-14 21:07 README.md
-rw-r--r--  1 arni arni  2.22 kB 2018-09-14 21:07 appveyor.yml
-rw-r--r--  1 arni arni   2.9 kB 2018-09-14 21:07 build.rs
-rw-r--r--  1 arni arni     15 B 2018-09-14 21:07 codecov.yml
drwxr-xr-x  2 arni arni   4.1 kB 2018-09-14 21:07 docs
-rw-r--r--  1 arni arni    973 B 2018-09-14 21:07 mkmain.rs
drwxr-xr-x 97 arni arni   4.1 kB 2018-09-14 21:07 src
drwxr-xr-x  3 arni arni   4.1 kB 2018-09-14 21:08 target …
```
=> Change `ls -l -h` formatting to match GNU ls

src/tee/tee.rs
simplifies to using a shorthand field
=> refactor: use shorthand fields

src/base32/base32.rs, src/base64/base64.rs, src/base64/base_common.rs, src/uucore/encoding.rs, src/uucore/macros.rs
Merge `base32` and `base64` as discussed in #1307.
=> base32, base64, uucore: merge base32/base64 code

src/echo/echo.rs, tests/test_echo.rs
This caught my eye, so I threw together a rewrite: https://www.reddit.com/r/rust/comments/b90l5i/is_the_code_badly_written_or_this_is_how_rust/
See: https://github.com/uutils/coreutils/issues/1342
Should function the same, but it's a lot shorter, more readable, and has tests.
=> echo: rewrite for readability and tests

src/chown/chown.rs
=> chown: change first file with --reference

src/env/Cargo.toml, src/env/env.rs, tests/common/util.rs, tests/fixtures/env/vars.conf.txt, tests/test_env.rs
* includes test which demonstrates the problem
Note that this is on top of the improved testing introduced in PR#1281.
=> fix ~ env: support windows commands (BAT/CMD, builtins)

src/uucore/signals.rs
* Add some tests to the signal module of uucore
* Fix `is_signal` to work for the highest valued signal
* Don't allocate in `signal_by_name_or_value`
=> Uucore signals cleanup

README.md
This solves `error: no default toolchain configured` if root user has no toolchain installed.
=> README: clarify elevated installation

README.md
fix `master/src/hashsum/hashsum.rs` to `src/uu/hashsum/src/hashsum.rs`
=> Fix hashsum.rs links in README.md

src/uu/date/src/date.rs, tests/test_date.rs, tests/tests.rs
Set a date doesn't work (but didn't before).
I will work on it more
=> Refresh "date" and includes a bunch of tests

src/cat/cat.rs
@Arcterus I would like to tackle `cat` as part of https://github.com/uutils/coreutils/issues/1358 and hopefully other utils down the line.
However seems like I need your comments/direction on what to do at least at high level otherwise this might end up as a big refactoring PR without any chance of merging.
Feel free to start giving direction. The idea of the repo is very nice, hope to see it is improving.
=> Refactor `cat`

src/uu/cat/src/cat.rs
Simple style fix ... checking testing now.
=> refact/cat ~ fix style issues

tests/test_users.rs, tests/tests.rs
Hopefully, will work on Windows too
=> test(users): Introduce two tests

src/uu/expand/src/expand.rs, src/uu/unexpand/src/unexpand.rs
I created this new PR from #1434
=> Flush output buffer for expand/unexpand commands

tests/fixtures/fmt/one-word-per-line.txt, tests/test_fmt.rs, tests/tests.rs
Even if it is a bit broken for now
=> test(fmt): Add some tests for fmt

src/uu/head/src/head.rs, tests/test_head.rs
Rebase https://github.com/uutils/coreutils/pull/1427
(I don't have permissions)
=> feature(head): Introduce NLines to handle negative lines parameters

Cargo.lock, src/uu/uptime/Cargo.toml, src/uu/uptime/src/uptime.rs, tests/test_uptime.rs
For this, I:
* moved from getops to clap
* remove the millisecond maths
=> feature(uptime): add option --since

Cargo.lock, src/uu/hashsum/Cargo.toml, src/uu/hashsum/src/hashsum.rs
Additionally, slightly refactor.  This commit will be the first of a series of commits refactoring (at the very least) `hashsum`.
This can be merged now, but I plan to add more commits in a few days.
=> hashsum: switch from getopts to clap

src/uu/factor/src/factor.rs
~46% faster overall than `master`
=> factors: Speed up displaying the results

src/uu/factor/src/factor.rs, src/uu/factor/src/rho.rs, src/uu/factor/src/table.rs
=> factor::rho: Refactor for readability and fewer allocations

src/uu/factor/build.rs, src/uu/factor/src/table.rs
~26% runtime improvement.
I will probably keep trying to improve on this, but I don't think there's much reason not to merge it as-is, as I'm unsure how long the optimisations I have in mind will take me to implement and test.
=> Speed up factor::table

.github/workflows/CICD.yml, src/uu/cp/src/cp.rs, src/uu/split/src/split.rs, src/uu/tee/src/tee.rs
- fixes several CICD warnings which have crept in over the last several merges
=> Fix CICD warnings

tests/by-util/test_head.rs
I ran the latest GNU head test suite and added the tests we were failing. Some unsupported features, some bugs.
=> Adding failing GNU head tests

src/uu/split/src/split.rs, tests/by-util/test_split.rs
=> Add additional-suffix option to split

src/uu/tr/src/tr.rs, tests/by-util/test_tr.rs
=> Fix `tr` argument handling for missing arguments

Cargo.lock, src/uu/install/Cargo.toml, src/uu/install/src/install.rs, tests/by-util/test_install.rs
I will do improvements once this lands
=> refactor(install): move to clap

Cargo.lock, src/uu/rm/Cargo.toml, src/uu/rm/src/rm.rs, tests/by-util/test_rm.rs
Will probably fail on some configurations because https://github.com/uutils/coreutils/pull/1629/commits/cc0a94ef7b486ce8a5c1554a82dcdfbb537b2ddd
needs to be merged first
=> refactor(rm): Move to clap + add a test

src/uu/uname/src/uname.rs, tests/by-util/test_uname.rs
Just return 'unknown' for both
Closes: #1636
=> feature(uname): Implement -p & -i

tests/by-util/test_rm.rs
See https://github.com/uutils/coreutils/pull/1667
=> test(rm): Add a test for multiple -f

Cargo.lock, src/uu/tail/Cargo.toml, src/uu/tail/src/tail.rs
See #1683 for past commit log. I was unable to squash properly into the same branch even after spending almost an hour, so I closed that PR ._.
=> tail: moving to clap from getopt

.github/workflows/GNU.yml
Fixes #1431 
Run the GNU coreutils tests to monitor compatibility.
=> Add gnu tests

src/uu/fmt/src/fmt.rs, tests/by-util/test_fmt.rs
=> bug(fmt): just like the GNU version, fails when -W is bigger than 2500

.github/workflows/GNU.yml
Ok, I am now confident that the tests are running against the rust code, new results:
```
```
Also the running time is now at ~45 minutes.
It would be good if someone could review the results to make sure they are reasonable.
=> Fix gnu tests

src/uu/seq/src/seq.rs, tests/by-util/test_seq.rs
I'm not sure about the test included here, as if it fails the test will hang forever.
=> Do not allow seq to run with an increment of zero

src/uu/paste/Cargo.toml, src/uu/paste/src/paste.rs
closes #1734
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uutils/coreutils/1785)
=> paste: move from getopts to clap

Cargo.lock
missed from #1785
ran `cargo +1.33.0 update`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uutils/coreutils/1789)
=> paste: update cargo lock file

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
=> cp: Implement --parents

src/uu/paste/src/paste.rs, tests/by-util/test_paste.rs, tests/common/util.rs
- cleaner impl for multi-stdin support
- added some tests from gnu coreutils
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/uutils/coreutils/1803)
=> paste: add more tests

tests/common/util.rs
File was not write-able if opened with write.
=> tests/utils: fixed mode for write

tests/by-util/test_sleep.rs
Continuation of #1777 
As mentioned here:
https://github.com/uutils/coreutils/pull/1777#discussion_r593807712
=> sleep: Add more test cases

src/uu/tr/src/expand.rs, tests/by-util/test_tr.rs
=> tr: process octal escape sequences

src/uu/tee/Cargo.toml, src/uu/tee/src/tee.rs
=> tee: move from getopts to clap

src/uu/chroot/Cargo.toml, src/uu/chroot/src/chroot.rs, tests/by-util/test_chroot.rs
Hey @sylvestre, implemented the basic structure with clap, however still need tests etc. I'll ping when you when it is ready to review. 
Closes #1732
=> chroot: move to clap from getopts

src/uu/head/src/head.rs, tests/by-util/test_head.rs
This PR adds ability to check the given path is a valid file before unwrapping it for every argument.  
fixes: https://github.com/uutils/coreutils/issues/1800
=> fix(head): check the whether file exists before unwrap

src/uu/tail/src/tail.rs, tests/by-util/test_tail.rs
closes: https://github.com/uutils/coreutils/issues/1860
=> fix(tail): add support for negative indexing

src/uu/tsort/Cargo.toml, src/uu/tsort/src/tsort.rs, tests/by-util/test_tsort.rs
closes: https://github.com/uutils/coreutils/issues/1862
=> tsort: move from getopts to clap

src/uu/echo/Cargo.toml, src/uu/echo/src/echo.rs
Move echo from getopts to clap (resolves: #1875)
=> echo: move from getopts to clap

src/uu/unexpand/Cargo.toml, src/uu/unexpand/src/unexpand.rs, tests/by-util/test_unexpand.rs, tests/fixtures/unexpand/with_spaces.txt
move unexpand from getopts to clap: (closes: https://github.com/uutils/coreutils/issues/1863)
=> feat(unexpand): move from getopts to clap

src/uu/echo/src/echo.rs
Unfortunately https://docs.rs/clap/2.33.3/clap/struct.Arg.html#method.allow_hyphen_values does not fix this. I played around a little bit, but with no success. I reworked #1884 a little bit.
I added a failing test case for leading hyphens in echo.
With C implementation echo -foo works fine.
=> echo: reworking of the new options

src/uu/cat/Cargo.toml, src/uu/cat/src/cat.rs
Yet another port to clap, current test suite passes, also fixed a one pretty small clippy warning.
=> cat: move cat to clap

src/uu/nl/Cargo.toml, src/uu/nl/src/helper.rs, src/uu/nl/src/nl.rs
For https://github.com/uutils/coreutils/issues/1864
There shouldn't be any behavioral changes.
=> nl: move from getopts to clap

src/uu/comm/Cargo.toml, src/uu/comm/src/comm.rs
Closes #1940 
tests are passing and there is no problem with clippy and rustfmt
=> comm: move from getopts to clap

Cargo.lock, src/uu/tr/Cargo.toml, src/uu/tr/src/tr.rs
Porting tr from getops to claps
Tests passed
Resolves #1929
=> tr: move from getopts to claps #1929

src/uu/chmod/src/chmod.rs, tests/by-util/test_chmod.rs
This fixes chmod's behavior for -v and -f and -R on dangling symlinks:
* fixed #1775
* added tests
* changed some output to mimic GNU's chmod output:
- added padding for permissions in octal
- added correct info text for dangling symlink
- switched some info text from stderr to stdout
=> chmod: fixed behavior for dangling symlinks (#1775)

src/uu/more/Cargo.toml, src/uu/more/src/more.rs
=> more: move from getopts to clap

DEVELOPER_INSTRUCTIONS.md
See https://github.com/uutils/coreutils/pull/1959#issuecomment-810519719
=> Add pre-commit instructions

src/uu/relpath/Cargo.toml, src/uu/relpath/src/relpath.rs, tests/by-util/test_relpath.rs
=> relpath: move from getops to clap (#1939)

Cargo.lock, build.rs, src/uu/chroot/src/chroot.rs, src/uu/head/src/head.rs, src/uu/hostname/src/hostname.rs, src/uu/ln/src/ln.rs, src/uu/mktemp/src/mktemp.rs, src/uu/numfmt/src/numfmt.rs, src/uu/readlink/src/readlink.rs, src/uu/shred/src/shred.rs, src/uu/stdbuf/src/stdbuf.rs, src/uu/uptime/src/uptime.rs, tests/common/util.rs
Apparently fmt from 1.40.0 is a bit more strict in some places
Let me know if this is worthwhile merging :)
=> chores: run `cargo +1.40.0 fmt`

src/uu/more/src/more.rs, tests/by-util/test_more.rs
=> Add error message if more is used on a directory

src/uu/factor/sieve.rs
This requires MSRV of 1.36.0 so probably can't be merged right away.
=> Use Iterator::copied() in sieve.rs (merged once 1.36.0 is the minimal version)

Cargo.lock, src/uu/cat/Cargo.toml, src/uu/cat/src/cat.rs
Revert "cat: Improve performance on Linux (#1978)"
This reverts commit 7a947cfe46b694f61a5a7d840d622ce292da457c.
=> Fix bug #2017 - cat isn't working

src/uu/fold/src/fold.rs, tests/by-util/test_fold.rs
- refactor implementation for readability
- correct handling of files with no trailing newline and/or blank lines
=> fold: improve newline handling and test coverage

src/uu/du/src/du.rs
=> Consider device id when comparing files

Cargo.lock, src/uu/fold/Cargo.toml, src/uu/fold/src/fold.rs, tests/by-util/test_fold.rs, tests/fixtures/fold/space_separated_words.txt
This PR includes these changes for fold: 
* Moved to clap
* Added tests and fixtures for testing compatibility against obsolote syntax
=> fold: move to clap, add tests

README.md
This is a minor revision for the initial build instructions in the README, including some de-linting fixes.
Fixes #2045.
=> README update revising initial build instructions

tests/by-util/test_stdbuf.rs
see https://github.com/uutils/coreutils/pull/2036#issuecomment-817277638
=> stdbuf: do not pipe data into failure tests

src/uu/chown/src/chown.rs, tests/by-util/test_chown.rs
=> chown: fix #2060

tests/by-util/test_cat.rs
Honestly, I'm not sure if this is an ugly solution but I could reproduce the failing test on a VM and this fixes it.
=> cat: make tests stable

tests/by-util/test_ls.rs
=> ignore the test_ls_styles

src/uu/pinky/Cargo.toml, src/uu/pinky/src/pinky.rs, tests/by-util/test_pinky.rs
=> pinky: move from getopts to clap (#2123)

tests/by-util/test_ls.rs
This should fix the time style test.
=> `ls`: fix time style test

Cargo.lock, src/uu/link/Cargo.toml, src/uu/link/src/link.rs
=> link: replace getopts with clap

tests/by-util/test_link.rs
=> Add tests to check link fails with 1 or 3 argument(s)

tests/by-util/test_tr.rs
https://github.com/uutils/coreutils/pull/2158#discussion_r624711268
=> tr: add test

src/uu/df/src/df.rs, tests/by-util/test_df.rs
on this platform, capacity column is also displayed.
=> df little update proposal for mac.

Cargo.lock, src/uu/logname/Cargo.toml, src/uu/logname/src/logname.rs
=> logname: replace getopts with clap

src/uu/head/src/head.rs
This pull request simplifies the code in `rbuf_n_bytes()` to use existing abstractions provided by the standard library. Specifically, use `Read::take()` to limit reading to the first `n` bytes, and use `io::copy()` to read from the input and write directly to the output.
=> head: simplify rbuf_n_bytes() in head.rs

tests/by-util/test_ls.rs
This tests for the open issue described in #2223
=> tests: add test for issue #2223

src/uu/tail/src/tail.rs
Similar to how we simplified `head -c -NUM` in pull request #2216, we can simplify `tail` to just use `std::io::copy()` after seeking the to the right place in the file.
=> tail: use std::io::copy() to write bytes to stdout

tests/by-util/test_truncate.rs
This should have gone with pull request #2238, sorry about that.
=> truncate: rustfmt test_truncate.rs file

src/uu/realpath/src/realpath.rs, src/uucore/src/lib/features/fs.rs
This pull request replaces code in `realpath` with a single call to `uucore::fs::canonicalize()`. In order for this to work, I needed to make a slight adjustment to the behavior of `canonicalize()` when `can_mode` is `CanonicalizeMode::None`. The tests pass on my machine, but I'm not 100% certain the change in the behavior of `canonicalize()` is acceptable. (It changes the function so that it does not try to resolve symbolic links in the final component of a path; previously it was trying to resolve the link if the final component were a symbolic link.)
In updating `canonicalize()` I also added a documentation comment that describes my understanding of how the function is intended to behave. That may also be incorrect, so please double check it.
=> realpath: use uucore::fs::canonicalize() to reduce code duplication

util/build-gnu.sh
250MB is too big and hard to read. Try to simplify it
=> Try to decrease the size of the GNU log 

src/uu/mv/src/mv.rs, tests/by-util/test_mv.rs
=> mv: log proper error message when permission error occurs

Cargo.lock, src/uu/du/Cargo.toml, src/uu/du/src/du.rs
=> du: replace getopts with clap

src/uu/chmod/src/chmod.rs, tests/by-util/test_chmod.rs
=> chmod: match GNU error

src/uu/rmdir/src/rmdir.rs, tests/by-util/test_rmdir.rs
=> rmdir: match GNU error output

.github/workflows/CICD.yml, DEVELOPER_INSTRUCTIONS.md
=> CI: set clippy targets 'all'

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs, tests/common/macros.rs
=> cp: show errors in cow on linux

src/uu/seq/src/seq.rs, tests/by-util/test_seq.rs
Move the validation logic to an argument validator.
=> seq: reject NaN arguments

src/uu/more/src/more.rs
Closes https://github.com/uutils/coreutils/issues/2348
=> `more`: Do not accidentically hide last line

src/uu/more/src/more.rs
Implement feature requested in #2318.
=> more: Show next file at bottom line

src/uu/chroot/src/chroot.rs
In https://github.com/uutils/coreutils/commit/f60790dd411fbdc85a77eef24faab5c34422b00b, i used some undocumented features of clap, this PR addresses that and closes: https://github.com/uutils/coreutils/issues/2304
=> chroot: refactor undocumented features

util/build-gnu.sh
~~`build-gnu.sh` suggest to clone into `../gnu`~~
Edit:
suggest to clone into the path that `util/run-gnu-test.sh` will be using
=> util: fix path

src/uu/more/src/more.rs
Implement option '-d' (silent mode)
The method used in `make_prompt_and_flush()` is a bit messy to deal with both silent and help text.
If you have any suggestions, please comment. I would be more than happy to fix it.
Related to #2320
=> more: Implement option '-d'

tests/common/util.rs
This is useful for testing, I needed it here: #2361
=> tests/util: add CmdResult::new()

src/uu/du/src/du.rs, tests/by-util/test_du.rs
This PR implements --threshold argument handling for du utility and closes #2352.
Marking as draft as tests are yet to be added.
=> Implement du threshold argument handling

src/uu/test/src/test.rs, tests/by-util/test_test.rs
=> test: implement user, group ownership checks

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
Related: https://github.com/uutils/coreutils/issues/2353
Signed-off-by: Hanif Bin Ariffin <hanif.ariffin.4326@gmail.com>
=> Fixed cp --preserve accepting no args

src/uu/test/src/test.rs, tests/by-util/test_test.rs
parser.rs already accepts this, finish the implementation.
=> test: Implement -k

src/uu/mkdir/src/mkdir.rs, src/uu/mktemp/src/mktemp.rs, tests/by-util/test_mktemp.rs, tests/by-util/test_mv.rs, tests/by-util/test_sort.rs
When running the tests in a VM I encountered some test failures, which this pr tries to fix.
This was pointed out by @siebenHeaven in https://github.com/uutils/coreutils/issues/2418#issuecomment-865165836.
Could you confirm that these tests are now passing on your windows machine as well?
=> Make tests pass on a windows VM

.github/workflows/GnuTests.yml
Avoid to generate incorrect json files
=> CI/GNU: if an error is detected, don't generate the json file

src/uu/install/src/install.rs, tests/by-util/test_install.rs
Similar to the implementation in `cp`
=> install: support --target-directory

.github/workflows/FixPR.yml
Experiments to fix `git push ...` issues with 'CICD/FixPR'.
=> maint/CICD ~ fix 'FixPR' git push errors

src/uu/arch/src/arch.rs
=> arch: use UResult

src/uu/arch/src/arch.rs
Follow up for #2466 as suggested by @miDeb
=> arch: match GNU error

src/bin/coreutils.rs
Use clap to extract command line arguments. This generates much better
error messages.
Examples:
```
cargo run completion ls zs
Finished dev [unoptimized + debuginfo] target(s) in 0.09s
Running `target/debug/coreutils completion ls zs`
error: 'zs' isn't a valid value for '<shell>'
[possible values: bash, elvish, fish, powershell, zsh]
Did you mean 'zsh'?
USAGE:
completion <utility> <shell>
For more information try --help
```
```
cargo run completion ls
Finished dev [unoptimized + debuginfo] target(s) in 0.09s
Running `target/debug/coreutils completion ls`
error: The following required arguments were not provided:
<shell>
USAGE:
completion <utility> <shell>
For more information try --help
```
=> coreutils: better errors for invalid args for completions

src/uu/dirname/src/dirname.rs, src/uu/hostid/src/hostid.rs, src/uu/hostname/src/hostname.rs
=> Added UResult for hostname, hostid and dirname

src/uu/du/src/du.rs
=> du: Use UResult

src/uu/tr/src/tr.rs, tests/by-util/test_tr.rs
=> tr: fix squeeze and complement with two sets (#2485)

src/uu/sleep/src/sleep.rs, tests/by-util/test_sleep.rs
=> sleep: use UResult

src/uu/echo/src/echo.rs, src/uu/false/src/false.rs, src/uu/kill/src/kill.rs, src/uu/pwd/src/pwd.rs, src/uu/true/src/true.rs
Related to #2464 
@tertsdiepraam  Thanks for helping me out! :)
=> Add Uresult for false, echo, pwd, true and kill

src/uu/chown/src/chown.rs
=> chown: added UResult

src/uucore/src/lib/mods/error.rs
Make it plain what each of the functions is meant to implement and how they are
supposed to work.
=> uucore: error: Add docs to the `code` and `usage` functions

src/uu/df/src/df.rs
=> df: add `UResult`

src/uu/ln/src/ln.rs
Signed-off-by: Yagiz Degirmenci <yagizcanilbey1903@gmail.com>
Related: #2464
=> feat(ln): use UResult

src/uu/base32/src/base_common.rs, tests/by-util/test_base32.rs, tests/by-util/test_base64.rs, util/build-gnu.sh
I still have to check that it passes on CI, but it works on my machine™
=> base32/64: make the gnu test pass

src/uu/cat/src/cat.rs
=> migrate `cat` code to UResult #2464

.vscode/cspell.dictionaries/workspace.wordlist.txt, Cargo.lock, Cargo.toml, README.md, src/uu/base32/src/base_common.rs, src/uu/basenc/Cargo.toml, src/uu/basenc/src/basenc.rs, src/uu/basenc/src/main.rs, src/uucore/Cargo.toml, src/uucore/src/lib/features/encoding.rs, tests/by-util/test_basenc.rs, util/build-gnu.sh
basenc is a brand-new gnu core utility (added less than 3 years ago!),
which enables some more encodings.
=> basenc: add utility

src/uu/id/src/id.rs
=> id: use UResult

src/uu/nice/src/nice.rs
=> nice little code simplification, included already in the libc

src/uu/install/src/install.rs, src/uucore/src/lib/mods/error.rs
Related to uutils#2464
I didn't actually check whether the error messages match what GNUs `install` gives, I merely took the existing ones. I hope I got the idea right, otherwise I'm open for suggestions.
=> install: Use UResult

tests/by-util/test_cp.rs
Setting the current directory in tests affects other tests, even if the
change is reverted afterwards, because tests are run in parallel.
This should fix the flaky cp tests.
=> cp: do not set the current directory in tests

src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs
- Correct fallbacks (command line argument -> termsize -> environment variable -> 80)
- Print a single line when the width is 0
=> ls: correct output width

src/uu/csplit/src/split_name.rs
csplit fails when suffix has no flags:
```
$ csplit result.expected -f /tmp/EXPECT -b "%d" "/^## alternative ##$/" {*}
csplit: error: incorrect conversion specification in suffix
```
This is supported by original csplit
Closes #2531
=> csplit: fix suffix support without flag

src/uucore/src/lib/features/fsext.rs, src/uucore/src/lib/features/utmpx.rs
fsext build fix and utmpx implementation proposal.
=> uucore netbsd update

.github/workflows/CICD.yml
An attempt to resolve the problems caused by #2595, advised by @miDeb. Let's see if this works.
=> Make clippy workspace selection more finegrained

src/uu/ls/src/quoting_style.rs
For example, we quote `'~a'` and `'~'` but not `a~`. We do the same for `#`.
Fixes https://github.com/uutils/coreutils/issues/2606
=> ls: only quote ~ and # when they appear at the start of the name

src/uucore/src/lib/features/perms.rs, tests/by-util/test_chgrp.rs
- prevent duplicate errors from both us and `walkdir` by instructing `walkdir'
to skip directories we failed to read metadata for.
- don't directly display `walkdir`'s errors, but format them ourselves to
match gnu's format
I expect this to pass one more gnu test for `chgrp`.
=> uucore/perms: correct some error messages

src/uu/chgrp/src/chgrp.rs, src/uu/chown/src/chown.rs, src/uucore/src/lib/features/perms.rs, tests/by-util/test_chgrp.rs
- Share argument parsing and argument definitions
- refactor code to be more rust-y
- correctly handle -P, -H and -L
This should pass 3 more gnu tests.
=> chown/chgrp: share more code & refactor

src/uucore/src/lib/features/fsext.rs
prioritising statfs over statvfs for this platform.
=> fsext build fix for OpenBSD.

src/uu/whoami/src/whoami.rs
=> whoami: Added UResult

src/uu/uptime/src/uptime.rs
=> uptime: added UResult

src/uu/touch/src/touch.rs, tests/by-util/test_touch.rs
Used in gnu/tests/touch/relative.sh
=> touch: add --ref as an alias

src/uu/printf/src/tokenize/num_format/formatter.rs, src/uu/sort/src/sort.rs
Includes the commit from #2648.
=> Fix clippy warnings about Default impls

src/uu/mktemp/src/mktemp.rs
We can easily afford the UTF-8 check, so I think it's best to show clearly that the code is safe.
=> mktemp: Do not use unsafe

.vscode/cspell.dictionaries/jargon.wordlist.txt, src/uu/install/src/install.rs, src/uu/ls/src/ls.rs, src/uucore/src/lib/mods/error.rs
See https://github.com/uutils/coreutils/pull/2675#issuecomment-919092543
=> Do not discard non-OS error messages

src/uu/kill/src/kill.rs, tests/by-util/test_kill.rs
Before this change:
```
$ /kill -l
EXIT HUP INT QUIT ILL TRAP ABRT EMT FPE KILL BUS SEGV SYS PIPE ALRM TERM URG
STOP TSTP CONT CHLD TTIN TTOU IO XCPU XFSZ VTALRM PROF WINCH INFO USR1 USR2 
```
After this change:
```
$ ./kill -l
EXIT HUP INT QUIT ILL TRAP ABRT EMT FPE KILL BUS SEGV SYS PIPE ALRM TERM URG STOP TSTP CONT CHLD TTIN TTOU IO XCPU XFSZ VTALRM PROF WINCH INFO USR1 USR2
```
=> add kill -l final new line #2644

src/uu/csplit/src/csplit.rs, src/uu/dd/src/parseargs/unit_tests.rs, src/uu/ls/src/ls.rs, src/uu/more/src/more.rs, src/uu/od/src/output_info.rs, src/uu/sort/src/sort.rs
These were causing CI failures
=> ls,more,csplit,sort,od,dd: fix clippy complaints

src/uu/base32/src/base32.rs, src/uu/base32/src/base_common.rs, src/uu/base64/src/base64.rs, src/uu/basenc/src/basenc.rs, tests/by-util/test_base32.rs, tests/by-util/test_base64.rs
=> base32 + base64 + basenc: use UResult

src/uu/ls/src/ls.rs
=> ls: add possible value for `--color=`

src/uu/chmod/src/chmod.rs, tests/by-util/test_chmod.rs
=> chmod: use UResult

src/uu/who/src/who.rs, src/uucore/src/lib/features/utmpx.rs
=> who: use UResult

src/uu/basename/src/basename.rs, src/uu/date/src/date.rs, src/uu/fold/src/fold.rs, src/uu/nl/src/nl.rs, src/uu/nproc/src/nproc.rs, src/uu/shuf/src/shuf.rs, src/uu/uname/src/uname.rs
=> basename+date+fold+nl+nproc+shuf+uname: use UResult

src/uu/mv/src/mv.rs, tests/by-util/test_mv.rs
Attempt to fix bug described here: https://github.com/uutils/coreutils/issues/2760
=> Fix mv bug: Should be able to stat files, but not able to mv if source and target are the same

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
Fix of cp bug described at: https://github.com/uutils/coreutils/issues/2760
=> Fix cp bug: pre-write permission change

src/uu/more/src/more.rs
Fixes a compile issue due to: https://github.com/uutils/coreutils/pull/2771/files#r770165506
=> more: return Ok in main loop

tests/by-util/test_cp.rs
=> cp: add a unit test for issue 1665

src/uucore/src/lib/features/fsext.rs
proc(5) mentions the following for the fields section and hyphen:
> (7)  optional fields: zero or more fields of the form "tag[:value]";
> see below.
> (8)  separator: the end of the optional fields is marked by a single
> hyphen.
IOW, there may actually be multiple optional fields, not just one, in
which case the previously hardcoded indexes for the filesystem type and
device name are now incorrect. Now, the filesystem type and device name
are parsed relative to the hypen's location, ensuring that they will be
correct regardless of the number of optional fields.
Signed-off-by: Ryan Gonzalez <ryan.gonzalez@collabora.com>
=> uucore::fsext: Fix mountinfo parsing w/ multiple optional fields

src/uu/tac/src/error.rs, src/uu/tac/src/tac.rs
=> tac: return UResult from uumain() function

src/uu/comm/src/comm.rs, tests/by-util/test_comm.rs
=> comm: return UResult from uumain() function

src/uu/cksum/src/cksum.rs
=> cksum: return UResult from uumain() function

build.rs, src/uu/ln/src/ln.rs, src/uu/numfmt/src/format.rs, src/uu/paste/src/paste.rs, src/uu/pr/src/pr.rs, src/uu/ptx/src/ptx.rs, src/uucore/src/lib/features/encoding.rs
These fixes were suggested by `cargo +nightly clippy`.
=> fixes suggested by nightly version of clippy

src/uu/chroot/src/chroot.rs, src/uu/chroot/src/error.rs
=> chroot: return UResult from uumain() function

src/uu/dircolors/src/dircolors.rs
=> dircolors: return UResult from uumain() function

src/uu/expand/src/expand.rs
=> expand: return UResult from uumain() function

src/uu/factor/src/cli.rs
=> factor: return UResult from uumain() function

src/uu/groups/src/groups.rs
=> groups: return UResult from uumain() function

src/uu/hashsum/src/hashsum.rs
=> hashsum: return UResult from uumain() function

src/uu/join/src/join.rs
=> join: return UResult from uumain() function

src/uu/link/src/link.rs, tests/by-util/test_link.rs
=> link: return UResult from uumain() function

src/uu/logname/src/logname.rs
=> logname: return UResult from uumain() function

src/uu/mkfifo/src/mkfifo.rs
=> mkfifo: return UResult from uumain() function

src/uu/mknod/src/mknod.rs
=> mknod: return UResult from uumain() function

src/uu/mv/src/error.rs, src/uu/mv/src/mv.rs
=> mv: return UResult from uumain() function

src/uu/nice/src/nice.rs
=> nice: return UResult from uumain() function

src/uu/nohup/src/nohup.rs
=> nohup: return UResult from uumain() function

src/uu/numfmt/src/numfmt.rs
=> numfmt: return UResult from uumain() function

src/uu/od/src/od.rs
=> od: return UResult from uumain() function

src/uu/paste/src/paste.rs
=> paste: return UResult from uumain() function

src/uu/pathchk/src/pathchk.rs
=> pathchk: return UResult from uumain() function

src/uu/pinky/src/pinky.rs
=> pinky: return UResult from uumain() function

src/uu/printf/src/printf.rs
=> printf: return UResult from uumain() function

src/uu/dd/src/datastructures.rs, src/uu/dd/src/dd.rs, src/uu/dd/src/parseargs.rs, tests/by-util/test_dd.rs
See #2464.
I updated one unit test so that it better matches the behavior of GNU dd in the case where there is no outfile.
=> dd: return UResult from uumain() function

src/uu/csplit/src/csplit.rs, src/uu/csplit/src/csplit_error.rs
=> csplit: return UResult from uumain() function

src/uu/cut/src/cut.rs
=> cut: use UResult

src/uu/fmt/src/fmt.rs, src/uu/fmt/src/linebreak.rs
=> fmt: return UResult from uumain() function

src/uu/shred/src/shred.rs
=> shred: return UResult from uumain() function

src/uu/ptx/src/ptx.rs
=> ptx: return UResult from uumain() function

src/uu/relpath/src/relpath.rs
=> relpath: return UResult from uumain() function

src/uu/rm/src/rm.rs, tests/by-util/test_rm.rs
=> rm: return UResult from uumain() function

src/uu/stat/src/stat.rs
=> stat: return UResult from uumain() function

src/uu/test/src/test.rs
=> test: return UResult from uumain() function

src/uu/sync/src/sync.rs
=> sync: return UResult from uumain() function

src/uu/sum/src/sum.rs
=> sum: return UResult from uumain() function

src/uu/tty/src/tty.rs
=> tty: return UResult from uumain() function

src/uu/unexpand/src/unexpand.rs
=> unexpand: return UResult from uumain() function

src/uu/stdbuf/build.rs
Closes #1276.
I have tested this with 
```
cargo install --git file://<path to local repo> uu_stdbuf
```
Let's hope it also works correctly with crates.io.
=> stdbuf: fix cargo --git build (#1276) (Attempt 2)

src/uu/numfmt/src/format.rs, src/uu/numfmt/src/numfmt.rs, src/uu/numfmt/src/options.rs, tests/by-util/test_numfmt.rs
adds support for the --suffix option from issue #1280.
=> numfmt: implement missing --suffix option

src/uu/tee/src/tee.rs
=> tee: return UResult from uumain() function

src/uu/wc/src/wc.rs
See #2464.
I need some help with this one. I will leave a comment on the line of code that is causing a test failure.
=> wc: return UResult from uumain() function

src/uu/runcon/src/errors.rs, src/uu/runcon/src/runcon.rs
See #2464.
I don't know how to test this one, so please review with care.
=> runcon: return UResult from uumain() function

src/uu/timeout/src/timeout.rs
=> timeout: return UResult from uumain() function

src/uu/tsort/src/tsort.rs
=> tsort: return UResult from uumain() function

src/uu/pr/src/pr.rs
See #2464.
(There's a ton of custom error-handling in this module that can now be improved, but I didn't touch any of it in order to focus on just getting the top level `uumain()` functions to return `UResult`.)
=> pr: return UResult from uumain() function

src/uu/realpath/src/realpath.rs
=> realpath: return UResult from uumain() function

src/uu/tr/src/tr.rs
=> tr: return UResult from uumain() function

src/uu/stdbuf/src/stdbuf.rs
=> stdbuf: return UResult from uumain() function

Cargo.toml, src/uu/date/Cargo.toml, src/uu/du/Cargo.toml, src/uu/uptime/Cargo.toml
See: https://rustsec.org/advisories/RUSTSEC-2020-0071.html
=> Force minimal version of chrono to avoid a security issue

src/uu/head/src/head.rs
This pull request factors out a loop for finding the index of the byte immediately following the `n`th line from the end of a file. This does not change the behavior of the code, just its organization. This is needed for a future pull request that will improve the organization of the `head` code further.
=> head: refactor helper function find_nth_line_from_end()

.vscode/cspell.dictionaries/jargon.wordlist.txt, Cargo.lock, Cargo.toml, build.rs, src/bin/coreutils.rs, src/bin/uudoc.rs
Rather than building a HashMap at compile time, use the phf (and phf_codegen) crates to build the map at compile time in build.rs
=> Use a PHF map for util_map()

tests/by-util/test_ls.rs
Closes https://github.com/uutils/coreutils/issues/2969
=> `ls`: fix flaky test

README.md
Closes #2634.
[All GNU tests now pass.](https://github.com/uutils/coreutils/runs/5012335596?check_suite_focus=true#step:14:18)
=> README: mark join as done

.cargo/config, src/bin/coreutils.rs, src/uu/chroot/src/chroot.rs, src/uu/du/src/du.rs, src/uu/env/src/env.rs, src/uu/kill/src/kill.rs, src/uu/split/src/number.rs, src/uu/split/src/split.rs, src/uu/tail/src/platform/unix.rs, src/uu/tail/src/platform/windows.rs, src/uucore/src/lib/features/fsext.rs, src/uucore/src/lib/features/wide.rs, tests/by-util/test_du.rs, tests/by-util/test_env.rs
add warnings for most of the lints used in #2963
=> add additional lints

src/uu/shuf/src/shuf.rs
=> Include ABOUT for shuf

src/uu/df/src/df.rs
Add a `Options::from()` function to collect the code for parsing an
`Options` object from the `clap::ArgMatches` object. This does not change the behavior of the code, just its organization.
=> df: create Options::from() function to contain the code for parsing ArgMatches

src/uu/touch/src/touch.rs, tests/by-util/test_touch.rs
Closes: https://github.com/uutils/coreutils/issues/3049
=> touch: Better error messages when no args is provided

.travis/redox-toolchain.sh, util/GHA-delete-GNU-workflow-logs.sh, util/build-code_coverage.sh, util/build-gnu.sh, util/publish.sh, util/run-gnu-test.sh, util/show-code_coverage.sh, util/show-utils.sh, util/update-version.sh
Update shell scripts according to shellcheck recommendations and other minor cleanup.
Mostly changes of variable quoting and where possible, changing to use /bin/sh instead of /bin/bash
=> Shell script cleanup

src/uu/printf/src/printf.rs
It was mentioned in a previous [printf PR](https://github.com/uutils/coreutils/pull/3024#issuecomment-1027488132) that we should eventually be using clap's output - this PR addresses that, so that `printf --version` and `printf --help` are not manually parsed and handled.
The right terminal displays the current output of `printf --help`, the left displays the output with the new changes.
=> printf: use clap default help and version

src/uu/df/src/df.rs
Use a `for` loop in the `filter_mount_list()` function to make the filtering logic easier to read. This does not change the behavior of the code, just its organization.
=> df: refactor filter_mount_list() to be more flat

src/uu/stat/src/stat.rs, tests/by-util/test_stat.rs
=> stat: allow formatting of negative numbers

src/uu/dd/src/dd.rs
Addresses https://github.com/uutils/coreutils/issues/3073.
=> dd: make status=progress rewrite once/sec

docs/Makefile
Fixes https://github.com/uutils/coreutils/issues/3114
@kevinburke Could you verify this fix? I couldn't reproduce the issue on my machine.
=> make: add clean target for docs

src/uu/head/src/head.rs
Refactor the `Mode` enum in the `head.rs` module so that it includes
not only the mode type---lines or bytes---but also whether to read the
first NUM items of that type or all but the last NUM. Before this
commit, these two pieces of information were stored separately. This
made it difficult to read the code through several function calls and
understand at a glance which strategy was being employed.
=> head: incorporate "all but last" option into Mode

src/uucore/Cargo.toml, src/uucore_procs/Cargo.toml
Make these point to the correct location
=> uucore, uucore_procs: use the correct URLs in the crate manifest

.editorconfig, .github/workflows/CICD.yml, .github/workflows/GnuTests.yml, .rustfmt.toml, .vscode/cSpell.json, .vscode/extensions.json, .vscode/settings.json, util/GHA-delete-GNU-workflow-logs.sh, util/build-code_coverage.sh, util/build-gnu.sh, util/dwr.sh, util/publish.sh, util/run-gnu-test.sh, util/show-code_coverage.sh, util/show-utils.sh
* waiting for the CI to pass to make sure I didn't make any silly mistakes.
=> maint ~ configuration and utility clean-up and maintenance

tests/by-util/test_split.rs
=> fix failure in test_split

tests/by-util/test_test.rs
Closes https://github.com/uutils/coreutils/issues/2958
@water-ghosts would you mind checking whether this works?
=> `test`: fix wsl executable permission

.github/workflows/GnuTests.yml, util/run-gnu-test.sh
Fix profiling permission error caused by https://github.com/uutils/coreutils/pull/3045/commits/1ccf94e4fa8dd334a33e4174043acbeb57730802.
=> Run GNU root tests after other tests

.github/workflows/CICD.yml, Cargo.lock, src/uu/expr/Cargo.toml
2nd attempt. Sorry for the noise.
=> expr: update onig crate to 6.3

Cargo.lock, src/uu/hashsum/Cargo.toml, src/uu/hashsum/src/digest.rs, src/uu/hashsum/src/hashsum.rs
=> hashsum: update hex to 0.4.3

src/uu/df/src/df.rs
Replace unsafe code with a safe version of the `statfs()` function
provided by `uucore`.
=> df: use safe wrapper function for statfs() func.

.github/workflows/CICD.yml
Until https://github.com/uutils/coreutils/issues/3210 is fixed
=> Update to ubuntu latest for cross compilation

.github/workflows/CICD.yml
a few changes:
* Add a job to build with rust stable
* Add a job to build with rust nightly
* Change the list of build to use min rust version
=> Various CI changes to unbreak the CI

src/uu/timeout/src/timeout.rs
Factor a helper function `wait_or_kill_process()` out of the main
`timeout()` function. This helper function contains the code to wait
for a child process and send the `SIGKILL` signal if it does not
terminate within a specified amount of time. This does not change the
function of `timeout`, just the organization of the code.
I'm making this pull request to make the code easier to understand in order to make it easier for me (or whomever works on it) to improve the status code handling in `timeout`.
=> timeout: refactor helper func for wait-then-signal

src/uu/df/src/df.rs
Remove the use of the `FsSelector` struct when deciding whether a
filesystem type should be included or excluded from the output
table. Instead, just maintain optional `Vec`s of filesystem types to
exclude and include, and check whether the filesystem type is
contained in one of those. This reduces the amount of code required to
implement these checks, and since the number of types given in the
`include` or `exclude` lists is likely to be small, there should not
be much of a difference in performance.
=> df: remove use of FsSelector abstraction

src/uu/nproc/src/nproc.rs, tests/by-util/test_nproc.rs
It should fix one of the GNU test
=> nproc: Improve the GNU compat

.github/workflows/CICD.yml
Missed something in the previous PR :) (https://github.com/uutils/coreutils/pull/3271)
Now the codecov should be improved as well.
=> Also run unittests in codecov

src/uu/ln/src/ln.rs, tests/by-util/test_ln.rs, util/build-gnu.sh
We haven't a great error message with hard link on the same file
+ Update the GNU error message to match ours
=> ln: make the tests/ln/hard-backup.sh test work

src/uu/df/src/table.rs, tests/by-util/test_df.rs
Use `IUse` instead of `IFree` to calculate `IUse%`.
=> df: fix calculation of IUse%

.github/workflows/GnuTests.yml
more about this release: https://lwn.net/Articles/891574/
=> GNU/Coreutils: update the reference to 9.1

src/uu/df/src/df.rs, tests/by-util/test_df.rs
Solve issue #3366. Make -h and -H override each other (the latest take the priority)
=> df: -h -H shouldn't cause an error #3366

tests/by-util/test_df.rs
Adapt test to work with the new column width handling.
=> df: fix broken "test_df_output_overridden" test

src/uu/df/src/table.rs, tests/by-util/test_df.rs
PR is based on @jfinkels' comment in https://github.com/uutils/coreutils/pull/3386#discussion_r851760031
=> df: remove trailing spaces in rightmost column

tests/by-util/test_stat.rs
These are tests for unfixed issues:
https://github.com/uutils/coreutils/issues/3485
https://github.com/uutils/coreutils/pull/3280
Provided without a fix because I don't know when I will be able to fix these.
=> test_stat: add tests for issues with stdin

.github/workflows/GnuTests.yml
the result can be seen here:
https://github.com/uutils/coreutils/actions/runs/2284215712
=> fix the GNU error detection

tests/by-util/test_uniq.rs
See: https://github.com/uutils/coreutils/issues/3509
=> uniq: Disable one of the gnu test for failing too often

src/uu/df/src/table.rs
Rounds up byte values in the `Size`, `Used`, and `Available` columns.
Fixes #3479.
=> df: round up values if block size is specified

src/uu/fold/src/fold.rs, src/uu/head/src/parse.rs, src/uu/ls/src/ls.rs, src/uu/numfmt/src/format.rs, src/uu/od/src/od.rs, src/uu/od/src/parse_formats.rs, src/uu/od/src/parse_inputs.rs, src/uu/ptx/src/ptx.rs, src/uu/sort/src/sort.rs, src/uu/stat/src/stat.rs, src/uu/stdbuf/src/stdbuf.rs, src/uu/tail/src/parse.rs, src/uu/tsort/src/tsort.rs, src/uu/who/src/who.rs, src/uucore/src/lib/parser/parse_size.rs, tests/by-util/test_ls.rs
These were found by running `cargo +nightly clippy --workspace --all-targets --all-features --`. (This appears in `.pre-commit-config.yaml`.) This is not quite all of the issues it found though. I don't know how to resolve the remaining few.
=> all: clippy fixes

src/uu/dd/src/progress.rs, tests/by-util/test_dd.rs
Update `dd` to only print a concise form of the number of bytes with an SI prefix (like "1 MB" or "2 GB") if the number is at least 1000. Similarly, only print the concise form with an IEC prefix (like "1 MiB" or "2 GiB") if the number is at least 1024. Previously, it was always printing both forms. For example,
$ head -c 999 /dev/zero | dd > /dev/null
1+1 records in
1+1 records out
999 bytes copied, 0.0 s, 999.0 KB/s
$ head -c 1000 /dev/zero | dd > /dev/null
1+1 records in
1+1 records out
1000 bytes (1000 B) copied, 0.0 s, 1000.0 KB/s
$ head -c 1024 /dev/zero | dd > /dev/null
2+0 records in
2+0 records out
1024 bytes (1 KB, 1024 B) copied, 0.0 s, 1.0 MB/s
This matches the behavior of GNU `dd`, even though the format of the concise byte counts is still not quite right. The format can be …
=> dd: only print concise byte counts if count is sufficiently large

src/uu/dir/src/dir.rs, src/uu/ls/src/ls.rs, src/uu/vdir/src/vdir.rs, src/uu/wc/src/wc.rs, src/uu/wc/src/word_count.rs, src/uucore/src/lib/lib.rs, src/uucore/src/lib/mods.rs, src/uucore/src/lib/mods/quoting_style.rs, tests/by-util/test_wc.rs
rebase of #3679 @sylvestre @gkalas8. 
Authorship info has been preserved
=> rebase of #3679:  Fix wc gnu test suite compatibility - Closes: #3678 

src/uu/readlink/src/readlink.rs, tests/by-util/test_readlink.rs
- readlink: fixed panic when symlink loop error happened
- added test for symlink loop when running readlink
=> readlink: symlink loop handling

tests/by-util/test_rm.rs
Add test that fails because of issue #3722
=> tests/rm: add test for issue #3722

tests/by-util/test_cp.rs
=> tests/cp: add test for cp-parents.sh

README.md
* add badge for MSRV
* use the term "Minimum Supported Rust Version (MSRV)"
=> README: add badge for MSRV

src/uu/touch/src/touch.rs, tests/by-util/test_touch.rs
Make `gnu/tests/touch/trailing-slash.sh` pass
=> touch: trailing slashes handling

Cargo.lock, src/uu/tail/Cargo.toml, src/uu/tail/src/tail.rs
=> Update notify 5.0.0 pre.16

src/uu/cp/src/cp.rs, src/uucore/src/lib/macros.rs
Just some more simple cleanup in `uucore`.
=> `uucore` & `cp`: remove `show_error_custom_description` macros `show_usage_error`

src/uu/chcon/src/chcon.rs
Commented about it here: https://github.com/uutils/coreutils/pull/3848#issuecomment-1221337477
=> Fix GNU `tests/misc/chcon-fail.sh` test

src/uu/link/src/link.rs
Fixes the issue mentioned in https://github.com/uutils/coreutils/pull/3876#discussion_r955038735
=> link: move use statement after copyright

.github/workflows/CICD.yml
Many thanks to Aleksandr Chebotov for the help
=> docker: Mount some volumes when building with cross

.github/workflows/CICD.yml, .github/workflows/FixPR.yml
Signed-off-by: Hanif Bin Ariffin <hanif.ariffin.4326@gmail.com>
=> cargo-tree is already part of cargo. Use that instead

src/uu/cp/src/cp.rs
Improve readability of the `copy_on_write_linux()` helper function by employing new helper functions `clone()` and `sparse_copy()`.
This change helps me in preparing a future pull request to improve compatibility of the `--sparse` option with the behavior of GNU cp.
=> cp: make copy_on_write_linux() func more readable

.github/workflows/GnuComment.yml, .github/workflows/GnuTests.yml
Followup on https://github.com/uutils/coreutils/pull/4010
(again needs to be merged before we can test sadly)
=> CI: run GnuComment also if pipeline fails

docs/src/installation.md
My last PR (https://github.com/uutils/coreutils/pull/4048) introduced some spell checker problems and there was a grammatical error :)
=> docs: installation.md fixes

src/uu/cp/src/cp.rs, src/uu/mv/src/mv.rs, tests/by-util/test_cp.rs, tests/by-util/test_mv.rs
=> {cp, mv} -i --update source existing should not do anything and exit 0

src/uu/chcon/src/chcon.rs, src/uu/chgrp/src/chgrp.rs, src/uu/chown/src/chown.rs, src/uu/cp/src/copydir.rs, src/uu/cp/src/cp.rs, src/uu/dd/src/parseargs/unit_tests.rs, src/uu/df/src/df.rs, src/uu/echo/src/echo.rs, src/uu/head/src/head.rs, src/uu/hostname/src/hostname.rs, src/uu/id/src/id.rs, src/uu/ls/src/ls.rs, src/uu/realpath/src/realpath.rs, src/uu/sort/src/sort.rs, src/uu/tail/src/args.rs, src/uu/test/src/test.rs, src/uu/touch/src/touch.rs, src/uu/uniq/src/uniq.rs, src/uu/who/src/who.rs, tests/by-util/test_chown.rs, tests/by-util/test_ls.rs, tests/common/random.rs
Found using the following command (which appears in `.pre-commit.yaml`):
```
cargo +nightly clippy --workspace --all-targets --all-features --
```
=> clippy fixes

src/uu/pwd/src/pwd.rs, tests/by-util/test_pwd.rs
Should fix tests/misc/pwd-option.sh
=> pwd: support the env variable 'POSIXLY_CORRECT'

Cargo.lock, src/uu/dir/Cargo.toml, src/uu/dircolors/Cargo.toml, src/uu/vdir/Cargo.toml
Another round of [`cargo-machete`](https://github.com/bnjbvr/cargo-machete), to trial it again. Mostly no unused dependencies here, great job!
=> Remove unused dependencies

.github/workflows/CICD.yml, .github/workflows/FixPR.yml, .github/workflows/GnuTests.yml
See: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Replace set-output by the GITHUB_OUTPUT variable

.github/workflows/CICD.yml
oups :)
I am surprised that it is working...
=> CI: fix a typo

.github/workflows/CICD.yml, .github/workflows/GnuTests.yml
See https://github.com/mozilla/grcov/pull/893
=> coverage: rename the arg to match a change in grcov

src/uu/dd/src/dd.rs
As an optimization, prevent `dd` from allocating buffers for use in its main loop when `count=0`.
This fixes some of the test cases in the GNU test suite file `tests/dd/no-allocate.sh`.
=> dd: don't allocate buffer if count=0

src/uu/dd/src/dd.rs, tests/by-util/test_dd.rs
Before this commit, if `sparsefile` were a regular file of non-zero size whose contents are all null bytes, then
dd if=sparsefile of=outfile conv=notrunc
would have resulted in `outfile` having zero size as reported by `stat`. After this commit, `outfile` will have the same size as `sparsefile` (even if the contents are represented sparsely by the filesystem).
This fixes `tests/dd/sparse.sh`.
=> dd: correctly set file size when conv=sparse

.github/dependabot.yml
We don't need to move that fast
=> Move the dependabot to weekly

tests/common/util.rs
This pr increases the delay used in the `uchild` tests but also takes other measures to make these tests less prone to such intermittent failures.
Closes #4223
=> tests/util: Fix #4223: intermittent failing uchild tests

tests/by-util/test_cp.rs
=> Ignore some cp tests on android

src/uu/dd/src/parseargs.rs, src/uu/touch/src/touch.rs, tests/by-util/test_dd.rs, tests/by-util/test_install.rs, tests/by-util/test_mktemp.rs, tests/by-util/test_rm.rs, tests/by-util/test_seq.rs, tests/by-util/test_touch.rs
Fixes for `dd` and `touch`; testing fixes/updates for `dd`, `install`, `mktemp`, `rm`, `seq`, and `touch`.
=> Fix usage error production and testing (multiple uutils)

Cargo.lock, src/uu/uname/Cargo.toml, src/uu/uname/src/uname.rs, tests/by-util/test_uname.rs
Update `uname` for newest platform-info, add fixes and tests, and refactor variable names to standards.
=> change/uname ~ update and revise

util/publish.sh
This was the only issue I ran into while publishing. The rest of the script works really well now :)
=> util: fix publish order of uucore_procs and uucore

.github/workflows/CICD.yml, .github/workflows/FixPR.yml, .github/workflows/GnuTests.yml
- `outputs()` function update throughout
- increased baseline SHA ref size to 10 hex digits
- spell-checker updates
- cosmetic comment changes
=> CICD maintainence

src/bin/uudoc.rs, tests/by-util/test_pr.rs, tests/by-util/test_rmdir.rs
Found via
```sh
cargo +nightly clippy --workspace --all-targets --all-features --
```
=> Fixes from nightly version of clippy

.github/workflows/CICD.yml, .github/workflows/GnuTests.yml
=> End the current execution if there is a new changeset in the PR

.github/workflows/GnuTests.yml
We have a list, no need to show them over and over.
They are adding noise:
https://github.com/orgs/uutils/projects/2
=>     GNU: Ignore some intermittent

src/uu/mkdir/mkdir.md
=> fix spell checker error in mkdir.md

src/uucore/src/lib/parser/parse_time.rs
=> fix: Fix panic in multi-byte characters

tests/by-util/test_timeout.rs
=> timeout: add a test to verify that it fails as expected

docs/src/installation.md
See: https://bugs.gentoo.org/895754
=> gentoo has renamed the package

.github/workflows/GnuTests.yml
Some are SKIPPED because of this
=> Install some missing dependencies for the GNU tests

README.md
See: https://github.com/uutils/coreutils/discussions/4466
=> Document how to build in release mode

src/uu/pwd/src/pwd.rs
I just opened a random util to see if I could make some improvements, but `pwd` was already in pretty good shape :)
=> `pwd`: small refactor of some match expressions

tests/by-util/test_date.rs
Regex matching for correctness check.
Tests for format with Minute and Hours added.
=> tests/date: Added tests for date ISO8601 formats.

src/uu/date/src/date.rs, tests/by-util/test_date.rs
=> date: fix invalid argument error for RFC 3339

tests/by-util/test_du.rs
=> test_du: fix unnecessary boolean operation

tests/by-util/test_chown.rs, tests/by-util/test_cp.rs, tests/by-util/test_env.rs, tests/by-util/test_mktemp.rs, tests/by-util/test_nproc.rs, tests/by-util/test_printenv.rs, tests/by-util/test_sort.rs, tests/by-util/test_uptime.rs, tests/by-util/test_users.rs, tests/common/util.rs
=> Remove `keep_env` from the test framework

.github/workflows/freebsd.yml
Closes #4513
1. Check fmt task throw error in annotations here: https://github.com/miles170/coreutils/actions/runs/4539969647
2. Check lint task throw error in annotations here: https://github.com/miles170/coreutils/actions/runs/4539972415
=> CI: linting and formatting checks for FreeBSD

util/build-gnu.sh
We are doing a better job.
Make it FAIL => PASS
=> du: Update the GNU error message to our for tests/du/threshold.sh

.github/workflows/GnuTests.yml
Fix for https://github.com/uutils/coreutils/pull/4728#issuecomment-1503243245
=> CICD: fix full path for the ignore list

src/uu/ls/src/ls.rs
move a lot of content from `from` into dedicated functions
=> Improve the readibility of ls code

.github/workflows/GnuTests.yml
Release notes: https://lists.gnu.org/archive/html/info-gnu/2023-04/msg00006.html
=> GNU/coreutils: update reference to 9.3

.github/workflows/CICD.yml
=> CI: warn if the size of the binary increases by more than 5%

src/uu/cp/src/copydir.rs, src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
related to #4822 but when src is a dir
=> cp: preserve permissions on -r -p --parents

src/uu/rm/src/rm.rs, tests/by-util/test_rm.rs
=> rm: support non-UTF-8 paths

src/uu/more/src/more.rs, tests/by-util/test_more.rs
#2320
This pull request implements the argument: `-s` / `--squeeze`
=> more: implement argument -s / --squeeze

.github/workflows/CICD.yml, .github/workflows/freebsd.yml
because of https://github.com/mozilla/sccache/issues/1789
=> specify the sccache version 

Cargo.lock, src/uu/pr/Cargo.toml, src/uu/pr/src/pr.rs
Closes https://github.com/uutils/coreutils/issues/4934
Undid last commit to add local timezone to test as it caused the test to fail on CI.
=> `pr` use chrono instead of time

Cargo.lock, src/uu/install/Cargo.toml
=> install: remove time crate

src/uu/shred/src/shred.rs, tests/by-util/test_shred.rs
This should fix [#4879](https://github.com/uutils/coreutils/issues/4879)
This is my first contribution, so pardon me if I missed something, do let me know and I will fix it promptly!
=> fixed shred -u for windows

GNUmakefile
Thanks to this, it is easier to generate these files:
* make manpages
* make completions
=> make: split the manpage / completions generation into their target

CONTRIBUTING.md
=> Add the Perl Power Tools impl

util/build-gnu.sh
For some reason the `CheckScripts` workflow failed to commit this change in the main repository.
=> build-gnu.sh: indent comment

Cargo.lock, deny.toml
Some updates that renovate had issues with because of `cargo deny`.
=> Some updates of deps

Cargo.toml
Followup on: https://github.com/uutils/coreutils/pull/5148
=> chore(deps): update is-terminal and tempfile in Cargo.toml

README.md
Closes https://github.com/uutils/coreutils/issues/5188
I've put some temporary text in for the dev docs. I'll try to bring those back up later this week.
=> README: update links to docs

src/uucore/Cargo.toml
This PR makes the dependencies related to the `sum` feature optional.
=> uucore: make deps of "sum" feature optional

util/build-gnu.sh
This PR fixes some formatting issues shown by `shfmt`.
=> build-gnu.sh: fix formatting issues

src/uu/echo/echo.md
See the issue here:
https://uutils.github.io/coreutils/book/utils/echo.html
=> echo's doc doesn't show correctly

src/uu/cat/src/splice.rs, src/uu/cksum/src/cksum.rs, src/uu/env/src/env.rs, src/uu/hashsum/src/hashsum.rs, src/uu/sort/src/ext_sort.rs
removing useless mutability mostly.
=> uu clippy fix proposal.

.github/workflows/CheckScripts.yml
This PR removes the auto committing from `CheckScript.yml` because the committing always fails. 
Fixes https://github.com/uutils/coreutils/issues/5119
I'm not sure whether the changed workflow works correctly as I don't know how to test it.
=> ci: remove committing from CheckScripts.yml

src/uu/whoami/src/whoami.rs
Corresponding nushell PR: https://github.com/nushell/nushell/pull/10488
=> Expose `whoami` function (for nushell!)

util/run-gnu-test.sh
Otherwise, the error can be cryptic
=> run-gnu-test.sh: show if we can't find the file

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
=> cp: fix cp -dR --no-preserve=links d c should have different inodes

src/uu/chmod/src/chmod.rs, src/uu/install/src/mode.rs, src/uu/mkdir/src/mkdir.rs, src/uu/mknod/src/parsemode.rs, src/uucore/src/lib/features/mode.rs
and some ride along simplification
=> Replace list of digit by is_digit

tests/by-util/test_ls.rs
See
https://github.com/uutils/coreutils/pull/5341#issuecomment-1741855958
=> ls -R1: add a test to replicate GNU's recursive.sh

src/uu/head/src/head.rs, src/uu/head/src/parse.rs
This PR adds some empty lines to make the code look less cramped.
=> head: add some empty lines

src/uu/expr/src/syntax_tree.rs, src/uu/expr/src/tokens.rs
This PR adds some empty lines to make the code look less cramped.
=> expr: add some empty lines

Cargo.lock, Cargo.toml, src/uu/ls/Cargo.toml
=> ls: move to `uutils-term-grid`

src/uu/cat/src/cat.rs, src/uu/env/src/env.rs, src/uu/logname/src/logname.rs, src/uu/printenv/src/printenv.rs, src/uu/uname/src/uname.rs, src/uu/unlink/src/unlink.rs, src/uu/whoami/src/whoami.rs, src/uu/yes/src/yes.rs
This PR removes all "last synced with" comments as I think they are outdated.
=> Remove "last synced with" comments

.github/workflows/code-quality.yml, src/uu/base32/src/base_common.rs, src/uu/cat/src/cat.rs, src/uu/csplit/src/csplit.rs, src/uu/cut/src/cut.rs, src/uu/dirname/src/dirname.rs, src/uu/du/src/du.rs, src/uu/fold/src/fold.rs, src/uu/head/src/head.rs, src/uu/install/src/install.rs, src/uu/ls/src/ls.rs, src/uu/mkfifo/src/mkfifo.rs, src/uu/mv/src/mv.rs, src/uu/nl/src/helper.rs, src/uu/nl/src/nl.rs, src/uu/numfmt/src/numfmt.rs, src/uu/paste/src/paste.rs, src/uu/ptx/src/ptx.rs, src/uu/shuf/src/shuf.rs, src/uu/sort/src/numeric_str_cmp.rs, src/uu/split/src/split.rs, src/uu/sum/src/sum.rs, src/uu/tail/src/follow/files.rs, src/uu/tail/src/follow/watch.rs, src/uu/test/src/parser.rs
Enabled clippy::implicit_clone checkes and fixed all warnings
=> Fix clippy::implicit_clone

Cargo.toml
=> Cargo.toml: fix typo

src/uu/expr/src/syntax_tree.rs, tests/by-util/test_expr.rs
=> `expr`: check prefix operation

.vscode/cspell.dictionaries/acronyms+names.wordlist.txt, src/uucore/src/lib/features/fs.rs
=> uucore: add support for loongarch64

src/uu/fmt/src/fmt.rs, src/uu/fmt/src/linebreak.rs, src/uu/fmt/src/parasplit.rs
I saw some opportunities to clean up `fmt`. Each commit contains a small atomic improvement. I recommend reviewing the commits separately.
This should not have changed any of the behaviour of `fmt` it's all just small changes.
=> `fmt`: a collection of small refactors

tests/by-util/test_mv.rs
This PR renames two tests and moves one of them a bit.
=> mv: rename two tests

docs/src/installation.md
I also checked that it works on a Windows machine :)
=> docs: add winget installer

tests/by-util/test_sort.rs
I made all CI fail by merging https://github.com/uutils/coreutils/pull/5681 😄
=> `test/sort`: run cargo fmt

src/uucore/src/lib/features/fsext.rs
Couldn't resist doing some cleanup here. And frankly there's much more to be done 😄
=> Fsext refactor

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
=> cp: debug with --update=none should show 'skipped'

.github/workflows/fuzzing.yml
=> Disable fuzzing seq until issue #5724 is fixed

src/uu/cat/src/cat.rs, src/uu/touch/src/touch.rs
Some code refactoring to address cognitive complexity in `touch` and `cat`.
=> Address cognitive complexity

src/uu/head/src/head.rs
Improve the execution of tests/head/head-c.sh
=> head: -c allocate memory as needed

src/uu/more/more.md, src/uu/test/src/test.rs, src/uu/test/test.md, src/uu/vdir/vdir.md
This PR should address 3 more of the docs issues from https://github.com/uutils/coreutils/issues/5692 , regarding `more`, `test` and `vdir` commands.The last issue remaining would be the one regarding the usage string of everything based on `hashsum`.
=> Fix docs issues.

util/build-gnu.sh
It will avoid a rebuilding when doing:
bash util/build-gnu.sh && bash util/run-gnu-test.sh   ../gnu/tests/xxx
=> GNU: Improve the built

src/uu/mv/src/mv.rs
This PR moves a statement to simplify a condition.
=> mv: simplify condition

util/build-gnu.sh
to transform an ERROR into FAIL
=> Workaround https://github.com/uutils/coreutils/issues/5766

README.md
https://github.com/uutils/coreutils/issues/3336#issuecomment-1206292911 :
> We moved to project mgmt for this:
https://github.com/orgs/uutils/projects/1
=> META bug: moved to project mgmt

src/uucore/src/lib/features/signals.rs
=> Fix typo in signals.rs

src/uucore/src/lib/features/format/mod.rs, tests/by-util/test_seq.rs
=> seq: adjust some error messages. GNU's are better

util/build-gnu.sh
No longer needed since github.com/uutils/coreutils/pull/5789 landed
=> Remove the tests/cp/link-heap.sh workaround

src/uucore/src/lib/features/format/num_format.rs
Closes https://github.com/uutils/coreutils/issues/5807
=> `printf`: use 0 instead of 0o as octal prefix

src/uu/seq/seq.md, src/uucore_procs/src/lib.rs
Closes https://github.com/uutils/coreutils/issues/5933
@LucasLehmann could you check that this fixed your issue?
I made the macros fail if they can't find the text so that we can diagnose similar issues sooner.
=> `seq`: fix about text not found

src/uu/ln/ln.md
=> ln: fix help text

fuzz/fuzz_targets/fuzz_printf.rs
=> fuzzing: set LC_ALL=C when running GNU printf

util/build-gnu.sh
Should make tests/pr/pr-tests.pl pass
=> pr: relax some error messages

util/compare_gnu_result.py, util/size-experiment.py
You can get more about shebang in there: https://realpython.com/python-shebang/
Please check and give me feedback.
=> added shebang to run python scripts

src/uu/shred/src/shred.rs, tests/by-util/test_shred.rs
should make tests/shred/shred-remove pass
=> shred: some small improvements

src/uu/factor/src/cli.rs, tests/by-util/test_factor.rs
Easy drive-by fix while fielding the next few steps in #5998.
=> factor: correctly handle repeated flag

util/show-utils.sh
Closes https://github.com/uutils/coreutils/issues/6117
I'm not really sure what happened, maybe the format changed with newer rust versions? Anyway, I tried to fix up the jq query here and simplify it a bit in the process.
=> show-utils.sh: fix jq query

src/uu/uniq/src/uniq.rs, tests/by-util/test_uniq.rs
Closes https://github.com/uutils/coreutils/issues/6122
=> `uniq`: print version and help on stdout again

CONTRIBUTING.md
=> Doc: Explain that it is allowed to look at OpenBSD or Apple sources

src/uu/dirname/src/dirname.rs, tests/by-util/test_dirname.rs
This is work towards https://github.com/uutils/coreutils/issues/5998. Turns out, it's pleasantly simple to fix dirname.
=> dirname: accept repeated flag

.github/workflows/code-quality.yml
=> fix macos ci instability on clippy with retry

README.md
=> Readme: fix links to docs

tests/by-util/test_env.rs
This PR removes the dependency on GNU `env` in the tests, thus getting rid of the "version for the reference coreutil 'env' is higher than expected; expected: 8.3, found: 9.5" messages when running the tests on my machine.
=> env: remove dependency on GNU env in tests

tests/by-util/test_cp.rs
This PR removes all `if !condition { panic!() }` in the tests as I think it is not idiomatic test code.
=> cp: remove panics in tests

src/uu/date/src/date.rs, tests/by-util/test_date.rs
=> date: fix date get timezone error while set utc time (#6495)

tests/by-util/test_date.rs
Seems like
- https://github.com/uutils/coreutils/issues/3463 is closable
- https://github.com/uutils/coreutils/issues/2685 too
=> date: add test

src/uucore/src/lib/features/checksum.rs, tests/by-util/test_cksum.rs
=> cksum: read the next file when the first is missing or invalid

src/uu/sync/src/sync.rs
subtask of issue5487, replacing `crash!` by using USimpleError.
please let me know if anything is not correct.
=> sync: replace crash! with USimpleError

src/uu/hashsum/src/hashsum.rs, src/uucore/src/lib/features/checksum.rs, tests/by-util/test_hashsum.rs
=> hashsum: Return err when only --strict or --quiet is given

src/uu/dd/src/parseargs.rs, tests/by-util/test_dd.rs
=> dd: fix issue #5905 (different error msg from GNU)

src/uu/ln/src/ln.rs, tests/by-util/test_ln.rs
=> `ln`: allow final destination directory when using `-nf`

src/uu/cat/src/cat.rs, tests/by-util/test_cat.rs
Fix issue #6248 about `cat` and add a test related to this issue.
=> Cat: Fix issue #6248

.github/workflows/GnuTests.yml
```
2024-10-16T07:22:20.6386088Z SKIP: tests/misc/xattr
2024-10-16T07:22:20.6386173Z ======================
2024-10-16T07:22:20.6386178Z 
2024-10-16T07:22:20.6386369Z ./tests/misc/xattr.sh: line 42: getfattr: command not found
2024-10-16T07:22:20.6386526Z xattr.sh: skipped test: failed to get xattr of file
```
=> GNU tests: install attr

src/uu/mkdir/src/mkdir.rs, src/uu/rmdir/src/rmdir.rs, tests/by-util/test_mkdir.rs, tests/by-util/test_rmdir.rs
=> mkdir/rmdir: require arguments

.github/workflows/CICD.yml
to send email only when ready
closes: #6859
=> publish: by default, put it as draft

src/uu/du/src/du.rs, tests/by-util/test_du.rs
=> du: fix the display with --inodes

src/uu/tr/Cargo.toml, src/uu/tr/src/tr.rs, src/uucore/src/lib/features/fs.rs, tests/by-util/test_tr.rs
should fix tests/misc/read-errors.sh for real
=> tr: generate an error for real if the input is a directory

tests/by-util/test_cut.rs
This PR applies some trivial refactorings to the tests to hopefully improve them.
=> cut: some test refactorings

util/why-error.md
https://github.com/uutils/coreutils/pull/7025
=> remove test  t tests/chmod/symlinks from the list

util/why-error.md
https://github.com/uutils/coreutils/pull/7116
=> doc: df test now passes

util/why-error.md
by https://github.com/uutils/coreutils/pull/7145
=> why-error: fixed tests/seq/seq-precision

Cargo.lock, src/uu/du/Cargo.toml, src/uu/du/src/du.rs, src/uu/groups/Cargo.toml, src/uu/groups/src/groups.rs, src/uu/mktemp/Cargo.toml, src/uu/mktemp/src/mktemp.rs, src/uu/nohup/Cargo.toml, src/uu/nohup/src/nohup.rs, src/uu/tsort/Cargo.toml, src/uu/tsort/src/tsort.rs
follow: https://github.com/uutils/coreutils/pull/7175
=> Move other programs to thiserror

src/uu/printf/src/printf.rs, tests/by-util/test_printf.rs
=> printf: Show warning message in case of excess arguments

fuzz/Cargo.lock
Simply running `cargo update` in the `fuzz` folder.
=> fuzz: update dependencies

tests/by-util/test_base64.rs, tests/by-util/test_cp.rs, tests/by-util/test_dd.rs, tests/by-util/test_du.rs, tests/by-util/test_env.rs, tests/by-util/test_pwd.rs, tests/common/util.rs, tests/test_util_name.rs
Adds a method to test suit for mounting a tmpfs at a given mount point
=> mount temp fs

.vscode/cspell.dictionaries/workspace.wordlist.txt, Cargo.lock, src/uu/mv/Cargo.toml, src/uu/mv/src/mv.rs, tests/by-util/test_mv.rs
=> Make mv command fallback to copy only if the src and dst are on different device

tests/common/util.rs
Address issue in #7356 ([comment](https://github.com/uutils/coreutils/pull/7356#discussion_r1973348386))
=> test-utils: Add fails_with_code() function

util/why-error.md
https://github.com/uutils/coreutils/pull/7408
=> Remove a head test from the list of failure

src/uu/echo/src/echo.rs, src/uucore/src/lib/features/format/escape.rs, src/uucore/src/lib/features/format/mod.rs, src/uucore/src/lib/features/format/spec.rs, tests/by-util/test_printf.rs
Refit of #7210 by @aryalaadi
I had some trouble rebasing so I just copied the changes manually to a new branch, so your name disappears from the commits. Sorry for that, I'll try to find a way to make you a co-author of these changes
Fixes #7202
=> printf: fix octal escape parsing

tests/by-util/test_cp.rs
Also update existing test to ensure output is empty.
=> cp: create failing test for #7455

src/uu/stat/src/stat.rs, src/uucore/src/lib/features/fsext.rs
Maybe useful to (partially) understand what is going on in #7583.
=> stat: Print what kind of "weird" mode it is, if it's "weird"

src/uu/sum/src/sum.rs
Update sum to properly propagate errors from file-reads, including implementing a retry on ErrorKind::Interrupted. Also switch to using writeln! rather than println! to prevent crashes if stdout is directed to /dev/full
=> sum: Rework some error handling

src/uucore/Cargo.toml
Gate optional dependencies behind the appropriate feature flag.
=> uucore: Minor fix to optional dependences

src/uu/df/src/df.rs
Closes #7536
I'm not particularly happy with the solution for `FilesystemTypeBothSelectedAndExcluded`, but it does pass the tests.
I'd be happy to receive any feedback to improve it.
Thanks!
=> df: migrate OptionsError to thiserror

src/uu/dd/src/dd.rs, src/uu/env/src/split_iterator.rs, src/uu/expr/src/syntax_tree.rs, src/uu/more/src/more.rs, src/uu/numfmt/src/format.rs, src/uu/sort/src/merge.rs, src/uu/sort/src/sort.rs, src/uu/split/src/split.rs, src/uu/tail/src/follow/watch.rs, src/uu/test/src/parser.rs, src/uu/tr/src/operation.rs
Used this command:
```shell
cargo clippy --fix --workspace --all-targets -- -A clippy::all -W clippy::unnested_or_patterns
cargo fmt --all
```
=> chore: fix `clippy::unnested_or_patterns`

src/uucore/src/lib/features/tty.rs
Fixes https://github.com/uutils/coreutils/issues/7732 and fixes https://github.com/uutils/coreutils/issues/7733
=> Fix the implementation of Display and TryFrom<&str> for Teletype

.github/workflows/fuzzing.yml
https://github.com/sylvestre/coreutils/actions/runs/14429413097
=> fuzzing: add a summary and enable printf

util/build-gnu.sh
Not that crazy anymore, fixed by #7675.
@jfinkels
=> util/build-gnu.sh: Accept hex float as sleep parameter

tests/by-util/test_sleep.rs, tests/by-util/test_timeout.rs
- **timeout: add tests**
- **sleep: add tests**
addresses #7678 (comment)
@drinkcat just to make sure you see this.
=> add tests against '0 in sleep/timeout durations

src/uu/od/src/multifilereader.rs, src/uu/od/src/od.rs, tests/by-util/test_od.rs
Fixes #7666
For `od` utility, if client specifies `-N` maximum bytes to be read
then ensure stdin is left pointing to the next byte when `od` exits.
To do this...
- Bypass standard buffering on stdin.
- Instantiate BufReader further up the stack to maintain performance.
=> od: fix for issue #7666

src/uucore/src/lib/features/parser/num_parser.rs
Especially after splitting the `parse` function in multiple chunks, this makes the code a bit easier to read, despite the fact that `parse` is still inherently a complex function.
@tertsdiepraam FYI, I think I like it better now, using slices consistently instead of a mix of slices and iterators. And if I understand correctly how slices work, this should be mostly equivalent, performance wise.
@Qelxiros FYI too, some small changes to stuff you touched (lifetimes mostly, carving out suffix parsing to a common function)
=> uucore: num_parser: Operate on slices, instead of iterator

src/uu/ls/src/ls.rs
Gets closer to GNU `ls`, ~8% gain vs current main.
```
cargo build -r -p uu_ls && taskset -c 0 hyperfine --warmup 100 -L ls ls,target/release/ls,./ls-main "{ls} -lR /var/lib .git || true"
Benchmark 1: ls -lR /var/lib .git || true
Time (mean ± σ):      27.2 ms ±   0.6 ms    [User: 11.9 ms, System: 15.0 ms]
Range (min … max):    26.5 ms …  28.6 ms    109 runs
Benchmark 2: target/release/ls -lR /var/lib .git || true
Time (mean ± σ):      27.9 ms ±   0.9 ms    [User: 12.2 ms, System: 15.2 ms]
Range (min … max):    26.9 ms …  35.2 ms    104 runs
Benchmark 3: ./ls-main -lR /var/lib .git || true
Time (mean ± σ):      30.2 ms ±   1.4 ms    [User: 14.2 ms, System: 15.4 ms]
Range (min … max):    29.3 ms …  42.4 ms    96 runs
Summary
ls -lR /var/lib .git || true ran
1.02 ± 0.04 times faster than …
```
=> ls: More performance optimizations

src/uu/mknod/src/mknod.rs
This PR applies two refactorings to `uumain` in order to separate the handling of `mode` and `dev`.
=> mknod: refactor `uumain`

src/uu/install/src/install.rs, tests/by-util/test_install.rs
Fixed issue with install deleting file when attempting to install to same file.
=> install: fixes issue #7795

tests/by-util/test_date.rs
Follow up to https://github.com/uutils/parse_datetime/pull/128. Since the changes were in a separate crate / repo, it makes sense to have some tests in coreutils itself.
=> date: add tests for relative weekdays

tests/uutests/Cargo.toml
=> fixed link to repo on uutests docs

README.md, docs/src/test_coverage.md
* Updated README and documentation to switch to SVG graphs after https://github.com/uutils/coreutils-tracking/pull/24
Also see for findutils: https://github.com/uutils/findutils/pull/545
=> Switched to SVG graphs

src/uu/shred/src/shred.rs
This PR continues the work on issue #7870. It adds 4K alignment of output data to better matching with GNU shred behavior. Updating the alignment, but not the application's block size, allows to avoid the performance degradation observed in [shred: use 4K block](https://github.com/uutils/coreutils/pull/7886)  PR.
``` bash
echo a > foo && cargo run -q --features shred shred -v -n1 foo && du -b foo
shred: foo: pass 1/1 (random)...
65536   foo
```
``` bash
echo a > foo && cargo run -q --features shred shred -v -n1 foo && du -b foo
shred: foo: pass 1/1 (random)...
4096    foo
```
``` bash
echo a > foo && shred -v -n1 foo && du -b foo
shred: foo: pass 1/1 (random)...
4096    foo
```
I also tested a few more control values (1,4095,4096,4097,65535,65536,65537) to compare GNU shred with uutils …
=> shred: add 4K data alignment

tests/by-util/test_timeout.rs
=> timeout: add hex parsing test

flake.nix
=> flake.nix: Add cspell

src/uu/cksum/src/cksum.rs
This PR removes a duplicate unit test. We already test the same functionality in [`uucore/checksum`](https://github.com/uutils/coreutils/blob/main/src/uucore/src/lib/features/checksum.rs#L1286)
=> cksum: remove duplicate unit test

src/uu/tee/src/tee.rs, tests/by-util/test_tee.rs
To comply with [POSIX standard](https://pubs.opengroup.org/onlinepubs/9799919799.2024edition/utilities/tee.html) `tee` implementation must not buffer its output, so we replace `std::io::copy` implementation that does buffering with the custom one.
Fixes #8198
=> tee: remove output buffering

Cargo.toml
sorted and simplified a few minor things in the root Cargo.toml
=> chore: minor Cargo.toml linting

Cargo.toml, src/uu/echo/src/echo.rs, tests/by-util/test_echo.rs
fixes https://github.com/uutils/coreutils/issues/8308
=> echo: print help if not posixly correct and only argument is --help

src/uu/tail/src/tail.rs
gnu coreutils will show end of device for block devices. In current implementation this is skipped as a block devices are recognized as untailable.
The change ensures that we first try to output the end of any file and only then tell the observer that the file is not observable.
Gnu coreutils:
```
$ tail -c 16 /dev/sdc 
tail: cannot open '/dev/sdc' for reading: Permission denied
$ sudo tail -c 16 /dev/sdc |hexdump
0000000 d566 3260 cee2 32e5 7ce3 50ee 49c7 81e0
0000010
```
Before change:
```
$ target/debug/coreutils tail -c 16 /dev/sdc 
$ sudo target/debug/coreutils tail -c 16 /dev/sdc | hexdump
```
After change:
```
$ target/debug/coreutils tail -c 16 /dev/sdc 
tail: cannot open '/dev/sdc' for reading: Permission denied
$ sudo target/debug/coreutils tail -c 16 /dev/sdc | hexdump
0000000 …
```
=> tail: show end of device

Cargo.toml, src/uu/chroot/src/chroot.rs, src/uu/cp/src/cp.rs, src/uu/head/src/parse.rs, src/uu/id/src/id.rs, src/uu/stty/src/stty.rs, src/uu/sync/src/sync.rs, src/uu/uptime/src/uptime.rs
=> Enable some pedantic rules

.github/workflows/CICD.yml
We can at least use 4 cores instead of 1.
=> .github/workflows/CICD.yml: Speed up Build/SELinux

src/uu/mv/Cargo.toml, src/uu/mv/locales/en-US.ftl, src/uu/mv/src/mv.rs, src/uucore/src/lib/features/selinux.rs, tests/by-util/test_cp.rs, tests/by-util/test_install.rs, tests/by-util/test_mkdir.rs, tests/by-util/test_mkfifo.rs, tests/by-util/test_mknod.rs, tests/by-util/test_mv.rs
=> mv: add support for selinux and add minor refactor 

.github/workflows/freebsd.yml, GNUmakefile
=> Do not build SELinux programs on FreeBSD when using make

src/uu/cp/src/copydir.rs, src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
Fixes https://github.com/uutils/coreutils/issues/8555
=> cp: fix copying current directory (.) to existing directory

Cargo.lock, Cargo.toml, fuzz/Cargo.lock, fuzz/uufuzz/Cargo.toml, src/uucore_procs/Cargo.toml, util/publish.sh, util/update-version.sh
I burnt the version 0.2.1 with some experiments to fix https://github.com/uutils/coreutils/issues/8569
=> Prepare version 0.2.2

src/uu/mv/src/mv.rs, tests/by-util/test_mv.rs
=> mv: support moving source to a symlink directory

src/uucore/Cargo.toml, src/uucore/locales/en-US.ftl, src/uucore/locales/fr-FR.ftl, src/uucore/src/lib/features/safe_traversal.rs
and add support for translations
=>  safe traversal: use the nix crate instead of unsafe calls to libc 

src/uu/date/src/date.rs, tests/by-util/test_date.rs
=> date: use --reference=file to display the file modification time

src/uu/expr/src/syntax_tree.rs, tests/by-util/test_expr.rs
Should make tests/expr/expr-multibyte pass
=> expr: fix some multibyte issues

src/uu/hashsum/src/hashsum.rs
follow up https://github.com/uutils/coreutils/pull/8650/files
=> hashsum: remove the usage of the mut

src/uu/ls/benches/ls_bench.rs, src/uu/numfmt/benches/numfmt_bench.rs, src/uu/sort/benches/sort_bench.rs, src/uu/sort/benches/sort_locale_bench.rs, src/uu/tsort/benches/tsort_bench.rs, src/uu/wc/benches/wc_bench.rs
I don't think we get much values for having a lot of run
=> Codspeed: reduce the number of tests and increase some values for long tests

src/uu/df/Cargo.toml, src/uu/df/src/df.rs, tests/by-util/test_df.rs
Fixes: https://github.com/uutils/coreutils/issues/8677
=> df: follow symlinks
