src/uu/cksum/src/cksum.rs, src/uu/hashsum/src/hashsum.rs, tests/by-util/test_cksum.rs, tests/by-util/test_hashsum.rs
Should make tests/cksum/cksum-a.sh  pass
=> cksum: Improve the GNU compat

src/uucore/src/lib/features/fsext.rs
This PR removes support for Bitrig, a discontinued OpenBSD fork. Rust support for it has been removed years ago (see https://github.com/rust-lang/rust/issues/60743).
=> uucore: remove support for Bitrig

src/uu/stdbuf/src/stdbuf.rs
This PR renames `dragonflybsd` to `dragonfly` because the former is an incorrect `target_os`.
=> stdbuf: rename `dragonflybsd` to `dragonfly`

src/uu/cp/src/copydir.rs, src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
=> ``cp``: Added overwrite detection for existing symlinks

tests/by-util/test_tail.rs
This PR uses `#[ignore]` instead of `#[cfg(disable_until_fixed)]` to disable tests. It fixes several "unexpected `cfg` condition name: `disable_until_fixed`" warnings from the `unexpected_cfgs` lint (see, for example, https://github.com/uutils/coreutils/actions/runs/8996946984/job/24714228670?pr=6378#step:11:548)
=> tail: use `#[ignore]` to disable tests

src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs
fixes #6227 
The ``get_metadata()`` function seemed to try to deference to the non existent file. We change it to directly get the metadata of the symlink itself incase the deference fails.
=> Fix ls: panicking on dangling symlink with ``--color=auto -l``

tests/by-util/test_cp.rs, tests/by-util/test_tail.rs
This PR uses `#[ignore]` instead of `#[cfg(disabled_until_fixed)]` to disable tests. I overlooked those cases in https://github.com/uutils/coreutils/pull/6388 because of the slightly different attribute name ("disable**d**_until_fixed" vs. "disable_until_fixed").
=> cp/tail: use `#[ignore]` to disable tests

src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs
=> ls: fix quoting alignment, add tests for default quoting style in TTY and quoting alignment

src/uu/cp/src/cp.rs
This PR removes two unnecessary `target_os = "macos-12"` entries to fix the corresponding "unexpected `cfg` condition value: `macos-12`" warnings (see, for example, https://github.com/uutils/coreutils/actions/runs/9108537605/job/25039512756#step:11:287).
=> cp: remove `target_os = "macos-12"`

Cargo.lock, Cargo.toml, fuzz/Cargo.toml
This PR downgrades `libc` to `0.2.153` because `0.2.154` got yanked.
=> Downgrade `libc` to `0.2.153`

src/uu/hashsum/src/hashsum.rs, tests/by-util/test_hashsum.rs
will help with tests/cksum/b2sum.sh
=> hashsum: improve the blake2 --tag export

src/uucore/src/lib/features/utmpx.rs
This PR is an attempt to fix some of the errors that make the `Build (macos-latest, x86_64-apple-darwin, feat_os_macos)` job fail in the CI. It should fix the tests of `pinky`, `uptime`, and `who`, which currently fail with:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IndeterminateOffset', src/uucore/src/lib/features/utmpx.rs:192:62
```
For some unknown reason, `OffsetDateTime::now_local()` from `time` is unable to determine the offset and returns an error. The proposed fix simply removes the `unwrap` and sets a default offset in the error case. I don't know whether this is correct, as I develop "blind", without macOS.
=> uucore/utmpx: use UTC if offset can't be resolved

src/uu/cp/src/copydir.rs, src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
this pr tries to fix gnu test case "link deref" for cp utility 
these are the changes made:
1. when trying to copy a folder without `-R` before throwing "-r not specified" error, cp would make sure that source is not a symlink and noderef option is not given. This way, when both of them are given, it would treat it as a file and copy the symlink itself.
2.  to match gnu cp's behavior, `-R` won't disable dereference if `--link` is given
=> cp: link-deref gnu test fix

src/uu/pinky/src/platform/unix.rs
This PR fixes the same issue as https://github.com/uutils/coreutils/pull/6413 but in a different place. It should fix the remaining `pinky` tests in the failing `Build (macos-latest, x86_64-apple-darwin, feat_os_macos)` job in the CI.
=> pinky: use UTC if offset can't be determined

tests/by-util/test_chmod.rs, tests/by-util/test_cp.rs, tests/by-util/test_mkdir.rs, tests/common/util.rs
This pr tries to add umask manipulation to test util, this would allow changing umask in a contained manner instead of doing it globally.
=> util: added umask manipulation

src/uu/cp/src/copydir.rs, tests/by-util/test_cp.rs
Hi, this pr tries to fix parent-perm-race gnu test case. this test tries to check the temporary permissions of directories created by cp which might be too permissive under some conditions.
This is how gnu's cp behaves, when `--preserve=mode`  or  `--preserve=ownership` is given whenever it creates a directory it disables some permissions for `group` and `others`. I'm not entirely sure why gnu's cp is doing this, but my assumption is that when the user tries to preserve mode or ownership they're expecting some security guarantees in the destination directory, but having permissions that are too permissive even for a short period of time might compromise that security guarantee. 
#4211 is a pr that fixes a similar issue
=> cp: parent-perm-race gnu fix

src/uu/sort/src/sort.rs, src/uucore/src/lib/parser/parse_size.rs, tests/by-util/test_du.rs, tests/by-util/test_head.rs, tests/by-util/test_od.rs, tests/by-util/test_sort.rs, tests/by-util/test_split.rs, tests/by-util/test_stdbuf.rs, tests/by-util/test_tail.rs, tests/by-util/test_truncate.rs
This PR removes all `#[cfg(not(target_pointer_width = "128"))]` to fix several "unexpected `cfg` condition value: `128`" warnings in the CI (see, for example, https://github.com/uutils/coreutils/actions/runs/9151519099/job/25157662399#step:11:377).
=> tests: remove all `#[cfg(not(target_pointer_width = "128"))]`

Cargo.toml
This PR fixes an "unresolved import `uucore::mode`" error when running tests with `cargo test --features="<util name>" --no-default-features`.
=> Cargo.toml: enable uucore's `mode` feature

src/uu/tr/src/operation.rs, src/uu/tr/src/tr.rs, tests/by-util/test_tr.rs
To simplify the checks for [:upper:] and  [:lower:], I have separated the character classes into a sub-enum.
Additionally, I have implemented the divergent tr behaviour from the issue into a testcase.
Fixes issue #6342
=> tr: disallow classes besides [:upper:]/[:lower:] in set2 when translating

.github/workflows/CICD.yml
macos-latest is now an arm64 runner, it used to an amd64 runner but with https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/ macos-latest is no longer an am64 runner. 
This PR fixes this. By changing;
-> macos-14 to macos-latest
-> macos-latest to macos-13
=> fix: macos-latest is now arm64

deny.toml
This PR adds the "Boost Software License 1.0" (BSL-1.0) to the list of allowed licenses. It's added because it's used by `lockfree-object-pool`, a new dependency of `zip` (see https://github.com/uutils/coreutils/pull/6426).
=> deny.toml: allow BSL-1.0 as license

src/uu/df/src/columns.rs
Similarly to the `Used` column, GNU df pads an extra space to the right of the `Size` column.
=> df: fix size column padding

tests/by-util/test_df.rs
This PR fixes an incorrect test related to https://github.com/uutils/coreutils/pull/6433 and adds an additional test to ensure the `Used` column is left-padded with a space.
=> df: fix incorrect test & add another test

src/uucore/src/lib/features/fsext.rs
Enables stat to recogise a BcacheFS filesystem - for example:
$ ./target/debug/stat -f /
File: "/"
ID: 64b40636928f3ee7 Namelen: 512     Type: bcachefs
Block size: 512        Fundamental block size: 512
Blocks: Total: 2044464374 Free: 295830135  Available: 291278902
Inodes: Total: 2375400624 Free: 2366641080
=>   src/uucore/src/lib/features/fsext.rs: Add magic for bcachefs

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
This PR was initially intended to fix GNU test preserve-mode, but as it turns out, there was nothing wrong with how `uu-cp` preserved mode. The test was failing because overriding wasn't working properly. The test involved copying a FIFO with options `-a --preserve=mode`. The `-a` was supposed to disable copying contents, but it was getting overridden by `--preserve` wrongly. So, this PR now tries to fix the overriding of attributes.
**changes in behavior**
- when a flag like `-a` which expands to `-dR --preserve=all` is given and a --preserve is given after that, cp would only override the --preserve part.
- cp could handle `--preserve` and `--no-preserve` together in a single command, for example `cp --preserve=mode,ownership --no-preserve=ownership --preserve=link f f2` would preserve …
=> cp: gnu test case preserve-mode fix

Cargo.lock, src/uu/cksum/src/cksum.rs, src/uu/hashsum/src/hashsum.rs, src/uucore/Cargo.toml, src/uucore/src/lib/features/checksum.rs, src/uucore/src/lib/macros.rs, tests/by-util/test_cksum.rs, tests/by-util/test_hashsum.rs
Summary of the change:
* Move the common code into checksum
* Create a structure HashAlgorithm to handle the algorithm (instead of the 3 variables)
* Use the same function for cksum & hashsum for --check (perform_checksum_validation)
* Use the same for function for the hash generation (digest_reader)
* Add unit tests
* Add integration tests
* Fix some incorrect tests
=> cksum/hashsum: refactor the common code.

src/uucore/Cargo.toml
This PR enables the `sum` feature for the `checksum` feature in `Cargo.toml`. I noticed the missing feature when trying to run `cargo test --features=checksum`.
=> uucore: enable `sum` feature for `checksum` feature

src/uu/seq/BENCHMARKING.md
This MR fix a little type in the documentation of `seq` benchmarking documentation file.
=> seq: fix typo in benchmarking documentation file

src/uu/tr/src/operation.rs, tests/by-util/test_tr.rs
If there is a [:lower:] or [:upper:] in set2, then there must be a [:lower:] or [:upper:] at the same logical position in set1
So
```bash
$tr '[:upper:]' '[:lower:]' # works
$tr '1[:upper:]' '[:lower:]' # doesnt
```
To accomplish this change I have done the following things:
- flatten error checks (take early exits from  `solve_set_characters` instead of nesting `if`s)
- simplify CharStar (`[c*]`) handling code by simply replacing CharStar with a CharRepeat of appropriate length
- switch flatten() from `Sequence -> u8` to `Sequence -> Char`
The main idea here is that to correctly implement the tr behaviour, one has to flatten everything but [:upper:]/[:lower:] into the underlying string of chars and then check if  the character class in the one set is at the same position in the other …
=> tr: A [:lower:]/[:upper:] in set2 must be matched in set1

src/uu/head/src/head.rs, src/uu/join/src/join.rs, src/uu/numfmt/src/numfmt.rs, src/uu/shuf/src/shuf.rs, src/uu/sort/src/sort.rs, src/uu/split/src/filenames.rs, src/uu/split/src/split.rs, src/uu/tail/src/chunks.rs, src/uucore/src/lib/features/sum.rs, tests/by-util/test_shuf.rs
This PR fixes clippy warnings introduced by Rust 1.79 from the [legacy_numeric_constants](https://rust-lang.github.io/rust-clippy/master/index.html#/legacy_numeric_constants) and [use_self](https://rust-lang.github.io/rust-clippy/master/index.html#/use_self) lints.
=> clippy: fix warnings introduced by Rust 1.79

Cargo.lock, Cargo.toml, deny.toml, src/uu/pr/src/pr.rs
This PR bumps `itertools` from `0.12.1` to `0.13.0` and adds it to the skip list in `deny.toml`. And in `pr` it uses `chunk_by()` from `itertools` instead of the deprecated `group_by()`.
=> Bump `itertools` and fix use of deprecated function

src/uu/tr/src/operation.rs, tests/by-util/test_tr.rs
I think we should fall in line with GNU behaviour here.
If you really think you need to do this: 
```
tr [:lower:]123 [:upper:]
```
you can already do this:
```
tr [:lower:]123 [:upper:]Z
```
which does the same thing and is more explicit about which character is repeated to fill set2.
(Although generally, I think that if you are at that point you are already using the wrong tool).
However, I do not have strong opinions on this and would happily implement this the other way  if someone is clearly in favour of  that.
=> Refuse to translate if set1 is longer than set2 and set2 ends in a character class

src/uu/cp/src/copydir.rs, src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
This PR aims to fix the GNU cp-parents test case. The following behaviors have been changed in this PR:
- if dereference is enabled and --preserve attributes are specified, instead of copying the attributes of the symlink itself, cp will try to copy the attributes of the actual file the symlink points to.
- --parents will not fail if an absolute path is given (I couldn't make this work on Windows).
- For GNU compatibility, cp will not return an error if setting ownership fails.
=> gnu `cp-parents` test case

src/uu/od/src/partialreader.rs
=> od: use `u64::MAX` instead of `max_value()`

src/uu/shuf/src/shuf.rs
Fix warnings from legacy_numeric_constants lint
Fix uutils/coreutils#6478
=> shuf: use usize::MAX instead of std::usize::MAX

src/uu/tr/src/operation.rs, tests/by-util/test_tr.rs
If complementing and translating with a character class, there can only be one unique character in set2.
The underlying issue, [y*] not being expanded to "" was fixed "accidentally" in a previous restructuring of tr. I have simply added the error check here.
=> Refuse to translate if set2 contains more than one unique characters and set1 contains a character class

src/uu/ls/src/dired.rs, src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs
regressed because of https://github.com/uutils/coreutils/pull/6139
=> ls --dired: adjust our code after GNU v9.5

Cargo.lock, Cargo.toml, src/uu/ls/src/colors.rs, src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs, util/build-gnu.sh
This pr tries to fix gnu test case color-norm for ls util
these behaviors that are changed
- ls could now apply normal colour to non file names when --color is passed
thanks @tavianator for helping me with issue.
=> ls: gnu `color-norm` test fix

src/uucore/src/lib/features/checksum.rs
This PR simplifies the signature of the `determine_regex` function from:
```rust
fn determine_regex(filename: &OsStr, input_is_stdin: bool, lines: &[String]) -> UResult<(Regex, bool)>
```
to
```rust
fn determine_regex(lines: &[String]) -> Option<(Regex, bool)>
```
=> uucore/checksum: simplify `determine_regex()`

src/uu/hashsum/src/hashsum.rs, src/uucore/src/lib/features/checksum.rs, tests/by-util/test_hashsum.rs
Should fix tests/cksum/b2sum.sh
=> hashsum/b2sum: when the checksum file is untagged, detect the size      

Cargo.toml
To build all the docs with features
```
[package.metadata.docs.rs]
all-features = true
```
Fix: https://github.com/uutils/coreutils/issues/6442
Documentation:
- https://docs.rs/about/metadata
=> build all features on docs.rs

Cargo.toml
This PR adds a "expensive_tests" feature in order to fix "unexpected `cfg` condition value: `expensive_tests`" warnings in the nightly builds in the CI (see, for example, https://github.com/uutils/coreutils/actions/runs/9673817439/job/26688539353?pr=6496#step:7:630).
=> Cargo.toml: add "expensive_tests" feature

src/uu/ls/src/colors.rs, src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs, util/build-gnu.sh
This pr tries to fix gnu test case `color-clear-to-eol`.
This test tries to check when a colored file name that is too long is wrapped, it will append a clear-to-end-of-line ANSI code. GNU's ls does this because in some terminals, when ls tries to print at the last line of the terminal window and needs to scroll the text up in order to print the new lines, the background color would stretch up to the end of the line.
for example 
```shell
seq 200 # inorder to fill the terminal window
touch zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz.foo # create a long named file so that it would wrap
env TERM=xterm  LS_COLORS="*.foo=0;31;42" TIME_STYLE=+T ls  --color=always zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz.foo
``` 
without the patch, it would look like this
with the patch 
Behaviors …
=> ls: gnu `color-clear-to-eol` fix

src/uu/users/src/users.rs
Fix uutils/coreutils#6508
---
Tests on OpenBSD: build and lint with `clippy` OK
```bash
$ target/debug/coreutils users
fox
$ target/debug/coreutils users tests/fixtures/users/openbsd_utmp
root test test user
```
=> users: fix lint error needless_borrows_for_generic_args on OpenBSD

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
This PR reports preserved hardlinks.
Before this PR, the reporting occured after the hardlink creation.
The PR calls the verbose output before the preserved harlink processing.
Fixes #6267
=> cp: fix preserved hardlinks are not reported in --verbose

src/uu/touch/src/touch.rs, tests/by-util/test_touch.rs
Should fix https://github.com/uutils/coreutils/issues/2639
=> `touch`: change message when directory

src/uucore/src/lib/lib.rs
Trying to do #5068 
https://docs.rs/uucore/latest/uucore/trait.Args.html
=> document uucore::Args #5068

src/uucore/src/lib/lib.rs
Related to #5069
https://docs.rs/uucore/latest/uucore/fn.args_os.html
https://docs.rs/uucore/latest/uucore/fn.get_utility_is_second_arg.html
https://docs.rs/uucore/latest/uucore/fn.set_utility_is_second_arg.html
=> documents functions - #5069

build.rs
This PR skips the "expensive_tests" feature when building a map of crates. It should fix the "use of undeclared crate or module `expensive_tests`" error in https://github.com/uutils/uutils.github.io/pull/35
=> build.rs: skip "expensive_tests", not a crate

src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs
Close #6492
- Fix error output when hyperlink options combines with recursive
=> ls: fix error sub dir output

.vscode/cspell.dictionaries/jargon.wordlist.txt, Cargo.lock, src/uu/sort/Cargo.toml, src/uu/sort/src/sort.rs, src/uu/sort/src/tmp_dir.rs, tests/by-util/test_sort.rs, util/gnu-patches/tests_sort_merge.pl.patch
should make the gnu test tests/sort/sort-merge.pl pass
=> sort: improve the error mgmt with --batch-size

src/uu/ls/src/dired.rs, src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs
=> ls: fixed dired option (-D) not outputting datetime and parent dir byte offsets

src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs
Should fix gnu/tests/ls/stat-dtype.sh
=> ls: when -CF is passed, use a tab. closes: #5396

src/uucore/src/lib/features/fsxattr.rs, tests/by-util/test_cat.rs, tests/by-util/test_chown.rs, tests/by-util/test_cp.rs, tests/by-util/test_du.rs, tests/by-util/test_head.rs, tests/by-util/test_install.rs, tests/by-util/test_ls.rs, tests/by-util/test_nohup.rs, tests/by-util/test_pinky.rs, tests/by-util/test_split.rs, tests/by-util/test_stat.rs, tests/by-util/test_stdbuf.rs, tests/by-util/test_tail.rs, tests/by-util/test_test.rs, tests/by-util/test_touch.rs, tests/common/util.rs
- Disabled failed tests on OpenBSD
```bash
$ cargo nextest run --no-default-features --features "unix" --no-fail-fast
(...)
Summary [ 291.195s] 3288 tests run: 3288 passed, 56 skipped
```
- Disabled tests on OpenBSD in `src/uucore/src/lib/features/fsxattr.rs`
```bash
$ cargo nextest run --no-fail-fast --all-features -p uucore
(...)
Summary [   3.850s] 124 tests run: 124 passed, 0 skipped
```
Fix #6541
=> Disable failed tests on OpenBSD

src/uu/env/src/split_iterator.rs, src/uu/env/src/string_parser.rs, src/uucore/src/lib/features/colors.rs, src/uucore/src/lib/features/format/num_parser.rs, src/uucore/src/lib/features/pipes.rs, src/uucore/src/lib/features/quoting_style.rs, src/uucore/src/lib/features/ranges.rs, src/uucore/src/lib/features/ringbuffer.rs, src/uucore/src/lib/features/signals.rs, src/uucore/src/lib/features/update_control.rs, src/uucore/src/lib/features/version_cmp.rs, src/uucore/src/lib/lib.rs, src/uucore/src/lib/macros.rs, src/uucore/src/lib/mods/display.rs, src/uucore/src/lib/mods/error.rs, src/uucore/src/lib/mods/io.rs, src/uucore/src/lib/mods/line_ending.rs, src/uucore/src/lib/mods/os.rs, src/uucore/src/lib/mods/posix.rs, src/uucore/src/lib/parser/parse_size.rs, src/uucore/src/lib/parser/shortcut_value_parser.rs, src/uucore_procs/src/lib.rs, src/uuhelp_parser/src/lib.rs
Fix #5066
In the futur: enable `#![deny(missing_docs)]` for `uucore` (for now it's commented)
=> add docs - fix #5066

src/uu/df/src/df.rs, src/uu/df/src/filesystem.rs, src/uu/stat/src/stat.rs, src/uucore/src/lib/features/fsext.rs
remove all `crash!` in fsext and modify some related files. I think those were the final `crash!`s.
relating issue #5487
I also noticed that the cargo doc in CICD has been failing since commit fb48e7d.
=> fsext: remove crash!

tests/by-util/test_date.rs
These tests check that days and month with a single digit are correctly handled.
Subsitute to #6401
=> tests(date): Add tests for #6392

src/uu/tr/src/operation.rs, tests/by-util/test_tr.rs
=> tr: Raise error if set2 is too big on complemented class

src/uu/cut/src/cut.rs, src/uu/tr/src/tr.rs, src/uucore/src/lib/lib.rs, tests/by-util/test_tr.rs
=> tr: Accept non UTF-8 arguments for sets

src/uu/mv/src/mv.rs, tests/by-util/test_mv.rs
tries to fix #6577
**Behaviors changed**
- mv would remove the destination file first, if we are trying to move the file between different partitions and the destination is a symlink
=> mv: gnu test case `to-symlink` fix

tests/by-util/test_mv.rs
=> mv: inter partition copying test code cleanup

src/uucore/src/lib/features/process.rs
Sorry, I closed pr by mistake :( #6590
This pr will add getsid function for process.rs to detect the session ID of pid.
The session ID plays a full role, and he usually plays the role of a process group identifier on Linux systems (or is it the POSIX standard?). The session ID plays a full role as a kind of process group identifier. In addition to that, this pr will also fulfill the role of getting the session leader.
However, because of the need to call libc, the pr involves unsafe code, so this pr will be ready for review after due consideration.
=> uucore: Add `getsid` for `process.rs`

src/uu/cksum/src/cksum.rs, src/uucore/src/lib/lib.rs, tests/by-util/test_cksum.rs
=> cksum: accept non-UTF-8 filenames

tests/by-util/test_basename.rs, tests/by-util/test_realpath.rs
This PR adds two words to `spell-checker:ignore` that started to fail the "Style/spelling" job in the CI (see, for example, https://github.com/uutils/coreutils/actions/runs/10318729989/job/28565689683?pr=6626#step:5:16). The failures are probably due to a new release of `cspell`.
=> basename,realpath: add words to `spell-checker:ignore`

src/uu/test/src/error.rs, src/uu/test/src/test.rs, tests/by-util/test_test.rs
Should fix tests/test/test-diag.pl
=> test: -o arg should trigger an error

Cargo.lock, fuzz/Cargo.toml
renovate has a problem with updating `tempfile`, so doing it manually.
=> Bump `tempfile` from `3.10.1` to `3.11.0`

Cargo.lock
This PR bumps the `windows-targets` crates from `0.48.0` to `0.48.5` and from `0.52.0` to `0.52.6`
=> Bump windows-targets crates

Cargo.lock, Cargo.toml, tests/by-util/test_ls.rs
This pr tries to fix #6536 
- when one suffix is specified more than once with different cases and with different styles, then ls would only do a case-sensitive matching.
This is marked as draft because it's dependent on this ~~[pr](https://github.com/sharkdp/lscolors/pull/86)~~ [pr](https://github.com/sharkdp/lscolors/pull/87)
=> ls: gnu test case `color-ext` fix

Cargo.lock, Cargo.toml, deny.toml, src/uu/cat/src/cat.rs, src/uu/wc/src/count_fast.rs, src/uu/wc/src/countable.rs, src/uu/yes/src/splice.rs, src/uu/yes/src/yes.rs, src/uucore/src/lib/features/pipes.rs
This PR bumps `nix` from `0.28` to `0.29` and `ctrlc` from `3.4.4` to `3.4.5` and fixes compilation errors in our code due to API changes in `nix`. And it adds an additional version of `windows-sys` to the skip list in `deny.toml`.
=> Bump `nix` & `ctrlc` and adapt code to API changes in `nix`

build.rs
Without this guard, the build script is rebuilt as soon as any file within the package is changed. This includes files created by external tools such as IDE.
Fix #6640
=> Do not rebuild the build script unless necessary

Cargo.lock, deny.toml
This PR bumps `parking_lot_core` from `0.9.9` to `0.9.10` in order to get rid of an older version of `redox_syscall`. And removes `redox_syscall` from the skip list in `deny.toml`.
=> Bump `parking_lot_core`

tests/common/util.rs
Eliding named lifetimes elicits a warning in Rust 1.83+.
=> tests: do not elide named lifetimes

src/uu/ls/src/colors.rs, src/uu/ls/src/ls.rs
This would help us reduce a lstat() call on ``ls/colors.rs``
=> ``ls``: Changed unwrap_or and ``or`` option handling to lazy evaluated ``unwrap_or_else`` and ``or_else``

src/uu/mkdir/src/mkdir.rs, tests/by-util/test_mkdir.rs
=> mkdir: do not change mode of existing directories

.github/workflows/CICD.yml
The `Code Coverage (windows-latest, windows, nightly-x86_64-pc-windows-gnu)` CI step seems to always fail for all PRs, and has been broken for several months now: #6534.
Instead of wasting even more CPU time (and perhaps money?) on a broken CI step that apparently noone wants to fix it, let's just deactivate it for now. If someone wants to fix it later, a FIXME points at the open issue #6686, which also serves as a good place to discuss potential fixes, should someone ever be interested.
=> ci: disable broken code coverage on windows

Cargo.lock, Cargo.toml, src/uu/tail/src/platform/windows.rs
This PR bumps `windows-sys` from `0.48` to `0.59` and adapts `tail` to an API change.
=> Bump `windows-sys` & adapt `tail` to API change

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
The `PathBuf` value parser from `clap` cannot be used directly as it does not (rightly) accept empty file names. 
Fix #6177
=> cp: treat an empty file name as a non-existing file

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
=> fix: add arg count for cp

Cargo.lock, deny.toml
This PR bumps `selinux-sys` from `0.6.9` to `0.6.12` and `fts-sys` from `0.2.9` to `0.2.11`, thus removing some dependencies. It also removes `itertools` from the skip list in `deny.toml`.
=> Bump `selinux-sys` and `fts-sys`

src/bin/coreutils.rs
This PR adds `--list` to the help output of the multi-call binary.
=> bin/coreutils: add `--list` to help output

src/uu/cp/src/cp.rs, src/uu/mv/src/mv.rs, src/uucore/src/lib/features/update_control.rs, src/uucore/src/lib/parser/shortcut_value_parser.rs, tests/by-util/test_cp.rs, tests/by-util/test_mv.rs
fix for #6598
Behviours changed:
-  `-n' would now silently fail to copy a file when the destination already exists
- added  --update=none-fail to cp and mv
- arg parser would show a suggestion if parsing failed because of ambiguous value
=> mv: gnu test case mv-n compatibility

src/uu/tr/src/tr.rs, tests/by-util/test_tr.rs
This warning is being emitted whenever the input string ends with a backslash, even if the backslash is escaped.
=> tr: fix unescaped trailing backslash warning

.pre-commit-config.yaml
These are not being fixed, so it does not make sense to constantly take on new lints. The fmts may never be stabilized. Currently, you can not even commit, because it errors out. At least switch to lints that make it to stable when they are released.
=> Change the git pre-commit actions to work on stable.

tests/by-util/test_tr.rs
I noticed that there is a test marked as "ignore" because it fails on Windows. This PR enables this test on unix.
=> tr: enable ignored test on unix

.github/workflows/android.yml
The emulator executable has a warning that enabling or disabling metrics collection (for the emulator developers) will at some point become blocking. Since there's nothing sensitive about CI runs, this commit enables them now.
See any recent Android CI run to see the warning in question.
=> Android CI: enable emulator metrics

.cargo/config.toml, Cargo.toml
This prevents unnecessary rebuilds when mixing runs of `cargo clippy` and other cargo commands (e.g., `cargo c && cargo clippy && cargo c` no longer rebuilds).
=> move lints from rustflags to Cargo.toml

.pre-commit-config.yaml
This is in response to #6715: e8bb8dffa1b1af05b7be184c820f5c72a2b8c1da
The pre-commit actions have a higher MSRV than the overall project (1.70.0), so if 1.70.0 is the configured default, this lead to problems: #6730
This PR fixes the situation by specifying 'stable', whatever that means on the user's system.
Fixes #6730.
=> Change the git pre-commit actions to *actually* use stable

tests/by-util/test_tr.rs
Specifically:
- check_against_gnu_tr_tests_e: Yes, the test is about octal interpretation.
- check_against_gnu_tr_tests_ross_0a: Yes, the [Y*] generates multiple Y's, which causes conflicting replacements, which is why the operation is rejected.
- check_against_gnu_tr_tests_ross_0b: Same, plus a newline character was accidentally forgotten.
- check_against_gnu_tr_tests_fowler_1: Apparently the problem was fixed at some point.
Inspired by #6737.
=> tr: enable ignored tests that have already been fixed

src/uu/printf/src/mod.rs
The main file in directories like this is `main.rs` (in contrast to subdirectories, where it would be `src/foo/mod.rs`), and no other `src/mod.rs` exists, indicating that this was just an error all the way back in 0892ad3cdecb8ad38f1419f92d697f0fcb0a2058.
Found by #6721.
Fixes #6721.
=> printf: delete unused file

.github/workflows/GnuTests.yml
This PR bumps ubuntu from `22.04` to `24.04` in the GNU tests workflow and installs the `libselinux1-dev` package to fix the build issue mentioned in https://github.com/uutils/coreutils/pull/6742#issuecomment-2378428594
=> ci: use ubuntu v24 for GNU tests workflow

src/uu/cat/src/cat.rs
This PR removes some duplicate code I noticed while reviewing #6763
=> cat: use `write_end_of_line()`  to avoid duplicate code

src/uu/users/src/users.rs
`users` allows only a single file argument whereas our code implies there are multiple file arguments possible. This PR renames some variables and uses clap's `get_one()` function instead of `get_many()`.
=> users: use `Option` instead of `Vec` for file arg

src/uu/cat/src/cat.rs, tests/by-util/test_cat.rs
https://github.com/uutils/coreutils/issues/5186
See linked issue for details
=> cat: fix #5186 by adding explicit flush.

src/uu/users/src/users.rs
Fix uutils/coreutils#6771
---
No error for `users` tool on OpenBSD with clippy
```bash
$ cargo clippy --all-targets -puu_users -- -W clippy::manual_string_new -D warnings
(...)
Checking uucore v0.0.27 (/home/fox/dev/rust-coreutils.git/src/uucore)
Checking uu_users v0.0.27 (/home/fox/dev/rust-coreutils.git/src/uu/users)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 14.90s
```
=> users: fix lint error manual_unwrap_or_default on OpenBSD

Cargo.toml
Accidentally lost this in #6751, thankfully it looks like no merged PRs triggered it in the meantime.
=> add back use_self clippy warning

src/uu/join/BENCHMARKING.md, src/uu/join/src/join.rs
In my benchmarks, this shows about 20% better performance when using `join -i`.
=> join: avoid extra allocations when using `-i`

src/uu/paste/src/paste.rs, tests/by-util/test_paste.rs
Also: refactored the delimiter processing logic
=> paste: permit the delimiter list to be empty

CONTRIBUTING.md
The link to the git book gave 404 and the link to windows VMs was not formatted the same way as other links in the document.
Broken links were mentioned in open issue: https://github.com/uutils/coreutils/issues/6602 , which could have referred to the link I fixed even if it was not specified? Anyway the links explicitly mentioned are not broken anymore so maybe the issue could also be closed
=> CONTRIBUTE.md: Update broken link and formatting of link

src/uu/cp/src/platform/linux.rs
There are 2 fixes:
- `pwrite` does not guarantee that all bytes will be written, `write_all_at` is a proper wrapper over it
- `sparse_copy_without_hole` (triggered on ZFS) can eat RAM if file is large and there are not enough holes; now the write happens at max 16 MiB chunks (as far as I tested, it saturates SSD anyways without much CPU)
I have tested it with checking sha256sum of a 4 GiB file.
=> cp: fix possible OOM and partial write with large files

util/gnu-patches/tests_tsort.patch
but will still fail.
Currently:
```
2024-10-16T07:22:20.6275735Z --- only-one.1	2024-10-16 07:11:51.980024380 +0000
2024-10-16T07:22:20.6275907Z +++ only-one.E	2024-10-16 07:11:51.984024374 +0000
2024-10-16T07:22:20.6276011Z @@ -1,2 +1,5 @@
2024-10-16T07:22:20.6276133Z -tsort: extra operand 'g'
2024-10-16T07:22:20.6276299Z -Try 'tsort --help' for more information.
2024-10-16T07:22:20.6276445Z +error: unexpected argument 'g' found
2024-10-16T07:22:20.6276519Z +
2024-10-16T07:22:20.6276622Z +Usage: tsort [OPTIONS] FILE
2024-10-16T07:22:20.6276696Z +
2024-10-16T07:22:20.6276838Z +For more information, try '--help'.
```
=> tsort.pl: adjust error message

Cargo.lock, Cargo.toml, src/uu/test/Cargo.toml, src/uu/test/src/test.rs
All of the specific functions are covered by relibc (as of Redox 0.9 at least).
=> Get rid of redox-specific code

src/uucore/src/lib/mods/panic.rs
This PR adds `#[allow(deprecated)]` to "fix" the warnings "use of deprecated type alias `std::panic::PanicInfo`: use `PanicHookInfo` instead" from the lint jobs in the CI (see, for example, https://github.com/uutils/coreutils/actions/runs/11393908726/job/31703171797?pr=6789#step:7:350).
=> uucore: allow use of deprecated `PanicInfo`

src/uucore/src/lib/features/checksum.rs, tests/by-util/test_cksum.rs, tests/by-util/test_hashsum.rs
As #6603 implicitly implemented commented line support, I moved it into its own PR, with proper testing.
**TL;DR**:
This change make the checksum verification system ignore lines starting with `#`, treating them as empty lines.
Example:
```
$ echo 'foo-content' > foo
$ cksum --algo=sha1 foo | tee CHECKSUM
SHA1 (foo) = 058ab38dd3603703b3a7063cf95dc51a4286b6fe 
$ echo '# Comment' >> CHECKSUM 
$ cat CHECKSUM
SHA1 (foo) = 058ab38dd3603703b3a7063cf95dc51a4286b6fe
$ cksum --check CHECKSUM
foo: OK
```
The changes similarly apply to `hashsum` and its derivatives.
=> cksum/hashsum: Support for commented lines in checksum files

src/uu/tsort/BENCHMARKING.md, src/uu/tsort/src/tsort.rs
This pull request is an attempt to rework the current tsort implementation in order to allow for better performance. 
I finally had some time to give it a shot after I mentionned it in #4931 with @tertsdiepraam 
It also tries to mimic gnu tsort output. 
Please share any suggestions.
=> tsort refactoring proposal

src/uu/echo/src/echo.rs, tests/by-util/test_echo.rs
Bug was reported, with root cause analysis, by kkew3 Added tests were derived from test cases provided by kkew3 See https://github.com/uutils/coreutils/issues/6741
=> echo: handle multibyte escape sequences

src/uucore/src/lib/features/checksum.rs, tests/by-util/test_cksum.rs
=> cksum: fix error handling

src/uu/echo/src/echo.rs, tests/by-util/test_echo.rs
While reviewing https://github.com/uutils/coreutils/pull/6803 I noticed the double negation `if !no_newline`. This PR moves the negation operator to a different place and renames the var so we can write `if trailing_newline`. The PR also removes an unnecessary `no_stderr()` in a test.
=> echo: remove double negation

src/uucore/src/lib/features/checksum.rs, src/uucore/src/lib/lib.rs, tests/by-util/test_cksum.rs
Second part of splitting #6603.
This PR adds support for non-UTF-8 checksum file content for `cksum` and `hashsum` validation tools.
In practice, given a CHECKSUM file with the following content, non-UTF-8 characters can appear in 2 places:
- in the filename
- in a comment
All the other places are either algorithm name, which should be ASCII, or hexa/base64 digest, which should be ASCII as well.
```
$ cat CHECKSUM
SHA1 (filename-might-have-non-utf-8) = 058ab38dd3603703b3a7063cf95dc51a4286b6fe
```
The most important step is to get rid of the call to `BufRead::lines()` to iterate on the lines of the CHECKSUM file, otherwise, it panics on non-UTF-8 characters.
This change makes heavy use of `String`/`OsString`/`Vec<u8>` conversion, which happen to not be equally treated on all platforms.
=> cksum/hashsum: Support for non-UTF-8 input in checksum files

src/uucore/src/lib/lib.rs, src/uucore_procs/src/lib.rs, tests/by-util/test_sleep.rs, tests/common/util.rs
Fixes https://github.com/uutils/coreutils/issues/6759
Test procedure (verifies that a single SIGSEGV stops a program):
```
ecordonnier@lj8k2dq3:~/dev/coreutils$ ./target/release/coreutils sleep 100 &
[1] 4175464
ecordonnier@lj8k2dq3:~/dev/coreutils$ kill -11 $(pidof coreutils)
ecordonnier@lj8k2dq3:~/dev/coreutils$
[1]+  Segmentation fault      (core dumped) ./target/release/coreutils sleep 100
```
=> uucore: disable default signal-handlers added by Rust

src/uu/mkdir/src/mkdir.rs, tests/by-util/test_mkdir.rs
Make `--parent` overrides itself when provided more than once. Fixes #6828
=> mkdir: allow --parent to be provided more than once

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
=> cp: normalize path when checking for duplicate source

src/uu/mv/src/mv.rs, tests/by-util/test_mv.rs
=> mv: gnu test `dup-src` compatibilty 

src/uu/sort/src/sort.rs
On OpenBSD 7.6 (release October 2024), Rust version = 1.81.0 => we can now enable `clippy::suspicious_open_options` for lint with `clippy`.
Revert commit ee4392e30cfdcd4c464b0faa0af1ed79d8c0a752
---
Tests OK with clippy (Rust 1.81 on OpenBSD 7.6) for `sort`:
```bash
$ cargo clippy --all-targets -puu_sort -- -W clippy::manual_string_new -D warnings
(...)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.61s
```
=> sort: enable clippy::suspicious_open_options on OpenBSD

src/uu/cksum/src/cksum.rs, src/uu/hashsum/src/hashsum.rs, src/uucore/src/lib/features/checksum.rs, tests/by-util/test_cksum.rs
Now that #6782, #6793 and #6815 have landed, it is time to achieve the rework of `checksum.rs` started in #6654.
This will allow us to fix #6572, #6614 and #6653.
This PR mainly tries to split the massive `perform_checksum_verification` in smaller functions, and to get rid of the `&mut ChecksumResult` that is passed everywhere, which makes it very difficult to understand where the global state of the program is modified.
Also, it adds ignored tests for future features (it will prevent too many conflicts when rebasing future PRs on each other).
Next PRs will focus on reworking the algorithm detection behavior, in particular for blake2b size guessing,
Regex detection behavior which for now prevents us from encountering both hexa and base64 digits in the same file.
=> checksum: prepare further behavior fix with a rework

Cargo.toml
solving https://github.com/uutils/coreutils/issues/6867.
I have test-run the `util/update-version.sh` from 0.0.28 to 0.0.29 and it correctly identifies the four version strings and the resulting workspace passes all the `cargo test` cases.
=> fix(deps): crates import compatible uucore

.clippy.toml, .github/workflows/CICD.yml, Cargo.toml, README.md, tests/by-util/test_tee.rs
This PR bumps the MSRV from `1.70` to `1.77`. I used `1.77` because of #6755. It also fixes a clippy error from the [ref_as_ptr](https://rust-lang.github.io/rust-clippy/master/index.html#ref_as_ptr) lint.
=> Bump MSRV to `1.77`

src/uu/mv/src/mv.rs, tests/by-util/test_mv.rs, util/gnu-patches/tests_dup_source.patch
+ adjust a GNU test
Should make tests/mv/dup-source.sh pass
=> mv: fix the output of an error message

Cargo.lock, Cargo.toml, deny.toml
This PR bumps `thiserror` from `1.0.69` to `2.0.3` and adds `thiserror` and `thiserror-impl` to the skip list in `deny.toml`.
=> Bump `thiserror` from `1.0.69` to `2.0.3`

Cargo.lock, src/uu/stdbuf/src/libstdbuf/Cargo.toml
This PR manually bumps `cpp` and `cpp_build` from `0.5.9` to `0.5.10` because `renovate` has a problem with updating them: they show up in the dependency dashboard but no PRs are created.
=> Bump `cpp` and `cpp_build` from `0.5.9` to `0.5.10`

tests/by-util/test_mv.rs
So far `std::thread::sleep` was used in the tests to ensure that `fileA` is older than `fileB`. With this PR, the same is done by calling `set_modified` on the "older" file, thus speeding up the tests.
=> mv: remove `sleep` in tests

src/uucore/src/lib/features/checksum.rs, tests/by-util/test_cksum.rs
This PR further rework `checksum.rs` to get rid of entangled variable processing.
It also partly fixes #6576, for the case where the digest has an odd length (it may still fail in case the length is even but still wrong)
=> checksum: Further rework

tests/by-util/test_cp.rs
This PR removes some `sleep()` calls in tests and uses `set_modified()` instead to ensure `fileA` is older than `fileB`.
=> cp: remove some `sleep()` calls in tests

tests/by-util/test_env.rs
Currently, when running `cargo test --features=env --no-default-features` some tests fail because they depend on other features. This PR fixes this issue by adding the missing `cfg` attributes to the failing test functions.
=> env: add missing `cfg` attributes to tests

src/uu/tr/src/operation.rs, tests/by-util/test_tr.rs
This PR is to fix issue #6821. 
I add `parse_octal_up_to_three_digits_with_warning` which is similar to `parse_octal_up_to_three_digits` but can print warning. Becuase `parse_octal_up_to_three_digits` is alse used in other cases, and those cases should not output the warning. With two versions, we can avoid printing the same warning more than once. 
Some of the other functions are also added "with_warning" version.
=> tr: Add ambiguous octal escape warning

src/uu/csplit/src/csplit.rs, src/uu/cut/src/matcher.rs, src/uu/cut/src/searcher.rs, src/uu/date/src/date.rs, src/uu/dd/src/dd.rs, src/uu/dd/src/numbers.rs, src/uu/df/src/df.rs, src/uu/env/src/string_parser.rs, src/uu/env/src/variable_parser.rs, src/uu/fmt/src/linebreak.rs, src/uu/fmt/src/parasplit.rs, src/uu/join/src/join.rs, src/uu/od/src/inputdecoder.rs, src/uu/od/src/multifilereader.rs, src/uu/shuf/src/shuf.rs, src/uu/sort/src/merge.rs, src/uu/split/src/filenames.rs, src/uu/split/src/split.rs, src/uu/tail/src/chunks.rs, src/uu/timeout/src/timeout.rs, src/uu/wc/src/utf8/read.rs, src/uucore/src/lib/features/sum.rs, tests/by-util/test_dd.rs, tests/by-util/test_du.rs, tests/by-util/test_env.rs, tests/by-util/test_ls.rs, tests/common/util.rs
`The following explicit lifetimes could be elided: 'a`
=> Fix new clippy warnings

src/uu/du/src/du.rs, tests/by-util/test_du.rs
Should fix:
tests/du/hard-link.sh
=> du: deduplicate the input

src/bin/uudoc.rs, src/uu/chcon/src/chcon.rs
This PR fixes two additional warnings from the [needless_lifetimes](https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes) lint. They show up when running `cargo clippy --all-features --all-targets`.
=> uudoc,chcon: fix `needless_lifetimes` warnings

src/uu/tr/src/operation.rs, src/uu/tr/src/tr.rs, tests/by-util/test_tr.rs
tested by tests/misc/read-errors
=> tr: generate an error if the input is a directory

src/uu/comm/src/comm.rs, tests/by-util/test_comm.rs
tested by tests/misc/read-errors
=> comm: generate an error if the input is a directory

src/uucore/src/lib/features/perms.rs
This PR fixes a todo and simplifies some code by using ORs on bytes instead of using a `match`.
=> uucore/perms: use ORs instead of `match` (fix todo)

src/uu/mv/src/mv.rs, tests/by-util/test_mv.rs
When using `mv d/f d`, GNU `mv` fails with a "same file" error whereas uutils `mv` doesn't fail. This PR makes uutils `mv` fail, too.
=> mv: show "same file" error for `mv d/f d`

src/uu/mv/src/mv.rs, tests/by-util/test_mv.rs
=> Revert "mv: show "same file" error for `mv d/f d`"

src/uu/du/src/du.rs
`Path::is_dir` does another call to `stat` but we can reuse the metadata we already have.
Also `Path::is_dir` traverses symbolic links which is only right if `-L` was passed.
~1.13x speedup on my test directory.
```
> cargo build --release
> measure-command { .\target\release\coreutils.exe du --apparent-size "test folder" }
TotalSeconds      : 11.0101422
```
```
> cargo build --release
> measure-command { .\target\release\coreutils.exe du --apparent-size "test folder" }
TotalSeconds      : 9.7109226
```
=> du: Reuse existing metadata instead of calling path.is_dir() again

src/uucore/src/lib/features/backup_control.rs, tests/by-util/test_mv.rs
see https://github.com/uutils/coreutils/pull/6040#issuecomment-2016746488
the gnu mv:
```plaintext
hamflx@hamflx-workstation:~/coreutils/test$ find . -delete && mkdir C D E && touch C/c D/d E/e
hamflx@hamflx-workstation:~/coreutils/test$ mv -T --backup=numbered C E/
hamflx@hamflx-workstation:~/coreutils/test$ tree -a
.
├── D
│   └── d
├── E
│   └── c
└── E.~1~
└── e
3 directories, 3 files
```
the uu_mv:
```plaintext
hamflx@hamflx-workstation:~/coreutils/test$ find . -delete && mkdir C D E && touch C/c D/d E/e
hamflx@hamflx-workstation:~/coreutils/test$ ../target/debug/mv -T --backup=numbered C E/
hamflx@hamflx-workstation:~/coreutils/test$ tree -a
.
├── D
│   └── d
└── E
└── c
2 directories, 2 files
```
=> mv: fix invalid numbered backup path

src/uu/more/src/more.rs
Work towards (but definitely does not close): https://github.com/uutils/coreutils/issues/6397
This just reduces the number of strings that are allocated. We're still at 5x the file though. Even though technically, we don't need to keep the file in memory at all.
=> `more`: reduce memory usage a bit

src/uu/install/src/install.rs, tests/by-util/test_install.rs
Fix #6435.
As is suggested by the original issue, the creation of the destination file is delegated to `fs::copy` which creates the file with default mode `0644`. This makes the file readable by other users before the final `chmod` is done, which is potentially unsafe and inconsistent with GNU install.
Since the current implementation unconditionally removes the destination path before the copy, creating the file with a minimal `u=rw` permission would not hurt the copy. This patch implements this (for unix).
=> install: create destination file with safer modes before copy

src/uu/base32/src/base_common.rs, src/uu/paste/src/paste.rs
Mirror behavior of `std::io::Read`'s `read_to_end` function ([link][1]): continue reading when errors with kind `std::io::ErrorKind::Interrupted` are encountered.
Also: clean up a few other things.
[1]: https://doc.rust-lang.org/std/io/trait.Read.html#method.read_to_end
=> basenc: ignore Interrupted errors

src/uu/seq/src/numberparse.rs, tests/by-util/test_seq.rs
=> seq: handle scientific notation with uppercase 'E'

src/uu/seq/src/numberparse.rs, tests/by-util/test_seq.rs
Fix: #6926
This pull request fixes the issue where `seq` mishandles scientific notation in the form of `0e...` by treating it as zero. 
Note;
While testing with `bash util/run-gnu-test.sh`, I discovered another bug unrelated to this fix. I will file a new issue.
```bash
cargo run -q seq 0x1p-1 2
seq: invalid hexadecimal argument: '0x1p-1'
```
=> fix(seq): handle 0e... scientific notation without padding

tests/by-util/test_seq.rs
While reviewing the recent `seq` PRs I noticed that we often use the following in the tests:
```
.stdout_is("something")
.no_stderr()
```
This PR simplifies this by using `stdout_only()` and removing `no_stderr`.
I also noticed that the referenced tickets in the "ignore" messages have been closed as duplicates and so I replaced them with references to the original tickets.
=> tests/seq: use `stdout_only()` to remove `no_stderr()`

src/uu/mv/src/mv.rs
This commit fixes #6727 by returning the error status instead of causing a panic. It aligns with the original GNU mv more closely
```
cargo run -q mv dummy /run/media/user/8EC5-8BC8
thread 'main' panicked at src/uu/mv/src/mv.rs:682:47:
called `Result::unwrap()` on an `Err` value: Os { code: 95, kind: Uncategorized, message: "Operation not supported" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```
cargo run -q mv dummy /run/media/user/8EC5-8BC8
mv: cannot move 'dummy' to '/run/media/user/8EC5-8BC8/dummy': Operation not supported
```
```
mv dummy /run/media/user/8EC5-8BC8
mv: preserving permissions for ‘/run/media/user/8EC5-8BC8/dummy’: Operation not supported
```
- ArchLinux
- rustc 1.83.0 (90b35a623 2024-11-26)
- Destination filesystem is FAT32 …
=> fix(mv): don't panic if apply_xattrs fails

src/uu/seq/src/numberparse.rs
Hello, 
I noticed that the code in the ```numberparse``` module tries to work without extra memory allocations. However, one place with ```to_lowercase``` breaks the general approach.
So, I slightly updated that part to match the common pattern. 
Please feel free just to close the PR if this change seems unimportant or a preliminary optimization.
Thank you
=> seq:reduce memory allocation during prefix search

Cargo.lock, src/uucore/Cargo.toml, src/uucore/src/lib/features/checksum.rs, tests/by-util/test_cksum.rs
Fixes #6653
This PR changes the way the regex to parse a checksum line is chosen. Now, every line gets to choose the regex it matches with, instead of trying to match with the regex that matched the first line (except for non-algo based line which should follow the flavor of the first one).
While doing this, I've decided to get rid of the `regex::Capture` which was being carried around everywhere, and create a `LineInfo` struct that holds all the parsed data.
It adds `lazy_static` as a *direct* dependency to `uu_core` (it was an indirect dependency until now). I allows to not recompile the regexes again and again.
---
EDIT: I have added some code to rework the way the expected checksum is decoded, this PR now fixes #6576 and #6614 as well.
=> cksum: even more fixes

GNUmakefile
When running `./util/build-gnu.sh` I noticed the following two warnings:
```
GNUmakefile:288: warning: overriding recipe for target 'test_busybox_sleep'
GNUmakefile:288: warning: ignoring old recipe for target 'test_busybox_sleep'
```
They are shown because `sleep` is listed in both `PROGS` and `UNIX_PROGS` whereas all other utils are listed only in one of those two lists.
This PR removes `sleep` from `UNIX_PROGS`. I removed it from `UNIX_PROGS` and not from `PROGS` because there is no special handling of `sleep` in `Cargo.toml`.
=> GNUmakefile: remove `sleep` from `UNIX_PROGS` to avoid warning

.vscode/cspell.dictionaries/jargon.wordlist.txt, src/uu/cut/src/cut.rs, tests/by-util/test_cut.rs, util/gnu-patches/tests_cut_error_msg.patch
but we still have some differences on this test
=> cut.pl: adjust to our messages as they are better

Cargo.lock, Cargo.toml
This PR manually bumps `zip` from `1.1.4` to <del>`2.2.0`</del> <del>`2.2.1`</del>`2.2.2` because `renovate` seems to have a problem with updating this crate (https://github.com/uutils/coreutils/pull/6426).
=> Bump `zip` from `1.1.4` to `2.2.2`

src/uu/base32/src/base_common.rs, tests/by-util/test_basenc.rs
Currently, an error is shown if the input provided to `basenc --base16 --decode` contains lowercase characters. This PR fixes this issue and allows lowercase characters. It also makes the tests `b16_9` and `b16_10` in [basenc.pl](https://github.com/coreutils/coreutils/blob/master/tests/basenc/basenc.pl) pass.
```
// before change
$ printf "48656c6c6f2c20576f726c6421" | cargo run basenc --base16 -d
basenc: error: invalid input
// after change
$ printf "48656c6c6f2c20576f726c6421" | cargo run basenc --base16 -d
Hello, World!
```
=> basenc: ignore case with "--base16 --decode"

src/uu/chcon/src/chcon.rs, src/uu/du/src/du.rs, src/uu/fold/src/fold.rs, src/uu/split/src/split.rs, src/uu/tac/src/tac.rs, src/uu/tail/src/args.rs, src/uu/tail/src/paths.rs, src/uu/uniq/src/uniq.rs, src/uucore/src/lib/features/fs.rs, src/uuhelp_parser/src/lib.rs
See:
https://rust-lang.github.io/rust-clippy/master/index.html#map_unwrap_or
=> clippy: fix clippy warnings

.github/workflows/GnuTests.yml
I am seeing if I can test CI. More fixes to come.
=> Put DEFAULT_BRANCH into an env variable.

.github/workflows/GnuComment.yml
This looks like a false positive.
=> GnuComment: zizmor: ignore[dangerous-triggers]

src/uucore/src/lib/features/entries.rs
The code above the line with `truncate` handles the case if `res` is larger than `ngroups`, but `res < ngroups` is also a possibility, which this line attempts to address but actually does not.
The original code resizes to `ngroups` which is a no-op (given that `groups` is already `ngroups` size). The correct target for re-sizing the `groups` is the result from the last `getgroups`, i.e., `res`.
=> uucore: correctly truncate response if getgroups shrinks

.github/workflows/android.yml
It looks like the runner must have switched from bash to some other shell (likely dash). This caching step is failing on recent runs (without failing the whole run, because of the `; exit 0`). This commit just switches from bash's fancy `[[` to the more standard `[` shell test, which is good enough for the existing one-liner.
=> Android CICD: use posix style test

src/uu/cut/src/cut.rs, tests/by-util/test_cut.rs
While reading the code of `cut` I noticed that the special case `-d=` can't be overridden. This PR fixes the issue.
Before the change:
```
$ printf "a:=b" | cargo run -q cut -f2 -d= -d:
b
$ printf "a:=b" | cargo run -q cut -f2 --delimiter== -d:
=b
$ printf "a:=b" | cut -f2 -d= -d:
=b
```
After the change:
```
$ printf "a:=b" | cargo run -q cut -f2 -d= -d:
=b
```
=> cut: fix overriding of `-d=`

src/uu/mkfifo/Cargo.toml, src/uu/mkfifo/src/mkfifo.rs, tests/by-util/test_mkfifo.rs
Should make tests/misc/mknod.sh pass
=> mkfifo: better handle the mode + umask

.clippy.toml, .github/workflows/CICD.yml, Cargo.toml, README.md, src/uu/ls/src/ls.rs, src/uu/wc/src/wc.rs, src/uucore/src/lib/features/format/argument.rs, src/uucore/src/lib/features/format/spec.rs, src/uucore/src/lib/features/quoting_style.rs, src/uucore/src/lib/lib.rs
This adds support for non-UTF-8 bytes in the quoting_style library on Unix platforms. This is necessary for proper support of non-unicode inputs in a few utilities, including `wc`, `ls`, and `printf` (as of this PR, `wc` should be good, `ls` is in a much better state but will need some work to close the final gaps, and `printf` needs @andrewliebenow's #6812, which might conflict this this, but if so, should be a quick fix).
The first commit bumps the MSRV, because we need access to [Utf8Chunks](https://doc.rust-lang.org/std/str/struct.Utf8Chunks.html), since we need to operate on strings and non-unicode bytes in the same OsString (namely, we need to be able to tell if something is invalid unicode, or valid unicode but a control character, and apply the appropriate escaping). Avoiding that …
=> quoting_style: Add support for non-UTF-8 bytes

src/uu/sort/src/ext_sort.rs, src/uu/sort/src/merge.rs, src/uu/sort/src/sort.rs, tests/by-util/test_sort.rs
Fixes #6944
Rework the way batching is done with sort such that it doesn't open more input files than necessary. Previously, the code would always open one extra input file which causes problems in ulimit scenarios. Add additional test case.
=> sort: Rework merge batching logic

src/uu/echo/src/echo.rs
This PR removes a workaround that is no longer needed with a MSRV of `1.79`.
=> echo: remove code made obsolete by MSRV 1.79

src/uucore/src/lib/features/ranges.rs, tests/by-util/test_cut.rs
This PR removes the merging of adjacent ranges. It should make the tests `out-delim4`, `out-delim5` and `od_abut` in [cut.pl](https://github.com/coreutils/coreutils/blob/master/tests/cut/cut.pl) pass.
=> cut: don't merge adjacent ranges

.vscode/cspell.dictionaries/jargon.wordlist.txt, src/uu/ls/src/colors.rs, tests/by-util/test_ls.rs, util/gnu-patches/tests_ls_no_cap.patch
Should fix tests/ls/capability.sh
=> ls: when a file has capabilities (setcap), change the color

util/gnu-patches/tests_comm.pl.patch
This PR adapts some GNU error messages as ours are better.
=> comm: adapt GNU error messages

src/uu/csplit/src/csplit.rs, tests/by-util/test_csplit.rs
This PR adds `-q`, a short for `--quiet`. It makes some of the tests in [csplit-suppress-matched.pl](https://github.com/coreutils/coreutils/blob/master/tests/csplit/csplit-suppress-matched.pl) pass.
=> csplit: add support for `-q`

src/uu/echo/src/echo.rs, tests/by-util/test_echo.rs
This PR fixes an issue with double hyphens:
```
$ cargo run -q echo -- --
--
$ env echo -- --
-- --
```
It also simplifies a few tests by replacing
```rust
.run()
.success()
```
with `.succeeds()`.
=> echo: handle double hyphens

src/uu/mv/src/error.rs, src/uu/mv/src/mv.rs, tests/by-util/test_mv.rs
- improve move-to-self detection, so this errors without data loss:
```diff
mkdir mydir
mv mydir mydir/subdir
-mv: No such file or directory (os error 2)
+mv: cannot move 'mydir' to a subdirectory of itself, 'mydir/subdir'
```
- align "cannot move source to a subdirectory of itself" and "same file"
errors more closely with coreutils:
```diff
mkdir mydir
mv mydir/ mydir/..
-mv: cannot move 'mydir/' to a subdirectory of itself, 'mydir/../mydir/'
+mv: 'mydir/' and 'mydir/../mydir' are the same file
```
=> mv: improve move-to-self error handling

src/uu/cut/src/cut.rs, tests/by-util/test_cut.rs
This PR fixes the handling of newline as a delimiter and should make all tests in [cut.pl](https://github.com/coreutils/coreutils/blob/master/tests/cut/cut.pl) pass.
=> cut: fix handling of newline as delimiter

src/uu/csplit/src/patterns.rs, tests/by-util/test_csplit.rs
So far, an offset without sign like in `'/^$/1'` causes an "invalid pattern" error whereas GNU `csplit` allows such a pattern (see https://www.gnu.org/software/coreutils/manual/html_node/csplit-invocation.html). This PR fixes the issue.
=> csplit: allow offset without sign in pattern

Cargo.toml, build.rs, src/uu/wc/src/wc.rs, tests/by-util/test_wc.rs
It turns out GNU wc only escapes file names with newlines in them. This was never working properly, but became more noticeable when we added non-unicode support. (I'll also just say this choice by GNU was questionable.)
This also adds one of the tests requested in #6882. I added a new flag to build these kinds of tests, since, as hinted in #6639, files with unusual file names can be problematic with file systems or tools not written with them in mind.
=> wc: fix escaping

src/uu/rm/src/rm.rs
=> remove open call from uu-rm

src/uu/rm/src/rm.rs
This comment removes an outdated comment mentioned in https://github.com/uutils/coreutils/pull/7010#discussion_r1899119853
=> rm: remove outdated comment

src/uu/install/Cargo.toml, src/uu/install/src/install.rs, src/uucore/src/lib/features/buf_copy/linux.rs, tests/by-util/test_install.rs
Resolves:
- #5080
- #4387
`install` now uses the `buf-copy` module from `uucore` to do quick data copy under Linux & Android and a buffer-based copy for other OS. FIFOs, character/block devices are considered as streams. Other files still use Rust's `fs::copy`.
=> install: implement copying from streams

util/build-gnu.sh
Now fails with:
```
2024-12-28T14:55:18.9355074Z -rm: cannot remove 'a': Operation not permitted 
2024-12-28T14:55:18.9355364Z +rm: cannot remove 'a/b': Operation not permitted
```
=> GNU: try to remove the fail-2eperm.sh workaround

src/uu/head/src/head.rs, tests/by-util/test_head.rs
Fix a subtraction underflow that occurred on `head --bytes=-N` when the input had fewer than `N` bytes. Before this commit,
printf "a" | head -c -2
would panic. After this commit, it terminates successfully with no output as expected.
=> head: fix subtraction underflow with --bytes=-N

src/uu/env/src/env.rs, tests/by-util/test_env.rs
This fixes #6165 and was adapted from #6711.
This PR contains changes that ensure short options (-u) do not have '=' as their arguments' first character in accordance with GNU/POSIX standards.
Tests were added to ensure this change does not regress.
=> env: fix only long options are allowed to contain '='

src/uucore/src/lib/features/format/mod.rs, tests/by-util/test_seq.rs
Improve the error message produced by `seq` when given invalid format specifiers for the `-f` option. Before this commit:
$ seq -f "%" 1
seq: %: invalid conversion specification
$ seq -f "%g%" 1
seq: %: invalid conversion specification
After this commit:
$ seq -f "%" 1
seq: format '%' ends in %
$ seq -f "%g%" 1
seq: format '%g%' has too many % directives
This matches the behavior of GNU `seq`.
=> seq: improve error handling for invalid -f values

src/uu/chmod/Cargo.toml
This PR adds the missing `perms` feature from `uucore` to `Cargo.toml`. I noticed it when I tried to run the `chmod` tests:
```
$ cargo test --features=chmod --no-default-features
Compiling uu_chmod v0.0.28 (/home/dho/projects/coreutils/src/uu/chmod)
error[E0433]: failed to resolve: could not find `perms` in `uucore`
--> src/uu/chmod/src/chmod.rs:229:23
|
229 |         .args(uucore::perms::common_args())
|                       ^^^^^ could not find `perms` in `uucore`
|
```
=> chmod: add uucore's `perms` feature to `Cargo.toml`

src/uu/chroot/src/chroot.rs, src/uu/chroot/src/error.rs, tests/by-util/test_chroot.rs
Currently fails with:
```
2024-12-28T14:55:18.9330231Z thread 'main' panicked at src/uu/chroot/src/chroot.rs:284:46:
2024-12-28T14:55:18.9330718Z called `Result::unwrap()` on an `Err` value: Custom { kind: NotFound, error: "Not found: nobody:+65535" }
2024-12-28T14:55:18.9331305Z note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> chroot: handle the error when invalid user

src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs
Will help with tests/ls/ls-time
=> ls: finish the plug of mtime

Cargo.lock, Cargo.toml, deny.toml
This PR bumps `itertools` from `0.13.0` to `0.14.0` and adds it to the skip list in `deny.toml`.
=> Bump `itertools` from `0.13.0` to `0.14.0`

src/uucore/src/lib/features/format/num_format.rs, tests/by-util/test_printf.rs
This PR resolves issues with exponent calculation and usage, ensuring more accurate formatting:
- Exponent for negative values can differ from 0
- Switching to decimal mode now follows the P > X ≥ −4 rule
Fixes #7031
```
cargo run -- printf "%g" -0.1171875
-0.11719          
cargo run -- printf "%g"  -0.00001
-0.00001              
```
```
cargo run -- printf "%g" -0.1171875
-0.117188        
cargo run -- printf "%g"  -0.00001
-1e-05                                
```
```
printf "%g" -0.1171875
-0.117188  
printf "%g" -0.00001
-1e-05                               
```
=> uucore:format:fix floating-point representation

src/uu/chroot/src/chroot.rs, src/uu/chroot/src/error.rs, tests/by-util/test_chroot.rs
Fix the parsing of the `--userspec=USER:GROUP` argument so that the both the user and the group are optional, and update the error message to match that of GNU `chroot`. This commit also removes the incorrect `clap` arguments for `--user` and `--group`. In `chroot --user=USER`, the `--user` is an abbreviation of `--userspec`, and in `chroot --group=GROUP`, the `--group` is an abbreviation of `--groups`.
Closes #7040.
=> chroot: fix parsing of --userspec argument

src/uu/chroot/src/chroot.rs, tests/by-util/test_chroot.rs
This PR removes the `-G` short option because GNU `chroot` doesn't have such a short option. I think it was overlooked in https://github.com/uutils/coreutils/pull/7043 when removing the other options not available in GNU `chroot`.
The PR also removes some outdated info from the help for `--userspec`.
=> chroot: remove `-G` short option

src/uu/chroot/src/chroot.rs, src/uu/chroot/src/error.rs
This merge request fixes several issues in the behavior of `chroot`, mostly around setting
group IDs. It ensures that supplemental groups provided by `--groups` are properly handled with respect to the groups implied by `--userspec`. It ensures that we fall back to numeric parsing when attempting to lookup user and group IDs from their names.
It changes the type of `Options.groups` to be `Option<Vec<String>>` so that
the absence of the `--groups` option is meaningfully distinguished from
an empty list of groups. This is important because `chroot --groups=''`
is used specifically to disable supplementary group lookup.
It improves the parsing of the `--groups` parameter to `chroot` so that it
handles more error cases and better matches the behavior of GNU
`chroot`. For example, multiple …
=> chroot: fix many issues with chroot

src/uu/kill/src/kill.rs, tests/by-util/test_kill.rs
GNU coreutils also implements it this way.
Close #7067
=> kill: add `-n` hidden option for compatibility with bash

src/uu/kill/src/kill.rs, tests/by-util/test_kill.rs
=> kill: make `-s` conflict with `-l` and `-t`

src/uu/cksum/src/cksum.rs, tests/by-util/test_cksum.rs
The code fix the error message: first the code controls if the flags length and algorithm blake2b are present, if not the error `cksum: --length is only supported with --algorithm=blake2b`.
I added a new test to cover this case.
Fix #7050
=> cksum: fix error message when the flags length and an algorithm different from blake2b are present 

Cargo.lock, Cargo.toml, fuzz/Cargo.lock, fuzz/Cargo.toml
This PR manually bumps `tempfile` from `3.14.0` to `3.15.0` because `renovate` shows an "Artifact update problem" in https://github.com/uutils/coreutils/pull/7058.
=> Bump `tempfile` from `3.14.0` to `3.15.0`

src/uu/mkfifo/Cargo.toml
This fixes the following issue:
```
$ cargo build -p uu_mkfifo
Compiling uu_mkfifo v0.0.28 (/home/jeffrey/src/coreutils/src/uu/mkfifo)
error[E0433]: failed to resolve: could not find `mode` in `uucore`
--> src/uu/mkfifo/src/mkfifo.rs:43:35
|
43 |         None => 0o666 & !(uucore::mode::get_umask() as usize),
|                                   ^^^^ could not find `mode` in `uucore`
|
note: found an item that was configured out
--> /home/jeffrey/src/coreutils/src/uucore/src/lib/lib.rs:73:26
|
73 | pub use crate::features::mode;
|                          ^^^^
note: the item is gated here
--> /home/jeffrey/src/coreutils/src/uucore/src/lib/lib.rs:72:1
|
72 | #[cfg(all(not(windows), feature = "mode"))]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
For more information about this error, try …
```
=> mkfifo: add missing "mode" feature for uucore dep

.github/workflows/CICD.yml, .vscode/cspell.dictionaries/jargon.wordlist.txt, src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
on the destination
Should fix tests/misc/xattr.sh
=> cp: when copying a read only file, make sure that the xattrs can be set properly

src/uu/cksum/src/cksum.rs, tests/by-util/test_cksum.rs
The code fix the error message: I deleted the clap code that output the wrong error message, then when the check flag is controlled, if the tag is set to true, the program outputs `the --binary and --text options are meaningless when verifying checksums` as the GNU implementation.
I added a new test to cover this case.
Fix #7055
=> cksum: the --tag is meaningless with --check

src/uu/tsort/src/tsort.rs, tests/by-util/test_tsort.rs
Make `tsort` split on any whitespace character instead of just
whitespace within a single line. This allows edge information to be
split with the source node on one line and the target node on another.
For example, after this commit
$ printf "a\nb\n" | tsort
a
b
whereas before this would print an error message.
This pull request also makes two other small changes. First, it introduces a `TsortError` enum implementing the `UError` trait to represent the various problems that `tsort` might encounter. Second, it uses the standard library `std::io::read_to_string` and `std::fs::read_to_string` in place of custom code that was ultimately doing the same thing.
Closes #7077
=> tsort: split edge data on any whitespace chars

src/uu/cp/src/copydir.rs, src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
=> cp: copy attributes after making subdir

Cargo.lock, src/uu/head/Cargo.toml, src/uu/head/src/head.rs, tests/by-util/test_head.rs
Resolves #7029.
Head did not correctly exit when writing to /dev/full because the buffer reader is not properly flushed after the copy operation. This PR addresses the latter.
Changes introduced alongside:
- refactor `head` to use error enums instead of directly returning `UError`s from USimpleError, thus allowing it to print specific errors like I/O errors (including the "device full" message when writing to /dev/full).
- the use of the extraneous `BufWriter` under `read_n_lines` is deleted as `stdout` already implements `Write`. moreover, this will improve performance under specific platforms as `io::copy` will try to make use of platform-specific write calls that do not use user-space buffer.
=> head: make head fail when writing to /dev/full

src/uucore/src/lib/features/buf_copy.rs, src/uucore/src/lib/features/buf_copy/linux.rs, src/uucore/src/lib/features/buf_copy/other.rs
Follow-up of #6980. Delete several functions adopted from `yes` in the `buf_copy` module from uucore as the functions there are too specific to `yes`'s use.
=> uucore/buf-copy: delete redundant functions

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
=> cp: make --backup and --no-clobber are mutually exclusive

src/uu/echo/src/echo.rs, tests/by-util/test_echo.rs
This PR adds support for the `POSIXLY_CORRECT` environment variable and should make [tests/misc/echo.sh](https://github.com/coreutils/coreutils/blob/master/tests/misc/echo.sh) pass.
=> echo: add support for `POSIXLY_CORRECT`

src/uu/csplit/src/csplit.rs, src/uu/join/src/join.rs, src/uu/unexpand/src/unexpand.rs, src/uucore/src/lib/features/fsext.rs, src/uucore/src/lib/lib.rs, src/uucore/src/lib/macros.rs
Remove the crash! and crash_if_error! macros, as discussed in #5487 .
I've replaced all crash_if_err! macro calls, by changing the return type of the functions it was called on. Instead of returning T, they return UResult\<T\>.
This way, instead of crashing, we can propagate the error.
The prompt_yes! macro also used crash_if_err!. In this case, I've replaced that with a call to show_if_err!.
All test pass, except test_df::test_type_option_with_file, which already failed before the changes.
NOTE: This is my first time contributing. Hope I've done everything alright.
=> Remove crash! macro

src/uu/env/src/env.rs, src/uu/stdbuf/src/stdbuf.rs, tests/by-util/test_env.rs, tests/by-util/test_stdbuf.rs
should fix tests/misc/stdbuf
Closes: #7072
=> env/stbuf: better handling of the errors 

src/uu/csplit/src/csplit.rs, src/uu/csplit/src/csplit_error.rs, tests/by-util/test_csplit.rs
Closes #6461 
- Removed metadata check, defer IO read error handling to `InputIterator`.
- Use `UResult` instead of `io::Result` in `InputIterator` for a more uniform IO error handling.
- Change error message on opening file to conform better with the original `csplit`.
=> csplit: support reading from pipe

Cargo.toml, src/uu/cp/src/cp.rs, src/uu/cp/src/platform/macos.rs, src/uucore/src/lib/features/fs.rs, tests/by-util/test_cp.rs, tests/by-util/test_ls.rs
This PR fixes a bunch of clippy errors introduced with Rust `1.84`:
- an error from [unnecessary_map_or](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or) in `cp`
- two errors from [regex_creation_in_loops](https://rust-lang.github.io/rust-clippy/master/index.html#regex_creation_in_loops) in `ls` tests
- an error from [large_stack_arrays](https://rust-lang.github.io/rust-clippy/master/index.html#large_stack_arrays) in a `cp` test
It also allows the `large_stack_arrays` lint in `Cargo.toml` because the lint only partially works (see https://github.com/rust-lang/rust-clippy/issues/13774)
=> clippy: fix errors introduced with Rust `1.84`

src/uucore/src/lib/macros.rs
The `crash!` macro has been removed in https://github.com/uutils/coreutils/pull/7084
=> uucore: remove mention of crash in docs

src/uu/printf/src/printf.rs
Remove an `allow(dead_code)` directive that seems unnecessary.
=> printf: remove allow(dead_code) directive

deny.toml
This PR removes some entries from the skip list in `deny.toml` that are no longer necessary due to the update of the `notify` crate.
=> deny.toml: remove entries from skip list

src/uu/chmod/src/chmod.rs, src/uucore/src/lib/features/perms.rs, tests/by-util/test_chmod.rs
Closes: https://github.com/uutils/coreutils/issues/7023
=> chmod: add support for the deref and links options

src/uu/chroot/src/chroot.rs, tests/by-util/test_chroot.rs
=> chroot: make group option self overwriting

src/uu/stat/src/stat.rs, tests/by-util/test_stat.rs
Support precision when rendering the time of last data modification with `stat`. For example, after this commit
$ stat --printf='%.1Y\n' f
1668645806.7
Previously, the precision in the format specification was ignored. This is implemented with a custom renderer because GNU `stat` seems to truncate the number as opposed to rounding the number as would happen when using `format!` with a specified number of digits of precision.
Fixes #3233
=> stat: fix precision when rendering mtime (%Y)

src/uu/df/src/df.rs, src/uu/df/src/filesystem.rs
Make `df` error when two devices are mounted at the same directory and the earlier one is given as a positional argument to `df`. This is called "over-mounting". After this commit, an error message is printed like this:
df: cannot access '/dev/loop1': over-mounted by another device
Fixes #3970
(This is essentially identical to https://github.com/uutils/coreutils/pull/4316, just rebased on `main` with a couple minor merge conflict fixes.)
=> df: error on over-mounted device

Cargo.lock
This PR downgrades `log` from `0.4.24` to `0.4.22` because the newer versions have been yanked.
=> Cargo.lock: downgrade `log` from `0.4.24` to `0.4.22`

src/uu/tsort/src/tsort.rs, tests/by-util/test_tsort.rs
Update `tsort` so that
* nodes are printed as they are visited,
* cycles are printed as they are discovered,
* finding a cycle doesn't terminate the traversal,
* multiple cycles can be found and displayed.
This isn't a perfect solution, as it breaks the cycles arbitrarily and just repeats the process until it can make more progress, but is an improvement on the previous situation.
Fixes #7074
=> tsort: print nodes and cycles as they are visited 

.github/workflows/CICD.yml
This PR is an attempt to fix the failing "Documentation/warnings" job in the CI (see, for example, https://github.com/uutils/coreutils/actions/runs/12742477783/job/35510671748). It currently fails with
```
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/selinux-sys-0.6.13/build.rs:258:10:
selinux-sys: Failed to find 'selinux/selinux.h'. Please make sure the C header files of libselinux are installed and accessible: Kind(NotFound)
```
=> ci: install `libselinux1-dev`

src/uu/split/src/split.rs, tests/by-util/test_split.rs
Fix the behavior of `split -C` when given large arguments. Before this commit, bytes were being greedily assigned to a chunk too aggressively, leading to a situation where a split happened in the middle of a line even though the entire line could have fit within the next chunk. This was appearing for large arguments to `-C` and long lines that extended beyond the size of the read buffer. This commit fixes the behavior.
I couldn't figure out how to make this work with the existing `LineBytesWriter` and instead wrote the code as a plain function that loops over each line, writing it if it fits in the chunk or otherwise moving to the next chunk. There may be a way to get it working with the `LineBytesWriter`, I just couldn't figure it out. The new code will probably be less efficient.
Fixes …
=> split: fix bug with large arguments to -C

src/uu/dd/src/dd.rs, tests/by-util/test_dd.rs
Make `dd` error if `iflag=directory` and the input file is not a
directory, as in
: | dd iflag=directory
Fixes #5900
=> dd: error if iflag=directory and input is stdin

util/build-gnu.sh
Disable some useless tasks for us and make sure that
`bash util/build-gnu.sh && bash util/run-gnu-test.sh ../gnu/tests/misc/read-errors.sh`
doesn't rebuild too many things
=> Improve gnu build script

src/uu/dircolors/src/dircolors.rs, tests/by-util/test_dircolors.rs
=>  dircolors: fix empty COLORTERM matching with ?* pattern

Cargo.lock, Cargo.toml, src/uu/date/Cargo.toml, src/uu/date/src/date.rs, tests/by-util/test_date.rs
Improve the display of dates formatted with the `%Z` specifier so that
the timezone abbreviation is displayed, not just its numeric offset.
To accomplish this, two dependencies on third-party packages `chrono-tz` and
`iana-time-zone` are added to our `date` package. Together, these two packages
allow us to produce time zone abbreviations (like `UTC`) from numeric
timezone offsets.
Finally, in order for the tests to be independent of which time zone you are in, I added support for the `TZ=UTC0` environment variable, which forces the timezone to be UTC.
Fixes #3756
Most of the work was done by #5164, I'm just updating it and making the tests pass.
=> date: display %Z alphabetic time zone abbreviation

src/uu/seq/src/floatparse.rs, src/uu/seq/src/hexadecimalfloat.rs, src/uu/seq/src/number.rs, src/uu/seq/src/numberparse.rs, src/uu/seq/src/seq.rs, tests/by-util/test_seq.rs
Hello,
This is the initial implementation of hexadecimal floating-point arguments in seq. It started as an attempt to add parsing for hexadecimal floats (issue #6935), but quickly grew into bigger changes.
```
cargo run -q seq 0x1p-1 2
seq: invalid hexadecimal argument: '0x1p-1'
```
```
cargo run -q seq 0x1p-1 2
0.5
1.5
```
```
seq 0x1p-1 2
0.5
1.5
```
- Added the``hexdecimalfloat`` module for parsing hex-floats and detecting the precision of numbers closer to GNU seq. I tried to keep the new functionality separate and minimize changes to the existing code to make changes more observable. I'm sure it’s possible unify number parsing to handle all types of values in one place. However, this seems like a big change and (IMHO) deserves a separate refactor-like PR.
- Changed the method for …
=> seq:add floating point support

src/uu/seq/src/numberparse.rs, tests/by-util/test_seq.rs
This PR adds a lower bound for the minimum exponent value to prevent [overflow](https://github.com/akubera/bigdecimal-rs/blob/466b291b12654520592af217f73030358e96a2f5/src/impl_num.rs#L101) when [parsing](https://github.com/akubera/bigdecimal-rs/blob/466b291b12654520592af217f73030358e96a2f5/src/impl_num.rs#L36) BigDecimal numbers.
```
cargo run -- seq 1e-9223372036854775808
seq: invalid floating point argument: '1e-9223372036854775808'
```
```
cargo run -- seq 1e-9223372036854775808
```
```
seq 1e-9223372036854775808
```
Thank you
=> seq: add a lower bound for exponents

fuzz/Cargo.lock
This PR bumps `bigdecimal` used for fuzzing from `0.4.3` to `0.4.7`. It should fix the failing "Build the fuzzers" job in the CI. It no longer fails because of an issue in Rust nightly but because the changes in https://github.com/uutils/coreutils/pull/7145 use a function not available in `bigdecimal 0.4.3`. See, for example, https://github.com/uutils/coreutils/actions/runs/12805298613/job/35701410937
=> fuzz: bump `bigdecimal` from `0.4.3` to `0.4.7`

Cargo.lock, Cargo.toml, fuzz/Cargo.lock, src/uu/date/src/date.rs, tests/by-util/test_date.rs
This PR bumps `chrono-tz` from `0.8.6` to `0.10.0` and adapts the code to an API change.
It also fixes a small issue if the `TZ` environment variable is empty. In such a case, GNU `date` uses `UTC` whereas we used whatever the default was on the machine:
```
$ TZ= date +"%Z"
UTC
$ TZ= cargo run -q date +"%Z"
CET
```
=> Bump `chrono-tz` to `0.10.0`

src/uucore/src/lib/features/fsext.rs
Replace the display of certain special characters in `df`: ASCII space for plain space character, ASCII horizontal tab for plain tab character, and ASCII backslash for plain backslash character.
This is basically #5754, I've just rebased it and addressed the review comments.
=> df: fix display of special characters

src/uu/comm/Cargo.toml, src/uu/comm/src/comm.rs, tests/by-util/test_comm.rs
A few comments:
* skip if the two args are pointing to the same file
* skip if the same content in the two files
* implement --check-order
* implement --nocheck-order
* output the right things on stderr
Should pass: tests/misc/comm
=> comm: implement the ordering check

Cargo.lock, src/uu/ls/Cargo.toml, src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs
Display the alphabetic timezone abbreviation (like "UTC" or "CET") when
the `--time-style` argument includes a `%Z` directive. This matches the
behavior of `date`.
This uses basically the same code as in pull request #7134. The common code in `date` and `ls` could be refactored later.
Fixes #7035
=> ls: display %Z alphabetic time zone abbreviation

tests/by-util/test_numfmt.rs
Currently, we test that lowercase suffixes cause an "invalid suffix" error. This PR expands the test to ensure the same error is shown for invalid uppercase suffixes and that valid suffixes are recognized.
=> numfmt: extract test from other test & expand it

util/gnu-patches/tests_ls_no_cap.patch
Currently, `util/build-gnu.sh` fails to apply `tests_ls_no_cap.patch` with GNU `coreutils 9.6`:
```
patching file tests/ls/no-cap.sh
Hunk #1 FAILED at 21.
1 out of 1 hunk FAILED
```
This PR adapts the patch to the changes made to `tests/ls/no-cap.sh` in https://github.com/coreutils/coreutils/commit/96100139fc9c05c0ad2236a240783543f0778b85
=> gnu patches: adapt `tests_ls_no_cap.patch` to GNU `coreutils 9.6`

deny.toml
This PR removes `syn` from the skip list in `deny.toml`. It also removes the `Unicode-DFS-2016` license from the allowed licenses to fix a "license not encountered" warning from `cargo deny`.
=> deny.toml: remove `syn` from skip list

util/build-gnu.sh
Re-enable the test case
```
returns_ 1 $prog '%.*dx\n' $INT_OFLOW 0 >>out 2> /dev/null || fail=1                                                     
```
in the GNU test file `tests/printf/printf.sh`. On my machine, the behavior of this command with uutils printf now matches the behavior of GNU printf:
```
$ printf '%.*dx\n' 2147483648 0
printf: invalid precision: '2147483648'
```
=> Re-enable integer overflow test case for printf

util/build-gnu.sh
Update the `util/build-gnu.sh` script to restore the use of uutils programs that had been temporarily replaced with GNU programs in test files where the program to replace was not a primary concern. For example, before this commit we were forcing the use of GNU `stat` instead of uutils `stat` in the test file
`tests/touch/60-seconds.sh`. After this commit, we use the uutils `stat` since it is working well enough for this test case.
=> build: restore uutils in GNU test files

src/uu/mv/src/mv.rs, tests/by-util/test_mv.rs
This PR adapts the behavior of `-u --interactive` to the new behavior of GNU `coreutils 9.6` and shows a prompt. It should make [tests/mv/update.sh](https://github.com/coreutils/coreutils/blob/master/tests/mv/update.sh) pass.
=> mv: show prompt for `-u --interactive`

src/uu/kill/src/kill.rs, tests/by-util/test_kill.rs
This PR shows signal `0` (`EXIT`) in the output of `-l`/`--list` and `-t`/`--table`. It's a [change](https://github.com/coreutils/coreutils/blob/master/NEWS) made in GNU `coreutils 9.6`:
> kill -l and -t now list signal 0, as it's a valid signal to send.
=> kill: list signal `0` with `-l` and `-t`

src/uu/sort/src/sort.rs, tests/by-util/test_sort.rs
Fixes issue #7185 "sort: errors on overflowing -k argument but shouldn't"
```bash
$ printf "2\n1\n" | cargo run sort -k 18446744073709551616
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.10s
Running `target/debug/coreutils sort -k 18446744073709551616`
1
2
```
I'm making the assumption based on the issue that we set to `usize::MAX`. 
As this is my first ever commit to a project and new to rust, please let me know what else would have to be done if needed to get this approved.
=> sort: errors on overflowing -k argument but shouldn't

.github/workflows/GnuTests.yml, DEVELOPMENT.md, util/build-gnu.sh, util/gnu-patches/series, util/gnu-patches/tests_cksum_base64.patch, util/gnu-patches/tests_comm.pl.patch, util/gnu-patches/tests_cut_error_msg.patch, util/gnu-patches/tests_dup_source.patch, util/gnu-patches/tests_env_env-S.pl.patch, util/gnu-patches/tests_factor_factor.pl.patch, util/gnu-patches/tests_invalid_opt.patch, util/gnu-patches/tests_sort_merge.pl.patch, util/gnu-patches/tests_tsort.patch
hard to rebase other and hard to detect regressions
=> gnu patches: move to use quilt

src/uu/sort/BENCHMARKING.md, src/uu/sort/src/numeric_str_cmp.rs, src/uu/sort/src/sort.rs, tests/by-util/test_sort.rs
Fixes #7182 
```bash
$ printf "1Q\n1R\n" | cargo run sort -h
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.12s
Running `target/debug/coreutils sort -h`
1R
1Q
```
```bash
$ printf "1Q\n1R\n" | sort -h
1R
1Q
```
=> sort: needs support for human-readable block size suffixes R and Q

src/uu/cksum/src/cksum.rs, src/uu/hashsum/src/hashsum.rs, src/uucore/src/lib/features/checksum.rs, tests/by-util/test_cksum.rs
This PR does 4 things:
- Move the printing of improperly formatted inline warning to the `process_checksum_line` loop instead of only printing in the case of a problem of algorithm parsing (necessary for passing tests for `--warn`)
- Introduce another rather shitty variable for "caching" the algorithm that was used in the previous checksum line, so we can use it to print a warning message for a potentially incorrect line after.
Example:
```
CHECKSUM.txt:
SM3 (foo.txt) = xxxxxxxxxxx
an invalid line
```
```
cksum -c CHECKSUM.txt --warn
foo.txt: OK
CHECKSUM.txt: 2: improperly formatted SM3 checksum line      <-- SM3 is from the previous line
```
- Change the way the `--status`, `--quiet` and `--warn` flags interact together. In GNU, these flags supersedes each other to set a specific verbose …
=> cksum: Update error and flags handling to improver GNU's match

src/uu/timeout/src/timeout.rs, tests/by-util/test_timeout.rs
This PR adds support for `-f` and `-p`. These short options have been added in GNU `timeout 9.6`. From the [release notes](https://github.com/coreutils/coreutils/blob/master/NEWS):
> timeout now supports the POSIX:2024 specified -f, and -p short options,
corresponding to --foreground, and --preserve-status respectively.
The PR also simplifies some tests by using `no_output()` instead of `no_stderr()` and `no_stdout()`.
=> timeout: add support for `-f` and `-p` short options

src/uu/dd/src/parseargs.rs, src/uu/df/src/df.rs, src/uu/du/src/du.rs, src/uu/od/src/od.rs, src/uu/sort/src/sort.rs, src/uucore/src/lib/parser/parse_size.rs, tests/by-util/test_sort.rs
Add support for parsing percent arguments to the `-S` option. The given
percentage specifies a percentage of the total physical memory. For
Linux, the total physical memory is read from `/proc/meminfo`. The
feature is not yet implemented for other systems.
In order to implement the feature, the `uucore::parser::parse_size`
function was updated to recognize strings of the form `NNN%`.
Fixes #3500
=> sort: support percent arguments to -S option

src/uu/chgrp/src/chgrp.rs, src/uucore/src/lib/features/perms.rs, tests/by-util/test_chgrp.rs
Should make tests/chgrp/from  pass
=>  chgrp: add option --from 

src/uu/kill/src/kill.rs, tests/by-util/test_kill.rs
This PR no longer allows to use lowercase signal names with `-` and makes the `returns_ 1 env kill -cont $$ || fail=1` test in [tests/misc/kill.sh](https://github.com/coreutils/coreutils/blob/master/tests/misc/kill.sh#L39C1-L39C39) pass.
=> kill: don't allow lowercase signal names with '-'

src/uu/od/src/formatteriteminfo.rs
Issue #7187
Removing custom ```PartialEq``` and ```Eq``` implementations helps avoid issues like:
```
warning: function pointer comparisons do not produce meaningful results since their addresses are not guaranteed to be unique
--> src/uu/od/src/formatteriteminfo.rs:29:45
|
29 |             (IntWriter(a), IntWriter(b)) => a == b,
|                                             ^^^^^^
|
= note: the address of the same function can vary between different codegen units
= note: furthermore, different functions could have the same address after being merged together
```
Observable on nightly 1.86
Thank you
=> od:remove custom implementations of PartialEq and Eq

Cargo.lock, Cargo.toml, deny.toml, src/uu/tr/src/operation.rs
This PR does three things:
* bumps `nom` from `7.1.3` to `8.0.0`
* adds `nom` to the skip list in `deny.toml`
* adapts `tr` to API changes in `nom`
=> Bump `nom` and adapt `tr` to API changes

src/uu/kill/src/kill.rs, tests/by-util/test_kill.rs, util/why-error.md
This pull request solves the issue number #7218.
Fixes #7218
=> kill: fix the fail to use only least significant bits to identify signal with -l

Cargo.lock, Cargo.toml, tests/by-util/test_sort.rs
I noticed that the `rand_pcg` crate is only used in one single place in a `sort` test. This PR removes the crate and uses `rand::rngs::SmallRng::seed_from_u64` instead of `rand_pcg::Pcg32::seed_from_u64`.
Edit: The crate was added in https://github.com/uutils/coreutils/pull/3927
=> Remove `rand_pcg`

Cargo.lock, deny.toml, fuzz/Cargo.lock
This PR bumps `tempfile` from `3.15.0` to `3.16.0` and adds `getrandom` and `wasi` to the skip list in `deny.toml`.
=> Bump `tempfile` & add two crates to the skip list in `deny.toml`

util/build-gnu.sh
Remove some replacements of uutils `touch` for GNU `touch` in the `util/build-gnu.sh` script, since recent improvements to the `parse_datetime` have made these replacements unnecessary.
=> Remove some replacements of touch in build script

Cargo.lock, Cargo.toml, deny.toml, fuzz/Cargo.lock, fuzz/Cargo.toml, fuzz/fuzz_targets/fuzz_cksum.rs, fuzz/fuzz_targets/fuzz_common.rs, fuzz/fuzz_targets/fuzz_cut.rs, fuzz/fuzz_targets/fuzz_echo.rs, fuzz/fuzz_targets/fuzz_env.rs, fuzz/fuzz_targets/fuzz_expr.rs, fuzz/fuzz_targets/fuzz_printf.rs, fuzz/fuzz_targets/fuzz_seq.rs, fuzz/fuzz_targets/fuzz_sort.rs, fuzz/fuzz_targets/fuzz_split.rs, fuzz/fuzz_targets/fuzz_test.rs, fuzz/fuzz_targets/fuzz_tr.rs, fuzz/fuzz_targets/fuzz_wc.rs, src/uu/mktemp/src/mktemp.rs, src/uu/shred/src/shred.rs, src/uu/shuf/src/rand_read_adapter.rs, src/uu/shuf/src/shuf.rs, src/uu/sort/src/sort.rs, tests/by-util/test_factor.rs, tests/by-util/test_sort.rs, tests/by-util/test_split.rs, tests/by-util/test_tail.rs, tests/common/random.rs
This PR does three things:
* bumps `rand` from `0.8.5` and `rand_core` from `0.6.4` to `0.9.0`
* adds some crates to the skip list in `deny.toml`
* adapts the code to the API changes
=> Bump `rand` & `rand_core` to `0.9.0`, adapt code to API changes

src/uucore/src/lib/features/format/escape.rs, src/uucore/src/lib/features/format/mod.rs, tests/by-util/test_printf.rs
Change `printf` to correctly terminate with an error message when an escape sequence starts with `\x` but doesn't include a literal hexadecimal value after. For example, before this commit,
printf '\x'
would output `\x`, but after this commit, it terminates with an error message,
printf: missing hexadecimal number in escape
Fixes #7097
=> printf: error on missing hexadecial escape value

src/uucore/src/lib/features/format/spec.rs, tests/by-util/test_printf.rs
=> printf: negative asterisk param changes alignment

src/uu/cksum/src/cksum.rs, src/uucore/src/lib/features/checksum.rs, tests/by-util/test_cksum.rs
Fixes #6375, and 2 other ignored tests
=> cksum: Fix #6375 and un-ignore now passing tests

tests/by-util/test_uptime.rs
This PR removes a test that does the same as `test_uptime_with_non_existent_file()`.
=> uptime: remove duplicate test

Cargo.toml
This PR fixes a "warning[E0602]: unknown lint: `clippy::manual_if_else`" warning from clippy (see, for example, https://github.com/uutils/coreutils/actions/runs/13132290196/job/36639841764#step:7:36) caused by an incorrect lint name in `Cargo.toml`.
=> Cargo.toml: fix incorrect lint name

src/uu/cat/src/cat.rs, tests/by-util/test_cat.rs
Change `cat` so that it terminates with an error message when the input file is the same as the output file and the output file is being appended to. For example,
cat <f >>f
cat: -: input file is output file
Fixes #7165
=> cat: error when output is input and appending

Cargo.lock, src/uu/tee/Cargo.toml, src/uu/tee/src/tee.rs, tests/by-util/test_tee.rs
=> tee: fix -p behavior upon broken pipe stdout

Cargo.lock, deny.toml
This PR bumps `fts-sys` from `0.2.13` to `0.2.14` and adds `bindgen` and `rustc-hash` to the skip list in `deny.toml`. It also updates a few comments there.
=> Bump `fts-sys` from `0.2.13` to `0.2.14`

src/uu/touch/src/touch.rs, tests/by-util/test_touch.rs
Support obsolete form of timestamp argument for old POSIX versions. In summary, when older versions of POSIX are used and the first positional argument looks like a date and time, then treat it as a timestamp instead of as a filename. For example, before this commit
_POSIX2_VERSION=199209
POSIXLY_CORRECT=1
touch 01010000 11111111
would create two files, `01010000` and `11111111`. After this commit, the first argument is interpreted as a date and time (in this case, midnight on January 1 of the current year) and that date and time are set on the file named `11111111`.
Fixes #7180.
=> touch: support obsolete POSIX timestamp argument

src/uu/csplit/src/csplit.rs, tests/by-util/test_csplit.rs
Avoid a panic that would occur when attempting to remove a file that didn't exist. This would happen when scanning for a regular expression match, advancing by a positive offset, and suppressing empty files. For example, before this commit,
echo a | csplit -z - %a%1
would cause a panic. After this commit, the process terminates as expected: without error, without output, and without any files written.
Fixes #7251.
=> csplit: don't panic on missing suppressed file

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
Fixes: #7285
This pull request addresses an ordering issue in the cp command where the verbose message is printed before the interactive prompt for overwrite confirmation.
In GNU cp, the verbose output appears only after the user has responded to the prompt, and this PR adjusts our behavior to match that order.
=> cp: fix verbose output order after prompt

flake.nix, util/build-gnu.sh
This PR should make the `Style/spelling` job in the CI pass by adding words to `spell-checker:ignore` in `flake.nix` and `util/build-gnu.sh`. The job currently fails, see https://github.com/uutils/coreutils/actions/runs/13324924599/job/37216058428.
=> ci: add words to `spell-checker:ignore` in two files

tests/by-util/test_split.rs
Avoid an extremely long format width specifier in test case `test_long_lines`. The Rust compiler is planning an upcoming change to restrict the maximum width that can be specified to 65535, so this change defends against future limitations in the compiler. For more information, see
<https://github.com/uutils/coreutils/pull/7128#discussion_r1955787665>.
=> split: avoid extremely long format width in test

src/uu/rm/src/rm.rs, tests/by-util/test_rm.rs
Simplify the `remove_dir()` helper function by eliminating an unnecessary call to `std::fs::read_dir()` and using `UIoError` for displaying error messages.
=> rm: simplify remove_dir() helper function

src/uu/hashsum/hashsum.md, src/uu/runcon/runcon.md, src/uu/test/test.md, src/uu/unlink/unlink.md
Went through the list in #5692 and found inconsistencies for unlink, runcon, test, and hashsum.
`runcon` uutils:
runcon [CONTEXT COMMAND [ARG...]]
but `runcon` requires a context command to function:
runcon: No command is specified
`unlink` uutils:
unlink [FILE]
but `unlink` requires a file to unlink:
error: the following required arguments were not provided:
<FILE>
`hashsum`:
hashsum [OPTIONS] [FILE]...
but `hashsum` requires a digest to operate and may take multiple options:
hashsum: Needs an algorithm to hash with.
`test` uutils:
test EXPRESSION
[
[ EXPRESSION ]
[ ]
[ OPTION
]
but:
1. `[` alone is not a valid test command:
[: missing ']'
2. `test` alone is a valid test command.
3. `]` alone is not a valid test command.
As appropriate, this matches GNU behavior.
=> Fix usage strings for #5692

src/uu/echo/Cargo.toml, src/uu/echo/src/echo.rs
Remove some duplicate code in favor of just calling `uucore::format::parse_escape_only()`.
Fixes #7258.
=> echo: use uucore::format::parse_escape_only()

src/uu/numfmt/src/format.rs, tests/by-util/test_numfmt.rs
Fix #7219 
The change to GNU coreutils has been real recent, part of 9.6
=> numfmt: fix from iec-i without suffix are bytes

src/uu/rm/src/rm.rs, tests/by-util/test_rm.rs
Change the prompt when attempting to remove an inaccessible directory. Before this commit, the prompt was
rm: remove write-protected directory 'dir'?
After this commit, the prompt is
rm: attempt removal of inaccessible directory 'dir'?
This required slightly adjusting the logic for which prompt messages to display under which circumstances.
Fixes #7309.
=> rm: correct prompt for removing inaccessible dir

src/uu/tr/src/operation.rs, tests/by-util/test_tr.rs
Fix the remaining edge case of #6777:
```sh
$ ./target/debug/tr -d '[=aa=]'
./target/debug/tr: aa: equivalence class operand must be a single character
```
=> tr: Fix GNU behavior deviation

tests/by-util/test_test.rs
This PR removes `sleep` from two tests and uses `File::set_modified` instead.
=> test: remove `sleep` from tests

GNUmakefile
When packaging uutils for Conda-Forge, the install of completion scripts fails with the following error.
> make: /bin/sh: Argument list too long
The completion scripts are installed with a `foreach` loop that expands into a single long command. That command hits the maximum argument length on the build platform used by Conda-Forge.
To fix, we change the Make command to split each install into a seperate command. This is done by embedding a newline in the command. See the following for an example of how this works.
https://www.extrema.is/blog/2021/12/17/makefile-foreach-commands
=> GNUmakefile: fix install error "argument list too long"

Cargo.lock, Cargo.toml, src/uu/uptime/Cargo.toml, src/uu/uptime/src/uptime.rs, src/uucore/Cargo.toml, src/uucore/src/lib/features.rs, src/uucore/src/lib/features/uptime.rs, src/uucore/src/lib/lib.rs
Move some code from uu_uptime to uucore, [to use them in uu_top](https://github.com/uutils/procps/pull/306#discussion_r1929531381).
It may duplicate #7256. When I started, #7256 was not yet open.
I also implement Windows(except load average, it seems impossible)
=> uptime: refactor, move some codes to uucore

src/uu/du/src/du.rs, src/uu/pr/src/pr.rs, src/uu/sort/src/sort.rs, src/uu/stty/src/stty.rs, src/uucore/src/lib/features/fsext.rs
This PR fixes a clippy warning from the [precedence](https://rust-lang.github.io/rust-clippy/master/index.html#precedence) lint and disables warnings from the [unnecessary_map_or](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or) lint. Those warnings are disabled instead of fixed because the fix requires a MSRV of `1.82`.
=> clippy: fix/disable warnings introduced with Rust `1.85`

src/uu/test/src/parser.rs, src/uu/test/src/test.rs, tests/by-util/test_test.rs
=> test: add < and > operators for string comparison

fuzz/Cargo.lock, fuzz/fuzz_targets/fuzz_test.rs
This PR uses the new `<`/`>` operators, introduced with https://github.com/uutils/coreutils/pull/7315, in `fuzz_test.rs`. The PR also bumps `parse_datetime` from `0.7` to `0.8`.
=> fuzz: use new `<`/`>` operators in `fuzz_test.rs`

.github/workflows/CICD.yml, GNUmakefile, README.md
When packaging uutils for Conda-Forge and a cross-compiled architecture, the install of completion scripts and manpages fails with the following error.
> .../coreutils manpage arch > .../man/arch.1
> /bin/sh: .../coreutils: Bad CPU type in executable
> make: *** [GNUmakefile:349: manpages] Error 126
When cross-compiling, the `coreutils` tool will be for a different architecture then the build platform. So we won't be able to extract the manpages and completions.
Provide build arguments that let us skip the build and install of manpages and completions.
=> GNUmakefile: support skipping manpages and completions

tests/by-util/test_tee.rs, tests/common/util.rs
This PR uses `pipe_in_and_wait` instead of the deprecated `pipe_in_and_wait_with_output` in the tests. And removes the deprecated function from the test framework.
=> tee: fix usage of deprecated function in tests

tests/by-util/test_yes.rs
This PR uses `wait()`  instead of the deprecated `wait_with_output()` in a test.
=> yes: fix use of deprecated function in test

tests/common/util.rs
This PR makes the `wait_with_output` function private and un-deprecates it.
=> tests: make `wait_with_output` private

src/uu/expr/src/expr.rs, src/uu/expr/src/syntax_tree.rs
As a side effect, we also now have the right behavior when adding arguments after `--help` or `--version`. Before this change, clap would have printed the help, but it is expected that flags are ignored if argc > 2 (more than 1 arg is given) 
Benchmarks:
```
$ export N=2500
$ hyperfine -m 1000 -- "./expr_clap $(yes 1 | head -n $N | paste -s - 2>&1 | sed 's/\t/ + /g')"
Time (mean ± σ):      47.4 ms ±   3.3 ms    [User: 34.4 ms, System: 12.8 ms]
Range (min … max):    37.3 ms …  74.4 ms    1000 runs
#After
$ hyperfine -m 1000 -- "./expr_no_clap $(yes 1 | head -n $N | paste -s - 2>&1 | sed 's/\t/ + /g')"
Time (mean ± σ):      24.7 ms ±   2.2 ms    [User: 13.9 ms, System: 10.7 ms]
Range (min … max):    18.8 ms …  34.7 ms    1000 runs
```
=> expr: Get rid of clap for performance reasons

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
=> cp: disabled verbose output if file has been skipped

src/uucore/src/lib/features/format/num_format.rs
Floating hex format is supposed to be `[-]0xh.hhhp±d`. Note that
the exponent is a decimal value, not an hex number: fix that.
Also, add basic tests for this format, while we're at it.
Test: `cargo test --package uucore --all-features float`
Fixes #7362.
Negative numbers were not printed correctly with `%a`:
- A leading `-` is expected.
- The exponent mask was too wide (15 bits instead of 11)
---
This doesn't fix everything (see #7364), but at least the output is now _somewhat_ correct.
=> printf: (partially) fix hex format: exponent is decimal, correctly print negative numbers

src/uu/head/src/head.rs, tests/by-util/test_head.rs
Head tool now ensures that stdin is set to the last character that was output by the tool. This ensures that if any subsequent tools are run from the same input stream they will start at the correct point in the stream.
These changes should fix the head-pos.sh GNU test. This is tracked by issue #7028.
=> Head: ensure stdin input stream is correct on exit

deny.toml
This PR removes the crates `linux-raw-sys`, `rustix`, and `terminal_size` from the skip list in `deny.toml`.
=> deny.toml: remove three crates from skip list

.github/workflows/CICD.yml, Cargo.toml, README.md, tests/common/util.rs
=> Bump MSRV to 1.82.0

src/uucore/src/lib/mods/panic.rs
This PR uses `PanicHookInfo` instead of the deprecated `PanicInfo`.
=> uucore: replace `PanicInfo` with `PanicHookInfo`

src/uu/du/src/du.rs, src/uu/pr/src/pr.rs, src/uu/sort/src/sort.rs, src/uu/stty/src/stty.rs
This PR fixes warnings from the [unnecessary_map_or](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or) and replaces `map_or` with `is_none_or`.
=> clippy: fix warnings from `unnecessary_map_or` lint

src/uu/mktemp/src/mktemp.rs, src/uu/tr/src/operation.rs
This PR fixes two todos and replaces `repeat().take()` with `repeat_n()`. It will prevent warnings from the  [manual_repeat_n](https://rust-lang.github.io/rust-clippy/master/index.html#manual_repeat_n) lint coming with Rust `1.86`.
=> mktemp,tr: replace `repeat().take()` with `repeat_n()` 

src/uucore/src/lib/features/checksum.rs
This PR fixes a todo that requires a MSRV of `1.82` and replaces `is_some_and` with `is_none_or` to improve the readability.
=> cksum: replace `is_some_and` with `is_none_or`

Cargo.lock, src/uucore/Cargo.toml, src/uucore/src/lib/features/checksum.rs
This PR removes the `lazy_static` dependency and uses `std::sync::LazyLock` instead, which was added in Rust 1.80.
=> uucore: remove `lazy_static` and use `LazyLock` instead

.github/workflows/CICD.yml
Add a new Linux build that runs without `cross`, and adds
`--workspace` to the cargo test command.
From cargo test documentation, this option "tests all members in
the workspace.". For example, this includes running tests within
the `uucore` package (see #7383).
Fixes #7392.
=> .github: CICD: add workspace test to build matrix

src/uu/expr/src/expr.rs, src/uu/expr/src/syntax_tree.rs, tests/by-util/test_expr.rs
I've rewritten all the GNU testcases of `gnu/tests/expr/expr.pl` in our testsuite, to more easily track potential regressions.
Sadly, the remaining issues are all caused by our regex dependency (`rust-onig`) which has a diverging behavior from GNU. This emphasizes the need to find another regex engine, as discussed in #1145
=> expr: Add tests

GNUmakefile, src/uu/stdbuf/build.rs, util/build-gnu.sh
- Changes stdbuf's build script to allow target directory to not require 'target' or 'cargo-install' in name
- Updates scripts to use "CARGO_TARGET_DIR" when supplied
=> Fixed Bugs When Not Using Default Target Directory

src/uu/kill/src/kill.rs, tests/by-util/test_kill.rs
This PR adds two tests to ensure `kill -l <number>` works. It also adapts two error messages from `unknown signal name <SIGNAL>` to `<SIGNAL>: invalid signal` because I think the error messages from GNU `kill` are better than ours.
=> kill: test "-l <number>" & adapt error messages

src/uu/head/src/head.rs, tests/by-util/test_head.rs
And provide more details than GNU
Should fix tests/head/head-write-error
=> head: improve error mgmt.

deny.toml
This PR adds `rustix` and `linux-raw-sys` to the skip list in `deny.toml` to allow the merging of https://github.com/uutils/coreutils/pull/7409 and https://github.com/uutils/coreutils/pull/7410.
=> deny.toml: add `rustix` & `linux-raw-sys` to skip list

Cargo.lock, src/uu/uptime/Cargo.toml, src/uu/uptime/src/uptime.rs, src/uucore/Cargo.toml, src/uucore/src/lib/features/uptime.rs
`windows_sys::Win32::System::SystemInformation::GetTickCount` returns uptime **in milisecond**. A simple mistake.
i also optimise rustdoc and SAFETY comment. If ONE PR shouldn't do so many things, I can also split it into two PRs
=> fix uptime on windows

Cargo.lock, fuzz/Cargo.lock, src/uu/ls/src/ls.rs, src/uu/wc/src/count_fast.rs, tests/by-util/test_ls.rs
This PR bumps `libc` from `0.2.170` to `0.2.171` and removes `unsafe` blocks in `ls` and `wc` that are no longer necessary with this new version.
=> Bump `libc` & remove unnecessary `unsafe` blocks

src/uu/expr/src/syntax_tree.rs, tests/by-util/test_expr.rs
This pull request addresses a stack overflow issue in the `expr` utility when handling deeply nested expressions.
Fixes #7338
- Replaced recursive tree traversal with stack-based approach
- Add identifiers for AST nodes
- Use a BTreeMap with node IDs for the result stack
The implementation includes a new test case that verifies the ability to handle large expressions that would previously cause stack overflow.
A simpler solution would be to use the [decurse](https://crates.io/crates/decurse) crate.
=> expr: Refactor AST evaluation to avoid stack overflow

src/uu/false/src/false.rs, src/uu/true/src/true.rs, tests/by-util/test_false.rs, tests/by-util/test_true.rs
This PR removes an unnecessary newline from the version strings of `true` and `false`.
Before change:
```bash
$ cargo run -q false --version
false 0.0.30
$
```
After change:
```bash
$ cargo run -q false --version
false 0.0.30
$
```
The PR also makes some minor improvements to the tests of `true` and `false`.
=> true,false: remove unnecessary newline from version string

Cargo.lock, Cargo.toml, src/uu/cp/Cargo.toml, src/uu/cp/src/platform/linux.rs
The current ioctl operation code for FICLONE is fully open-coded instead of using the ioctl macros, which makes it non-portable to other architectures including mips, arm & powerpc. Get the constant from the linux-raw-sys crate instead, which is already a transitive dependency.
=> cp: Use FICLONE ioctl constant from linux-raw-sys

src/uu/touch/src/touch.rs, tests/by-util/test_touch.rs
When using `touch -t` with a 2 digit year, the year is interpreted as a relative year to 2000.
When the year is 68 or less, it should be interpreted as 20xx. When the year is 69 or more, it should be interpreted as 19xx.
This is the behavior of GNU `touch`.
fixes gh-7280
Arguably 2 digits years should be deprecated as we are already closer to 2069, than 1969.
=> Fix touch -t with 2 digit years when YY > 68

src/uucore/src/lib/features/format/num_format.rs, tests/by-util/test_seq.rs
The fact that printf and seq path are totally different is, TBH, a bit confusing...
printf uses precision 6 because of this subtle line in `spec.rs:Spec::write` (`Self::Float` case):
```
let precision = resolve_asterisk(*precision, &mut args).unwrap_or(6);
```
2 small additional changes (I can split to 2 other PR if needed, they felt small enough to just tack on this one):
- While adding one of the seq test, noticed that printing of 0 with capitalized `%E` was wrong, fix that as well.
- And noticed 2 seq tests that were disabled that can be enabled.
----
Those tests appear to have been fixed, enable them.
Add tests for some of the default float formats (%f, %g, %E), mostly
to check that the default precision is correctly set to 6 digits.
The default precision is 6, no matter the format. …
=> seq: fix default float precision (`%f`); fix 0 scientific printing

src/uucore/src/lib/features/format/num_format.rs, tests/by-util/test_printf.rs
This was broken before the last few commits.
Add a few end-to-end tests for printf of unusual floats (nan,
infinity, negative zero).
Simplifies the code, but also fixes printing of negative and positive `NaN`:
`cargo run printf "%f %f\n" nan -nan`
Fixes part 2 of #7412.
Fixes formatting of `NaN` to `nan`.
Fixes part 1 of #7412.
=> Fix `nan` print, simplify negative number printing.

CONTRIBUTING.md
The link https://opensource.apple.com/source/file_cmds/ is no longer valid.
It appears that https://github.com/apple-oss-distributions/file_cmds/ is its official equivalent.
=> CONTRIBUTING: fix broken link to Apple's file_cmds

.vscode/cspell.dictionaries/acronyms+names.wordlist.txt, .vscode/cspell.dictionaries/jargon.wordlist.txt, .vscode/cspell.dictionaries/shell.wordlist.txt, docs/src/installation.md
An update to the docs on how to install in fedora and RHEL/CentOS Stream or AlmaLinux and RockyLinux
Tested on CentOS Stream 9 and Fedora 41
=> add fedora and RHEL installation docs

src/uucore/src/lib/features/utmpx.rs
Unfortunately, the names of those constants are not standardized:
- glibc uses __UT_HOSTSIZE, __UT_LINESIZE, __UT_NAMESIZE
- musl uses UT_HOSTSIZE, UT_LINESIZE, UT_NAMESIZE
See:
1. https://git.musl-libc.org/cgit/musl/tree/include/utmpx.h
2. https://github.com/bminor/glibc/blob/master/sysdeps/gnu/bits/utmpx.h#L35
This is a partial fix for https://github.com/uutils/coreutils/issues/1361
=> utmpx.rs: use correct constant names for musl libc

README.md
Small fixup, Mac refers to the hardware, macOS to the OS, and this section talks about OSs (Linux, Windows, ...)
=> README.md: Refer to macOS when talking about the OS, not Mac (hardware)

src/uucore/src/lib/features/fsext.rs
Commit https://github.com/uutils/coreutils/pull/3396/commits/2a0d58d060eb51ee482e7e8a764f36bda21105e5 (part of https://github.com/uutils/coreutils/pull/3396 which contains a description of the changes) changed this line from libc::fsid_t to nix::sys::statfs::fsid_t. The pull-request description at https://github.com/uutils/coreutils/pull/3396 indicates that this was done in order to fix the android build, and indeed using a cast to nix::sys::statfs::fsid_t takes advantage of the definition of nix::sys::statfs::fsid_t which abstracts away the different name on Android:
```
/// Identifies a mounted file system
#[cfg(target_os = "android")]
pub type fsid_t = libc::__fsid_t;
/// Identifies a mounted file system
#[cfg(not(target_os = "android"))]
pub type fsid_t = libc::fsid_t;
```
This cast …
=> fsext.rs: use type inference fsid_t / __fsid_t

docs/src/extensions.md, src/uu/base32/src/base_common.rs, tests/by-util/test_base32.rs, tests/by-util/test_base64.rs, tests/by-util/test_basenc.rs
I noticed that the base64 that comes with macOS includes a `-D` flag.
> Usage:	base64 [-Ddh] [-b num] [-i in_file] [-o out_file]
>   -b, --break       break encoded output up into lines of length num
>   -D, -d, --decode  decode input
>   -h, --help        display this message
>   -i, --input       input file (default: "-" for stdin)
>   -o, --output      output file (default: "-" for stdout)
Implementing this flag makes it easy to replace the system default implementation with coreutils on macOS, as there are programs that rely on this flag (e.g. imgcat).
=> base32/base64/basenc: add -D flag

src/uu/head/src/head.rs, src/uu/head/src/take.rs
Rework logic for handling all-but-last-lines and all-but-last-bytes for non-seekable files. Changes give large performance improvement.
=> head: rework handling of non-seekable files

src/uu/seq/BENCHMARKING.md, src/uu/seq/src/seq.rs
Use a BufWriter to wrap stdout: reduces the numbers of system calls, improves performance drastically (2x in some cases).
Fixes _part_ of #7482, see this comment: https://github.com/uutils/coreutils/issues/7482#issuecomment-2734399193
Thanks @mjguzik!
For floating point prints, we are now faster than GNU:
```
taskset -c 0 hyperfine -L seq seq,./seq-main,target/release/seq "{seq} 0 0.1 100000"
Benchmark 1: seq 0 0.1 100000
Time (mean ± σ):     161.6 ms ±   0.3 ms    [User: 160.8 ms, System: 0.6 ms]
Range (min … max):   161.2 ms … 162.4 ms    18 runs
Benchmark 2: ./seq-main 0 0.1 100000
Time (mean ± σ):     282.7 ms ±   5.0 ms    [User: 221.0 ms, System: 60.0 ms]
Range (min … max):   279.7 ms … 296.2 ms    10 runs
Benchmark 3: target/release/seq 0 0.1 100000
Time (mean ± σ):     143.8 ms ± …
```
=> seq: Buffer writes to stdout

src/uu/cp/src/cp.rs, src/uu/mv/src/mv.rs, src/uucore/src/lib/features/backup_control.rs, src/uucore/src/lib/features/update_control.rs
Resolve https://github.com/uutils/coreutils/discussions/7502
This pull request includes several changes to the `cp`, `mv`, and `uucore` utilities, focusing on adding `Default` implementations to various enums and structs.
The selection of default values is based on the values that would be set when no flag are passed in the command line.
Key changes include:
* Added `Default` implementations for enums `ClobberMode`, `OverwriteMode`, `ReflinkMode`, `SparseMode`, `CopyMode`, and struct `Attributes`. This simplifies the initialization of these types. [[1]](diffhunk://#diff-fed63f74214c092a801901cdce011f1941f6378a84d9c7947b5bd02adce2de43L113-R122) [[2]](diffhunk://#diff-fed63f74214c092a801901cdce011f1941f6378a84d9c7947b5bd02adce2de43R132-R163) …
=> Implement `Default` for `Options` of `mv` and `cp`

tests/by-util/test_arch.rs
This test ensures that the output of the arch command is non-empty, which is a minimal expectation across all supported architectures.
This helps avoid regressions or edge cases where the command might unexpectedly return an empty string on unsupported or misconfigured platforms.
=> Add test to ensure arch output is not empty

docs/src/test_coverage.js
Currently, the ["Coverage per category" section](https://uutils.github.io/coreutils/docs/test_coverage.html#coverage-per-category) doesn't show any categories and there's a 404 error in the browser's console. This PR fixes the url of the file with the coverage results, as we recently changed its name in https://github.com/uutils/coreutils-tracking
=> docs: fix url of file with coverage results

Cargo.lock, src/uu/csplit/src/split_name.rs, src/uu/dd/src/progress.rs, src/uu/seq/BENCHMARKING.md, src/uu/seq/src/hexadecimalfloat.rs, src/uu/seq/src/number.rs, src/uu/seq/src/numberparse.rs, src/uu/seq/src/seq.rs, src/uucore/Cargo.toml, src/uucore/src/lib/features/format/extendedbigdecimal.rs, src/uucore/src/lib/features/format/mod.rs, src/uucore/src/lib/features/format/num_format.rs, src/uucore/src/lib/features/format/spec.rs, tests/by-util/test_printf.rs
Okay, this one is a bit of a large PR... I can split it up if needed (e.g. everything up to `uucode: format: Change Formatter to take an &ExtendedBigDecimal` is fairly mechanical). Also, I'm not too worried about having to rewrite stuff if needed (one of my purpose to contribute is to learn about Rust ,-)), so please let me know ,-)
The idea here is to switch formatting functions to use ExtendedBigDecimal, instead of f64. This allows us to get arbitrary precision with custom format in `seq`:
```
cargo run seq -f "%.32f" 0.1 1 1
0.10000000000000000000000000000000
```
Note that that doesn't match what `coreutils` outputs on x86, since they use an 80-bit int:
```
0.10000000000000000000135525271561
```
But that's better than before this change, where we used a `f64`:
``` …
```
=> Move ExtendedBigDecimal to uucore/format, make use of it in formatting functions

src/uu/cat/src/cat.rs
Issue #7518
Add a BufWriter over stdout when cat outputs any kind of formattted data. This improves performance considerably.
=> cat: Improve performance of formatting.

Cargo.lock, src/uu/shuf/Cargo.toml, src/uu/shuf/src/shuf.rs, src/uucore/src/lib/mods/display.rs, tests/by-util/test_shuf.rs, tests/common/util.rs
- shuf now uses OS strings, so it can read from filenames that are invalid Unicode and it can shuffle arguments that are invalid Unicode. `uucore` now has an `OsWrite` trait to support this without platform-specific boilerplate.
- shuf no longer tries to split individual command line arguments, only bulk input from a file/stdin. (This matches GNU and busybox.)
- More values are parsed inside clap instead of manually, leading to better error messages and less code.
- Some code has been simplified or made more idiomatic.
I plan to follow up with a PR to optimize shuf with vectored writes and mmap. (Last time I tried this I got sidetracked by a stdlib bug: https://github.com/rust-lang/rust/pull/121938)
=> Make `shuf` OsStr-compliant and bring newline handling in line with GNU

tests/by-util/test_seq.rs, tests/by-util/test_yes.rs, tests/common/util.rs
Still trying to untangle/understand more about GNU `seq` behavior outside of what is clearly specified in their manual. Some of it makes sense, filed a bug for one case that I don't think makes sense (and found an existing bug for another case):
- https://lists.gnu.org/archive/html/bug-coreutils/2025-03/msg00028.html
- https://lists.gnu.org/archive/html/bug-coreutils/2025-02/msg00007.html
Also move some shared code between seq/yes tests to common/util.
---
Some of these tests are not completely defined behavior, but
in many cases they make sense (or at least one can find some
consistent logic to it).
However, there are 2 edge cases that are more dubious IMHO.
One of them has been reported on list a while back, and I
just reported another.
Tests for both `seq` and `yes` run a command that …
=> test_seq: Add a few more tests for corner cases

docs/src/installation.md
Links for ubuntu on `installation.md` are broken because they are old. This PR fixes both to the latest version.
=> doc: bump version of ubuntu badge

docs/src/installation.md
While reviewing https://github.com/uutils/coreutils/pull/7553, I noticed that we mention the no longer existing `coreutils-hybrid` package on the [installation page](https://uutils.github.io/coreutils/docs/installation.html#non-standard-packages). This PR replaces it with the [coreutils-uutils](https://aur.archlinux.org/packages/coreutils-uutils) package.
=> docs: replace AUR package in installation.md

CONTRIBUTING.md
This is similar to #7201, but for others links.
Relative links works on github but are broken for the `CONTRIBUTING.md` on the mdbook. This pr change the links that have problems to absolute links that work on both.
I tested these changes on a local mdbook and they are fine.
=> doc: fix broken links on mdbook

src/uu/chmod/chmod.md, src/uu/mkdir/mkdir.md
On [chmod](https://uutils.github.io/coreutils/docs/utils/chmod.html) and on [mkdir](https://uutils.github.io/coreutils/docs/utils/mkdir.html) there is a RE that is valid markdown link:
This line:
Each MODE is of the form '[ugoa]*([-+=]([rwxXst]*|[ugo]))+|[-+=]?[0-7]+'. 
Into this:
Each MODE is of the form `[ugoa]*([-+=]([rwxXst]*|[ugo]))+|[-+=]?[0-7]+`. 
I try to escape that RE using monospace/backticks.
=> doc: escape RE with backticks (`)

src/uu/seq/BENCHMARKING.md, src/uu/seq/src/seq.rs
Doing `stdout.write_all(separator.as_bytes())?` is quite a bit faster than using format to do the same operation: `write!(stdout, "{separator}")?`.
This speeds up by about 10% on simple cases.
We do the same for the terminator even though this has no measurable performance impact.
---
Integer increments (no point comparing with coreutils on that one, it's much faster):
```
$ cargo build -r -p uu_seq && taskset -c 0 hyperfine --warmup 3 -L seq target/release/seq,./seq-main "{seq} 1 1000000"
Finished `release` profile [optimized] target(s) in 0.12s
Benchmark 1: target/release/seq 1 1000000
Time (mean ± σ):     162.9 ms ±   2.4 ms    [User: 161.5 ms, System: 0.9 ms]
Range (min … max):   160.4 ms … 167.7 ms    17 runs
Benchmark 2: ./seq-main 1 1000000
Time (mean ± σ):     182.2 ms ±   4.6 ms …
```
=> seq: Directly write separator string, instead of using format

src/bin/uudoc.rs
This change is documented here: https://doc.rust-lang.org/nightly/edition-guide/rust-2024/match-ergonomics.html
I'm... not sure to understand everything, but this change is what `cargo fix --edition --features="uudoc" --allow-dirty` suggests.
Fixes #7572.
=> uudoc: Fix for edition 2024

tests/by-util/test_test.rs
I found the logic a little difficult to understand, and the comment probably doesn't match what `-N` is supposed to do?
Intead, let's just manually set mtime and atime.
Hopefully this helps clear up Android flakiness in #7570. Or at least understand better what is going on.
=> test_test: Simplify test_file_N

deny.toml
This PR removes `bindgen` and `rustc-hash` from the skip list in `deny.toml`.
=> deny.toml: remove two crates from skip list

.github/workflows/CICD.yml
Make sure we catch build errors.
Would prevent #7572 from happening again.
=> ci: Enable uudoc feature on x86-64 native builder

.pre-commit-config.yaml
That cuaght me a few times... I think it's reasonable to ask devs to install cspell locally if they want to use the pre-commit hook.
=> .pre-commit-config.yaml: Also run cspell

src/uu/date/src/date.rs, tests/by-util/test_date.rs
Clap needs to be specifically configured to allow values with a leading hyphen
`date -d '-2 weeks'` is a valid offset.
```bash
target/debug/coreutils date -d '-2 weeks'
Sun Mar  9 22:18:35 GMT 2025
```
```bash
date -d '-2 weeks'
Sun  9 Mar 22:18:57 GMT 2025
```
closes #7515
=> date: allow negative date offsets

.editorconfig, .envrc, .github/workflows/CICD.yml, .github/workflows/CheckScripts.yml, .github/workflows/FixPR.yml, .github/workflows/GnuComment.yml, .github/workflows/GnuTests.yml, .github/workflows/android.yml, .github/workflows/code-quality.yml, .github/workflows/freebsd.yml, .github/workflows/fuzzing.yml, .gitignore, .vscode/cSpell.json, .vscode/extensions.json
Noticed this because pre-commit would try to run on dotfiles as
well (will CI ignored it)
Also fix a couple of real spelling mistakes.
=> ci: Enable cspell on test on dotfiles too

src/uu/echo/src/echo.rs, tests/by-util/test_echo.rs
Added check to only insert addition double hyphen if at start of arguments to correctly prepend addition hyphens for clap as well as additional test case
=> echo: fixed double hyphen as argument

src/uucore/src/lib/features/format/num_format.rs
All the other tests directly called format_float_* functions,
bypassing the additional logic in `fmt` (negative numbers, padding,
etc.).
This also tests the `parse` function in `mod.rs`, which calls back
into `try_from_spec` here. This also makes it easier to test a lot
of different format combinations without having to do end-to-end
tests in `test_printf.rs`.
Also add broken tests for the issues in #7509 and #7510.
This is a bigdecimal issue, see
https://github.com/akubera/bigdecimal-rs/issues/144 .
Also add a few tests, including a disabled one (our workaround
is _before_ the call to format_float_decimal).
=> uucore: format: num_format: add `fmt` function tests, and workaround 0e10 printing.

Cargo.lock, src/uu/dd/Cargo.toml, src/uu/dd/src/parseargs.rs, src/uu/expand/Cargo.toml, src/uu/expand/src/expand.rs, src/uu/numfmt/Cargo.toml, src/uu/numfmt/src/errors.rs, src/uu/ptx/Cargo.toml, src/uu/ptx/src/ptx.rs, src/uu/split/Cargo.toml, src/uu/split/src/filenames.rs, src/uu/split/src/split.rs, src/uu/split/src/strategy.rs, src/uu/tac/Cargo.toml, src/uu/tac/src/error.rs, src/uu/unexpand/Cargo.toml, src/uu/unexpand/src/unexpand.rs, src/uu/wc/src/utf8/read.rs
closes #7538, closes #7534, closes #7533, closes #7532, closes #7531, closes #7530, closes #7529
=> Move more errors to thiserror

src/uucore/Cargo.toml, src/uucore/src/lib/features/checksum.rs
After reading https://github.com/uutils/coreutils/issues/7504, i looked in https://github.com/uutils/coreutils-tracking/blob/main/individual-size-results/ and saw that `cksum` had a big jump in size as well. I identified the culprit: bringing in the regex crate. 
After looking a bit into regex for bytes, I tried removing the regex calls altogether and i came up with this branch.
The binary size is much smaller: `1.4MB` vs `3.1MB` .
The binary is much faster (?!) tested on a 162500 lines long file of b2sum 50% tagged and 50%untagged checksum :
```bash
taskset -c 0 hyperfine --warmup 10 -L cksum ../cksum.latest,../target/release/cksum "{cksum} -c checkbig.b2sum" --export-csv output.csv
Benchmark 1: ../cksum.latest -c checkbig.b2sum
Time (mean ± σ):     914.7 ms ±   2.8 ms    [User: 451.6 …
```
=> cksum: take out regex pattern matching

tests/by-util/test_stat.rs
These tests have been so flaky, sounds better to just disable for now. We can try to implement the fix documented in #7583 and re-enable at some point.
---
It's not totally clear why they sometimes work, sometimes fail, but it does appear that running `stat` on `/dev/stdin` is perhaps not the most reliable approach.
A likely more solid approach is described in #7583.
=> test_stat: Disable test_stdin_pipe_fifo1/2 on Mac OS X

src/uucore/src/lib/features/format/argument.rs, src/uucore/src/lib/features/format/extendedbigdecimal.rs, src/uucore/src/lib/features/format/num_parser.rs, src/uucore/src/lib/features/format/spec.rs, tests/by-util/test_printf.rs
Stacks on top of #7514.
The main direct advantage of this change is that `printf` parser is a bit more accurate (more corner cases are covered), and can now print floats with arbitrary precision.
A follow-up CL will move `seq` to use this parsing functions as well, so that we do not have to maintain and fix 2 different set of parsing functions like we do now.
- Changes the integer parsing code to use `ExtendedBigDecimal` internally
- Add support for scientific number parsing.
- Fix a few corner cases (leading `+`, no binary floats, etc.)
`printf "%.24f %.24a\n" 0.1 0.1` after this PR:
```
0.100000000000000000000000 0xc.cccccccccccccccccccccccdp-7
```
`main` used to print (`f64` precision)
```
0.100000000000000005551115 0xc.cccccccccccd000000000000p-7
```
More precise than what coreutils …
=> uucore: format: num_parser: Use ExtendedBigDecimal

tests/by-util/test_uptime.rs
This PR fixes an "unused import" warning in test on FreeBSD (and on OpenBSD), see https://github.com/uutils/coreutils/actions/runs/14187800672/job/39746177169?pr=7627#step:5:4257
=> uptime: fix "unused import" warning in test

src/uu/sort/BENCHMARKING.md, src/uu/sort/src/chunks.rs, src/uu/sort/src/sort.rs
Numeric sort can be relatively slow on inputs that are wholly or
mostly numbers. This is more clear when comparing with the speed of
GeneralNumeric.
This change parses whole lines as f64 and stores that info in
`LineData`. This is faster than doing the parsing two lines at
a time in `compare_by()`.
```
shuf -i 1-1000000 -n 1000000 > shuffled.txt
hyperfine --warmup=4 -r10 '<sort_cmd> -n /tmp/shuffled.txt'
```
`default_release`
```
Benchmark 1: /tmp/before_coreutils_defaults sort -n /tmp/shuffled.txt
Time (mean ± σ):     363.2 ms ±  10.2 ms    [User: 1906.8 ms, System: 15.9 ms]
Range (min … max):   350.3 ms … 380.8 ms    10 runs
```
`codegen-units=1` `-C target-cpu=native`
```
Benchmark 1: /tmp/before_coreutils_native sort -n /tmp/shuffled.txt
Time (mean ± σ):     357.9 ms ±   9.8 ms …
```
=> sort: immediately compare whole lines if they parse as numbers

src/uucore/src/lib/features/format/argument.rs, src/uucore/src/lib/features/format/extendedbigdecimal.rs, src/uucore/src/lib/features/format/num_format.rs, src/uucore/src/lib/features/format/num_parser.rs, tests/by-util/test_printf.rs
Stacks on top of #7556. A bunch of fixes and additions to parsing code that brings common core parsing to parity with `seq` implementation, and will allow the custom `seq` parser to be removed in the next PR.
---
Not much more that can be easily simplified now.
1E3 and 0x1P3 are acceptable numbers.
Sprinkle uppercase values in the tests.
When parsing floating point numbers, return errors if we end up
overflowing/underflowing BigDecimal (e.g. with large/small exponents).
When parsing integers, we should still return the min/max value
of the type (depending on the type), and wrap that in the error.
We need to refactor the map function to handle this case better,
and add an extract function to get the value out of an error
(if any).
This fixes the integer part of #7508.
-i64::MIN overflows …
=> uucore: format: Collection of small parser fixes

Cargo.lock, src/uucore/src/lib/features/format/extendedbigdecimal.rs, src/uucore/src/lib/features/format/num_format.rs
This PR bumps `bigdecimal` from `0.4.7` to `0.4.8` and fixes a failing test.
=> Bump `bigdecimal` & fix failing test

Cargo.lock, deny.toml
This PR bumps `iana-time-zone` from `0.1.62` to `0.1.63` and adds `windows-core` to the skip list in `deny.toml`.
=> Bump `iana-time-zone` & add `windows-core` to skip list

src/uu/cat/src/cat.rs, tests/by-util/test_cat.rs
Fixes #7637
Fixes an crash seen when running with -T option if no newline is found in a buffer.
Added unit test to validate.
=> cat: bugfix when running with -T option

src/uu/yes/src/yes.rs, tests/by-util/test_cp.rs, tests/by-util/test_dd.rs, tests/by-util/test_factor.rs, tests/uutests/src/lib/util.rs
This PR fixes warnings from the [doc_overindented_list_items](https://rust-lang.github.io/rust-clippy/master/index.html#doc_overindented_list_items), [unnecessary_semicolon](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_semicolon), and [manual_repeat_n](https://rust-lang.github.io/rust-clippy/master/index.html#manual_repeat_n) lints. It also fixes an "unused import" warning in a test.
=> clippy: fix warnings from Rust 1.86

src/uu/seq/src/error.rs, src/uu/seq/src/seq.rs, tests/by-util/test_seq.rs
=> seq: Do not allow -w and -f to be specified at the same time

src/uu/seq/src/numberparse.rs, tests/by-util/test_seq.rs
Otherwise, `seq` crashes with ` 0xee.` as input.
Also update one of the tests to catch that.
=> seq: Trim whitespaces, then try to remove +

src/uu/seq/src/seq.rs, src/uucore/src/lib/features/format/num_format.rs, src/uucore/src/lib/features/format/spec.rs, tests/by-util/test_printf.rs
Fix 2 more printing issues. For now, we print like GNU coreutils on x86-64 does. I plan to write up a bit more about float precision handling (and how we are different from GNU coreutils, not just in `printf`, but also in `seq`), but I think I'll do that as a separate PR.
---
The default hex format, on x86(-64) prints 15 digits after the
decimal point, _but_ also trims trailing zeros, so it's not just
a simple default precision and a little bit of extra handling is
required.
Also add a bunch of tests.
Fixes #7364.
The default precision for float actually depends on the format.
It's _usually_ 6, but it's architecture-specific for hexadecimal
floats.
Set the precision as an Option, so that:
- We don't need to sprinkle `6` in callers
- We can actually handle unspecified precision correctly …
=> uucore: format: Fix hexadecimal default format print

src/uucore/src/lib/features/parser/num_parser.rs, src/uucore/src/lib/features/parser/parse_time.rs, tests/by-util/test_timeout.rs
Note that unlike GNU coreutils, any value > 0 will not be treated
as 0, even if the exponent is very large.
Gives a little bit more flexibility in terms of allowed input
for durations (e.g. in `timeout`), e.g. hex floating point
numbers are now allowed.
Fixes another part of #7475.
Values like 0e18172487393827593258 and 0e-18172487393827593258 should
just be parsed as 0, and do not need to return an error.
There were some missing corner cases when handling infinity and
nan:
- inf/infinity can be capitalized
- nan must always be rejected, even if a suffix is provided
Also, return Duration::MAX with infinite values, just for consistency
(num.fract() returns 0 for infinity so technically we were just
short of that).
Add unit tests too.
Fixes some of #7475.
=> timeout: Use common parser to parse time duration

Cargo.lock, src/uu/cat/Cargo.toml, src/uu/cat/src/cat.rs
Use memchr library in `cat` to improve performance when detecting newlines.
Significantly improves performance when running with -n, -s, -E, -b flags.
=> cat: Formatting performance improvement

.github/workflows/CICD.yml, .github/workflows/FixPR.yml, fuzz/Cargo.lock
Not sure how useful the FixPR.yml change is, given #7651...
---
For some reason this lockfile has not been updated since the
edition 2024/1.85.0 update.
=> .github/workflows: Take care of both ./Cargo.lock and fuzz/Cargo.lock

src/uu/cat/src/cat.rs
Add a simple class to manually maintain a string representation of the line number for the `cat` application.
Maintaing this string is much faster than converting a `usize` line-number variable to a string each time it's needed.
Gives a significant performance improvement with `-n` and `-b` flags.
=> cat: Performance improvement when printing line numbers

src/uucore/src/lib/features/format/argument.rs, src/uucore/src/lib/features/format/spec.rs, src/uucore/src/lib/features/parser/num_parser.rs, tests/by-util/test_printf.rs
This pull request fixes the tests/printf/printf.sh tests. The main discrepancies between the uutil's implementation and GNU's appear to be the handling of negative widths or precisions when provided for `%*.*` - this was implemented for strings, but this PR brings other format specifications to also handle negative widths/precisions.
This PR also allows character constants with " instead of '. I had trouble finding any documentation about this; as far as I can tell GNU printf treats " and ' the same in the situations tested.
There is also a bug fix for interpolated values with %b to use \0XXX notation for octal bytes - this comes in for something like `printf '\0001'`, which should be the null byte and an ASCII '1', vs `printf '%b' '\0001'`, which is the single 0x01 byte because …
=> printf: Consistently handle negative widths/precision

src/uu/tail/src/tail.rs
Reasonable performance improvements for `tail` command. Benchmarks...
```
$ hyperfine -L tail /usr/bin/tail,./target/release/tail.original,./target/release/tail "{tail} -n 100000 ./shakespeare.txt"
Benchmark 1: /usr/bin/tail -n 100000 ./shakespeare.txt
Time (mean ± σ):       4.8 ms ±   0.4 ms    [User: 2.6 ms, System: 2.3 ms]
Range (min … max):     4.2 ms …   6.7 ms    539 runs
Benchmark 2: ./target/release/tail.original -n 100000 ./shakespeare.txt
Time (mean ± σ):       4.6 ms ±   0.7 ms    [User: 3.1 ms, System: 1.5 ms]
Range (min … max):     3.9 ms …  11.7 ms    466 runs
Benchmark 3: ./target/release/tail -n 100000 ./shakespeare.txt
Time (mean ± σ):       3.6 ms ±   0.4 ms    [User: 2.2 ms, System: 1.4 ms]
Range (min … max):     3.1 ms …   5.9 ms    689 runs
Summary …
```
=> tail: Performance improvements

fuzz/fuzz_targets/fuzz_common/mod.rs, src/uu/base32/src/base_common.rs, src/uu/basename/src/basename.rs, src/uu/dd/src/blocks.rs, src/uu/dd/src/parseargs/unit_tests.rs, src/uu/expr/src/syntax_tree.rs, src/uu/pathchk/src/pathchk.rs, src/uu/sort/src/sort.rs, src/uu/stty/src/flags.rs, src/uu/tr/src/tr.rs, src/uucore/src/lib/features/version_cmp.rs, tests/by-util/test_cp.rs, tests/by-util/test_du.rs, tests/by-util/test_id.rs, tests/by-util/test_ls.rs, tests/by-util/test_mv.rs, tests/test_util_name.rs
Deleted commas in cases like `foo,)` -- mostly in macros
=> chore: cleanup trailing commas before parens

fuzz/fuzz_targets/fuzz_cksum.rs, fuzz/fuzz_targets/fuzz_common/mod.rs, fuzz/fuzz_targets/fuzz_common/pretty_print.rs, fuzz/fuzz_targets/fuzz_expr.rs, fuzz/fuzz_targets/fuzz_test.rs, tests/benches/factor/benches/table.rs, tests/by-util/test_chcon.rs, tests/by-util/test_chgrp.rs, tests/by-util/test_chmod.rs, tests/by-util/test_cksum.rs, tests/by-util/test_cp.rs, tests/by-util/test_csplit.rs, tests/by-util/test_dd.rs, tests/by-util/test_du.rs, tests/by-util/test_head.rs, tests/by-util/test_install.rs, tests/by-util/test_ln.rs, tests/by-util/test_ls.rs, tests/by-util/test_mktemp.rs, tests/by-util/test_realpath.rs, tests/by-util/test_rm.rs, tests/by-util/test_sort.rs, tests/by-util/test_stat.rs, tests/by-util/test_tail.rs, tests/by-util/test_tee.rs, tests/by-util/test_touch.rs, tests/test_util_name.rs, tests/uutests/src/lib/macros.rs, tests/uutests/src/lib/util.rs
Follow up to the other few lint PRs - keeping test PRs separate to ensure stability
Minor manual cleanup - inlined many format args.  This makes the code a bit more readable, and helps spot a few inefficiencies and possible bugs.  Note that `&foo` in a `format!` parameter results in a 6% extra performance cost, and does not get inlined by the compiler (yet).
=> chore: manual inline formatting - tests

src/uu/id/src/id.rs
Spotted while doing format arg inlining, and confirmed in https://github.com/uutils/coreutils/pull/7689#issuecomment-2786827777
cc: @cakebaker
=> bug: fix id printing of egid

src/uu/csplit/src/split_name.rs, src/uu/cut/src/searcher.rs, src/uu/dd/src/parseargs.rs, src/uu/install/src/install.rs, src/uu/ln/src/ln.rs, src/uu/ls/src/colors.rs, src/uu/od/src/prn_float.rs, src/uucore/src/lib/features/checksum.rs, src/uucore/src/lib/features/format/num_format.rs
A few minor linting changes:
* simplify a few `match` statements
* use `.is_empty()` instead of creating a new vector just to see if there is nothing in it
* do not use `std::u64` - use `u64` keyword instead. Note that `MAX` is deprecated when used the old way.
* remove `mut` in the `&mut self` for few functions that don't need it
* remove unneeded casting
=> feat: minor linting

src/bin/coreutils.rs, src/uu/env/src/env.rs, src/uu/ls/src/ls.rs, src/uu/pr/src/pr.rs, src/uu/ptx/src/ptx.rs, src/uu/tail/src/chunks.rs, src/uu/tail/src/tail.rs, src/uucore/src/lib/features/parser/parse_size.rs, src/uucore/src/lib/mods/error.rs, tests/by-util/test_cp.rs, tests/by-util/test_factor.rs, tests/by-util/test_ls.rs
Keeps code a bit more readable. Also uses `write!` macro to optimize writing to a `String` using `format!`
=> chore: remove unneeded parens

src/uu/mktemp/src/mktemp.rs
This prevents a race conditions vulnerability in the `make_temp_dir` implementation, where an attacker potentially could modify the created temporary directory, before the restrictive permissions are set.
The race conditions occurs in the moment between the temporary directory is created, and the proper permissions are set.
This patch changes the `make_temp_dir` to create the temporary directory with the proper permissions creation time. Rather than first create, then set permissions. This is done by giving the permissions to the builder. See [tempfile doc](https://github.com/Stebalien/tempfile/blob/95540ed3fcb9ca74845c02aee058726b2dca58b7/src/lib.rs#L449-L450).
The attack is only possible if the umask is configured to allow writes by group or other for newly created files/directories. …
=> mktemp: Prevent race condition when setting permissions for tempdir

.github/workflows/fuzzing.yml, fuzz/fuzz_targets/fuzz_cksum.rs, fuzz/fuzz_targets/fuzz_common/mod.rs, fuzz/fuzz_targets/fuzz_common/pretty_print.rs, fuzz/fuzz_targets/fuzz_cut.rs, fuzz/fuzz_targets/fuzz_echo.rs, fuzz/fuzz_targets/fuzz_env.rs, fuzz/fuzz_targets/fuzz_expr.rs, fuzz/fuzz_targets/fuzz_printf.rs, fuzz/fuzz_targets/fuzz_split.rs, fuzz/fuzz_targets/fuzz_test.rs, fuzz/fuzz_targets/fuzz_tr.rs, fuzz/fuzz_targets/fuzz_wc.rs
Not quite sure what's the proper way to run `cargo clippy` in fuzz, as it fails if I do `cd fuzz && cargo clippy`.
Let's fix what we can for now, we can think about how to add `fmt`/`clippy` tests to CI later (#7718).
---
Just in case some of the values cause an infinite loop (or at
least take a _very_ long time, see #7708), timeout, with the same
duration as the maximum total fuzzing time.
That'll allow us to _see_ what input causes the infinite loop.
Unfortunately, cargo clippy fails when testing fuzz_seq_parse_number:
```
error[E0603]: module `number` is private
--> fuzz_targets/fuzz_seq_parse_number.rs:9:13
|
9  | use uu_seq::number::PreciseNumber;
|             ^^^^^^ private module
|
note: the module `number` is defined here
--> …
```
=> Fuzzing: minor fixes

Cargo.lock, deny.toml
This PR manually bumps `hostname` from `0.4.0` to `0.4.1` because `renovate` fails to create an PR (see the [dependency dashboard](https://github.com/uutils/coreutils/issues/4598)). It also removes `windows-core` from the skip list in `deny.toml`.
=> Bump `hostname` & remove `windows-core` from skip list

src/uucore/src/lib/features/parser/num_parser.rs
The number of digits would grow exponentially when large exponents are passed, leading to conversion of numbers like 0x2p1000000 taking forever to compute.
We use exponentiation by squaring to keep the precision within reasonable bounds.
Fixes #7708.
=> uucore: num_parser: Limit precision when computing 2**exp

src/uucore/src/lib/features/parser/num_parser.rs, tests/by-util/test_printf.rs
When printing unsigned numbers, GNU coreutils makes negative numbers around, so when we try to get a u64 from a BigInt and it's negative, convert it to an i64 and from that to a u64 so it wraps around.
For the test cases I used the same ones as in the original issue https://github.com/uutils/coreutils/issues/7488
Closes https://github.com/uutils/coreutils/issues/7488
=> printf: make negative values wrap around with unsigned/hex format

src/uu/numfmt/src/format.rs, src/uu/numfmt/src/numfmt.rs, src/uu/numfmt/src/options.rs, tests/by-util/test_numfmt.rs
This partially fixes https://github.com/uutils/coreutils/issues/1280. With this patch, the GNU compatibility tests for `numfmt --zero-terminated` pass:
```
$ bash util/run-gnu-test.sh tests/misc/numfmt.pl
...
z1...
z3...
z2...
z4...
z5...
...
```
One thing to note is that this patch does an `unwrap` on `String::from_utf8` because `BufRead.split(0)` results in `Vec<u8>` instead of `String`. This isn't a regression though because the rest of the program already assumes input can be put into `String`. Here's an example from the `main` branch:
```
$ printf "\xED\xBF\xBF" | cargo run -q --bin coreutils numfmt
numfmt: stream did not contain valid UTF-8
```
I don't see a bug report for that so I'm happy to file one. I just didn't want to do more than one thing in this PR.
=> numfmt: add --zero-terminated option

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
- added logic to check in `copy_source` after resolving src and dst to compare
timestamps
- if dst is newer, we skip the operation and prevent prompting the user
- else, proceed to copy
Fixes #7660
=> cp: fix update prompting

src/uu/cp/src/copydir.rs, src/uu/install/src/install.rs, src/uu/tee/src/tee.rs
* `cp`: in `copy_dir.rs`, remove duplicate copy_file() calls and streamline error handling
* `install`: simplify `preserve_timestamp`
* `tee` - simplify error handling
=> chore: clean up a few code paths

src/uu/chmod/src/chmod.rs, src/uu/cp/src/copydir.rs, src/uu/cp/src/cp.rs, src/uu/df/src/blocks.rs, src/uu/env/src/env.rs, src/uu/expand/src/expand.rs, src/uu/fmt/src/fmt.rs, src/uu/id/src/id.rs, src/uu/readlink/src/readlink.rs, src/uu/tail/src/follow/files.rs, src/uu/unexpand/src/unexpand.rs, src/uucore/src/lib/features/signals.rs
It is usually easier to reason about the code if the `return` is used in one place rather than in every branch of the match or if statements.
=> chore: simplify `return` in multi-branch

src/uu/fmt/src/fmt.rs
Fix an overly complex case when w is 0. Note that this might have been an error - I kept the logic, but the initial implementation might have been incorrect.
=> chore: minor fmt match cleanup

Cargo.toml
I am not sure what the original issue was, but it seems to work:
```
cargo build --target=x86_64-unknown-linux-musl --features feat_os_unix_musl
...
coreutils$ ./target/x86_64-unknown-linux-musl/debug/coreutils stdbuf -o L echo "foobar"
foobar
```
=> enable feature_require_crate_cpp for musl

src/uu/du/src/du.rs, tests/by-util/test_du.rs
```console
$ cargo run du -B0
Running `target/debug/coreutils du -B0`
thread '<unnamed>' panicked at src/uu/du/src/du.rs:551:26:
attempt to divide by zero
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
du: sending on a closed channel
[$? = 1]
```
I think that's a new record for fewest characters needed to cause a panic :D
This PR fixes the panic, and adds a test to ensure we don't regress.
This addresses only part of #7738.
=> du: don't panic on block-size 0

Cargo.toml, src/uu/chroot/src/chroot.rs, src/uu/cp/src/copydir.rs, src/uu/cp/src/cp.rs, src/uu/dd/src/dd.rs, src/uu/pr/src/pr.rs, src/uu/split/src/platform/unix.rs, src/uu/split/src/platform/windows.rs, src/uu/split/src/split.rs, src/uu/split/src/strategy.rs, src/uu/touch/src/touch.rs
Resolve [ref_option](https://rust-lang.github.io/rust-clippy/master/index.html#ref_option) lint.  Also, I optimized `is_first_filename_timestamp` a bit to make it faster and more streamlined.  In some cases, I replaced `&Option<T>` with `Option<T>` instead of a reference when `T` was copyable.
p.s. disclaimer: I'm the author of that lint
=> chore: fix `ref_option` lint

src/uu/comm/src/comm.rs, src/uu/cp/src/copydir.rs, src/uu/du/src/du.rs, src/uu/echo/src/echo.rs, src/uu/env/src/native_int_str.rs, src/uu/fmt/src/linebreak.rs, src/uu/mv/src/mv.rs, src/uu/split/src/platform/unix.rs, src/uu/split/src/platform/windows.rs, src/uu/split/src/split.rs, src/uu/touch/src/touch.rs, src/uu/unexpand/src/unexpand.rs, src/uu/wc/src/wc.rs, src/uucore/src/lib/features/checksum.rs, tests/uutests/src/lib/util.rs
This applies some straight-forward suggestions from clippy-nightly. I checked each one manually, and I'm convinced this is correct.
Originally, I wanted to tackle the "unused `std::ops::ControlFlow`" warnings, but I'm not convinced that these are correct.
In particular:
- https://rust-lang.github.io/rust-clippy/master/index.html#io_other_error
- https://rust-lang.github.io/rust-clippy/master/index.html#let_and_return
- https://rust-lang.github.io/rust-clippy/master/index.html#manual_contains
- https://rust-lang.github.io/rust-clippy/master/index.html#mem_replace_option_with_some
- https://rust-lang.github.io/rust-clippy/master/index.html#ptr_eq
=> Apply suggestions from clippy 0.1.87+nightly

src/uu/head/src/head.rs, src/uu/head/src/parse.rs, tests/by-util/test_head.rs
closes #7166
Also changes number parsing to allow for a leading `+`, in line with GNU `head`
=> head: fix overflow errors

.github/workflows/code-quality.yml, .github/workflows/freebsd.yml, Cargo.toml, src/uu/df/src/filesystem.rs, src/uu/head/src/take.rs
This PR moves the lints defined in the CI to the `workspace.lints.clippy` section in `Cargo.toml`. The reason for this move is to have a single place for lints we enforce.
The PR also fixes a few clippy warnings that showed up in the CI.
=> Move clippy lints from CI to `Cargo.toml`

tests/by-util/test_date.rs
- Converts the resultant date to UTC.
- Takes the absolute difference of the result and the expected value.
- Checks if this value is less than (within) a window.
=> refactor(tests): use absolute difference of dates to check if they are within a window

util/gnu-patches/series, util/gnu-patches/tests_du_move_dir_while_traversing.patch, util/gnu-patches/tests_env_env-S.pl.patch
This PR adapts a GNU test to accept our phrasing of the error message.
I was looking at low-hanging fruit on [the table](https://uutils.github.io/coreutils/docs/test_coverage.html), and dived straight into `du/move-dir-while-traversing`.
This GNU test exists to ward against a regression: an old GNU coreutils version used to contain a bug that triggered an assertion failure. The test's intention is to make sure that `du` fails not due to an assertion error (thus not producing any information, or corrupt output), but rather due to the correct reason (files vanishing). In particular, we simply emit a slightly different error message than GNU, and that's why we technically didn't pass that test.
However, since we pass the *spirit* of the test, I think it is appropriate to adapt the test to …
=> du: already passes GNU test in spirit, adjust test

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
Follow up to https://github.com/uutils/coreutils/pull/7729#discussion_r2041156999
Recap:
```
$ ln -s nonexistent bad
$ cp -P --link bad bad2
$ ls -1i bad bad2
20145169 bad
20145169 bad2
$ cp -P bad bad2
$ ls -1i bad bad2
20145169 bad
20145169 bad2
$ cargo run -q cp -P bad bad2
$ ls -1i bad bad2
20145169 bad
20178774 bad2
```
It looks like GNU detects that the hardlinks are the same and simply no-ops (I did an `strace` and all it's doing is `stat`-ing each file and exiting). There's similar logic in `uutils`, but it's currently conditioned on the backup option. I think this is unnecessary since if source and dest are hardlinks to the same file, then no actual copy should be necessary. Let me know if I may be missing something though; there are an awful lot of obscure edge cases though …
=> cp -P hardlink-to-symlink hardlink-to-same-symlink should no-op

src/uu/sleep/Cargo.toml, src/uu/sleep/src/sleep.rs, src/uucore/src/lib/features/parser/num_parser.rs, src/uucore/src/lib/features/parser/parse_time.rs, tests/by-util/test_sleep.rs, tests/by-util/test_timeout.rs
closes #7669
`sleep` now uses uucore's `from_str` instead of `fundu` to support hex parsing. This changes some error output (although it looks to be more in line with GNU, not less), so I changed the relevant tests as well. However, at first glance, it looks like it might be returning "empty string" in unexpected cases (e.g. '\n').
=> fix(sleep): use uucore's from_str to support parsing hex

Cargo.lock, src/uu/sleep/Cargo.toml
This PR removes `fundu` from `Cargo.toml` as it is no longer used due to https://github.com/uutils/coreutils/pull/7675
=> sleep: remove unused `fundu` from `Cargo.toml`

.clippy.toml, src/uu/cp/src/cp.rs, src/uu/ln/src/ln.rs, src/uu/mv/src/mv.rs, src/uu/stty/src/stty.rs, src/uucore/src/lib/features/backup_control.rs, src/uucore/src/lib/features/checksum.rs, src/uucore/src/lib/features/sum.rs, src/uucore/src/lib/features/update_control.rs
* Disabled `avoid-breaking-exported-api` and sorted items in Clippy.toml
* Renamed `BSD` -> `Bsd`, `SYSV` -> `SysV`, and `CRC` -> `Crc` to match Rust naming rules
* Renamed items in `BackupMode` and `UpdateMode` because they repeated the same word in every item - making it redundant and harder to read
=> chore: address a few clippy lints that break API

src/uu/chroot/src/chroot.rs, src/uu/chroot/src/error.rs, src/uu/nproc/src/nproc.rs, src/uu/split/src/strategy.rs
* There is no need to allocate a vector when matching a sequence of items.
* This also removes an unused `InvalidUserspec` error
=> feat: optimize iter matching

src/uucore/src/lib/features/parser/num_parser.rs, tests/by-util/test_printf.rs
~This can wait a bit, e.g. after #7656 and #7675 so they don't have to rebase (I don't think there's any direct logical conflict but maybe some context).~
---
printf treats "0x" as a partial match of 0 and "x".
Numbers like 123.15e or 123.15e- should return PartialMatch.
Numbers like `e`, `.e` are not valid.
Fixes #7685.
This is mostly important when parsing digits like `.` and `0x.`
where we should return an error.
Fixes #7684.
=> parser: Fix 3 corner cases

src/uu/mkdir/src/mkdir.rs, src/uu/stat/src/stat.rs, src/uucore/src/lib/features/selinux.rs
This PR renames `check_selinux_enabled()` to `is_selinux_enabled()` and changes its return type from `Result<(), Error>` to `bool` to improve the API.
The PR conflicts with https://github.com/uutils/coreutils/pull/7768 and https://github.com/uutils/coreutils/pull/7769
=> selinux: rename `check_selinux_enabled()`

src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs
This update relies on [MR46](https://github.com/uutils/uutils-term-grid/pull/46) in `uutils-term-grid` crate.
This update uses new `Filling::Tabs` option instead of explicitly setting text separator with \t.
Closes #6897 
Closes #7526 
Closes #3624
=> ls: add -T support and fix --classify output

Cargo.lock, Cargo.toml, tests/by-util/test_uptime.rs
This PR bumps `bincode` from `1.3.3` to `2.0.1` and adapts an `uptime` test to API changes.
=> Bump `bincode` & adapt test code to API changes

src/uu/df/src/df.rs, tests/by-util/test_df.rs
This PR fixes #6194 .
When `df` receives both a `-t` type filter and file paths, the mount point for each path must be determined before the filesystem type filter is applied.
The cause of this bug was that the filtering was applied at https://github.com/uutils/coreutils/blob/e147063e26c42647f9b3b6cf018ac5dfe11183da/src/uu/df/src/df.rs#L387 before the mount point was determined at https://github.com/uutils/coreutils/blob/e147063e26c42647f9b3b6cf018ac5dfe11183da/src/uu/df/src/df.rs#L403 
This led to mount points being incorrectly determined for paths in some cases. For instance, on MacOS `cargo run df -a -t apfs /dev` would print the mount point at `/`. More examples are given in #6194 
The fix was to re-order filtering and mount point resolution.
=> fix: df: filter filesystem types after mount point resolution

src/uu/more/src/more.rs
fix(partially) #6397.
This PR improves `uu_more` by storing only the lines to be drawn in memory.
1. We pass in a file object that implements `BufRead + Seek` into `more()` .
2. When initializing the `Pager` object, we scan the entire file once and store the byte positions of each line for faster subsequent file scans. If pattern matching is required, we save the first line containing the pattern.
4. When drawing lines, we first read only `self.content_rows` no. lines into memory (in `load_visible_lines`) before writing to `stdout`.
=> more: keep only screen lines in mem

.github/workflows/CICD.yml, Cargo.toml, src/uu/pinky/src/pinky.rs, src/uu/uptime/src/uptime.rs, src/uu/users/src/users.rs, src/uu/who/src/who.rs, src/uucore/src/lib/features.rs, src/uucore/src/lib/lib.rs, tests/by-util/test_uptime.rs
musl provides stubs of the utmpx functions, and those stubs are provided in the libc crate version 0.2.172. Thus let's enable the feature so that it can compile with musl. Note that those stubs always return a success exit value, and commands such as "users" will report an empty list of users, when calling those stubs.
This is consistent with the behavior of GNU coreutils which does the same thing.
The coreutils utillities using utmpx are "pinky", "uptime", "users", "who". This is the expected behavior when using those utilities compiled with those musl utmpx stubs:
```
root@qemuarm64:~# users
root@qemuarm64:~# echo $?
0
root@qemuarm64:~# pinky
Login    Name                 TTY      Idle   When         Where
root@qemuarm64:~# echo $?
0
root@qemuarm64:~# uptime
12:58:47 up 0 min,  0 users, …
```
=> enable utmpx feature for musl

src/uu/mv/src/mv.rs
Factor out helper functions from the `rename_with_fallback()` function so that there is one fallback helper per file type (symlink, directory, or file). This doesn't change the functionality of `mv`, it is just a re-organization of the code.
This was extracted from pull request #7241.
=> mv: factor rename_with_fallback function into helpers

src/uu/csplit/src/csplit_error.rs
no need to implement this manually when you can use `#[from]` from `thiserror`.
=> csplit: removed unnecesary implementation of From<io::Error>

.github/workflows/CICD.yml, src/uucore/src/lib/features/selinux.rs, tests/by-util/test_ls.rs, tests/by-util/test_stat.rs
I noticed that clippy warnings related to SELinux don't show up in the CI. This PR adds a linting step to the `test_selinux` job in the CI.
=> ci: lint with selinux

tests/by-util/test_du.rs
While working on #7739, I notices a weird warning message that I've never seen before: `warning: options --apparent-size and -b are ineffective with --inodes`. Turns out, we already implement that correctly. Awesome! To make sure we never accidentally lose this correct behavior (it's a very informative warning!), let's add a test.
=> du: test existing correct behavior: warn about --inodes -b conflict

src/uu/cp/src/cp.rs, src/uucore/src/lib/features/fs.rs
Create a function `uucore::fs::make_fifo()` for creating a named pipe on Unix systems, and use it in `cp`.
This was extracted from pull request #7241. The `make_fifo()` function will be used in `mv` as well.
=> cp: factor make_fifo() function out to uucore::fs

Cargo.lock, src/uu/whoami/Cargo.toml
This dependency was specified under cfg(unix) but is no longer used in the whoami crate.
=> whoami: remove unused libc dependency

src/uu/env/src/env.rs, tests/by-util/test_env.rs
Fixes https://github.com/uutils/coreutils/issues/7750
Problem: `env` applies special case logic to some args, such as `-u` and `-S`. However, it applies this logic to args that are supposed to be only for the program it invokes.
Solution: In the code that special cases certain args, figure out when we've gotten to the command name and stop processing.
This also puts long option names into constants since they're used in a few places now.
=> env: ignore flags after the command or -- argument

src/uu/tail/src/args.rs, tests/by-util/test_tail.rs
Fixes issue #7613
Tail now correctly handles the -v flag when only 1 input file is given.
=> tail: fix issue with -v flag and stdin

src/uu/install/src/install.rs, tests/by-util/test_install.rs
show friendly message when following happens:
```
touch file
mkdir dir1
mkdir dir1/file
install file dir1/
```
=> install: friendly message install file to directory

src/uu/shred/src/shred.rs, tests/by-util/test_shred.rs
This is tested for in the GNU shred-passes test, so we don't have a choice if we want to stay compatible.
Found while getting ready for #5711.
=> shred: remove unwanted padding in verbose messages

src/uu/chroot/src/chroot.rs
I tried to use the uutils `chroot` binary, it failed saying it can't switch to the new root. I found that the line I'm changing in this PR was the culprit, and commented it out. This made it work, however the new shell opened in the directory I had previously opened (I believe it was mapped inside the new root somewhere). Changing the `set_current_dir` call to target `/` (which is always the new root AFAIK, since this call runs after `chroot`) seems to do the right thing (it worked for me).
I did not look into how other implementations of `chroot` work, I only observed that this implementation was broken (initially the version AerynOS ships, then a self-built binary from the latest state of this repo, a little over two weeks ago), and played around with it until I had a fix that worked, …
=> Fix chroot trying to change into non-existent directory

src/uu/ls/BENCHMARKING.md, src/uu/ls/src/ls.rs
See #7563, I'll have more fixes, but these are low-hanging fruits in printing.
We get closer to GNU coreutils (~10%),  this improves performance by about ~15% for the use case below.
```
cargo build -r -p uu_ls && taskset -c 0 hyperfine --warmup 100 -L ls ls,target/release/ls,./ls-main "{ls} -lR /var/lib .git || true"
Benchmark 1: ls -lR /var/lib .git || true
Time (mean ± σ):      26.7 ms ±   1.2 ms    [User: 11.3 ms, System: 14.7 ms]
Range (min … max):    25.8 ms …  38.5 ms    109 runs
Benchmark 2: target/release/ls -lR /var/lib .git || true
Time (mean ± σ):      29.5 ms ±   1.3 ms    [User: 13.2 ms, System: 15.5 ms]
Range (min … max):    28.6 ms …  41.3 ms    100 runs
Benchmark 3: ./ls-main -lR /var/lib .git || true
Time (mean ± σ):      33.8 ms ±   1.5 ms    [User: 18.3 ms, System: …
```
=> ls: Print optimizations

src/uu/shred/src/shred.rs, tests/by-util/test_shred.rs
Fixes #7798.
Before:
```console
$ cargo run -q shred -v -n100 foo
<SNIP>
shred: foo: pass 11/100 (b6db6d)...
shred: foo: pass 12/100 (ffffff)...
shred: foo: pass 13/100 (222222)...
shred: foo: pass 14/100 (222222)...
shred: foo: pass 15/100 (000)...
shred: foo: pass 16/100 (999999)...
<SNIP>
```
After:
```console
$ cargo run -q shred -v -n100 foo
<SNIP>
shred: foo: pass 34/100 (random)...
shred: foo: pass 35/100 (6db6db)...
shred: foo: pass 36/100 (000000)...
shred: foo: pass 37/100 (db6db6)...
shred: foo: pass 38/100 (888888)...
<SNIP>
```
=> shred: correctly print zero-byte pass in verbose mode

tests/by-util/test_ls.rs
Do more extensive test of the output to check long output for metadata failure, without relying on GnuTests.
@sylvestre follow up from https://github.com/uutils/coreutils/pull/7801#issuecomment-2817841961 .
=> test_ls: Improve test_ls_perm_io_errors

tests/by-util/test_ls.rs
Create a file with some ACL, and another without, and check that `+` only appears on the file with ACL.
---
I was hoping to optimize `has_acl` call in `ls`, but I don't think that's possible, a syscall is required for every file. Anyway, I improved a bit the test as part of that effort, might as well push it anyway.
=> test_ls: Improve acl test

src/uu/mv/Cargo.toml, src/uu/mv/src/mv.rs, tests/by-util/test_mv.rs
Fix a bug in `mv` where it would hang indefinitely while trying to copy
a FIFO across filesystems. The solution is to remove the old FIFO and
create a new one on the new filesystem.
~The first commit factors out helper functions from the `rename_with_fallback()` function
so that there is one fallback helper per file type (symlink, directory,
or file). This doesn't change the functionality of `mv`, it is just a
re-organization of the code.~ This was done in pull request https://github.com/uutils/coreutils/pull/7774
Fixes #7076
=> mv: fix moving FIFO to a different filesystem

src/uu/mknod/src/mknod.rs, tests/by-util/test_mknod.rs
This PR removes a Windows-related function and many `#[cfg(not(windows))]` because `mknod` is a unix-only util.
=> mknod: remove windows-related code & flags

.vscode/cspell.dictionaries/workspace.wordlist.txt, Cargo.lock, Cargo.toml, fuzz/fuzz_targets/fuzz_parse_time.rs, src/uu/sleep/src/sleep.rs, src/uu/tail/Cargo.toml, src/uu/tail/src/args.rs, src/uu/timeout/src/timeout.rs, src/uucore/src/lib/features/parser/num_parser.rs, src/uucore/src/lib/features/parser/parse_time.rs, tests/by-util/test_tail.rs
- **tail: support hex parsing**
- **remove fundu dependency**
closes #7670
addresses @sylvestre's comment on #7675
From that issue:
> By just using `from_str` from `parse_time.rs` naively, only 3 tests fail:
> 
> 1. One which exceeds `float::MAX`: `1.0e100000`
> 
> 2. A single point: `.`
> 
> 3. Seconds unit: `1.0s`
The first looks erroneous to me. I can't get GNU tail to error on my system due to an interval larger than `float::MAX`.
The second and third are patched in this PR.
=> tail hex parsing, remove fundu dependency

tests/by-util/test_mknod.rs
The tests `test_invalid_arg` and `test_mknod_invalid_arg` are more or less identical. This PR removes `test_invalid_arg` and moves `test_mknod_invalid_arg` to its place.
=> mknod: remove duplicate test

src/uu/shred/src/shred.rs, tests/by-util/test_shred.rs
- **shred: fix random passes, update documentation, add test**
- **shred: update tests**
closes #7809
On my system, the number of random passes (as determined by `shred -vn$x foo.txt |& grep random | wc -l`) is not determined by `x/10`. While it's true that 25 is the tipping point at which all patterns are used, the pattern is unclear. I'll open a separate issue so I don't dump too much shell output here. For the purpose of this PR, I changed 3 + x/10 to (x/10).max(3) to get closer to GNU behavior.
=> shred: fix random passes*

src/uu/id/src/id.rs, tests/by-util/test_id.rs
Fixes #7835
The PR should get the CI back to green and does the following things:
- adapts an error message to match the one from GNU `id` 9.7
- simplifies the `test_id_default_format` and `test_id_zero` tests by extracting three new test functions that ensure a specific error message is shown
- removes all `[#[cfg(unix)]` in the tests because `id` is unix-only
=> id: adapt error message to match the one from GNU `id`

tests/by-util/test_shred.rs
This PR removes the test `test_shred_verbose_pass_single_0_byte_name`. It ensures that the `000000` pattern is used at least once within 200 iterations. A new test, `test_all_patterns_present`, introduced with https://github.com/uutils/coreutils/pull/7830, ensures that each pattern is used at least once within 25 iterations, and thus covers the previous case, too.
=> shred: remove obsolete test

src/uu/printf/src/printf.rs, src/uucore/src/lib/features/format/argument.rs, tests/by-util/test_printf.rs
=> printf: improve support of printing multi-byte values of characters

src/uu/printf/src/printf.rs, src/uucore/src/lib/features/format/argument.rs, src/uucore/src/lib/features/format/mod.rs, src/uucore/src/lib/features/format/num_format.rs, src/uucore/src/lib/features/format/spec.rs, tests/by-util/test_printf.rs
This PR implements the ability for `printf` (and the general formatting functionality in uucore) to have "conversion specifications" that explicitly say which argument to use. This comes from the [Single Unix Specification](https://pubs.opengroup.org/onlinepubs/7908799/xsh/fprintf.html) and is tested for in GNU's tests/printf/printf-indexed test.
To handle arbitrary positions, I've changed the iterator-based approach to a slice of `FormatArgument`'s, and wrapped that in a struct to keep track of the "next" argument to grab (as well as how the positions should be offset when repeatedly processing the format string
=> printf: Add indexing to format strings

docs/src/extensions.md
See also #7823.
In short: Our method of computing the number of passes is simpler and presumably matches user expectations more closely. See the diff for a longer explanation.
Closes #7823.
=> shred: document simplified (better?) number of random passes

src/uu/expr/src/syntax_tree.rs, tests/by-util/test_expr.rs
Escape the regexp start of string anchor characters '^' within pattern definitions. Only keep the start anchor as is if it is at the beginning of the user input pattern.
- Extracts a core pattern by removing a single leading ^
- Escapes any '^' characters inside the pattern body
- Ensures an asterisk (*) at the beginning of the pattern is escaped to avoid unintended regex behavior
- Always prepend a start anchor ^ to the core pattern
- Test that the start anchor (^) is not escaped if it is at the start of the input pattern
- Test that start (^) anchors are escaped within the core pattern
fixes #7663
=> expr: Escape anchor characters within pattern

src/uu/rm/src/rm.rs, tests/by-util/test_rm.rs
There's a currently redundant check in `prompt_file_permission_readonly` which is unreachable due to being under `prompt_file` but we add the extra check just in case the prompt should ever be used in a different codepath
=> rm: skip prompt when stdin is not interactive; Fix #7326

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
Fixes https://github.com/uutils/coreutils/issues/6589
Here's a quick recap of the issue:
```
$ touch exists
$ ln -s exists good
$ ln -s nonexistent bad
$ cp -P good bad .
cp: 'good' and './good' are the same file
cp: 'bad' and './bad' are the same file
$ cargo run -q cp -P good bad .  # succeeds!
```
This doesn't affect the GNU compatibility tests.
Note that the other cases described in https://github.com/uutils/coreutils/issues/6589 have the correct behavior and exit statuses, just different error messages. So I didn't bother to change those since I don't think matching error messages is a goal of this project (correct me if I'm wrong).
=> cp: refuse to copy symlink over itself

src/uu/date/src/date.rs, src/uucore/src/lib/features/custom_tz_fmt.rs, tests/by-util/test_date.rs
This was fixed upstream in #7333, but it's a good idea to have a
test here as well, especially as we're considering switching
datetime library.
It's easy to just replace %#z with %z as the capitalization makes
no sense anyway.
=> date: add `%q` test, support `%#z` properly

.github/workflows/CICD.yml
rust-orig current release is broken with GCC 15.1, and I don't think it's possible to pin to an older github image, or an older msys2 gcc...
Fixed upstream: https://github.com/rust-onig/rust-onig/issues/191
But waiting for new release: https://github.com/rust-onig/rust-onig/issues/193
=> CICD: Disable windows-latest/x86_64-pc-windows-gnu for now

Cargo.lock, Cargo.toml, fuzz/Cargo.lock, src/uu/ls/src/ls.rs, tests/by-util/test_ls.rs
Chrono just released a new version of their crate, introducing more flexible way to parse unknown format specifiers.
Closes #7802
=> ls: update chrono crate version and switch to `new_lenient` use

Cargo.toml, docs/src/performance.md
Also fix comment about release profile, debug info is not there.
@tertsdiepraam not sure if you meant something else by "debug info", but the `release` binaries definitely don't have debug(ger?) information (`strip` removes nothing).
=> Cargo.toml: Add profiling profile

src/uucore/src/lib/features/format/argument.rs, src/uucore/src/lib/features/format/spec.rs, tests/by-util/test_printf.rs
#7837 added support for indexing in format strings, but allowed for an index of 0, treating it as equivalent to an index of 1. GNU rejects 0 indexes, which makes sense, as all the other indexes are 1-indexed, which means a user could encounter difficult to debug off-by-one errors if printf didn't return an error (e.g., if looping indexes from `0..$n`).
This commit forbids 0 indexes, expressed at the type level with `std::num::NonZero`. Doing so also cuts the aligned size of `ArgumentLocation` in half, from two pointer widths to one, which is the sort of thing that could help some optimizations (I didn't run any benchmarks, the benefit is likely pretty tiny).
=> printf: use non-zero indexes

src/uu/install/src/install.rs, tests/by-util/test_install.rs
implemented and tested for situations metioned in #4066
=> Install implement the --no-target-directory option

src/uu/install/src/install.rs
This PR removes three todos. Two have been fixed in the meantime. With the last one it's unclear to me what needs to be done: I did a simple refactoring (replacing `if let Err` with `map_err`) to make the code a bit cleaner.
=> install: remove todos

tests/by-util/test_uptime.rs
This PR fixes some "unused import" warnings in the tests. See, for example, https://github.com/uutils/coreutils/actions/runs/14763292223/job/41469042921?pr=7863#step:14:243
=> uptime: fix "unused import" warnings with `musl`

src/uu/expr/src/syntax_tree.rs, tests/by-util/test_expr.rs
The previously used `REGEX_OPTION_NONE` allowed anchors (^) and ($) to match across newlines.
New anchor behaviors:
- `^` matches the start of the entire string (`\A`)
- `$` matches the end of the entire string (`\Z`)
The following is copied from the documentation comments of `RegexOptions::REGEX_OPTION_SINGLELINE`:
```
onig::flags::RegexOptions
pub const REGEX_OPTION_SINGLELINE: Self = REGEX_OPTION_SINGLELINE
─────────────────────────────────────────────────────────────────
`'^'` -> `'\A'`, `'$'` -> `'\Z'`
```
=> expr: Fix regex anchor matching behavior with `REGEX_OPTION_SINGLELINE`

src/uu/cp/src/copydir.rs, tests/by-util/test_cp.rs
This PR makes the following work:
```
$ mkdir x
$ touch x/foo
$ cp -r x/. y # directory y is created with file foo
```
Fixes #7871
=> cp: copy dir if source path ends with dot

.github/workflows/CICD.yml, src/uu/dd/Cargo.toml, src/uucore/src/lib/lib.rs, src/uucore/src/lib/mods.rs
Older versions of `uucore` could be compiled with `wasm32-unknown-unknown`. But inside `uucore::mods::io` are file handles used which only exist when you have a filesystem which wasm doesn't have. So I feature gated them behind `fs`. I cannot really run the tests on my machine as my german operating system doesn't report english error messages.
=> Allow compiling `uucore` with `wasm32-unknown-unknown`

src/uu/cp/Cargo.toml
This PR uses `authors.workspace = true` instead of the `authors` field in `Cargo.toml`, as we do in the other utils.
=> cp: use `authors.workspace` in `Cargo.toml`

src/uu/echo/src/echo.rs, src/uucore/src/lib/features/format/mod.rs, tests/by-util/test_echo.rs
[Issue 7736](https://github.com/uutils/coreutils/issues/7736)
Hello Everyone,
This PR introduces analysis of returned `ControlFlow` values, helping to eliminate compiler warnings about unused return values on nightly toolchains. It also adds the ability to exit early when encountering `EscapedCharacter::End`, which seems like the correct behavior in that case. [1]
While working on this, I noticed that the `printf` utility already relies on `ControlFlow` results. So this change also helps unify the approaches and code between `printf` and `echo`.
Please note: these are initial changes, intended for review, discussion, and testing on real examples. Any feedback or observations are highly appreciated.
Thank you
[1] Output of GNU Coreutils (9.7) and uutils/coreutils
GNU coreutils
``` …
```
=> uucore/echo:handle ControlFlow result

README.md
This PR fixes a small typo reported on issue #7895
=> uptime: fix typo (Gnu -> GNU)

src/uu/ptx/src/ptx.rs, tests/by-util/test_ptx.rs
close #2049
As discussed in the issue, `ptx` breaks when handling utf-8 characters (which may span multiple bytes). We need to use character positions instead of byte positions to index into `chars_line`. We can do so using `.chars().count()`. I created a helper function to consolidate this change since `format_roff_line` and `format_tex_line` use the same logic. I've also added some comments and renamed variables for readability.
=> ptx: use char count instead of byte index to handle utf-8 characters

src/uu/csplit/src/csplit.rs, tests/by-util/test_csplit.rs
closes #7126
`BufRead::lines` is inherently lossy in that it is impossible to know whether a line ended due to a newline or EOF. In this PR, I replaced it with a custom iterator using `BufRead::read_until` to keep track of the line endings manually.
=> csplit: don't add a newline if the file doesn't end with one

src/uu/uptime/src/uptime.rs, tests/by-util/test_uptime.rs
This PR refactors `uumain`. It applies the following changes:
* use clap to handle the "too many paths provided" error case
* remove `unix` block and make a single var platform-specific instead
* split `default_uptime` into two functions
=> uptime: refactor `uumain`

src/uu/id/src/id.rs
This PR removes two unnecessary `to_string` calls (plus a block).
=> id: remove unnecessary `to_string` calls

Cargo.lock, fuzz/Cargo.lock, src/uu/mktemp/src/mktemp.rs
This PR bumps `tempfile` from `3.19.1` to `3.20.0` and uses `keep()` instead of the deprecated `into_path()` in `mktemp`.
=> Bump `tempfile` & fix deprecation warning

tests/by-util/test_split.rs
Currently,  `add_lines` and `add_lines_with_line_size` in the test are almost identical. This PR uses delegation to remove the duplicate code. It also merges some imports.
=> split: use delegation to avoid code duplication in test

src/uu/wc/src/count_fast.rs
Fixes  #7929.
bytecount uses vector operations to speed up line counting.
At least on x86 with AVX2 support, the vectors are 256-byte wide,
and operations are much faster if the data is aligned.
Saves about 4% of total performance, matching wc's performance.
Improves performance by about 4% on large files.
---
This gets us close or better than GNU's version:
```
seq 10000000000000 1 inf | head -n 100000000 > seq100M
cargo build -r -p uu_wc && taskset -c 0 hyperfine --warmup 10 -L wc ./wc.main,target/release/wc,wc "{wc} -l tmp/seq100M"
Compiling uu_wc v0.0.30 (/home/drinkcat/dev/coreutils/coreutils/src/uu/wc)
Finished `release` profile [optimized] target(s) in 11.51s
Benchmark 1: ./wc.main -l tmp/seq100M
Time (mean ± σ):     265.1 ms ±   5.4 ms    [User: 49.7 ms, System: 212.3 ms]
Range …
```
=> wc: Speed optimization

src/uu/ls/src/ls.rs
This PR removes some duplicate code by making only the conditions platform-specific instead of the entire `if`-blocks.
=> ls: remove duplicate code

Cargo.lock, src/uu/pr/Cargo.toml, src/uu/pr/src/pr.rs
=> pr: migrate from quick-error to thiserror

.github/workflows/CICD.yml, CONTRIBUTING.md, DEVELOPMENT.md, src/uu/tail/README.md
This PR bumps the `markdownlint` action in the CI from `v19` to `v20` and fixes its warnings.
=> Bump `markdownlint` action & fix warnings

Cargo.lock, Cargo.toml, src/uu/more/Cargo.toml, src/uu/more/src/more.rs, tests/by-util/test_more.rs
close #6397
```rust
enum InputType {
File(BufReader<File>),
Stdin(Stdin),
}
``` 
This PR improves `uu_more` by achieving constant memory overhead during initialization. Previously (#7680), we read the entire file once and store byte positions. We now do so incrementally using the following techniques:
1. We handle files and pipes together using the `InputType` enum shown above. `Stdin` already implements `BufRead` and we need the underlying `File` type to get the file size for displaying the status.
2. When initializing the `Pager` object, we scan the only up to the start line (`options.from_line`). We store the lines read in `lines`, and the byte positions in `cumulative_line_sizes` to display the file navigation status.
3. If pattern matching is required, we scan from the initialized …
=> more: constant memory initialization overhead

.clippy.toml, src/uu/cp/src/cp.rs, src/uu/cp/src/platform/macos.rs, src/uu/more/src/more.rs, src/uu/mv/src/mv.rs, tests/by-util/test_cp.rs
This PR sets a MSRV of `1.85.0` for clippy and fixes warnings from the [io_other_error](https://rust-lang.github.io/rust-clippy/stable/index.html#io_other_error), [unnecessary_debug_formatting](https://rust-lang.github.io/rust-clippy/stable/index.html#unnecessary_debug_formatting), and [let_and_return](https://rust-lang.github.io/rust-clippy/stable/index.html#let_and_return) lints in order to get the CI back to green.
I attributed @Qelxiros as a co-author of the `mv` and `cp` fixes due to his work in #7941.
Fixes #7945
=> clippy: set MSRV and fix warnings

fuzz/fuzz_targets/fuzz_test.rs, tests/benches/factor/benches/table.rs
It seems these files were missed by CI. Command to run cargo fmt on absolutely *everything* (and possibly too much)
```console
$ find tests -name "*.rs" -print0 | xargs -0 cargo fmt --
```
=> Run cargo fmt on missed files

util/build-gnu.sh
It is not relevant for us:
* the selinux crate is handling errors
* the test says "maybe we should not fail when no context available"
=> cp: context Disable a check in tests/cp/no-ctx.sh

.github/workflows/CICD.yml
This PR fixes an `Unexpected input(s) 'file'` warning (see, for example, https://github.com/uutils/coreutils/actions/runs/15113187214/job/42477260722#step:10:1) from the `codecov-action` by changing the deprecated key `file` to `files`.
=> ci: fix `unexpected input 'file'` warning in coverage job

.cargo/config.toml
This PR sets `CFLAGS='-std=gnu17'` in order to make `onig` compile with GCC 15, which by default uses a newer C standard (C23).
It temporarily fixes https://github.com/uutils/coreutils/issues/7904 until there is a new `onig` release. An alternative approach would be to change the dependency line for `onig` in `Cargo.toml` as suggested in https://github.com/uutils/coreutils/issues/7904#issuecomment-2873337715
=> .cargo/config.toml: set `CFLAGS='-std=gnu17'`

src/uu/mv/src/mv.rs
This PR changes the return type of `can_delete_file` from `Result<bool, io::Error>` to `bool` as we don't care about any error.
=> mv: use `bool` instead of `Result` as return type

tests/by-util/test_du.rs
This PR fixes a "function `du_hard_link` is never used" warning that appears in the Android jobs of the CI (see, for example, https://github.com/uutils/coreutils/actions/runs/15069663302/job/42362538785?pr=7942#step:16:1600). It also fixes the same warning on OpenBSD.
=> du: fix "function never used" warning in test

src/uu/sync/src/sync.rs
I noticed the following warning in the Android jobs of the CI (see, for example, https://github.com/uutils/coreutils/actions/runs/15039807606/job/42268624578#step:16:836):
```
[2025-05-15 08:08:33] warning[E0133]: call to unsafe function `libc::syscall` is unsafe and requires unsafe block
[2025-05-15 08:08:33]   --> src/uu/sync/src/sync.rs:45:9
[2025-05-15 08:08:33]    |
[2025-05-15 08:08:33] 45 |         libc::syscall(libc::SYS_sync);
[2025-05-15 08:08:33]    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call to unsafe function
```
This PR fixes this warning by moving the function call inside the already existing `unsafe` block used for the non-Android code.
=> sync: move call to unsafe fn to unsafe block

.github/workflows/CICD.yml
I noticed the following error in the `Code Coverage` job (see, for example, https://github.com/uutils/coreutils/actions/runs/15113187214/job/42477260722#step:9:5458):
```
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/selinux-sys-0.6.14/build.rs:258:10:
selinux-sys: Failed to find 'selinux/selinux.h'. Please make sure the C header files of libselinux are installed and accessible: Kind(NotFound)
```
This PR (hopefully) fixes this issue by installing `libselinux1-dev`.
=> ci: install `libselinux1-dev` for coverage job

src/uu/tsort/src/tsort.rs
During my previous refactor PR, a duplcate sorting step was added. 
THis PR fixes the issue.
=> tsort: remove duplicate sorting step

Cargo.lock, Cargo.toml, fuzz/Cargo.lock, src/uu/cat/src/cat.rs, src/uu/cat/src/splice.rs, src/uu/dd/src/dd.rs, src/uu/tee/src/tee.rs, src/uu/wc/src/count_fast.rs, src/uucore/src/lib/features/buf_copy.rs, src/uucore/src/lib/features/buf_copy/linux.rs, src/uucore/src/lib/features/fs.rs, tests/by-util/test_ls.rs
This PR bumps `nix` from `0.29.0` to `0.30.1` and `ctrlc` from `3.4.6` to `3.4.7`. And it adapts the code to API changes in `nix`.
=> Bump `nix` & `ctrlc`, adapt code to API changes in `nix`

Cargo.lock, Cargo.toml, deny.toml, fuzz/Cargo.lock
This PR bumps `fluent` from `0.16.1` to `0.17.0` and `fluent-bundle` from `0.15.3` to `0.16.0`. It also removes `self_cell` from the skip list in `deny.toml`.
=> Bump `fluent` and `fluent-bundle`

src/uu/expr/src/expr.rs, src/uu/expr/src/syntax_tree.rs, tests/by-util/test_expr.rs
Handle the following special cases for regex patterns for `expr` and add tests for them:
- Trailing backslashes
- `$` at the beginning of the regex pattern
=> expr: Handle more special cases for regex pattern

.github/workflows/CICD.yml
Fixes #7977.
See commit message below, I don't fully get what's going on, but... I'm not sure how much that matters really (maybe something wrong with msys...).
We could have done that in the first place to avoid the onig issue... so this doesn't even need to be stacked on top of #7976.
---
The issue referenced has been long fixed, and for reasons not
totally clear to me, blake3 fails after the GCC update (I tried
to dig into this, but couldn't really figure out if this is really
a problem with GCC 15, or with the version provided by MSYS, or
some other side effect of the exact sequence in CI).
Since blake3 CI doesn't do that gcc update (it uses the default gcc ~12
in the github windows image), let's _also_ not do that, and if there's a
real problem with gcc 15+, that'll presumably fail …
=> Reenable windows-latest/x86_64-pc-windows-gnu (and do not update gcc)

Cargo.lock, Cargo.toml, fuzz/Cargo.lock
This PR manually bumps `onig` from `6.4.0` to `6.5.1` as https://github.com/uutils/coreutils/pull/7973 doesn't update `fuzz/Cargo.lock`.
Fixes #7975
=> Bump `onig` from `6.4.0` to `6.5.1`

src/uu/shred/src/shred.rs, tests/by-util/test_shred.rs
Fixes issue #5711.
This PR introduces the `--random-source` feature, and implements it faithfully: Copy the data from the source into the file-to-be-shredded. Note that the "random" data is *not* modified in any way. This is good, because no deterministic transformation can ever increase the entropy in random data; and it also makes it much simpler to verify that `shred` uses the specified source.
Note that the second of the two new tests is broken because the functionality was always broken, but only now becomes more visible. See #7947.
Note that this PR is not yet sufficient to pass `shred-passes.log`. A future PR will have to adjust the test in order to accept our implementation.
Note a final distinction: The GNU implementation also takes the "shuffled" order of passes from the random …
=> shred: implement and test feature --random-source

src/uu/expr/src/syntax_tree.rs, tests/by-util/test_expr.rs
Fix parsing the following special cases for range quantifiers in the regex of the `expr` command.
- `\{,\}` zero or more
- `\{,6\}` six or less
This PR also enables the rest of the ignored `test_bre*` tests and removes redundant escaping of the '*' character.
fixes #7664
=> expr: Fix parsing range quantifiers in regex

.github/workflows/freebsd.yml
I noticed that one of the freebsd jobs hangs occasionally and runs into the 90 min timeout. As the freebsd jobs usually take less than ten minutes to run, I think it makes sense to reduce the timeout to avoid wasting resources. And thus this PR reduces the timeout from 90 min to <del>60</del> 45 min.
=> ci: reduce timeout of freebsd jobs

Cargo.lock, deny.toml
This PR bumps `type-map` from `0.5.0` to `0.5.1` in order to remove `rustc-hash` from the skip list in `deny.toml`.
=> Bump `type-map`

src/uu/expr/src/expr.rs, src/uu/expr/src/syntax_tree.rs, tests/by-util/test_expr.rs
This PR fixes parsing and error reporting for the regex range quantifiers for `expr`. The `\{` token is handled literally when used at the start of the regex or its subexpressions. The following closing braces `\}` are also handled literally until the next `\{` that is not at the start of an expression.
Quote from #8009:
> Normally, `\{` begins a range quantifier like `{n,m}`. However, at the start of the regex or its subexpression (after `\(` or `\|`), there is no preceding item to which the quantifier can be applied. The expr command should handle `\{` literally at the start of the regex or its subexpression.
**Other changes**:
- Remove nonexistent error `UnmatchedClosingBrace`
- The closing brace without a related opening brace is handled literally
- Fix error message for too big range …
=> expr: Fix handling of regex range quantifiers

GNUmakefile
This adds `stty` to `GNUmakefile` and build it by default.
This is [no longer WIP](https://github.com/uutils/coreutils/pull/310).
=> Add stty to GNUmakefile

src/uu/sync/Cargo.toml, src/uu/sync/src/sync.rs
1. Safe wrappers exist for the unix side of things, so let's use those.
1. A function isn't `unsafe` just because it uses `unsafe` code, it's only `unsafe` if it can be invoked in a way that violates safety guarantees.
1. Safety comments shouldn't document why something is `unsafe`, they're for documenting either how to invoke something `unsafe` safely, or why the `unsafe` invocation is actually safe.
=> sync: reduce use of unsafe and improve comments

src/uu/csplit/src/patterns.rs, tests/by-util/test_csplit.rs
This PR fixes two issues related to the use of `\d` in regexes because it matches Unicode digits whereas we only expect ASCII digits.
=> csplit: fix two issues with non ASCII digits

src/uu/sync/src/sync.rs
Removes a stale safety comment I missed (sorry), plus adds some backticks while we're at it.
=> sync: adjust safety comments

.pre-commit-config.yaml
cspell pre-commit hook would fail if the only change was a Cargo.lock change.
This fixes it.
=> .pre-commit-config.yaml: Do not fail cspell if all files are ignored

src/uucore/src/lib/features/utmpx.rs
Fixes https://github.com/uutils/coreutils/issues/7865
We are intentionally calling the stub utmpx functions of musl, in order to achieve behavior parity with GNU coreutils, and in order to be able to ship those utilities for musl libc. Silence those warnings.
See also https://github.com/uutils/coreutils/issues/1361 for details.
=> utmpx: silence musl warnings

src/uu/ln/src/ln.rs
While reviewing #7449 I noticed the following snippet:
```rust
if !target_dir.is_dir() {
return Err(LnError::TargetIsDirectory(target_dir.to_owned()).into());
}
```
This PR fixes the snippet by renaming the error variant to `TargetIsNotADirectory`.
=> ln: rename error variant

src/uucore/src/lib/features/parser/num_parser.rs
This is the latest version in https://github.com/akubera/bigdecimal-rs/pull/148 , but the discussion sort of stalled, this is really complicated math, but this new function is a little bit better than the original (at least I hope so).
--
I think we can close #7708 after this, I'm referencing https://github.com/akubera/bigdecimal-rs/issues/147 so if/when we reach a conclusion there, we can drop this function.
=> uucore: num_parser: Update pow_with_context

src/uu/rm/src/rm.rs
This PR does an "early return" in `uumain` a bit earlier and removes the `else` to get rid of an indentation level. It also sets the "after help" in `uu_app`, instead of `uumain`, like in most other utils. And it removes some unnecessary type information.
=> rm: do "early return" earlier in `uumain`

src/uucore/src/lib/mods/locale.rs
Recent cargo clippy prefers to use if let for single pattern.
For some reason it only triggers on one of the LANG restore case though, but we can just fix them all.
Not completely sure why cargo clippy only complains about this one:
```
error: you seem to be trying to use `match` for destructuring a single pattern. Consider using `if let`
--> src/uucore/src/lib/mods/locale.rs:767:9
|
767 | /         match original_lang {
768 | |             Some(val) => unsafe {
769 | |                 env::set_var("LANG", val);
770 | |             },
771 | |             None => {} // Was already unset
772 | |         }
| |_________^
|
= note: you might want to preserve the comments from inside the `match`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#singl …
```
=> uucore: locale: Use if let instead of match

src/uu/mv/src/mv.rs, tests/by-util/test_mv.rs
Closes #8044
dangling symlinks can now be relocated into a directory without failure, matching GNU coreutils’ behavior.
```log
cargo test mv
Compiling uu_mv v0.1.0 (/home/albin/projects/coreutils/src/uu/mv)
Compiling coreutils v0.1.0 (/home/albin/projects/coreutils)
Finished `test` profile [unoptimized + debuginfo] target(s) in 5.09s
Running unittests src/bin/coreutils.rs (target/debug/deps/coreutils-d0ad6b34a65b65cb)
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
Running tests/test_util_name.rs (target/debug/deps/test_util_name-7b96ec09c97220a7)
Setting UUTESTS_BINARY_PATH=/home/albin/projects/coreutils/target/debug/coreutils
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 8 filtered out; finished …
```
=>  mv:  moving dangling symlinks into directories 

src/uu/stdbuf/build.rs, src/uu/stdbuf/src/libstdbuf/Cargo.toml
libstdbuf is currently compiled as e.g. liblibstdbuf.so, which is confusing. Compile the library as libstdbuf.so instead.
=> stdbuf: avoid double "lib" prefix

.pre-commit-config.yaml
ATTENTION admins:  I don't see pre-commit in the list of actions that ran on this PR - perhaps it was never enabled?  https://pre-commit.ci/
Pre-commits are usually used to minimize busy work by the contributors, e.g., by fixing extra spacing, formatting, etc. This PR adds various basic text file checks to the repo.  I copied these settings from many other projects I maintain - they have proven to be fairly useful. I also made yaml spacing a bit cleaner.
I was a bit surprised it is used for `cargo clippy` because you wouldn't want clippy's auto-fixes to be auto-applied by CI, so usually GitHub workflow simply runs it as a regular step. This is outside of the scope for this PR, but perhaps it should be removed here?
=> Enable common pre-commit.ci fixes

tests/by-util/test_rm.rs
This PR does three trivial things:
* replaces the `test_rm_` prefix used for some test function names with `test_` for consistent naming
* simplifies some tests by using `new_ucmd!`
* merges some imports
=> rm: consistent naming of test functions

src/uu/uname/src/uname.rs
`uname` from `coreutils` prints the OS information last, for example:
```
$ uname -pio
unknown unknown GNU/Linux
```
whereas our `uname` doesn't:
```
$ cargo run -q --features=unix uname -pio
GNU/Linux unknown unknown
```
This PR fixes the issue. It also gets rid of the trailing space in the return of the `display` function and thus makes the `trim_end()` call unnecessary.
=> uname: output OS last

src/uu/tr/src/tr.rs
This PR applies five small improvements:
* removes a `spell-checker:ignore` line
* sets "after help" in `uu_app` instead of `uumain`
* merges some imports
* uses a logical AND (`&&`) instead of a bitwise AND (`&`)
* uses `sets_len == 1` instead of `sets_len < 2` for better readability because in our case `sets_len` can never be `0`
=> tr: some small improvements

src/uu/expr/src/syntax_tree.rs, tests/by-util/test_expr.rs
Fixes #8063
Changed parsing of `expr substr` arguments, so they have a higher precedence than whatever follows. Before those changes the parser was too eager and gave incorrect results when `expr substr` arguments were followed by bash conditional ("!="). The script used to reproduce the issue now gives the correct result.
Looking forward to feedback for this short PR :)
Fixes for `index`, `length`, `match` will come, if actually needed, in future PR(s).
=> expr: fix substr parsing

Cargo.lock, Cargo.toml, fuzz/Cargo.lock, src/uu/tail/src/platform/windows.rs
This PR bumps `windows-sys` from `0.59.0` to `0.60.1` and adapts an import in `tail`.
=> Bump `windows-sys` & adapt to API change

tests/by-util/test_tail.rs
Fixes #4956. thanks to @Absobel for the fix, im just creating PR now because it seems this fix was never merged
=> tail: fix test that disables output in bash shell

src/uu/cat/src/cat.rs, tests/by-util/test_cat.rs
Closes #8068.
The `write_fast` function was silently ignoring read errors due to using `while let Ok(n) = handle.reader.read(&mut buf)` pattern. When `read()` returned an `Err`, the loop would simply exit without propagating the error, potentially leading to incomplete output without any indication of failure.
This PR replaces the while-let pattern with proper match-based error handling that immediately returns read errors using `Err(e) => return Err(e.into())`.
=> cat: add error handling in write_fast function

src/uu/expr/src/syntax_tree.rs, tests/by-util/test_expr.rs
Follow up to #8158
The issue #8063 found in `expr substr` was also present in `index`, `length`, `match`. This PR applies the same fix for those remaining builtin expr functions.
=> expr: fix builtin functions precedence

src/bin/coreutils.rs, tests/test_util_name.rs
fixes #8071
Output is the same as in usage, but no trailing newline:
```bash
coreutils 0.1.0 (multi-call binary)
```
=> feat: add `--version` argument to print main binary version

src/uu/hashsum/src/hashsum.rs, src/uucore/src/lib/features/checksum.rs, tests/by-util/test_hashsum.rs
closes #7906
exact GNU behavior is as follows (the issue wasn't very clear):
if an IO error is encountered (I tested with file not found and permission denied), the binary name, file name, and error are printed to stderr and the program continues. If any errors are found, the program exits with status code 1.
=> hashsum: don't exit early on io errors

src/uu/head/src/head.rs, tests/by-util/test_head.rs
Fixes #7472.
Update to head app when printing all-but-last-n-lines of a file.
Code now checks if the last line of the input file is missing a terminating newline character, and if so prints an extra line in the output. This aligns with GNU-head behavior.
Also made a change to improve performance of this usecase by using an optimized iterator (memchr-iter) for searching through the input file (gives a ~25% improvement for `head -n -100000 ./shakespeare.txt` vs the current mainline tip).
=> head: fix bug with non-terminated files.

src/uu/stty/src/stty.rs, tests/by-util/test_stty.rs
this addition is part of #3859. on almost all platforms, setting asymmetric ispeed/ospeed is not supported, so `stty ispeed 110`, `stty ospeed 110` and `stty 110` all have the exact same effect. still, its useful to add these options which are found in the GNU version.
=> stty: add ispeed/ospeed settings

src/uu/stty/src/stty.rs, tests/by-util/test_stty.rs
fixes #8134. adds a new way to set a control character to undefined, eg `stty intr ''`, which disables the interrupt signal control character.
=> stty: fix mappings with empty string literal args

.cargo/config.toml, Cargo.toml, src/uu/stdbuf/Cargo.toml, src/uu/stdbuf/build.rs, src/uu/stdbuf/src/stdbuf.rs
Fixes https://github.com/uutils/coreutils/issues/6591
"feat_external_libstdbuf": use an external libstdbuf.so for stdbuf instead of embedding it into
the stdbuf binary.
There are 2 use-cases:
1. Installation of uutils-coreutils using cargo install (e.g. from crates.io which supports only "cargo install" as installation method).  In this case, installing libstdbuf.so is impossible, because "cargo install" installs only binary programs (no cdylib), thus libstdbuf.so must be embedded into stdbuf and written to /tmp at runtime.  This is a hack, and may not work on some platforms, e.g. because the SELinux permissions may not allow stdbuf to write to /tmp, /tmp may be read-only, libstdbuf.so may not work at all without SELinux labels, etc.
2. Installation of uutils-coreutils using an external …
=> stdbuf: add feat_external_libstdbuf

tests/by-util/test_tee.rs
Since #1805 is fixed, this test can be enabled now.
There's also a way to pipe output to `/dev/full`, so that part is also fixed.
=> tests/tee: enable no_more_writable test

.vscode/cspell.dictionaries/jargon.wordlist.txt, src/uucore/src/lib/features/fsxattr.rs, tests/by-util/test_ls.rs, util/gnu-patches/tests_ls_no_cap.patch
```
$ strace -e llistxattr,listxattr,getxattr ./target/debug/coreutils ls -lLd l
listxattr("l", 0x1, 0)                  = 24
listxattr("l", "system.posix_acl_access\0", 24) = 24
drwxrwxr-x+ 2 sudhackar sudhackar 4096 Jun 18 16:47 l
+++ exited with 0 +++
```
as compared to no `+`
=> ls: follow symlinks for xattrs, fix #8216

Cargo.lock, Cargo.toml, build.rs
This PR bumps both `phf` and `phf_codegen` from `0.11.2` to `0.12.1` and fixes errors in `build.rs` due to a breaking change in `phf_codegen`.
=> Bump `phf` and `phf_codegen` & fix compilation errors

src/uucore/src/lib/mods/locale.rs
I'm not sure exactly why this is happening, but when I install coreutils with `make install PREFIX=some-prefix`, before this patch coreutils would look in the wrong place for locales - it would look in e.g. "bin/cut/en-US.ftl" instead of in share/locales/cut/en-US.ftl.
This patch fixes the issue, add a test as well.
Fixes #8115.
=> lib/mods/locale: fix locale loading

src/uu/uptime/src/uptime.rs
This PR improves the readability of `uptime_since` by reducing the number of `cfg` attributes and renaming a variable.
=> uptime: improve readability of `uptime_since`

src/uu/dir/src/dir.rs, src/uu/ls/src/ls.rs, src/uu/vdir/src/vdir.rs, src/uu/wc/src/wc.rs, src/uucore/src/lib/features/format/argument.rs, src/uucore/src/lib/features/format/spec.rs, src/uucore/src/lib/features/quoting_style/mod.rs
This MR introduces constants for quoting styles to simplify the declaration of quoting style variables throughout the codebase.
It also changes the interface of `escape_name` family of function to take `QuotingStyle` instead of `&QuotingStyle` as a parameter, because the struct implements `Copy` anyway
=> uucore(quoting_style): Improve quoting style handling

src/uu/od/src/prn_char.rs, tests/by-util/test_od.rs
Fixes #8202
I'm not sure if this fix is complete, because I couldn't reproduce the original behavior of uutils impl with GNU od, so I don't know in which situations the previous implementation was valid (I assume there is/was a reason for implementing it the way it was implemented).
Regardless of the above, this fixes the reported issue. It still lacks localization support, but it works correctly for `LC_ALL=C` as well as `LC_ALL=en_US.UTF-8`.
=> od: fix handling of non-ascii chars

src/uucore/src/lib/features/selinux.rs, src/uucore/src/lib/mods/locale.rs
This PR fixes warnings from the [uninlined_format_args](https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args) lint in some `uucore` unit tests.
=> clippy: fix warnings from `uninlined_format_args` lint

src/uucore/Cargo.toml, src/uucore/src/lib/features/checksum.rs, tests/by-util/test_cksum.rs, tests/uutests/src/lib/macros.rs, tests/uutests/src/lib/util.rs
Fix [#6892](https://github.com/uutils/coreutils/issues/6892)
=> cksum: Fix file quoting on stderr

src/uu/install/src/install.rs
This PR changes the return type of `need_copy` from `UResult<bool>` to `bool`.
=> install: use `bool` as return type of `need_copy`

Cargo.lock, Cargo.toml, fuzz/Cargo.lock, fuzz/Cargo.toml, fuzz/uufuzz/Cargo.toml, src/uu/chmod/Cargo.toml, src/uu/cksum/Cargo.toml, src/uu/factor/Cargo.toml, src/uu/hashsum/Cargo.toml, src/uu/install/Cargo.toml, src/uu/ls/Cargo.toml, src/uu/more/Cargo.toml, src/uu/sync/Cargo.toml, src/uucore/Cargo.toml, tests/benches/factor/Cargo.toml, tests/uutests/Cargo.toml
Try to remove all unused dependencies from various crates
=> chore: remove unused dependencies

src/uu/rm/src/rm.rs, tests/by-util/test_rm.rs
=> rm: fix too long filename corner case

src/uu/timeout/src/status.rs, src/uu/timeout/src/timeout.rs, src/uucore/src/lib/features/process.rs, tests/by-util/test_timeout.rs
fixes #8040 
set a signal handler and terminate child process on receiving SIGTERM.
I'm a bit confused about how to write tests for it, is it appropriate to use `ps` and `kill` in ci?
=> timeout: catch TERM signal

src/uu/stty/src/stty.rs, tests/by-util/test_stty.rs
closes #3859, specifically the `drain`, `line`, `min`, and `time` settings
=> `stty`: special settings

Cargo.toml, src/uu/head/src/parse.rs, src/uu/nohup/src/nohup.rs, src/uu/od/src/parse_formats.rs, src/uu/ptx/src/ptx.rs, src/uu/stty/src/stty.rs
Apparently this causes a slowdown per [docs](https://rust-lang.github.io/rust-clippy/master/index.html#inefficient_to_string).
I used this command and fixed a few remaining manual ones.
```sh
__CARGO_FIX_YOLO=1 cargo clippy --fix --all-targets --workspace --allow-dirty
```
=> chore: cleanup `inefficient_to_string` lint

Cargo.toml, src/uu/cp/src/cp.rs, src/uu/dd/src/progress.rs, src/uu/df/src/table.rs, src/uu/ls/src/ls.rs, src/uu/mv/src/hardlink.rs, src/uu/mv/src/mv.rs, src/uu/nice/src/nice.rs, src/uu/shred/src/shred.rs, src/uu/stdbuf/build.rs, src/uu/stty/src/stty.rs, src/uucore/src/lib/features/format/argument.rs, src/uucore/src/lib/features/format/mod.rs, src/uucore/src/lib/features/selinux.rs, src/uucore/src/lib/mods/locale.rs, tests/by-util/test_cp.rs, tests/by-util/test_date.rs, tests/by-util/test_install.rs, tests/by-util/test_ls.rs, tests/by-util/test_mkfifo.rs, tests/by-util/test_mknod.rs, tests/by-util/test_printf.rs, tests/by-util/test_stdbuf.rs
I used this command, plus some manual fixes:
```sh
__CARGO_FIX_YOLO=1 cargo clippy --fix --all-targets --workspace --all-features --allow-dirty
```
=> chore: fix uninlined_format_args lint

.vscode/cspell.dictionaries/workspace.wordlist.txt, Cargo.lock, Cargo.toml, src/uucore/src/lib/features/fs.rs, tests/by-util/test_tr.rs
This pull request fixes a regression introduced in 3e4221a4 that causes `tr` to fail when used with ksh93 sockets (previous bug report: https://github.com/uutils/coreutils/issues/7658).
The test used for determining if a file descriptor tested with `fstat` points to a directory is traditionally done by using the `S_IFMT` mask[^1][^2], e.g.:
```C
#define S_ISDIR(m)	(((m) & S_IFMT) == S_IFDIR)
```
In Rust, this translates to `m & libc::S_IFMT == libc::S_IFDIR`. `is_stdin_directory()` uses `has!(mode, S_IFDIR)`, which is **not** equivalent and causes non-directory sockets to be incorrectly recognized as directories. This causes `tr` to break when used with all sockets created with `socketpair`, including ksh93 pipes[^3]. Below is an example Rust program demonstrating why the current check is …
=> tr: Fix regression causing read error with sockets

src/uu/stty/src/flags.rs, src/uu/stty/src/stty.rs, tests/by-util/test_stty.rs
fixes for #3860. i added the function `combo_to_flags()` which takes a combination name as a string and decomposes the combination into the individual settings. this function returns a vec of all the flags that correspond to the combination, which are then appended to the `valid_args` vec that is used during arg parsing. one of the combinations is not fully complete yet, as it requires functionality in #3859, which i will tackle next.
=> stty: add combination settings

src/uu/tail/src/tail.rs, tests/by-util/test_tail.rs, tests/uutests/src/lib/util.rs
~~Fixes #4965.~~
~~The original issue can be reproduced with:~~
Edit: I misunderstood #4965, but it's related.
The incorrect handling of broken pipe can be reproduced with:
```
$ echo "oneline" > file
$ tail file | false
$
$ coreutils tail file | false
tail: Broken pipe
$
```
=> tail: handle broken pipe gracefully

Cargo.toml, src/uu/od/src/formatteriteminfo.rs
auto-derived clone generates identical assembly: https://rust.godbolt.org/z/GvenxKcKo
=> chore: fix expl_impl_clone_on_copy lint

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs
If the source is a symbolic link pointing at a directory, --parents was ignored, as we entered the "copy as directory" code path.
Fixes: #8330
=> cp: Fix --no-dereference --parents with symlink source

src/uu/echo/src/echo.rs, tests/by-util/test_echo.rs
This PR shows the version info when `--version` is the only argument and `POSIXLY_CORRECT` is not set. It matches the behavior of GNU `echo`:
```
$ ../gnu/src/echo --version
echo (GNU coreutils) 9.7-modified
Copyright (C) 2025 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by Brian Fox and Chet Ramey.
$ POSIXLY_CORRECT=1 ../gnu/src/echo --version
--version
```
The PR also renames a test function to make the naming more consistent.
=> echo: show version when `--version` is the only argument

src/uu/cat/src/cat.rs, tests/by-util/test_cat.rs, tests/by-util/test_tail.rs
Fixes #6876.
I was able to reproduce the original issue with both:
```
$ echo a | gzip -c > f.gz
$ perl -e '
use POSIX qw(dup2);
$SIG{PIPE} = "DEFAULT";
pipe my ($read_end, $write_end);
dup2 fileno $write_end, 1;
close $read_end;
exec "cat", "f.gz", "f.gz";
'
cat: f.gz: EPIPE: Broken pipe
cat: f.gz: EPIPE: Broken pipe
```
and:
```
$ cat f.gz | false
cat: f.gz: EPIPE: Broken pipe
```
This PR fixes both cases.
Preparing yet another similar fix (previous ones: https://github.com/uutils/coreutils/pull/8327 and https://github.com/uutils/coreutils/pull/8312) I wonder if it makes sense to fix it for all binaries in a single place (at least for non-windows platforms), like in `uucore::main` macro in `src/uucore_procs/src/lib.rs`:
```
// disable rust signal handlers (otherwise processes don't dump …
```
=> cat: handle broken pipe gracefully

src/uu/echo/src/echo.rs, src/uu/printf/src/printf.rs, src/uucore/src/lib/features/checksum.rs, src/uucore/src/lib/features/extendedbigdecimal.rs, src/uucore/src/lib/features/format/argument.rs, src/uucore/src/lib/features/format/mod.rs, src/uucore/src/lib/features/format/spec.rs, src/uucore/src/lib/features/parser/num_parser.rs, src/uucore/src/lib/lib.rs, tests/by-util/test_printf.rs, util/why-error.md
Rebased #7209 yet again (I "had" to squash 2 commits together to make the rebase slightly easier..), I'll also attempt to apply the changes I suggested.
--
Rebases https://github.com/uutils/coreutils/pull/6812 on https://github.com/uutils/coreutils/pull/7208.
EDIT: Now also includes a commit from me to pass the printf-mb GNU test, as well as a few other odds and ends. Fixes https://github.com/uutils/coreutils/issues/6804.
=> printf: accept non-UTF-8 input in FORMAT and ARGUMENT arguments

src/uu/stty/src/stty.rs, tests/by-util/test_stty.rs
=> stty: print non-default control characters

src/uu/chroot/locales/en-US.ftl, src/uu/chroot/locales/fr-FR.ftl, src/uu/du/locales/en-US.ftl, src/uu/du/locales/fr-FR.ftl, src/uu/nohup/locales/en-US.ftl, src/uu/nohup/locales/fr-FR.ftl
This PR replaces some `\n` with a new line in ftl files. It should make [tests/du/files0-from.pl](https://github.com/coreutils/coreutils/blob/master/tests/du/files0-from.pl) pass.
=> l10n: replace `\n` with a new line in ftl files

.cargo/config.toml, src/uucore/src/lib/lib.rs
This fixes out-of-tree builds which are using --manifest-path and ignoring .cargo/config.toml because of https://github.com/rust-lang/cargo/issues/2930 :
```
git clone https://github.com/uutils/coreutils.git
mkdir test && cd test
cargo build --manifest-path=../coreutils/Cargo.toml
```
This also fixes installation of coreutils from crates.io, which also ignores .cargo/config.toml:
```
cargo install coreutils --locked
```
Using `option_env` is not possible because `concat!` needs a string literal. I don't see a need to change the project name using an environment variable, so let's keep things simple and simply remove it to fix this bug.
Fixes https://github.com/uutils/coreutils/issues/7992
=> remove PROJECT_NAME_FOR_VERSION_STRING

util/build-gnu.sh, util/why-skip.md
See #7252, both `timeout` and `yes` reset the SIGPIPE handler (actually, the Rust core does that), leading to trap_sigpipe_or_skip_ test:
```
(trap '' PIPE && timeout 10 yes |:) 2>&1 | grep 'Broken pipe'
```
to fail, causing 4 tests to be skipped.
I believe the intent here is to check if the OS supports SIGPIPE, so it probably makes sense to use System's timeout/yes here, and run the tests anyway (which, happen to pass).
=> util/build-gnu.sh: Bypass timeout/yes SIGPIPE handling bug

src/uu/basename/src/basename.rs
Looks like this is not needed, and Pathbuf already behaves as expected.
Tiny simple PR, I'll stack OsStr changes on top.
=> basename: Simply logic, do not trim path separators `/`

src/uu/basename/src/basename.rs, tests/by-util/test_basename.rs
The test was not really testing for the right thing. If a non-unicode
string is passed, the basename should be printed as-is.
This will allow us to handle non-Unicode strings correctly.
The logic needs to be updated, next.
=> basename: Handle non-unicode parameters

src/uu/cp/src/cp.rs
Fixes #8383, and would fix `tests/cp/preserve-gid` if we didn't hit #8382 (I added `+rx` permission to my home directory to work around the issue).
---
For example, if a file with ownership `root:wheel` is copied with
`-p`, we expect the copy to have ownership `$USER:wheel`
(assuming `$USER` is part of `wheel` group)
It's not possible to add a unit test for this, as it requires a
file with non-$USER ownership, which can only be created by root
(or another user).
=> cp: Try to change gid only if changing uid+gid fails

util/build-gnu.sh
Partial fix for `tests/cp/preserve-gid`, and also a small refactoring of `util/build-gnu.sh`.
I'll file a bug for the next issue.
---
path_prepend_ sets $abs_path_dir_, but the sed command above removes
it. Set it manually instead.
Fixes part of tests/cp/preserve-gid.
Patching tests/local.mk instead of Makefile makes it a bit easier
to see what has been modified with a `git diff`, and Makefile
is generated anyway.
=> tests/cp/preserve-gid: Partial fix

.github/workflows/CICD.yml, GNUmakefile
When creating the `target` directory, `cargo` also creates `target/CACHEDIR.TAG` which is important for backup tools to know to ignore the directory.
This doesn't happen if something else creates the `target` directory (e.g. `locales` Makefile target).
Swap the execution order to fix this.
=> Makefile: Copy locales _after_ build

src/uu/du/Cargo.toml, src/uu/du/src/du.rs, src/uu/ls/Cargo.toml, src/uu/ls/src/ls.rs, src/uucore/src/lib/features/fsext.rs, tests/by-util/test_du.rs
Was meant to be a maybe-not-that-useful refactoring, uncovered a bug in `du`...
`ctime` is _change_ time, not modification time.
```
$ stat date_test
File: date_test
...
Access: 2015-05-15 00:00:00.000000000 +0800
Modify: 2016-06-16 00:00:00.000000000 +0800
Change: 2025-07-27 10:34:50.223190416 +0800
Birth: 2025-07-27 10:34:33.814131325 +0800
$ du --time=ctime date_test 
0	2025-07-27 10:34	date_test
$ cargo build -p uu_du && ./target/debug/du --time=ctime date_test 
0	2016-06-16 00:00	date_test
```
---
It turns out `du` used to test for the wrong thing, `ctime` is
the change timestamp, not creation time.
We have to rely on a regex again, as the change timestamp is the
current time.
Easier to just move the change time logic to another function.
We assume that the string has been validated …
=> `du`/`ls`: Unify file metadata time handling

src/uu/stat/locales/en-US.ftl, src/uu/stat/locales/fr-FR.ftl
Arguably this should be part of the CI, but I'm not sure how to run it outside of precommit.
=> stat/locales: Fix fluent_linter errors

src/uu/pwd/src/pwd.rs
This pull request proposes a minor stylistic simplification for the `physical_path` function in the `pwd` utility.
The current implementation is perfectly correct and performant and correctly handles the platform-specific behaviors of `env::current_dir()`. It correctly avoids a redundant `canonicalize()` call on Unix while applying it on other platforms like Windows where it's necessary.
This PR suggests a small refactor to reduce code duplication. By calling `env::current_dir()` once and then using `#[cfg]` blocks to apply the `canonicalize()` call only where needed, the function becomes slightly more DRY.
Before:
```rust
fn physical_path() -> io::Result<PathBuf> {
// std::env::current_dir() is a thin wrapper around libc::getcwd().
// On Unix, getcwd() must return the physical path:
// …
```
=> style(pwd): simplify physical_path implementation

src/uu/who/src/platform/unix.rs, src/uu/who/src/who.rs
This PR renames `runlvline` to `runlevel_line` for better readability.
=> who: rename var, cleanup spell-checker:ignore

tests/by-util/test_date.rs
See:
https://data.iana.org/time-zones/tzdb/backward
=> date: update deprecated TZ

src/uu/mkdir/src/mkdir.rs
This pull request refactors the argument parsing for the `mkdir` utility on the `--mode` (`-m`) option.
Previously, the utility relied on a manual function (`strip_minus_from_mode`) to process mode values that begin with a hyphen (e.g., `-rwx`). This required manipulating the raw argument list before it was parsed by `clap`.
This change removes the manual parsing logic and uses `clap`'s built-in `.allow_hyphen_values(true)` setting instead. This approach is cleaner, more robust, and relies directly on the features of the argument parsing library.
* Removed the `strip_minus_from_mode` function and its related logic.
* Updated the `clap` argument for `--mode` to use `.allow_hyphen_values(true)`.
* Refined the `uumain` and `get_mode` functions by removing the now-unnecessary variables and …
=> refactor(mkdir): Simplify mode argument parsing

Cargo.lock, src/uu/du/src/du.rs, src/uu/ls/src/ls.rs, src/uu/stat/Cargo.toml, src/uu/stat/src/stat.rs, src/uucore/src/lib/features/fsext.rs, src/uucore/src/lib/features/time.rs
Mostly common code elimination, and fix a crash if a file change time (ctime) is <1970 (not a terribly common thing ,-P)
---
Useful for archaeologists and time travellers, do not crash if
ctime is before 1970.
Creating a file with such a change time is a bit challenging
(touch can't change that), so we can't easily add end-to-end
tests.
Steps to create a filesystem with a file `x` with birth/change
time in 1960.
```
dd if=/dev/zero bs=100M count=0 seek=1 of=ext4
mkfs.ext4 ext4
sudo mount ext4 mnt
touch mnt/x
umount mnt
echo "set_inode_field x ctime 196001010101" | debugfs -w ext4
echo "set_inode_field x ctime_extra 1234" | debugfs -w ext4
echo "set_inode_field x crtime 196001010101" | debugfs -w ext4
echo "set_inode_field x crtime_extra 0x123400" | debugfs -w ext4
sudo mount ext4 mnt
``` …
=> `stat`: Convert to use `uucore` functions

tests/by-util/test_pr.rs
A small refactoring to improve the readability and to get rid of one `unwrap_or_default()` call.
=> pr: reduce nesting to improve readability of `file_last_modified_time_format()`

src/uucore/src/lib/mods/locale.rs
Looks like there is a CI coverage gap...
cargo +stable clippy --workspace --all-targets --all-features -- -D warnings
```
error: variables can be used directly in the `format!` string
--> src/uucore/src/lib/mods/locale.rs:750:17
|
750 |                 eprintln!("Init localization failed: {}", e);
|                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
= note: `-D clippy::uninlined-format-args` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::uninlined_format_args)]`
help: change this to
|
750 -                 eprintln!("Init localization failed: {}", e);
750 +                 eprintln!("Init localization failed: {e}");
|
error: …
```
=> uucore: locale: Fix clippy warning

deny.toml
This PR removes version `0.48.0` of `windows-sys` and its dependencies from the skip list as those dependencies have been removed in https://github.com/uutils/coreutils/pull/8436
=> deny.toml: remove old `windows-sys` version from skip list

tests/by-util/test_more.rs
Added cleanup in test_alive to ensure all spawned processes are terminated on successful test execution.
This also fixes a race condition that could occur: the check for process is_alive might be executing while more is still parsing the arguments.
Fixes #8429
=> more: tests: cleanup processes in test_valid_arg

.github/workflows/CICD.yml, tests/by-util/test_install.rs
This PR uses the `macos-latest` image instead of `macos-13` because GitHub [announced](https://github.blog/changelog/2025-07-11-upcoming-changes-to-macos-hosted-runners-macos-latest-migration-and-xcode-support-policy-updates/#macos-13-is-closing-down) its retirement:
> The macOS 13 hosted runner image is closing down, following our [N-1 OS support policy](https://github.com/actions/runner-images?tab=readme-ov-file#software-and-image-support). This process will begin September 1, 2025, and the image will be fully retired on November 14, 2025.
=> ci: use `macos-latest` instead of `macos-13`

src/uucore/src/lib/features/format/num_format.rs
Optimizing for the `%g` printf format. I don't particularly care about the usecase below, but I'm thinking of moving `od` to the common formatter, where those optimizations would be welcome.
We're still 20% away from coreutils, but this picks some of the low hanging fruits.
```
cargo build --release -p uu_seq && hyperfine -L seq ./target/release/seq,seq,./seq.main "{seq} -f "%g" 0 1e-9 1e-3 > /dev/null"
Finished `release` profile [optimized] target(s) in 0.13s
Benchmark 1: ./target/release/seq -f %g 0 1e-9 1e-3 > /dev/null
Time (mean ± σ):     169.5 ms ±   3.3 ms    [User: 168.0 ms, System: 1.0 ms]
Range (min … max):   164.4 ms … 174.7 ms    17 runs
Benchmark 2: seq -f %g 0 1e-9 1e-3 > /dev/null
Time (mean ± σ):     138.8 ms ±   4.9 ms    [User: 136.7 ms, System: 1.6 ms]
Range (min … …
```
=> uucore: num_format: Optimize `format_float_shortest`

src/uu/chcon/src/chcon.rs, src/uu/chcon/src/fts.rs, src/uu/cp/src/copydir.rs, src/uu/csplit/src/csplit.rs, src/uu/cut/src/cut.rs, src/uu/df/src/df.rs, src/uu/install/src/install.rs, src/uu/mktemp/src/mktemp.rs, src/uu/nohup/src/nohup.rs, src/uu/od/src/formatter_item_info.rs, src/uu/od/src/input_decoder.rs, src/uu/od/src/od.rs, src/uu/od/src/output_info.rs, src/uu/od/src/prn_float.rs, src/uu/runcon/src/runcon.rs, src/uu/sort/src/chunks.rs, src/uu/sort/src/merge.rs, src/uu/split/src/split.rs, src/uu/stat/src/stat.rs, src/uu/stty/src/stty.rs, src/uu/tail/src/follow/files.rs, src/uu/wc/src/utf8/read.rs, src/uu/wc/src/wc.rs, src/uucore/src/lib/features/checksum.rs, src/uucore/src/lib/features/selinux.rs, src/uucore/src/lib/lib.rs, tests/by-util/test_env.rs, tests/uutests/src/lib/util.rs
This PR fixes a bunch of clippy warnings introduced with Rust `1.89`. Most are related to the [mismatched lifetime syntaxes lint](https://blog.rust-lang.org/2025/08/07/Rust-1.89.0/#mismatched-lifetime-syntaxes-lint) described in the announcement. Other warnings are from the [needless_return](https://rust-lang.github.io/rust-clippy/master/index.html#needless_return), [manual_let_else](https://rust-lang.github.io/rust-clippy/master/index.html#manual_let_else), [unnecessary_unwrap](https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_unwrap), and [cloned_ref_to_slice_refs](https://rust-lang.github.io/rust-clippy/master/index.html#cloned_ref_to_slice_refs) lints. 
Additionally, in `od` I suppressed warnings from the `unpredictable_function_pointer_comparisons` Rust lint …
=> clippy: fix warnings introduced with Rust `1.89`

src/uu/tr/BENCHMARKING.md, src/uu/tr/src/operation.rs
Results:
```
$ dd if=/dev/zero bs=1M count=10 | tr '\0' 'x' > 10mb_input
$ hyperfine --export-markdown tr.md --warmup 3 \
'/usr/bin/tr a b < 10mb_input > /dev/null' \
'./target/release/tr a b < 10mb_input > /dev/null' \
'./target/release/tr.previous a b < 10mb_input > /dev/null'
Benchmark 1: /usr/bin/tr a b < 10mb_input > /dev/null
Time (mean ± σ):       6.5 ms ±   0.7 ms    [User: 4.1 ms, System: 2.4 ms]
Range (min … max):     5.1 ms …  10.3 ms    520 runs
Benchmark 2: ./target/release/tr a b < 10mb_input > /dev/null
Time (mean ± σ):      10.7 ms ±   0.8 ms    [User: 7.9 ms, System: 2.7 ms]
Range (min … max):     9.7 ms …  15.3 ms    271 runs
Benchmark 3: ./target/release/tr.previous a b < 10mb_input > /dev/null
Time (mean ± σ):      61.2 ms ±   2.2 ms    [User: 58.5 ms, System: 2.5 ms] …
```
=> Improve tr performances (Closes: #8439) 

tests/by-util/test_cp.rs
For unclear reason, this is a source of test flakiness (#8453).
---
Seems better than continuously have to click retry on so many PR... Not sure what's wrong though ,-(
=> test_cp: On MacOS, ignore tests that use /dev/fd/0

src/uu/chmod/src/chmod.rs
This PR removes a Windows-specific function because `chmod` is unix-only. It also removes some unnecessary `cfg` attributes.
=> chmod: remove Windows function & unnecessary cfgs

src/uu/sort/src/sort.rs, tests/by-util/test_sort.rs
found by @cakebaker in https://github.com/uutils/coreutils/pull/8431
=> sort: adjust the behavior of 'sort --output --file-with-dash' to match GNU's

src/uu/cp/src/cp.rs, tests/by-util/test_cp.rs, tests/uutests/src/lib/util.rs
=> cp: fix recursive socket file copy

tests/by-util/test_users.rs
This PR fixes two "unused import" warnings that show up in the FreeBSD job in the CI (see, for example, https://github.com/uutils/coreutils/actions/runs/17008637021/job/48221643186#step:5:4574)
=> users: fix unused imports in tests on FreeBSD

src/uu/head/locales/en-US.ftl, src/uu/head/locales/fr-FR.ftl, src/uu/head/src/head.rs
This PR removes the `BadEncoding` variant of `HeadError`. It's currently marked as `#[allow(dead_code)]` and not used anymore.
=> head: remove `BadEncoding` variant of `HeadError`

src/uu/head/src/head.rs
This PR refactors `uumain`: it replaces a `match` with `map_err` and renames some vars. It also removes the `_NAME` suffix from the option constants.
=> head: refactor `uumain`

src/uu/rm/src/rm.rs
This PR contains three trivial changes:
- it fixes an unused var warning on non-(unix & windows) platforms
- it replaces a `#[cfg(not(windows))]` with `#[cfg(unix)]]`
- and it groups all `handle_writable_directory` functions together by moving the `path_is_current_or_parent_directory` function
=> rm: fix unused var warning on non-(unix & windows)

src/uu/nl/src/helper.rs, src/uu/nl/src/nl.rs, tests/by-util/test_nl.rs
This PR uses `OsString` for `--number-separator` in order to support number separators with non-utf-8 characters to match the behavior of GNU `nl`.
The PR also renames a test function for consistency purposes.
=> nl: use `OsString` for `--number-separator`

tests/by-util/test_factor.rs
This PR fixes two "unused import" warnings that show up when running `cargo test --features=factor --no-default-features`.
=> factor: fix two "unused import" warnings in test

src/uu/cksum/src/cksum.rs
This PR applies two trivial refactorings:
* it does an earlier continue if a provided path is a directory to avoid creating an unused `BufReader`
* it renames a var `not_file` to `is_stdin` to avoid double negation when using `!`
=> cksum: two small refactorings

tests/by-util/test_chmod.rs
run ssh, it might break with:
```
---- test_chmod::test_chmod_umask_expected stdout ----
thread 'test_chmod::test_chmod_umask_expected' panicked at tests/by-util/test_chmod.rs:240:5: assertion `left == right` failed: Unexpected umask value: expected 022 (octal), but got 002. Please adjust the test environment.
left: 2
right: 18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> chmod: make a test environment-agnostic

src/uu/who/src/platform/unix.rs, tests/by-util/test_who.rs, tests/uutests/src/lib/util.rs
=> who: honor locale settings

src/uu/stty/src/stty.rs
The expect() calls cause stty to panic if we are not attached to a tty with ENOTTY. This in turn causes shells to print messages "Aborted (core dumped)", breaking tests that assume empty stderr [with normal stderr of the process being redirected].
Refactor the code to use .and_then() and .map_err() to map the resulting nix Errno into a boxed UIoError.
=> Avoid panic in stty

src/uu/nl/src/helper.rs, src/uu/nl/src/nl.rs, tests/by-util/test_nl.rs
This PR adds support for non-UTF8 values for `-d`/`--section-delimiter`.
=> nl: allow non-UTF8 section delimiter

src/uucore/build.rs
This PR renames a function from `embed_all_utilities_locales` to `embed_all_utility_locales` to be consistent with another function named `embed_static_utility_locales`.
=> uucore/build.rs: rename function

tests/by-util/test_touch.rs
This PR adapts the expected error message in a test on Windows. It should make the CI green again.
=> touch: adapt expected error message in test

src/uu/cp/src/platform/linux.rs
Conceptually, just makes the code a little bit easier to read.
=> Replace casting to Ioctl with a const from libc

src/uu/pinky/locales/en-US.ftl, src/uu/pinky/locales/fr-FR.ftl, src/uu/pinky/src/pinky.rs, src/uu/pinky/src/platform/unix.rs, tests/by-util/test_pinky.rs
Fixes: https://github.com/uutils/coreutils/issues/8667
=> pinky: add --lookup flag

src/uu/date/locales/en-US.ftl, src/uu/date/src/date.rs, tests/by-util/test_date.rs
Implements the `--resolution` flag for `date`. On unix platforms this uses the posix function `clock_getres`. I could not find an equivalent syscall on windows, however every windows operating system since at least Windows 2000 has used a resolution of 100ns, so I decided to hardcode that as the returned resolution. 
I treated the `--resolution` flag as a date source like it is in GNU date, this allows other formatting flags to apply to the output of the `--resolution` flag. I also tried to make sure the implementation would interact well with a future implementation of the `--debug` flag. 
As a bit of a drive by I also add conflicts_with annotations to the four date source options, this is to make the GNU date behaviour of failing when multiple date sources are specified. However, I'm …
=> date: implement `--resolution` flag

src/uu/sort/locales/en-US.ftl, src/uu/sort/locales/fr-FR.ftl, tests/by-util/test_sort.rs
An expected error message in the GNU test `sort-files0-from` changed slightly in version `9.8`. This PR adapts our error message to make the test pass again.
=> sort: adapt error message to pass `sort-files0-from`

src/uu/tsort/src/tsort.rs
Hi. 
I was benchmarking several tools and found there some low hanging minor optimizations for input processing that can be done:
- Don't lookup in hashmap twice
- Don't allocate extra arrays of input strings
=> Remove extra lookups and memory allocations from tsort graph construction

src/uu/pinky/src/pinky.rs, tests/by-util/test_pinky.rs
While reviewing https://github.com/uutils/coreutils/pull/8669 I noticed a unit test among the integration tests. This PR moves the unit test to `pinky.rs`. It also cleans up the imports in the test file and removes an unnecessary import on OpenBSD.
=> pinky: move unit test away from the integration tests

src/uucore/src/lib/features/systemd_logind.rs
Fixes: https://github.com/uutils/coreutils/issues/8670
=> who/pinky: fix systemd local host

src/uu/numfmt/benches/numfmt_bench.rs, src/uu/sort/benches/sort_bench.rs, src/uu/sort/benches/sort_locale_bench.rs, src/uucore/src/lib/features/benchmark.rs
```
/home/runner/work/coreutils/coreutils/target/codspeed/instrumentation/uu_numfmt/numfmt_bench: numfmt-error-invalid-suffix
/home/runner/work/coreutils/coreutils/target/codspeed/instrumentation/uu_sort/sort_bench: sort-cannot-read
```
=> fix some benchmark (some of them were failing)

src/uu/ls/src/ls.rs
Redox OS now has getgrgid as seen in https://gitlab.redox-os.org/redox-os/relibc/-/blob/master/src/header/grp/mod.rs?ref_type=0636af21a468f04971bad11eb4571bcb94fdfa81#L253, so we can remove this special handling. This allows the group name to show up on Redox OS, instead of just the group id.
=> ls: remove unnecessary getgrgid handling for Redox OS

src/uu/ptx/src/ptx.rs, tests/by-util/test_ptx.rs
This PR fixes a compatibility bug where `ptx` incorrectly formatted references when the input source was standard input (stdin). The change ensures the output matches GNU `ptx`'s behavior for all reference modes (`-A` and `-r`).
When processing stdin, `uutils/ptx` was generating references with a hyphen `"-"` as a placeholder for the filename (e.g., `"-:1"` for auto-references). The correct GNU `ptx` behavior is to use an empty string for the filename part in this scenario (e.g., `":1"`).
This inconsistency affects any workflow that relies on parsing `ptx`'s output when using stdin.
- The reference generation logic was updated to specifically check if the input source is stdin.
- When the input is stdin, an empty string is now used for the filename portion of the reference, ensuring …
=> fix(ptx): Correct reference format for stdin

src/uu/unexpand/src/unexpand.rs
```
hyperfine --warmup 3 "/usr/bin/unexpand moby64.txt"                     "./target/release/coreutils.prev unexpand moby64.txt" "./target/release/coreutils unexpand moby64.txt"
Benchmark 1: /usr/bin/unexpand moby64.txt
Time (mean ± σ):      95.8 ms ±   3.8 ms    [User: 81.1 ms, System: 14.6 ms]
Range (min … max):    89.6 ms … 104.8 ms    31 runs
Benchmark 2: ./target/release/coreutils.prev unexpand moby64.txt
Time (mean ± σ):     952.3 ms ±   3.0 ms    [User: 846.4 ms, System: 105.6 ms]
Range (min … max):   949.4 ms … 958.1 ms    10 runs
Benchmark 3: ./target/release/coreutils unexpand moby64.txt
Time (mean ± σ):      63.7 ms ±   2.2 ms    [User: 52.9 ms, System: 10.7 ms]
Range (min … max):    60.8 ms …  70.2 ms    46 runs
Summary
./target/release/coreutils unexpand moby64.txt ran
1.50 …
```
=> unexpand: improve performances (1.50 faster than GNU)

.github/workflows/CICD.yml, GNUmakefile
Allow to replace `ln-fs` by `make LN=ln` (Minimized replacement for #8790 and #7928 ).
Reasons:
1. Windows does not allow symlinking by default. It blocks to build this as single binary at MSYS2.
2. AppArmor needs proper argv[0] .
~I have no idea what test should we have for this feature.~
=> Allow to replace ln -fs and hardlink on Windows by default

src/uu/unexpand/src/unexpand.rs
This PR removes an unnecessary condition I overlooked while reviewing https://github.com/uutils/coreutils/pull/8815.
=> unexpand: remove unnecessary condition

Cargo.toml, src/uu/cat/src/cat.rs, src/uu/comm/src/comm.rs, src/uu/cp/src/cp.rs, src/uu/df/src/table.rs, src/uu/env/src/env.rs, src/uu/head/src/take.rs, src/uu/more/src/more.rs, src/uu/mv/src/hardlink.rs, src/uu/paste/src/paste.rs, src/uu/stat/src/stat.rs, src/uu/tsort/src/tsort.rs, src/uucore/src/lib/features/buf_copy/common.rs, src/uucore/src/lib/features/checksum.rs, src/uucore/src/lib/features/extendedbigdecimal.rs, src/uucore/src/lib/features/format/escape.rs, src/uucore/src/lib/features/format/mod.rs, src/uucore/src/lib/features/fsext.rs, src/uucore/src/lib/features/parser/num_parser.rs, src/uucore/src/lib/features/safe_traversal.rs, src/uucore/src/lib/features/selinux.rs, src/uucore/src/lib/features/systemd_logind.rs, src/uucore/src/lib/features/utmpx.rs, src/uucore/src/lib/lib.rs, src/uucore/src/lib/mods/clap_localization.rs, src/uucore/src/lib/mods/locale.rs
This PR moves the [use_self](https://rust-lang.github.io/rust-clippy/stable/index.html#use_self) lint from `lints.clippy` to `workspace.lints.clippy` in `Cargo.toml` and fixes its warnings.
=> clippy: move `use_self` lint to workspace lints
